### ISSUE TITLE
UX issue with inviting users

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#100]
@ilmartyrk @anettlinno I just tested inviting myself to a public group to test something for the HC texts, and found that I accidentally didn't send the invite. 

This is because I typed in the email address, and clicked "Save". As far as I was concerned, this should have meant the invite was sent. 

I went back to check because I know such misunderstandings happen with the platform, and as I'm familiar with the platform I saw instantly that I hadn't done the "press enter to add". But I think most people would be assuming their invite was sent and go happily on their way (with the person/s "invited" never actually receiving the invite).  

Needs some UX consideration I think (a quick fix perhaps for now - i.e. a pop-up explaining the problem if they try and save without inviting anyone): 

![image](https://user-images.githubusercontent.com/61320526/228008056-29dbd5b8-0ef3-401e-903e-b59fe54e2068.png)

**Comment by anettlinno** [comment]
@BeccaMelhuish this is well-known issue for me as well and just today I experienced the same problem. In mobile view we don´t even have "Press enter to add" button. There is only "Save" but after pushing it, nothing happens. 

![Screenshot_20230524_132900_Chrome](https://github.com/citizenos/citizenos-fe/assets/45175679/37bdde99-82ab-4d09-be2a-5019a24f6e45)

@kevincrepin @ilmartyrk any good ideas about how to fix this UX problem?

**Comment by anettlinno** [comment]
Triage 85. Replicated the issue and discovered that topic invite and group invites are different. In topic invite system will display email in drop-down menu where User have to click enter or link which is good UX. Let´s use topic invitation design in group invite. 
If User has not entered any emails then "Save" button should be inactive as well.

<img width="365" alt="Invite users" src="https://github.com/citizenos/citizenos-fe/assets/45175679/198ec47d-4348-4e7a-afdc-654f3fd9799a">

Also fix the mobile view. 

Est. dev. time 30 min. Sending it TO DO.
