### ISSUE TITLE
Discussion: Moderation reason shows original reason not moderators reason

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1001]
Something for the moderation review when it comes, this is showing my original reason for reporting the argument to admin, but should it not show the moderators reason for approving the moderation? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1a08c878-3e9d-48a5-93ee-96478a74a7e3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish there was an issue with moderation form the didn't post the moderators reasons properly
