### ISSUE TITLE
Discussion: past argument headings appear

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1003]
Low priority, but should these appear? Doesn't seem that helpful to me in this context, and a bit random which ones show (I think).. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/783c0b79-b485-4ae8-82b8-6fc05f920f06)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is rather browser specific thing, but will add a fix
