### ISSUE TITLE
Discussion: Character limit duplicated and 2 different numbers

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1004]
Isn't needed twice (not sure which is as per the design?) and the two numbers don't match:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a9ff2c31-006f-4779-ab10-cf850c7f2af4)

**Comment by ssin1901** [comment]
Fixed (see screenshot) but will wait on an update about #1109 before closing
<img width="1411" alt="Screenshot 2024-04-19 at 21 42 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1353d8e1-0a84-47a4-b384-a9c332882b83">

**Comment by ssin1901** [comment]
Fixed and closing
