### ISSUE TITLE
Discussion: Wording for removed replies - should be contribution

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1006]
Low priority, but some wording change needed here. 

This is a reply, not an argument, and a grammar issue too. So should be this (to cover both argument and reply): 

"This contribution was removed by its creator"

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dfa7e1e8-64e4-4af6-8e50-74f3518e966a)

Same for when it has been hidden by moderator:

"This contribution" rather than argument, so that it works for both arguments and replies.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ce29f9a1-4a4b-4481-b0dd-9f12b6d3332b)

**Comment by ilmartyrk** [comment]
Changed argument to contribution in all these texts

```"ARGUMENT_HAS_BEEN_DELETED_BY": "This contribution has been deleted by user {{usersFullName}}",
      "ARGUMENT_HAS_BEEN_DELETED_BY_MODERATOR": "This contribution has been deleted by user {{usersFullName}} (moderator)",
      "ARGUMENT_WHY": "Why?",
      "ARGUMENT_VIEW_ARGUMENT_ANYWAY": "View contribution anyway",
      "ARGUMENT_FOUND_INAPPRIOPRIATE_BY": "This contribution was found inappropriate by user <b>{{usersFullName}}</b>",
      "ARGUMENT_CREATOR_REMOVED_ARGUMENT": "This contribution was removed by its creator",
```

**Comment by ssin1901** [comment]
Seems to be changed (screenshot1) and closing.
<img width="1440" alt="Screenshot 2024-04-22 at 19 01 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/52e3eb47-80fa-4b89-abb4-40b1dfd21613">
