### ISSUE TITLE
Topic: Editors shouldn't be able to see option to edit rights

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1007]
Not urgent, but as an editor when I go here, it looks to me like I can change people's rights. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0292fabd-0963-412f-9c2c-d8ff4582322d)

When I try, it tells me no. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3443f6bc-3a4a-4a64-afb3-94b6fee35b36)

But they shouldn't be shown the drop-down box as if they can edit it, they should just see the rights. 

The groups and Invited is also not relevant to them. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b860f719-f199-43e6-8566-d4f16b1812d7)

So in fact, maybe they shouldn't have these options at all, if they are just editors. Might need reviewing by @kevincrepin at some point, to work out what editors should actually see at this point. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ae3ca008-32f0-467e-b789-06fb44e55db6)

**Comment by ssin1901** [comment]
@BeccaMelhuish high priority – editors should not get the insufficient permissions error. Came up in the usability tests. To clarify, the editor should not see the menu to change the rights in the first place.

**Comment by BeccaMelhuish** [comment]
@ssin1901 they should though surely, as editors can't change rights, only admins can? 

https://citizenos.com/help/topics/understanding-topic-user-rights/ 

So for me the issue isn't so much that they got the error, but that they shouldn't have access to these bits in the first place. As they can only edit content..

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk to clarify – Can we not show the users the options that Becca described?

**Comment by BeccaMelhuish** [comment]
Removing these from editor view seems simplest option, unless I'm missing something (i.e. a reason they need to see the list of people/rights) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/467b5cb7-c064-4dcf-9353-bd41f7f3f12f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 removed the options

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish I think the option is removed in both places, so editors can simply edit the topic not get involved in inviting and managing user permissions (screenshot1, screenshot2)
<img width="1287" alt="Screenshot 2024-03-14 at 16 16 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fe68e6b0-7950-4c7f-bb81-fff479faaccd">
<img width="1293" alt="Screenshot 2024-03-14 at 16 17 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5e791978-4d2b-4bff-b522-d03267aa8d00">
