### ISSUE TITLE
Topic: Says pad is open in another window but isn't 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1009]
Not urgent, but it says this when it isn't the case. 

(After having left it open and coming back to it). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/341ad0f7-3068-4122-a94c-00b1b7e24b68)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is an Etherpad specific thing, adding wontfix and closing the issue
