### ISSUE TITLE
Group: Says 3 voting topics, but there are 0 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1014]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e166eca2-a783-4de8-bf65-15c5544a80b1)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a  fix together with API update should now also have follow up topics in that list

**Comment by ssin1901** [comment]
@BeccaMelhuish I think it is fixed now (screenshot1, screenshot2). Closing the issue.
<img width="1099" alt="Screenshot 2024-03-15 at 12 57 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/26626d52-0797-4152-b16c-c8ecf93c2b93">
<img width="1298" alt="Screenshot 2024-03-15 at 12 57 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b1e19588-4da1-4b6b-8e55-023551e38cf8">
