### ISSUE TITLE
L10n: AF menu doesn't align to text width

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#1019]
**What is the problem?**

Activity feed menu doesn't adapt to localised text width:

https://github.com/citizenos/citizenos-fe/assets/34126353/bc3bb27d-4b2a-40f6-8fd6-8ed22dc79710

**Comment by ssin1901** [comment]
Moving to done (screenshot1)
<img width="1346" alt="Screenshot 2024-08-12 at 21 50 53" src="https://github.com/user-attachments/assets/474cbd46-a52f-48d7-a66f-35c5bf4f3162">
