### ISSUE TITLE
TOPICS: My Topics not in correct order

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1023]
**What is the problem?**
My Topics are not in correct order. In the screenshot( screenshot1) the user has JUST joined and it should have appeared first.
<img width="1291" alt="Screenshot 2024-03-15 at 13 02 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c5d571f7-d416-4e71-8fa3-03e40bf430ae">

**Why is this a problem?**
User could not find the topic they had just been invited to. 

**Possible solution.**
The topic that the user just joined should have appeared first

**Comment by ilmartyrk** [comment]
@ssin1901 it is a decision that we made a long time ago that my topics are ordered by their status so that voting topics are first as they might be most time critical if they have deadline.

**Comment by ssin1901** [comment]
@ilmartyrk my bad, thanks a lot for clarifying.
