### ISSUE TITLE
DB: 3 x broken links

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1025]
These 3 links take me to 'My topics'.

@ssin1901 @MeelikaH @ilmartyrk we need to think about the 'share your story' form? Do we replicate what we have on current platform? 

Donate and translation links once fixed should open in new tabs (as go to our website)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3eef9ca0-fe1a-4208-a7da-b86eca0a38ea)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk @MeelikaH @oksks could it link to this page? 

https://citizenos.com/get-involved/

**Comment by ilmartyrk** [comment]
@ssin1901 do you mean github page?
I changed the links for now so that the first one redreicts to https://citizenos.com/get-involved/ and other two are https://citizenos.com/get-involved/volunteer-translator and https://citizenos.com/donate

**Comment by ssin1901** [comment]
@ilmartyrk my bad, I meant this page https://citizenos.com/get-involved/

**Comment by ssin1901** [comment]
@BeccaMelhuish @MeelikaH I am closing this issue as the links seem to be okay for the launch. Please re-open if you disagree.
