### ISSUE TITLE
AF: Set notifications no longer showing on activity feed

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1030]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0d38a108-4adb-4377-8630-50ced1113fd8)

I seem to remember it was there before, like it is in the design? Or is this a Phase II thing? 

Would be good to have the link to set the notifications there at least: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fc3fd7c1-918b-4ccb-ab87-3f673d50e408)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk could this one be bumped up to higher priority (I think it's not in any list at the moment?), partly because it's quite important for usage (i.e. important that people find how to set their notifications so they stay in the loop) and also as I'd like to see if they find it in the upcoming user tests (May 20th onwards) :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk not sure if this is in the design, but I think it should be here too, so that people easily find where they can manage them all. And would take you to the notifications page in behind 'Account' :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5c1c901a-56fa-4bdc-a151-f1554fcce21a)

And as suggested by @oksks we could have it added to the Profile menu (between account and log out), though this would need reviewing by @kevincrepin, seems a good way to make users more easily find this very important section, but also clutters that menu a bit :)

**Comment by kevincrepin** [comment]
In the design we had this whole additional block with summary and a link to the settings:
![Screenshot 2024-05-15 at 11 54 52](https://github.com/citizenos/citizenos-fe/assets/26792281/e5a0d3b7-8a5f-4f49-9fae-7123fe2dcf40)

Figma: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=342%3A50139&t=ZK2cJdqHcuW8U5ig-1

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin we didn't have that section in the redesign it was never implemented, added the button only for the topics as it was easy to do. It will all come together when we finally decide and reach the point to upgrade activity feed to our redesign

**Comment by BeccaMelhuish** [comment]
@kevincrepin what are your feelings on notifications being added to this menu as well? Both @oksks and I had the same idea, that it such an important feature for user to find (it could really make or break their engagement in the topic - whether or not they get notified of engagement or have to remember to come back), and this would make it much more likely that they do. 

But it also makes this menu a bit heavier, and we've not yet tested with the notifications in the activity feed where your design had them. 

I'd vote for having it in the menu too, but what is your thinking? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3cc29ab2-bc3a-4603-98ab-cdb5a0288e78)

**Comment by kevincrepin** [comment]
If people have a hard time finding it and tending to go there, then we can add it there. You can see in the new interviews which way they go :) But this menu can scale, that's not a problem.
![Screenshot 2024-05-16 at 14 14 04](https://github.com/citizenos/citizenos-fe/assets/26792281/831285f3-1ad6-4913-9c10-1428be894dd4)


@ilmartyrk 
https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=11577%3A88092&t=XDEIRURuj3UBDpcA-1

**Comment by BeccaMelhuish** [comment]
Wonderful, thank you @kevincrepin!

@ilmartyrk if possible to add by Monday would be great :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the item to the "profile" menu

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Though it should also be added to the global activity feed (without the data) - see Figma design:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d7f738fc-a52e-4938-969c-6e611e9d388c)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Reopening this one as it's still missing from the DB activity feed :) 

![image](https://github.com/user-attachments/assets/c5e697f4-0abb-42eb-abaa-30d01076e1d9)

**Comment by BeccaMelhuish** [comment]
Closing this one now that we've removed it entirely due to its crash-causing nature :D
