### ISSUE TITLE
Tour: 'Create' and Main menu are blurred in tour 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1031]
Should be able to see the create button and the main menu when the tour is pointing to them: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/55f693ed-1c14-40d1-98e4-aba4f7ef9ed8)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b1aecdff-3f01-4eee-9b76-7a494db94ec8)

**Comment by ssin1901** [comment]
Working now (screenshot1, screenshot2) and closing the issue.
<img width="1440" alt="Screenshot 2024-03-21 at 15 04 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1191be84-3848-44f9-8195-3d6c7e9abd94">
<img width="1440" alt="Screenshot 2024-03-21 at 15 04 40" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ae765ba9-9c51-4ebe-b2bf-0eda74a89a6a">
