### ISSUE TITLE
Discussion: Bug in reporting category

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1032]
In a test (desktop), user clearly selects 'other' in the dropdown, for a moment it shows as selected, but as soon as he starts typing it reverts to 'is abusive or insulting'

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/299f4e5d-dd97-496b-8b45-699d29c66b61)

**Comment by ssin1901** [comment]
@BeccaMelhuish closing as it is now working in Google Chrome (see screenshot)
<img width="1293" alt="Screenshot 2024-03-17 at 19 14 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ef29d06c-9e7f-4c45-be5b-5abfa33a3af2">
