### ISSUE TITLE
REGISTRATION: Activate email seems to be skipped

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1035]
**What is the problem?**
@ilmartyrk  not sure if this is because the email account was deleted and then created again via Group Invite, but now the Activation process seems to have been skipped and the user is directly prompted to login (which works). See the screen recording below.

https://drive.google.com/file/d/1ykdbc_dmOCQ_A9oawso4Mr3UvcNm17RQ/view?usp=sharing

**Why is this a problem?**
Will really confuse the users

**Possible solution.**
1.Step 1, user receives invite and is prompted to create an account
2. Step 2, user fills details 
3. Step 3, user receives confirmation that an activation email is on the way. If user tries to login at this stage, they should get a notification that the account has not been verified yet.
4. Step 4, user clicks on activation link in email
5. Step 5, user sees message that activation has been successful and is automatically logged in OR user receives the same topic invitation and is asked is Login
6. Step 6, user sees all Login options not only email and password

**Comment by ilmartyrk** [comment]
@ssin1901 the issue was that registration process to access groups or topics via invite were too long. So as user has gotten invite to the e-mail they have to register the account with we can directly activate the e-mail and skip the verification process.
