### ISSUE TITLE
LOGIN: Getting Not Found error after successful login

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1038]
**What is the problem?**

_Tested on Google Chrome_

Getting a Not Found error after a successful login regardless of whether social login, e-id or email and password is used (see screenshot)
<img width="1292" alt="Screenshot 2024-03-17 at 23 36 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/26bc8b63-78c0-4205-b667-bb1cc8019776">

**Why is this a problem?**
Confusing to the user

**Possible solution.**
No error message should be displayed

**Comment by ilmartyrk** [comment]
@ssin1901 I believe it was related with the initial Plausible events setup, but not sure about that. I now removed the parts that I had added for testing, let me know if this issue still exists. If it does then please open the browsers console with F12 key, navigate to the network tab, and go through the process  again and let me know what row is getting the 404 error

**Comment by ssin1901** [comment]
@ilmartyrk seems to be a caching problem, could not replicate in Incognito mode. Attaching a screenshot anyway from Network tab but I think we can close the issue (screenshot1).
<img width="1383" alt="Screenshot 2024-03-18 at 10 53 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/83f62b9b-e7f4-4ddb-a017-fd3a4f2b5575">
