### ISSUE TITLE
GROUP: Incorrect number of updates in follow up

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1041]
**What is the problem?**
Number of follow up updates showed 1, when the topic was clicked on it turned out there was no follow up system (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/47717504-2a70-4a9b-99a9-06911a6a75df

NB! issue only occurs in Groups, correct view in My Topics (screenshot1)

<img width="1235" alt="Screenshot 2024-03-18 at 12 38 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bc82930d-f4ab-4d91-8fba-7168551b9f9c">

**Why is this a problem?**
Misinforms the user

**Possible solution.**
Should have shown 0 instead of 1 updates

**Comment by ilmartyrk** [comment]
Not high-priority, might be confusing but not an issue that interrupts platform usage too much.
