### ISSUE TITLE
Topic: Publish button design-dev mismatch on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1043]
Minor thing, but when there's time would be good to make it match the design here (wording and size of buttons) on mobile: 

Design: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/087225a5-1f3c-48ba-bdb3-1360dfdd6afc)

How it is now: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cd62596c-141f-4666-9d1f-bc518b8a6e1f)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/06292e07-1fab-412a-acb1-031d272edd13)

**Comment by ssin1901** [comment]
@BeccaMelhuish I will close this issue and open another one because I think the UI/UX changed a lot in mobile since this issue was created (see screenshot from Android device)
![IMG_0072](https://github.com/citizenos/citizenos-fe/assets/72747107/9afd5887-9e6d-47a2-b37a-7ecd5b625708)
