### ISSUE TITLE
Topic: Insufficient permissions when editing a topic title

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1045]
I edited a published topic title, and clicked 'Save changes and publish'. (On mobile, Android, Chrome)

I got taken to the topic and the title was edited, so all worked fine, but I had the 'Insufficient permissions' error display.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I could not replicate it, not sure if it still an issue

**Comment by ssin1901** [comment]
@ilmartyrk I will close the issue then.
