### ISSUE TITLE
Topic: Wrong notification message for 'Save as draft'.

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1046]
Non-urgent, but when I create a new topic, then save it as draft rather than publishing it, I get 'Topic successfully updated!" This makes sense when it is a draft topic you have edited and then saved again as a draft, but when it is a new topic you are saving as draft for the first time, it should be rather:

**Draft topic saved!**
Your topic has been saved to your drafts.

**Comment by ssin1901** [comment]
Fixed in the test environment (see screenshot). Moving the issue out of the testing column.

<img width="1384" alt="Screenshot 2024-04-22 at 18 51 40" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f96eb757-81d1-4cda-9128-3e25c95dd897">
