### ISSUE TITLE
Topic: Wrong publish button when creating a new topic 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1047]
In create flow, should just be 'Publish'. As per designs below, should only be 'Save changes and publish' when in edit flow.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/461fccab-1e4d-4d6d-8109-4e788afac712)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b4c69806-04fc-4219-aa4a-3d8687f1d3c7)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk Mobile and Desktop have different views In Preview (screenshot1 and screenshot2). Was this intended?

![IMG_0073](https://github.com/citizenos/citizenos-fe/assets/72747107/0b320bec-d1b2-43e4-8eed-8e21d829b9e4)
<img width="1378" alt="Screenshot 2024-03-28 at 13 50 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8117cbee-5464-4cee-83dd-fb1c1116301f">

**Comment by ilmartyrk** [comment]
@ssin1901 it is because of the text length

**Comment by ssin1901** [comment]
@ilmartyrk thanks! Do we still keep the issue open then?

**Comment by ilmartyrk** [comment]
Closed the issue
