### ISSUE TITLE
Topic: Draft topic gets published when only wanted to continue to next step

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1048]
As shown in this video, this is a draft topic I was intending to keep as a draft not publish. I go into it, click continue to get to the next step (which should be editing the settings), and suddenly it is published: 

https://www.loom.com/share/d02127870dad4a90b77555b61fcdf4f6?sid=6697d0f9-6513-41d6-9496-94d1402b4c4c

**Comment by BeccaMelhuish** [comment]
Also copying in this related bit from the now closed issue, just so it doesn't get lost - will check it once bug is fixed :) 

_This has made me realise we need another variation in the design from kevin - the flow for editing a draft and editing a published topic should be different - as when you are editing a draft you could either want to save it as a draft again or publish it, whereas when you are editing a published topic (presumably?) the only option is to publish it._

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I believe this is now fixed

**Comment by BeccaMelhuish** [comment]
Tried it on desktop (Windows Chrome) and does indeed work now. Will leave open in case @ssin1901 needs to test any more, but I think it's all good :)

**Comment by ssin1901** [comment]
@BeccaMelhuish closing as I could not replicate
