### ISSUE TITLE
Topic: Attachment not working 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1049]
**What is the problem?**
_Tested in Google Chrome_

Normal file types (JPG, PDF below 5 mb) cannot be added to the topic. Error message depicted in screenshot (see screenshot)
<img width="1424" alt="Screenshot 2024-03-18 at 19 01 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a0ebdb2b-fbcb-4146-9a3e-063b1729dab6">

**Why is this a problem?**
User cannot add attachments

**Possible solution.**
User should be able to upload attachments below 5MB

**Comment by ilmartyrk** [comment]
@ssin1901 was a configuration issue, had forgotten to update the validation configuration

**Comment by ssin1901** [comment]
@ilmartyrk fixed and closing issue (screenshot1, screenshot2)
<img width="1428" alt="Screenshot 2024-03-19 at 11 50 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a5b209a0-a55d-478c-9540-77b1595ab834">
<img width="1420" alt="Screenshot 2024-03-19 at 11 51 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/69d3922e-01db-46af-b775-e2b387dac635">
