### ISSUE TITLE
Activities related to user and My Activities are Identical 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#105]
**What is the problem?**
When the user goes to Activity Feed and tries to filter the activities, "Topics related to user" and "My activities" yield identical results (see screenshots 1 and compare with screenshot 2).

<img width="1192" alt="v1" src="https://user-images.githubusercontent.com/72747107/231795130-7ddbff2d-6025-42cf-b186-66f725afea53.png">
<img width="1189" alt="v2" src="https://user-images.githubusercontent.com/72747107/231795146-0aba5d64-7597-4643-bd01-cbbd86f33880.png">

Tested on MacOS Google Chrome. 

**Why is this a problem?**
One of the filter items is redundant 

**Possible solution.**
Redundant items should be removed

**Comment by anettlinno** [comment]
"All activities" do not show all the activities, but only some ("Activity feed" displays 64 new activities, but only 4 appears in the feed): 

<img width="593" alt="Activity feed" src="https://github.com/citizenos/citizenos-fe/assets/45175679/136c4dd8-d289-4658-87a2-d0eea8e49337">

"Activities related to user" is confusing as I don´t understand which user? :) Also "My activities" -- are those ALL my activities? Please remind me and see if we need to change the copy. 

<img width="134" alt="Activities" src="https://github.com/citizenos/citizenos-fe/assets/45175679/35a35dbd-d5e9-4c48-8fad-b3d70c04862c">

**Comment by ilmartyrk** [comment]
@anettlinno activities not loading more results is  a separate issue, I created a new issue for that and posted a fix https://github.com/citizenos/citizenos-fe/issues/128

**Comment by ilmartyrk** [comment]
My activities returns all activities where the user is the actor, or basically where the user has done the action described in activity. Related to user activities returns all activities that have relation to the user also including the ones where user is the actor

**Comment by anettlinno** [comment]
> My activities returns all activities where the user is the actor, or basically where the user has done the action described in activity. Related to user activities returns all activities that have relation to the user also including the ones where user is the actor

Thank you for the explanation, @ilmartyrk :) And for creating new issue (I thought about it for 2 seconds if I should create new issue, but I didn´t) 
Hmm... My Activities, All activities and Activities related to user is still very confusing. 

BUT that will change in the redesign, and I would not put any effort or time fixing this in current version. If you agree with that @ilmartyrk let´s close this issue with no further actions.

<img width="133" alt="Actfeed" src="https://github.com/citizenos/citizenos-fe/assets/45175679/3caf0774-7e06-4063-810a-e8edd9fc0ece">
