### ISSUE TITLE
NOTIFICATIONS: User may not receive Notifications on older topics

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1052]
**What is the problem?**
Just tested an old and new topic where both the settings were On under Notifications (screenshot1, screenshot2). 

<img width="1131" alt="Screenshot 2024-03-20 at 15 09 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2b3b083c-cd0c-4ce5-b92f-56870165b947">
<img width="1234" alt="Screenshot 2024-03-20 at 15 08 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cb6b4db2-003f-46fa-8301-8f005c76a5e7">

On the new topic, the user was informed via email about topic updates. On the old topic the user was not notified.

**Why is this a problem?**
Users who have previously added topics may stop receiving notifications via email.

**Possible solution.**
Either users should be notified about the change or continue to receive notifications.

**Comment by ilmartyrk** [comment]
@ssin1901 check from notification settings what type of notifications are selected for both topics

**Comment by ssin1901** [comment]
@ilmartyrk here are the screenshots. I will check the action though, if it was really a topic update.
<img width="1440" alt="Screenshot 2024-03-21 at 16 23 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/acc4262d-ebe9-4d52-8074-d78ea217eed7">
<img width="1440" alt="Screenshot 2024-03-21 at 16 20 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1f347dae-a7fe-4b73-9782-0f428bad4795">

**Comment by ssin1901** [comment]
@ilmartyrk based on the topic actions column, I believe that the user shouldn't have been notified in the first place (see screenshots). My apologies, closing the issue.

<img width="1440" alt="Screenshot 2024-03-21 at 16 25 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0cac63dc-2d59-4240-8b8b-d0789f02f074">
