### ISSUE TITLE
HELP: Comments and non-compulsory email causing confusion

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1054]
**What is the problem?**
Help requests and comments are bundled together (see screenshot) and a user who wants to submit a Help Request won't know that they have to submit an email address for us to get back to them.

Validated in a platform demo.

<img width="1322" alt="Screenshot 2024-03-21 at 12 35 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a1604262-a5bd-4b42-99b0-0e1f53135c16">

**Why is this a problem?**
We won't be able to reach users who have Help Requests and forgot to submit an email address. 

**Possible solution.**
@BeccaMelhuish @ilmartyrk can we please a) remove comments from the HC for the time being b) Make the email compulsory again

**Comment by BeccaMelhuish** [comment]
Decision on Slack to move email field underneath message field, and change the wording to "Want a response? Please provide your email". 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1913116c-7f7f-4ed2-bab4-488151c1ca6d)

**Comment by ilmartyrk** [comment]
Added changes

**Comment by ssin1901** [comment]
@ilmartyrk at the moment, it seems to be the same in app.citizenos.com

**Comment by ssin1901** [comment]
@ilmartyrk it seems okay, we can push to live (screenshot attached)
<img width="1440" alt="Screenshot 2024-03-27 at 11 23 10" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fd53a1f4-8b45-486a-a0e0-e86597835b68">
