### ISSUE TITLE
Topic: Duplicate title for topic transferred over

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1058]
Only found it in this one so far, but I guess there may be others? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/83a668d9-a42d-4aa8-8d49-915cef58cc39)

**Comment by BeccaMelhuish** [comment]
@ssin1901 I'm guessing we can close this one as it's not come up in any topics recently, must be fixed? 

And that particular topic is fine now: 

![image](https://github.com/user-attachments/assets/7403ed74-05b6-47de-81cb-f237c1daad7e)

I will close it but put in testing for you just in case :)

**Comment by ssin1901** [comment]
@BeccaMelhuish it wasn't a bug, rather – the topic had a heading that matched the topic title. I actually edited it to remove the duplicate!

Sending to Done
