### ISSUE TITLE
GROUP: Add Topics not working 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1059]
**What is the problem?**
_Tested in Google Chrome_

User cannot search and add a topic they created in Group->Add Topic (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/cc07496f-366c-42d2-abf4-e6ff1be14287

**Why is this a problem?**
User is unable to add a topic to a group

**Possible solution.**
Topics that the user has admin rights to should be displayed when the user is searching

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk tested in Chrome incognito but still could not add a topic that I created (screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/503522e9-5f94-4117-a1e9-567a23d98a84

**Comment by ssin1901** [comment]
@ilmartyrk tested and seems to be okay. Can push to live (screenshot1, screenshot2)
<img width="1440" alt="Screenshot 2024-03-27 at 11 24 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b96ca627-c223-426f-a700-0b7dbdb9d95f">
<img width="1440" alt="Screenshot 2024-03-27 at 11 25 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/32fef2e8-c4b3-4f18-9c2d-8fd20ec89611">
