### ISSUE TITLE
GROUP: User cannot remove group from topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1060]
**What is the problem?**
User went to edit a topic and received successful confirmation that they had removed the group but when they went back to Edit, the group was still showing (screen recording) and also present under Groups in Topic Interface as well as in Group under Topics.

https://github.com/citizenos/citizenos-fe/assets/72747107/a7f14079-0c87-4599-bc6e-a77b5adf523f

**Why is this a problem?**
User will think they can remove Group from Topic following the steps described above.

**Possible solution.**
User should not see the Add to group option if they cannot remove the group from the topic

**Comment by ilmartyrk** [comment]
@ssin1901 I see the issue, currently you can remove topic from group from under topic manage participants view. Will post a fix soon

**Comment by ssin1901** [comment]
@ilmartyrk I just found where to remove a topic (screen shot attached) and thanks a lot! Keeping this issue open though because the group cannot be removed by the topic editor.

<img width="1440" alt="Screenshot 2024-03-22 at 18 53 10" src="https://github.com/citizenos/citizenos-fe/assets/72747107/02ce13fd-1ac5-42cb-882f-b02546dc4590">

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix for users to be able to remove groups from topic edit view. Group will only be removed if changes are saved.

**Comment by ssin1901** [comment]
@ilmartyrk it still doesn't seem to be working as I was notified that my edits were successfully published (see screen recording)

https://drive.google.com/file/d/1Xuq5O0BIZd9QLFdAEkS4ix6t-j1JFtRn/view?usp=sharing

**Comment by ilmartyrk** [comment]
@ssin1901 It is in the testing app not live

**Comment by ssin1901** [comment]
@ilmartyrk my sincerest apologies.
