### ISSUE TITLE
No error message for header images above 5MB

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1062]
**What is the problem?**
_Tested in Google Chrome_

User doesn't get an error message when the header image is above 5MB (screen recording) even after refreshing.

https://github.com/citizenos/citizenos-fe/assets/72747107/d1231ee2-3098-4725-ae1b-52837a5bfdfb

**Why is this a problem?**
User thinks the functionality is broken 

**Possible solution.**
User should receive error message that only images under 5MB are accepted by the system

**Comment by ssin1901** [comment]
@ilmartyrk this is also fixed in the test environment (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/cba8f85f-56ad-4b8e-917e-c971da6867bd

**Comment by ilmartyrk** [comment]
@ssin1901 I don't remember doing any fixes for this issue, but just tested and it worked in live too, so closing it for now. Maybe the issue was somewhere else
