### ISSUE TITLE
Public Topics->Hidden by Admin->Why not working

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1065]
**What is the problem?**
In Public Topics, under Hidden by Admin the Why button doesn't do anything (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/932a00ca-70d9-41df-a573-8b73f0dd9ad8

**Why is this a problem?**
Users should be able to view Why a public topic has been hidden

**Possible solution.**
Clicking the Why button should show the reasoning behind hiding the topic

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix to testing, also removed subscribe to newsletter box from dashboard

**Comment by ssin1901** [comment]
Works and newsletter removed (screenshot1, screenshot2) 

<img width="1440" alt="Screenshot 2024-03-26 at 15 11 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/87ee116d-fcff-4ec1-b0a9-1f290e228ae1">

<img width="1437" alt="Screenshot 2024-03-26 at 15 12 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/986e90c3-00d8-4ee7-bc04-439a41b333d5">

@ilmartyrk can I close the issue now or should I wait until it is deployed to live?
