### ISSUE TITLE
VOTING: File format issue/query 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1072]
**What is the problem?**

_Tested on Google Chrome on Mac OS_
_Tested on Google Chrome, Windows_

I was expecting to get different file formats for BDOC, Äriregister, Riigikogu, KOV but got the same BDOC format for all 3 (see screen recording).

https://github.com/citizenos/citizenos-fe/assets/72747107/fc5b65a0-d900-4a7f-a80b-ecf062818031

**Why is this a problem?**
I am not sure the file formats are correct, which could cause issues for users.

**Possible solution.**
File formats should be fixed or removed as options.

**Comment by ilmartyrk** [comment]
@ssin1901 container types are as is, but the content of the containers is different, Machine readable container doesn't have results csv file as it caused errors in the Business Register system.
