### ISSUE TITLE
Group: Code in the Group Activity Feed

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1081]
**What is the problem?**
String not returned when a user has accepted a group request (see screenshot)
<img width="1061" alt="Screenshot 2024-04-04 at 16 37 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f138d314-7bc0-4d0d-8877-58cea2cc3d62">

**Why is this a problem?**
Code in the activity feed confuses the user

**Possible solution.**
String should be returned

**Comment by ilmartyrk** [comment]
@ssin1901 I think this is fixed though this issue still might occur as I changed the structure of the activity from the initial version and this changed the translation key too. So for any new activities it should be fixed and if any old exist just ignore

**Comment by ssin1901** [comment]
@ilmartyrk could not replicate the issue in the live environment. Closing and will open a new issue if it occurs again.
