### ISSUE TITLE
Group: Cannot Request a Topic to be added to the group

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1082]
**What is the problem?**
At the moment, a topic cannot be added to the modal (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/cd21b2da-8dc9-42ec-8f43-9eed0cf3c9b7

NB! The request was still sent and the Group Admin notified by email

**Why is this a problem?**
User does not know if the request has been successful

**Possible solution.**
1. User should receive a message that the request has been sent instead of an error message

**Comment by ilmartyrk** [comment]
@ssin1901 I am having difficulties replicating this issue, is the group private or public?

**Comment by ssin1901** [comment]
@ilmartyrk the group is Private but after testing it seems everything works alright with a newly created topic but there are some issues with the older topics. The issue I described above is with an older topic.

**Comment by ilmartyrk** [comment]
@ssin1901 I think there might be some other issue related to the older topics, I couldn't replicate it, but it might have something to do with being the test environment and some topics have their Etherpad connected data deleted

**Comment by ssin1901** [comment]
@ilmartyrk no worries, I will test this in Live then.

**Comment by ssin1901** [comment]
Fixed in app.citizenos.com and closing.
