### ISSUE TITLE
GROUP: Clicking on Accept a Topic from email leads to a blank page 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1084]
**What is the problem?**
_Tested on Google Chrome in incognito mode_

Regardless of whether a user is logged in or logged out, clicking Accept a Topic leads to a blank page (see screen recording). Works after a hard refresh.

https://github.com/citizenos/citizenos-fe/assets/72747107/87a9d82b-772d-45fd-b3d5-7828ddab97af

**Why is this a problem?**
User will be confused

**Possible solution.**
Refresh shouldn't be needed

**Comment by ilmartyrk** [comment]
@ssin1901 I could not replicate the issue

**Comment by ssin1901** [comment]
@ilmartyrk seems to be fixed now (see screenshot) in logged in view.
<img width="1221" alt="Screenshot 2024-04-09 at 12 20 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e22e20c6-76d0-4d45-948a-4e4e9960b93a">

I have a question though. In logged out view, the user is redirected to the dashboard. I guess it is okay (see screen recording) but if we don't fix this, then let me know and I will close the issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/3d9cd5e7-b2f3-4eb4-8779-6ec084ec14d7
