### ISSUE TITLE
GROUP: Add to Group Text Changes

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1089]
**What is the problem?**

@oksks @BeccaMelhuish 

1. Text issue (ideally it should not appear). Text should be replaced with "Your request to add a topic has not been sent. Please try again." (see screenshot)

<img width="1416" alt="Screenshot 2024-04-09 at 13 38 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/732d1360-23b3-464f-a803-d98562fa8ab9">

2. Text issue: Word "Topic should be inserted" (see screenshot)

<img width="1415" alt="Screenshot 2024-04-09 at 16 25 53" src="https://github.com/citizenos/citizenos-fe/assets/72747107/dbf708f3-541b-495b-91bd-0fba49cd7cbf">

**Why is this a problem?**
1. Incorrect and confusing message. User cannot correct the action.

**Possible solution.**
1.User should be able to understand the issue.

**Comment by ssin1901** [comment]
@oksks it seems that the word topic is missing here 
<img width="1415" alt="Screenshot 2024-04-17 at 13 07 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0ec680d9-2a3a-4c91-b66c-020c652df7b1">

**Comment by ssin1901** [comment]
@oksks

**Comment by oksks** [comment]
Fixed!
