### ISSUE TITLE
E-ID Card error message is confusing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#109]
**What is the problem?**
When you go to Login-> Log in with ID-Card/Mobiil ID-> Authenticate and there is _no E-ID card reader attached or detected_ you get an error "no implementation" screenshot below.

<img width="1334" alt="Screenshot 2023-04-26 at 14 29 00" src="https://user-images.githubusercontent.com/72747107/234563173-4d3153e5-4284-4137-a6d1-81843497e13a.png">

**Why is this a problem?**
User is confused about why they are unable to login.

**Possible solution.**
User should be notified if E-ID card authentication is not working due to no card reader being detected or the card not placed/detected in the card reader. Something like "No card in card reader" or "Card in card reader not found". See https://www.id.ee/en/article/issues-with-the-id-card-reader/

**Comment by anettlinno** [comment]
Triage 85. We have translations for these error messages and should be easy fix. 
Est. dev. time 30 min. Sending it TO DO.

**Comment by ssin1901** [comment]
Issue doesn't seem relevant now, see screenshot. Moving to Done.

![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/c925981f-8de4-47ec-9e6d-be9b0931dd7d)
