### ISSUE TITLE
GROUP: Request feature should include Private or Public 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1090]
**What is the problem?**
The Request to Add Topics to Groups email (see screenshot1) should include information about whether the topic is Private or Public.

<img width="1052" alt="Screenshot 2024-04-09 at 12 18 20" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a9f9431f-ec78-4e98-9ca9-6257f8ea4d2d">

**Why is this a problem?**
1.A group admin should know if the topic is Private or Public before accepting the topic to the group. Currently there is no way for Group Admin to view the status of the topic before accepting it.

**Possible solution.**
1. Email should include information about whether it is Private or Public under a third column titled "Visibility".

**Comment by ilmartyrk** [comment]
@ssin1901 updated the email though there might be some delay with crowdin an translation syncing

**Comment by ssin1901** [comment]
Fixed and closing (screenshot1)
<img width="1093" alt="Screenshot 2024-04-09 at 18 47 30" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a8f51695-432b-4147-8925-64ae353e8631">
