### ISSUE TITLE
GROUP: Requested topic is not greyed out

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1092]
**What is the problem?**
Under Request Topic to Group, a previously requested topic is not greyed out (see screenshot)

<img width="1418" alt="Screenshot 2024-04-09 at 13 47 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3c9f5d0b-db47-4212-888b-2a2842e808a4">

**Why is this a problem?**
User will try to add the same topic multiple times or get confused

**Possible solution.**
Already requested topics should be greyed out

**Comment by ilmartyrk** [comment]
@ssin1901 will check, but it is a little complicated issue to solve at this point. I can gray out the topics that are added already, but currently if a new request is created by the same user with new level we update the request info in the databade. For example user  x requested topic with edit permissions to be added to the group. We dont have any edit request view, but user can create a new request with read permissions of the initial request was created with wrong level

**Comment by ssin1901** [comment]
@ilmartyrk fixed (screenshot) and moving to done.
<img width="1417" alt="Screenshot 2024-04-12 at 15 15 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1f71ad49-f03c-4fee-8fca-f0a6c71479f5">
