### ISSUE TITLE
GROUP: Request to Add Topic to Group Accepted View is not looking correct

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1094]
**What is the problem?**
Once a user has accepted a topic to group (see screenshot)

<img width="1440" alt="Screenshot 2024-04-09 at 13 53 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7a6553ca-e1b0-47f2-99b7-a0b675e7fdf9">

1. The topic is not visible until the Topic requests modal is closed
2. It is unclear why the Topics modal is displayed in the first place

**Why is this a problem?**
1. Very confusing for the group admin 

**Possible solution.**
1. The Group Admin should only see the success message
2. The Topic should instantly be added, no need to close anything or refresh

**Comment by ilmartyrk** [comment]
@ssin1901the modal itself is not that confusing as it was opened intentionally. It will not close directly as there might be multiple requests in the list. 

I'll try to add updating after each accept action

**Comment by ilmartyrk** [comment]
@ssin1901 fixed 2 , 1 not an issue from my point of view

**Comment by ssin1901** [comment]
@ilmartyrk I think it is okay for this phase with the topic immediately appearing (screenshot). Closing now.
<img width="1415" alt="Screenshot 2024-04-09 at 18 45 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a34b8c6f-cca7-44d6-8002-1341ee11d23a">
