### ISSUE TITLE
GROUP: Request link in email takes the user to dashboard in Logged Out View 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1095]
**What is the problem?**
After a user has clicked on Accept (screenshot1), they are prompted to Login. However, after logging in – they see the dashboard view (screenshot2) instead of the Group view with success message (screenshot3)

<img width="1095" alt="Screenshot 2024-04-09 at 15 34 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f9757505-ce1d-4ec7-ada3-024706effea6">
<img width="1425" alt="Screenshot 2024-04-09 at 15 34 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/91307863-3429-4b77-8d1b-331b9ebf71f8">
<img width="1221" alt="Screenshot 2024-04-09 at 12 20 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f9d4e471-ee54-4bfe-89c8-db3e60fa5db8">

**Why is this a problem?**
User would be totally confused about the status of Accepting the topic, as it is not mentioned anywhere.

**Possible solution.**
A clear and concise description of what you expected to happen (when applicable).
1. User should be redirected to the Group view with success message.

**Comment by ilmartyrk** [comment]
A complex issue to solve, but I will try to come up with a fix

**Comment by ilmartyrk** [comment]
@ssin1901 I tried to make it a little better

**Comment by ssin1901** [comment]
@ilmartyrk works okay for this phase (see screen recording). Closing the issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/82c3e403-8692-468a-92cc-351905a5a3a8
