### ISSUE TITLE
Email: Formatting inconsistency

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1096]
Minor thing, these are usually black (blue-black) bold, but here they are italic. Should be consistent, so all in bold.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b96c4039-7e14-4223-ba86-4e5c1b231d72)

**Comment by ilmartyrk** [comment]
Will fix

**Comment by ssin1901** [comment]
Fixed (see screenshot) and moving to Done

<img width="1082" alt="Screenshot 2024-04-12 at 16 09 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/72bc3eb4-2bd1-4667-9e48-5cd61b763658">
