### ISSUE TITLE
VOTING: Mobile user can add Arguments in a Voting Topic 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1099]
**What is the problem?**
Tested in Mac OS Google Chrome
Tested in Android Google Chrome

In Mac OS Google Chrome, the user Dave who created a Voting Topic is not able to add Arguments (seems correct functionality as it is specified in the argument description that pro/con arguments are skipped in a Voting topic). Screenshot attached (screenshot1)

<img width="1417" alt="Screenshot 2024-04-10 at 12 37 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/911cc263-ebc0-4495-b433-3a63a16d36f4">

However, in **Android Google Chrome**, the same user is able to add Arguments (screenshot2, screenshot3, screenshot4)

![IMG_0077](https://github.com/citizenos/citizenos-fe/assets/72747107/37842d91-791e-4d15-823b-43a5ac0bbedf)
![IMG_0078](https://github.com/citizenos/citizenos-fe/assets/72747107/a47074fc-6ed3-4b05-a506-5b6cf554e9c0)
![IMG_0079](https://github.com/citizenos/citizenos-fe/assets/72747107/551978f0-7a1e-4dd3-af65-f7c3581ce2c8)

**Why is this a problem?**
1. Will confuse the users and there is also a possibility (needs further investigation) that this will convert Voting Topics into Discussion Topics. Hence, the high priority label.

**Possible solution.**
Mobile functionality should match Desktop functionality.

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
Fixed now in test environment (see screenshot). Closing the issue.


![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/f343a15a-1122-4f74-99de-85cf5a0befd4)
