### ISSUE TITLE
Ideation: Participants ideas filter needs thinking through

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1101]
@ilmartyrk @kevincrepin, just noting here some things from Kevin re the ideation feature, for re-thinking and to note in the development of it :)  

_Actually needs to be thought through more because now the filter person card overlaps an idea. Also closing it would bring back the full list of participants to filter – unlike now it's clearing the filter – but that's bit more tricky to have it in the prototype_

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/91dba980-ea30-4e8e-a004-55226955e6ad)

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk Am adding pre UX tests label here, if at all possible to review this week :)

**Comment by kevincrepin** [comment]
Worked a bit on this and would suggest this approach:
![Screenshot 2024-05-16 at 15 25 39](https://github.com/citizenos/citizenos-fe/assets/26792281/84e66215-f509-4558-a12f-c6498eb28b61)
No more overlapping over an idea + closing it would clear the filter. If you want to find by another person you can do it immediately via the dropdown.

@ilmartyrk If this goes then it's available in figma here: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=13077%3A88829&t=3yt34QVGBQCTs3ip-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin this looks good! 

Wondering what this bit does though, if the 4 idea cards would be displayed below?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/23813347-3ca9-40ab-a6a0-5b80a3313af6)

And I wonder if a little invisible being a similar shade, but we can see in the tests!

**Comment by kevincrepin** [comment]
Actually those are unnecessary. Initially in my mind I thought to do it like when you search any word in a browser, the content remains but you can jump to the next hit with the arrows. But here we filter out entirely... So pretty useless! :D Will remove it.
![Screenshot 2024-05-16 at 15 50 55](https://github.com/citizenos/citizenos-fe/assets/26792281/9d73f0fc-afc7-4dce-a83b-735d722d1a28)

**Comment by kevincrepin** [comment]
Ok, I'm clearly one leg into my time off already, because this entire block becomes pointless if we're anyway showing the participant name in the field.

**Comment by BeccaMelhuish** [comment]
Ah haha yes good point! The only thing missing if removed though would be number of results..

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin I guess we can add the number behind the name in the brackets or would it be too confusing
?

**Comment by BeccaMelhuish** [comment]
I'm wondering if it's also a nice visual reminder that they have a filter on, plus easy way to remove the filter and get back to 'All' (if clicking the X would do that, or maybe that's confusing)? So could keep it as it is in the screenshot above?

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish added the design as in this image

**Comment by ssin1901** [comment]
I am a little bit confused – this feature has been implemented in the Redesign app?

**Comment by BeccaMelhuish** [comment]
@ssin1901 yes just checked and it is there :) 

Though @ilmartyrk one small design thing, it should go to the edges: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6a5312fa-5cee-4f3c-80f1-34fa304482b1)

**Comment by ssin1901** [comment]
@BeccaMelhuish close if fixed (screenshot1)
<img width="1053" alt="Screenshot 2024-05-20 at 23 42 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6b91c2b4-317c-4266-b950-c29564ced563">

**Comment by BeccaMelhuish** [comment]
Great yes looks good! Spotted a typo here but could edit myself, so will close :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dd186e32-5a29-419c-b2fa-c43f0db8ef7c)
