### ISSUE TITLE
L10n: text width needs to be flexible

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#1102]
**What is the problem?**
Under "Help", some text has been cut off in translation:

<img width="380" alt="Screenshot 2024-04-12 at 11 04 21" src="https://github.com/citizenos/citizenos-fe/assets/34126353/91b4786b-e5bf-413b-a1e2-fa833b5f138a">

English copy: "Your email address (optional)"
Please make width adaptable:)

**Comment by ilmartyrk** [comment]
@oksks made the panel wider

**Comment by ssin1901** [comment]
Fixed and closing issue (see screenshot). NB! It is fixed in the test environment.
<img width="1440" alt="Screenshot 2024-04-19 at 21 49 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c763c701-e7f1-45c8-8f0f-7036dbcd6cc5">

**Comment by oksks** [comment]
@ilmartyrk now (in live) this button spreads out beyond the edges:

<img width="432" alt="Screenshot 2024-04-20 at 14 35 08" src="https://github.com/citizenos/citizenos-fe/assets/34126353/d041e43d-7de1-4f66-9b71-0930a400e7de">
