### ISSUE TITLE
ARGUMENT: Internal server error after clicking Add Argument

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1109]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

In the test environment, Add argument leads to an error (see screen recording)
https://github.com/citizenos/citizenos-fe/assets/72747107/34eccb61-79cd-4113-b2e4-d71477441938

**Why is this a problem?**
User cannot add argument (MVP feature)

**Possible solution.**
User should be able to Add Argument without Internal Server Error

**Comment by ilmartyrk** [comment]
@ssin1901 database was full, cleaned it up, closing the issue
