### ISSUE TITLE
TOPIC: Group list is not working as expected

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1119]
**What is the problem?**

_Tested in Google Chrome in incognito mode_

In Topics->Add Topic to Group, there is an inconsistency when it comes to displaying the group list. 

Here is 1 view (same account, same browser)
<img width="1397" alt="Screenshot 2024-04-25 at 17 44 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d0a757b9-4c1c-4373-9fe2-fb55fc4c98ab">

Here is another view (same account, same browser)
<img width="1386" alt="Screenshot 2024-04-25 at 17 42 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/dfd2f64e-5dca-42d4-a6be-33e44d1739eb">

**Why is this a problem?**
1. User won't be able to add Topic to their own group.

**Possible solution.**
1. All groups where the user is admin should be displayed. As previously agreed, private groups where the user is a member rather than admin should also appear.

**Comment by ssin1901** [comment]
@ilmartyrk seems a duplicate of https://github.com/citizenos/citizenos-fe/issues/1259

Should I close?

**Comment by ilmartyrk** [comment]
@ssin1901 I'll close this one
