### ISSUE TITLE
IDEATION: Add attachment doesn't accept valid file type

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1123]
**What is the problem?**
_Tested in Google Chrome incognito mode_

Add Attachment does not accept a PDF file of 2MB and triggers incorrect notification (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/e82e6d78-4de3-4e82-8fa6-1911786ff57a

**Why is this a problem?**
User cannot add valid attachment

**Possible solution.**
User should be able to add a 2MB PDF file

**Comment by ilmartyrk** [comment]
Was a redesign.app config issue, fixed now
