### ISSUE TITLE
IDEATION: Can proceed to the next step without an Ideation Question

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1124]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

User can publish the Ideation topic without an Ideation question (screenshot1, screenshot2)

<img width="1391" alt="Screenshot 2024-04-30 at 15 35 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8dfbde7f-4661-438c-912f-c274bb9d0a6c">

<img width="1386" alt="Screenshot 2024-04-30 at 15 35 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2d2790fc-1a11-44ea-993c-41dfa95a31ad">

**Why is this a problem?**
1) Ideation field listed as compulsory 2) Needs to be like Voting where one cannot proceed without adding a question first

**Possible solution.**
1. User should not be able to publish an Ideation Topic without an Ideation question

**Comment by ssin1901** [comment]
@ilmartyrk it works (see screenshot) but I think that in the long term I think the button should be greyed out and non functional until the question is added. 

<img width="1430" alt="Screenshot 2024-05-03 at 16 25 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9590dcd7-5051-47b3-88f1-dcc5ea133521">

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk I think the button still looks like it works and isn't greyed out (screenshot attached)
<img width="1434" alt="Screenshot 2024-05-06 at 17 11 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9c14abfa-0923-435b-838f-24eeed21761c">

Tested in Google chrome, incognito

**Comment by ilmartyrk** [comment]
@ssin1901 sorry, there was a connection error with my dev machine and the fix was not uploaded. Got it fixed and uploaded the code, should appear in a minute or two

**Comment by ssin1901** [comment]
@ilmartyrk works now (screenshot1, screenshot2) and closing
<img width="1436" alt="Screenshot 2024-05-09 at 15 33 31" src="https://github.com/citizenos/citizenos-fe/assets/72747107/45bae8af-10ac-411e-9038-a3061c3b13ff">

<img width="1434" alt="Screenshot 2024-05-09 at 15 33 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/362ef419-9375-4cfd-aa74-b19d8d5b00f9">
