### ISSUE TITLE
IDEATION: Add to group causes an error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1125]
**What is the problem?**
When a user adds an ideation topic to a group, they will receive this error (screenshot1)

<img width="1390" alt="Screenshot 2024-04-30 at 15 41 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/30e5c110-8783-4967-8222-6cbee791f937">

Error doesn't occur unless a group has been added.

**Why is this a problem?**
Could be related to the test database 

**Possible solution.**
A clear and concise description of what you expected to happen (when applicable).

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk works nicely now (screenshot attached) and closing.

<img width="1238" alt="Screenshot 2024-05-03 at 16 16 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c8eab603-ca57-41ab-a59b-bba9a49c07ab">
