### ISSUE TITLE
IDEATION: Missing Activity Feed Items

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1126]
**What is the problem?**
@ilmartyrk @oksks now that we have Ideation, should the Discussion, Voting and Ideation topics be labelled in the AF as such? Currently they all only say "Topic" (screenshot1)

<img width="1386" alt="Screenshot 2024-04-30 at 15 45 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1292850c-c202-4885-a7ba-d5c4af43ffd2">

**Why is this a problem?**
Users might get confused about whether a Topic is an Ideation, Discussion or Voting Topic. They may also misreport bugs, because they may not remember what they originally selected and think that the topic got converted on its own.

**Possible solution.**
Low priority, only affects users with multiple different topics. Maybe this is something that we should discuss before the text review though.

**Comment by ilmartyrk** [comment]
Missing activity feed items should be the name for this issue. I think there will be quite many items that don't have translations yet

**Comment by ssin1901** [comment]
@ilmartyrk I will rename it. But it's not an important issue, I don't think it needs to even go under Ideation specifically.

**Comment by ilmartyrk** [comment]
linked to https://github.com/citizenos/citizenos-fe/issues/1169

**Comment by BeccaMelhuish** [comment]
@ssin1901 I think this one can be closed now? Will put into testing for you to check though :)

**Comment by ssin1901** [comment]
@BeccaMelhuish issue is not fixed but I'm moving it to Backlog - Later. It's not a very important issue unless it comes up in one of your tests.

**Comment by BeccaMelhuish** [comment]
Actually @ssin1901 looking at this now I will keep it closed and move it to done, as from the users' perspective we no longer have 'discussion topics', 'voting topics' etc, we just have 'topics that start with' one of these phases (this was a UX change that happened part-way through the implementation of the redesign). So while internally we might still refer to them as 'X phase topics', to users we don't. (And ideally should get in the habit of calling them 'starting with' topics internally too). 

![image](https://github.com/user-attachments/assets/6a7a2a83-eb32-40ba-a96e-126e8ebde562)
