### ISSUE TITLE
IDEATION: Edit idea doesn't work

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1127]
**What is the problem?**

_Tested in Google Chrome in incognito mode_

In a Published Topic, the Edit idea button doesn't work (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/25cfaf51-b190-4cec-b685-0b7d1ca1309e

**Why is this a problem?**
User cannot edit their idea

**Possible solution.**
User should be able to edit their idea

**Comment by ilmartyrk** [comment]
@ssin1901 added the missing component

**Comment by ssin1901** [comment]
Fixed (screenshot1, screenshot2) and closing the issue.
<img width="1384" alt="Screenshot 2024-05-02 at 16 30 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/363f1cb1-b37c-4cb8-8930-a1566f4cabb4">
<img width="1390" alt="Screenshot 2024-05-02 at 16 30 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/02519470-8f85-4c95-865e-e620e24e0d04">
