### ISSUE TITLE
IDEATION: Cannot Invite Users 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1128]
**What is the problem?**
Inviting a user to join an Ideation topic leads to an Insufficient Permissions error (see screenshot) and user is not invited either

<img width="1440" alt="Screenshot 2024-04-30 at 17 11 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8d7ae894-d950-4055-afc6-ec020337d9ae">

**Why is this a problem?**
Cannot invite users to an ideation topic

**Possible solution.**
It should be possible to invite a user to an ideation topic without an error

**Comment by ilmartyrk** [comment]
@ssin1901 was an API side issue with permissions check depending on topic status. Went over all the places where it is done and included topic status ideation everywhere where needed (invites, attachments ..)

**Comment by ssin1901** [comment]
@ilmartyrk issue is fixed (see screenshot). Closing the issue.
<img width="1436" alt="Screenshot 2024-05-03 at 16 17 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1b1b75e6-8c91-4750-85ac-debe90bdb60f">
