### ISSUE TITLE
IDEATION: Topic tour missing Ideation

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1129]
**What is the problem?**
Topic tour should refer to ideation (see screenshot)
<img width="1384" alt="Screenshot 2024-04-30 at 16 00 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/847981b1-cbd4-44cd-b451-bbe838285246">

**Why is this a problem?**
User will not understand how to use ideation if they take a topic tour

**Possible solution.**
Topic tour should include ideation

**Comment by BeccaMelhuish** [comment]
I think it's fixed now?

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1440" alt="Screenshot 2024-05-16 at 11 05 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8cdb78c3-479a-4604-80e6-410c8414b3a7">
