### ISSUE TITLE
Ideation: Needs adding to all create menus

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1136]
Ideation should be in all the create menus: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e8a8f0f9-43d9-4899-8c81-e4bdc5311ffc)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/905d3faf-3aa7-42e2-ba7e-b3fc505b2d8b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk fix has been added but it is getting cut off on regular Desktop size (see screenshot)
<img width="1437" alt="Screenshot 2024-05-06 at 13 42 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ed6ea8b0-9731-45af-aa9c-0f9b216bd63d">
