### ISSUE TITLE
Ideation: Should show in phases tabs in all topics, even when not started

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1137]
All topics should now have the ideation tab (even when there is 'No ideation yet'): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1a5f691f-9665-45f1-b966-99035d2addcf)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I followed the logic from Vote topics where we don't allow discussion. Users cannot add ideation to discussion topics so there is no point in displaying the tab there as is the case with vote topics

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK sorry I'm getting confused about what order the phases come in as in the menu it looks like discussion > ideate > vote. But that's for a separate issue, so will close this one here :)
