### ISSUE TITLE
Ideation: Order of phases should be consistent everywhere

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1138]
@ilmartyrk Are we putting ideation before discussion or after discussion in the order of phases? 

Whichever way it is, it needs to be consistent in all places, i.e. the places screenshot below :) 

Which order is best for users should become clearer through the user testing (though I expect it will vary a lot from case to case, so potentially show a need for greater flexibility as per this [idea](https://github.com/citizenos/citizenos-fe/issues/653)). But for now we could just stick to the order Kevin has designed it, then adjust once we have a clearer picture of users' needs? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2d332b50-421c-4f9c-b852-78c30906c3e3)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/824b53d6-0382-42ff-8727-21fb66def671)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ed649c59-0529-4df0-a25d-cc0d9d1f2a4c)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should be fixed
