### ISSUE TITLE
Ideation: Text bug in character limit message

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1140]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4e8a991b-007b-4fcc-99d6-564761250d2a)

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1175" alt="Screenshot 2024-05-16 at 15 38 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5611abf6-adff-45e1-9195-1c855783b341">
