### ISSUE TITLE
Ideation: Bug in manage ideation menu - edit

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1141]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8030acb8-a91a-49c3-9b8d-e682ea90292b)

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1435" alt="Screenshot 2024-05-09 at 15 37 45" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cf847e53-0248-4490-9f84-7e1278ec4ca0">
