### ISSUE TITLE
Voting: 2 letter country code not pre-filled

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1142]
When @ssin1901 and I tested e-ID voting just now, the two-letter country code wasn't pre-fillled. See related (closed but seemingly not fixed) issue [here](https://github.com/citizenos/citizenos-fe/issues/853) :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/44d4a5f5-418d-4d55-9f5f-38561fd6d5c6)

**Comment by ssin1901** [comment]
Moving to done (screenshot1)
<img width="1344" alt="Screenshot 2024-08-12 at 22 06 21" src="https://github.com/user-attachments/assets/ae0f7cf5-ba16-43c6-97d7-5babc9c38c3e">
