### ISSUE TITLE
Ideation: Start voting pop-up after ideation needs different text

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1144]
@ilmartyrk Is it possible to make it so that when you click the 'Add voting phase' button to open the voting pop-up, the text on the front is different depending on whether you are starting a vote from a discussion topic or an ideation topic? 

As texts such as the bit highlighted below will need to be adjusted accordingly. 

If we can't, we'll need to write a text that works for both (though that likely will get a bit confusing/hard to read) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bd22c183-f36b-4b89-b588-736f65d77953)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish yes it can be done

**Comment by BeccaMelhuish** [comment]
@ilmartyrk great, here is the text then please! Change in bold :) 

Are you sure you want to start the topic voting?
Things to keep in mind:

X You can no longer (co-)edit your topic text
X You can't edit a vote once you have started it
X You can only start one vote per topic
**X Participants can no longer add ideas**
V You can still invite and share with participants
V Participants can still continue to have a discussion

From here you can move the topic into follow-up.

**Comment by ssin1901** [comment]
Fixed as per the suggestion by @BeccaMelhuish and closing (screenshot1)
<img width="1233" alt="Screenshot 2024-05-20 at 10 16 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e07c7a2e-bad5-4258-9870-777c8384e2d2">
