### ISSUE TITLE
Ideation: Not many clues after ideation ended

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1146]
Once you end an ideation phase, all the buttons disappear, but there's no clues to anyone who comes to it after it has closed why they can no longer add anything. 

There should be some sort of message, e.g. "The ideation phase has now closed". And maybe the buttons should still be there, but greyed out? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6034bb4b-52c5-4e73-9765-9ee0f9187aeb)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @kevincrepin added the 'pre UX tests' label, in case possible to get fixed before Monday would be nice, but not crucial :)

**Comment by kevincrepin** [comment]
Agreed, not very clear. I'm also wondering why the manage button is gone whereas in voting it's still available after voting ended? Might be a good reason for that which I don't see.

But in any case I think they should both behave similarly:
- a notice at the top to say ideation has ended, what participant can't do anymore and what they still can do.
- I would remove the add idea button entirely, not disable it.

![Screenshot 2024-05-16 at 15 37 46](https://github.com/citizenos/citizenos-fe/assets/26792281/a90bc7d1-8022-4a77-807d-6ecfdac9053a)

Similar to:
![Screenshot 2024-05-16 at 15 39 54](https://github.com/citizenos/citizenos-fe/assets/26792281/20978baa-e0ec-4f7e-9542-e7c07d885300)

@ilmartyrk if this goes, then you can find the figma here: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=13098%3A83247&t=3yt34QVGBQCTs3ip-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin this looks good! 

Text-wise though, if I'm not mistaken (re what they can and can't do at this point, @ilmartyrk please confirm), then I think it should be this:

The ideation has ended!
A topic admin has closed the ideation. You can no longer add ideas, but you can still read, reply, favourite and upvote them. 

(Not mentioning voting here, as that's a separate phase if the admin chooses to start a vote). 

Though also, I've assumed they should still be able to do this lot: "reply, favourite and upvote", but that's up for discussion/decision-making.. Maybe it should all be locked. I can hopefully get insight on that in the tests though.

**Comment by kevincrepin** [comment]
That's ok and yeah with voting I meant the upvote :) I'm also not sure should it still be possible, but I leave that up to you guys! Copy is updated in Figma ;)

**Comment by ssin1901** [comment]
@BeccaMelhuish here is the view when Ideation is closed (screenshot1) and here is the view when Voting is closed (screenshot2). To me, all looks good but please close the issue if you feel that it is resolved.

<img width="1234" alt="Screenshot 2024-05-20 at 10 12 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0c4aa19a-8025-4653-943c-161a6f29e3a7">

<img width="1225" alt="Screenshot 2024-05-20 at 10 12 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/973481eb-984b-4e6d-86f5-b68790df8104">

**Comment by BeccaMelhuish** [comment]
Looks good! Just for the record, have adjusted the text to 'The ideation has been closed'. And now closing the issue :)
