### ISSUE TITLE
Ideation: UX issue with 'Add your idea' button in folder

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1147]
There is currently this 'Add your idea' button within the folders, that is identical to the one at the bottom: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/66960c5c-4d97-43c7-b9d1-8d7a8d41a4c7)

It takes you to add an idea/s to the folder, rather than to add an idea to the ideation, which is what the bottom one does. 

I'd suggest it's re-named to "Add ideas to folder" or 'Edit folder', to make it clearer what you get when you open it:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5ab97e88-23fb-4d52-bf29-8276132329e4)

Though there is also this 'Edit folder' in the menu here that's currently dead (I think @ssin1901 is reporting that separately), but needs some thought re how these two interrelate (can't have two 'Edit folder' links that do different things, though maybe both open the same window but from different places?): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a34841c5-7433-4725-8369-3e97b711bba6)

**Comment by ssin1901** [comment]
@BeccaMelhuish The Add Idea button is removed from folder section (screenshot1) but present in the idea section (screenshot2). However, it does not Add an Idea to the folder (screenshot3)

<img width="1104" alt="Screenshot 2024-05-09 at 15 39 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a2cd4558-f6ef-4831-b727-22926976cc17">

<img width="1427" alt="Screenshot 2024-05-09 at 15 39 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/65114e8c-7780-4e94-a523-4ff937bf0ec1">

<img width="1430" alt="Screenshot 2024-05-09 at 15 39 30" src="https://github.com/citizenos/citizenos-fe/assets/72747107/295809a6-f334-4826-9885-a6e037017984">

Please close if this UX solution works till the User tests.

**Comment by BeccaMelhuish** [comment]
Yes works well now we have this 'Edit folder' for adding ideas. Closing, thanks! 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/521def53-1583-47c7-9056-028b68fe6ef2)
