### ISSUE TITLE
Ideation: Delete an argument popup when deleting an idea reply

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1148]
Currently when you try to delete a reply to an idea, you get this 'delete argument' pop up.

It should be changed to: 

**Delete reply**

Are you sure you want to delete this reply? This action cannot be undone. 

Yes, delete this reply

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/44e42a5e-6132-43d3-bd9e-37efdd7361ab)

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1433" alt="Screenshot 2024-05-10 at 16 10 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d939c716-9df0-4cfa-a591-4db28c9c8da0">
