### ISSUE TITLE
Ideation: "Character limit" should say "Characters remaining" 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1149]
When adding an idea, it currently says "Character limit" where it should say "Characters remaining" (where I've highlighted below). May be the same for arguments etc elsewhere, I've not checked. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fd4613d4-07af-4664-9684-e30e914c88f1)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish technically this is fixed but to my mind, there is now a character mismatch in the text
<img width="1230" alt="Screenshot 2024-05-10 at 16 30 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b03fb17b-2571-4598-ac23-ff7621c33d6e">

**Comment by BeccaMelhuish** [comment]
@ssin1901 Hmm yes true, and we also don't need it twice, just one or the other :)

**Comment by ssin1901** [comment]
I will close this issue and create a separate issue though, as this issue has been fixed
