### ISSUE TITLE
Ideation: 1 idea and 1 folder grammar correction

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1150]
When there is only 1 idea or only 1 folder, it should be grammatically correct, so with no 's': 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0783eb51-7f5e-4b83-b752-af65f5aba12d)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I guess it should be other way around "ideas 1" and "folders 1"as we already know from @oksk basics with using numbers and wording

**Comment by ssin1901** [comment]
@BeccaMelhuish I think this should work for the time being (see screenshot). Closing the issue.
<img width="1433" alt="Screenshot 2024-05-09 at 15 42 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e6c9ae13-3fa6-4e9c-8634-f4bcbd83b9f0">
