### ISSUE TITLE
Ideation: Can still edit topic text and ideation question once ideation started?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1151]
@ilmartyrk am I correct in thinking this text below is incorrect? 

Admins can edit their topic at any point including during ideation, it's only when they start a vote that it gets locked? 

And just to be clear for text elsewhere - they can also edit their ideation question at any point too, I assume? It's only with voting questions that it's locked? (User feedback from 1 user so far suggests this is the correct logic - ideation question they would want to have flexibility to clarify if users were misunderstanding). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9b6461a2-f47f-4fdb-b6a6-15655d73648b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish currently yes, but I guess it all depends on how we decide to solve the issue with different content in different topic phases and also the order of the flow. This text is directly from Figma

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK thank you! 

I've changed it to this for now then: 
"You can still edit your topic at any point prior to starting a vote."
