### ISSUE TITLE
IDEATION: User taken to wrong view

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1152]
**What is the problem?**
_Tested in Google Chrome_

A user _was invited to a topic with Ideation_  (screenshot1) and saw this view without ideation (screenshot 2)
<img width="777" alt="Screenshot 2024-05-06 at 23 58 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/080c98f6-819b-4264-814a-3bf397b3e2a3">

<img width="1184" alt="Screenshot 2024-05-07 at 00 00 14" src="https://github.com/citizenos/citizenos-fe/assets/72747107/40670018-71e3-4444-b174-31fde3462a78">

User had to login to Redesign and go into My Topics to get the correct view (screenshot3)
<img width="1205" alt="Screenshot 2024-05-07 at 00 06 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/80d2334d-2599-4e2a-a2f6-9b80fba2030b">

**Why is this a problem?**
@ilmartyrk might be due to syncing between Redesign and Test but makes testing more difficult

**Possible solution.**
User should see the correct view

**Comment by ilmartyrk** [comment]
@ssin1901 this is the issue with test and redesign platforms and emails. There is no good solution now, will close the issue as it will be solved when ideation is moved to testing app
