### ISSUE TITLE
IDEATION: Misleading "Days Left"

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1156]
**What is the problem?**
The Ideation "Days left" section is misleading to the users for 2 reasons

a) The yellow bar looks like a progress bar, but does not accurately reflect the number of days left (screenshot1)
b) The number of Days left for a topic without a deadline is random (screenshot2). 

<img width="1063" alt="Screenshot 2024-05-07 at 12 22 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/81ed4979-8485-4619-bade-41a992565712">

<img width="1067" alt="Screenshot 2024-05-07 at 12 27 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e251caa7-2d30-4fa7-9f55-0011ea340c46">

**Why is this a problem?**

Will confuse Ideation participants

**Possible solution.**
a) If the yellow bar is a progress bar, then it should correspond to the number of days left. If there is no deadline, the progress (
"yellow bar") should be 0.

b) No days left should be displayed when there is no deadline.

@ilmartyrk @BeccaMelhuish screenshot from Figma is attached (screenshot3)

<img width="716" alt="Screenshot 2024-05-07 at 12 28 55" src="https://github.com/citizenos/citizenos-fe/assets/72747107/344a43a7-34ea-42e9-a9d0-2c6e7e529ffc">

**Comment by ilmartyrk** [comment]
@ssin1901 it actually had similar logic to voting, but there was a small bug that allowed displaying these numbers when no deadline.

**Comment by ssin1901** [comment]
Fixed and closing (screenshot1)
<img width="1427" alt="Screenshot 2024-05-09 at 15 45 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2e5d0692-ebc0-496d-9c2b-7a320fae82ff">
