### ISSUE TITLE
IDEATION: Idea Rating button is not correct as per the Figma

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1159]
**What is the problem?**
The button for Rating Ideas (screenshot1) does not have the correct functionality as per the Figma. After an idea has been rated, the background is supposed to change.

<img width="1427" alt="Screenshot 2024-05-07 at 13 10 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/29b1af74-a02f-4990-a384-85ed231b7afe">

**Why is this a problem?**
Design mismatch 

**Possible solution.**
Button functionality should be as per the Figma (screenshot2)

<img width="717" alt="Screenshot 2024-05-07 at 13 12 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/dbd1a4f6-2897-47e5-8371-3296637a9e9f">

**Comment by ilmartyrk** [comment]
@ssin1901 good catch I didn't notice that in Figma

**Comment by ssin1901** [comment]
It was actually @BeccaMelhuish who caught it!

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1172" alt="Screenshot 2024-05-09 at 15 46 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/59a6b3d2-dd3f-4a52-bbc5-d60af0f2c628">
