### ISSUE TITLE
IDEATION: Inconsistency regarding Discussion

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1163]
**What is the problem?**
Under Create menu, Ideation feature is explicitly described as having no pro or con discussions available (screenshot1)

Yet Discussion feature is still present even though the Topic was created as an Ideation topic (screenshot2) 

<img width="1420" alt="Screenshot 2024-05-08 at 13 21 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1176e4f5-70d9-4d9a-8a6e-5b88a978d6d1">

<img width="1422" alt="Screenshot 2024-05-08 at 13 22 04" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a890a4d3-6999-4022-9076-de236413fe96">

**Why is this a problem?**
Incorrect descriptions confuse the user and also product support 

**Possible solution.**
Either the text needs to be amended or Discussion removed from topics that are created as Voting or Ideation topics.

**Comment by BeccaMelhuish** [comment]
Fixed in text review so will close :)
