### ISSUE TITLE
IDEATION/AF: idea folder creation updates displaying incorrectly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1169]
(In redesign)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bb1f4708-b759-42de-a770-1dc724ef513c)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish closing as it is basically duplicate of https://github.com/citizenos/citizenos-fe/issues/1126
