### ISSUE TITLE
IDEATION: 'No ideation yet' block should be removed for discussion and voting topics 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1173]
When a user creates a discussion topic, this 'No ideation yet' block shouldn't be there (as it's not relevant to discussion blocks in the current flow). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/08282a1c-5b83-4797-9a36-10cad20f8257)

**Comment by BeccaMelhuish** [comment]
Same for voting topics: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f314f911-ed9a-4b83-aef0-59ca202fecab)

**Comment by ssin1901** [comment]
View has been fixed (see screenshot) and closing the issue.
<img width="1426" alt="Screenshot 2024-05-13 at 15 51 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e0f3dbcf-435d-4a13-a1e0-f9c9208ec101">
