### ISSUE TITLE
IDEATION: Add in ideation to notifications text

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1177]
@ilmartyrk please add in text for whatever ideation notifications there will be :) 

Maybe you can let me know what notifications get sent for (ideas, replies, 'upvoted' ideas, new folders, favourited, deleted ideas, etc? not sure it should be for all of them?) and then I can check the text?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c284c3a8-592e-420e-a5ff-a66c63833d73)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk checked but not seeing it? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b1901b13-28f5-46b0-b55a-8a09b77a92f2)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I've re-opened again as still don't see it in the list :)

![image](https://github.com/user-attachments/assets/be7d4cf0-a160-4073-b161-eeed0978e630)

There should be a row saying: 

_Idea gathering (ideas, replies, reactions)_

**Or,** if it's not separated out from discussion notifications, then we'd need to change the 'Topic discussion' row copy to:

_Topic contributions (ideas, arguments, replies, reactions)_

One or the other, whichever is relevant to how it works :)

**Comment by ilmartyrk** [comment]
Added Ideation as a separate item in the list for translations, technical side will still need some work as the whole notification system needs some work

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk I guess this would need to be tested in the test environment?

**Comment by BeccaMelhuish** [comment]
@ssin1901 I'm also getting confused which place to test at the moment so am just checking both if I don't find it in test :D 

This one is showing in test though: 
![image](https://github.com/user-attachments/assets/46f6c714-df19-490f-a978-e05fa693c24e)

But @ilmartyrk, just to check what did you mean about the technical side - is that [this issue](https://github.com/citizenos/citizenos-fe/issues/1212), or something else? :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish the idea gathering text is there (screenshot1). I think we can move to Done as it is a separate thing from functionality, for which a couple of issues have been raised.

<img width="1344" alt="Screenshot 2024-09-25 at 22 23 19" src="https://github.com/user-attachments/assets/cff00af8-554a-4822-a141-f6e77b944cd4">
