### ISSUE TITLE
DB: Add in ideation texts to logged out dashboard

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1178]
@ilmartyrk texts/blocks need adding here :) 

Have reviewed the texts in the strings, so just need adding from there: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7a03e15f-7658-403e-80f4-c87941e05d42)

**Comment by ssin1901** [comment]
@BeccaMelhuish this went into the testing column but not sure what I should test. Can you help me?

**Comment by BeccaMelhuish** [comment]
@ssin1901 checked and mostly all good, it was just to add these bits in yellow :) 

But @ilmartyrk one small thing, could ideas be before discussions, as would be good to keep the order consistent throughout - should help reinforce the topic phase order logic in user's heads :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/83b01a6f-918a-4bf1-8b1e-66bc0e62f36a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed and closing
