### ISSUE TITLE
IDEATION: Most 'illuminating' ideas should be shown first

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1180]
@ilmartyrk According the design/text, should be the case, but doesn't seem to be currently. Will we make this happen initially, or should I edit the text to match how it currently is? 

What the text says: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2dafd529-2b8b-4ac8-82ac-18ffe60b9e55)

Tried it out, didn't show my liked one first (after refreshing): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/141bf18b-bf8a-4445-aad7-b28ec3f5cd20)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the default ordering it will now order using 3 components 1 is votes count second is replies count and third is creation time

**Comment by BeccaMelhuish** [comment]
@ilmartyrk grand, if have understood correctly, that sounds good! And tested - my liked idea now shows first, so will close :)

**Comment by BeccaMelhuish** [comment]
Oh sorry @ssin1901, you probably need to QA test this, reopening :)
