### ISSUE TITLE
VOTING: Min votes text is missing 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1183]
**What is the problem?**
_Tested in Google Chrome_

In our Test app, the voting required a minimum of two votes (screenshot1) but the text only mentioned maximum votes (screenshot2)
<img width="1427" alt="Screenshot 2024-05-14 at 11 35 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e4da9045-726f-46c5-b122-0cbea5225c9b">
<img width="1237" alt="Screenshot 2024-05-14 at 11 35 32" src="https://github.com/citizenos/citizenos-fe/assets/72747107/aec99c83-1345-4ae5-9c64-94e667c4e590">

**Why is this a problem?**
User did not realise that the Submit vote button was greyed out as two options need to be selected.

**Possible solution.**
Text about min votes should be added

**Comment by BeccaMelhuish** [comment]
@ilmartyrk If there is a minimum, then the text should be: 

You can choose minimum X options and maximum X options.

**Comment by ilmartyrk** [comment]
est dev time 5 min. "PREVIEW_VOTE_TYPE_MULTIPLE": "This is a multiple selection voting. Please choose {{range}} options."

if max and min are different then range eg. 1 - 2 . if same then only the value.

**Comment by BeccaMelhuish** [comment]
Checked and all good, moving to Done :)
