### ISSUE TITLE
VOTING: Topic talked about Discussion when there was no Discussion

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1184]
**What is the problem?**
_Tested in Google Chrome_

In the Test application, the topic talks about a Discussion when there is no Discussion in the Voting Topic (screenshot2)

<img width="1429" alt="Screenshot 2024-05-14 at 11 38 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4c96bdd8-c20a-4181-b2b1-994059755356">

**Why is this a problem?**
Confusing communication, as in general there should be no Discussion references or Discussion tab in a Voting Topic.

**Possible solution.**
Remove references to Discussion

**Comment by BeccaMelhuish** [comment]
@ssin1901 good catch thanks! Please tag me if it's anything text related and add a 'text review' label if possible :) 

@ilmartyrk can we have different pop-ups here, with different texts depending what kind of topic it is? If so will provide the texts :)

**Comment by ssin1901** [comment]
Closed as issue is a duplicate of #1595
