### ISSUE TITLE
TOPIC: Add to Group should be moved from Topic settings

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1190]
**What is the problem?**
Topic Settings -> Add to Group is taking up a lot of screen space, especially when there are no groups to display. This is the view seen by user who hasn't joined/created any groups (screenshot1).

<img width="1173" alt="Screenshot 2024-05-14 at 13 52 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1031cd66-fc1c-4877-8ed2-b3755ed912cb">

**Why is this a problem?**
1. Confuses the users

**Possible solution.**
Currently there are multiple places where users can Add Topic to Group. Either we could remove it or implement the suggestion by @BeccaMelhuish to add more explanation about what a group is. Not a priority for now, will await input from @BeccaMelhuish

**Comment by BeccaMelhuish** [comment]
@ssin1901 initial thoughts are that I'd disagree that it should be removed from here, as I've seen in the user tests that it's an important moment for them understanding that groups exist, what they are, starting to think through whether they want to use one, etc. But we can have more of an explanation indeed, will come back to this when more time :)
