### ISSUE TITLE
IDEATION: Internal Server error for Reporting an Idea 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1191]
**What is the problem?**
User encountered an Internal Server Error after Reporting an Idea (screenshot1). 

<img width="1071" alt="Screenshot 2024-05-14 at 14 00 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/99658aca-4a54-4846-aa87-7fa66db32bfc">

**Why is this a problem?**
User could not report an idea

**Possible solution.**
User should not receive an internal server error

**Comment by ilmartyrk** [comment]
@ssin1901 does this still happen? I think it might have had something to do with missing translations as I cannot replicate it

**Comment by BeccaMelhuish** [comment]
@ilmartyrk as requested in [this](https://github.com/citizenos/citizenos-fe/issues/1278), the test was on Monday 27th from 14.-15.30 your time :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish didn't get the Internal Server Error for reporting own (screen recording1) or other's idea (screen recording2). 

https://github.com/user-attachments/assets/0a3b33fe-2915-4dcc-8147-d2b453617b2c

https://github.com/user-attachments/assets/c781b0b9-43c3-4388-9760-0feeb5546040

@BeccaMelhuish – was it expected that the user gets some kind of notification that the topic has been successfully reported?

**Comment by BeccaMelhuish** [comment]
@ssin1901 yes though there's another issue for that already (https://github.com/citizenos/citizenos-fe/issues/1330), so I guess this can be closed :)
