### ISSUE TITLE
Discussion: What it means to 'add a discussion' phase needs thinking through - potential for messiness/confusion

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1192]
_@ilmartyrk @kevincrepin I feel like this needs some thinking through re adding phases - as in this case an admin can't actually 'add' a discussion phase, they can only launch a discussion phases by adding an argument. And it also means a participant can add a discussion phase when the admin hasn't intended there to be one, by simply adding an argument. Feels like potential for quite some messiness/lack of control by the admin, which in some cases could be problematic/mess up the process.._ 

_Originally posted by @BeccaMelhuish in https://github.com/citizenos/citizenos-fe/issues/1172#issuecomment-2110643110_

**Comment by BeccaMelhuish** [comment]
Re this bit: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4ad663e5-d5ce-4486-afbc-6a321259782c)

And this bit: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/40b1abbd-0b55-4d88-888f-369322105230)

**Comment by kevincrepin** [comment]
Oops, first replied in the closed issue :)

So, maybe I'm misunderstanding but I think we have this logic already in place, just for the other phases?

What admin sees until they've added the phase/initiated it:
![Screenshot 2024-05-15 at 12 11 23](https://github.com/citizenos/citizenos-fe/assets/26792281/f663f666-0fc1-4e84-8a2b-5d0396afee7a)

What participants see before admin adds/initiates phase:
![Screenshot 2024-05-15 at 12 17 17](https://github.com/citizenos/citizenos-fe/assets/26792281/22cc1d07-4dae-4cdb-86ae-e82cff9a818c)

Could it not work the same here?

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ah brilliant yes that seems a good solution! 

So in this case, this button view for admins (and editors? if relevant to them?) would be something like:

**Add discussion**
Discuss the pros and cons

(And for participants just 'No discussion yet')

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cb10fb75-6ed1-49be-bc79-da0195a6fb84)

**Comment by kevincrepin** [comment]
Sounds good to me!

**Comment by BeccaMelhuish** [comment]
@ilmartyrk will add pre UX tests label if possible :)

**Comment by ssin1901** [comment]
@BeccaMelhuish here is admin view (screenshot1) and participant view (screenshot2). Heads up – both admins and participants can introduce Discussion to the ideation topic.

If the fix is as per the discussion, please close.

<img width="1244" alt="Screenshot 2024-05-16 at 16 52 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/82405c06-efd5-4589-bc4b-d4a02f15659f">
<img width="1213" alt="Screenshot 2024-05-16 at 16 58 53" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e6bfa89c-26c1-48a0-87b6-fe02d8ec087a">

**Comment by ilmartyrk** [comment]
@BeccaMelhuish check the solution and please check the copy, created a similar solution as starting voting or follow-up. Also disabled adding arguments to ideation topic

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Went through it from both perspectives and a few things needing adjustment:

- I made an ideation topic, invited my other account to it, then started a discussion phase. I then went into the topic as a participant, and could only see 'No discussion yet' with no possibility to add an argument. 

See screen recording here: 
https://www.loom.com/share/6187bdafa8e543f39faa82702830fbc4?sid=37a3d661-64a4-4980-a8c3-908f6e8b18a1

- Here for the admin let's have it as 'Start discussion phase'

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3522d968-c10c-4778-9c66-89dd83e16115)

- This is probably something for after the testing when we have the process insights, but I'm wondering if we definitely want to close the ideation as a result of opening the discussion. As it may well be they sometimes need to happen in parallel..

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3f392a0b-f99a-4fee-adfe-a8d97739c21b)

- But assuming we keep this as the flow for the tests, then the text needs some adjusting. (My understanding of what is/should be possible still, please correct me if wrong). X for cross and V for tick. 

_X Participants can no longer add, edit or upvote ideas_
_X You cannot restart ideation once it's closed_
_V Participants can still favourite, reply to and report ideas_
_V You can still add ideas to folders_
_V You can still invite and share with participants_
_V You can still add a voting system and follow-up updates_
 
_This is the next stage of your topic. You can now discuss the collected ideas, before moving on to voting or follow-up._ 

- Clarifying the different 'no discussion yet' views for participants

In this bit, it seems we need different views/texts, depending on whether there is 'no discussion yet' because the admin hasn't added one, or because no-one has added any arguments yet. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f6795bcf-8cbc-48da-94b2-f7d373306541)

**For when the admin hasn't yet added a discussion phase - for both participant and admin view:** 
(Changed bit in bold)

_There is no discussion yet_

_How discussions work_

_In discussions, participants can add pro or con arguments, and other participants can reply or react to these. The general sentiment of the discussion is shown visually._

_Arguments can be favourited or recognised as including proof._

**_There is currently no discussion phase for this topic. To have one, this phase must be started by a topic admin._** 

***

**For when the admin has added a discussion phase but there are no arguments yet - for participant view:** 
(Changed bit in bold)

**_Get the discussion started!_**

_How discussions work_

_In discussions, participants can add pro or con arguments, and other participants can reply or react to these. The general sentiment of the discussion is shown visually._

_Arguments can be favourited or recognised as including proof._

**_The discussion is open, but no-one has posted any arguments yet. Be bold and be the first to post one!_** 

***

**For when the admin has added a discussion phase but there are no arguments yet - for admin view:** 
(Changed bit in bold)

**_Get the discussion started!_**

_How discussions work_

_In discussions, participants can add pro or con arguments, and other participants can reply or react to these. The general sentiment of the discussion is shown visually._

_Arguments can be favourited or recognised as including proof._

**_No-one has posted any arguments yet. As topic admin, get the discussion flowing by posting some yourself!_**

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the texts

**Comment by BeccaMelhuish** [comment]
Thanks @ilmartyrk!

Checked it over and just a few things :) 
 
1. As a participant, am seeing this button:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/158b3a44-eee1-40d2-8f48-73645c6589dd)

2. Let's have these lines at the end in just regular text, not bold: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/976d2771-f68a-433f-b49c-1a3a841acd7e)

3. Get the discussion started

Sorry, I forgot to mark with bold the two bits that should say 'Get the discussion started!', now marked bold in the previous comment, please see above! 

Tagging @kevincrepin in case he disagrees with any of this, but I think it will help the different roles understand what's going on / what's possible and what they need to do next :) 

And just for info, I've changed this text to this below (was a bit clunky previously): 

'There is currently no discussion phase for this topic, but topic admins can start one once the ideation ends.'

**Comment by BeccaMelhuish** [comment]
Oops forgot to move it back to 'In progress', @ilmartyrk if possible to prioritise this one before the next test (tomorrow at 14.00) would be perfect :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish moved to testing

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Text looks good, but how about the 'Get the discussion started' for when there has been a discussion phase added, but no-one had posted any arguments yet? :) 
(For both admin and participant) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/499fed96-0c50-4d14-938d-5ce656bee9d0)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1048e9b8-368a-4ccd-bb8c-fac64bc96675)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I just noticed that it's not quite right yet - in a topic for which I'm admin, but I haven't yet added a discussion phase it currently says this, and has a button to add an argument: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/98afa5f6-95ed-4a39-8473-ddc12a45e44a)

But for admins it should be like this below.
And for participants it should be like this below but without the button. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ed51626c-74a6-4104-8dff-9f34647d6dbf)

**Comment by BeccaMelhuish** [comment]
Ah, and then I added a discussion by clicking 'Add argument' which brought up the 'Start topic discussion' box. But once I had done this then the button was the below, when it should say 'Add argument'. So it seems they are muddled up? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/154a2034-cc33-4057-b1fa-8a8f3b60d212)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Looks like it's getting closer now but 2 things not correct currently for me: 

For everyone when there's not yet been a discussion added by an admin yet it should say 'There is no discussion yet' here:
(Checked and currently has this heading for both participant and admin)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7c54e8da-4bf4-4912-ac5e-5c44fd052078)

And for participants, when there _has_ been a discussion added, it's currently saying all the right things, but the button to add an argument is greyed out (but shouldn't be):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3c30b732-53f3-409c-b4e5-ac2ea994e7cf)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
All seems to be as it should be, closing thank you!

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Still not quite right here though sorry - I checked in a topic both as admin and as participant, where I haven't yet added a discussion phase, and it currently says this, but should say 'There is no discussion yet':

(It's only 'Get the discussion started' for when there is a discussion phase open). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ad47fde2-b5c1-4f5f-af22-a358ac6d9299)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I don't understand this request, I see that there is already discussion question in place so there should be discussion going on.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk ah no the 'test image' is just the title that has been pulled from the topic (see [this issue](https://github.com/citizenos/citizenos-fe/issues/1318) re that happening), there's actually no discussion added yet (see 'add discussion' block):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1d5c5949-e527-4deb-8182-862b1f77d14d)

**Comment by BeccaMelhuish** [comment]
Checked again from participant side now, and the heading is right, but button should be greyed out. All looking good for admins though :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/36469b74-65bb-4a09-92b1-1d3230b27ab9)

**Comment by ilmartyrk** [comment]
Oh I see, this is actually a migration issue with already existing topics, will check what to do with that

**Comment by BeccaMelhuish** [comment]
Ah OK yes makes sense! For testing only greying out the button is priority then I think (though sometimes they do check old public topics)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish cleaned it up and also removed the button if not admin as on other tabs (voting, follow-up)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk one more thing on this - I spotted that in the IOF topic (which starts with discussion), it says this (which is the text for when the admin hasn't yet added a discussion phase), but should have the 'Get the discussion started' texts instead (with the 2 different texts for the admin and the participant versions).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6a05c5c6-3157-4f26-a3df-2180645337eb)
