### ISSUE TITLE
IDEATION: Error message too early on adding second idea

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1193]
When I go to add a second idea, the pop up starts off looking like this. Error message shouldn't be there yet, too soon. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e876caf4-e888-4bc1-bfed-4982bb463bfe)

**Comment by ssin1901** [comment]
Seems fixed (screenshot1) but the error will come when you click on the fields, and then will pop up every time you close and try to add the idea (screen recording)

<img width="1246" alt="Screenshot 2024-05-17 at 00 17 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7ef541e2-570b-48b5-a009-2652f1a6942b">

@BeccaMelhuish @ilmartyrk if it is fine, then I will close it but please check the recording as well.

**Comment by BeccaMelhuish** [comment]
There's still a minor problem with it but I think it's low priority :) 

https://www.loom.com/share/14f3096980cd454fa673f1bd72669657?sid=cf45472e-660f-4fb0-8e42-4ab79922695e

**Comment by ssin1901** [comment]
@BeccaMelhuish I think it looks alright now, but please check! (screen recording attached)

https://github.com/citizenos/citizenos-fe/assets/72747107/e7642088-831f-4a18-b412-47cf3b4acdab

**Comment by BeccaMelhuish** [comment]
Looks good from the recording thanks! Closing :)
