### ISSUE TITLE
FOLLOW UP: Invited user sees "Create an update"

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1195]
**What is the problem?**
In the Redesign app and replicated in Live App, a user who was invited to a Topic, saw this "Create an update" view (see screenshot)

<img width="1106" alt="Screenshot 2024-05-15 at 10 28 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3ce48b5d-8a95-48d4-9852-4fac93708e44">

**Why is this a problem?**
Misleading to the user

**Possible solution.**
@oksks @BeccaMelhuish maybe the text could just say "Updates"?

**Comment by BeccaMelhuish** [comment]
Yes if @ilmartyrk could just change it to 'Updates' as a quick fix for now, but keep the topic open as would like to have more of a think - as I think we might need something that gives more of an explanation to users of what this bit's all about. Or maybe there's something in the design already :)

**Comment by oksks** [comment]
This string is also being used elsewhere, I've just checked to see if could fix this myself - @ilmartyrk, could you split up this string into two? And keep the descriptive one as "Updates". Thanks!

**Comment by ilmartyrk** [comment]
@ssin1901 @oksks posted a fix, basically switched the title for the main block and the input form

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1402" alt="Screenshot 2024-05-21 at 12 30 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fbab53d4-01c9-4648-88ec-60307c35127a">
