### ISSUE TITLE
FOLLOW UP: Milestones and deadlines not displayed 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1196]
**What is the problem?**
Under a Topic in Follow-Up, Milestones and deadlines are not displayed (screenshot1)

<img width="925" alt="Screenshot 2024-05-15 at 13 31 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ebc5da56-3462-4d61-ac71-9ee16fb9e9c1">

**Why is this a problem?**
User would expect to see these updates

**Possible solution.**
User should see these updates

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk my apologies, was fixed some time ago. Screenshot(screenshot1) and closing.
<img width="1006" alt="Screenshot 2024-05-21 at 12 28 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a30e5f54-db9d-4a65-8bfc-50628a9cc638">
