### ISSUE TITLE
IDEATION: Ideation button in home page does not work

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1198]
**What is the problem?**
The Ideation button in the home page does not work (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/b83f57ac-1cb7-402f-bf4d-dfc74eb4bed8

**Why is this a problem?**
User cannot use this shortcut

**Possible solution.**
Clicking on the button should take logged in user to Create Ideation view. Logged out users should be prompted to login.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk added pre UX tests label to this one, if possible :)

**Comment by ssin1901** [comment]
Fixed and closing (screenshot1, screenshot2)
<img width="1438" alt="Screenshot 2024-05-16 at 16 46 53" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a585acb5-ac47-4551-bebe-440eb764c23b">
<img width="1245" alt="Screenshot 2024-05-16 at 16 47 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d0232283-9386-4397-a28c-53ee8def3cc6">
