### ISSUE TITLE
MISC: Mock help tooltips for testing their need and content requirements

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1200]
@ssin1901 and I have mapped out possible areas for Help tooltips and guidance notes to be added to relevant places in the platform, in the place of the Help Centre, which we currently don't have. (@ssin1901 I added a couple more than what we agreed, as no harm in testing so can decide based on evidence :))  

The idea is to test the need for these during the ideation testing (by seeing if users click on them and asking what help they were after if so), which is rather close now (starting Mon 20th), but if possible to add some of these, would be a real help. If it has to be partway through the testing process that they show up though (i.e. not by Monday) that's fine too. 

@ilmartyrk would it be possible to add dummy tooltips all with the same text: 

**Help on its way**
Help text coming soon! Please tell us what help you were looking for. 

**But all these changes should only ever (until decided upon, and real texts added) be seen in the testing environment, not live :)** 

- [x] Show my name and email (x 2 locations)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/aaf6a1a5-4554-4613-a828-a0143c7bb84f)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8c5ae79d-dcaf-4939-aae1-4ca3ab0b824d)

- [x] Upload a header image
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/967ce555-9641-442a-84af-c6f3d8bc0915)

- [x] Topic visibility
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d0980174-7686-4069-989c-a4d03e0c9678)

- [x] Country and language
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0c70fc21-491a-48f1-86d6-f53ef8cce92a)

- [x] Add to group
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fde76d2c-0884-4300-897c-8f1d77cf894c)

- [x] Neutral and Veto
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e8b9fa6b-614c-4aeb-aa8b-1da765fc8c09)

- [x] eID voting
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dbc41b8f-248d-41ca-8b4d-b76d4f1589dd)

- [x] Download BDOC
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/829edd28-9e07-4f1a-8560-f7906ed6752c)

- [x] Manage notifications
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/484abaa0-4c47-4b0a-8916-542cda12e3ef)

- [x] Request to add topics to group
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d1429acb-b075-4083-9372-27f2f816e210)

- [x] Download vote results
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c0d89c8e-5a07-475a-9760-297e83315809)

- [x] Invite co-editors
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4c237968-16d2-4740-ac86-522137499337)

- [x] Group permissions
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1942763f-aad8-4f5b-9c9e-c68451d903e5)

For this one, please add headings 'Name', 'Rights', 'Actions' so that the help button can be next to the 'Rights' heading. (Ignore crossed out bit). Just for testing. 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5e7953ca-b6a7-4670-8afe-e0392ae3c661)

- [x] Topic permissions
For this one, please add headings 'Name', 'Rights', 'Actions' so that the help button can be next to the 'Rights' heading. Just for testing. 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/44b1200e-9f87-438d-8934-583e64ec46ec)

- [x] Topic description
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f5b093d8-727a-4f85-b805-ace67160a6a9)

Same for this one.
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fe45fe4f-bf47-4165-9c9d-0e115f19df23)

This one just add button. 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/63af6f11-d811-4ed5-9997-f1649deb8b9f)

- [x] Add to ideation folder
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4085434b-9384-4754-9122-864ccf5ad81c)

- [x] Start topic vote
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0c7bf50c-ac08-4368-b2fd-5ffced4ba440)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added most of them, but there are differences between real world and Figma images you used eg. download vote results. But I guess it doesn't make too much of a difference

**Comment by BeccaMelhuish** [comment]
Awesome thanks @ilmartyrk! And yes if slight differences to screenshots shouldn't matter :) 

It wasn't possible on 'manage participants' window though, or that one will be added later?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish manage participants was more work so I left it last. I started with easier ones, but now implemented to all places you suggested

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish have a question about this tooltip (screenshot1). 

<img width="1438" alt="Screenshot 2024-05-19 at 14 19 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/79ed9332-60d7-44b6-ab48-32d5bcbc81dd">

@BeccaMelhuish are we leaving it like this for the testing? To see if the users click on it?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Yeah exactly, all these ones in this thread will be like that for the tests - if they click it I'll ask them what guidance they were looking for at that point, then we can write the ones that are necessary :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk minor adjustment on this one, could it be moved to the end of the sentence (as the help will likely re related to downloading rather than the vote ending) :)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d12a8eb2-8573-4621-9c59-7889c804c712)

**Comment by BeccaMelhuish** [comment]
Doesn't need fixing as was only for the mock ones, but just for reference when we come to add more genuine ones, some of them were getting misplaced on mobile (iPhone, Safari): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8f190e46-43b5-45d8-bc06-27b726ed4fe9)

**Comment by BeccaMelhuish** [comment]
Closing this one
