### ISSUE TITLE
IDEATION: Ideation says closed but ideas can be added

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1201]
**What is the problem?**
Topic admin saw that ideation has been closed, but they could still add ideas (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/c9297c6f-fe76-4ab7-8651-691d8195c41c

**Why is this a problem?**
Will confuse the users and affect the ideation process as new ideas will appear, despite the user being informed that ideation is closed.

**Possible solution.**
User should not be able to add ideas, if the ideation is closed.

@BeccaMelhuish probably needs the pre ux label

**Comment by BeccaMelhuish** [comment]
I think this one is fine if it's still happening in the tests, I can explain :)

**Comment by ilmartyrk** [comment]
@ssin1901 this seems to be wrong video as it is not what the issue describes, but I've fixed this error poping up

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1368" alt="Screenshot 2024-06-04 at 20 49 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/48bd6579-7980-48a6-ad7f-8c59fe30722d">
