### ISSUE TITLE
IDEATION: Ideation closed message when there is no deadline

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1202]
**What is the problem?**
When there is no deadline added, user is notified that the ideation is closed (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/bf210c2a-cc16-42a6-af69-91dae7a92b7e

**Why is this a problem?**
Users can add ideas, so not critical. However, it is probably very confusing for the users.

**Possible solution.**
When there is no deadline, topic admin should be able to manually close the ideation. 

@BeccaMelhuish probably needs pre ux label

**Comment by BeccaMelhuish** [comment]
Added pre UX tests label though it's not crucial if the functionality still works, I can explain the bug in the tests, that it shouldn't say that :)

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish my bad, I forgot to add condition for that message, closing the issue as it is fixed

**Comment by ssin1901** [comment]
@ilmartyrk in Google Chrome, the ideation closed is replaced by this string
<img width="1440" alt="Screenshot 2024-05-16 at 16 49 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8fdf39bc-2564-4a21-84d4-ed0f1baa3120">

**Comment by ssin1901** [comment]
Fixed and closing (screen recording1, screenshot1)

https://github.com/citizenos/citizenos-fe/assets/72747107/ec348650-5715-46e6-b87d-aca497fcc995

<img width="1185" alt="Screenshot 2024-05-22 at 01 00 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f54f619d-0154-4fca-8bdf-ec8375eeb43d">
