### ISSUE TITLE
IDEATION: Idea actions should be greyed out if not possible

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1206]
E.g. 'Edit idea' and anything else in this menu that isn't possible:
(Though I guess which should/shouldn't be possible is still open to discussion/decision - I can get insights in the testing) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7902a55e-013e-401a-b023-3ea91ef8d154)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish you can edit your idea

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Oh OK, I got 'Insufficient permissions' when I tried, just tried again and got the same:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/549f91f8-d482-4ba6-b5ac-0b8baba2f936)

I feel like it could make sense for you to not be able to once it's closed, though I'm not sure.. Will ask users in the tests :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I've hidden away the actions as we don't gray them out in dropdowns

**Comment by BeccaMelhuish** [comment]
Closed as checked on a closed ideation and looks good to me
