### ISSUE TITLE
IDEATION: Text adjustment to ideation closed text 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1208]
@ilmartyrk, if this list I proposed in [this other topic](https://github.com/citizenos/citizenos-fe/issues/1192) is correct (please check :)) then we need to change the second sentence of the 'Ideation has closed' text to: 

_You can no longer add, edit or upvote ideas, but you can still read, reply and favourite them._ 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3901a56d-a3a6-400d-9dcd-68541b69f3eb)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/006f0a69-aba2-4434-8f78-296821ad5b02)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the text
