### ISSUE TITLE
Voting deadline is incorrect in vote reminder emails

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#121]
**What is the problem?**
When a user sets a vote reminder, the topic participants get an email reminding them to vote before the deadline. However, this deadline is different from the actual voting deadline which is displayed correctly in the the topic participants topic view (screenshot attached) but appears incorrectly in the voting reminder email (screenshot attached).

<img width="1153" alt="Screenshot 2023-05-11 at 21 47 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8e85566f-a9e3-43bd-a758-915acfcaf306">

<img width="1003" alt="Screenshot 2023-05-11 at 21 48 10" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bc214509-8bc5-4519-a72c-1ee14455415c">

Also might be connected with this issue https://github.com/citizenos/citizenos-fe/issues/90

+ add screenshot / screencast whenever possible

**Why is this a problem?**
Users will be confused about when the voting deadline actually is and this will negatively impact the whole flow of the discussion and voting.

**Possible solution.**
Date and time should be the same

**Comment by anettlinno** [comment]
Triage 85. As a quick fix, let´s take out voting deadline from the e-mail as we cannot provide false information for Users. 
Please change to copy to: 
"Vote for the topic _Topic _name__ is ending, don´t forget to cast your vote" @sara please check if this is OK copy :)

Sending this issue for further investigation to find good solution how to fix the issue.
