### ISSUE TITLE
GROUP/TOPIC: Incorrect and misleading text in Topic->Add Topic to Group

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1211]
**What is the problem?**
@ilmartyrk @BeccaMelhuish almost flagged this is as an important permissions related bug due to misleading text.
 
If a user has Member only permissions for _a Public group_ then they cannot Add Topic to Group from Settings. The text indicates that simple Joining a Group will allow them to add the topic to the group (screenshot1). 

<img width="1440" alt="Screenshot 2024-05-17 at 17 19 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b1838bc2-4ad8-4c36-be18-58f74c2368e9">

However, that applies only to Private Groups.

**Why is this a problem?**
Really confusing for the users

**Possible solution.**
Can we add the word "Private" to this view?

**Comment by BeccaMelhuish** [comment]
Hi @ssin1901 so sorry I lost track of this one, coming back to it now!

Here's what I suggest we do to solve this, the (i) being a help tooltip, in which the italic (i) text would be shown. (The reason for suggesting it as a tooltip is that it gets a bit overwhelming to have too much info and in the main text, and it'll only be important for some users, who can then choose to open it). 

Wdyt? :) 

**Add to group**
You can add this topic to a group you're part of, either now or later. All topics in a group are shared with its members, and can be shared via the group's public link too. To add topics to a group, you'll need to have the correct rights (i)

_(i) In a private group, anyone can add topics. In a public group, only admins can add topics, but anyone can 'Request to add topics' via the button on the group's page._

**No groups to add yet** 
Once you're part of a group and have the correct rights, you can add this topic to it here. Don’t worry, you can skip this now and still do it later.

**Comment by BeccaMelhuish** [comment]
@ssin1901 I figured you'd be OK with the text changes so have made them myself in the strings (ideation strings though, so not yet live), so then it's just for @ilmartyrk to add the tooltip :) 

@ilmartyrk the tooltip placement would be here (though the text is now different): 

![image](https://github.com/user-attachments/assets/6da797ef-5077-4cab-806f-3323ef90cf76)

And the tooltip text should be:

**Who can add topics**
In a private group, anyone can add topics. In a public group, only admins can add topics, but anyone can 'Request to add topics' via the button on the group's page.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish tooltip should probably have been a separate issue :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish for the tooltip, I should test the test app right?

**Comment by BeccaMelhuish** [comment]
I checked both and don't see it yet :)

**Comment by BeccaMelhuish** [comment]
Checked again today in a few different views in test and it is indeed there, so moving to done :)

**Comment by ssin1901** [comment]
Tooltip present (screenshot1) so moving to Done.

<img width="1206" alt="Screenshot 2024-09-24 at 01 55 51" src="https://github.com/user-attachments/assets/01364c2f-490e-4902-8688-e99ee3471fd8">
