### ISSUE TITLE
IDEATION: Notifications for other idea related actions?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1212]
In my email text review, it seems we don't have email notifications yet for other idea related actions. 

For example:

- Someone has replied to your idea
- Someone has replied to an idea you are following _(meaning they have replied to the same idea as they replied to, so an idea reply thread they're involved in, there might be better wording for that)_
- Someone has upvoted your idea
- Your idea has been added to a folder

I can't think of any others right now, but maybe there are more :) 

The top two seem especially important to add asap I'd say, if we don't already have them.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish yes this is a bigger issue related to activity feed, I have to update, but it is a bigger task.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the activities to the activity feed, (hopefully didn't miss any). I guess they will need a copy review and after that we can also added to the notification emails

**Comment by BeccaMelhuish** [comment]
Grand thanks @ilmartyrk, have assigned myself this for copy review and will update here once done! Please send me the links to the notifications strings on Slack :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I just double checked if had done this, and I think most of it is now OK (made some minor tweaks - in Ideation branch strings though), so this issue can soon be closed.  But I was unsure what this one was referring to? I think 'idea reply field' needs to be clearer, but not sure what it is or why a moderator would be updating it? 

"ACTIVITY_MODERATOR_UPDATE_COMMENT_IDEA": "User <em>{{userName}}</em> (moderator) has updated the idea reply field <em>{{fieldName}}</em> in topic <em>{{topicTitle}}</em>"

**Comment by BeccaMelhuish** [comment]
P.S Re-read and see it can't be closed yet, as next step will be to add the notifications emails as well :)

**Comment by ilmartyrk** [comment]
Est. dev time 16h.

**Comment by BeccaMelhuish** [comment]
I'm thinking we should prioritise pretty early once @ilmartyrk is back, seeing as we do have the 'ideas' option in the notifications list: https://github.com/citizenos/citizenos-fe/issues/1177 (and currently only very few and temperamental notifications from what I understand). Will move it to the top of the column :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk depending on how long it's likely to be until it gets fixed, I think we could hide the option in the notifications in the meantime? As it's currently quite misleading: 

![image](https://github.com/user-attachments/assets/af49ad50-beff-4ca0-a290-156d4c0205ba)

**Comment by ilmartyrk** [comment]
I've added my estimation, so if I understand correctly I should hide the option for now and we'll solve the issue later?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I think let's still keep the bigger fix as a high priority (as participants knowing when someone has replied or reacted is quite important to topic engagement actually happening, and will be important for admins too), but if it's easy to quickly hide the option in the meantime, would be good to do that asap :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I tested in development with adding an idea, liking an idea and replying and I didn't get any notifications come through at all. Waited 10-20 mins, I think they're usually pretty instant?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish check reply here https://github.com/citizenos/citizenos-fe/issues/1690#issuecomment-2549757323

**Comment by BeccaMelhuish** [comment]
@ilmartyrk thank you, all good - closing and moving to pre-live! :)

**Comment by BeccaMelhuish** [comment]
Seems I didn't move it there, doing so now :)
