### ISSUE TITLE
IDEATION: String not retrieved correctly in Activity Feed

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1213]
**What is the problem?**
Some strings are not being retrieved correctly in the Activity feed (see screenshot1, screenshot2)

<img width="1429" alt="Screenshot 2024-05-20 at 10 08 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cd6e9ad9-e2a1-4142-a08d-a605ed804cb3">

<img width="1244" alt="Screenshot 2024-05-20 at 12 05 04" src="https://github.com/citizenos/citizenos-fe/assets/72747107/285f8441-54fe-4a6b-b7f5-1872ef5daf1f">

**Why is this a problem?**
Not important for User Tests. Minor inconvenience to the user.

**Possible solution.**
String should be retrieved correctly

**Comment by ilmartyrk** [comment]
I've added translations for these items, but activities will have a fix that will make all other ideation activities appear later.

**Comment by ssin1901** [comment]
@ilmartyrk one more string just for reference (screenshot1), not sure how urgent it is to fix them 
<img width="1372" alt="Screenshot 2024-05-22 at 01 03 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2b08f769-c0f9-405e-8d31-11804c38e956">

**Comment by ilmartyrk** [comment]
@ssin1901 i removed this activity, as it basically duplicated the next activity after that
