### ISSUE TITLE
IDEATION: Votes should be organised by Folder

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1215]
**What is the problem?**
_Tested in Test App, Google Chrome incognito mode_

Even though the user created Ideation Folders (screenshot1) when they sent the Topic to Voting, all ideas were bundled into "Ideas" and there was no mention of the folders in the voting options (screenshot2)

<img width="1119" alt="Screenshot 2024-05-20 at 12 23 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0bf24c40-7ce6-4638-8769-fee8d78dd84a">

<img width="1440" alt="Screenshot 2024-05-20 at 12 02 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/452e08ec-0e44-44bb-a1d5-428c3724382a">

**Why is this a problem?**
User would expect the folders to appear as voting options

**Possible solution.**
In Figma (screenshot1) the votes in Voting are organised by Folder
<img width="1197" alt="Screenshot 2024-05-20 at 12 15 20" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bf44baec-1f11-4341-adad-1ee8c8cc9622">

@BeccaMelhuish how important is this for the UX tests?

**Comment by ilmartyrk** [comment]
@kevincrepin @ssin1901 @BeccaMelhuish this probably needs UX review as how it should work , should there be option to switch between ideas list, or between folders, how to pick the ideas from folders or list or combined etc. I only implemented the easiest and most logical way for me

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish should we see what comes up in the user tests? Maybe users don't even expect to see folders in voting options.

**Comment by BeccaMelhuish** [comment]
@ssin1901 @ilmartyrk one downside to the testing is that we're not likely to be testing with large numbers of ideas, which is when the folders would be most necessary. I can definitely ask users but agree it seems pretty common sense that they would want to be able to see the folders at this point. 

Something for Kevin to review/clarify the vision for, do you agree @ilmartyrk? If he can come up with a design for how it would work with smooth UX for an ideation with say 250 different ideas, some of which are in folders and some of which aren't (quite possible this would happen)? Maybe it needs a search function added, as well as possible switch between list view and folder view like Ilmar suggests? 

Re timescales, I think if we can get it sorted for some point during the first round of tests (this week and next) would be great, but if not then could be ready for second round, early/mid June :)

**Comment by kevincrepin** [comment]
Admittedly it was probably too hidden but in the prototype you could actually open up a folder:
![Screenshot 2024-05-28 at 17 26 41](https://github.com/citizenos/citizenos-fe/assets/26792281/d7c04c7b-4007-4373-875a-9ab3cfce73ba)

The idea was that you could choose full folder or specific ideas from that folder.

A search in this would make sense yes, but before moving to that we have to think about the bigger concept of dynamic phase adding, ie. there might be multiple ideations within a topic in this case and then from which ideation phase do we get the ideas to turn into votes? Do we allow from all of them? Or would it at this point make sense to not offer that functionality at all and let the users themselves write down the voting options – and it's up to them if they want to include past ideas.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk have added 'pre UX tests' label for this one if possible before Round 2 :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  Found it from the prototype and working on it

**Comment by ssin1901** [comment]
@ilmartyrk folder feature has been implemented but is it ready for Kevin to check the UI against the Figma design?

**Comment by BeccaMelhuish** [comment]
Hmm yes something for @kevincrepin to consider here, what happens when there are some ideas in the folder and some out. This doesn't seem right to me - having them show up twice? I guess only showing the ones in folders within their folders, and the ones not in folders 'loose' in the list below?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dff4a996-3134-4dd2-b49d-011aa80fdbfa)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk some bugs going on here too, it's showing multiple times for me (two views showing the scroll - as above there are actually only 4 ideas and 2 folders):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/38ddda01-1a78-4963-8675-0b2bd3da0b22)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5cf494ba-1ecf-4285-85f3-49b71140f9cb)

**Comment by kevincrepin** [comment]
Uuuh, that's a good one. Because we don't actually move ideas into a folder, it's basically a "clone". In that sense you can have one idea, move it into 5 separate folders and then here you would have 6x the same idea you could select :) 5x in a folder and 1x loose.

I think in any case what should happen is if you select an idea that's across different folders and loose, it should select all of them.

**Comment by BeccaMelhuish** [comment]
Ah right, yes that makes sense! 

So basically, all is working as it should here except the bug @ilmartyrk :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish a clarification – are the idea folders supposed to open up to show the ideas?

**Comment by BeccaMelhuish** [comment]
@ssin1901 yes :)
