### ISSUE TITLE
IDEATION: Summary box should be clickable navigation button like discussion

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1217]
Clicking should take the user to the ideation tab: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0eba86fa-b7c6-4896-9436-8e172ce202ed)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think it works now (see screen recording). Close if works as expected.


https://github.com/citizenos/citizenos-fe/assets/72747107/ba917912-39b4-47ab-9d42-d06a37e5b634

**Comment by BeccaMelhuish** [comment]
Beautiful, closing!
