### ISSUE TITLE
Group: Not possible to right click topic card > open in new tab

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1218]
I tried to right click and 'Open in new tab' for each of these topics, so that I could easily flit back and forth between all of them, compare them, etc. But when I tried to do so, the option to 'Open in new tab' wasn't available in the right click menu on my browser. Is there a way to make this appear for people? Just a hunch (no evidence), but seems it could be useful for users too.   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bc545e4a-af00-4034-b420-f50551d0d5fd)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fix coming with ideation
