### ISSUE TITLE
IDEATION: Adding photos (ideally multiple) and other resources (links, documents, videos, etc) to ideas 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1219]
@ilmartyrk I'm guessing the 'add image' function for ideation is more complex and so will come later? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2ee73de7-c0b5-4cef-97d9-384895e6e0c3)

But when it does, @kevincrepin @ilmartyrk, an insight from the one prototype test I did would be that she would want to be able to add multiple images to her idea, rather than just one. (She was making a suggestion for cycling improvements along her route to work, and wanted to be able to add a few photos of various places on her route where the problem she wanted fixed arises). 

And some insight from the Viimsi PB would be that it seems they found it useful to be able to add the photos in among their text rather than as an attachment. (Not a solid insight, as maybe they only did it like that because that's all they found how to do, but it seems to make sense that they would when you look at their issues - e.g. this one: https://app.citizenos.com/en/topics/78e4d06f-6b9b-4041-bc31-c4de588abe09#discussion but also a few others).  

I will also ask more about images in the Round 1 tests, so can add more insights when they come :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk 

**Insights from Round 1 ideation admin UX tests** 

- Users are very keen for photos. Most brought this need up on their own. 

- One user brought up a lot how 'text focused' our platform is and that for his processes it would need to be more image focused. Some things he suggested:

(1) It should be possible to add photos to the ideas. Others said this too, though mixed views on whether it needed to be in the body of the text as well as an attachment. General preference for the body though, to make it easier to see them. Some said could be both.   

(2) There could be a kind of cover photo for the idea cards. e.g. in this space somehow (though mixed views on the empty spaces here - this user didn't like the 'sameness' and 'boringness' (my words to sum up his thoughts) of the empty space in the cards, and wanted it filled with an image or a bit of the idea text, but another user mentioned liking the cleanliness of just the headings):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fd920346-6580-402f-928f-d71a12fe856a)

(3) He would want to be able to upload images for the voting too. E.g. vote on which design you would prefer. (Not sure if he had thought of putting the images in the topic text, with a number linked to each for voting. Maybe he'd be OK with this if he had. But regardless, there was a strong message from him that imagery should have more importance in our system).  

- Another user mentioned wanting users to be able to add images to their replies too. For example: Someone suggested a garden. She'd ask them if they had an inspirational photo to share. They could then attach one to their reply. (And maybe someone else could share a different one in their reply. Etc.)  

- It also came out that users want to be able to add other kinds of documents (not just photos, but documents, videos, digitally signed docs, etc), and also to add hyperlinks in the text so they can link to websites. 

**Suggestions** 

Definitely multiple photos need to be possible to add in some way, plus URL hyperlinks and other documents (PDFs, videos, etc), to both ideas and replies, but the rest needs more thought :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk 

My thoughts on the timescale split, see what you think?

- **Ideation launch fix:** Allow attachments to be added to ideas and replies, and URLs to be embedded into the text. 
- **To fix later(?):** Consider other suggestions such as including images on the idea card, and voting on images not just text.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish   @kevincrepin this is a bigger update, so no launch fix anyway. But if we move to "topic" based ideas it would already be technically solved on the API side, also adding images is quite ambiguous as would they be images inside content or would it be just one "cover image" or a gallery attached to the idea. In any case it will take some time to solve as I guess we should also target the image editing issue(s) before that.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK, so no possibility to add attachments for a while (bigger later fix), if I've understood correctly? How about URLs in the text?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I'll see what can be done, we use markdown editor (similar to what Github uses here) so it actually has a lot of different features, links should be quite easy to add

**Comment by BeccaMelhuish** [comment]
Just adding for info that the desire to be able to add photos came up in Round 2 testing as well, so is quite a priority one for when there's time :)

**Comment by BeccaMelhuish** [comment]
Made 2 spin-off issues, but leaving this one open as there is more to be covered here :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish make new issues for what ever is outstanding
