### ISSUE TITLE
IDEATION: Reply posted notification got 'stuck'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1221]
In test, user posted a reply, got this 'reply successfully posted' notification, but it got 'stuck' and appeared on all the subsequent ideas he looked at. 

It should disappear as soon as he clicks right or left (and even if he comes back to the same one, shouldn't be there any more). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c048a232-c802-48f2-ac76-d8904c8a8344)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0b82a357-1aa6-4cda-8471-d983b385472e)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3062d78e-39e1-49bf-8117-8e7fec9d92de)

**Comment by ssin1901** [comment]
@BeccaMelhuish is the issue fixed (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/9936986c-2c5c-46ac-89e7-12a9ab8601a4

**Comment by BeccaMelhuish** [comment]
It wasn't quite that, but tested and seems to work well for me so closing thank you!
