### ISSUE TITLE
IDEATION: No. of updates missing on card 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1224]
In user test, on card in 'My topics': 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a90cfb87-7f8f-446a-a23d-9bbad193ea39)

**Comment by ilmartyrk** [comment]
I think this might have been caused by slow connection, I tried to fix it a little, but it will happen with slow connection until content is loaded

**Comment by BeccaMelhuish** [comment]
Ah, yes he did have connection issues during the call, so that would fit

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish I tested My Topics with throttled internet speed Slow 3G (https://drive.google.com/file/d/1OHtZxhYSqQ1UK7y5gqCaVCQJHZMRmIsV/view?usp=sharing). Please check and tell me if I followed the steps correctly.

**Comment by ilmartyrk** [comment]
@ssin1901 looked OK, connection was slow and as a result loading times were slow

**Comment by ilmartyrk** [comment]
@BeccaMelhuish managed to do a proper fix, if the data is not loaded yet there is no text with numbers

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK cool, so it will be blank until loaded, and then once loaded, appear correctly, is that right? Definitely seems an improvement if so :)
