### ISSUE TITLE
IDEATION: Deadline should have a tickbox like in Voting settings

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1225]
A UX bug shown up by [this bug here](https://github.com/citizenos/citizenos-fe/issues/1220): there needs to be a tick box for the deadline in the ideation settings the same as there is for Voting settings. So that after having started to add a deadline, if you want to then change your mind and remove the deadline, you can (currently not possible). 

Text can be the same as for the ideation one, but replacing the words 'vote' and 'voting' (4 times) with 'ideation' :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/49b109f8-f95a-49b7-8f76-3899c6fbbfdc)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/51762f51-2706-4a34-b2e0-3ffb15df4160)

**Comment by ssin1901** [comment]
@BeccaMelhuish seems fixed, please check (screenshot1)
<img width="916" alt="Screenshot 2024-05-27 at 16 48 33" src="https://github.com/citizenos/citizenos-fe/assets/72747107/07aa30fe-1f03-4a1c-a831-fb581002a92e">

**Comment by BeccaMelhuish** [comment]
Ah yes looks good but needs to say 'Add ideation deadline' (not voting) for the tick-box.

And the text above it should be the same, but edited for ideation, so:

**Ideation deadline**
You can opt to include a deadline, which will close the ideation automatically when reached. You can always edit the deadline, or manually close the ideation at any time.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bc10075e-f05a-426a-85e6-b5d8950e6ab4)

**Comment by BeccaMelhuish** [comment]
Checked and all good, closing :)
