### ISSUE TITLE
IDEATION: Saving ideation topic as draft in Step 1 turns it into a Discussion topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1226]
@ilmartyrk @kevincrepin This is mostly a bug in the way the system works, but I assume needs a UX fix (if can't be fixed technically?), so am tagging you both :) 

**Insight from Round 1 ideation UX tests**

Every time the user made a topic during the test, he filled out the '1. Compose' tab, and then saves it as a draft. There are 2 very legit reasons for doing this: either (1) because he had invited a co-creator at that point and so was waiting for them to edit the topic text before proceeding, or (2) to make sure it had saved, and he wasn't going to lose what he had done so far.

So, this meant that when he created an ideation topic, when he went back into the draft ideation topic he had created, it had turned itself into a discussion topic. (It seems that if no ideation question has been added when it is saved, the system assumes it's a discussion topic).   

But the user didn't know what was going on, he didn't notice the problem, only that our solution for 'ideation' seemed very unsuitable as it was still asking for pro and con arguments. It was only when I explained what had happened, that he was able to go back and make one without saving as a draft mid-way. 

I just checked if it's the same for voting topics, if you save as draft before adding a voting question, and looks like it is. There is an error message 'Voting question is required!' after a draft voting topic closes with no voting question, but this doesn't seem like it would help the user much to me (would still be very confusing and unlikely they'd figure out what's happening). Please see [screen recording here](https://www.loom.com/share/d98c7e8bdf104c159aca3740c6cefb77?sid=96475267-1512-41d6-aec1-46f0d8018bc0): 

**Suggestions** 

- Ideally, can this be fixed technically, so that if someone has selected 'Ideation' or 'Voting' from the create menu (or whichever menu/button they create it from), then that topic is forever more treated by the system as such? 
- If not: 
*Can the default now be an ideation topic, so that all the options are still available to be added (i.e. all phases are visible and possible to add). 
*Can @kevincrepin review the solution that's been created for the same situation with voting topics (the error message) and suggest something that would be more helpful to users in this situation? 

Have added high priority label seeing as it's already a problem in the live system too, with the voting topics.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk tested and works beautifully! (Made 2 topics - 1 ideation with only a title, 1 voting with only a title, and saved as draft, reopened and all was correct). 

Only thing would be let's remove these error messages now? As not needed / confusing (no reason a draft needs a question).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f617ffe3-da6c-4043-b86e-4f7643f9a054)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e780e5f4-8267-44e7-b7ea-4e1e12955230)

Also @ilmartyrk does the fix have anything to do with the menu button that was clicked at the beginning, or nothing connected to that? As if it  is at all connected then I wasn't able to check via this menu (a separate issue stopped me, will report), or the 'You have no topics yet' create buttons for new users. If so then maybe @ssin1901 is able to test that bit :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6f3edf7c-27f6-420c-9ef3-f97b2746a6ac)

**Comment by BeccaMelhuish** [comment]
And I'm not sure the flow for this fix going live, but could the fix for voting topics be added to the live platform already, even though the ideation part isn't live yet?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish yes it can

**Comment by BeccaMelhuish** [comment]
@ilmartyrk am putting this into testing for @ssin1901 to check more thoroughly in live (if has been done there too?) and in test, but please move back if misunderstood :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish 

Ideation draft is saved correctly as ideation topic but after saving draft there is an error message that ideation question is needed (screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/7ef37bcd-9c40-4e5c-b5e1-c130590e1d35

Should we close it?

**Comment by BeccaMelhuish** [comment]
Let's not close yet no, 'til these two errors have been removed as well (assuming both are still there, not just the ideation one) :)
(Screenshot from previous comment above - not new)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e6cd5be9-01a8-45b7-b193-47715f0016a1)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk I think we can send this back to In Progress? The expected result is that one cannot publish the topic without inputting ideation and voting question. Currently, users can still publish without but they will get the error message.

**Comment by BeccaMelhuish** [comment]
@ssin1901 yes have moved it back (I understand it's fine/best to just do so ourselves if we see something unfixed) and @ilmartyrk yes, please remove the two error messages :)

**Comment by ilmartyrk** [comment]
est. dev time 15mins.  to remove errors
