### ISSUE TITLE
TOPICS: Timezones in deadline setting unclear to users

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1227]
**Insight from Round 1 ideation UX tests**

User pointed out that this list of timezones doesn't mean a lot to him, he would have difficulty knowing which to choose.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0ce7b202-27a1-41da-8e5c-40936e294f4e)

**Suggestion**

@kevincrepin can hopefully advise what the top best practice is, but having the key cities written next to the timezones, and having it so that pressing a key on your keyboard will toggle through timezones with that letter at the start of the main city, would seem to make it easier :)   

Also if the system can automatically choose the timezone that person is in, if that info is accessible?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin default timezone is the users timezone

**Comment by BeccaMelhuish** [comment]
@ilmartyrk ah great! It still needs some clues for the user though, so they can quickly see that the one selected is correct :)

**Comment by kevincrepin** [comment]
Yep, I agree this can be improved! Here's  long article – probably you will enjoy this @BeccaMelhuish ;) – https://www.nngroup.com/articles/time-zone-selectors/

I would say let's do it like @BeccaMelhuish suggests and have a search in the dropdown and let's do it based on city, country like this example:
![Screenshot 2024-05-28 at 15 07 56](https://github.com/citizenos/citizenos-fe/assets/26792281/53e41146-fc9d-420b-9bf8-4fc426ad185e)

@ilmartyrk I hope there are already libraries existing for this?

**Comment by BeccaMelhuish** [comment]
Ooh nice yes this looks great!

And for the search, it should work so that as soon as they start typing something it finds the closest option? I.e. they shouldn't have to type 'Luxembourg' and press enter to find it, but as soon as they have typed 'Lu' it would be found?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @kevincrepin @loorm I suggest we drop the whole time-zone dropdown and just inform user about their current time-zone. I see the situations when it makes sense to be able to select it from the dropdown, but the whole management side is quite difficult from how the dates actually work in databases and script

**Comment by BeccaMelhuish** [comment]
It's true that in most cases it'll just be their own timezone anyway. What if they are using a VPN though, will that affect it? 

Just Googled whether that's more common among activists and seems like it would be: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/35f4eb13-19b6-4bb5-926e-42a437b946aa)

**Comment by kevincrepin** [comment]
@ilmartyrk How does it currently work actually? If someone in Brazil sets a deadline in their timezone. Will I, in Estonia, see the hour corrected to my timezone? Or it just shows like **Deadline: 21.09.2024 14:00 GMT-3** ?

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish by default browser timezone is used so VPN doesn't affect it and it should also convert any dates to your local time. Currently user sets date x with whatever timezone, our database stores these times in it's own timezon (Ireland if I remember correctly) and when user selects different timezone to their current browser timezone (javascript Dates operate with browser time) we in the background convert the selected time according to the timezone selected to be posted to the server

**Comment by BeccaMelhuish** [comment]
@kevincrepin what do you think on this one? Does it seem like it'll work to just show the user's own timezone, and if so what would the UI look like for that? :)

**Comment by kevincrepin** [comment]
If we can do it so that we remove the doubt from users with one sentence, that'd be great. And I'd place your current timezone in between brackets.
![Deadline](https://github.com/citizenos/citizenos-fe/assets/26792281/81f7da1c-ae5f-47df-99b6-113e40c89b04)

**Comment by BeccaMelhuish** [comment]
OK yes this looks good! My only concern is that they still might not be sure if 'GMT+3' is their timezone, but on reading it they should figure it out hopefully (that if it's automatic for participants, it should be automatic for them too) :)

Should we use UTC though, rather than GMT? Less euro-centric and I assume more likely people are familiar with it, or can more easily look it up to be sure?

**Comment by kevincrepin** [comment]
Maybe we don't add the timezone at all? :) I'm also not really sure if we created the confusion ourselves by having all this timezone text there. Normally platforms just calculate it according to your (current) timezone. But I think having the text mention that everyone will see it correctly based on their timezone is a good thing to keep.

If we do keep it UTC is also ok for me, I honestly am confused by all of them :D

**Comment by BeccaMelhuish** [comment]
That makes sense to me yes! Indeed they are confusing things, and the text itself should clarify any uncertainty :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk could we have this text added though? :) 

(Maybe it's in other places, but for the one I just checked - idea gathering create flow, it wasn't) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a91890c8-69dc-4402-8704-75db6cec86ab)

**Comment by BeccaMelhuish** [comment]
And if possible to remove the timezone altogether, even better :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/df019e52-4687-4986-8a0a-46d05482703a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish went through all the views with the datepicker removed the timezone name after the selected time and added the info text
