### ISSUE TITLE
TOUR: Users annoyed by constantly popping up Topic Tour box 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1228]
**Insight from Round 1 ideation UX tests**

User confirmed [this issue](https://github.com/citizenos/citizenos-fe/issues/1078): that it's quite annoying for the user to have the topic tour box popping up all the time.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/caef84fc-3cfb-4afe-8ba3-9347dcc631e1)

**Suggestion** 

It should only pop up the first time ever anyone goes into a topic _at all_ (not the first time they go into every topic). I.e. the first ever opportunity for it to pop up (the first ever time someone goes into a topic since the redesign), it does so, then never again. So any given user will only have it pop up for them once, never more :) 

(Though actually we may need to re-think this entirely, as I don't believe (will double check notes) anyone has taken the topic tour at all in any of the redesign tests, despite it popping up all the time - my guess is they either think it is the same tour as the dashboard one, or they just don't want to take another tour. But let's fix this issue more short-term, and I will make a separate issue for re-thinking more long term :))

**Comment by ssin1901** [comment]
@BeccaMelhuish replicated it and there was no Topic tour box for my session. In my view, the UI looked much cleaner. But please check (screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/eaf1f82b-bd63-4319-8a83-ef1b4d29f3ab

**Comment by BeccaMelhuish** [comment]
Oh that's odd that you have no topic tour box at all. @ilmartyrk any ideas on why that would be? Quite the opposite problem to the issue :D 

Edit: Ah I see, it's the same for me now. So just to clarify, the idea was that it should pop-out once (the very first time), and then remain there but minimised the rest of the time. Though if it's a pain to add it back in maybe leave it for now, as no-one is taking that tour anyway, and I will make an issue to consider what to do with the topic tour in future. 

Alternatively, @ssin1901 if you're able to set up data collection on the topic tour button (the start tour one) then we can also base a decision on that, not just the tests :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed it

**Comment by BeccaMelhuish** [comment]
Ah grand, just in test though I think, as it's still popping up in the live one? (Sorry not clear on the process flow with testing -> live, but can discuss in our next product meeting :))

**Comment by ssin1901** [comment]
@BeccaMelhuish I think that this is fixed in testing environment (
<img width="1205" alt="Screenshot 2024-06-04 at 20 51 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/45083889-87a7-45ca-8c7a-f401e09bb9be">
see screenshot). Should I close the issue?

**Comment by BeccaMelhuish** [comment]
Seems to be fixed yes, as long as a brand new user (or brand new since the redesign) does still have it pop-up for them the very first time they arrive in a topic. Will check during my participant tests recording analysis over the next couple of days and close if all good :)

**Comment by ssin1901** [comment]
@BeccaMelhuish I added the test app label. We can wait till the end of the tests to close this issue, as that would be more thorough testing. All the fixes in test environment will be deployed to live.
