### ISSUE TITLE
Login: Hide/view 'eye' icon missing for registration password

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1229]
**Insight from Round 1 ideation UX tests:** 

User struggled with password creation, without the hide/view icons here

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ced6f22f-fb30-4772-86e9-4d3e41e3536c)

**Suggestion:**

Should be added the same as in other places :)

**Comment by ssin1901** [comment]
@BeccaMelhuish seems fixed (see screenshot)
<img width="1378" alt="Screenshot 2024-05-27 at 15 20 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b6c19b11-172a-4bba-9da5-f08026b4acac">

**Comment by BeccaMelhuish** [comment]
Great that it's there though not quite the right UX:

When the password isn't visible there should be a line through the eye:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3180091b-0bb8-4090-a0ce-f3ef8440af17)

When there is no password entered, there shouldn't be an eye: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a9a2ece6-d3b4-4ffd-b135-ae0d747a2097)

I wonder if the eyes are a bit over-sized, but that's just a minor thing and more @kevincrepin's call :)

**Comment by ssin1901** [comment]
@BeccaMelhuish can we create a separate UX issue for the eye icon size?

**Comment by BeccaMelhuish** [comment]
Made the new issue,  closing this one
