### ISSUE TITLE
Topics: Group permissions heading out of line with the column content

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1230]
In topic create flow (in test environment): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/49c747a2-c971-46da-a9e1-66a18f7149ac)

**Comment by ssin1901** [comment]
@BeccaMelhuish can you check (see screenshot)
<img width="1123" alt="Screenshot 2024-05-27 at 15 24 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b86ccef9-8360-4f5d-84e8-1b5ac220031d">
