### ISSUE TITLE
Voting: Vote reminders tick box hidden 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1233]
In a user test, user discovered that the tick box here is invisible until you tick it. This is on the test platform. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ef6bc134-5b43-4ee7-8087-84ad6c178b9d)

**Comment by ssin1901** [comment]
@ilmartyrk I think the bounding box of the checkbox is still too light (screenshot). This is from the Add Voting voting box.

<img width="1031" alt="Screenshot 2024-05-27 at 15 48 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/99203cee-54b4-4241-a891-e6a3a85949ec">
