### ISSUE TITLE
FOLLOW-UP: Edited update didn't seem to post, and UX needed for update edit. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1234]
In test environment, when user edited an update after having posted it, it didn't seem to post. Whether the update actually saved I'm not sure, but when he was clicking on 'Post an update' nothing was happening. 

However, this bug also shows up a UX issue here, that when they are editing rather than posting, I guess the button should say 'Save changes'? And also should be an option to 'Cancel' if they change their mind about editing it. (Unless it was just a bug that these things didn't show). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5a328067-649e-4fec-b0b9-cf580c8dd519)

**Comment by ssin1901** [comment]
@BeccaMelhuish can you check? I checked the Cancel and Save Changes and it works alright. 

<img width="839" alt="Screenshot 2024-05-27 at 15 50 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2311ebf0-783d-4d15-9555-0ae195e5f837">

**Comment by BeccaMelhuish** [comment]
Just going on the screenshot and what @ssin1901 said, looks good so will close :)
