### ISSUE TITLE
IDEATION: Editing Ideation topic closed the Ideation phase

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1237]
**What is the problem?**
Editing an Ideation Topic lead to the Ideation closing without any warning (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/0a10a670-3b25-48c9-865a-755f6d4ce0ea

**Why is this a problem?**
User had no idea that Editing the Ideation would close the Ideation

**Possible solution.**
@ilmartyrk @BeccaMelhuish any ideas for how we can make this more user friendly? It was quite inconvenient

**Comment by BeccaMelhuish** [comment]
Just a bug I think @ilmartyrk? :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk have added pre UX tests label here, if possible to prioritise (next test tomorrow 14.00) - it just happened to me too when setting up a topic for testing - I edited the header and added a photo and it closed the ideation.

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish yes I small bug, should be fixed now

**Comment by BeccaMelhuish** [comment]
Seems to work OK when I edit the image, though wasn't able to edit the topic text (see [this issue](https://github.com/citizenos/citizenos-fe/issues/1245)) so hopefully @ssin1901 can test that :)

**Comment by BeccaMelhuish** [comment]
I tried editing the topic intro text though and no issues, so seems likely it's fine. Will leave open anyway though :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish the issue is that currently topic content can only be edited in draft and in discussion, will try to post a fix

**Comment by ilmartyrk** [comment]
@BeccaMelhuish closing this issue as it has no technical connection with https://github.com/citizenos/citizenos-fe/issues/1245
