### ISSUE TITLE
IDEATION: Ideation Q didn't show up 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1240]
I made an ideation topic with an ideation question, but after publishing it didn't show up (pretty sure it was there in the preview, not 100% though):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c0686b89-0a25-49aa-94f9-834a026d86cd)

**Comment by BeccaMelhuish** [comment]
Tried again and can confirm it shows it the preview, but not when published. Refreshing doesn't help either.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish can you create a video, I cannot replicate it

**Comment by BeccaMelhuish** [comment]
@ilmartyrk here you go (on Chrome):
(Will report the header image issue separately) 

https://www.loom.com/share/d55ce99f512d4e73a2c187681cf287f8?sid=b74559fc-1855-4419-9adc-42fa8ff290fc

**Comment by BeccaMelhuish** [comment]
When I went in in edit mode, this part was all empty, though I had filled both: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/09a34c60-2d83-429d-b7e6-90ffcc6c7eeb)

When I edited them, deadline showed up but not Q:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/084908d2-75f4-4512-8079-8b00a2ea29a3)

**Comment by BeccaMelhuish** [comment]
But going back into edit they were both gone again: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/01797738-fded-4639-bbd5-2d8a35e9e58e)

**Comment by BeccaMelhuish** [comment]
More info on this: I tried making several different topics (some yesterday and one this morning) with the same content (copy and pasting the same text etc) and every time the ideation Q didn't show up. But just tried one with different texts etc and the Q did show (though this was at a later time).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish so the issue is that we currently don't allow editing of the question when the ideation has started, but the question will be empty when you add image to the topic.  It is a race condition difficult to explain here, but I will try to post a fix

**Comment by BeccaMelhuish** [comment]
Hey @ilmartyrk I'm not sure I understood but just to be clear the flow so far has been this:

- User creates topic (with a photo header and attachment)
- In preview, the ideation Q shows up
- Once published, it's not there 

This happened in the user test today for the user (though she didn't notice, so no issues caused!). She was on Chrome too :) 

Re not being able to edit the ideation Q, I've made a quick separate issue for this now [here](https://github.com/citizenos/citizenos-fe/issues/1246), but I think it should be possible to edit it after publishing.

**Comment by BeccaMelhuish** [comment]
Added the high priority label to this one as of all the issues so far I think it's the main one needing urgent attention as far as the user tests are concerned (will do participant tests next, so will need the Q to show up for them). Not yet scheduled but hoping to recruit some in the next day or two :)

**Comment by BeccaMelhuish** [comment]
Just made a topic with header and attachment and the ideation Q did show up (so seems fixed to me so far), but will leave for @ssin1901 to test more thoroughly :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk this one just happened to me again - on desktop, Chrome, incognito: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0d1a2dc3-bc6c-47c3-ab84-df85695e98ce)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish found the issue, there was a bad race condition. Should be fixed now

**Comment by BeccaMelhuish** [comment]
OK cool, will keep an eye, and I guess leave it open for @ssin1901 to test more thoroughly at some point :)

**Comment by ssin1901** [comment]
Could not replicate @BeccaMelhuish but let's keep an eye on this one
