### ISSUE TITLE
TOPICS: Duplicating an ideation topic turns it into a discussion topic. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1241]
@kevincrepin Maybe the user needs to be given a choice when duplicating, what type of topic they are now creating? 

But @ilmartyrk for now, default could be always ideation topic, as that has all phases available? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0fa19817-3c91-455b-bacb-5d5972abf1d1)

**Comment by kevincrepin** [comment]
Maybe this is just a bug? Because duplication should take over the phases it has, otherwise it's not really duplicating?

**Comment by BeccaMelhuish** [comment]
Yes true @kevincrepin, if it's a duplicate it should indeed just duplicate everything about it (phases too). 

@ilmartyrk is it possible to fix it?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate but let's keep an eye on this
