### ISSUE TITLE
TOPICS: Topic header image not showing up

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1242]
In test. Tried several times but this header image isn't appearing when I publish. I am adding the same image as the header as I am attaching, not sure if that's relevant? I can go in an edit the topic, upload it again and then it does appear (but then ideation gets closed as per other issue).   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/09995b67-4444-4a85-ba17-36723b2e6a46)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk please see video here, this time for me it didn't show up in preview, but did show up in the topic itself: 
(Relevant bit around 1:45 min)

https://www.loom.com/share/d55ce99f512d4e73a2c187681cf287f8?sid=b74559fc-1855-4419-9adc-42fa8ff290fc

Reported other header issues separately [here](https://github.com/citizenos/citizenos-fe/issues/1244).

**Comment by BeccaMelhuish** [comment]
Tried again just now and it showed up in both preview and published, but will leave for @ssin1901 to test more thoroughly :)

**Comment by ssin1901** [comment]
@ilmartyrk tested and it did not show in Preview (see screen recording) but did show up in Published.

https://github.com/citizenos/citizenos-fe/assets/72747107/c3bfbf19-5b7b-4035-89d0-f63deab77858

**Comment by ssin1901** [comment]
@BeccaMelhuish I am closing this one but leaving #1244 open because it hasn't been deployed to live yet though it is fixed in testing. Also added the label.

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish fixed the preview image not appearing

**Comment by ilmartyrk** [comment]
@BeccaMelhuish can you provide the image info you are trying to upload

**Comment by BeccaMelhuish** [comment]
@ilmartyrk For me it's OK if @ssin1901 has tested :) 
(Was just messaging on Slack about the new 'test app' label and 'testing' label confusion - maybe we don't need 'testing' one anymore?)

**Comment by BeccaMelhuish** [comment]
Unless I've misunderstood and you've added something since @ssin1901 has tested, and if so we re-open this one? :)

**Comment by BeccaMelhuish** [comment]
This was the photo I was uploading in the above case 
![213a2fc9-8b28-4923-8c0a-7f3a1f93f9ed](https://github.com/citizenos/citizenos-fe/assets/61320526/682cbfda-d0ac-4bb9-b413-6a3e23f3c7f6)
