### ISSUE TITLE
PROFILE: Profile pics getting stretched/squeezed and clipped

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1243]
Has happened a few times, they always seem to upload a bit warped, and with the bit at the bottom missing: 
(This is in test). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e87e5a95-e856-41cf-993d-274d72bf2741)

**Comment by ilmartyrk** [comment]
I am closing this issue, we already have many issues related to images and they will get fixed once we do a proper solution.
