### ISSUE TITLE
TOPICS: Not able to remove header image once added

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1244]
In test, I uploaded the wrong image and wanted to remove it to upload the other one, but couldn't:
(Relevant bit around 0:40 secs) 

https://www.loom.com/share/d55ce99f512d4e73a2c187681cf287f8?sid=b74559fc-1855-4419-9adc-42fa8ff290fc

**Comment by BeccaMelhuish** [comment]
Then when I went into edit this, it shows like it's not there: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ec5a6086-417b-4eb3-8c34-243c4b38f191)

Until I click on it: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ded7a61e-a197-4d44-9676-1a1ac367fe11)

But I was able to then remove it: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e0b1e081-c26c-471b-a20a-7d1e8d6c8254)

**Comment by ssin1901** [comment]
@ilmartyrk issue currently occurs in live environment as well (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/ea912263-f42f-46a0-9c58-75611c87b135

**Comment by ssin1901** [comment]
@ilmartyrk issue not fixed in test either (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/8a99ef7a-33b7-42c4-a85a-dd52fabd4e1d

**Comment by ssin1901** [comment]
I think that since the issue occurs in live, the high priority label is needed.

**Comment by ilmartyrk** [comment]
@ssin1901 I could not replicate this issue, can you provide more info, browser, topic status etc.

**Comment by ssin1901** [comment]
@ilmartyrk in the live environment

1. Tested in Google Chrome incognito mode
2. I went to Create -> Discussion Topic, filled in topic details and added a header image of 2.4 MB
3. **Tried to remove the header image but could not**
4. After successfully publishing the topic, I went to Edit -> Compose and I could then remove the header image

Seems to occur only at the time of creating the topic.

**Comment by ilmartyrk** [comment]
@ssin1901 found the issue, posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk fixed in Test environment (screen recording). 

We can discuss deploying to live in the current meeting.

https://github.com/citizenos/citizenos-fe/assets/72747107/f82c8f2b-6487-4cba-b235-dd991a660ced
