### ISSUE TITLE
TOPICS: Not able to edit topic text

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1245]
Trying to edit a topic text, when I go to that bit it looks like this and won't let me click anywhere (can't type).
In test. Tried refreshing. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/44f65863-c635-471b-a5f7-c9c2e6bfff6c)

**Comment by BeccaMelhuish** [comment]
Tried going out of the topic and coming back in, same problem. In Chrome.

**Comment by BeccaMelhuish** [comment]
Ideally would be fixed before today's test at 14.00, but can work around it if not :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is  because topic description editing was only allowed for drafts and discussion topics, so this was probably ideation topic, posted a fix

**Comment by BeccaMelhuish** [comment]
Makes sense thank you! Will leave for @ssin1901 to test properly :)

**Comment by ssin1901** [comment]
@BeccaMelhuish tested and seems everything can be edited now (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/daaa540e-801e-43e0-ac4c-3922f05a53a9

Please close if all okay!
