### ISSUE TITLE
IDEATION: Should be possible to edit ideation question

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1246]
@kevincrepin @ilmartyrk 

**Insights/thoughts from Round 1 admin ideation testing and prototype testing:**

Not super solid user insights (this didn't come up much in the tests), but seems reasonable from what I've seen and heard, and thinking it through myself, that the ideation question should be editable after the ideation has started. Reasons for this: 

- The ideation starts immediately once you launch the ideation topic. This means your only chance to catch a mistake or change how your phrase the question is in the preview. And it seems people are often just trying it out/putting in some draft text when they first publish, to see how it will look and work, discuss with others etc, and then come back and edit things before sharing it more widely.  
- The Figma prototype tester confirmed that she would want to be able to edit the question once it's started, in case she had made a mistake, or if it was clear that participants were misunderstanding the prompt. I.e. if she thinks her prompt (ideation Q) is a good one, but then sees people are misunderstanding and adding the wrong sorts of ideas. Then she'd want to be able to edit it. 
- One of the user testers made a typo in her ideation question that she hadn't caught previously. She didn't notice it, but I can imagine that she would notice later or someone else would, and it would be frustrating to not be able to edit it. 
- I'm thinking that the only reason we're not allowing editing is because we've adopted the same rules from our voting flow. But in voting it makes more sense to not be able to edit once the vote has started. In ideation, I don't really see a reason not to allow it? 

**Suggestion:** 

Make it editable while the ideation is open (but I guess not once it is closed?).

**Comment by ssin1901** [comment]
@BeccaMelhuish did a test and it seems to be working (screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/36f34f50-2c75-426a-961c-475d054fe52c

Please close if all fine!

**Comment by BeccaMelhuish** [comment]
Great that it's possible now! 

Only thing would be that from a UX perspective I think it needs to be added to this menu, as "Edit ideation", and this would take you to the point in the Edit flow shown below. (Unless @kevincrepin thinks otherwise).  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d8337070-f001-45a5-940c-65d55fce8b6f)


![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3342b1f4-5f40-419a-b48c-78ac47815873)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the option

**Comment by BeccaMelhuish** [comment]
@ilmartyrk tried and works great, but something seems to be up with the deadline. It shows that there is one, but when I get taken to that part it isn't ticked: 
(Can make a new issue though if a separate thing?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ec33161c-b15f-4b47-b37b-ab5362d51669)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8a90d1d8-cd22-4d1a-b1e6-56ae0be31f67)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the date issue you referred

**Comment by BeccaMelhuish** [comment]
Wonderful, tested and working well for me, but will leave to Sara for proper testing :)

**Comment by ssin1901** [comment]
@BeccaMelhuish 

1.Ideation question could be edited (screen recording 1)
2. Deadline was added (screen recording 2)
3. Manage deadline updated to edit deadline (screenshot3)

https://github.com/citizenos/citizenos-fe/assets/72747107/4a5c7fc8-9166-4578-870a-d14bb8cb546c

https://github.com/citizenos/citizenos-fe/assets/72747107/f50eaeef-aa41-4bbf-9d92-dfdf43046ebb

<img width="1376" alt="Screenshot 2024-06-04 at 21 15 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7b754ad4-7fc1-4981-a2f5-7727ef374862">


Will close the issue then!
