### ISSUE TITLE
Groups: Can't add topic to group - internal server error

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1247]
In live platform, tried all the different ways of adding topic to group, but all gave me this error:

(Trying to add topic to Citizen OS team group, for which I have admin rights so should be able to)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4246068c-95de-4c05-9c3a-fc24a5c9c471)

**Comment by BeccaMelhuish** [comment]
@MeelikaH was unable to access the same topic, when I had invited her directly via email due to not being able to add to the group. May be related? (Not sure if the rest of you are able to access it yourselves, @ssin1901 @ilmartyrk etc? :)) 

This is re 'Fortnightly team meetings' topic.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should now be fixed

**Comment by ssin1901** [comment]
@ilmartyrk in our live environment, I don't see all the private groups that I have Admin rights for (AI deliberation for example, screenshot1) listed when I try to Add Topic to Group (screenshot2). Cannot scroll through groups either.

<img width="1198" alt="Screenshot 2024-05-31 at 16 42 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9c5e84c4-5246-4f84-9f1a-f147907dc4a9">
 
<img width="1376" alt="Screenshot 2024-05-31 at 16 42 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f3c34210-fd06-47ae-a415-d40b6c130b16">

**Comment by ilmartyrk** [comment]
@ssin1901 this is a separate issue, I created a new [here](https://github.com/citizenos/citizenos-fe/issues/1259)

**Comment by ssin1901** [comment]
@ilmartyrk adding topic to private group with members only permission and private group with admin permission. No error occurred, topic was successfully added. Closing the issue.
