### ISSUE TITLE
User should be able to change the group image file name in groups

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#125]
**What is the user story?**
When the User goes to Groups->Edit settings and attaches an image, the image is attached but the user cannot change the name of the image and in fact, clicking on the file name removes the image altogether (screenshot attached)
<img width="1143" alt="Screenshot 2023-05-21 at 15 40 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/54ca6065-dc1d-4c1c-a79e-34481016f4b1">

**Which feature needs to be updated and how?**
Users should be able to edit the attachment file name, like in topics (screenshot attached)
<img width="1145" alt="Screenshot 2023-05-21 at 15 44 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c9e38368-a221-46a4-93a3-c1adf0753afb">

**Additional information.**
@BeccaMelhuish we don't have a Help Centre article for attaching images to groups, do we?

**Comment by ilmartyrk** [comment]
#Triage 85, as the file name does not have any functional importance in this context and the button is meant for removing the image, we will rename the button to "remove image".
