### ISSUE TITLE
IDEATION: Some processes need more space for ideas

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1251]
@kevincrepin @ilmartyrk

**Insights from Round 1 ideation admin UX tests and recent public use case**

I didn't get to ask about this in all tests (only in one), but between what this one admin said, the recent Viimsi PB idea gathering process, it seems quite a solid insight that there will be a need for much longer texts (and other content) for the ideas. 

- An admin for a community decision-making process for what to do with an under-used square said that if there's no technical reason for a character limit, then it shouldn't be restricted, but if we have to restrict it then the space should be at least A4 amount of text (this was just off the top of his head though, would need testing in a real life situation). 

- We can see from the recent [Viimsi participatory budgeting use case](https://app.citizenos.com/groups/919baf8a-3e24-468a-87c8-64ba956bda26/join) (which was very much following an idea-gathering process) that the amount of space used by the participants to submit their ideas was hugely different to the space we currently allow. 

**Suggestions:** 

We currently only allow 2048 characters (same as for discussion arguments). Can the limit be taken off, so people can take as much space to explain their idea as they want to? Or if not, can we make the limit very large? 

I wonder if someone adds a long idea like this, with lots of photos etc., this would change how we'd want the ideas to be laid out. I feel they work well with this layout if they are just short texts, but for a long idea [like this for example](https://app.citizenos.com/en/topics/82a1f353-26ac-4952-a2ee-2456e4857542#discussion), with loads of texts, graphs, photos, chart etc in the body of the idea, it would all be a bit too squeezed and narrow? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0d36b2e7-3c7b-4541-9180-a8ed73054336)

**Comment by kevincrepin** [comment]
If we allow for long documents (in essence it's what the example is) for ideas, then I agree this layout would not help anyone get through it. So the question is, should ideas gathered during an ideation phase be of this scale? I think this needs to be discussed and agreed internally in Citizen OS together with @loorm , I'm sure he has a vision for this :)

If we do want to not limit anyone then I will revise this current design.

**Comment by BeccaMelhuish** [comment]
OK yes, makes sense! :) 

I'm feeling relatively confident from a recent strategy meeting (with Margo) that these use cases are priority ones, as we ranked our target groups in order of priority for meeting our mission/vision as it stands, and the two groups mentioned above were ranked #.1 (local community action groups) and #.2 (local governments). Plus the two aims of the processes were very much in line with our vision too (collectively deciding what to do with a local space, and collectively deciding what to do with the local budget). 

And I see no reason for us wanting to limit anyone in padding out their ideas, if they want to. But I know that we do limit arguments, so maybe there is a reason to want to limit idea explanations too. 

But @ilmartyrk what do you think? Options are:
- If you agree with my thoughts above, then we decide between just us to ask Kevin to redesign it accordingly. 
- If you're not sure, I can take it to the team and get their input as well? On Slack or we could raise it at MM tomorrow?

**Comment by kevincrepin** [comment]
BTW I'm also thinking that to accommodate for longer idea texts this current way of adding your idea is too compact. So this would need a redesign and with this comes then also probably the redesign for the argument adding, since they use the same component. Otherwise it would all be different and getting messy already.

So just heads up that this is a change with quite big implications.

**Comment by BeccaMelhuish** [comment]
OK yes noted thank you! Just to be sure though, by argument adding, do you mean the replies on the idea? :)

**Comment by kevincrepin** [comment]
No, the pro/con/neutral arguments. Using the fixed bottom bar that opens up. It's not meant for the kind of scale we're talking about, adding images and long texts.

Probably would move to removing that in favour of a process of adding your contribution **within** the widget.

**Comment by BeccaMelhuish** [comment]
Ah gotcha, understood! 

Will see what Ilmar / the team think, then let's see :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @kevincrepin @loorm  at one point there was discussion on possibly moving from ideas to new topics so that an idea could become a topic. So for me that brings up some possibilities:

1. We continue with current solution, but add a button to transform ideas into topics and possibly link them back to the original topic/ideas somehow.
2. We drop the current idea solution in a separate table and ideas will become topics, but they will have "special" idea status that we won't list together with other topics?
3. Hybrid system where ideas can either be current "compact" solutions or topics
4. Possibility to add existing topics as ideas

For me the ideas should be quite short and just give a general overview, but I guess for some cases it makes sense to have long descriptive overview of the idea and how to possibly make it happen as without that people could get thrown away as they can't see the full reasoning.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Hmm for me the idea of participants having to navigate back and forth between ideas that are just in the ideation part and ideas that are separate topics ("housed" where, I'm wondering) feels a bit too complex for the average participant who is just coming to add an idea and browse others and vote. Would be lot of potential for users to get a bit lost / confused / overwhelmed and give up. So maybe the turning ideas into topics thing could be something to be explored later (so far no users have mentioned/shown a need for it), but not part of the 'main flow' of how we expect people to use it :) 

But what I'm hearing is agreement that we do need to allow for more space for those that need it (like in these use cases above)? So in that case should we go ahead and ask @kevincrepin to come up with some possible solutions (whether that's making all ideas have the potential to be longer, or giving an option to 'expand further' on your idea)? 

Or best to discuss more in the MM tomorrow?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I was more describing it in the technical side of things, the UX is another thing to solve anyway. But I guess it could also be that in the "idea phase" the topic would only have title and description, but the description would be using Etherpad as it is for the topic.
Well technically I guess we could solve the idea description with Etherpad without using our "topics" table. But if we decide that ideas can be converted into separate topics we can link the already existing Etherpad document with a new topic generated from the idea

**Comment by BeccaMelhuish** [comment]
Ah right, sorry misunderstood! :) 

But based on our Slack convo just now, I'm thinking we could split this issue out like so:

- **Ideation launch fix:** We make the ideas the maximum length of characters that will work for the current design (@ilmartyrk and @kevincrepin your input needed on that), and ideally with [attachments possible](https://github.com/citizenos/citizenos-fe/issues/1219) if this is doable before the 17th. (As then if someone really wants to elaborate on their idea before we have solved this, they can do so with attachments).  
- **Bigger structural fix:** Making the ideas work for longer ideas with photos in the body, of the sort of length that the Viimsi PB ones were. 

If agreed, I'll make a spin-off issue for the 'BSF' work to be done later :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I guess we should actually lower the character amount for the idea "title" to the same length as is for the topic title (100 characters) and remove the limit for the description.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah I'm confused though, is this for the pre-launch fix, or for the bigger fix? As I understood that seeing as making the idea descriptions unlimited length would mean big design and technical changes, then we should keep the design as it is (so with limited but as long as possible with the existing design) for the ideation launch, and then Kevin will revisit the design as part of the 'Bigger structural fixes'?

**Comment by kevincrepin** [comment]
No problem for me to limit title characters and no limit content. If the solution is approved which I suggest [here](https://github.com/citizenos/citizenos-fe/issues/1249) then bigger content will already have more width.

**Comment by BeccaMelhuish** [comment]
Oh OK cool! So we could already allow more space for ideas then in the Round 2 tests?

What about this problem you [mentioned here](https://github.com/citizenos/citizenos-fe/issues/1251#issuecomment-2152370011 ) though @kevincrepin?

**Comment by kevincrepin** [comment]
That problem still persists here, but if I understood correctly then doing the bigger update where user can add long form text + images etc will be in a next phase?

**Comment by BeccaMelhuish** [comment]
Ah yes that's where I'm getting confused though, as to me no limit on the content/description means the longer texts, which I thought was coming later. But maybe I'm misunderstanding? :) 

Maybe it's just that for now we can allow longer texts but only with the formatting options currently available, but with the bigger later fix we'll be able to offer the full formatting options like we have in topics? If so that's great.

**Comment by kevincrepin** [comment]
How I see it is that there's no technical reason why a user would not be able to add more text in the current form. But there's very little text formatting, no images, no attachments (in this phase). Including any of those would mean more work that will be in the next phase. 

So that's why I think for the time being we _can_ give users a no-limit on text. It just won't be very comfortable for anyone to go through it.

**Comment by BeccaMelhuish** [comment]
Perfect, this sounds a good plan then! So:

- **Ideation launch fix:** Allow unlimited characters for the idea description within the current ([now slightly updated](https://github.com/citizenos/citizenos-fe/issues/1249)) design. 

- **Bigger structural fix:** Change the design to work for longer ideas with photos in the body plus additional formatting, attachments etc, of the sort of length that the Viimsi PB ones were.

**Comment by BeccaMelhuish** [comment]
Made a separate 'bigger fixes' [issue](https://github.com/citizenos/citizenos-fe/issues/1305) so this one can be closed when the ideation launch fixes are done :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin @ssin1901 I've allowed adding links and images to our arguments and ideas using the current markdown editor. Image adding is a little confusing if you have never used markdown. But lets see how it turns out in testing

**Comment by BeccaMelhuish** [comment]
Hmm I think it's a bit too confusing as I couldn't figure it out myself.. 

This was my attempt - the URL in the end I decided must work like this (but didn't) and the photo I was quite clueless how to add :D 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8d6a5da3-b2f8-4b47-aba9-711b370d400f)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fec4070d-98b9-4b43-8209-64204777e9d8)

**Comment by BeccaMelhuish** [comment]
Not sure @kevincrepin's feeling on it, but my hunch would be best not to include it at all until we have a more standard UX for it?

**Comment by ilmartyrk** [comment]
photo needs link to a photo, removing it for now

**Comment by BeccaMelhuish** [comment]
Ah OK :) 
What about this bit? Was it a bug that it didn't work, or wasn't correctly done? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8aca5a3d-dae1-4544-b0b3-5ea9c532a11a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it's the same as in Github, left it in at the moment, should I take this out too?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk maybe technically it's the same but the UX is a bit different, and therefore less intuitive :) 

Have made a little screen capture comparing the two here: 

https://www.loom.com/share/8811a066657940ea933f588ba0a55689?sid=c5ec2f87-7ce7-4019-8bfb-279758445d14 

Also once posted, it doesn't seem to show as a hyperlink for me - see above and at the end of the recording. 

I think if we could get it working the same for the user as adding a link on Github, then would be great to test this one in the tests and see if it's intuitive for those not used to github :) (But longer term, find a clearer fix, for less tech savvy people - e.g. older folk etc).

**Comment by BeccaMelhuish** [comment]
P.S. to make it clear that you do need the https bit (assuming it's crucial? If not then ignore), it could be like this when you click the link button: with the URL selected so they (hopefully) see that's the bit they have to replace. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dd976641-fe29-4072-8b4c-945433a6eecb)

**Comment by kevincrepin** [comment]
I don't even see the URL or image option in my markdown options :)

**Comment by ilmartyrk** [comment]
@kevincrepin yep, already removed them

**Comment by BeccaMelhuish** [comment]
Tested this out and found some formatting issues that I made a [separate issue](https://github.com/citizenos/citizenos-fe/issues/1310) for, but one thing directly related to this:

I added a very long idea: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/df1b2ab6-bb88-4d5a-903b-9a87a8d9ec98)

I then went in to edit it and tried to see what happened if I added bullet points. When I published it, the idea had been cut shorter:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/eca31ff8-61ac-4570-8a5c-bad8bf2590c4)

And when I go into edit, there is no a character limit: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fad837b6-2d19-4d53-9d72-0abcb64e8ac0)

**Comment by BeccaMelhuish** [comment]
Also @ilmartyrk, sorry it wasn't on the wishlist, but if at all possible for [this issue](https://github.com/citizenos/citizenos-fe/issues/1276) to be fixed as part of this too - as not having the character limit below for ideas now makes it more confusing what the top one is for :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cecd58b3-4e8c-4c36-8680-ce689817b21c)

I.e. Kevin's solution here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8f1c46e2-1651-43b9-9ecb-f2cfde5e1a89)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated and fixed

**Comment by BeccaMelhuish** [comment]
@ilmartyrk great! Tested editing and it no longer cuts it short, though when I go into edit it says this - is it possible to remove it? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/43335de9-e4fd-41c9-afcd-6969c8903dc0)

**Comment by BeccaMelhuish** [comment]
Checked and all looking great now thank you! :)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/009ec8f6-b9b9-4811-afdb-d92f434395f9)
