### ISSUE TITLE
IDEATION: UX insights for lightbulbs (and related features)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1252]
@kevincrepin @ilmartyrk 

**EDIT: This issue got a bit long and messy, so feel free to skip to [this comment](https://github.com/citizenos/citizenos-fe/issues/1252#issuecomment-2149315674) for a summary! And just refer back up if needed :)** 

**Insights from Round 1 ideation admin UX tests** 

Two of the 4 admin users read this "illuminating" explanation for the lightbulb upvote toggle, and those two did quickly understand what it was for. They both got confused initially between the lightbulb and the star for 'favourite', but in the end seemed to figure out the difference. Same with the 1 admin Figma prototype tester, she also read this text and therefore understood it. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bc815e21-ef96-4e1e-9c4c-d5f2ba37f95c)

The other 2, who it seemed didn't read the above text, were confused by the toggle and didn't understand what it was. They thought it might be a tool specifically for admins, and weren't sure if participants would see it too (and didn't understand that it was for upvoting - they had other ideas on what it might be for - can elaborate if needed). Though this was just them trying to guess when I asked them, they were mostly just confused.  

(I remember myself also being confused by this toggle when I saw it in the Figma, and asking what it was for.)

**Suggestions** 

Everyone understands the up thumb and down thumb icons for the replies, so maybe instead of a lightbulb it could be a thumbs up? We do call it 'Likes' in other places, so would be more consistent with what people know as 'likes'. Or a + sign, or up arrow, maybe, for the 'upvote' concept? But then maybe having both upvoting and then actual voting gets confusing.

(I do quite like the lightbulb concept myself know I know what it's for, and like that it's different to social media - something a bit more unique to us, but it seems it's not being easily understood). 

Or maybe some kind of tour like prompt when they first ever see it, which explains what it's for?

**Comment by BeccaMelhuish** [comment]
**Will add an insight from the first participant test too (90 year-old):**

She didn't notice it at all (as was the case with one or two of the admins, I had to ask them), but once I asked her what she thought it could mean she guessed correctly: "Liking it". 

**Suggestion:**

Could we make them a bit more visible when they are toggled "off"? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4b82bbcf-5aef-48da-bc99-87d58890b0b1)

And perhaps best to wait for the next two participant test (Mon 3rd & Tues 4th) insights as well before deciding what to do - maybe the confusion is more on the admin side, as there are more things it could be doing for them. (And in which case, maybe we solve it with more admin specific communication).

**Comment by BeccaMelhuish** [comment]
**Will also add some further related admin Round 1 insights**

1. 
One user felt he would want a downvote as well as an upvote, so he could get a better idea of the overall feeling on the ideas (as admin). 

He also mentioned being uncertain what the meaning/purpose of the up/downvotes on the idea replies was, in terms of understanding the reactions to the whole idea (as admin). 

This user didn't know at this point (and also didn't seem to understand later) that ideas could be voted on in a formal vote. Not sure if this would affect his feelings on the above things.  

**However**
Another user approved of it as it is: "This is good, as you wouldn't want to have a 'thumbs down'. It's not very proactive I guess" (probably meaning 'positive'). 

2. 
Another user asked:
 “Can I highlight it as an admin, or can anyone highlight it?”
 (I guess he would work this out as the process went along though).

**Comment by BeccaMelhuish** [comment]
Sorry this has turned into rather a messy issue! But I've got the participants testing issue now so will do a summary post here:

**Main insights overall:**
- Admins that read the "ideas can be considered more or less 'illuminating'" text figure out what the button does. 3 out of 5 read it and understood the button quickly, 2 out of 5 didn't and were really confused. (I myself was also confused seeing the lightbulb for the first time, not having read the text). 
- Admins were more likely to get confused than participants, as there are more other options for what this could do - i.e. marking it as something to send to vote, or allowing replies on this idea, etc. 
- Relating to the above, admins are unsure if it's something just for them, or for all participants to use. (I'll make a separate issue about a possible need for admin's to see a 'participant' view, like with Facebook pages etc. Seems to be coming up a lot).  
- Participants generally figure out what it does, though with differing degrees of certainty. 1 was pretty confident, 2 were unsure, but guessed in the end it must be 'liking'.
- One participant (90y/o), didn't see it at all, finding it blends in to much to the background. A couple of others didn't take much notice of it either, and I had to prompt them to click it / talk about it. 
- One participant, after deciding what it does, was very positive about how "cute, fun, colourful" etc it was, and different to other platforms (not seen similar elsewhere). But the positivity was "as long as people can understand what it does".  
- There is some confusion between this button and the favourites button. Sometimes when people think they've worked out what the lightbulb, they then lose confidence when they see the favourites. 
- One participant was expecting / wanting to have hover explanations over the lightbulb and the favourites star.  
- One admin though the favourites star might have been an admin tool to mark what would go to vote. (Similar to what one other thought about the lightbulb). 
- One admin wanted to be able to downvote as well as upvote ideas, though another liked that you could only make a positive reaction to ideas.  
- One admin (same one as wanted downvotes) was confused about how the likes and dislikes on the idea replies would feed into his understanding of the reaction to / feeling about the idea overall. 

**Main suggestions:**

- Use a hover explanation (or something nicer) over the lightbulb and favourites to explain what they do? 
- Change the lightbulb to another kind of icon? (Thumb, plus, up arrow, etc?) 
- Make the lightbulb icon (or whatever it gets replaced with) more visible, so it pops out a bit more when not clicked. 
- Consider downvotes for ideas? Or allowing admins to set whether they have both or just one, in some 'advanced settings'?  
- I wonder if we actually need the favourites star on the ideas or if it just confuses things? I didn't get a sense from any of the tests that it was something important to the users.

**Comment by BeccaMelhuish** [comment]
I'd say this should be under 'Ideation launch fixes' if possible

**Comment by kevincrepin** [comment]
I agree with the tooltip on hover and the lightbulb interaction more standard. I don't think you should be able to downvote ideas, because in ideation the whole point is anything goes, no? :) 

I think some small changes can already improve this a lot. Let's not have it as a toggle anymore, but rather as an actual button.

**Tooltip on hover:**
![Screenshot 2024-06-07 at 15 11 06](https://github.com/citizenos/citizenos-fe/assets/26792281/73909a48-a0fe-45e8-be15-9180c8ec3956)


**Clearer indication it's been clicked + here we can also add a tooltip on hover stating "you find this idea insightful". Maybe we can rename from illuminating to insightful btw? LinkedIn uses this term...**
![Screenshot 2024-06-07 at 15 11 11](https://github.com/citizenos/citizenos-fe/assets/26792281/397966c3-6598-47f0-8781-ecff1aa1ce78)


**Relocating it on the Idea card:**
![Screenshot 2024-06-07 at 15 12 19](https://github.com/citizenos/citizenos-fe/assets/26792281/ba383583-594c-46b4-a8e5-8e29be8eb74c)


Designs can be found here: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=13338-115399&t=xoQN4LtSq20tl0HZ-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin hover tooltip looks great! 

What are your thoughts on adding one to the favourites too? (Or even scrapping the favourite ideas? I feel like it doesn't add much and causes more confusion (from what I've seen/heard in the tests - e.g. confusion on the difference between favourites and lightbulb, and confusion between favourite topics and favourite ideas, etc). 

Also agree that the hover for after having 'lightbulbed' an idea, and for 'X no. of people' have too, are good additions. 

But not sure about the 'insightful'. I think things on LinkedIn work better for that as they might be thought-provoking, i.e. an insightful article. Whereas an idea might not be insightful (or indeed illuminating), but you might like/agree with it. E.g. "A playground". Or "A car park". One user explained what he thought it might mean as this 'resonates' with me. Which is quite nice wording, but maybe better to keep it simple with just 'like' or 'agree'? 

Good point re not down-voting during ideation, should be "anything goes" indeed :)  

Changing from a toggle to a button seems a good solution, should be clearer. Might that mean we could also add the possibility to see who has 'liked' it, like we do with the idea (and discussion) replies? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b27b7248-f460-488e-beb8-4da881952fdf)

Not so keen on the movement of the button to the top though, it seemed to be working well where it was (and one participant tester verbalised approval of the placement too), I think the problem was more that when it wasn't selected it was really blending in, so not so visible:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6be090c7-0bb0-46f2-9283-d2481d346224)

**Comment by kevincrepin** [comment]
The lightbulb is a "common/popular" (I can't find a better wording for it) indicator as in it's shared across all participants. Favourites however is a personal thing. It's not because you favourite an idea that it's favourited for me. But if you "like" an idea, then I see the output of that. But I agree a clearer hover state for this would not hurt. There's a reason why we added it there, so I guess there was the requirement :)

I know it wasn't requested to move the lightbulb button, but in its new form it doesn't fit there – it's very "floaty" and needs "something to hold on to" :) Unless in new testing it shows that it doesn't work there I would like to keep it at the top. Consider in the future there might be an image here as well, so in this update at least we have room for it already :D 

We can reuse the same dialog info window on who has "liked" as we have for the thumbs up/down, shouldn't be an issue. And with the new design at least the icon and the number are more separated.

**Comment by BeccaMelhuish** [comment]
OK yes let's add the tooltips then, and hopefully that'll clear things up, and then maybe at some point @ssin1901 can get us data on whether anyone is using it (my feeling from the tests is that they won't but real life may well be different!). 

So suggested text for the favourites star hover tooltip could be this? 

_Save idea to your personal favourites_ 
 
OK yes no problem, we can see in the Round 2 testing how it goes. My worry is that it won't be easily found/noticed there, especially as it's small now too, but let's see how it goes :) (Also a worry that the cards will look extra empty without it, as so far the ideas titles been shorter than in the Figma - see example from a test below. Though this will probably vary case to case). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/36da10dd-3553-4b0c-9df1-ca186257a85f)

**Comment by kevincrepin** [comment]
Kinda hoping people would also open up the ideas and read more about them (+ any replies to them) before giving their "upvote", but yeh, I also have no idea how people would use it. 

For the favourite (both here and in discussions then):
![Screenshot 2024-06-07 at 15 37 27](https://github.com/citizenos/citizenos-fe/assets/26792281/e745ffe4-273f-40b0-86a0-3c9e0aa82d9c)

**Comment by BeccaMelhuish** [comment]
It's a good point! Will report back post Round 2 :)

**Comment by BeccaMelhuish** [comment]
Reviewed the lightbulb button and it looks good, but still the hover tooltips to come right @ilmartyrk? Will move it back to in progress for that bit :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the tooltips

**Comment by BeccaMelhuish** [comment]
Awesome! A bit flickery but definitely good enough for testing! 

I would just add it here too:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/98f5bcb1-cb89-41c1-ad6d-64585ae639a5)

And seeing as it's currently '1 people found this idea insightful' if there's only 1 person (so a grammar issue), shall we change it to 'See who found this idea insightful'? The number probably doesn't need repeating anyway. 

In these two places (the second it's currently missing): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/93971b06-2795-47af-9ed3-5b8ee1d99139)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/383007fa-a80b-48e3-8add-b97c6e67966f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the tooltips

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Thank you! 

Have made the text adjustment in the strings too. 

So all good for testing, but will leave open for fixing the flickering at some point (let me know if screen recording needed) :)

**Comment by BeccaMelhuish** [comment]
I made a separate issue for the [jumpy hover tooltips](https://github.com/citizenos/citizenos-fe/issues/1368)

**Comment by BeccaMelhuish** [comment]
@kevincrepin 

**Some more insights from Round 2 on this issue:**

It was definitely better this time, but: 

- There's still some confusion about what the lightbulb means.
- Some users (in Indonesia) weren't understanding what the lightbulb tooltip text 'click to show your approval' means - they were really quite baffled what it could be for. 
- One user on mobile pointed out that she had to click on the lightbulb to see the help tooltip, and then felt uncomfortable because in doing so she had accidentally shown approval for an idea that was controversial (and worried people may have been notified that she had).  
- Users in Indonesia suggested that a 'thumbs up' like button would be much clearer to their audience. 
- There's also still some confusion about the difference between the star and the lightbulb - they are seen as being very similar. And even one user who seemed initially quite clear on the difference, at some point described clicking the star as 'liking' the idea. 
- One user suggested if the star means 'Save to your favourites' then it should be the 'Save' icon as found on Insta etc.
- Users are generally understanding in the end what the star does for ideas, but they get confused that there is also a star at the top of the page (topic favourite). One user on mobile thought this must mean she is 'Saving' that phase of the topic, but couldn't see why she would want to.

**Suggestions:** 

- We could change the lightbulb to a 'Like' button. It would be a shame to lose the uniqueness of the lightbulb icon, but would ensure that users everywhere (including older/less tech-using audiences) understand it, as it is such a universally known icon/action. 
- We could also try using an up arrow, as this would help show that upvoted ideas do get moved up to the top. But 'like' would be safer considering we don't have another testing round planned. 
- Instead of the star, we could use the 'Save' icon from Insta etc, and change the wording too? 'Save to favourites?' 'Saved ideas'?   
- In the topic actions menu, instead of 'Favourite' we could have 'Favourite topic' or if changing the wording, 'Save topic to favourites'. So that it's clear to mobile users they are saving the topic, not just the phase that is on their screen.  
- We should edit the tooltip texts too, but can decide that once we've decided if we'll change the icons :)

**Comment by kevincrepin** [comment]
OK let's switch to a thumbs up. Too bad, but no point in holding on to smt if it doesn't work. About the saving: We had this icon previously for "recognise as evidence", but I don't think this is implemented, so let's think something else for that whenever it comes...
![Screenshot 2024-07-05 at 10 48 12](https://github.com/citizenos/citizenos-fe/assets/26792281/08c2b45f-7603-4d9c-94bc-5d167c01c17c)


@ilmartyrk I made a small update to the thumbs up/down icon (slightly thicker stroke) to use for both arguments and idea:

![Icon_Small_Dislike_Full](https://github.com/citizenos/citizenos-fe/assets/26792281/84e49188-6d0c-4f69-9bd8-972fec31e30c)
![Icon_Small_Dislike_Stroke](https://github.com/citizenos/citizenos-fe/assets/26792281/6de9960b-7bcb-443a-8c02-3eda5859cc26)
![Icon_Small_Like_Full](https://github.com/citizenos/citizenos-fe/assets/26792281/181d8d60-aa5e-4f06-b048-973326be9959)
![Icon_Small_Like_Stroke](https://github.com/citizenos/citizenos-fe/assets/26792281/8c311217-cbe5-415a-8515-906e25e2d999)

And the save idea (and maybe later argument) icon: 
![Icon_Small_Save_Full](https://github.com/citizenos/citizenos-fe/assets/26792281/bac7acae-ebdb-4123-861d-a54dcde2a726)
![Icon_Small_Save_Stroke](https://github.com/citizenos/citizenos-fe/assets/26792281/920bc8a3-23b6-46ef-bbcf-3682c8719bd5)

And then let's also change the star icon at the top of the topic to this same icon, so it's all consistent:
![Icon_Big_Save_Full](https://github.com/citizenos/citizenos-fe/assets/26792281/edba9125-3c44-45b5-bf81-3dfbea16aac0)
![Icon_Big_Save_Stroke](https://github.com/citizenos/citizenos-fe/assets/26792281/7823307f-5444-4539-9d7e-1c0695e9bc19)

Be aware this last save icon is the big version, whereas the first one is a smaller version.

**Comment by BeccaMelhuish** [comment]
@kevincrepin Great, thank you! Sad to see the lightbulb go too, but there you go. 

A few other things to make it all consistent now: 

- Shall we also add hover tooltip for the topic 'Save' button? 

"Save this topic to your personal favourites"
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b73ce317-cd8d-4dc2-bbed-72151ba11fd4)

- In the topic 'Manage' menu, should now be 'Save topic'? Or 'Save to favourites'? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/935bc3e8-89a0-4609-b86e-2d43e4795ff0)

- For this one, 'Saved to favourites'? (Am thinking just 'Saved topics' could be confused with the other kind of saving).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/993a8409-cb81-45f4-9e70-815499cc2b6b)

- Add for this, 'Saved ideas'? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/14a328b7-2d69-45af-a73b-37280053b9bc)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin  I updated the icons, but I think before we do any changes we need @oksks input as long strings will break these views

**Comment by kevincrepin** [comment]
Agree with the hover over the icon.

I would say "Save to favourites" as the action and keep in the filter "Favourites". "Saved to favourites" seems a bit unnecessary and tbh a weird filter label.

Saved ideas is ok for me.

**Comment by BeccaMelhuish** [comment]
OK yes, sounds good :)

**Comment by ilmartyrk** [comment]
est. dev time 15 mins. for changing the texts

**Comment by BeccaMelhuish** [comment]
@ilmartyrk A summary of what's still needed as promised, but a couple of them I could do myself in the strings so have ticked them off :) 

- [x] Add hover tooltip to topic save icon: "Save this topic to your personal favourites"

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e1a0c5de-431c-412f-8a0c-1c4786281642)

- [x] Edit hover tooltip here to "See who approved of this idea" 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1c6d6e0b-4b63-42f7-9d72-e91b38d3cb42)

- [x] Change "Favourite" in topic 'Manage' menu text to "Save to favourites"

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/152717ac-6cca-4fc0-b49f-b97adec880b6)

- [x] Change "Favourites" in the idea type filter to "Saved ideas"

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e7f22540-8b8b-48c2-be7c-680293cc2e4e)

**Comment by BeccaMelhuish** [comment]
Sorry @ilmartyrk two things I only thought of when reviewing it: 

- [x] We'll need to change the icon here to 'save' icon as well:

![image](https://github.com/user-attachments/assets/b41f2107-0e50-4dcb-a98d-aca09a74f263)

- [x] And for the tooltips that say 'Save idea to your personal favourites' and 'Save topic to your personal favourites', once someone has clicked them, the hover tooltip should then switch to saying 'Idea saved to your personal favourites' and 'Topic saved to your personal favourites'.
