### ISSUE TITLE
TOPIC: Double notification for invites sent & topic updated

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1255]
In a test, on test app, for an ideation topic (he only sent one invite - invited me):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4bc3517e-050d-4254-9f75-d98808fc110a)

**Comment by BeccaMelhuish** [comment]
Same thing here with topic updated notification, user was using Firefox: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/77e5dd2d-06a3-467e-aa97-2800a1ca9bab)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think this is fixed now, as I remember doing something related to that in a more recent issue

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate but let's keep an eye out for this one
