### ISSUE TITLE
IDEATION / VOTING: User confusion about 'Choose from ideas'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1258]
@kevincrepin @ilmartyrk 

**Round 1 ideation admin and Figma prototype UX test insights :**

1 out of the 4 admins who found the 'Choose from ideas' voting option for ideation topics was confused by it and didn't use it as he didn't understand how it worked. (The 5th one didn't find ideation voting at all). 

He said "How can a person choose an idea as a voting answer?". And as he couldn't imagine how it worked, he discounted it and instead chose a 'Custom choices' vote, and made the vote about something else. But from seeing his use case, I think this option would have been exactly what he wanted. 

**Suggestion:**

Either we try to improve the explanatory text (or add a tooltip), with a bit more detail on how it works. Or, I'm wondering: could it be that as soon as you have clicked here, it opens up and shows you the folders and ideas to choose from already. That way they would see instantly how it works. (It was only 1 of the 4 though, so maybe not worth such a big change).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8621e590-9b58-4581-99e3-aa1720fd366f)

**Comment by kevincrepin** [comment]
Looking at this now in the bigger picture (that being dynamic and multiple phases), would this still be an actual option? If we allow for the topic to have multiple ideations, then how would this option know from which ideation to choose? Or it could include ALL but it becomes so messy so quickly I'm wondering it the value is there to design and develop it so it works...

I think we need to put a pin in this until we have figured out the dynamic phases topic.

**Comment by BeccaMelhuish** [comment]
It's true yes if we do go with having multiple ideations per topic that might complicate the idea selection process! Though I think we could find a way to make it work, if that's what the user's processes need. As it seems like it's an important part of the ideation process - voting on the ideas after they've been generated. 

Re the timescale split, how about this:

- **Ideation launch fix:** Improve the copy or add a tooltip, to make it clearer how this works, at the point of selecting voting type. 

- **Bigger structural fix:** Re consider this once we know if we'll have multiple ideations or not.

**Comment by ilmartyrk** [comment]
Will it need a tooltip or we could just update the option text?

**Comment by BeccaMelhuish** [comment]
Yes possibly just the existing text indeed, I'd suggest this. A bit longer, but I think should make it pretty clear? 

_Participants can vote for their preferred idea(s) from the ideation phase. In the next step, you'll choose which ideas to include in the vote_

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bfa4d026-b9d8-4eff-9a4c-22338ef6cff6)

**Comment by kevincrepin** [comment]
Yes, if there's already dedicated space for explanatory text, then let's use that. We should try to avoid needing to use both a tooltip and an explanatory text that's already visible simultaneously.

**Comment by BeccaMelhuish** [comment]
Checked and all good - closing :)
