### ISSUE TITLE
IDEATION: User confusion around naming of 'Ideation' and 'Discussion' topics/phases

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1261]
@kevincrepin @ilmartyrk 

**Round 1 ideation admin UX test insights:**

Two users had issues with the naming of the topics / phases, to different degrees:

1.  For one user, it was quite serious. We were testing a use case that was much better suited to ideation (coming up with and deciding on membership criteria for a collective), but he chose to make a discussion topic. At some point I steered him to revisit his choice (so we could test ideation). Looking at the menu he agreed on reflection ideation would be better, but was still clearly quite confused. A few things he said at various points in test:
- Didn’t choose it as “was clear I needed a discussion rather than ideation.”
- For him, ideation would be rather: “Should we have a membership criteria or not”? (Which to us, would be more discussion suited)
- “I’m not able to understand the difference between an idea(tion) and a discussion”
- When I nudged him start an ideation topic - “Do you want me to change the scenario. To make it rather ‘Should we have a membership criteria or not?'
- "Do I also need a discussion, or can directly go to vote? There are a couple of ideas where the discussion is happening in the replies.”
- "The (differentiation between the topic types) doesn’t seem high for me." 
- When referring to the ideation, at times calls it "the discussion". 
This was all from a smart and tech-savyy lead member of a collective that is all about collective decision-making (in India, perhaps there's some different wording there). And he had taken the DB tour, but not the topic tour. 

2. For the other user, it was much less serious. But he wasn't familiar with the word 'ideation' and took a little time to work it out. He had very good English as far as I could tell from speaking and seeing his texts. He did guess it correctly though, so didn't cause problems, just a bit of thinking. 

(The other 3 admins didn't seem to have any issue with the naming, though one did say "Now I can get the discussions started" when she had finished her group, referring generally to ideation and discussion phases (she right after that made an ideation topic)). 

**Suggestion:**

As it was only 1 admin who really struggled, maybe we just tweak the create menu texts a bit and see for the next round. But if we do want to try something more, some ideas below. 

Users are often launching quite quickly into making a topic, without having seen how one works. I.e. not having seen what happens in an ideation topic, or in a discussion topic. Sometimes they look around at public topics first, but not always, and what they see depends on the phases within them. So maybe there's some way we can visually show them the structure of the type of topic they have chosen, when they choose it? Or before they get to it, like on the logged out (or logged in) dashboard. As then they are more likely to choose the one that has the right structure for them. 

It seems a very valid point to me that there is 'discussion' that happens in the ideation phases. As suggesting ideas and then having back and forth reply threads (discussions) about them, is still a discussion, it's just an ideas-based discussion. So some ideas for possible changes to the texts below. But I don't really have a solid proposal (not too keen on these myself, none of them really seem to work), just ideating :D  

Instead of ideation / ideation topic: 
- Gather ideas
- Gather & discuss ideas
- Idea-gathering
- Ideas 

Instead of discussion / discussion topic: 
- Discuss pros and cons 
- Pro-Con
- Debate 
(as the pro and con structure of the discussion tab does make it more 'debate' like than the ideation discussions). 

I.e. for these bits:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/aac3d146-9e26-4026-9b05-e6b62bede2af)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3028b693-093f-4aec-b2fa-d378b1bc8382)

**Comment by kevincrepin** [comment]
I think one issue is also that currently we call these things topics, whereas they are phases. And as we discussed in our last call it's just one topic which includes different phases. Maybe this would already solve a lot and if then on top these phases get a proper explanation I would hope it'd be clearer?

**Comment by BeccaMelhuish** [comment]
Hmm yes, some ideas for how to split this timescale-wise then:

- **Ideation launch fixes:** We adjust the structure and copy of the create menu a bit, but keep the rest the same. (Ideas coming below). 

- **Bigger structural fixes:** We can revisit this once we know how phases will work in future.

**Comment by BeccaMelhuish** [comment]
@kevincrepin proposed changes to the create menu to test in Round 2, what do you think? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d4aea976-f502-4141-8d77-a75adfac536d)

At the top: "Choose your topic's starting phase". 

- **Idea gathering**
Start with an ideation phase to gather ideas before potentially moving on to pro-con discussion and/or voting and follow-up. 
- **Pro-con discussion** 
Choose this if you want to discuss pros and cons before _(etc, same as it currently is)._ 
- **Voting** 
_Text same as current_

(I'm not sure how this would work with the 'Group' bit at the bottom though, maybe you have thoughts on this? I have been thinking, though it's a separate issue from separate insights, that we might want to put 'Private group' and 'Public group' both on the menu, to better explain the usage of public groups for collecting topics together, which is still sometimes getting missed). 

The phase 'tabs' would still be the same as they are (i.e. still 'Ideation' not 'Idea-gathering', 'Discussion' not 'Pro-con discussion') but through the menu we'll have taught them what we mean by this.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/244e3f53-8f82-4e11-b583-f082b39f5285)

**Alternatively, we could call the 'Ideation' phase the 'Ideas' phase**, and the tab (and all other places where the phase is named) could be 'Ideas'. 

I've now noticed in the participants analysis that one participant (native speaker, 90y/o) looked at the below and said: "Ideation, what does that mean?". So it's probably more in the design or business world that this term is used, whereas for the average user, 'Ideas' would be simpler. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7f90916d-520b-45b6-bc97-967468ff4e3a)

In which case, the menu texts could be:

- **Ideas**
Choose this if you want to gather ideas before potentially moving on to pro-con discussion and/or voting and follow-up. 
- **Discussion** 
Choose this if you want to discuss pros and cons before _(etc, same as it currently is)._ 
- **Voting** 
_Text same as current_

**Comment by kevincrepin** [comment]
Random thought, what about 

_Choose how to start your topic:_
- with idea gathering
- with a pro/con-discussion
- with a voting

Or _Create a topic starting with:_

Personally "Choose your topic's starting phase" feels a bit awkward, but then again I'm not native, so just wanted to bring in this suggestion – I'll go with whichever you choose, @BeccaMelhuish :)

However the wording, I added the title to design:
![Screenshot 2024-06-07 at 14 33 08](https://github.com/citizenos/citizenos-fe/assets/26792281/152ecd42-14a8-4a3d-8db7-45031ef52d63)

Figma: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=2-8742&t=xoQN4LtSq20tl0HZ-1

**Comment by BeccaMelhuish** [comment]
Hmm yes you're right, let me think about the menu copy and come back to it on Monday! 

What are your thoughts on calling it 'Ideas' phase throughout though, e.g. in these two places, and elsewhere: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/085d21a1-a3f7-445e-839b-d881ddbc1394)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e013d623-fb54-4f61-8f3c-6dd3935b7b95)

**Comment by kevincrepin** [comment]
I personally prefer "Idea gathering", feels a bit weird to just have "ideas" ;)

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK yes :) 

Was just thinking that was a bit long for this bit (and maybe even longer in other languages?), but if you think that's OK then let's go with it:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c577202b-d231-4965-a527-de4839f643ab)

**Comment by BeccaMelhuish** [comment]
And have had a think on "Create a topic starting with": yes sounds good! 

Will tweak the menu texts once we're clear on what the 'Ideation' phase will be called :)

**Comment by kevincrepin** [comment]
Good point about the length. Hard to make a call here. Maybe it can be "Idea gathering" in the Create-menu, but in the tabs it can be "ideas"? I think the connection would be clear enough.

**Comment by BeccaMelhuish** [comment]
Yeah I think that works fine! 

@kevincrepin Which would it be here though? Not sure myself which I would go for to be honest - there is space for 'idea gathering' but then more consistent with the tab if just 'ideas'. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7b94a866-a848-4bc1-b09a-e90f1aced48a)

**Comment by kevincrepin** [comment]
I would go with "idea gathering" since we already have "4 ideas" on the right :D

**Comment by BeccaMelhuish** [comment]
Ah good point indeed! 

So @ilmartyrk just to clarify, full text changes should be: 

_In the create menu:_

**Create a topic starting with** 

**Idea gathering**
Start with this phase if you want to gather ideas before potentially moving on to pro-con discussion and/or voting and follow-up.

**Pro-con discussion**
Start with this phase if you want to discuss pros and cons before potentially moving on to voting and/or follow-up. No idea gathering available. 

**Voting**
Choose this phase if you want to collect people's votes before potentially moving on to follow-up. No idea gathering or pro-con discussion available. 


_In the phases tab:_

Ideas

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/23681bb0-984f-4ce1-83c6-5a73a8a9706c)

_In these blocks:_

Idea gathering 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4ceb6d9c-9b08-4b59-85a7-67717d8b1e5a)

**Comment by BeccaMelhuish** [comment]
Looks good, closing :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah sorry, noticed a bit missing actually :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3a3f3fd2-2b53-421a-a01a-dbb3614a5c40)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d2173d8a-3203-4a21-8283-d2f4db81f2b0)

**Comment by BeccaMelhuish** [comment]
Also @kevincrepin, unless any objections I will change these texts to: 

'Create a topic starting with idea gathering'
'Create a topic starting with a discussion'

But keep the last one as it is:
'Create a voting topic'  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/95af4a86-5c34-4d41-83b3-8512c10b2a1f)

But @ilmartyrk I can do this bit myself in the strings so no worries :)

**Comment by BeccaMelhuish** [comment]
Hmm though @kevincrepin this one is trickier as it would be too long for the buttons..

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/743bc6e7-172f-4d9d-a7af-a62fcd9d5674)

I will go with this for now, but let me know if you have other thoughts:

- 'Start idea gathering' 
- 'Start a discussion'
- 'Start a vote'

**Comment by BeccaMelhuish** [comment]
I've generally taken out all references to X topic (e.g. ideation topic, voting topic, etc). But for this bit (and equivalent in the other topics) I'm not sure what to do, will leave it for now :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4310c6ef-adac-4fb8-a338-ec55ad98217c)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the title to the create menu

**Comment by BeccaMelhuish** [comment]
Grand, thank you! Will leave open for @kevincrepin to review the text edits :)

**Comment by kevincrepin** [comment]
Generally all ok for me!

'Create a voting topic' Could maybe be "create a topic with voting options"? If that doesn't make sense then let's keep it as it is!

**Comment by BeccaMelhuish** [comment]
Grand, thank you @kevincrepin! 

I think "Create a topic with voting options" does work, will switch it now :) 

What about the 'Edit (X type of) topic' part like below for example, shall we just make it 'Edit topic' across all topics? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/11bf310b-bb85-49a9-9118-482a190db46f)

**Comment by kevincrepin** [comment]
"Edit topic" is ok for me. When we look at the dynamic/multiple phases then probably there's anyway an "edit topic" and "edit phase" possibility.
