### ISSUE TITLE
IDEATION/TOPIC: Insufficient permissions and not saving draft when editing topic text

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1262]
I don't have screenshots as was in a test, but what happened (from memory, I hope correct) was: 

- Had run the ideation phase. 
- Moved on to the discussion phase. Can't remember if I had 'started' the discussion or not at this point. But I wanted to edit the text so it would make sense for the discussion. 
- Went into 'Edit topic' and changed the topic text. 
- Tried to 'Save changes & publish', got an 'Insufficient permissions' error. 
- Tried to 'Save as draft' and couldn't. Can't remember if I got the 'Interrupt process' pop-up at that point or when trying to exit with the X. I believe it was when clicking 'Save as draft'. 
- Agreed to interrupt the process. 
- Was expecting this meant I couldn't edit the text. But actually when I went into the topic it actually had been edited. 
- Saw another thing needing editing in the text, and repeated all the above, with the same problems and same end result.

**Comment by BeccaMelhuish** [comment]
Adding pre UX tests label as makes the participant tests a bit tricky to run, but not the highest of priorities as I can work around it.

**Comment by ssin1901** [comment]
@BeccaMelhuish here are the steps I followed

Tested in Google Chrome

1. Started ideation phase (screenshot1)
2. Added an Idea (screenshot2)
3. Added a Discussion (screenshot3)
4. Went to Edit (screenshot4)
5. Edited (screenshot5)
6. Click Save changes & publish (screenshot6)

Did not encounter permissions error. Testing another scenario (with draft topics)

<img width="1376" alt="Screenshot 2024-06-03 at 16 48 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/347779a2-88db-4eab-8d1e-c2d68a0a0bc3">

<img width="1367" alt="Screenshot 2024-06-03 at 16 48 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2ba58cf6-042c-4865-9dd4-76d60a35d122">

<img width="1375" alt="Screenshot 2024-06-03 at 16 48 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ae46a551-bc7e-4fa0-b59e-6a7b49525b8c">

<img width="1195" alt="Screenshot 2024-06-03 at 16 49 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bd6fba58-d6a7-471c-9224-5fa4c58dd880">

<img width="1194" alt="Screenshot 2024-06-03 at 16 49 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/295ff4b6-1d50-4743-b613-6a96ba49047d">

<img width="989" alt="Screenshot 2024-06-03 at 16 52 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/333f2faa-7fe9-480c-8e98-7b5de2c9177a">

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish the issue was caused by edit/create ideation topic view. Ideation was already over, but when trying to  save topic in this view it also tried to save ideation and that was forbidden as the status of the topic didn't allow that. Fixed it so that topic parts that we allow to edit are editable, but ideation part is not.

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish could not replicate the issue, saved drafts works as expected, interrupting the process causes edits not to be saved and I was able to edit and publish the ideation topic as expected.

Can I close the issue and we can re-open it if it happens again?

**Comment by BeccaMelhuish** [comment]
Great yes, have closed :)
