### ISSUE TITLE
DISCUSSION: Reply should be visible after posting.

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1263]
Seems to just be a UX BUG so probably not needing Kevin's input: Once a user has posted a reply, it should stay open so they can see it posted. Then they can choose to close it if they wish. 

While typing reply: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c53dbf00-8132-4abd-b94b-6af69babe724)

As soon as have posted reply: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7f45cff3-fb82-4e55-8c91-a8ae9890498d)

**Comment by kevincrepin** [comment]
Yep, definitely should stay open after posting! Let's only hide after user consciously clicks the button to hide ;)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk, added this to ideation project as it's relevant to both :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin A similar question so will ask it in the same thread. What should happen just after you post an idea. Currently you post it, and your next view is this below. 

**Round 1 participant ideation user insight** from 90y/o user was that a couple of times, after she had posted her idea, it seemed like she was trying to see it, but was struggling to find it (e.g. trying clicking 'add your idea' again, for example). 

Am wondering if after you post it should pop-up in the 'expanded view', or what the best UX would be? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ce63c691-f555-4fc9-82bc-3852a6e3751c)

**Comment by kevincrepin** [comment]
Hmm, yes, I think it wouldn't hurt to end up on the opened idea. This way we avoid any confusion about whether the idea actually got posted.

![New idea posted](https://github.com/citizenos/citizenos-fe/assets/26792281/383028de-19eb-4b60-b015-a007a4799e33)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk have tested this and it's good for the idea itself, but also needs to be the case for when you post a reply to an idea or argument/contribution. 

So e.g., just after posting a reply it should be open like this - in discussions as well as in idea gathering :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/868121b4-2fc6-420c-84a6-a9a2c6f29071)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk maybe you're in the middle of this, but in case not: it seems like it's fixed for first level replies currently, but not yet for second level :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b5a4320d-9086-4ad7-a3b1-9824de2adbe4)

**Comment by BeccaMelhuish** [comment]
Also needs to be the same in the discussion phase (there both replies, and replies to replies, currently close after posting)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish quiet difficult to solve at the moment, I will try to come up with something, but cannot promise anything before testing tomorrow

**Comment by BeccaMelhuish** [comment]
Ah OK yes no worries! I guess if it's part way through the testing that's still good, and if it can't be tested this time so be it :)

**Comment by ssin1901** [comment]
@ilmartyrk if there is no fix, can we move this to In Progress?

**Comment by BeccaMelhuish** [comment]
Good point @ssin1901, should be in progress :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk now that [this issue](https://github.com/citizenos/citizenos-fe/issues/1328) has been completed, does it make this one more feasible to resolve quickly? 

Adding high priority as if it's now a quick fix I'd say it should be done before launch, but remove it if you disagree :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it was fixed by the other issue fix

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk after the user has posted a reply, the reply is closed (screen recording 1)

https://github.com/user-attachments/assets/eaa32814-b817-4b91-bbd8-2c02123f0776

**Comment by ilmartyrk** [comment]
Couldn't make it very smooth at the moment, It took a lot of time to create the current version and I guess it needs more thinking/research to properly solve it

**Comment by BeccaMelhuish** [comment]
Tried it out and I think it's good for now! 

@ssin1901 will leave for you to move to 'Done' in case it needs more testing :)

**Comment by ssin1901** [comment]
@BeccaMelhuish Ilmar seems to have fixed the UX (see screen recording 1)so moving to Pre-Live. Just let me know if it needs to go in Done though.

https://github.com/user-attachments/assets/c78170cb-a5a2-4c90-bc97-d5dc12246eab

It also works fine when the reply is nested (see screen recording 2)

https://github.com/user-attachments/assets/2ccbe67a-037a-4b20-a33c-105432308bd3

**Comment by BeccaMelhuish** [comment]
I think this can go to Done as it's already working in live :)
