### ISSUE TITLE
IDEATION: Error when trying to publish / save a new topic. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1264]
Was making a mock topic for a test. Got to the 'publish' stage and got this error below. Same thing happened when I tried to save as draft. Had to 'interrupt process' and expected to lose it, but then found it was actually saved. Went into the draft and found all was saved except the header photo, ideation and deadline. Added the ideation Q and deadline, and published, and it worked. Went back and added the photo and that worked too.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6e7fa809-81c2-48bb-a7bc-4d3d2bbcea68)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I could not replicate it, can you provide more info, this error is specific to image upload endpoint, so maybe more info about the image

**Comment by BeccaMelhuish** [comment]
@ilmartyrk this was the photo and details:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/18d0110e-4db0-40ad-83e2-2c8db98ff853)

![BRM criteria](https://github.com/citizenos/citizenos-fe/assets/61320526/36d5b8a6-f200-4bbc-925c-980ef34e6926)

**Comment by BeccaMelhuish** [comment]
I believe I had the same photo in header and in attachment, if that's relevant

**Comment by ilmartyrk** [comment]
@BeccaMelhuish not sure what happened, but as there are many changes to the code for the creating flows and I could not replicate this issue in live I am closing this issue

**Comment by ssin1901** [comment]
Moving to Done as could not replicate
