### ISSUE TITLE
IDEATION / TOPICS: Duplicating topic error

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1265]
In test, tried to duplicate an ideation topic which I didn't create but had admin rights to and got "Forbidden".   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/934cecec-e864-4d4e-8cbd-e1d1552d0fe3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish we currently allow only creators to duplicate topics, but I guess we should allow all admins

**Comment by BeccaMelhuish** [comment]
@ilmartyrk yeah seems best!
Have moved it to testing so @ssin1901 can check :)

**Comment by ssin1901** [comment]
I think this works well (I tested it with second admin who wasn't the creator)

https://github.com/citizenos/citizenos-fe/assets/72747107/7d5e5684-96af-4b41-a64e-6aab8ec6cdf0

Closing the issue.
