### ISSUE TITLE
IDEATION: Co-editor view not displayed 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1266]
**What is the problem?**
_Tested in Google Chrome_

In co-editor view, the view is not being displayed correctly (see screenshot1)
<img width="1198" alt="Screenshot 2024-06-03 at 11 26 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f1bdbeda-76a0-4e5e-9ff6-021e4c23038c">

**Why is this a problem?**
Confusing to the user

**Possible solution.**
Co-editor View should be displayed correctly

**Comment by ilmartyrk** [comment]
@ssin1901 these are actually missing translation errors, so I was thinking maybe we could categorize these as missing translations issues in the future

**Comment by ssin1901** [comment]
@ilmartyrk can do that. Should I create a separate label? This one is fixed though (screenshot attached) so I will close
<img width="1376" alt="Screenshot 2024-06-04 at 13 21 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ff283451-6ca8-465c-a1ed-b1127b7c13ae">
