### ISSUE TITLE
IDEATION: Reply opened scrolled down

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1271]
When user opened idea, the reply thread was already scrolled down, so she didn't see the avatar and name, date menu etc at the top.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e1467a23-2e53-4fcf-ac81-5fefee83b941)

**Comment by ilmartyrk** [comment]
Closing as the view has changed
