### ISSUE TITLE
VOTING: Voting Q disappeared

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1272]
In a test, user was making a voting topic, she had entered a voting question and it looked fine in preview: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/171932fa-519b-435e-a6d8-eb57fac50503)

But then when she clicks publish, she gets this error and the Voting Q has disappeared:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d9288971-9067-47ad-a52d-22b403f560d9)

(Was the end of the test so we just left it at that point, so no more details for you).

In case relevant, she had started with another voting Q, got to preview, then gone back and edited it (and the topic text too), and came back to preview again.

**Comment by BeccaMelhuish** [comment]
I don't think this happens any more so can be closed, but will put into QA testing for @ssin1901 just in case

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate. Can I move to Done? I think it has been resolved.

**Comment by BeccaMelhuish** [comment]
Done :)
