### ISSUE TITLE
IDEATION: Number of ideas showing 0 when there are more

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1273]
For me, in this one, there are actually 2. And in a user test today I noticed the same thing on his screen (with a different topic, there were multiple ideas in there but it always said 0).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dd861275-4706-4b7b-8f90-9047416815a3)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think this has been fixed as I didn't see any mismatch between my ideation topics and the number of ideas being displayed. Should we close it and re-open if it occurs again?

**Comment by BeccaMelhuish** [comment]
OK sounds good yes, will keep an eye on it :)
