### ISSUE TITLE
IDEATION: An idea went missing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1274]
In a topic that I used in a user test, one of the ideas is now missing. It says '9' ideas at the top, but there are only 8 showing. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9d522424-7345-4ce2-ba10-7d9ab118ec26)

I checked back the recording of the test, and the idea is visible there: 
(I didn't delete it myself, and the user wouldn't have been able to as it wasn't his idea). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1ceafe0c-c69f-49be-8cd3-4413b0c96ceb)

**Comment by ilmartyrk** [comment]
pagination was not working properly

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I checked this on the same topic, and now the page numbers do show, but there's still some problems: 

Also, I'm thinking 9 ideas is too few for each page and see on the prototype that it's 15 - could it be upped? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d9034e30-0e9b-4e07-8365-1b684cd04738)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/010a967b-7f04-4a05-aafb-6ad1f0c24be7)

**Comment by ssin1901** [comment]
@BeccaMelhuish pagination appeared for the 16th idea with the first 15 ideas appearing on the 1st page (screen recording1, screenshot1, screenshot2). Page number also updated correctly. 

Can we close?

https://github.com/citizenos/citizenos-fe/assets/72747107/118c1b31-6bb8-4ba8-a404-c511eb0f7c57

<img width="1340" alt="Screenshot 2024-06-26 at 17 53 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a4676717-ce17-4c42-bbf5-d572926e4681">

<img width="1342" alt="Screenshot 2024-06-26 at 17 53 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f313096a-f142-44fc-8523-3791d25270bd">
