### ISSUE TITLE
IDEATION: Character limit bug and UX insight

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1276]
Two things here :) 

- Yellow bit: Double character limit and mismatch same as [this issue](https://github.com/citizenos/citizenos-fe/issues/1004) for discussions, should be resolved the same way. 

- Red bit: Is this as per the design. Needs moving as is a bit confusing whether it is for the top field or bottom field (as pointed out by a user in a test). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/580f5a5d-b166-4efd-9cad-600c41b70df3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish red bit I could not find from designs, but I guess it was added at one point because of reasons. I guess we have issue about it somewhere, but couldn't find it. Anyway I guess if the bottom counter is removed it should be quite clear for what it stands for. Also number changes while user edits the input

**Comment by BeccaMelhuish** [comment]
Hopefully @kevincrepin can propose the best option, but it's still confusing having it where it is - it looks like a heading for the explanation field :) 

Have suggested two possible other places for it, probably the one on the right is best, fairly consistent with the one below (text must be consistent too though ofc): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/60d279c3-255b-4dec-8165-0c199f74c3f5)

**Comment by kevincrepin** [comment]
Can we do it like this? Top right corner in the field?
![Screenshot 2024-06-06 at 12 52 03](https://github.com/citizenos/citizenos-fe/assets/26792281/8df3d065-c76a-46f9-a298-cd3eef665ff7)
