### ISSUE TITLE
IDEATION: User could only add shortened idea, despite being within character limit

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1277]
User (last Monday), tried to add an idea, but was getting this error.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/095592c7-91fe-4fc3-ae6c-be688746548b)

Tried repeatedly and no luck. In the end we tried making it shorter and it did work. But she wasn't over the limit. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8ddd64b2-3cb8-4b25-a73e-4732e8a2255b)

Maybe connected to [this issue](https://github.com/citizenos/citizenos-fe/issues/1276)?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix, was issue with the database field allowed text length, issue 1276 is not related

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish Ideation is now broken in multiple places if more than 2048 characters are added in the description (see screenshot1, screenshot2).

I am opening another issue, and I will retest this issue after the other ones has been fixed

**Comment by BeccaMelhuish** [comment]
Moving it back to in progress then :)

**Comment by ssin1901** [comment]
@BeccaMelhuish seems fixed, can we close (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/cd8122b9-02f0-4b50-9aa9-d9a70ba2d48c
