### ISSUE TITLE
IDEATION: Internal Server Error when reporting own idea

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1278]
I guess probably just as it was her own one, but user was testing out reporting (on her own idea) and got this error:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/be043492-19d5-4112-b96b-64e25ab36e74)

**Comment by ilmartyrk** [comment]
Duplicate of https://github.com/citizenos/citizenos-fe/issues/1191

**Comment by ilmartyrk** [comment]
@BeccaMelhuish can you provide more info under #1191, eg. when was this test done so I can check if it is a missing translation error something else
