### ISSUE TITLE
Topics: Topic showing up twice but is the same topic (content synced)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1279]
In a user test, at some point between discussion and voting phase (I believe when I started voting, but not sure), my topic started appearing twice. 

It showed twice for the user on the test, and still shows twice for me now:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1f52891a-d481-40c4-94fd-e8dc76b3b6a5)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a4d5ad8d-3852-402c-a6f3-1f7b9978499b)

I just tried adding a new follow-up update to see if it appears in both of them, and it did, so they seem to be the same topic, just appearing twice:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f2d9f255-85e6-412d-9788-50f872a2bea6)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is now fixed
