### ISSUE TITLE
IDEATION: User preference for seeing who has up or downvoted idea replies (and ideas?) 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1280]
@kevincrepin @ilmartyrk 

Only from 1 user, but seeing as we have it already for discussions, seems it would be consistent and hopefully technically easy to add? 

**Insights from Round 1 ideation admin UX tests**

One admin said he would like to be able to see who has liked or disliked an idea reply, to get a better sense of the discussion. I assume he'd also want to see who has upvoted (lightbulbed) an idea, but he only mentioned it for the up and down on replies. So am not sure on that. The use case was for internal decision-making in a youth social movement. 

**Suggestion:**

Add this feature like we have in discussions? Though this would be a pop up over a pop up, so maybe not working?

**Comment by BeccaMelhuish** [comment]
Actually I just noticed from another test recording that this was already possible? So I think it must have been either a bug or a UX issue that meant the user above didn't find how to do this, i.e. here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/941b6637-eee1-4ee4-b008-e23a9c54cdcc)

But will leave this issue open anyway, in case we want to add a way for users to see who has 'lightbulbed' the idea - as this would be more consistent then (and arguably more important to see that than to see who reacted to a reply). Not sure how we would do it though, as clicking here is already an action (to toggle it on/off). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7f0bb9f9-b6d0-40e0-80f2-bbeeb4148348)

**Comment by kevincrepin** [comment]
I fixed it now in the latest iteration of the "insightful" bulb:

![Screenshot 2024-06-07 at 15 14 59](https://github.com/citizenos/citizenos-fe/assets/26792281/d3e5d488-cfae-4f4f-97f8-65e14ebec604)
![Screenshot 2024-06-07 at 15 15 06](https://github.com/citizenos/citizenos-fe/assets/26792281/2938776c-129c-4085-a99b-df337a1d0614)

**Comment by BeccaMelhuish** [comment]
Ah though @kevincrepin he actually wanted to see which people in particular had liked it, like we have with the discussion and vote replies, when you click it and you get this:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7377ccec-edcf-4104-832a-26dd92c0e50f)

Though just to clarify, the user actually mentioned this in relation to the idea replies (which for some reason he wasn't seeing), I've just made the assumption that if he wanted it for that he would have wanted it for the idea likes (seems more necessary for that, and a bit inconsistent if we show it for replies but not for the main idea?).

**Comment by kevincrepin** [comment]
Yes, we can reuse that logic: just click on the number and this dialog window would open.

**Comment by BeccaMelhuish** [comment]
Ah got it, yes that's good thank you!

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish I replaced the thumb-up icon with the lightbulb for this dialog

**Comment by BeccaMelhuish** [comment]
This seems done to me so moving it to testing in case @ssin1901 needs to test anything, but from my side seems good :)

**Comment by ssin1901** [comment]
@BeccaMelhuish this is how it currently works (see screen recording). If all fine, then you can close the issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/11a3ea61-a1be-4e09-9f6d-c2d45ac34c9c

**Comment by ssin1901** [comment]
@BeccaMelhuish I think this issue can be closed?
