### ISSUE TITLE
IDEATION: UX insights around idea folders

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1281]
@ilmartyrk @kevincrepin 

**Insights from Round 1 ideation admin UX tests**

- Admins are often not noticing the folders tab. 
- Some initial uncertainty from admins around what they'd used them for, but when pressed see that it could be useful. 
- One user (who hadn't seen them) when asked what she'd used them for, showed that she misunderstood them to be more like folders for storing files for the participants (and said that could be useful). However, she later said that she was missing something for categorisation, such as tags. (So was happy to discover that that's actually what the folders were for). 
- 3 of the users showed a preference for tags rather than folders, or an interplay between tags and folders. Whether it should be only admins or participants that would be able to apply the tags to ideas wasn't clear in all cases, but in one case there was a clear preference for user-added tags (to start of the categorisation in a bottom-up way, and to make the work easier for the admin(s)). 

**Suggestions:**

I don't have a strong sense of the importance of the above insights for users, and it may be that we leave it as it is and keep an eye on it in future tests, but some ideas if we do want to adjust: 

- Could we have some sort of explanatory text block in the folders tab for "There are no folders yet", like we have when a user first arrives and has no topics or groups? This would help make it clear what they're for. 
- Maybe the folders tab needs to be a little more prominent/eye-catching somehow? Though seems likely they would find it with more usage. 
- Could/should this idea of tags (potentially user-generated?) be integrated into the way that folders work? Could the names of any folders the idea as been added to show up like a tag on the idea when expanded?

**Comment by kevincrepin** [comment]
Fully agree on the empty state, that's needed:
![Screenshot 2024-06-10 at 17 22 10](https://github.com/citizenos/citizenos-fe/assets/26792281/7e833c0c-0938-404e-87e6-b74e60ae2c49)

I don't think it needs to be more eye-catching, otherwise we keep "fixing" things and making everything eye-catching which is probably not gonna help either :)

But we can show if an idea is part of a folder, doesn't hurt:
![Screenshot 2024-06-10 at 17 38 55](https://github.com/citizenos/citizenos-fe/assets/26792281/db666fc6-ef5b-4599-a9f7-65062d112718)
I think we can show if it belongs to several folders, and we can make them clickable also. But I wouldn't go so far as it have some filters in the folders in order to find an idea across different folders. Seems overkill.

**Comment by BeccaMelhuish** [comment]
Nice, this all sounds/looks good! 

I might go for "Added to Folder x, etc" for the copy though, wdyt?

**Comment by kevincrepin** [comment]
yes, definitely better! :D

**Comment by BeccaMelhuish** [comment]
@ilmartyrk great thanks! Though 3 things:

For participant view, let's change the text from "You can" to "Topic admins can" and get rid of the button entirely.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/36652a9b-26ff-4992-9f6b-8c9b0d3c7ff5)

And for ideas that haven't yet been added to any folders, I think let's remove it for now, but tagging @kevincrepin in case he has other thoughts :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a0b3e95b-f5a9-49b9-863e-5abd96e5db15)

For the ideas that have been added, I think the blue text is meant to be that you can click through to view that folder: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c12d0c76-6107-4d3d-9689-ddb205859589)

**Comment by kevincrepin** [comment]
Yes, in case an idea hasn't been added yet, we shouldn't show at all the "icon+ added to ..."

**Comment by BeccaMelhuish** [comment]
@kevincrepin Great. And the blue text is meant to be clickable through to the folder right?

**Comment by BeccaMelhuish** [comment]
Also @ilmartyrk, this should say 'Admins' in participants view:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0721e7e9-c9ba-4951-9a50-aad3b1296cfd)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I just checked this one from the pre-testing wishlist, and mostly it's done, but this making clicking the blue text click through to the folder (as it's blue it looks clickable) part isn't done - is it a quick job, or more complex? 

Am adding high priority in case it can be done before launch, but if a bigger job no worries - maybe the colour can just be changed to black for now? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c5f8783a-6a12-4ca1-8c80-6c2d0758c281)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk re the last one (link to folders), I tried it in [this topic](https://test.app.citizenos.com/topics/join/6BMgWrskz56e) (with ideation closed), while logged in as both participant and admin (same thing both times), and this happens:

When I click the folder in this idea:  
![image](https://github.com/user-attachments/assets/63990f83-ce12-4988-8649-d437232e64d6)

I get taken to the voting tab: 
![image](https://github.com/user-attachments/assets/07dd8489-01c1-468c-abb9-a90bd4726522)

Tried it for a few ideas/folders in that topic and same thing. 

Tried in a different topic in which the ideation is still open ([this one](https://test.app.citizenos.com/topics/join/ILyRe6BcKWsr)), while logged in as admin, and nothing happens when I click the folder, it just closes the idea. 

![image](https://github.com/user-attachments/assets/b33bd7bf-d3fb-4413-b6c9-968653bee731)

![image](https://github.com/user-attachments/assets/3624ef95-d377-4150-82ea-0874f4bb6489)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now, also please reopen if issue not fixed, only noticed it going through emails :)

**Comment by BeccaMelhuish** [comment]
Ah yes sorry, getting used to the new flow :) 

Seems to be working! There's something that could be improved, but I've made a [new issue](https://github.com/citizenos/citizenos-fe/issues/1392) 

I will leave it to @ssin1901 to move to Done, but as far as I'm concerned it's good :)

**Comment by ssin1901** [comment]
@BeccaMelhuish Seems fixed. Moving to Done.
