### ISSUE TITLE
IDEATION: Title and description not correctly displayed when title and description exceeds the character limit

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1282]
**What is the problem?**
If a user enters a title and/or a description **exceeding the character limit**, the display is incorrect (screenshot1, screenshot2, screenshot3)

<img width="1196" alt="Screenshot 2024-06-05 at 13 23 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7cd57b75-da24-442e-a433-e7462b01d1e9">

<img width="1197" alt="Screenshot 2024-06-05 at 13 23 55" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0c848700-b1da-4ba9-8213-bc2e6fd1ae37">

<img width="1109" alt="Screenshot 2024-06-05 at 13 30 30" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d5d204d1-1dc2-40b6-ba99-0bbe38608daa">

**Why is this a problem?**
Broken view, impossible to read text. High priority as it may affect the upcoming user tests @BeccaMelhuish 

**Possible solution.**
Title and description needs to be truncated correctly in all 3 views.

**Comment by ilmartyrk** [comment]
@ssin1901 should be fixed now

**Comment by ssin1901** [comment]
Fixed and closing (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/0d7dec0a-2032-4817-bb3b-5dbc2f5c7990
