### ISSUE TITLE
IDEATION: UX insights for idea 'card' design/interaction 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1283]
@kevincrepin @ilmartyrk 

Not very strong insights as each are from 1 user only, but some things to consider: 

**Insights from Round 1 ideation admin UX tests**

- Users have mixed feelings on ‘empty’ or ‘easy on the eye’ idea cards: 
* One had quite strong feelings that just having the idea title would get very boring / samey / empty looking etc. He brought it up a few times. One suggestion was that there could be a header photo for the idea that displays on the front. (He was strongly in favour of the platform having more visual elements for participation, not so text based - more in this [issue here](https://github.com/citizenos/citizenos-fe/issues/1219)). A second suggestion was that the first few words of the idea explanation could be visible on the card. 
* However, another mentioned that it was nice and "easy for the eye" just having the titles. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/049e3f9b-637a-451b-a9fa-92e5d05cdafd)

- One user expected / wanted to see name of idea creator on the idea card. He saw that it was possible to see the name inside the expanded card, but wanted to see it on the front. Whether just via hovering over the avatar, or having it actually written, I'm not sure. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/715a17df-dbc3-4c05-bf93-68637bcca953)

**Insights from Round 1 ideation participant UX tests**

- User (90 y/o) fails to open idea card (and therefore doesn't see something that might have changed how she voted), she guessed it might be clickable but clicks the wrong area (which doesn't open), so decides it isn't and gives up. She tried clicking at the very top of the card around about here, which despite having a 'hand' cursor isn't an active part (so this is partly just a bug): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/42da32e6-6714-4b47-b757-a5cb1b0853a0)

(Haven't finished the participants analysis yet, but don't believe there's any more to come on this one. Will add it in the next couple of days if so). 

**Suggestions:**

- Consider whether to add an idea header image option, or the first few lines of explanation text, to the idea card? Might start to get a bit overwhelming though? 
- Fix the bug for the area that isn't clickable (but has a hand cursor), but should we also have a 'clue' for users, e.g. so that when you are hovered and it's in a clickable state, it turns darker, or something? 
- Consider whether to add a name, or a 'name on hover' to the idea card?

**Comment by kevincrepin** [comment]
The original hover state was with this drop shadow which separates it better from the others:
![Screenshot 2024-06-10 at 17 01 44](https://github.com/citizenos/citizenos-fe/assets/26792281/62303b9d-12be-438e-990e-9d2def9d3559)

I think the name on hover is a good idea:
![idea_person_hover](https://github.com/citizenos/citizenos-fe/assets/26792281/32d9ee33-c664-4769-93eb-edc0f9d9817f)

Any images or additional texts are going to make it very busy in my opinion. If there are longer idea titles then it will also not scale very well.

**Comment by BeccaMelhuish** [comment]
I see this is done and all looks good to me so will close :)
