### ISSUE TITLE
IDEATION: User(s) would like to be able to download ideas and replies for analysis

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1286]
@ilmartyrk @kevincrepin 

**Insights from Round 1 ideation admin UX tests**

For one of the use cases, it was important that she could download an excel of all the ideas and replies (and any related data such as what folder they were in) for analysis, as it was a university research project (on local sustainable transport in collaboration with the local government) and they would need to analyse it very systematically / thoroughly, prior to voting. She had also previously mentioned the same need for discussion responses, in a previous test of the same use case. 

Another admin mentioned prior to testing the platform that she would need to be able to download an excel of the contributions for analysis (I believe prior to voting, again, would need to check), though after using it she said she felt the folders would be enough to be able to do it within the platform itself. 

**Suggestion**

Consider adding an option for admins to download the contributions in an excel spreadsheet for both the ideation and discussion phases?

**Comment by BeccaMelhuish** [comment]
Not sure on this one if would be 'Ideation launch fixes' or something to be left 'til later, depends @ilmartyrk how much work it would be - presumably quite a bit?

**Comment by ilmartyrk** [comment]
This is a bigger update, also defining the structure of the document, what data fields in what order (arguments, replies, possibly images)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I've added the high priority label for this one, now that we decided it should be done before the launch comms :) 

I suggest [this](https://docs.google.com/spreadsheets/d/1Y3IhkQrtlLcLs84G4P6hSj9BmrgTtv3Wg7XocfOyDMo/edit?usp=sharing) (accessible via COS email) as an MVP version of the download sheet, which hopefully keeps things fairly simple?

![image](https://github.com/user-attachments/assets/3b2dbcd8-69f1-4814-85c3-cad575d3506f)

It is missing the following, as they seem more complicated:
- Idea replies (as we discussed, it's tricky to show to which ideas and to which replies they relate, so we can leave out for the MVP version).
- Photos (though an option would be to at least indicate if there was an image added or not? Not sure how important this is though, so can leave for now I think) 

As shown, when there is no folder, we just leave that cell blank? 

Tagging @MeelikaH so she can input too :)

**Comment by BeccaMelhuish** [comment]
Also @ilmartyrk if you are doing this for ideas, is it much more work to do it for discussions as well? As if not, we might as well do it for both? :) (There has been some indication in the research that it's needed for discussions too).

**Comment by BeccaMelhuish** [comment]
Re where to download it from, I'd suggest we add 'Export ideas' to this menu as the third item, and use the 'download' icon. And I'd suggest we have it always available, not only once the idea gathering is closed.  

![image](https://github.com/user-attachments/assets/bf4f7f8c-0073-4627-b11b-0f3d093cd1c7)

![image](https://github.com/user-attachments/assets/3ac0c6af-1e62-452a-ace5-e22ef865820e)

And perhaps a pop-up to check that they want to download? With text:

_**Export ideas**_

_Download a .csv spreadsheet file of the ideas collected?_ 

_Yes / No_

But this is more for @kevincrepin :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish what are the fields that should be in that excel of ideas?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk see example above [here](https://github.com/citizenos/citizenos-fe/issues/1286#issuecomment-2304412084) :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I waited a bit but don't see it - is it just a lag still, or something's up? 

![image](https://github.com/user-attachments/assets/19608047-6d60-473a-80a0-919cc6039080)

**Comment by BeccaMelhuish** [comment]
Checked with a new topic this morning too and there's nothing in the menu, so will re-open :)

**Comment by kevincrepin** [comment]
> Re where to download it from, I'd suggest we add 'Export ideas' to this menu as the third item, and use the 'download' icon. And I'd suggest we have it always available, not only once the idea gathering is closed.
> 
> ![image](https://private-user-images.githubusercontent.com/61320526/360409234-bf4f7f8c-0073-4627-b11b-0f3d093cd1c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjI2MzgsIm5iZiI6MTcyNDc2MjMzOCwicGF0aCI6Ii82MTMyMDUyNi8zNjA0MDkyMzQtYmY0ZjdmOGMtMDA3My00NjI3LWIxMWItMGYzZDA5M2NkMWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEyMzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyODAxMjM5YTUxYzQ1ODBmOWYyNmFkMDU3OGMxNGZiMWMyOTYwN2E3ODU5NjQ5ZWE3MDRjODAxOTM0MTY4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_Acv99YbLMhrSATfEUWETDUgvgCBO49T2Gwe5zimVE)
> 
> ![image](https://private-user-images.githubusercontent.com/61320526/360408693-3ac0c6af-1e62-452a-ace5-e22ef865820e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjI2MzgsIm5iZiI6MTcyNDc2MjMzOCwicGF0aCI6Ii82MTMyMDUyNi8zNjA0MDg2OTMtM2FjMGM2YWYtMWU2Mi00NTJhLWFjZTUtZTIyZWY4NjU4MjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEyMzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YWIyOGJmZmNkMTM3Y2Y2YWMwMTFmY2M5MTIxMDNlZGJlYWY1ZjJjNTY5ZTY5OTcxZmQyM2FkMDRhZGQ3MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3J8Lv3Hpqnl-MIzT-_fxNdCX2t-lWZp8IQh-DdfNgyM)
> 
> And perhaps a pop-up to check that they want to download? With text:
> 
> _**Export ideas**_
> 
> _Download a .csv spreadsheet file of the ideas collected?_
> 
> _Yes / No_
> 
> But this is more for @kevincrepin :)

Agree with everything, but I'm not sure if the confirmation dialog is necessary here? It's not such a big action that it requires this user's confirmation in my opinion.

**Comment by BeccaMelhuish** [comment]
OK fair enough yes! The download icon should make it clear enough indeed :)

**Comment by BeccaMelhuish** [comment]
Realised I should check the test site not live, and it is indeed there :)

@kevincrepin Ilmar already created the pop-up, do we remove it? 

![image](https://github.com/user-attachments/assets/c3ee3ae6-4090-472d-8022-e70528448fd4)

Otherwise, @ilmartyrk, all looks good except:

- Can the name of the downloaded file be "Ideas export" instead of this:

![image](https://github.com/user-attachments/assets/27463cab-23a8-4c27-b669-7308788426ec)

- Can the spreadsheet column headings be capitalised, and the ones for the ideas be changed to 'Idea heading' and 'Idea' like so: 

![image](https://github.com/user-attachments/assets/e61fa5b5-bb36-4120-95e8-315cd8956995)

- I had only added one of the ideas to a folder, but they all had the folder name in the folder column: 

![image](https://github.com/user-attachments/assets/eab4d982-392a-4617-8244-c3f14fca3956)

**Comment by kevincrepin** [comment]
Yes, let's remove the pop-up, it's not necessary.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk looks good except that the pop-up should be removed now, and also I'm wondering what format this time is - seems rather odd? 

![image](https://github.com/user-attachments/assets/9d663113-2eb1-480c-a91a-285ddb66d25e)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish here's what I tested

1. Popup - Ideas are downloaded without reminder (screen recording1)
2. Exporting CSV - Username,Date,Time, Idea heading, Idea, Likes, Folders are all present and correct (screenshot1)
3. Exporting CSV - Idea matches what is inputted as an Idea Description. Text is not truncated. 


https://github.com/user-attachments/assets/7061e44e-a419-4532-b6b4-d899e2fcc60f


<img width="817" alt="Screenshot 2024-09-06 at 11 06 31" src="https://github.com/user-attachments/assets/9cd673a1-1846-4dad-8123-743ddc935691">

Can I move this to Done?

**Comment by BeccaMelhuish** [comment]
Moved to Done 🎉
