### ISSUE TITLE
IDEATION / VOTING: User confusion with 'End ideation' / 'Close voting' icon

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1287]
@ilmartyrk @kevincrepin 

**Insights from Round 1 ideation admin UX tests**

One admin understood what this button was for, but expressed that he might feel scared to click it, as the X icon to him usually means 'Delete'. 

He said the same thing for the 'Close voting' icon in the same place in the voting tab. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0552c13a-3abe-4ed3-88fd-f6049fc943b7)

**Suggestion**

A user in a previous (pre-launch) round had the same fear re voting, so a small pattern now. 

Should we change the icon from an X to something else, or just keep an eye on it in future tests? The user here suggested that it would be better as a tick, or something to show it was complete.

**Comment by kevincrepin** [comment]
Delete is usually a trashbin though :)

Maybe the copy of "closing" was unclear then? Maybe should be "End ideation phase"? 

I'm not against a checkmark, it's a bit more positive than an x. 

How did the voting user encounter an (admin) phase-ending action? Do you remember?

**Comment by BeccaMelhuish** [comment]
For the voting, it was here that the user had doubts about clicking it, and explained she thought she would lose the whole vote. After that we added the text just below, though I can't off the top of my head remember how much that's been tested since. There weren't any issues in this round with that though. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fc9895d4-169f-4489-a724-b745ac16273f)

For the ideation, we already have 'End ideation' (and did have in the tests already), so I think we could either try the tick icon in Round 2, or leave it and keep an eye on it, up to you :)

**Comment by kevincrepin** [comment]
@ilmartyrk The "end phase" icon is updated, added the svg here for your comfort.

![Screenshot 2024-06-11 at 11 58 09](https://github.com/citizenos/citizenos-fe/assets/26792281/0c691885-19f9-48ee-8371-a8a41dac556e)
![end_phase](https://github.com/citizenos/citizenos-fe/assets/26792281/79cb7956-6e70-4218-ad9c-53d3ad8e3ce5)

**Comment by BeccaMelhuish** [comment]
Checked, good, sending to done :)
