### ISSUE TITLE
IDEATION / VOTING: User needs for multiple votes per idea/topic & voting on images

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1288]
@kevincrepin @ilmartyrk 

A few things here related to voting options both for ideation ('choose from ideas') and voting more generally (still choosing from ideas, but ones which came about through other means than the ideation feature - i.e. in collaboration with landscape design students). 

**Insights from Round 1 ideation admin UX tests**

- As mentioned in [this issue](https://github.com/citizenos/citizenos-fe/issues/1219), one admin was keen to be able to vote on images (plans for the space), not only on text. As it stands he'd have to put the images in the text or attachments and then number them, but I guess he either hadn't thought of this or didn't feel it would work well that way. 

- This admin also mentioned wanting to have multiple votes (and multiple ideations) per topic. E.g. some of the ideas may have been about which target group they would aim at (e.g. a space for teens, a space for the elderly), but some may have been ideas people have to develop the space (e.g. a skatepark, a rose garden, etc). So he would then want to have 2 different votes on these different branches of the decision. (Whether in parallel or not I'm not sure, I imagine it may be more like: ideate a bit - see there's a need for a vote on target group - ideate more on what to do for that group - vote on the ideas). 

- The other admin testing the same use case (decision on local community space) was also wanting the vote to be focused on images (again, plans for the space). But in the way she was looking to set it up, it would be multiple votes. So for each design, you would be able to vote, 'Yes, No, Neutral, Veto'. When she saw you couldn't have multiple votes per topic, she said she'd make a separate topic for each (3 - 5 designs). She was OK with this, but the way she was setting up her process was with different topics for each phase (all collected within a group), as she hadn't seen that she could add different phases to one topic. She felt this worked fine, but from seeing past round user tests this may get confusing for participants. 

- Another admin also seemed to want multiple votes to have multiple options for the different ideas, though this wasn't 100% clear. In the vote he set up though, he had multiple options for one of the ideas, but this was the idea to not have any criteria at all (when the ideation was on criteria), so he kind of adjusted the scenario to fit what was available to him in the test (which in real life wouldn't be so possible). So it seems in reality he would have needed/wanted multiple votes per idea. (This user is the one that didn't try the 'choose from ideas' option, as [didn't understand it](https://github.com/citizenos/citizenos-fe/issues/1258), so it's not clear if that setup would have been suitable had he gone down that route). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/00bc3c63-19c3-4a91-9468-08fdc9b3439c)

**Insights from Round 1 ideation participant UX tests**

- A participant in another use case (getting 100% consensus on membership criteria) suggested similarly, that it would suit their use case better if you could vote 'yes, no, neutral, veto' for each idea, rather than just selecting the ideas you like. This would help them get to consensus more easily, as they could see if there were very strong opinions against an idea, or just more moderate ones, to help see where the most further discussion was needed. He would want to be able to veto an idea that he really was against, to ensure it didn't go through. 

**Suggestions**

- Once we have the feature to add images to ideas, will the photos be visible at the voting stage? 
- For standard voting (not choosing from ideas), should we also enable images to be attached to a vote option. 
- The rest would seem to depend on whether technically we can add multiple votes to a topic (maybe only enabling it for soft voting for now, if eID voting is where the problems come in?), but if we can: allowing multiple choices as the voting options for each idea (for 'choose from ideas', or for each voting question (for standard voting).

**Comment by BeccaMelhuish** [comment]
I think this one would be a '**Bigger structural fixes**' issue

**Comment by ilmartyrk** [comment]
This is bigger structural fix

**Comment by BeccaMelhuish** [comment]
Made 2 separate issues out of this and will close this issue now. 

Didn't make an issue for the idea of having multiple options per idea (i.e. for each idea: yes, no, neutral, veto), but will keep an eye on the need for this in future research
