### ISSUE TITLE
Password reset error message is confusing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#129]
**What is the problem?**
1. When a user resets their password and clicks on the link from their email, they are taken to a page where they enter their new password. 

2. However, once they have entered their new password, they encounter this error without explanation (screenshot).

<img width="1337" alt="Screenshot 2023-05-24 at 13 28 40" src="https://github.com/citizenos/citizenos-fe/assets/72747107/656bb13f-c6c4-4cb8-be4c-37b55e80a8e0">

NB! Has been tagged as a bug since I am not sure this was the intended outcome.

**Why is this a problem?**
1. Completely unclear to a user why the new password was not accepted

**Possible solution.**
1. It should be clear to a user trying to change their password why the new password was rejected. 

2. If it is because the link is not valid then they should get a "Link is not valid error message" instead of the reset form opening up. 

3. If the password doesn't match this should be indicated. 

4. If the password doesn't meet the strong password criterion then this should be indicated as well.

**Comment by ilmartyrk** [comment]
Triage 85.  Password mismatch error should be caught before posting it to server and should display an inline error under input(s) also prevent sending data to server at that point.

**Comment by ilmartyrk** [comment]
@ssin1901 could not replicate
