### ISSUE TITLE
TOPICS: Relevance of categories, location & language for private topics? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1290]
@ilmartyrk @kevincrepin 

**Insights from Round 1 ideation admin UX tests**

One admin pointed this out in this round, and a couple have pointed it out in previous rounds too. Which is they don't see the relevance of this chunk in the Create flow, when it's a private topic, as they don't need people to be searching and finding them. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/eb7193e9-44b1-4326-8df6-2622537ec832)

**Suggestion**
 
They seem to be making a good point to me, and I'm thinking we could just remove this from the Create flow and info box for private topics?

**Comment by kevincrepin** [comment]
You can be involved in a lot of private topics, so you might still want to filter out to find it quickly. These are also not mandatory, so they can be skipped.

**Comment by BeccaMelhuish** [comment]
Will close this one and only open if some further insights come up :)
