### ISSUE TITLE
IDEATION: Unclear error message when ideation is closed

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1293]
When a user tries to click the lightbulb in an ideation that is closed, they get an error message "Insufficient permissions" which isn't really correct and wouldn't mean much to them anyway. 

Can the error message in this case (and any other cases where trying to do something in a closed ideation brings up this message) be: "This action is no longer possible, as the ideation has closed." 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/14ce1a51-becc-44a0-9aaa-af78bc0d37bd)

And generally I'm thinking we should avoid the "Insufficient permissions" error message, as it won't help users very much in most situations - will be better to tell them what the actual problem is in a way that's relevant to them. So @ilmartyrk if there are other cases of this error message being used I'd be happy to provide suitable copy to replace them :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is the default error from server for when we don't have any specific definition in place. But I  guess just disabling the button would work in this case

**Comment by BeccaMelhuish** [comment]
@ilmartyrk it is already disabled (though no visual difference, it just doesn't work) but I think it's good to have the message telling people why..

I guess we do have this though, so may be fine: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9dc45f57-2acf-4448-9284-32afc5e821ee)

How about if the buttons are greyed out a bit? Not sure how this would look though.. 

Maybe @kevincrepin can suggest the best UX for it :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this error was from server because the button was not disabled, it changes the on/off position based on if the vote went through or not. I posted a fix with actually disabling the button and graying it out as we do in other places

**Comment by BeccaMelhuish** [comment]
Ah nice, adding a screenshot in case Kevin wants to check, but this seems a good solution :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/aff1ffd8-332e-4f36-a317-f3b2761df737)

**Comment by kevincrepin** [comment]
Since the look of this might change...Based on other sieesu/conversations. We can still use the disabling tho: the 50% transparency.
![Screenshot 2024-06-07 at 15 12 19](https://github.com/citizenos/citizenos-fe/assets/26792281/ccb88a59-283f-4aa3-88c2-988cf8be4f2d)


In figma: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=13338-115399&t=xoQN4LtSq20tl0HZ-1

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish moving this to in progress as currently the fix has not been implemented.
