### ISSUE TITLE
TOPICS: 'In progress' filter should be 'In discussion' 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1296]
Should be 'In discussion' now? 

This one is in group topics filter, but maybe also is in other places: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2c6d1f75-b3eb-40d1-bc02-428c2bde925b)

**Comment by ssin1901** [comment]
@BeccaMelhuish checked My Topics (screenshot1) and Public Topics (screenshot2) and it seems to be added. Should we close the issue?
<img width="1375" alt="Screenshot 2024-06-07 at 16 06 55" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8aeb0ff8-ac18-4eb4-95fb-822bea04018f">
<img width="1371" alt="Screenshot 2024-06-07 at 16 07 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/db0056e8-c83e-42ef-88ac-036664ef3f23">

**Comment by BeccaMelhuish** [comment]
Checked group topics filter (where it came up) too and seems to be fixed, so yes closing now :)
