### ISSUE TITLE
TOPICS: User was a 'participant' but could see and click 'Start topic discussion'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1297]
In test app, in an ideation topic. Shouldn't be able to: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/51682d4b-c52f-4df8-9c42-d726d2be17d8)

**Comment by ssin1901** [comment]
@BeccaMelhuish this is the view a Participant sees now and they cannot start a Discussion. Can we close it? (screenshot1)
<img width="1204" alt="Screenshot 2024-06-07 at 16 09 33" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2a8818ff-20d7-4bac-a644-8d0f28e10931">

**Comment by BeccaMelhuish** [comment]
I guess so yes, but I seem to remember it was fixed before this test, and it happened. May be wrong though, will close and keep an eye on it :)
