### ISSUE TITLE
IDEATION/VOTING: Back button duplicates voting options

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1298]
**What is the problem?**
Tested in Google Chrome in incognito mode

When the user hits the back button (screenshot1), the options are re-added as duplicates (screenshot2, screenshot3)

<img width="1370" alt="Screenshot 2024-06-07 at 16 18 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/97c6f926-210d-47b2-8e33-86ea894cef72">

<img width="1191" alt="Screenshot 2024-06-07 at 16 20 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a759d6b1-0002-4bba-aa55-c05b6749f430">

<img width="1079" alt="Screenshot 2024-06-07 at 16 19 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/83066cb2-b179-4b64-8d85-60a200b9ee57">

**Why is this a problem?**
Confuses the user but does not break functionality i.e voting can still be started

**Possible solution.**
Back button should not cause the options to be re-added as duplicates

**Comment by ilmartyrk** [comment]
Its a duplicate and already fixed, closing
