### ISSUE TITLE
Public group mobile view is broken

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#130]
**What is the problem?**
Public group mobile view is broken and topic status is out of the screen. Topics view:
<img width="158" alt="mobile" src="https://github.com/citizenos/citizenos-fe/assets/45175679/7f8153e3-7cb9-48a0-802b-f740575d4276">

Members view: 
<img width="161" alt="mobil2" src="https://github.com/citizenos/citizenos-fe/assets/45175679/c92eb85a-f3e4-461e-bf28-d59e1169e81d">

**Why is this a problem?**
Broken UX

**Possible solution.**
Please fix

**Comment by ilmartyrk** [comment]
@anettlinno we I believe we don't need designs from Kevin for such small changes specially during redesign process. I've made some adjustments, hope it's better now
