### ISSUE TITLE
TOPICS: 'Read more' not always seen

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1300]
@kevincrepin @ilmartyrk 

**Insights from participant Round 1 ideation UX tests**

The participant test with my favourite 90 y/o showed that the 'Read more' can be easily missed by less tech savvy users. She didn't notice the read more until the very end of the process (in Follow-up, after having gone through ideation, discussion, and voting without clicking it). 

**Insights from other places:**
 
In a previous round of testing, an admin raised the concern that he felt some of his participants could easily miss the 'Read more'. Though this was just his guess about others, he himself did see it. 
 
Myself when setting up mock topics (and real ones) have also noticed that depending how the text falls, it can be very easy to miss that the text continues below. 

**Suggestions:**

Is there a way we can make the 'read more' more visible (an animation, so it jumps the first time you see it?), or give some kind of visual clue that it continues, with some sort of gradient for example?

**Comment by kevincrepin** [comment]
We can make this more prominent, sure. And also added the gradient, which is a good idea.

![Screenshot 2024-06-10 at 14 23 19](https://github.com/citizenos/citizenos-fe/assets/26792281/616ce2b1-be6d-4919-a087-36fe766a192a)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Grand! Could the blue of the button be a shade or two darker perhaps? 

And @ilmartyrk is there a way we can make the gaps between lines of texts when published a little smaller? I find that when I'm editing text the gaps between lines are small, but when published they are large, which then pushes the text off into 'Read more' more easily, and also means that this gradient would often be over a gap in text (and therefore not visible).

Here's an example from our Marketing meetings for example (part of this is the heading gap, but still - I think you see what I mean): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1b4386a9-7a10-4dae-a0f3-7650331e1d9e)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/300a36f4-3665-458d-9726-b79879510962)

**Comment by kevincrepin** [comment]
We don't have any other shade blue as a button anywhere, the darker blue is a hover state. Otherwise it's black and that felt too much (in my opinion).

**Comment by BeccaMelhuish** [comment]
Ah OK yes, let's try it like that then and see :)

**Comment by ilmartyrk** [comment]
> @kevincrepin Grand! Could the blue of the button be a shade or two darker perhaps?
> 
> And @ilmartyrk is there a way we can make the gaps between lines of texts when published a little smaller? I find that when I'm editing text the gaps between lines are small, but when published they are large, which then pushes the text off into 'Read more' more easily, and also means that this gradient would often be over a gap in text (and therefore not visible).
> 
> Here's an example from our Marketing meetings for example (part of this is the heading gap, but still - I think you see what I mean):
> 
> ![image](https://private-user-images.githubusercontent.com/61320526/338165982-1b4386a9-7a10-4dae-a0f3-7650331e1d9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjQ2ODAsIm5iZiI6MTcxODAyNDM4MCwicGF0aCI6Ii82MTMyMDUyNi8zMzgxNjU5ODItMWI0Mzg2YTktN2ExMC00ZGFlLWEwZjMtNzY1MDMzMWUxZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEyNTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZWUzNjI2YmI1NWY3ZTc2NmI1NmE4OTljMGNkYmM0MmFmNTE0Zjg0NGUyYzNkYTU4ZDM3OTlkMmFkZjgwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8rCb6KRoSYhurKVcKgN7HonFYFhgQtNgOkRxrJ0t0_k)
> 
> ![image](https://private-user-images.githubusercontent.com/61320526/338166265-300a36f4-3665-458d-9726-b79879510962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjQ2ODAsIm5iZiI6MTcxODAyNDM4MCwicGF0aCI6Ii82MTMyMDUyNi8zMzgxNjYyNjUtMzAwYTM2ZjQtMzY2NS00NThkLTk3MjYtYjc5ODc5NTEwOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEyNTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNWRkMzE4NDZiOWMwZjFlMGIxZTUwMTZhMzgyZGFlYTFiMDVmNGU5YWY1MWY4ZTUxZTJmOTNmMWI4ZmQxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nQwmCYxxHeAUIZwThs7QsMI38grmWMqkLFj6ZUdLDVo)

This is a separate issue and it is more related to Etherpad exporting html

**Comment by BeccaMelhuish** [comment]
OK yes have made a [new issue](https://github.com/citizenos/citizenos-fe/issues/1304) for it :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk thank you! The fix is just the button size though right, and gradient will come later? 

For me it's like this currently: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/be18fc87-0714-4f12-ad3d-107ef53d339f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the gradient

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah thank you though it's not working quite right for me - see below for layout issue. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b3e5d687-75a9-4b21-ad52-3b5ab2559577)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk btw I noticed that it looks good in preview mode, but once published goes dodgy as above :)

**Comment by ilmartyrk** [comment]
What do you mean by dodgy? Added it as in the design https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=10569-67960&m=dev though a little difference in the width I will fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah quite right! But I'm pretty confident this is an error, and it's somehow jumped a bit since @kevincrepin designed it, and is meant to be like this:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/216149ed-41ea-4d5d-bab1-a2efabd8fb1f)

Rather than like this:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bf176626-c614-402b-9295-f42864ddb209)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk so basically how it's looking in this preview one is perfect (in published it has text poking out the bottom), but with less of the white at the bottom (or rather moving the button down closer to the edge of the white)  :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/017f9132-e066-4d34-a6a6-c513eadae5c7)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk better on desktop, but not displaying quite right on mobile :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/19ccd130-f7ac-401b-ad0e-22241c7f99f0)

I'm pretty sure this text isn't meant to be coming out the bottom on desktop either, but hopefully @kevincrepin can adjust the Figma design to show how it was meant to be :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c3db1afe-5017-4f92-ba0f-8dd80332c05a)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk the view was alright in newer topics (see screen recording) in Android and IOS but in this topic, the topic view (https://test.app.citizenos.com/en/topics/b029aa8a-a282-4ed2-92bf-b448d1e17f02#voting) was completely broken (see screenshot) in mobile.

https://github.com/citizenos/citizenos-fe/assets/72747107/d330cc3a-4c9b-4d58-86df-5ced749113ea

![Simulator Screen Shot - iPhone 14 - 2024-06-27 at 13 09 04](https://github.com/citizenos/citizenos-fe/assets/72747107/76b56377-8b80-4407-add8-220935b7297d)

**Comment by kevincrepin** [comment]
I think something was wrong in my designs with the alignment, which hopefully now is fixed everywhere. But indeed the text should not be poking out under the button, the button should be aligned at the bottom (with margins around it) like here: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=248-42420&t=LnaR2FosVT61o7PB-1
