### ISSUE TITLE
NOTIFICATIONS: Users aren't turning on notifications 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1301]
@kevincrepin @ilmartyrk 

Maybe at some point @ssin1901 can give more data on how many users have set optional notifications (or at least visited a notification setting page), but for now: 

**Insights from admin and participant ideation UX tests and previous rounds**

- Users don't seem to expect that they need to, or think to, turn on additional notifications for topics. They just would close the tab, and wait to hear about the next stage or would come back and check it every now and then. They raise the question sometimes in tests, that they're wondering whether you get a notification about certain things, but don't seem to expect that they might have control over that. 

- It's been very rare that anyone has found the notifications settings (let alone thought to look for it) in the tests so far. And when they have it's seemed to me that they've been in 'Let's check what's possible and give Becca feedback' mode, rather than realistically what they would do in real usage.

**Suggestions** 

Of course, it may be that they don't think to turn on extra notifications as they don't want them and are happy just checking back, but it seems to me that the additional notifications are really key to keeping a topic alive and keeping people engaged throughout a process, so I think we should be prompting them much more to turn them on. 

It may be that through further usage the users would find the notifications in the 'Profile' menu where they were recently added, but so far in the tests (all 7) none have clicked that menu. 

Is there a way we can raise awareness about the notifications, the benefit of using them for staying engaged, and nudge them more towards turning them on? 

(And when we have a review of the notifications and AF, I think we could revisit what is a 'default' notification and what is optional, as something like a vote being started seems like it should be default - according to my thinking and also mentioned by an ideation admin tester. But that we can discuss separately :))

**Comment by kevincrepin** [comment]
One option could be that we do it similar to GitHub and add a card in the sidepanel:
![Screenshot 2024-06-10 at 15 40 55](https://github.com/citizenos/citizenos-fe/assets/26792281/a970e5b3-b835-43fb-a78d-5c4772c08394)

**Comment by BeccaMelhuish** [comment]
Yes this could be good! Though I would make the text more about encouraging them to opt into the more helpful notifications. E.g. "You're only receiving minimal notifications for this topic. Turn on additional ones, to not miss out on any developments!" 

Though I realise that's too much text, thoughts welcome on a less text heavy way to get that across! 

Maybe just: "Turn on additional notifications so you don't miss out on important activity."
Or:  "Turn on additional notifications to keep up to date with this topic's progress."
Or: "Turn on additional notifications to stay engaged and up to date."

Also, had the idea today that maybe admin's could "Suggest notification settings" for their participants. I.e. if they want to nudge participants to turn on notifications for ideas being added or the topic being sent to vote, then they could select those from the list, and have a notification sent to participants, saying e.g. "User X requests you to turn on notifications for X topic." Which the participant could then either accept or decline. (This would be a 'bigger fix' for later though I realise).

**Comment by BeccaMelhuish** [comment]
@kevincrepin what did you think to the possible alternative texts? 

We can leave the other part for now though ('bigger fix'), but let me know if you think it's an idea worth exploring and I'll make a new issue for it :)

**Comment by kevincrepin** [comment]
For me the "additional" is a bit confusing here, because I don't know what is the baseline. So by default what notifications are you receiving? 

Wouldn't it be easier to by default get all notifications, have one button to unsubscribe from this and one separate button to manage specifically if you want to? 

I think the bigger part should be part of a conversation how admins are managing topics right now. I think we once spoke about a specific admin dashboard and probably there's a better way for them to remind users than having to go through each topic separately. Maybe they have a simple "message" system that they can use to bulk send to participants. Then it's not specific to any one functionality.

**Comment by BeccaMelhuish** [comment]
Hmm yes I was also thinking that what users receive by default should be more than it currently is, but the trouble with turning them all on by default is the users would become absolutely flooded with notifications in an active topic, as it currently stands. So I think before we could turn them all on by default we'd have to have a bit of a review of what notifications we send to whom and how (i.e. maybe some of them aren't so relevant, and perhaps they can be not all in separate emails, but in batches of those actions within a similar time frame - so more like how Google docs does it).  

Re the other part, I can't remember if I've mentioned this previously (I've not yet made a specific issue for it) but it's been coming up a lot that admins are expecting and/or feeling the need for an 'admin view' and a 'participant view', so maybe this is connected? But obviously something for the 'bigger fixes' stage :)

**Comment by kevincrepin** [comment]
I think from this settings screen it's also a bit unclear actually what do I get updates about. Maybe we can redefine this and take into account what would be default on and what would then be optional?
![Screenshot 2024-06-18 at 11 44 17](https://github.com/citizenos/citizenos-fe/assets/26792281/19279a33-0de7-4795-a52b-f57409ea1510)


**Settings**
- [ ] Send me notifications via e-mail
- [ ] Send me notifications on the platform
- [ ] Send me weekly updates on the topics I'm involved with


**General topic updates**
- [ ] Update me when changes are made to the topic text
- [ ] Update me when changes are made to the topic settings (status, categories,...)
- [ ] Inform me when a phase deadline is approaching (month, week, day before)


**Ideation phase updates**
- [ ] Update me when anyone posts an idea
- [ ] Update me when someone replies to an idea I posted
- [ ] Update me when someone replies to any ideation I'm involved with


**Discussion phase updates**
- [ ] Update me when anyone posts an argument
- [ ] Update me when someone replies to an argument I posted
- [ ] Update me when someone replies to any conversation I'm involved with


**Voting phase updates**
- [ ] Update me about voting progress (weekly, daily)
- ...


**Follow-up phase updates**
- [ ] Update me when a new milestone is added
- [ ] Update me when a new milestone is reached
- ....





And maybe the additional card is just a CTA to manage the notifications then and there isn't "one button to turn on/off or subscribe to notifications":
![Screenshot 2024-06-18 at 12 03 03](https://github.com/citizenos/citizenos-fe/assets/26792281/b781433a-0a60-4938-8a66-37d75a6819ce)

**Comment by BeccaMelhuish** [comment]
@kevincrepin nice yes I think if this below is something quite quick for @ilmartyrk to add that would be ideal as a short-term (pre ideation launch) thing, and then we can review the notifications further down the line - agreed that it's not super clear at the moment! 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3e159cf4-e929-437c-a34d-782f27046083)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added this box

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @kevincrepin Great stuff, though I've realised a flaw in our plan.. Once you have opted in to additional notifications, it still says the same thing - that you're receiving the 'standard' ones. Hopefully at some point we can rethink (may the text can change depending on your settings) but for now, shall we just change it to this?

"Manage your notification settings to stay engaged and up to date with this topic's activity." 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8d2e10f4-9916-401c-b368-51d440cb0777)

**Comment by BeccaMelhuish** [comment]
@kevincrepin I've decided to change it to this for the testing "Turn on all notifications to stay engaged and up to date with this topic's activity", as this is kind of still correct (or at least less incorrect) even if they've already done it. 

But the tests haven't started quite yet (will do so today or tomorrow) so let me know if you disagree at all :)

**Comment by kevincrepin** [comment]
Nope, you're right, the previous version would have to be dynamic so this is a good general one that can stay even after user has made changes!

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Noticed in a mobile test (android, chrome) that the button is missing from here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/09684d24-e5b8-416d-9390-2fa4a068a239)

**Comment by BeccaMelhuish** [comment]
@ssin1901 Moved this to testing, but it may just be [this issue](https://github.com/citizenos/citizenos-fe/issues/1488) that I've created a separate one for :)

**Comment by ssin1901** [comment]
@BeccaMelhuish can we move this to Done? I see that you have created a separate issue for the missing button in Public Topics
