### ISSUE TITLE
FOLLOW-UP: User confusion around what 'Follow-up' means

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1302]
@kevincrepin @ilmartyrk 

**Round 1 ideation admin and participant UX test insights:**

This round of testing has shown very solidly that there's a _lot_ of confusion / misunderstanding about what 'Follow-up' means. 

They've had various ideas about what it might mean before getting to that phase, and even after reading the text about and seeing an update, they've often still been confused. 

**Some ideas they've had about what it could mean (from a mix of admins and participants):**

- Following up with people - i.e. nudging them to participate
- Following up on the discussion - i.e. a loop where voting happens and then the discussion is followed up on. Very nicely summarised by one as: "Opening the discussion again on the points of contention"
- Showing a kind of timeline of the whole process and actions that are happening throughout. "What time frame, in what order things are coming. What is done, what is ongoing, what is coming in future."
- Just confusion / uncertainty without much idea of what it could be

A couple of users did understand it. Though one had used and tested the platform before. And the other read the 'There is no follow-up text' well. 

**Suggestions:**

1. Should we test out other words instead of 'Follow-up'? A few ideas:
**- Action** (May be the simplest? Make a decision then take action?)
**- Updates** (Makes me think of software updates, and also not clear that the updates are post-decision, not (currently) during).  
**- Next Steps** (Though this may make users think it is telling them the next steps in the process, which they are often looking for after contributing - some sort of CTA for "What's next". But currently the follow-up is only about post-decision things). 
**- Implementation** (Quite suitable in its meaning but a bit long in English..) 

2.  Could we have an explanatory text here, that explains at least briefly to users what this is about (as once the follow-up has been created, there is no longer the 'There is no follow-up' text which might have helped them out): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/60bcff5b-82f9-48da-8dfa-acec780f2ff8)

**Comment by BeccaMelhuish** [comment]
@kevincrepin I'm thinking in terms of timescales maybe idea 2 above (adding a short explanatory text) could be a 'Pre ideation fix' and idea 1 (changing the name), and/or anything else that would make it clearer, could be a 'bigger fix' for later, what do you think? :)

**Comment by kevincrepin** [comment]
I like the "Action" label and thought also about "Action plan" which makes it very specific that now you go into an actionable "phase".

In the design there's a possibility to add an intro but I missed this in the current live. Wasn't a prio or did it fall to the side, @ilmartyrk ?

In any case, I think in this case I would rather use a tooltip, because we have that intro possibility. Otherwise again a bunch of texts, making keeping hierarchy quite a challenge.

![Screenshot 2024-06-14 at 11 02 44](https://github.com/citizenos/citizenos-fe/assets/26792281/e3147c64-6915-4235-a790-c18864af475d)

**Comment by BeccaMelhuish** [comment]
Hmm OK yes I'm thinking this mostly might have to be left for the 'bigger fixes' where we can think it through more, and also for when the rest of the follow-up features are added. As how it currently is in live, it's more 'Updates' so people posting what has happened, but then also has a deadline which makes it seems more like a plan. And myself I'm confused if we're expecting people to say what has been done, or show a plan of what will be done (or presumably both - what is planned, and then updates on that plan being actioned), so I guess we need more time to discuss more and figure that all out :) 

But we could test out changing the tab / phase name to 'Action' already for the round 2 tests:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/42e7c535-ef8b-4be1-a626-c700e7a9bcfa)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0f960da5-8d1d-477e-8e39-53d2073d8a88)

Then for the confusion about whether we're looking for updates or plans, we could call them 'posts' rather than 'milestones' in the above bit. 

And for this bit, we could call it 'Plans and updates'? With the tooltip saying this? 

_In the Action phase of a topic, admins can post plans and updates for participants to see what has and will happen as a result of the decision made. This allows everyone to follow its progress._  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bd66ec3b-94e2-43a6-a640-ed27e1cf8d0f)

Second thoughts, maybe 'Milestones' is OK (instead of 'posts' and instead of 'Plans and updates'), as it kind of covers both - a milestone that has been achieved (an update) or a milestone that is planned (a plan). But maybe a 'Plans and updates' heading is clearer/simpler language, if a bit more clumsy?

**Comment by kevincrepin** [comment]
I'm ok with renaming this. Hopefully it avoids the confusion. I do prefer milestones over posts because posts are a bit too generic for what we want people to actually do here.

If we call it "plans and updates" then doesn't this first sentence in the tooltip also not change? 
_In the Action phase of a topic, admins can post plans and updates for participants to see what has and will happen as a result of the decision made. This allows everyone to follow its progress._

Since here it's still called "action phase"...Which I'm also ok with calling this, has a nice ring to it: "action phase, go!" :D

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ah though I was thinking that the phase is still called 'Action', e.g. here etc: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7b62db86-ec62-4ba4-a3e3-4cca02095e2a)

But that in the bit we currently have as 'Updates', we change it to 'Plans and updates'

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1699ec61-94d8-4b12-aade-321466adb2c2)

I think 'Milestones' would also be OK, but 'Plans and updates' maybe makes it clearer what it's about if you don't see/read the tooltip?

**Comment by kevincrepin** [comment]
Aaaah, I misunderstood. Yes sure let's do it like that :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I think I've made all these changes myself via the translation strings, so the only thing for you should be the tooltip texts to go next to what's now 'Plans and updates':

_In the Action phase of a topic, admins can post plans and updates for participants to see what has and will happen as a result of the decision made. This allows everyone to follow its progress._

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4f38b41b-c982-4c32-83b8-83cac45d1766)

And @kevincrepin FYI this one I changed to 'Updates', seeing as we don't have milestones anywhere else now, but can always bring the word back once we've revisited how it'll work in the next iteration :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e89c0a14-3025-4266-8f6e-13e12c9b918f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix
