### ISSUE TITLE
GROUPS: Admins not understanding topic already added to group in 'Add topics to group' create flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1303]
@kevincrepin @ilmartyrk 

**Insights from Round 1 admin ideation and pre-launch tests**

In a couple of cases where it's come up in tests that (admin) users are making a new topic within their group, they get quite confused at this bit, not really understanding that the group has already been added as they are making the topic via the 'Add topics to group' menu, and don't get why they can't select their group from the drop-down. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/73b5aeee-816e-43de-b542-f9fd596bd7e6)

**Suggestions:**

Is there a way we can make it clearer, either in the UX of the dropdown, or some other way?

**Comment by kevincrepin** [comment]
What if we add this title, might be enough? 
![Screenshot 2024-06-10 at 10 28 08](https://github.com/citizenos/citizenos-fe/assets/26792281/997025c4-1aaf-40ba-8a26-0afb1d0d4800)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Hmm though actually they've not been added at that stage (and there might be groups they're already added to that don't show there), so it's more 'Groups this topic is being added to' but that feels a bit odd somehow?

Though "Groups you're adding this topic to:" would work? 

Also wondering if we can do something with this drop-down. When you click it currently and have no groups or no more groups it is just blank like this. So maybe we add "No groups to add" there in such cases?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/86a896a1-54d8-42f7-855f-8023c532519d)

**Comment by kevincrepin** [comment]
Ah yes, sure, that copy works.

And I thought that maybe we should disable the dropdown when there's nothing more to add, but we'd still need to explain it... Might make more sense to just replace the content with a sentence explaining:
![Screenshot 2024-06-10 at 13 31 05](https://github.com/citizenos/citizenos-fe/assets/26792281/a9ac6351-29fa-4ac8-a432-f0dc95ba8d8d)

**Comment by BeccaMelhuish** [comment]
Though @ilmartyrk would it be complex to have different text in the dropdown depending on whether there's no groups showing because you have none to add, or because they're all already added to the topic?

If easy enough to do then the text for the former could be: "You don't yet have admin rights for any groups."

But if time-consuming, then maybe just "No groups to add" covers it OK?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be quite easy to add the text if no more groups available, a little more difficult to have multiple texts, but will check what I can do

**Comment by BeccaMelhuish** [comment]
Summary to-do list for @ilmartyrk :) 

- [x] Add the heading 'Groups you're adding this topic to:' (slightly different text to what's shown below, but same placement)

![image](https://github.com/user-attachments/assets/474c2563-dfc2-4cb3-81e4-48eebb9e97c5)

- [x] Add the line 'All groups you have admin rights for have already been added' (again, slightly different to what's shown below) to the dropdown box when there are no groups to add (i.e. when the dropdown currently is empty). 
(Ignore the rest of the text, it's not up to date - no changes needed other than the dropdown text).

![image](https://github.com/user-attachments/assets/b5e26ef1-dbaf-4aaa-808b-c85ab2a3c31c)

**Comment by BeccaMelhuish** [comment]
Tested in test and looks good! Moving to Done :)
