### ISSUE TITLE
TOPICS: Big gaps between lines in topic text

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1304]
_Originally posted by @BeccaMelhuish in https://github.com/citizenos/citizenos-fe/issues/1300#issuecomment-2158103148_

And @ilmartyrk is there a way we can make the gaps between lines of texts when published a little smaller? I find that when I'm editing text the gaps between lines are small, but when published they are large, which then pushes the text off into 'Read more' more easily, and also means that this gradient would often be over a gap in text (and therefore not visible).

Here's an example from our Marketing meetings for example (part of this is the heading gap, but still - I think you see what I mean)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1b4386a9-7a10-4dae-a0f3-7650331e1d9e)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/300a36f4-3665-458d-9726-b79879510962)

**Comment by ilmartyrk** [comment]
closing as it is related to https://github.com/citizenos/citizenos-fe/issues/1181
