### ISSUE TITLE
Misc: 'Internal Server Error' in test app

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1312]
Just got this on arrival to the test app, and when going back to the DB again: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/64a67fa8-5dbf-4976-95ec-861000cf3add)

**Comment by BeccaMelhuish** [comment]
When making a new topic too:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c0670a25-0c98-497b-9a86-315767682eab)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk See comment here re it happening again: https://github.com/citizenos/citizenos-fe/issues/1289#issuecomment-2180140278 

Adding 'pre UX tests' label :)

**Comment by ilmartyrk** [comment]
Closing as it should now be fixed
