### ISSUE TITLE
TOPICS: HTTP error while accessing topics

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1316]
**What is the problem?**
In the Test Environment on Android Chrome and IOS Safari, the user receives an HTTP error while trying to access a topic from My Topics (see screenshot). Is not topic specific.

![Simulator Screen Shot - iPhone 14 Plus - 2024-06-20 at 11 39 34](https://github.com/citizenos/citizenos-fe/assets/72747107/6f474092-2796-426d-9c3e-7441b2573b8d)

However, this may be down to a slow connection as the topic is accessible after a few refreshes.

**Why is this a problem?**
Was quite difficult to access My Topics in a mobile device

**Possible solution.**
@ilmartyrk not sure actually.

**Comment by ilmartyrk** [comment]
@ssin1901 I remember that this was fixed
