### ISSUE TITLE
MOBILE: After adding an idea, user is stuck after closing the popup

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1317]
**What is the problem?**
In Android Chrome and IOS Safari, a user adds an idea and gets this view. (screenshot1) After clicking on the x, they come to the second view (screenshot2) where back buttons are not displayed

![Simulator Screen Shot - iPhone 14 Plus - 2024-06-20 at 11 54 15](https://github.com/citizenos/citizenos-fe/assets/72747107/edc3b215-464e-40d7-b69a-09d747a90b41)

![Simulator Screen Shot - iPhone 14 Plus - 2024-06-20 at 11 52 56](https://github.com/citizenos/citizenos-fe/assets/72747107/fcac22ae-d4f2-4d78-b0d8-8f36ad98875a)

**Why is this a problem?**
User needs to close or refresh the page. Basically, they are stuck at this point.

**Possible solution.**
User should be taken back to the main page

**Comment by ssin1901** [comment]
User is redirected to the topic view after clicking x. Closing the issue.

**Comment by ilmartyrk** [comment]
@ssin1901 there was an update in between, if you check the date and name items you can see the change
