### ISSUE TITLE
DISCUSSION: What to do with discussion question block for old topics

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1318]
@ilmartyrk @kevincrepin Not one for now just in case after testing we decide not to go ahead with the discussion question in this way, but if we do, we'll need to think about what to do with this chunk for older topics where the discussion question didn't exist separately. 

Currently it just repeats the title, but this is a bit odd to me. 

And another question to consider will be do we allow admins to add in (i.e. edit) a discussion question to an old topic, and add in a deadline. So should there be a 'Manage' button there.  

But just parking it here for discussion after Round 2 :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2127ca7e-c226-45be-999f-9503eeff0a1c)

**Comment by kevincrepin** [comment]
I agree just a copy is a bit weird. I think by default we should request the admin when they open these old topics to add a prompt and a deadline, both not mandatory of course: 

![Screenshot 2024-07-04 at 14 52 36](https://github.com/citizenos/citizenos-fe/assets/26792281/8ec10f08-8c69-4ee2-8dcd-d44c27999d25)

And if they don't fill anything in maybe it can be "[topic title]discussion" to not have it empty.

**Comment by BeccaMelhuish** [comment]
Sounds good! Though with 'question' rather than 'prompt' :)

**Comment by kevincrepin** [comment]
Yes, I can't keep up with the changes in how we're calling things so whenever you see something like this then that's probably the reason :D

**Comment by ilmartyrk** [comment]
est. dev time 1h

**Comment by BeccaMelhuish** [comment]
Agreed to have discussion question text to just say 'Discussion' when there is no question

**Comment by BeccaMelhuish** [comment]
Checked the discussion heading and seems to not be quite right yet (should just say "Discussion") 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/184595f4-103e-47f6-9334-c3bb34ed2e1e)

I wasn't able to test the pop-up as it requires going into a pre discussion questions topic in test for which I am admin, and I couldn't find one. But maybe @ssin1901 or @ilmartyrk you could send a screenshot of how it's looking and I can check?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is caused by database migration. The question was set as the title.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish anyway tried to remove the question for discussions where the question matched the topic title, but accidentally update all of the questions to be empty. Won't fix that at the time as it is testing data

**Comment by BeccaMelhuish** [comment]
@ilmartyrk sorry I didn't fully follow! When it goes live, will the discussion question space be empty for old topics or what will be there? :)

**Comment by BeccaMelhuish** [comment]
And re the pop-up, I came across one so reviewed it, and all fine except some copy edits which I made in the strings, but also these two lines of text missing (the same ones as in 'start topic discussion' pop-up). 

![image](https://github.com/user-attachments/assets/1d1a2427-4a35-4a8a-9017-d2e93a4b03d5)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it will just say "Discussion"
