### ISSUE TITLE
DISCUSSION: Discussion deadline / discussion closing inconsistencies

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1319]
@kevincrepin @ilmartyrk 

Currently we have a bit of an inconsistency in that we say this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/530bd66a-9812-4361-bd09-1472744cfa60)

But then in reality, nothing changes after the deadline, I tested and could still post: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2709783a-7683-40c7-9415-372c1d79755d)

We also have an option to 'Close discussion', which then makes the deadline the minute that you closed it. But again otherwise doesn't change anything - still possible to post.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a3d562e8-754b-4d16-8d6b-98ae1cfc1dee)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/01b5f9a6-3989-4f74-9a13-bb257bf18fc1)

**I suggest that we do two 'quick fixes' for the tests which are:**

- Just so that the text matches reality for the tests, I'll change the text by the discussion deadline to this for now: 

_You can opt to include a deadline, to let participants know by when they should submit their contributions. You can always edit the deadline at any time._

-  @ilmartyrk is it easy to just remove the possibility to 'Close discussion', so it's no longer in that menu? 

Then when we have more time (and hopefully some insights from the testing), we can think more deeply about what to do about this :)

**Comment by BeccaMelhuish** [comment]
I also found this misleading text, so will change it to: 

"The deadline indicates to participants by when they should contribute." 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e44ffb33-3afe-45e1-b6a7-81614a92ce02)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I will fix it on the API side so that if deadline is reached users cannot add any arguments.
I also thought about making it so in the future that if there is a deadline set discussion will end, but if there are no deadlines set for discussion or ideation it will stay open even if topic is in another phase

**Comment by BeccaMelhuish** [comment]
Ah OK cool, will switch the texts back then :) 

And that sounds good for the future possibility of having more than one phases at once! (Once all worked out by Kevin of course, when we come to it) :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
Great! 

Just needs a couple more clues that it's ended:

- Shall we grey out the reply buttons too? Currently you can type a reply, but only find out after you try to post that it is 'Forbidden!'

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ae86b045-879f-419b-8135-cd2426c8eb9b)

- Can we have the same box as we have for ideation and voting having ended? 

With text:

**The discussion has ended!** 
The discussion has been closed. You can no longer add arguments or replies, but you can still read and react to them. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3e884847-a8d9-4b72-a484-0b52e2ee34e6)

- I'm not sure what we do with this though, what do you think @kevincrepin? As the No. of contributions is still important.. This part's not urgent before the testing though I don't think. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e2603d18-e145-4491-a6c9-a01a0d8f9f00)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the info box and disabled the buttons

**Comment by BeccaMelhuish** [comment]
@ilmartyrk grand, thank you! Though the text seems to be the ideation one, could it be switched to this below? (Not sure I can be certain of which line to edit in the strings)

**The discussion has ended!**
The discussion has been closed. You can no longer add arguments or replies, but you can still read and react to them. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/125ef6a3-c279-4d03-ae8b-d0afcd9cc99c)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish seems fixed to me (see screenshot) but was it agreed that replies are also disabled, if the Discussion is closed?
<img width="1211" alt="Screenshot 2024-06-27 at 17 49 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5a941182-7e18-4410-abe2-053c8833f349">
