### ISSUE TITLE
IDEATION: Ideation topic turning into a discussion topic mid create flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1320]
@ilmartyrk I wasn't fully paying attention to what I was doing as I was trying to very quickly make an ideation topic that I would then add a discussion phase to, to check a fix, and at some point during the create flow (before publishing) the ideation topic seemed to turn itself into a discussion one, but then give me an error as below. 

I believe it was after trying to click publish this happened, but as above - was going very quickly and on 'auto-pilot'.. 

I definitely hadn't published and then gone in to 'edit' as this screen would suggest (saying edit topic at the top). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8643031f-80dd-4405-ad61-c1506e52927c)

**Comment by BeccaMelhuish** [comment]
Next I clicked 'Interrupt process' to try starting again, and got published view, all looking OK as it should:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d5b78534-895b-4389-8be2-ac5c84ffaea2)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Happened again for me in another topic, was making an ideation topic, published, sent an invite via the pop-up, next view was this (edit discussion topic): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7a81cc7a-b731-45e3-b952-bc122429614a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk this one happened in a test today, will try to add more details soon, but just a heads up for now that it's not fixed :)

**Comment by ilmartyrk** [comment]
Happened when choose the option from the tablet menu est. fix time15min.

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate on Chrome or Safari. Can we move to Done?
