### ISSUE TITLE
LOGIN: Users getting repeatedly prompted to log in once already logged in (so they don't realise they are in)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1323]
@ilmartyrk something that has happened a few times in the tests lately, is this: 

- Users follows an invite link
- Gets prompted to register or login
- They choose to login in via Google
- They log in, but then again get prompted to login with this pop-up:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/57cc019b-6192-4865-8eeb-139152bdb424)
- They try again, same loop  
- In the end, the close the login box and we discover that they are actually logged in after all. 
- They then accept the T&C's in the pop-up that was hiding behind the login pop-up 

Seems to happen quite consistently when they use Gmail login

**Comment by ilmartyrk** [comment]
1h for testing 1h fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 Some more detail on how this came about in tests as promised: 

- Participant who follows a share link to public **topic**, then registers an account by **entering email and creating a password** - **no bug.** 

- 3 x participants who follow a share link to **public** **topic**, the registers by **logging in with Google - gets the bug.** 

- 1 x participant who follow a share link to **private** **topic**, the registers by **logging in with Google - gets the bug.** 

- 2 x participants who follows a share link to public **group**, the registers by **logging in with Google - no bug.** 
Note that the flow for groups seems to be different, they get this pop-up as the first thing they see (rather than a request to log in), which is more how it should be for topics (connected to [this issue](https://github.com/citizenos/citizenos-fe/issues/1376)). 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/08091c54-8fc5-4e02-851d-6c1024e7dcca)

So seems the pattern is pretty clear (the issue is for links to topics, and for logging in with Gmail), and seems likely is connected to [this](https://github.com/citizenos/citizenos-fe/issues/1366) issue? 

(Though just to note, it may also be an issue for logging in with Facebook or e-ID, but only Gmail was tested in the user tests).

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk a bit confused. Will this be fixed with #1366?

**Comment by BeccaMelhuish** [comment]
@ssin1901 I'm confused too but looks like Ilmar fixed this back in July, and hopefully it is live already? Could you test and see if/where it's fixed? :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish I also think it's fixed. I will check in Test (as the fix is probably also applied there)
