### ISSUE TITLE
LOGIN: User didn't receive an account verification email

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1324]
In a test, user created account with email (a gmail address - I can send it separately if helpful) and password, but then didn't receive a verification email. She also checked her spam but it wasn't there. 

Also, when she then tried logging in anyway "as sometimes it works even when you haven't verified", she got this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0a21b378-7570-4a43-b1b5-d0c546fceb56)

I explained it was a bug and told her to try logging in using Google login button, and that worked. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dc03f22e-9d58-43c3-8035-6d7259edc0e5)

**Suggestions:**

Obviously this is partly just a bug, but @kevincrepin should we have some other UX flow for occasions when for some reason they don't get a verification email?  

I.e. should we allow the login anyway, and then get them to verify later (I think this sometimes happens with other accounts?), and should the message be something other than the 'Sorry we don't recognise' one? Not sure what is best practice for such situations?

**Comment by ssin1901** [comment]
@BeccaMelhuish I just tested the verification email and all worked fine. Is there a possibility for us to check with the user if she eventually received the email?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 closing the issue as it seems to work, lets create a new one if happens again and add more info if possible
