### ISSUE TITLE
BUG: User replies to idea, it says he is replying to himself

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1326]
In [this scenario](https://github.com/citizenos/citizenos-fe/issues/1325) (user replies without viewing the other replies), when he has added his reply, it appears as if he is replying to himself (but the idea was submitted by someone else):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f85d3e61-7893-417c-a2e0-9a1a1754e8f2)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
@ssin1901 tagging you in case it still needs testing :)
