### ISSUE TITLE
TOUR: Topic tour is missing 'Idea gathering' text on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1327]
On mobile, the topic tour is missing the ideation text (haven't checked the rest of the tour texts, maybe there are other idea related texts missing too):  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2a11e92b-df67-4374-8714-fbdc746acd83)

**Comment by ilmartyrk** [comment]
est. dev time 5 min
