### ISSUE TITLE
IDEATION: When user clicks 'Replies', idea opens with the replies collapsed

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1328]
Currently when a user clicks here, the idea opens with the replies collapsed. Two participants raised this as an issue in their tests. When they go in there, idea should open with replies thread already open: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/757f3f5a-90aa-4383-a41c-0aa90f884d80)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk how big a job is this to fix? I would say it's a priority for pre-launch unless is a huge task

**Comment by ilmartyrk** [comment]
est. dev time 1-3h

**Comment by BeccaMelhuish** [comment]
Tried it out and seems good to me! With leave in testing in case @ssin1901 needs to test more though :)

**Comment by ssin1901** [comment]
@BeccaMelhuish seems fixed. I'm moving it to Done.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 Am reopening this one, as it seems to have become unfixed (clicking 'X replies' no longer opens the replies, tried it in an old topic and a new one).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed it again

**Comment by ssin1901** [comment]
@BeccaMelhuish UX not smooth, but replies don't seem collapsed (see screen recording). Can we move to Done?

https://github.com/user-attachments/assets/9dea2134-d22e-4791-b518-71b590841ec5
