### ISSUE TITLE
IDEATION: Incorrect number of Replies

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1335]
**What is the problem?**
In Google Chrome Mac OS (Desktop) the Replies counter indicates that there are no replies, but there are 2 replies (see screen recording). 

https://github.com/citizenos/citizenos-fe/assets/72747107/78d77053-31c6-4045-88c7-e6dedbf7a3b6

Reply counter works as expected in Android Chrome.

**Why is this a problem?**
User would think there are 0 replies

**Possible solution.**
Reply counter needs to be reflect the correct number in Chrome, regardless of device size

**Comment by ilmartyrk** [comment]
@ssin1901 i suspect it is a network connection speed thing, but I also posted a fix that should work in this case

**Comment by ssin1901** [comment]
@ilmartyrk works now and closing (see screen recording)
<img width="1408" alt="Screenshot 2024-06-27 at 19 03 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/62627ad0-70df-4eca-91fd-7e023bbbf0c0">
