### ISSUE TITLE
GROUPS: One group showing narrower than the others on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1336]
@ilmartyrk See below, on iPhone Safari:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/35d70102-1368-4954-82c5-916c0bcc3671)

**Comment by ssin1901** [comment]
@BeccaMelhuish checked in Mobile safari view in the test environment and the topic narrowing didn't seem to occur. Can we put it in Done? 

Screen recording below 

https://1drv.ms/v/c/7694ec49e01017c5/ETXzVnl9GxtEjNIwYk4rIdwBuJPwlpa5nqcjPSSDmYs2tA?e=VaLJd0

**Comment by BeccaMelhuish** [comment]
As long as it's live then yes can go to Done :)
