### ISSUE TITLE
IDEATION: Bugs in participant filter

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1338]
@ilmartyrk in a test, on iPhone, Safari, participants filter said 'Object object' and didn't reset to show all participants when they clicked reset. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f93e4a95-9381-4ec1-b565-ae1ef2918aaa)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by ssin1901** [comment]
@BeccaMelhuish seems fixed? (screenshot1, screenshot2). Can I move to Done?

<img width="532" alt="Screenshot 2024-08-26 at 11 20 24" src="https://github.com/user-attachments/assets/e622f2d6-43b6-4485-beea-316d14df498b">

<img width="423" alt="Screenshot 2024-08-26 at 11 18 53" src="https://github.com/user-attachments/assets/f4da1ebe-0575-454e-b5b9-eccf5722f39a">

**Comment by BeccaMelhuish** [comment]
Sorry @ssin1901 my original issue was unclear, it was actually here: 

![image](https://github.com/user-attachments/assets/a3d97059-29e8-4e33-b13d-148ff9d01b4e)

**Comment by ssin1901** [comment]
@BeccaMelhuish it was my bad, seems fixed here (screenshot1)

<img width="448" alt="Screenshot 2024-08-26 at 11 39 57" src="https://github.com/user-attachments/assets/d7144cb3-d1d5-4fb8-a538-91a00d50db5c">

**Comment by BeccaMelhuish** [comment]
@ssin1901 looks good! Though did this reset button work, after having selected filters, to go back to all? 

![image](https://github.com/user-attachments/assets/18d890c3-add9-453b-99e9-f37ff5b3a25a)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think the filter works now (see screen recording)

https://github.com/user-attachments/assets/b17e6e4e-6951-412e-aee1-2d9db3944de1

Can I move it to Done?

**Comment by BeccaMelhuish** [comment]
Looks good to me, moved to done :)
