### ISSUE TITLE
TOPICS:  Download button caused topic flow to exit and draft not saved

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1339]
When user clicked this button when creating his topic, he got taken suddenly to the DB and lost the topic he was making (it hadn't saved as a draft): 

iPhone, Safari

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d8e788e0-efe9-48ba-b89a-916eafb6969b)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think this is working as intended (see screen recording). Download doesn't take user away from topic and the contents of the download are correct.

https://github.com/citizenos/citizenos-fe/assets/72747107/7ff2e973-fb3c-40b8-850c-4e69586f4b0b
