### ISSUE TITLE
IDEATION:404 error for logged out user clicking on ratings number

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1340]
**What is the problem?**
_Tested in Google Chrome, incognito mode_

When a logged out user views a Public topic (Ideation topic) and click on the number next to ratings they get a 404 error (screenshot1, screenshot2)

<img width="1403" alt="Screenshot 2024-06-27 at 18 43 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3f2269b5-ab45-44e6-bc1c-c6ce7e99842e">

<img width="1407" alt="Screenshot 2024-06-27 at 18 43 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8d1541cf-4119-4806-a7e9-35ccddde6aac">

**Why is this a problem?**
Needs to be fixed before release, @BeccaMelhuish maybe not that important for the user tests 

**Possible solution.**
@ilmartyrk @BeccaMelhuish I guess for consistency, the names and profile picture of the people who rated the idea should appear in a Public Ideation Topic.

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk seems to be working, so closing this issue (screenshot1). I'll open a separate issue for the styling.
![Simulator Screen Shot - iPhone 14 Pro Max - 2024-06-27 at 19 25 29](https://github.com/citizenos/citizenos-fe/assets/72747107/10ca5fd7-4390-4344-a9b9-b3bd457a7fc5)
