### ISSUE TITLE
IS: Bulk actions bug on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1343]
In test, bulk actions looked like this when clicked (not functional), on iPhone, Safari, in 'invite co-creators' stage of topic create flow: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0370a8d5-2c13-48b8-905a-48c1cabf03f3)

**Comment by ssin1901** [comment]
@BeccaMelhuish seems fixed? (screenshot1)

<img width="482" alt="Screenshot 2024-08-26 at 11 21 33" src="https://github.com/user-attachments/assets/0b2bdbf5-991c-401c-84ed-a9bb4d861410">
