### ISSUE TITLE
TOPICS: text colour not showing when published

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1346]
In test (iPhone, Safari), user changed the colour of the text to blue (using the text colour dropdown), but when published it was black. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f4df9b86-d3dd-4dfa-a539-b0309288e689)

**Comment by ilmartyrk** [comment]
closing as it is related and will get fixed by https://github.com/citizenos/citizenos-fe/issues/1181
