### ISSUE TITLE
IDEATION: Minor design bug - idea likes in folder creation should be lined up 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1351]
Please see screenshot here, should all be aligned to the middle of 'Likes' heading:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d2519176-ef20-412b-824f-f378872fd753)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think this is fixed? (screenshot1, screenshot2)

![Simulator Screen Shot - iPhone 14 Plus - 2024-09-25 at 15 42 49](https://github.com/user-attachments/assets/54a0bc4b-bd57-4c33-9c90-99bdfa1b2b38)

<img width="1440" alt="Screenshot 2024-09-25 at 15 43 48" src="https://github.com/user-attachments/assets/a06a179f-e7fb-4ce3-b6ff-1ec5b25a7fbf">

**Comment by BeccaMelhuish** [comment]
Seems good to me yes, will move to Done :)
