### ISSUE TITLE
TOPICS: 'Invalid status flow' error when editing ideation topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1352]
In test (Android, Chrome), user got this error when trying to edit the topic text. She had created an ideation topic, got the 'authentication required' bug so couldn't add her topic text during creation, went back to try and add it later using 'edit' function, but got this upon trying to save: 
(Tried twice, same thing). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0f5a4da7-5f4a-4932-83e4-ec112db67d89)

**Comment by ilmartyrk** [comment]
1h research and fix

**Comment by BeccaMelhuish** [comment]
Hey @ilmartyrk! I checked the recording as promised, and the bug occurs in the flow like this: 

- First she creates the topic, and gets the topic text 'authentication required' bug
- She publishes the topic  
- She then goes straight in after the topic is published to try to edit the topic text
- This is the view below when she arrives in edit mode if that helps (though they all have the same 'Edit topic' text now, regardless of 'topic type'. She then adds the text, and tries to publish but gets the bug that's the focus of this issue ('Invalid status flow').
- And then repeats the process of trying to edit and save, but gets the same error.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/76ccb6fb-2946-4b66-8432-465dbfced7a9)

Unfortunately I don't have access to this particular topic though, as she didn't get to the part where she invites me to it (she accidentally closed ideation and had to start again with a new topic).

**Comment by ssin1901** [comment]
@BeccaMelhuish to confirm, the user had created an ideation topic and got the error when they tried to edit the topic text?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Yes - she makes a topic starting with ideation, publishes, goes back in to try to edit topic text, tries to publish, can't - gets the error.
