### ISSUE TITLE
IDEATION: Possible bug in favouriting ideas

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1355]
In a test (Android, Chrome), this is what it looks like happened from the recording. The user didn't mention anything being wrong, but from what I see in the video it seems buggy:

User seems to click favourite on an idea (it flashes blue on the star):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/57292576-04bd-434b-a63a-950174823da2)

Doing so seems to open an idea, but the idea isn't the one she seems to have favourited, and isn't favourited: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/86586583-f218-40c4-8a51-6601f53a8460)

She closes it and goes back to the ideas, the idea she seemed to have favourited initially isn't favourited: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1efc7284-348f-4803-b2a4-8e6efaa5ac70)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish if the user clicked on the icon it would have triggered the favoriting and not opened the idea, and if the user favorited the idea and then opened the idea the start would already be marked, so not sure if it is actually a bug. I've tested it and it works on android chrome as intended
