### ISSUE TITLE
DISCUSSION: discussion Q messy alignment

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1357]
@ilmartyrk @kevincrepin on mobile, Android, Chrome

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8076517d-c93d-4e16-b7c6-29145ef5b676)

**Comment by kevincrepin** [comment]
I think this is correct though. Seems there's not enough width to make more words fit on the lines?

**Comment by BeccaMelhuish** [comment]
Ah OK, to me it looked like more would fit, but maybe not :)

**Comment by kevincrepin** [comment]
I wonder @ilmartyrk if this text size is correct though? When I add the same sentence in Figma it fits better. Or maybe the space between text and "more" button is too big? In design it's only 8px.

![Screenshot 2024-07-04 at 13 11 56](https://github.com/citizenos/citizenos-fe/assets/26792281/e672d7f6-9fe3-42bb-a6e4-e3c9481dbb62)
