### ISSUE TITLE
TOPICS: Header image looks like it's lost when returning to '1. Compose'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1360]
When coming back to edit a draft topic, users (2 in the same test) thought their header image hadn't saved. Actually it had, it just doesn't show. But when they clicked on it, it appeared.   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ea509152-48af-4c33-82bc-7efbe5132a9e)

@ilmartyrk I assume this is just a bug and doesn't need Kevin's input - can it be made to always show?

**Comment by ssin1901** [comment]
@BeccaMelhuish checked in Test and the fix seems to have been implemented. I created a topic with the header and saved it as a draft topic (screenshot 1). When I went to edit it, the header image appeared automatically/ **without a click**

Can we put it in Done? 

<img width="1171" alt="Image" src="https://github.com/user-attachments/assets/916910df-b8f8-43c8-ac03-37e9d05fd119" />

<img width="1192" alt="Image" src="https://github.com/user-attachments/assets/c66e2bab-e03a-4540-a692-aba1f0e47eae" />

**Comment by BeccaMelhuish** [comment]
@ssin1901 Assuming it is live already, then yes can go to Done :)
