### ISSUE TITLE
IDEATION: Minor layout issue with idea reactions icons

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1362]
On mobile (Android, Chrome):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3e9c4d4b-d369-4f11-af84-0ee5bd3077b4)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue, was actually same for the argument reactions

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish this issue is fixed in Android so moving to Pre-Live but in #1811 there is an issue with iOS. I think it is a separate issue though.

**Comment by BeccaMelhuish** [comment]
@ssin1901 yeah let's keep that one separate 
@ilmartyrk I guess this may be fixed in live already? If so please just put to Done :)
