### ISSUE TITLE
VOTING: Voting results showed in 'Topic' tab as well as 'Voting' on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1363]
In a test, on mobile (Android, Chrome), when user followed link to topic to see the voting results, they showed in the first tab ('Topic') as well as in the 'Voting' tab. (Also see overflowing intro text, in topic tab). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/72f9a7ef-f789-4de8-b5e8-ecc854b32acc)

**Comment by BeccaMelhuish** [comment]
I noticed in the test recording that the same thing happened (in the same topic, same test) when the topic moved to follow-up as well:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c4e75146-798d-42e7-8603-c256aa68b0cf)

**Comment by ilmartyrk** [comment]
est. 1h research + fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk here is the [topic link](https://test.app.citizenos.com/en/topics/9d2066f6-7fde-4bcf-9b50-dd1a3357fe92) as promised :) 
(You are already admin, so hopefully that works, let me know if not)

**Comment by ssin1901** [comment]
@BeccaMelhuish is the intended UX that the topic intro and description along with the Read More button should only appear in this section on mobile devices (screenshot 1)? If that's the case, then I think the issue has been fixed (screenshot2, screenshot3).

<img width="469" alt="Image" src="https://github.com/user-attachments/assets/fe4f6d1d-e8ba-43e2-b570-4d56a3efde0b" />
<img width="431" alt="Image" src="https://github.com/user-attachments/assets/03dfb284-3cee-4b66-b8ad-6adcb6ff52ab" />
<img width="484" alt="Image" src="https://github.com/user-attachments/assets/8af24011-9cb8-47a8-8823-9b61e8a387e7" />

**Comment by BeccaMelhuish** [comment]
Seems good to me :) I assume this is live already?

**Comment by ssin1901** [comment]
@BeccaMelhuish yes with the last deployment certainly. Can we move it to Done?

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk it may not have been pushed to Live. I'll put it in QA Pre-Live for Ilmar to check.
