### ISSUE TITLE
MISC: Discussion block stats showing when there is no discussion

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1364]
In a test, admin user starts with ideation, then starts a vote (skipping discussion part). 

After starting the vote, the discussion block here changes to this, with all the stats as 0, but shouldn't, as the discussion isn't started: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/584ea5fd-8943-458c-9fe4-f004531700c6)

@kevincrepin I guess it needs some thought as to what this block should say / look like in this scenario, and also the text and buttons in the discussion tab. 

Though @ilmartyrk I'm not sure - is it technically possible to add a discussion after you have added a vote? If so then I guess it can all stay as it was previously ' e.g. "Add a discussion". "There is no discussion yet" etc. Unless, @kevincrepin, we feel it shouldn't be possible to add a discussion after a vote, in which case it should change.

**Comment by kevincrepin** [comment]
In the current version I think there's no possibility to add discussion after voting. In a next iteration – after we work out the dynamic phases – this could be possible though.

So if they go from Ideation to Voting then this discussion block should not be visible there.

**Comment by BeccaMelhuish** [comment]
@kevincrepin Does this mean that we remove or grey out this tab too then, or what should be done with that and the content on it? ("There is no discussion yet" heading and explanatory text) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/013dea83-59cc-4676-a8d6-96de55ab4a7d)

If so, might need some explanation in the 'Start topic voting' pop-up, explaining that doing so will remove the 'Discussion' tab? (Just so it's not a surprise/cause of confusion).

**Comment by kevincrepin** [comment]
I think it should be removed yeah, otherwise might be even more confusing why it's still there but disabled.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk how big a job is it to make this happen - that discussion tab disappears if admin starts vote straight after follow-up? 

Also, @kevincrepin to follow the same login, should any unused tabs/blocks also disappear if admin starts follow-up after ideation or discussion?   

I will propose some copy edits for the 'start X phase' tabs once confirmed, so admin is aware this will happen :)

**Comment by kevincrepin** [comment]
I think so, yes. Initially I had a state saying smt along the lines of "there was never this phase" but that also doesn't add much value and maybe having it in the tabs adds more confusion if it was never a part of the topic. 

So I would say, yes, if an admin "skips" a phase then this phase can be fully removed. In the future if we have multiple phases then this already aligns better as well.
