### ISSUE TITLE
IDEATION: Search function not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1365]
In a test on mobile, the search function in the idea gathering phase, just under the filters, wasn't working. Let me know if more info needed.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish removed it from mobile as we don't have that functionality yet on the API side and UX design for desktop

**Comment by ssin1901** [comment]
@ilmartyrk I think the search functionality is not on Desktop either?

**Comment by BeccaMelhuish** [comment]
Made an issue to add it in when we can :)
