### ISSUE TITLE
IDEATION/VOTING: Bug in adding ideas to choose from for voting

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1367]
During a test with [this topic](https://test.app.citizenos.com/topics/join/gljY9sbyoyQf), I encountered the following bug:

The idea gathering process took place. While it was still open I added 3 more ideas, just before starting a discussion, and therefore ending the ideation. 

When I later went to choose the ideas from which participants would be able to choose for voting, the 3 ideas I had added just before starting the discussion were not there. So I was not able to select them and include them in the vote.

**Comment by ssin1901** [comment]
@BeccaMelhuish I added a new idea, then added a discussion and then clicked on Add Voting. The new idea appeared. 

Test was in Google Chrome, Desktop. Did you use a different browser or device?

**Comment by BeccaMelhuish** [comment]
@ssin1901 I was using desktop and Chrome, too, though on Windows

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate. Can we move to Done?
