### ISSUE TITLE
IDEATION: User need for more detail/link back to ideas during idea voting & possibility for admins to edit or add ideas(?)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1369]
@kevincrepin @ilmartyrk 

One thing that occurred to me while going through several processes in the tests, and was to some extent backed up in the Round 2 participant tests - it seems like there's a need for a clear link back to the ideas that are being voted on, for the participants when making their choices. 

**Insights from 'participant' role testers in Round 2:**

- One user was very clear that when voting on the ideas, she'd need to have more detail than just the headings of the ideas, to be sure she was definitely voting on something she supported. She tried clicking on the vote option texts (the idea headings) to see if it would open more text. We discussed it, and she said that when that didn't work, she would next try going back to the idea gathering/discussion phase and checking to see if the vote option corresponded to something there. As she would want to see where the conversation went, and where it ended, before voting. She also said she would need to be 100% sure that what she was voting on was the same as the conversation she had found. 
- For another user it was less of a solid insight, but at some point during the voting she said about one of the voting options (which was a title of one of the ideas), "That's too vague", and therefore unticked it. Which I think can be safely assumed meant that the heading itself didn't give enough information to know what she would be voting on. 

**Reflections from myself while running the tests:**

These aren't actual user insights, but some thoughts from me while running various different tests with different scenarios:
- Participants are sometimes going to give their ideas headings that are quite ambiguous, as the full meaning of their idea is within the idea description. E.g. "Change the opening hours" might be about making them longer or shorter. "Vegetation" might be able clearing the existing vegetation or adding more. "New diet in the cafeteria" could refer to any sort of diet type. 
- When participants are creating the headings for their ideas, they're not thinking about (or even aware at that point) the fact that it will then become the text for the voting option. 
- Participants might type their headings with typos or bad grammar etc, and the admins may wish to correct this for the final official vote.
- Additional ideas might come up in the idea replies, that an admin may want to add to the vote. E.g. 'Make the library open 'til midnight' might be the idea. But then a reply "Even better, let's keep it open all night!" might have got a lot of likes, but not have been created as a separate idea, which the admin could then choose to include in the voting. 
- In the discussion phase, it might be that additional ideas come up, or it gets agreed that an idea in the idea gathering would actually be done slightly differently. 

**Suggestions**  

If there is some sort of quick fix we can do for ideation launch (hopefully @ilmartyrk can advise) then I'd suggest:
- We either make it so that you can click on the voting option text and it expands to show the original idea description, with some way to check the replies too (a link back to the original idea I guess). OR We have the voting options link back to the original idea, so you can go back and check it if you want?  
- We make it so that Admins can add additional voting options, as well as the ideas they have selected from the idea gathering phase? 

We might also want to consider at some point: 
- Should admins be able to edit the idea headings for voting?

**Comment by kevincrepin** [comment]
I think the easiest – hopefully – fix is to add a text link to the voting option that opens up the idea as it opens up in the ideation phase.

Link in voting idea (@ilmartyrk which means that not the entire thing can be clickable anymore, I think, or at least there's the exception of this text link area). Not a big fan of this repeating "view idea" label, so open to suggestions for that.
![Screenshot 2024-07-05 at 11 53 37](https://github.com/citizenos/citizenos-fe/assets/26792281/82fcb457-daf1-4a60-9a91-184382a72a6c)

And opening up like in the latest version:
![Screenshot 2024-07-05 at 11 57 23](https://github.com/citizenos/citizenos-fe/assets/26792281/ee2cca62-30c8-4999-8a37-81dc79e39dab)

I think in the future when the admin adds the voting phase that they then should be able to edit the idea headline and also view the original one during their voting phase creation. However in the current logic – the creation being done in a dialog window – makes it very messy and confined. I would suggest to implement that change when we implement the "each phase gets its own text" changes.

**Comment by BeccaMelhuish** [comment]
@kevincrepin super thank you! 

Wondering if they could be slightly separated though, so that the whole vote option button could still be clickable? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/08d6f5b5-e6f2-45b1-b380-c6f57d06f7fc)

And OK yes, sounds good if editing headlines comes later with bigger fixes :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk, Added high priority as would be good to have sorted for ideation launch, unless it's too big a task

**Comment by kevincrepin** [comment]
Yes, I had a similar idea! But then somehow didn't follow-up on it... :) 
![Screenshot 2024-07-08 at 10 41 34](https://github.com/citizenos/citizenos-fe/assets/26792281/ef4dab9f-d42c-4e26-8783-a1e9cf3bebf0)

https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=13729-119469&t=OOv6hBVMuaI6bQBX-1

**Comment by ilmartyrk** [comment]
est. dev time 4h

**Comment by BeccaMelhuish** [comment]
Checked it and looks and works great! 

Only thing would be I think we need to show it in the preview too: 
(Less urgent for launch though) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8d1bd0bf-dca5-4120-8382-27f5a93b1101)
