### ISSUE TITLE
No logic to results displayed in search bar

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#137]
**What is the problem?**
1. When the user types "test" into the search bar only the first two results are relevant. The next few results have no relation to "test" (screenshots 1 and 2).
<img width="1163" alt="Screenshot 2023-05-28 at 16 03 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e6fa47b2-4d1c-40f8-aee9-c7414dffb2a7">

<img width="1165" alt="Screenshot 2023-05-28 at 16 08 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/00836ae3-4ede-4e06-b999-25c1fff2b522">

Further, from screenshot 2 we can also see that a) the word test does not appear in the topic only in the search bar b) the user who searched the topic is neither editor or admin of the topic. So why does this particular topic show up?

**Why is this a problem?**
Highly inconvenient for the user as they cannot use the search bar to find anything

**Possible solution.**
The search bar should display ALL topics and groups, with most relevant results such as topics or group with the title "test" appearing first.

**Comment by ilmartyrk** [comment]
Fixed the issue
