### ISSUE TITLE
IDEATION: Users missing that starting discussion phase will close ideation

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1371]
@kevincrepin @ilmartyrk 

Somewhat linked to [this issue](https://github.com/citizenos/citizenos-fe/issues/1370) and also [this issue](https://github.com/citizenos/citizenos-fe/issues/860). 

**Insights from Round 2 ideation testing:** 

Two out of 3 of the admins in the Round 2 tests didn't realise that starting a discussion would close the ideation: 

- One admin went all the way through to start the discussion, and then was confused why her ideation had closed. She thought maybe she'd made an error in setting the deadline for the ideation, or that it was a bug. We then had to make a new topic to be able to run the ideation part. 
- Another admin got part-way through starting the discussion, but then was stopped by her colleague (a more experienced Citizen OS user). When asked, she hadn't realised starting a discussion would close the ideation. 

In both tests, the users were Indonesian, but using the platform in English. This could play a part in why they didn't notice the text saying that 'participants can no longer add ideas'. However, not all users use the platform in their own language, so I think we can't discount it for this reason. 

**Suggestions**

In the short term, shall we make these 2 lines bold, and the equivalent for other 'start phase' windows? 

Or, even have a tab before this one saying something like "Idea gathering will be closed. Are you sure you want to continue?" before they even get to this bit: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/02e87e2a-6bc2-4371-b498-4f3872cb4be1)

In the longer term, can we have a way for admins to re-open a phase if they have closed it in error?

**Comment by kevincrepin** [comment]
We can make them bold and/or even make them red so they really stand out. Maybe there should also be a line that just literally states "idea gathering phase will be closed"?
![Screenshot 2024-07-05 at 14 24 17](https://github.com/citizenos/citizenos-fe/assets/26792281/55ca0536-b24f-4173-8f9a-4720f9172c34)

I'm not sure if then another tab is necessary because it would basically have the same purpose as this one...

**Comment by BeccaMelhuish** [comment]
OK yes I think this is good! Should be hard to miss..

What about this one though? I'm thinking that seeing as we reiterate the other 2 'X' ones at the end of the vote setup (in the preview), we could move the third one to be second, and make the top two both red. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/82b47d70-b112-403c-aed9-382f1d6edf81)

**Comment by kevincrepin** [comment]
Yes, I guess the logic would then be that in red we indicate that the previous phase(s) are closed.

**Comment by ilmartyrk** [comment]
est. dev time 15 mins

**Comment by BeccaMelhuish** [comment]
Checked and all good, moving to done :)
