### ISSUE TITLE
IDEATION: Participants unsure who creates folders and if they can add ideas

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1372]
@kevincrepin @ilmartyrk 

**Insights from Round 2 ideation testing:** 

- There were several comments from participants questioning how the folders get created, how they come to be, who creates them etc. 
- By the time the participants came to see the folders, there were already folders added, so they didn't see the 'There are no folders yet' text which explains that admins can add ideas to folders. 
- One user also was very keen to add her idea to a folder, and tried to do so by first clicking on the actions menu for an existing idea, and then going into the folder and then clicking on the 'Add an idea' button whilst in that folder. 

**Suggestions**

- Might we add a little guidance somewhere that communicates to participants how folders work / who adds to them etc? 
- In future, might we be able to give the option for admins to allow participants to add ideas to folders themselves- perhaps as an option in the topic settings? One admin in Round 1 said she was keen for them to be able to do this, and a participant in Round 2 (as above) was keen to do so.

**Comment by kevincrepin** [comment]
We can add a simple line here:
![Screenshot 2024-07-05 at 14 35 32](https://github.com/citizenos/citizenos-fe/assets/26792281/77b5e2c0-6ce5-4228-92bf-78736190df39)

And having the option to allow Only admins or both admins & participants in the settings makes sense. We can reuse existing components for this:
![Screenshot 2024-07-05 at 14 40 52](https://github.com/citizenos/citizenos-fe/assets/26792281/1f22c5a3-941f-4852-b8d9-2ca485fbf66a)

**Comment by BeccaMelhuish** [comment]
Looks good! Though a few copy things: 

- Rather than just 'create', should be 'create and add to'? 
So "_Assign who can create and add to folders, to gather together ideas of a similar nature_".
Then in the ones below could be "_manage_"? 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/aa5ada67-e7d0-4c45-9e18-85ac6c40baca)

- Only issue with 'Admins & participants' is that we also have an 'editor' role. Maybe it should be: 

**_Anyone_**
_All those who've joined the topic can manage folders_

**Comment by kevincrepin** [comment]
Sure! Updated here: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=645-70531&t=OOv6hBVMuaI6bQBX-1

**Comment by BeccaMelhuish** [comment]
Made a new issue for the folders choice and will close this one :)
