### ISSUE TITLE
ACTIVITY FEED: Issues with users and topics the activity feed

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#138]
**What is the problem?**
1. When a user creates two topics with the same name and invites the same user to both the system treats it as if one user is in fact two users (screenshot attached)
<img width="797" alt="Screenshot 2023-05-28 at 19 30 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f8da187d-49e7-4f2c-8c91-941847602ac7">

2. Inviting the same user to similar topics leads to the topics being grouped together, which makes it very difficult for the user to find the topic in the activity feed (screenshot attached)

<img width="738" alt="Screenshot 2023-05-28 at 19 48 15" src="https://github.com/citizenos/citizenos-fe/assets/72747107/337c2580-20da-49b9-8760-dcf3dc81062d">

**Why is this a problem?**
Finding the most recent topic from the activity feed is difficult if different topics are grouped together as one. Also having the same user treated as two separate users is confusing for the topic owner.

**Possible solution.**
Each topic should be a separate entry in the activity feed regardless of the title or the author (and whether they are the same or similar)

**Comment by anettlinno** [comment]
Triage 86. Activity feed changes/improves quite a lot with redesign project. Will send this issue to redesign project.

**Comment by ilmartyrk** [comment]
@anettlinno this is rather Phase II issue, we dont have grouping anymore in the Phase I activity feed anyway

**Comment by ssin1901** [comment]
Activity feed reflects the accurate number of users (screenshot 1, screenshot2, screenshot3). Closing the issue 
<img width="1438" alt="Screenshot 2024-01-24 at 11 57 33" src="https://github.com/citizenos/citizenos-fe/assets/72747107/183d33e2-27df-49aa-97b8-6f4f1e880407">
<img width="1440" alt="Screenshot 2024-01-24 at 11 57 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7c5378e8-9fae-4627-8054-395ed46bcfa0">
<img width="1440" alt="Screenshot 2024-01-24 at 11 57 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c41508dd-1fa0-42f2-9a88-a4ebb6af2c92">
