### ISSUE TITLE
MISC: Removal of mock help tooltips before ideation launch 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1381]
@ilmartyrk the mock 'Help is on its way!' tooltips from [this issue](https://github.com/citizenos/citizenos-fe/issues/1200) were very helpful in the testing, but should be removed before idea gathering goes live :) 

Some of these tooltips the testing showed we do still need, but I've not yet prioritised writing the texts for them. So a couple of options depending on what works for you @ilmartyrk:

- I can prioritise writing the texts this week for the ones that should be kept, and then you can add the correct texts and remove the ones that aren't needed. 
OR:
- If it's possible to easily just hide them all for now, and then make them appear again when the texts are ready, this would be best for me in terms of workload and priorities. Then I could come back to working on the texts when I have more time. (None of them are causing an major UX issues at the moment, just would help clear up some points of confusion in places, so probably best if I spend time on other priorities for now).

**Comment by ssin1901** [comment]
@ilmartyrk, reopening this issue because of #1492
