### ISSUE TITLE
REGISTRATION: Facebook login not working properly 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1384]
**What is the problem?**
_Tested in Google Chrome, incognito_

In the Live environment, after creating an account with Facebook I was asked to login (screenshot1) instead of being asked to directly accept the terms and conditions (screenshot2). 

<img width="1432" alt="Screenshot 2024-07-09 at 23 29 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a5ba5afd-a457-4c9a-999c-5cb8b00db36b">

<img width="1429" alt="Screenshot 2024-07-09 at 23 31 05" src="https://github.com/citizenos/citizenos-fe/assets/72747107/34bb5ef0-15c0-4c32-8ba5-93712b07165a">

When retesting, I was able to create an account with valid Facebook credentials and accept the Terms and Conditions without an additional login popup.

NB! Deleted and recreated account was used for the second test

**Why is this a problem?**
There should be consistency. 

**Possible solution.**
Users should not see an additional Login popup.

**Comment by ssin1901** [comment]
Moving to Pre-Live as could not replicate the issue in Test. @BeccaMelhuish I'm thinking that Done might be more appropriate though?

**Comment by BeccaMelhuish** [comment]
Yeah done is better if can't replicate :)
