### ISSUE TITLE
Unnecessary code in the activity feed

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#139]
**What is the problem?**
The activity feed displays unnecessary code in certain places.

<img width="676" alt="Screenshot 2023-05-28 at 19 35 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/13b23092-4d0d-449a-8f63-2944975ba7e8">

**Why is this a problem?**
Confusing to the user

This is helpful for prioritizing the bugfix.

**Possible solution.**
The code should not be visible to the user

**Comment by anettlinno** [comment]
Triage 86. Probably is a quick fix, 10 min. Sending it TO DO.

**Comment by ilmartyrk** [comment]
@ssin1901 Could not replicate, can you add more details, possibly topic id

**Comment by ssin1901** [comment]
Hi @ilmartyrk my apologies. This error occurs on both Safari and Chrome, specifically when user1 invites user2 to a topic and then user 2 changes the field description (see screenshot from iPad below)
![IMG_0474](https://github.com/citizenos/citizenos-fe/assets/72747107/121cab02-fcbc-47b9-b0d3-7912d34b5f9b)

**Comment by ssin1901** [comment]
Also invited you to the topic
