### ISSUE TITLE
LANGUAGE: Changing language automatically triggers the login popup

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1391]
**What is the problem?**
_Tested in Google Chrome, incognito mode_

When a user switches Languages, the login popup appears along with a flash (see screen recording). Happens regardless of which Language is being selected.

https://github.com/user-attachments/assets/8d1a8064-8ee0-4958-8827-bd310b107115

**Why is this a problem?**
High priority because users may want to explore the site, and the log in popup would confuse them and prevent them for exploring public and private topics.

**Possible solution.**
Switching language should translate the content of the site without triggering a login popup

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix
