### ISSUE TITLE
TOUR: Wrong topic tour initial text on mobile 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1395]
I couldn't take a screenshot as was in incognito mode, but on my phone I get the wrong tour text display initially for the topic tour. It is currently the one that starts "Topics look (and work) a bit differently since the update". But this isn't the latest version of the text. 

I have always had the right text on desktop, and in tests on mobile users have often (but not always) had the right text too. But on certain mobiles it seems to display this wrong text - or it may depend on whether you are logged out or logged in when you go into the topic. In this case (where I got the wrong text), I was logged out.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I don't see any other text in the history, what should the text be?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK I see what it is now:

On desktop, the pop-up has the correct heading: 

![image](https://github.com/user-attachments/assets/ef9ce3c0-9fd6-4a1c-a47f-300b68f5a265)

But on mobile it has this old heading - should be the same as the above (with the celebration emoji too) :) 

![image](https://github.com/user-attachments/assets/3200ee67-fb53-4045-8c28-2e214c269a00)

**Comment by ssin1901** [comment]
@BeccaMelhuish tested with Playwright and got this correct tour (screenshot). Moving to Done
![Screenshot 2024-11-14 at 23 26 24](https://github.com/user-attachments/assets/62654184-9806-4796-90c7-198c96bb7de0)

**Comment by ssin1901** [comment]
Also got the same with Pixel 5 (Android).
