### ISSUE TITLE
TOPICS: Topic showing up in My topics twice

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1397]
@ilmartyrk @ssin1901 I made this ideation topic a few mins ago, and while working on it have noticed there are two of them showing up in my topics, but I only made one. They show slightly differently on the card as below, one with 6 ideas and one with 0, but when I go into the one that says it has 0, it does actually have 6. It seems they are just one topic, but showing twice. 

![image](https://github.com/user-attachments/assets/61dee69d-9e5f-4a3b-a1e9-ef3ec75937f8)

Link to the topic(s) here: 
https://test.app.citizenos.com/topics/join/yUJaOYRd5jAe 

Added high priority as seems needs fixing before launch :)

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate but let's keep an eye on this one
