### ISSUE TITLE
TOPICS: Header photo bugs in test app

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1399]
Was trying to change the header photo on a topic:

- Removed the original
- Tried to an a new one but got the error message to say it's too big (fine)
- Resized it and saved it
- Tried to upload it again, nothing happened when I clicked open (after 'Choose a file') 
- Saved with no photo
- Went back in to try again
- It looked like the new photo had uploaded when I clicked open this time
- But on saving it, I see that the old photo is still there
- Repeated this, same thing happened - screen recording here:
https://www.loom.com/share/a3428e51e215485296033205f1546a0e?sid=4ebe3503-b668-4055-b5b8-2b8222a563c7 

This is the topic: 
https://test.app.citizenos.com/topics/join/yUJaOYRd5jAe

**Comment by BeccaMelhuish** [comment]
Update: just went out of the topic and came back in again, the new photo was there :) 

![image](https://github.com/user-attachments/assets/6abf1530-1fbf-408f-9eb5-ff35920f2e98)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 I'm unsure if this should be high priority or not, but I guess possibly?

**Comment by ssin1901** [comment]
@ilmartyrk I could replicate the issue and I'm also not sure why the additional error message is being generated (screenshot1)

<img width="992" alt="Screenshot 2024-07-16 at 16 18 31" src="https://github.com/user-attachments/assets/bf8997fa-651b-4ccc-89fc-e039cbb8c97e">

Either way, after closing this message the new header image was not added. Adding a high priority label.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 I could not replicate it, can you send me the photo files to test with

**Comment by BeccaMelhuish** [comment]
@ilmartyrk this was the one I was using (originally larger, then resized), though let me know if you need it via another channel (not sure if github alters the size?)  

![sunny-urban-landscape](https://github.com/user-attachments/assets/060173d5-4aeb-4013-b516-545dbe468310)

**Comment by ssin1901** [comment]
@BeccaMelhuish I'm moving this to Done, but there are some small UX bugs with header images. Will create a separate issue for this.
