### ISSUE TITLE
LOGIN: HTTP Error after logging out

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1401]
**What is the problem?**
_Tested in Google Chrome, incognito mode_

I got an HTTP error in Live app after exiting a topic without saving (screenshot1).
<img width="1325" alt="Screenshot 2024-07-16 at 16 11 46" src="https://github.com/user-attachments/assets/ac60e790-d280-4cd6-8be2-6235f5bb8cd4">

For additional information, I had switched from Test to Live in the same window.

**Why is this a problem?**
Confusing to the users

**Possible solution.**
HTTP error should not be displayed

**Comment by ilmartyrk** [comment]
@ssin1901 this was probably caused by some server response issue. I checked at the heroku status for API and there were two times that this error happened. This is nothing from our code side, closing the issue
