### ISSUE TITLE
TOUR: Take the tour pop-up bug - should only be the first time

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1402]
@ilmartyrk @ssin1901 A comment from @MeelikaH that "I'm still getting "take a tour" pop-up every time I log in". 

I think we had an issue to fix that previously, but seems it's not fully fixed in this case? Should only be a user's first time on DB, and first time in a topic, since the redesign. After that should pop up no more :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 @MeelikaH might be that your browser settings don't allow cookies for some reason. Also what tour you are referring to dashboard or topic and also on what device, browser?

**Comment by BeccaMelhuish** [comment]
Will leave @MeelikaH to share more details on this one :)

**Comment by MeelikaH** [comment]
@BeccaMelhuish and @ilmartyrk this seems to no longer be the issue anymore. I no longer see it when I log in. I guess can be removed from tasks.
