### ISSUE TITLE
VOTING: Multiple choice vote did not indicate that multiple options had to be selected

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1406]
**What is the problem?**
_Tested in Google Chrome and Safari_

A multiple choice vote (https://test.app.citizenos.com/en/topics/58921fb1-a36f-45ef-bd06-951d735c80b4#voting) did not indicate in any way that at least 4 options (Min vote) had to be selected for the submit button to work (screenshot1).

<img width="824" alt="Screenshot 2024-07-17 at 11 54 48" src="https://github.com/user-attachments/assets/a2f16aef-d510-498c-bf6f-a42a1c3959d0">

**Why is this a problem?**
Initially assumed that voting was broken 

**Possible solution.**
@ilmartyrk @BeccaMelhuish did this text get changed? I remember that it used to say at least x number of options need to be selected.

**Comment by BeccaMelhuish** [comment]
@ssin1901 Well spotted yes there's a chunk missing that should be there in addition to that text, seems to have gone missing (checked a few other topics I have 'in voting' and the same for them too)

**Comment by ssin1901** [comment]
@ilmartyrk issue recurred (screenshot1) in an idea gathering topic (https://app.citizenos.com/en/topics/399bda02-2586-4b69-960a-50cf3bbdc038#voting)

<img width="1348" alt="Screenshot 2024-08-20 at 17 19 47" src="https://github.com/user-attachments/assets/6b06fe11-f3bd-4a1e-8e1d-73486e09a5b1">

<img width="1344" alt="Screenshot 2024-08-20 at 17 19 32" src="https://github.com/user-attachments/assets/39612b32-7131-4de8-baf1-3d345b43c274">
Preview was correct though (screenshot2)

**Comment by ssin1901** [comment]
@ilmartyrk My apologies, the text is displayed under the heading.
