### ISSUE TITLE
ACTION: Remove action item leads to internal server error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1416]
**What is the problem?**
When the user removes an item, they receive an internal server error (see screen recording)

https://github.com/user-attachments/assets/64bbc147-0117-448b-80fe-8405f17dfb9f

**Why is this a problem?**
User cannot remove action items

**Possible solution.**
User should be able to remove action items

**Comment by ilmartyrk** [comment]
@ssin1901 Actually the removing itself works, but the list was not reloaded after removing the item.
