### ISSUE TITLE
VOTING: User sent vote reminder but it was not received 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1419]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

The user sent a vote reminder for this topic (https://test.app.citizenos.com/en/topics/58921fb1-a36f-45ef-bd06-951d735c80b4#voting)and was notified that reminders were successfully delivered (screenshot1). 

However, the vote reminder was **not delivered** to user Sara. 

<img width="1152" alt="Screenshot 2024-07-18 at 12 12 47" src="https://github.com/user-attachments/assets/e381cbdb-bf3d-4e13-9cd1-e551ec72e10a">

**Why is this a problem?**
Vote reminders should be delivered. This is very important to the process.

**Possible solution.**
Recipient should have received the email.

**Comment by ilmartyrk** [comment]
@ssin1901 reminder sending might take some time as it is an automated background task that is running. It might have had some hick-ups in our testing as I am updating the code and it restarts all the servers etc.
