### ISSUE TITLE
Improve vote results UI

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#142]
**What is the user story?**
1. Currently when the topic administrator accesses the voting results, the UI is not very attractive or intuitive (see screenshot). <img width="802" alt="Screenshot 2023-05-30 at 17 48 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9e58385c-b48c-4305-9f6c-339c4337ff0f">

**Which feature needs to be updated and how?**
1. User should be able to visualise which topic got the most votes 

**Additional information.**
@ilmartyrk do we have a design for this in Redesign?

**Comment by anettlinno** [comment]
I couldn't find voting results from the redesign repository -- @kevincrepin is it there? :)

**Comment by kevincrepin** [comment]
It is here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=335%3A42968&t=pNUE6CCpAxvHVwFc-1

:)

**Comment by ssin1901** [comment]
@kevincrepin looks amazing. @anettlinno then this is already part of Redesign, so will eventually be implemented anyway?

**Comment by anettlinno** [comment]
Same discussion took place in issue #230 

@kevincrepin we are still missing "Download vote results" designs :)

**Comment by kevincrepin** [comment]
Added! 

https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=335-42968&viewport=-6060%2C-20961%2C0.5&t=HEcUcRHdzXZM1IP1-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

**Comment by anettlinno** [comment]
@ssin1901 voting results UI will be solved in redesign and we also have the vote results downloading designs.

**Comment by anettlinno** [comment]
Triage 95. Closing the issue as it is implemented.
