### ISSUE TITLE
Spammy-looking public topic headings

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#143]
@ilmartyrk @anettlinno @ssin1901 
These public topics panels are displaying the group name twice (but when you go into them the heading only shows once), looks rather spammy:

![image](https://github.com/citizenos/citizenos-api/assets/61320526/9073f883-1c6f-4aaa-b96c-52f14e80578a)

**Comment by ssin1901** [comment]
@BeccaMelhuish good catch. Issue has been replicated on Safari and Chrome and translating the page using the in built Translate to English feature in Chrome does not solve the problem (screenshot attached)

<img width="321" alt="Screenshot 2023-05-30 at 18 34 15" src="https://github.com/citizenos/citizenos-api/assets/72747107/94db7926-7044-4312-878a-e85f4b5e8ba8">

**Comment by anettlinno** [comment]
Triage 86. Quick fix, 10 min. Sending it TO DO.
