### ISSUE TITLE
Groups and public topics navigation broke when coming back to open tab after a few hours

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#144]
@ilmartyrk @anettlinno @ssin1901 
Copying my Slack message for info here: 

![image](https://github.com/citizenos/citizenos-api/assets/61320526/45fd2a11-3570-4d49-bbfe-04ed474308d6)

**Comment by anettlinno** [comment]
Triage 86. Could not replicate the issue. Left topic open for 12 hours and when clicked on "My groups", everything worked. 
BUT the system didn´t log me out, but it should, @ilmartyrk?

**Comment by anettlinno** [comment]
Triage 87. Needs some investigation. Est.time 30 min. Sending it to do.

**Comment by ssin1901** [comment]
@anettlinno @ilmartyrk came back to account after a few hours and everything was working normally on Safari and Chrome. Will keep an eye out for related issues though.

**Comment by anettlinno** [comment]
Triage 89. Closing this issue.
