### ISSUE TITLE
IDEATION: Translated text needs re-alignment

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#1448]
**What is the problem?**
There are a few places, where translated (=often longer) text doesn't fit into the designed space.
There'll probably be more findings - I'll keep adding them to this ticket if I find any.

#1 
<img width="739" alt="Screenshot 2024-07-23 at 18 26 01" src="https://github.com/user-attachments/assets/6a20186f-7fba-4be2-8aee-d12a94e86d22">

----

#2
There's also the menu (AF) that doesn't fit the set width:

https://github.com/user-attachments/assets/8bd515fd-3d3a-4920-808c-2181d86efc57

----

#3

Topic notifications settings menu has items which break if text is longer than necessary:
<img width="600" alt="Screenshot 2024-07-24 at 11 39 30" src="https://github.com/user-attachments/assets/1cae9fe4-544c-422b-b9ea-13b35325e9b7">

----

#4 

Help text's "?" icon appears on top of text for some reason, when adding a topic to group:

https://github.com/user-attachments/assets/ee0afb80-4413-4c08-bb2e-3d13c27a9942

**Comment by oksks** [comment]
Yup, I've tested and issues 1 + 4 are still intact

**Comment by ilmartyrk** [comment]
@oksks I have no good solution for the nav menu issue if by 1 you are referring to that. But will try to fix others on the go, also I thought I fixed 4 as I found when adding topic to group under topic view, so +1 extra issue found and fixed will fix 4 too

**Comment by ilmartyrk** [comment]
@oksks can we close this one for now and create a new issue(s) if they come up?

**Comment by oksks** [comment]
Sure! Closing.
