### ISSUE TITLE
IDEATION: Localized UI reverts back to English

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#1449]
**What is the problem?**
I've selected Russian as my language, but after a while, I've found I'm back on English for some reason.
Please check the video below - I've reproduced the issue. 
Mac, Chrome.

https://github.com/user-attachments/assets/c6918d5f-8fcf-4ed6-a981-25785ddc5af6

**Comment by ssin1901** [comment]
@BeccaMelhuish keeping this and #1468 here to keep an eye on it

**Comment by BeccaMelhuish** [comment]
@ssin1901 I have a feeling this may have happened today, when I was showing Meelika something in Estonian, I think at some point I found myself back in English and had to switch again. But I was preoccupied with the conversation so am not 100% sure :)
