### ISSUE TITLE
Activity feed "load more"

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#146]
@ilmartyrk @anettlinno 
Re the activity feed, @ssin1901 raised this as something that needs to be explained in the HC, but two issues for me below:

![image](https://github.com/citizenos/citizenos-api/assets/61320526/ca505328-19a7-4367-88eb-a866c7a66857)

(1) It didn't actually work like this for me, in my browser (Chrome, on Windows), when I scroll to the bottom nothing happens.

(2) Even if it does it is slow on some browsers, so would seem to be better UX if there was a "load more" button, so that people can see how it works, and so that it works more reliably across browsers. 
 
I wouldn't want to explain this sort of thing in the HC, but if we can make it work with a change of UI, then that would be great :)

**Comment by anettlinno** [comment]
Triage 86. Could replicate in some screen size, scrolling issue needs investigation. 
Decided not to change the scrolling option to "Load more" as if this works, then it´s logical and good solution.

Est. investigation time 30 min. Sending it TO DO.
