### ISSUE TITLE
PROFILE: Language switched back to English when it was still set to Eesti

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1468]
@ilmartyrk @ssin1901 See screenshot below. In internal testing, @MeelikaH had changed the language to Estonian, and it did change, but then a minute later it was English again. We went back to check the settings and Eesti was still selected. 

I checked the recording and the flow was that she changed it to Eesti (then did something profile photo related), then saved, then navigated to this Notifications tab, and as she did so it switched back to English:

![image](https://github.com/user-attachments/assets/17807a0e-9dd5-43d4-b15a-1e47dc12af23)

But as above. when we noticed and she went back into her profile, Eesti was still selected. 
![image](https://github.com/user-attachments/assets/26b59575-b76e-4dbf-9c19-4076f43d6bc7)

She saved again and it was fine (i.e. stayed in Estonian) for the rest of the test.

**Comment by BeccaMelhuish** [comment]
@ssin1901 maybe this one is worth testing some more before Ilmar looks at it? If it does seem to be a recurring issue please move it to 'soon' :)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk could not replicate this issue. Could I close this issue and #1449 and create a single issue in QA for testing language persistence?

**Comment by ssin1901** [comment]
@BeccaMelhuish closing this issue as it is similar to #1449
