### ISSUE TITLE
TOPICS: 'Add a / There is no discussion' block missing from ideation topic 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1469]
@ilmartyrk @ssin1901, In internal testing with @MeelikaH, I made a quick ideation topic, invited her as participant. During ideation phase, for both of us the 'Discussion' tab showed at the top, but there was no block for it in the right hand panel. I was still able to start a discussion though, via the tab view.   

![image](https://github.com/user-attachments/assets/3763dc75-ec57-46b7-887f-110451799557)

![image](https://github.com/user-attachments/assets/345e023f-a30c-446a-832f-c62a8e158680)

![image](https://github.com/user-attachments/assets/923fd3b8-b345-40d7-89ee-ed1a5a0bc66d)

**Comment by ssin1901** [comment]
Adding high priority as this really affects the process

**Comment by BeccaMelhuish** [comment]
@ssin1901 moved this to testing column in case needed :)

**Comment by ssin1901** [comment]
Panel now added (screenshot1, screenshot2).

<img width="1154" alt="Screenshot 2024-08-14 at 01 39 40" src="https://github.com/user-attachments/assets/d0abb07e-6539-4075-87d5-17e1dcefdb10">

![Simulator Screen Shot - iPhone 14 Plus - 2024-08-14 at 01 46 36](https://github.com/user-attachments/assets/43a9f47a-9225-432f-97c7-b38f519c3f30)

**Comment by ssin1901** [comment]
@BeccaMelhuish moving to Done. See comment above.

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk closing this one
