### ISSUE TITLE
Redesign create group flow

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#147]
Create group view from redesign project
Development tasks:
- [x] item

Administrative tasks:

- [ ] Update CHANGELOG files
- [ ] Inform marketing of new feature(s)
- [ ] Inform localization on new translations

**Comment by anettlinno** [comment]
Please add more room between description text and content text:


![Image](https://github.com/citizenos/citizenos-fe/assets/45175679/dcdc1921-a362-4c52-ae0b-0e5616a18ed7)

**Comment by anettlinno** [comment]
Rules or Agreements? 

I will leave this here to think about. Do we want people to follow the **rules** or set **agreements**?
In our cultural space the connotation for "rule" is something heavy, something that comes from top down. IMHO **Agreements** are more collaborative-minded and are more respectful towards each other. 

But what dictionaries say? 

**Rule** (_noun_)
1. one of a set of explicit or understood regulations or principles governing conduct or procedure within a particular area of activity (from Oxford Languages)
2. control of or dominion over an area or people (from Oxford Languages)

**Agreement** (_noun_)
1. harmony or accordance in opinion or feeling (from Oxford Languages)
2. a negotiated and typically legally binding arrangement between parties as to a course of action



![Image](https://github.com/citizenos/citizenos-fe/assets/45175679/014fd706-25e4-4e8f-86c8-303344482dd0)

**Comment by anettlinno** [comment]
Language list under the "Coutnry" drop-down menu: 


![Image](https://github.com/citizenos/citizenos-fe/assets/45175679/52c353cb-09e5-4929-817b-5d42510651ce)

**Comment by ilmartyrk** [comment]
@anettlinno don't get carried away, many new inputs under groups creating flow don't have real data/values, just placeholders as we don't have API side support for them, so no need to mark out wrong values in countries, tags etc. that we don't have in our current app

**Comment by anettlinno** [comment]
https://github.com/citizenos/citizenos-fe/issues/147#issuecomment-1592508630

Noted Ilmar :))
