### ISSUE TITLE
TOUR: In Estonian, topic tour tab shows additional text and gets in the way of content 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1470]
@ilmartyrk @ssin1901 Please see screenshot, needs checking in other languages: 

![image](https://github.com/user-attachments/assets/514b6782-ddb7-4db8-85c0-c778bcce7c6f)

Should just be like this in all languages: 

![image](https://github.com/user-attachments/assets/1235ea27-bc8f-42f0-93bf-c45d8f1e74d1)

**Comment by ssin1901** [comment]
Checked in other languages and no additional text (screen recording). Moving to Done.

https://github.com/user-attachments/assets/683f813c-1396-4ff0-9928-dd69ab1f46ba
