### ISSUE TITLE
IDEATION: When open an idea during another phase, moves you to that phase underneath 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1471]
@ilmartyrk @ssin1901 

E.g. here @MeelikaH opened an idea while topic had moved on to discussion phase. As you can see underneath the pop-up of the idea, it is showing the discussion tab. It shouldn't haved move her there, but she should stay in the ideas tab. Same thing happened when she opened one in the voting phase, it showed the vote underneath. 

![image](https://github.com/user-attachments/assets/cc4409ef-0cc2-4714-b063-edbdd1590af7)

**Comment by BeccaMelhuish** [comment]
Added high priority as could be very disorientating for users

**Comment by ssin1901** [comment]
@BeccaMelhuish Seems fixed and moving to done (see screenshot)
<img width="1156" alt="Screenshot 2024-08-14 at 01 35 34" src="https://github.com/user-attachments/assets/6d64de55-048f-4e0f-8064-84a6801a03ce">
