### ISSUE TITLE
IDEATION: Can't report an idea - "Internal server error"

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#1480]
**What is the problem?**
1) I've just tried reporting an idea in our AI topic, and I get an "Internal Server Error" message after trying to submit it. 
2) Also, this string doesn't seem to have made it as a translatable for FE, so it's in English instead of Russian - please create a translatable string:)

https://github.com/user-attachments/assets/1ad6bc1e-1aca-4c72-9c03-cf9bd651f377

3) Why does it say "You are reporting Becca Melhuish"? Maybe change it to "You are reporting a contribution made by user X"? As you're not really reporting a user.
<img width="577" alt="Screenshot 2024-07-25 at 19 06 58" src="https://github.com/user-attachments/assets/9258637e-2ef7-4158-85b3-a78161d21d53">

**Comment by ilmartyrk** [comment]
@oksks fixed the reporting not working issue

**Comment by ssin1901** [comment]
@BeccaMelhuish @oksks I just tested and reported an idea by Oksana. Did not get internal server error.

You should both have received notifications. Please let me know if you did!

**Comment by oksks** [comment]
Yep, I got an email about my idea having been reported, but I also got an email as a moderator, with an ask to review the report - filed a [separate bug](https://github.com/citizenos/citizenos-fe/issues/1503) about that.

**Comment by ssin1901** [comment]
@oksks I think we can close this one now?

You filed a separate bug about the moderator email.
