### ISSUE TITLE
DISCUSSION: Can't reply - reply button greyed out

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1483]
@ilmartyrk @ssin1901 In our team 'Story of Estonia testing/research' topic, I'm not able to reply to Meelika's comment - the reply button is greyed out: 

![image](https://github.com/user-attachments/assets/8816c881-b7cb-4929-91d6-1429f4173841)

Seems quite high priority to me, so have labelled it as such :)

**Comment by ssin1901** [comment]
Indeed, a high priority and could replicate! Thanks @BeccaMelhuish

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 posted a fix

**Comment by ssin1901** [comment]
@BeccaMelhuish I tested with nested replies (see screen recording). Seems to work alright.

https://github.com/user-attachments/assets/04ea0a2e-f971-4957-92da-ddf873c490ea

**Comment by BeccaMelhuish** [comment]
Great, looks good and I was able to reply to Meelika, so will move to 'Done' :)
