### ISSUE TITLE
TOPIC: Share link not working 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1486]
**What is the problem?**
_Tested in Google Chrome and Safari in incognito mode_ 

User generated a link but inputting the generated link led to a blank screen (see screen recording)

https://github.com/user-attachments/assets/dd978b74-f07b-4994-b635-cbf8f4fd4357

**Why is this a problem?**
Users cannot join topics via share link. High priority.

**Possible solution.**
Share link should work

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the issue

**Comment by ssin1901** [comment]
@ilmartyrk thanks! Issue is resolved (screen recording)

https://github.com/user-attachments/assets/9ded136d-35a3-4c3a-b143-2a75f5b8c520
