### ISSUE TITLE
NOTIFICATIONS: Missing 'manage notifications' button for participants

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1488]
I tried a couple of public topics, and both before and after joining, the button to manage notifications was missing, it only has the text:

![image](https://github.com/user-attachments/assets/83356cb2-c41e-41b5-b8d4-3a4c96d13c34)

![image](https://github.com/user-attachments/assets/1d466304-00a3-4bc8-b11a-613647994872)

I'd suggest that it's slightly different for before and after joining the topic.

**Before joining could be:**

Join this topic to turn on notifications, then mange them here to stay engaged and up to date.  
(Manage notifications) _- greyed out_

**After joining, same as it is already but with the button added:**

Turn on all notifications to stay engaged and up to date with this topic's activity.
(Manage notifications) _- active_

**Comment by BeccaMelhuish** [comment]
I notice it is also missing in [this private topic](https://app.citizenos.com/en/topics/62731600-613c-4cac-a5f3-f8f0dae41211#ideation) (in which I am participant not admin): 

![image](https://github.com/user-attachments/assets/d5de4f58-e21b-49f6-a180-20ded60d482c)

Will add 'small' label as I assume it must be

**Comment by BeccaMelhuish** [comment]
**Dev task summary:** 

Make sure the 'Manage notifications' button shows up for all types of users (admin, editor, participant) in all topic types (public or private), like it does currently for admins: 

![Image](https://github.com/user-attachments/assets/41de60db-a834-4f92-aef6-7ddc353a66a5)

**Comment by ilmartyrk** [comment]
fixed together with #1212

**Comment by BeccaMelhuish** [comment]
Tested and all good, moving to 'pre-live' :)
