### ISSUE TITLE
Remove 6 languages from the app

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#149]
Please remove the following 6 languages from the app, as per [chat](https://citizen-os.slack.com/archives/C7VFLSGN8/p1671549905193829):
- [ ] Macedonian
- [ ] Polish
- [ ] Dutch
- [ ] Latvian
- [ ] Finnish
- [ ] Brazilian Portuguese

Thank you!

**Comment by oksks** [comment]
Should be done at once with #154

**Comment by oksks** [comment]
Note to self: update number of languages on http://beta.citizenos.com/product/ when this ticket is closed

**Comment by oksks** [comment]
@ilmartyrk I still see them in the app?

**Comment by ilmartyrk** [comment]
@oksks done, there was some weird config issue that I will need to check in the future, Anyway sorry for the long delay
