### ISSUE TITLE
TOPICS/GROUPS: Displayed 'no groups' to add topic to, when there should have been 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1493]
@ilmartyrk @ssin1901 When I went in to edit a dummy topic I had made ([this one](https://app.citizenos.com/topics/join/O7ibYmFoqqYJ)), I was told I wasn't in any groups:

![image](https://github.com/user-attachments/assets/6dcc5a9a-82dd-4503-862b-86c928348b6c)

I tried refreshing and it appeared as it should:

![image](https://github.com/user-attachments/assets/3a68482d-5389-4e53-b393-3c1ac28f6a46)

I then tried again, going into edit mode and going to 'Settings', and the same thing happened: 

![image](https://github.com/user-attachments/assets/a82be280-3d95-4c05-97f2-4d677e1b7f44)

**Comment by BeccaMelhuish** [comment]
Just created a new topic and had the same thing happen. Again it worked when I refreshed. 

![image](https://github.com/user-attachments/assets/2823f97d-142c-4fdd-a3f7-192df44cb01d)

Will add high priority for when Ilmar's back, and maybe @ssin1901 can test if it's happening for others or just me?

**Comment by ssin1901** [comment]
@BeccaMelhuish could replicate. Additionally, after I refreshed the page, I had this view in Google Chrome (screenshot1)
<img width="1149" alt="Screenshot 2024-08-13 at 10 02 20" src="https://github.com/user-attachments/assets/98dd1b45-739e-489a-9f1f-2e8381b61d22">

**Comment by BeccaMelhuish** [comment]
Will leave for @ssin1901 to test if that's OK :)

**Comment by ssin1901** [comment]
@BeccaMelhuish checked the with the same topic and seems to be fixed (see screen recording)

https://github.com/user-attachments/assets/4deada2b-15db-49e9-8b6b-45258e9bfa60

Moving to Done
