### ISSUE TITLE
TOPICS: Group rights tooltip very misaligned and sometimes missing, plus text update

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1494]
In topic edit, and 'starting with discussion' create flow - misaligned:

![image](https://github.com/user-attachments/assets/1d9cd2f4-1ea6-4c9f-b6da-43a383f05463)

In 'starting with idea gathering' topic create flow - missing:

![image](https://github.com/user-attachments/assets/d4e67ea8-7f65-4086-a633-b4e24fb8ecfe)

In 'starting with voting' topic create flow - also missing:

![image](https://github.com/user-attachments/assets/d725381a-dfbf-4f33-8804-12611d94df11)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk when fixing this one, please also adjust the tooltip text to:

**Group permissions for topic access**
This will give all members of the group the selected role within the topic, unless you individually assign them a different role from the topic's 'manage participants' section.

**Admins** can access all settings to manage the topic. **Editors** can edit the topic content (text, images, attachments) and the tags (categories, language, location). **Participants** can participate in whichever topic phase is open.

**Comment by BeccaMelhuish** [comment]
Checked and the placement's looking better for me, but a few places it's not quite correct :) 

In create flow for 'starting with discussion' topics, and edit flow when it's in discussion, these two are the wrong way around - should be just 'Group permissions' as the dropbox heading, then 'group permissions for topic access' on the tooltip pop-up: 

![image](https://github.com/user-attachments/assets/1985568c-0f97-4e11-a685-c98c58a5fdde)

In create flow for 'starting with voting' and 'starting with idea gathering' topics, plus in edit flow when it's in voting and idea gathering, the heading on the tooltip pop-up itself should be 'group permissions for topic access': 

![image](https://github.com/user-attachments/assets/18b46dd5-c782-4057-86b2-360bd9df3691)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now

**Comment by BeccaMelhuish** [comment]
Checked and all good! Once issue re placement but I'll make another issue for that, moving to Done :)
