### ISSUE TITLE
TOUR: Text is misleading for recurring visitor

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1497]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

User has the tour window popup every time they login, but the text is misleading. The text indicates that it is the users first time on the redesigned platform but this not the case (screenshot1)

<img width="1345" alt="Screenshot 2024-08-13 at 19 59 34" src="https://github.com/user-attachments/assets/96f211e6-6f8d-4ece-b6a4-c342a24d9a94">

**Why is this a problem?**
This is very confusing, as the users would expect to see a new design every time they saw the text

**Possible solution.**
@BeccaMelhuish @ilmartyrk can you remind me what was decided? I think that only first time users need the onboarding.

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk I understood from this issue https://github.com/citizenos/citizenos-fe/issues/1402 that this is to do with browser cookies. 

I am still thinking – should we still change the text?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Yes it should indeed be only the first time a user comes to the site - either ever, or since the redesign launch. 

In [this](https://github.com/citizenos/citizenos-fe/issues/1402) (now closed) issue, Ilmar suggest it might be browser cookies? Does testing it in incognito mode affect how they work?

**Comment by ssin1901** [comment]
@BeccaMelhuish yes, I'm almost sure it is to do with the browser cookies. 

It happens in incognito and on a new browser session.

**Comment by BeccaMelhuish** [comment]
@ssin1901 @ilmartyrk how many users do we think this is likely to affect? 

As if it's a significant number then there's two things to consider - one is the text, but the other is that getting a tour repeatedly popping up when you've already taken or declined it is really annoying for users..

**Comment by ssin1901** [comment]
@BeccaMelhuish I remember from the tests, that users complained about this.

However, we didn't measure longevity i.e if user gets the same notification on a different day (not every 5 mins). Is this possible to test?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Do you have an idea of how many users might be affected by this though? As if not many, I would just leave it for now.. 

(And yes I agree - in the tests it was clear it's annoying, and Meelika has confirmed this too, but as you say - the tests aren't realistic in this sense, as they condense several days/weeks into one hour).

**Comment by BeccaMelhuish** [comment]
@ssin1901 I wonder, is there any way we can use the tracking of clicks (i.e. the X or the skip or the 'take the tour'), to gauge to what extent it's actually recurring for users?

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk from my detailed analysis of the collected stats, it seems that the issue, while no doubt irritating is not going to affect a lot of users. 

We can keep it open but move it to a later phase.

**Comment by BeccaMelhuish** [comment]
@ssin1901 Thank you! I think we could close it even? And just make a new issue or re-open if we find out it's more important than we thought?

**Comment by BeccaMelhuish** [comment]
As it's a UX issue I will take the decision to close it :)
