### ISSUE TITLE
LOGIN: Necessary to log in again after registering?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1507]
@ssin1901 @ilmartyrk @kevincrepin In the interests of streamlining the process of accessing a topic or group for new users (which users have expressed as important in the research), I'm wondering: do we have to ask a new user to log in once they have just registered and verified their account. 

Currently the flow is like this:

- Follow a link
- Put in an email and password to register
- Verify the email
- Put in the same email and password to log in
- Arrive at the destination 

But seeing as there is a step after registering that requires them verify (higher security than our usual login process which doesn't), I'm wondering what benefit this additional step brings, and if we couldn't just log them in automatically after they have verified?

**Comment by ilmartyrk** [comment]
Related to onboarding and accessing the platform faster. Will have new issues created where we will try to use topic intro so that people get a better overview if they even want to go through the register flow. Closing this issue and will reopen if needed in the future
