### ISSUE TITLE
IDEATION: Enable the adding of images to ideas

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1508]
@ilmartyrk Am making a new high priority issue as a spin-off from [this one](https://github.com/citizenos/citizenos-fe/issues/1219), for what we agreed to do before the 'hard launch' comms of the ideation feature. 

I think the most minimal 'MVP' version to have before the comms, would be to add this button, so users can add a single photo added to the idea. 

![image](https://github.com/user-attachments/assets/b29f532f-bc41-43e7-a4ac-acf28fd11c69)

But (from the research) other things which would be desirable, if there's time, would be:

- The possibility to add multiple images, not just one. 
- The possibility to add images into the body of the text as well. (I.e. like we have in topic texts)
- The possibility to add images to idea replies, not just to the idea itself. 
- If it's a similar amount of work to enable attaching images as it is to enable attaching other documents (e.g. PDFs, something that also came up in the testing) then we could do that too. 

Do we need designs from @kevincrepin on the UX/UI of what happens after you click the 'Add image' button? I.e. the view for adding the image/s, and also how it looks once added, when someone is viewing the attached images, etc.?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish everything is possible, as the idea description and argument explanation work the same way and use the same markdown editor we can implement the same solution quite easily. I already tested the solution of adding an image with the button that is outside of the editors toolbar and it works, I will have to solve the image uploading part and also making the editor be in the "preview" mode so that the text wouldn't look weird for average user

**Comment by kevincrepin** [comment]
We have an example for attachments:
![Screenshot 2024-08-27 at 15 01 42](https://github.com/user-attachments/assets/1a1fa4d3-8615-4989-b8dd-d84627bab404)

@ilmartyrk : https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=2-8742&t=Xkizp56Otqv8zCDK-1


Choosing a file is done through the native OS so doesn't need design.

**Comment by BeccaMelhuish** [comment]
@kevincrepin Great, thank you! 

What about how it should look when the image is added though, i.e. in the published idea? A visual preview of some sort showing the image/s in thumbnail and then a way to open them up, and click through them if there's more than one?

**Comment by kevincrepin** [comment]
I'm thinking a bit that a thumbnail is no problem, but I would be inclined to open these in the most basic "open in a new tab" kind of way, because we are already in a popup with the idea. and this popup also has the arrows to go trough the other ideas. It would become messy and confusing to then also have a gallery lightbox open on top of this...

![Screenshot 2024-08-27 at 15 28 02](https://github.com/user-attachments/assets/7f88a0d6-840b-4aa2-9a16-19d6ee928dfd)

**Comment by BeccaMelhuish** [comment]
Not sure I've seen this UX anywhere, so might be a bit unexpected, but how about when you hover over a certain thumbnail it expands to a more visible size (in the same position as shown above, but bigger). But then when you click on the file name (and maybe also when you click on the thumbnail?) it opens full size in a new tab?

Or, that when you hover, an icon appears (e.g. magnifying glass), then when you click, it expands it to a more visible size? 

I guess on mobile it would need to be when you tap the thumbnail.

I feel like only opening in a new tab is quite inconvenient / a bit annoying for anyone viewing a lot of photos (which could be the case sometimes, if it's a very image based discussion).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin the solutuion is quite different from what I initially thought, but it will make the file handling a lot easier. And for mobile the image can already be 100% width

**Comment by BeccaMelhuish** [comment]
Nice, thank you @ilmartyrk! 

A few things from me:  

- The 'Add image' button is a bit oversized, should be the same height as the other: 

![image](https://github.com/user-attachments/assets/134a1f8f-73d6-4491-8c40-6fb1bc1c0bdf)

- When I had already added an idea, then went to edit idea, deleted the image, added a new image, then tried to 'update idea', I got this insufficient permissions error:

![image](https://github.com/user-attachments/assets/855376af-66d5-4faa-9ca4-f92d4c318474)

- Here I had added two images but only one appeared, was it meant to be working for multiple: 

![image](https://github.com/user-attachments/assets/ace6b526-9326-47de-9b80-311fb0740baa)

- When I went to upload an idea, one that I had previously tried to add was already there attached in the (what should be) empty new idea window: 

![image](https://github.com/user-attachments/assets/592dc43c-d79f-4773-86ed-a739ea4d016d)

- Could there be a bit more gap between the image and the filename:

![image](https://github.com/user-attachments/assets/ae31e22e-f15b-4c84-afc0-440236b9d289)

- The image popping up on hover feels a bit weird to me. A bit unexpected and can be easily done by accident. My idea had been rather that it would expand like so (sketch below) within the window, but that might be a bit odd/hard to use as well, especially if there are multiple images, as they'd be moving around. Will tag @kevincrepin to review. We could just keep it as Kevin originally suggested, that it opens in a new tab (rather than downloads), but maybe make the thumbnail quite a bit bigger, so you can get a relatively good idea of what the photo is of before you click to open? 

![image](https://github.com/user-attachments/assets/df8bf396-f669-401f-8770-f6759b9c0e19)

- Another one for @kevincrepin, when I was editing an idea then wanted to exit without saving, I accidentally clicked the top right X, rather than the bottom left X. Top right X closed both pop-ups at once, and left me quite confused/disoriented. Should the top right X disappear while the 'Edit idea' box is open, to avoid confusion? (As it sits just to the top right of the edit box - quite easily confusable). Or just leave it and keep an eye in future tests?

![image](https://github.com/user-attachments/assets/5705feca-2cab-45c1-b28c-434dcac51099)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish made some fixes and updates

**Comment by BeccaMelhuish** [comment]
Thanks @ilmartyrk! Checked and still a few things :)  

- The way the image pops up is preferable to the previous version, but it's still a bit unexpected, I feel it might make users jump :D  Hopefully @kevincrepin can review and see if he has any ideas or if we should just stick to making the thumbnails a bit bigger and opening in a new tab only. Maybe next to the image we can have a 'magnifying glass with plus' icon, that you can click to expand the image. And same with minus to make it small again? That way they'll be actively choosing to make it bigger rather than it happening to happen when they move their mouse over it. 

- When you click on the URL for the photo, it looks for a second in my browser like it will open in a new tab, but then it still just auto downloads. Can we have it open in a new tab, and then users can save it from there if they want to? (I think this was @kevincrepin's suggestion initially).   

- Added 1 image to an existing idea (in edit mode). Then went into edit again and added a second image. I showed in edit mode, but then once published there was still only 1:

![image](https://github.com/user-attachments/assets/2958ae57-326c-474f-88c5-5aaa3866438b)

And then when I go into edit mode, it still shows 2:

![image](https://github.com/user-attachments/assets/bd7876e7-1543-4f6b-aba7-b255132cbca6)

- In another case, I made a new idea with 1 image, but when posted it wasn't there:

![image](https://github.com/user-attachments/assets/169690db-e9bd-41fa-8d96-8d758af85ed9)

Again when I went into edit mode it was:

![image](https://github.com/user-attachments/assets/bbe78054-8a17-475e-9267-90abb36c1c2e)

- Went to try making a new idea again, and found the image that I'd tried to add above was already attached:

![image](https://github.com/user-attachments/assets/423eed9f-da7e-413a-aad8-f1f4e7990a64)

- Tried deleting the above idea, and then adding one, and when publishing the idea the photo wasn't there. Also tried again with a new idea, again the photo didn't publish. (So just confirming that the problem seems to be every time with a new idea, not occasional):

![image](https://github.com/user-attachments/assets/80d0cdab-b234-40f2-86bc-881f9c913f62)

- Can we have the image show up when in edit mode, rather than only the URL?

![image](https://github.com/user-attachments/assets/7a970b0f-0e5d-4365-965e-c9a2311f7af4)

- I'm getting this at random points when testing (not clear why/due to what it's popping up):

![image](https://github.com/user-attachments/assets/8251a032-bbae-431a-b0cd-045f6798b4ac)

- It would be great to be able to add images to replies too, but I guess that's a lot more work so can make a separate issue for that as lower priority for now?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted more fixes

**Comment by BeccaMelhuish** [comment]
Seems to be working much better now! 

Though I got this error again, it just randomly popped up when I was looking and thinking, not doing anything: 

![image](https://github.com/user-attachments/assets/f024bbbb-cb0d-438b-8024-ff4f70f1a045)

And re deleting images, there were 2 initially here (below). I went in to edit mode to delete one and it disappeared fine, then went in to delete the next one and it was still showing. When I went out and back into the idea the second image had also been deleted, so I think this was just an issue with it not displaying what had actually happened? Is there a way to make sure it always updates? 

![image](https://github.com/user-attachments/assets/aeb2a9b1-cb47-44a1-b327-c1e394e698ad)

And then if possible to add the image thumbnail in edit mode too, so they can see the image they've added before they post it, but if that's a big job I'll make a separate issue? 

![image](https://github.com/user-attachments/assets/f94fbbcf-40fd-4407-8854-1f298d602704)

**Comment by kevincrepin** [comment]
I still think opening them in new tabs is fine in this context. Especially when there are multiple then in that way you could at least have them all open at once. Otherwise if we open it within the platform you have to open and close them one by one.

The thumbnail can be a bit bigger, for example 80px wide. And I don't think this hover interaction really works, it's a bit unexpected behaviour, so I would not do this. Just (bigger) thumbnail, filename and open in tab (not download as it does now). It's not a bad idea with the expand/minimise magnifying glass, but for me the problem is that all of this is crammed into this small popup window. If it's an image with a bigger size (some diagram or smt detailed), then we should still allow to view the full size, so they would still need to be able to download it or open it fully in the browser.

---

About editing the idea and still having the idea open behind it: I would approach this idea popup the same as the other content when an overlay is opened, namely darken it. We already have this darken layer over the topic behind it, so adding another one is maybe a bit weird, but what if that darken layer is on top of the idea popup when the edit overlay is open? Then this idea popup will also feel "disabled".

---

I also had the issue when I posted my idea that the image didn't show until I closed that idea and opened it again, so same issue as Becca has.

**Comment by BeccaMelhuish** [comment]
OK thank you @kevincrepin! Let's do it like that then - no 'magnifying hover', just 80px wide thumbnails and open in tab (not download). 

Having the darker layer over the idea during edit also sounds a great solution :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin downloading is caused by your browsers default behavior.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK, there's no workaround to fix it? To me it's really not a user-friendly solution..

@kevincrepin Does this change anything from your side?

**Comment by kevincrepin** [comment]
Yep, I agree if this automatically downloads the image, that's no good.

Then let's open it within the popup, with a possibility to close again and also to download the image.

So default looks like this:
![Screenshot 2024-09-13 at 11 04 50](https://github.com/user-attachments/assets/56ca76e5-b17b-4f21-8d92-d8fc07e938af)

And when the image is opened like this:
![Screenshot 2024-09-13 at 11 04 44](https://github.com/user-attachments/assets/475a8dbf-5a7c-409b-8284-03567107aefc)

@ilmartyrk you can find this here: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=13338-115399&t=dkotUyTY3qUxWrQ8-1

**Comment by ssin1901** [comment]
@BeccaMelhuish here is the final view
1. In screenshot 1, the user is adding several images

<img width="1343" alt="screenshot1" src="https://github.com/user-attachments/assets/4199cbaa-3b6f-4399-9f29-71e1aab351fa">

2. In screenshot2, the idea with attachments has been clicked on

<img width="1346" alt="screenshot2" src="https://github.com/user-attachments/assets/6d88e617-6add-4f63-a095-f43585b3d0f6">

3. In screenshot3, an attachment is expanded

<img width="1338" alt="screenshot3" src="https://github.com/user-attachments/assets/2ae7c0f0-d561-4259-b969-445a8e843a3b">

**Comment by BeccaMelhuish** [comment]
@ssin1901 @ilmartyrk something strange happened for me when I tried it:

- I went into an existing idea and into 'edit'
- I added 3 photos at once
- Added 2 more (at once), I think at that point it was OK too
- Added 3 more (at once) and one of them must have been too large as I got an error (and I see one of the images is missing)
- I think it was at that point that the images doubled up in a random order - I only added 1 of each image, but as you see below there are 2 of each. (Except for two of them, which only show up once). 
- When I then clicked 'Update idea', it seemed like none of the photos were added 
- However after making this issue I see that they were added (all of them including the duplicates), so it must have just taken time for the photos to load (I will make a separate issue suggesting we have a 'Loading' indication) 

![image](https://github.com/user-attachments/assets/2581a24e-e5fb-43d5-83e9-32790438c09b)

This is on desktop, Windows, Chrome

**Comment by BeccaMelhuish** [comment]
I then tried adding a smaller image (to the same idea) to test how it will look expanded, and it looked like it was added in the edit mode, but when published I got this, and the image hadn't been added:

![image](https://github.com/user-attachments/assets/e38e1b79-aacc-412c-8962-c47d94765bc6)

**Comment by BeccaMelhuish** [comment]
Made 3 spin-off issues re some UX things:

- Scroll bar missing on published and too narrow in edit: https://github.com/citizenos/citizenos-fe/issues/1601
- Loading images: https://github.com/citizenos/citizenos-fe/issues/1602
- Image filenames lost and spammy on download: https://github.com/citizenos/citizenos-fe/issues/1603

The only one that seems like it would be best to fix before launch if possible would be the scroll bar one, if it's a quick fix, so I added to ideation project. The other two can stay in Issue Priorities for now I think :)

**Comment by BeccaMelhuish** [comment]
Sorry just saw I didn't move this to in progress for the errors

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I tried to replicate the issues, but I could not. Duplicates  might have happened because you tried to upload the images again. I would need more info, browser , image files you used (types, size etc)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk browser was Chrome (on Windows) and I'm fairly sure I didn't try to upload the same images again, I'll try to (train wifi depending) send you and @ssin1901 the photos I was uploading by emails. Maybe @ssin1901 can test with these images, adding them in a similar  way to what I did - e.g. adding 3, then 2 more, then 3 more (the last batch including the oversized one, which I think is when the duplication happened). But I guess if it's mostly working fine (i.e. is all showing as working OK in @ssin1901's tests) then we're probably fine for launch, as presumably users will be adding less images and not in multiple edits like this, I assume.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 I also tested it on the test app with the same steps, but with my own images and it worked for me at least so there is some other factor that is causing it, but not sure what it is at this point

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK yes. Did you also include an image that was too large in the final 'batch'? My feeling was that it was at the point the 'file too large' error came up that the duplication also happened, but they may be unconnected of course.. 

Will move it to testing in case @ssin1901 is able to duplicate it on other devices :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish  I could replicate the issue in live but not in test. Although in test, the images take a while to appear but they do appear and there is no http error. 

Adding a 5MB image and then adding more images has been tested here

https://drive.google.com/drive/folders/1wBHq1LewZ5BsqQm8b2Pm-J5X7N6W-qsL?dmr=1&ec=wgc-drive-globalnav-goto

@ilmartyrk I guess the changes need to be pushed to live?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish yes, I also had a too large image file in the batch, tried in different combinations also and it was just skipped without any further issues for me

**Comment by BeccaMelhuish** [comment]
@ssin1901 when you managed to replicate the issue, was that the duplication issue as well, or just the http error?

**Comment by ilmartyrk** [comment]
@ssin1901 test and live are in sync, so the issue comes from something else

**Comment by ssin1901** [comment]
@ilmartyrk ah, then in that case I can reproduce the error in live. 

It is in this topic https://app.citizenos.com/en/topics/3e798cad-97ef-4fc8-8f51-0bee8890de2d#ideation and the idea is called Add ideas.

Screen recording of the error
https://drive.google.com/file/d/1HgofiUYYmPbUgs0EwvdJoojNl3BJ6NHB/view?usp=drive_link

**Comment by ssin1901** [comment]
@BeccaMelhuish no duplication error as far as I could see. However there was an HTTP error and the images that were added prior to receiving the error were not saved. 

You can also check here https://drive.google.com/file/d/1HgofiUYYmPbUgs0EwvdJoojNl3BJ6NHB/view?usp=drive_link

**Comment by ssin1901** [comment]
@Becca Melhuish @ilmar I am just wondering whether the issue is related to the upload limit. I can only replicate the issue with 10+ images but with 6 it worked fine, even after uploading 13.3 MB image.

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish I checked and there is a limit of 10 images to be added on the API side, so this might be one of the causes, I will add a limit to the FE side too

**Comment by BeccaMelhuish** [comment]
Ah good, will we have a notification to that effect then? So when they try to add more than 10 images: "Maximum 10 images allowed per idea." But I guess this is fairly low priority in terms of pre-launch fixes, as unlikely people will add more than 10.

Is this the only reason the error is happening, or you think there might be other reasons too @ilmartyrk?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 I suggest we close this issue for now and create a new ones if needed as it has become a long thread again and addings images to ideas has been added to our live app

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK good plan yes - I'll make a new issue and put it to QA to see if it's still an issue/to what extent :) 

https://github.com/citizenos/citizenos-fe/issues/1666
