### ISSUE TITLE
IDEATION: Slicker formatting UX for ideas

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1509]
@ilmartyrk I didn't note this in the meeting, but I believe this is one of the high priority things that @MeelikaH suggested should be fixed before the launch comms (and I would agree). 

Currently when you format an idea, you see the code for that formatting. E.g. this is how it looks if I try to make italic bullet points: 

![image](https://github.com/user-attachments/assets/b2eb94d8-7a88-42d7-a348-2d354c32764b)

Can this be fixed, so that rather than seeing the code, you see the formatting as it will look when published?

**Comment by BeccaMelhuish** [comment]
I'll also add this bug here, as it's related - the selected text moves when you select a formatting option, and the asterisks from the bold remain after you've removed the bold:

https://www.loom.com/share/ca10ffc2ec9546fc8d7d430a65db1d10?sid=b1088f4e-0621-41d3-9015-65443e8e334e

**Comment by BeccaMelhuish** [comment]
@ssin1901 I think we can close this one as it's fixed via this? https://github.com/citizenos/citizenos-fe/issues/1310

Closed but will leave it in testing in case :)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk I think this is ok for the launch. Moving to Done.
