### ISSUE TITLE
IDEATION: Adding URLs to ideas

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1510]
Making a spin-off issue from [this issue](https://github.com/citizenos/citizenos-fe/issues/1219), and adding high priority as we agreed to do it before the launch comms. 

Currently you can add an URL to an idea like this:

![image](https://github.com/user-attachments/assets/c019550c-cd5e-4f50-866e-506aaff49130)

But it would be preferable to be able to add links more neatly as hyperlinks instead.

If it is technically too difficult, to add as a hyperlinks, then maybe it could be a sort of attachment? 

@ilmartyrk @kevincrepin what do you think would work both technically and UX-wise?

**Comment by kevincrepin** [comment]
Made a simple prototype how this could work if @ilmartyrk agrees: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?page-id=3094%3A111670&node-id=14219-104511&viewport=-18559%2C-22634%2C0.5&t=dxW3BDhqpMf1dusH-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=14219%3A104511

**Comment by BeccaMelhuish** [comment]
@ilmartyrk checked it and all working fine except:

- link needs to open in a new tab, currently it opens in the same one
- the link button and the bullet buttons don't seem to work as well as all the others - for me, if I click right in the centre of the buttons nothing happens, only when I click nearer the edge. Takes me a few clicks to get it to work.  

![image](https://github.com/user-attachments/assets/c07abcba-7a72-44f8-a27c-5b213ff92eba)

**Comment by BeccaMelhuish** [comment]
Check and all good, moving to Done :)
