### ISSUE TITLE
TOPICS: In a public topic/group 'Back to my topics/groups' should be 'Back to public topics/groups'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1525]
As Kevin pointed out on Slack recently, when you go into a public group currently, the back button is 'To my topics'. It should however be 'To public topics'. 

(@kevincrepin In the designs the wording is 'Back to', but on the platform currently it is just 'To'. But just 'To' seems to make more sense to me, as it won't always be 'Back', as they haven't always come from there?)

![image](https://github.com/user-attachments/assets/d30a201f-7328-46be-8e6c-681a0e7ef44c)

I just checked the others too, and this public groups one has the same issue. When you go into a public group, it is currently 'To my groups', but should be 'To public groups'.

![image](https://github.com/user-attachments/assets/4c7119f5-c319-4003-a2c3-1113b6be160f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish so will we add the "Back to" or not, if I understand correctly from @kevincrepin back is not always back so might it not become a little confusing to users as also mentioned [here](https://github.com/citizenos/citizenos-fe/issues/547#issuecomment-1918655591).  From the functionality point the fix is quite easy to do with est 15mins.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I agree yes let's just stick with 'To public topics' and 'To public groups'

**Comment by BeccaMelhuish** [comment]
Checked and all seems good to me, @ssin1901 happy when you are :)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk fix is implemented in Test Environment and works well. 

That being said, should we mark it as Done once it's been deployed?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 made the 'ready for live' label we discussed and added it to this one :)

**Comment by ssin1901** [comment]
@BeccaMelhuish implemented in topics (screenshot1) and groups (screenshot2). Moving it to Pre-Live with status closed.

![Screenshot 2024-11-24 at 23 59 26](https://github.com/user-attachments/assets/98a57251-bec1-43d8-b421-ddde2ee6e6af)

![Screenshot 2024-11-25 at 00 10 49](https://github.com/user-attachments/assets/74096e34-89bf-4d45-a499-7eae021fa7bf)

**Comment by ssin1901** [comment]
@BeccaMelhuish ready for live label added by Ilmar already. Will move to Done once implemented in Live

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 moving this one back to 'pre-live' so it can be deployed to live, as it got automatically sent to done :)
