### ISSUE TITLE
IDEATION: Unnecessary notification

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1539]
I think we don't need this notification now that we show the idea after they have posted?

![image](https://github.com/user-attachments/assets/ba47b979-1b34-4cab-b347-d04ecd82cbc9)

**Comment by ilmartyrk** [comment]
Est dev time 5 min.

**Comment by BeccaMelhuish** [comment]
Checked and all good so moved to Done, guess it doesn't need further testing :)
