### ISSUE TITLE
User cannot add a new profile picture

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#155]
**What is the problem?**
When the user tries to change their profile picture with a 240 KB image, they click save and nothing happens (screenshot attached). <img width="1276" alt="Screenshot 2023-06-19 at 23 01 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/de6be03e-12e7-425b-86c1-f4f281c73c7b">

In Safari, the save button simply does nothing, but Chrome throws up this error (screenshot attached)

<img width="1440" alt="Screenshot 2023-06-19 at 23 08 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3af21034-0d2e-406a-89c2-f99977e509cf">

Additionally, the original profile picture seems to be distorted.

**Why is this a problem?**
1. The user is unable to save a profile image and in general the profile feature seems to be not working.

**Possible solution.**
1. User should be able to save a new profile picture without errors.
2. Profile picture in the user dashboard should be a circle.

**Comment by anettlinno** [comment]
Triage 78. After pressing "Save" button, we will display success message (green line) with the message: "Successfully updated"

PS! @ssin1901 picture is changed in the system but for seeing it in the left menu, you need to reload this page.
In redesign project we don´t display profile picture in the left menu, but in the dashboard. Ilmar tested that picture is uploaded in redesign after changing it. So, we will not put any effort for improving it in the current version.

Est.dev.time 5 min. Sending it To Do.

**Comment by ssin1901** [comment]
@ilmartyrk on Safari as well as Chrome the image is still not a circle (see screenshot)

<img width="151" alt="Screenshot 2023-08-30 at 15 15 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7de21e7d-8410-4ef5-8085-5829c5f098b4">
