### ISSUE TITLE
MISC: Help guidance / tooltip texts to add to translation strings 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1559]
@ilmartyrk As discussed, here is a list of texts to add to the translation strings so that @oksks could already start the translations. I'll make separate issues re where and how to actually add them :) 

**Topic text**
The main topic content goes here. Add any instructions, information or context that participants may need to engage in the topic.
https://github.com/citizenos/citizenos-fe/issues/1562

***

**Topic roles** 
**Admins** can access all settings to manage the topic. **Editors** can edit the topic content (text, images, attachments) and the tags (categories, language, location). **Participants** can participate in whichever topic phase is open. 
https://github.com/citizenos/citizenos-fe/issues/1564

***

**Group roles**
**Admins** can access all settings to manage the group. **Members** can access the topics to which the group has been invited, with whatever rights they have been assigned for each topic. In public groups, members can also invite and share the group. 
https://github.com/citizenos/citizenos-fe/issues/1566

***

**Group permissions for topic access**
This will give all members of the group the selected role within the topic, unless you individually assign them a different role from the topic's 'manage participants' section.

**Admins** can access all settings to manage the topic. **Editors** can edit the topic content (text, images, attachments) and the tags (categories, language, location). **Participants** can participate in whichever topic phase is open.  
https://github.com/citizenos/citizenos-fe/issues/1494
https://github.com/citizenos/citizenos-fe/issues/1565

***

**Topic language**
This gives an indication of the working language of the topic (i.e. the topic text, participant contributions, etc.). The platform language can be set separately by each individual user.  
https://github.com/citizenos/citizenos-fe/issues/1561

***

**Who can add topics**
In a private group, anyone can add topics. In a public group, only admins can add topics, but anyone can 'Request to add topics' via the button on the group's page.
https://github.com/citizenos/citizenos-fe/issues/1211

***

The delegee won’t know you’ve delegated to them, but their vote will be counted twice. You won’t get to see how the delegee voted. 
https://github.com/citizenos/citizenos-fe/issues/1560

***

By joining this group, you agree to your email address being made visible to the group's admin(s).
https://github.com/citizenos/citizenos-fe/issues/1558

**Comment by ilmartyrk** [comment]
- [x] #1562 
- [x] #1564 
- [x] #1566 
- [x] #1494 
- [x] #1565 
- [x] #1561 
- [x] #1211 
- [x] #1560 
- [x] #1558

**Comment by BeccaMelhuish** [comment]
Removed the high priority now that the strings are all added, though would be nice to have the topic roles one if there's time :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk please see this issue for the 2 alignment issues I mentioned, that were more than just minor polishing :) 

https://github.com/citizenos/citizenos-fe/issues/1604
