### ISSUE TITLE
Why is there an exclamation point next to an update in the activity field

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#156]
**What is the problem?**
I created a topic, enabled voting and then sent it to follow up but in the Activity Feed I see that there is an exclamation mark to the left side of this (screenshot attached)

<img width="794" alt="Screenshot 2023-06-20 at 13 12 20" src="https://github.com/citizenos/citizenos-fe/assets/72747107/70076904-544c-4701-84f0-119201415090">

**Why is this a problem?**
To my mind the exclamation mark in red is associated with a user being removed or a topic being deleted. This confuses me about the status and outcome of my topic.

**Possible solution.**
Maybe topics in follow up should have their own icon? PS - @ilmartyrk luckily you are invited to this topic so you can also see the content/status.

**Comment by anettlinno** [comment]
Triage 87. Activity feed will go through extreme makeover in the redesign project. As this is not critical bug, let´s not put any effort finding and fixing this right now. 
Closing this issue with no further action.
