### ISSUE TITLE
TOPICS: Add tooltips for topic roles

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1564]
Please add the following tooltip text in all places where topic roles are selected:

**Topic roles**
**Admins** can access all settings to manage the topic. **Editors** can edit the topic content (text, images, attachments) and the tags (categories, language, location). **Participants** can participate in whichever topic phase is open.

- [x] In the add co-creators pop up:

![image](https://github.com/user-attachments/assets/6af85cda-4f6e-4c26-aec4-e232911601ba)

- [x] In the invite & share link rights for topics:

![image](https://github.com/user-attachments/assets/b80dc47b-0b16-4328-a5e0-52c57c19c1e7)

- [x] In the Manage participants box:

![image](https://github.com/user-attachments/assets/b7300f89-09b0-41b6-8a9c-48266f8e76eb)

**Comment by BeccaMelhuish** [comment]
Checked and all are showing for me but will leave in testing so hopefully @ssin1901 could add this one the the tests and check the alignment is OK on different devices? :)

**Comment by ssin1901** [comment]
@BeccaMelhuish updated the screenshots in the folder to reflect the fixes. Moving to Done.
