### ISSUE TITLE
GROUPS: Add tooltips for group roles

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1566]
Please add tooltip text about group roles to all places where group roles are selected:

- [x] In the invite and share box for groups

![image](https://github.com/user-attachments/assets/f42d8b58-ca28-462b-9e9a-4cad881eede7)

- [x] Next to the 'Role' heading on the 'Members' tab for Groups

![image](https://github.com/user-attachments/assets/b6148077-39f3-4beb-b9ff-63d0c7f62ed0)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish we have texts for topic roles ,but can you provide text for the group roles  too?

**Comment by BeccaMelhuish** [comment]
Yes this is the text for here :) 

**Group roles**
**Admins** can access all settings to manage the group. **Members** can access the topics to which the group has been invited, with whatever rights they have been assigned for each topic. In public groups, members can also invite and share the group.

**Comment by BeccaMelhuish** [comment]
Checked, all good, moving to Done :)
