### ISSUE TITLE
TOPICS: 'Edit topic' missing from some topics' manage menus

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1577]
@ilmartyrk @ssin1901 It's a topic in test environment that's in discussion phase, but has had an idea gathering process already completed: 

![image](https://github.com/user-attachments/assets/2cc60a2d-fc17-445f-9e96-1208d967ebb6)

This is the topic: https://test.app.citizenos.com/topics/join/IXphID9nCJYA

Same thing happening for me in this topic too: https://test.app.citizenos.com/topics/join/IXphID9nCJYA 

Kind of high priority as it makes it hard to test, and also if the bug may be carried over when updates are made live? Will add the label as such and remove if you disagree :)

**Comment by BeccaMelhuish** [comment]
Ah OK, I see the same problem in live (in same situation - topic in discussion phase following an idea gathering phase), so definitely high priority :) 

Will add to idea gathering no status so we can discuss 

![image](https://github.com/user-attachments/assets/990ad300-d018-4621-ba1d-61ceb38b60e5)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk could replicate. In my scenario, adding the Discussion led to the removal of the edit button (see screen screenshot 1 and 2).

<img width="1231" alt="Screenshot 2024-09-23 at 11 44 20" src="https://github.com/user-attachments/assets/3ae48156-7bc4-440e-8b36-78825e4da425">


<img width="1221" alt="Screenshot 2024-09-23 at 11 44 45" src="https://github.com/user-attachments/assets/3f976ecd-7cf5-4135-826b-482ba40997a3">

**Comment by ssin1901** [comment]
Fixed, thanks @ilmartyrk 

@BeccaMelhuish I'm moving it to Done (screenshot1)

<img width="1228" alt="Screenshot 2024-09-23 at 12 40 48" src="https://github.com/user-attachments/assets/b9218b26-cc2a-4c91-84ec-ca9c4f369d3a">
