### ISSUE TITLE
Czech language works differently than others

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#158]
**What is the problem?**
When the user changes the language from English to other languages (for example Spanish, screenshot below) the menu is more or less correctly translated. This does not happen with the Czech language (screenshot attached).

<img width="1336" alt="Screenshot 2023-07-02 at 22 05 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0ebdef6c-b868-43de-81bc-8ef98d9e3fa7">

<img width="1330" alt="Screenshot 2023-07-02 at 22 05 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e7458b49-38ca-4924-a11c-f0c9d35e284c">

**Why is this a problem?**
Negatively affects users who want to translate the platform to Czech

**Possible solution.**
Either remove the option or fix the translation

**Comment by anettlinno** [comment]
Triage 87. Needs some investigation, approximately 30 minutes. Sending it To Do.

**Comment by ilmartyrk** [comment]
Translator had translated some references that were hidden and should never have been translated, this broke the string loading and made it fall back to default english

**Comment by ssin1901** [comment]
@ilmartyrk testing and it works now
