### ISSUE TITLE
NOTIFICATIONS: Remove from the side menu

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1580]
**What is the problem?**
Remove the Notifications from Topic activity (screenshot1)

<img width="1422" alt="Screenshot 2024-09-18 at 12 50 05" src="https://github.com/user-attachments/assets/cedf5194-4f62-477e-b090-33f1b6a80351">

**Why is this a problem?**
This feature causes the page to crash #1496

**Possible solution.**
No need to have it here as it is already (screenshot2)

<img width="1423" alt="Screenshot 2024-09-18 at 12 56 10" src="https://github.com/user-attachments/assets/9034bec3-649f-42e9-a1da-59d494cb6804">

**Comment by BeccaMelhuish** [comment]
Though Ilmar when you come to this, please see @ssin1901's [comment here](https://github.com/citizenos/citizenos-fe/issues/1496#issuecomment-2370581977), as seems it is now working (not crashing) in the test app? 

I just tried clicking it in live too, and for me it also didn't crash :) 
(Desktop, Windows, Chrome)

**Comment by ssin1901** [comment]
Closed as it's working now

**Comment by BeccaMelhuish** [comment]
Just making a note that we decided to keep it in testing for a while, so Sara can test every now and then to be sure it's fully fixed :) 

Removing from ideation project

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk Notifications is present in the test environment (screenshot1) and causing the page to crash (see screenshot2)

<img width="1367" alt="Screenshot 2024-11-20 at 15 43 23" src="https://github.com/user-attachments/assets/1010642b-80ef-4db6-a043-02b4f6adcdb4">

<img width="1361" alt="Screenshot 2024-11-20 at 15 42 14" src="https://github.com/user-attachments/assets/ba9f74df-f00b-43ab-934f-ba0739836c6f">

**Comment by BeccaMelhuish** [comment]
@ssin1901 ah that's a shame. OK let's remove it then as we initially decided before it fixed itself! Will put to ready for dev high priority :)

**Comment by ilmartyrk** [comment]
estimated dev time 5 min

**Comment by BeccaMelhuish** [comment]
Moving to Done as it got merged to live
