### ISSUE TITLE
MISC: 'This is a test environment' pop-up very frequent and pushes down content

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1586]
@ilmartyrk @ssin1901 As discussed on Slack, the pop-up is a bit overactive, as it pops up all the time (going into a topic, adding a new idea, etc etc). It also pushes the content beneath it down, which makes the UI suddenly jump and the button you may have been about to click on move. 

Could it be only on arrival into the platform (after logging in), as it used to be? 

Am adding 'pre-UX texts' as if we do have one test later this month (as hoped, but not yet scheduled), would be good to have it fixed before then if possible. Will put it into 'ready for dev' column in ideation project as @ilmartyrk already mentioned he'd look into it :)

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish added a cookie for hiding the notification

**Comment by ssin1901** [comment]
This issue no longer bothers me because I wrote a function in Playwright to close the notification before the screenshot is captured.

And Ilmar's fix would prevent it from becoming an issue for the manual testers. So moving it to Done.
