### ISSUE TITLE
AF: String not being retrieved for Adding Attachment to Idea

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1588]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

String not retrieving values for adding an attachment to idea (screenshot1)

<img width="1400" alt="Screenshot 2024-09-23 at 12 32 43" src="https://github.com/user-attachments/assets/6730b899-f068-4d6e-b904-4faa5ad48879">

**Why is this a problem?**
Not urgent but should be fixed before the launch

**Possible solution.**
String should be retrieved

**Comment by BeccaMelhuish** [comment]
Will add high priority seeing as it's a pre-launch one :)

**Comment by ssin1901** [comment]
Fixed and closing (screenshot1)

<img width="1339" alt="Screenshot 2024-09-25 at 21 56 23" src="https://github.com/user-attachments/assets/d8ac3d44-6a5c-467e-9036-f34470bdb863">
