### ISSUE TITLE
Duplicate text in invitation expires

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#159]
**What is the problem?**
When the user goes to Invite users and adds a user, the text "Invite expires: in 14 days" has a duplicate 14 days (screenshot attached)
<img width="604" alt="Screenshot 2023-07-03 at 01 45 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/906505ad-408b-47bf-8d57-12fe3caa3577">

**Why is this a problem?**
Confusing for the user and makes them think that the web application is not working the way it should.

**Possible solution.**
Duplicate "14 days" should be removed

**Comment by anettlinno** [comment]
Triage 78. Easy fix, 2 min. Sending it To DO.
