### ISSUE TITLE
BUG: Idea gathering notifications not being received

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1594]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

User Sara did not receive updates that ideas had been added for this topic https://test.app.citizenos.com/en/topics/c722b70e-2963-4da9-bf09-cb9b417e5727 even though topic settings were as follows (screenshot1) and user Dave had added 3 ideas

<img width="1341" alt="Screenshot 2024-09-24 at 23 26 02" src="https://github.com/user-attachments/assets/c628efa6-a69a-46cf-8647-f04802fc9634">

**Why is this a problem?**
Notifications that a new idea had been added not received

**Possible solution.**
Notifications that an idea has been added should be received. @ilmartyrk we can close the issue if the email functionality is not in place yet.

**Comment by BeccaMelhuish** [comment]
I will close this one as we have it covered here: https://github.com/citizenos/citizenos-fe/issues/1212
