### ISSUE TITLE
VOTING: Topic invitation is misleading

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1595]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

Users invitation indicates that they can participate in idea gathering and discussion in a voting topic, but they cannot have discussions or add ideas in a voting topic (screenshot1)

<img width="1384" alt="Screenshot 2024-09-25 at 13 24 12" src="https://github.com/user-attachments/assets/dd536264-5a2d-41a0-a17a-4d334b1c8851">

**Why is this a problem?**
Confusing to the users.

**Possible solution.**
@BeccaMelhuish @ilmartyrk am I correct that this is the wrong topic invitation for this kind of topic (voting topic)?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish please create a more generic copy for the topic phases and actions description

**Comment by BeccaMelhuish** [comment]
@ssin1901 It's a bit tricky to create a text that works regardless of what phases are included, but I think this below would work. Technically if it's just a voting topic there's actually no way to 'engage with others', unless you count voting as engaging with the admin on the question they raised.. But I think that's OK. 

"Participate in the topic, giving your view and engaging with others". 

@ssin1901 I'll wait for a second opinion on it from you and then update it in the strings :)

**Comment by ssin1901** [comment]
@BeccaMelhuish I had a think, and from a user perspective what you suggested is probably the least confusing of the "generic" topic texts. 

So green light from me!

**Comment by BeccaMelhuish** [comment]
@ssin1901 Updated in the strings! I'll put to 'In progress' then once @ilmartyrk has merged it or whatever needs to happen to make it live, it can go to QA :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 merged the translations, moved to QA

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish seems to be implemented (screenshot1). Moving to Done.
<img width="1386" alt="Screenshot 2024-11-12 at 13 31 31" src="https://github.com/user-attachments/assets/77544878-816f-416e-8e3b-55325c2809df">
