### ISSUE TITLE
Remove "Company" from registration fields

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#160]
As discussed on Slack with @anettlinno and @ssin1901, we should remove "Company" from the registration fields: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fd39a416-6c8a-4907-b86e-e62a0a51c991)

**Comment by ssin1901** [comment]
This has been renamed Organisation (see screenshot1, screenshot2). Closing this issue and let's make another issue about Organisation if it comes up.

<img width="1242" alt="Screenshot 2024-02-19 at 14 10 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c85ca1fd-44b7-47c7-807d-4ccadb31f06e">

<img width="1440" alt="Screenshot 2024-02-19 at 14 10 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/61ae755d-65be-4593-b5fa-cf846e0aa636">
