### ISSUE TITLE
IDEA GATHERING: Italicisation doesn't work in Preview

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1600]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

In Preview, italicisation doesn't display properly. 

<img width="1342" alt="Screenshot 2024-09-25 at 22 02 49" src="https://github.com/user-attachments/assets/acba9a4a-3184-487e-bf7b-7a459ab192d8">

**Why is this a problem?**
Related to #1509 

**Possible solution.**
In Preview, should be italicised. Not have _ view

**Comment by ssin1901** [comment]
Just wanted to add that it worked just now.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 moved this to ready for dev in ideation, in case is a quick fix can be sorted for launch :) 

(As I feel like if preview doesn't actually show the preview correctly, users will struggle to understand what it's for)

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish it is broken because the formatting is broken. the underline tags work per line
