### ISSUE TITLE
MISC: 2 x tooltip alignments on mobile need fixing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1604]
@ilmartyrk @ssin1901 

- [x] **'Add to group'** tooltip - see below. (Was from @ssin1901's test screenshots - I guess this was in topic create flow, and I guess the same in each different view - different topic 'types', edit or create).  

![image](https://github.com/user-attachments/assets/63a40c60-fac5-4405-9b87-a007612ae5fe)

- [x] 'Group roles' tooltip - very close to delete button. Seems it would be hard to differentiate between which you are tapping on? 

![image](https://github.com/user-attachments/assets/b0e75271-dd41-4664-84b3-4cef89fcc003)

**Comment by ssin1901** [comment]
@BeccaMelhuish here are the updated mobile screenshots! If fine, please move to Done

![Simulator Screen Shot - iPhone 14 Plus - 2024-09-26 at 14 34 17](https://github.com/user-attachments/assets/c3427cc3-65f3-4b65-8c4b-142c7b20466f)

![Simulator Screen Shot - iPhone 14 Plus - 2024-09-26 at 14 35 35](https://github.com/user-attachments/assets/6e0563e5-d187-4019-b073-7dfda01afeb6)

**Comment by ssin1901** [comment]
@BeccaMelhuish updated the screenshots in the folder to reflect the fixes. Moving to Done.
