### ISSUE TITLE
TOPIC: Preview misaligned when inline image is added

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1606]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

If an inline image has been added, the Preview is misaligned in Google Chrome Desktop (screenshot1)

<img width="1141" alt="Screenshot 2024-09-26 at 11 45 04" src="https://github.com/user-attachments/assets/cd05af56-5d4e-4fc3-b5fb-171a19903e2b">

**Why is this a problem?**
Not urgent, looks okay in published mode

**Possible solution.**
Preview should be aligned like this (screenshot2)

<img width="1150" alt="Screenshot 2024-09-26 at 11 48 55" src="https://github.com/user-attachments/assets/3a6542af-a821-458d-9212-36233ee42b1b">

**Comment by ilmartyrk** [comment]
@ssin1901 I don't understand what is the issue here?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Am I right in thinking that this edge I've highlighted yellow is the left hand edge of the browser window? So this issue is that topic header etc is all shifted over to the left? 

![Image](https://github.com/user-attachments/assets/40aa1a34-ddda-4c93-ac59-ac1c42b82ada)

**Comment by BeccaMelhuish** [comment]
I think this one can just be in Issues Prioritisation though, not ideation - as no need to fix urgently?

**Comment by ssin1901** [comment]
@BeccaMelhuish issue is fixed (screenshot1) and you are correct, it was the corner that was misaligned

![Image](https://github.com/user-attachments/assets/a7b56432-b476-4795-be25-8d5c29b27d6d)
