### ISSUE TITLE
TOPIC: Editing topic in draft leads to topic status error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1609]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

I was editing this topic https://test.app.citizenos.com/en/topics/edit/9027266b-2527-4a9a-9e2d-3b0056911465#info which was saved in draft. While trying to save the edits, I got this error (screenshot1)

<img width="1347" alt="Screenshot 2024-09-26 at 11 53 11" src="https://github.com/user-attachments/assets/a586f17e-4a9a-44f8-9c8e-87403835dbff">

**Why is this a problem?**
Could not interact with the topic after the error message was received

**Possible solution.**
Should not receive error messages

**Comment by ssin1901** [comment]
Also got the error with this topic (https://test.app.citizenos.com/en/topics/edit/eb07ef6e-aaf2-44d6-b913-501dc151b6cf#settings)

**Comment by ilmartyrk** [comment]
@ssin1901 what type of topic were you creating (idea gathering, discussion, voting)?

**Comment by ssin1901** [comment]
@ilmartyrk idea gathering

**Comment by ssin1901** [comment]
@ilmartyrk issue is no longer there. Might have been related to #1608 which was fixed. Should I close?

**Comment by ilmartyrk** [comment]
@ssin1901 oh yes, that might have been the case as it opened in the wrong edit view, I'll close this issue then
