### ISSUE TITLE
Voting results and options not displayed properly in custom vote when there are many choices

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#161]
**What is the problem?**
Custom Voting results are not displayed properly. In the following use case 51 options were added in custom voting with the user having the option to select 51 options. 

When the topic was closed the options were displayed with incorrect numbering in displayed options (see screenshots 1, 2, 3) and 
also in displayed results (see screenshot 4,5,6).

<img width="1329" alt="Screenshot 2023-07-09 at 15 44 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/08a7a3fb-c9b3-4826-bffe-ae78b689b525">
<img width="1327" alt="Screenshot 2023-07-09 at 15 44 44" src="https://github.com/citizenos/citizenos-fe/assets/72747107/88ed2998-8f0d-4a07-95d2-dcf0a12510fb">
<img width="1332" alt="Screenshot 2023-07-09 at 15 44 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6a9f56ff-1a91-4301-953a-dcba12337fa1">

<img width="1333" alt="Screenshot 2023-07-09 at 15 44 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/27393b38-d023-4cdb-93f5-b96fe3fb12f8">
<img width="1329" alt="Screenshot 2023-07-09 at 15 45 05" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f6fbd1e0-88ac-4954-b242-2ea9e9c8e3aa">
<img width="1331" alt="Screenshot 2023-07-09 at 15 45 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9f81fa76-cc8d-4e9b-a67c-d717545487ef">

**Why is this a problem?**
Very critical bug. Users cannot get proper voting results but only get to know this after having gone through the whole process. Extremely frustrating and demotivating for users.

**Possible solution.**
Options should be displayed as they are without an ordered list. Ordered list such as number or alphabet already confuses the user as it indicates hierarchy and relationship when in fact all the options are equal and unrelated. 

For voting results, the options should be organised according to number of votes, i.e 41 = 3 votes, 37 = 1 votes.  In this scenario 41 is on top, followed by 37 and so on and so forth.

**Comment by ilmartyrk** [comment]
@ssin1901 Fixed some styling and ordering of items as in the original spec, but didn't go deeper at this point

**Comment by anettlinno** [comment]
Triage 87. Critical bug. Needs fixing:
- Correct numbering 
- Remove alphabet counting and in the results display option name (like is in the graphic file)

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/665513e7-14da-4ac5-95e6-966e81c25926)

- After voting is closed, display graphic so that winning options are being showed first

Est.dev.time 1 hour. Sending it To Do.

**Comment by ssin1901** [comment]
@ilmartyrk @anettlinno Ilmar has posted a fix in the test environment
