### ISSUE TITLE
IDEA GATHERING: Etherpad asked for authentication 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1612]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

Etherpad asked for authentication in this idea gathering topic https://app.citizenos.com/en/topics/ae0e4b27-8855-4a45-9c2d-248ec8c77943 (screenshot1)

<img width="1344" alt="Screenshot 2024-09-27 at 11 22 10" src="https://github.com/user-attachments/assets/1bbd6d9f-c2c2-44a8-9b9a-bfa6f1e67d46">

**Why is this a problem?**
User could not enter a topic description

**Possible solution.**
User should be able to enter a topic description

**Comment by BeccaMelhuish** [comment]
@ssin1901 will close this one as we already have https://github.com/citizenos/citizenos-fe/issues/364 open :)
