### ISSUE TITLE
IDEA GATHERING: Co-editor sees view for creating and managing folders but gets insufficient permissions error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1613]
**What is the problem?**
_Tested in Google Chrome and in Safari_

A user invited as co-editor sees the view for creating and managing folders. However, when they try to create a folder, they get an insufficient permissions error (screenshot1)

<img width="1290" alt="Screenshot 2024-09-27 at 11 54 30" src="https://github.com/user-attachments/assets/9da2ad1e-4966-4a28-8f1a-1f41e8ebffe7">

**Why is this a problem?**
Very misleading about user permissions

**Possible solution.**
@ilmartyrk @BeccaMelhuish if I am not mistaken, a co-editor cannot organise the ideas? They can only edit the topic text? In that case, this is the correct view (screenshot2)

<img width="894" alt="Screenshot 2024-09-27 at 12 07 19" src="https://github.com/user-attachments/assets/e89d16ac-dc53-4498-b44d-b98b73bcd909">

**Comment by BeccaMelhuish** [comment]
@ssin1901 It's a good question whether editors should have rights to edit folders.. It's not something we've discussed. But I guess best to have it just as admins for now, then we can see if there's a need for editors to have the rights too. 

In which case I agree that they shouldn't see the view for creating and managing folders (screenshot 1). They should have the participants view (screenshot 2).

**Comment by BeccaMelhuish** [comment]
Moved this one to ready for dev in ideation, in case it's a quick fix that can be done before @ilmartyrk's off :)

**Comment by BeccaMelhuish** [comment]
With editor rights I got this, so will move to Done :) 

![image](https://github.com/user-attachments/assets/1d23b29b-8333-45bd-956a-d87550154415)
