### ISSUE TITLE
IDEA GATHERING: Incorrect view for co-editor in topic settings

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1614]
**What is the problem?**
_Tested in Google Chrome in incognito mode_ 

When a user with Editor permissions tries to edit a topic in Idea Gathering, they see this view (screenshot1) which is the Topic Settings view. 

<img width="1295" alt="Screenshot 2024-09-27 at 13 53 59" src="https://github.com/user-attachments/assets/cc54367f-33c5-40a3-8709-c42616e41cd3">

However, this view is not correct (as the editor is not supposed to change or access topic settings) and consequently the changes were not saved.

**Why is this a problem?**
High priority as the editor would not be able to save changes.

**Possible solution.**
In a Discussion topic, the co-editor sees this view (screenshot2). @BeccaMelhuish agrees that this should be the view for editors in all the topics (Idea Gathering, Discussion and Voting)

<img width="1440" alt="Screenshot 2024-09-27 at 13 26 39" src="https://github.com/user-attachments/assets/9f104b89-75d2-4f3e-9c77-b448be096651">

**Comment by BeccaMelhuish** [comment]
Also should be locked in idea gathering tab

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 fixed together with https://github.com/citizenos/citizenos-fe/issues/1554

**Comment by ssin1901** [comment]
@ilmartyrk unfortunately user Dave is still able to access the topic settings, but is unable to save the changes (see screen recording).

https://github.com/user-attachments/assets/e1b6ca13-0c50-4cd3-85ff-05cac301d5bc

This is the topic https://app.citizenos.com/topics/join/Pzx5SDRsFf5Z

**Comment by ssin1901** [comment]
Ah @ilmartyrk I guess you made the changes in test?

In test, the view is correct (see screen recording) but the insufficient permissions message prevents the user from successfully publishing the edits, though the edits are in fact saved. 

https://github.com/user-attachments/assets/fc9821d2-ae22-4cb3-a8f1-3be91ef509bc

**Comment by ssin1901** [comment]
@ilmartyrk closing this issue and reopening #1554 but keeping this in review since the changes haven't been deployed to live yet.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 re-opening as it needs to be the same for the idea gathering settings too (we can use the same pop-up, same text - at least for now I think it works OK). Currently with editor rights I can still access that:

![Image](https://github.com/user-attachments/assets/01a8fffe-327b-45cd-b1f6-8c0b97c580d7)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish the idea gathering view is locked for editors. Is it possible that we move this to Done and create a separate issue for the consistent UX? Currently the editors would not be able to edit the question so not a high priority issue in my view.

**Comment by ilmartyrk** [comment]
@ssin1901 added the view at the same time you were posting

**Comment by BeccaMelhuish** [comment]
@ssin1901 Am struggling with train wifi but if the idea gathering settings are locked for editors now that's good and can be moved to Done :)

**Comment by ssin1901** [comment]
Here is the view (see screen recording). Moving to Done. 

https://github.com/user-attachments/assets/920a8135-1ed0-4c7e-9e5d-6f7af717bb47
