### ISSUE TITLE
IDEA GATHERING: One person's ideas missing when selecting ideas to add to folders

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1616]
@ilmartyrk, @ssin1901 and I are testing the idea gathering in this topic: https://app.citizenos.com/topics/join/lV2cKkHVNhSN

- Initially she was admin and I was editor. 
- We each added several ideas. 
- She then made me admin. 
- We then both tried to add ideas to folders
- For each of us, we could only see Sara's ideas in the list

It said 14 ideas at the top, which was the total number of ideas, but then underneath it only showed the 9 made by Sara: 

![image](https://github.com/user-attachments/assets/3c0e0c76-d3be-4726-9020-87bc08d75ce3)

![image](https://github.com/user-attachments/assets/8f2d7b0d-80b1-44bb-853d-89afcfc53921)

Will put into ready for dev in ideation as is quite high priority to fix :)

**Comment by ssin1901** [comment]
Tested and all 10 ideas appeared in the folder and also in voting

**Comment by ssin1901** [comment]
Moving to Done
