### ISSUE TITLE
User can edit date but not time

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#162]
**What is the problem?**
When the user has initiated voting, and then goes to Actions->Edit deadline they are able to generate a new date and time (see screenshots 1 and 2) but this new time is not saved (see screenshot 3)
<img width="1328" alt="Screenshot 2023-07-09 at 16 34 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/010a8743-fe70-43ec-b173-6ccd96b36735">

<img width="1349" alt="Screenshot 2023-07-09 at 16 34 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/665eeb22-2f2c-4a03-bc4a-802044106bd8">

<img width="1138" alt="Screenshot 2023-07-09 at 16 35 04" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8a499297-3969-4ab9-8844-b35e078d6174">

**Why is this a problem?**
Not being able to change the time is bad for the user and may negatively impact all users in the topic, as they could receive voting reminders at unsociable times or be confused about when to vote.

**Possible solution.**
User should always be able to edit both date and time

**Comment by anettlinno** [comment]
@ssin1901 I could semi replicate this issue. After changing the voting time and refreshing the page, I could see changed voting deadline in the upper right corner.

**Comment by ssin1901** [comment]
@ilmartyrk bug is fixed (see screenshots). Just one thing - it needs refresh to update which is not ideal as the user might think the date and time has not been updated.

<img width="1333" alt="Screenshot 2023-08-16 at 11 33 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b20d6244-438a-47ef-9418-1dc5d272a380">
<img width="1137" alt="Screenshot 2023-08-16 at 11 33 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8c12f94a-40c5-40af-a8b0-0e7ca66ceb9d">
