### ISSUE TITLE
TOPIC: Formatting not saved correctly

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1626]
**What is the problem?**
_Tested in Google Chrome _

In a topic, the text does not appear in Preview and formatting is incorrectly saved (screen recording1)

https://github.com/user-attachments/assets/3754927a-2e3f-4020-bf46-3da70dc98e59

**Why is this a problem?**
@ilmartyrk high priority because a user submitted a help request about this issue

**Possible solution.**
Text should appear in Preview and formatting should be correctly saved

**Comment by BeccaMelhuish** [comment]
@ssin1901 I think we could close this one, as there is already [this issue](https://github.com/citizenos/citizenos-fe/issues/1181) grouping together issues with formatting after saving, and it already mentions the colour saving issue? (I have mentioned the support request there too). 

Have removed high priority from this one but will move 1181 high up in 'soon' though, as we discussed it should be a priority :) 

@ssin1901 should the 'text not showing in preview' part of this issue be a separate issue though? Or we can rename this issue to that and keep it open for that particular problem?

**Comment by ssin1901** [comment]
Closed as covered in #1181
