### ISSUE TITLE
Unfriendly message after the user tries to submit an argument without a main statement

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#163]
**What is the user story?**
After the user tries to submit an argument without a main statement they receive this unfriendly message (screenshot below)

<img width="1440" alt="Screenshot 2023-07-09 at 21 07 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ae7e8062-a938-4580-b73d-347375460a8b">

**Which feature needs to be updated and how?**
1.Arguments -> Main statements

2.Main statement field should indicate visually that this is a compulsory field (maybe a red outline over the field) and the user should know this before they add 

**Additional information.**
Not a priority for now but maybe with Redesign to enhance the user experience

**Comment by anettlinno** [comment]
Character limit is added in redesign project and as this is soon changing then I wouldn´t put any time and effort for fixing current one :) 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/52dc817b-4f7f-4dc1-989c-e6d3eeea55ec)

Closing this issue with no further action.

**Comment by anettlinno** [comment]
Character limit is in redesign

**Comment by anettlinno** [comment]
Triage 87. Compulsory field is also missing in redesign and should be added there. 
- Add asterisk before "Your main statement" which will mark the compulsory field 
- Red box with the error message under the input field: "Missing main statement"

Character limit is added in redesign, but it´s hidden. Ilmar will do the A/B testing where: 
A) we´ll add "Characters left" count-down counter behind  "Your main statement" and also same in the argument field
b) it remains the same for the argument field, but will add counter under the main statement input 
(please ask Kevin´s review before launching).

Sending this to redesign project. In current version no actions will be made.

**Comment by ssin1901** [comment]
Red background has been replaced with white background which looks friendlier (see screenshot)

<img width="1440" alt="Screenshot 2024-01-24 at 12 02 14" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9b847747-b63f-4f2d-bb09-60e606d62951">
