### ISSUE TITLE
Changes to tick boxes on registration form 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#164]
Two things for the registration form tick boxes:

1: The copy about Policies needs some work. It currently talks about having changed the policy, which I don't think is relevant to someone new who's registering? It's also rather long and formal and explains things that don't seem necessary. 
Could we just keep it simple, e.g.:
"I have read and agree to the Terms of Use and Privacy Policy." (With the links below like they currently are). 
This seems to be quite standard for such boxes.
@ssin1901 or @anettlinno, I don't seem to be able to tag Kati for her input here, are either of you able to?  

2. Please add an tick box to sign up to our newsletter. 
@MeelikaH What copy would you like for this?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3c0dc736-dcb7-4ccb-8efb-75ca4557cc54)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno just bringing this one to your attention again as we have the same message on the live version too, and it doesn't really make any sense in this context (when signing up for a new account - see below highlighted bits).

I can change it myself in the translation strings for the redesign one, but that wouldn't change it on the live one I believe? And wanted to check you are happy with my proposed new text before doing so :) 

For the newsletter sign-up, @ilmartyrk I checked with Meelika and for now it should just be "Sign up to our monthly newsletter!" please. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a1bbb197-e1f0-4a61-8334-fd3d84e4d9fe)

**Comment by anettlinno** [comment]
This issue is related to the #283 
@BeccaMelhuish 
> And wanted to check you are happy with my proposed new text before doing so :)
> 

Do you mean the text that you proposed in Issue 283? If so, then yes, this text is good.

With current platform we agreed that we won´t do any changes there any longer, so let´s keep it as it is in there and make the changes in redesign version.

**Comment by BeccaMelhuish** [comment]
@anettlinno Ah no, these are similar but different things :) 

Issue 283 is for a couple of occasions in which a pop-up appears asking users to accept the T&Cs (to existing users when we have changed the T&Cs, or to new users who register via social login), but this text is for the tick box on the registration form in which new users registering have to tick a box to accept them. 

My proposed text for this context is this below - nice and simple, and pretty standard I believe: 
"I have read and agree to the Terms of Use and Privacy Policy."

(And then it's also a request for a newsletter sign-up tick box to be added :))

**Comment by anettlinno** [comment]
Ahhh, thanks @BeccaMelhuish for the explanation! Yes, I totally agree that this one simple sentence you proposed works nicely there :)

**Comment by BeccaMelhuish** [comment]
OK super, thanks @anettlinno!

So the two tasks for @ilmartyrk from this then would be: 

- Change the text for the T&Cs tick box to: "I have read and agree to the Terms of Use and Privacy Policy."
- Add a third tick box: "Sign up to our monthly newsletter!"

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/08c01bc0-2c14-4194-add6-1d67ca91a5dd)

**Comment by anettlinno** [comment]
Triage 95. Sending To Do.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I don't know any newsletter list to start adding users to, I guess it will be for the phase II
