### ISSUE TITLE
TOPIC: Remove member is misaligned and therefore does not appear for the last member

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1644]
**What is the problem?**
_Tested in Google Chrome in Incognito Mode with viewport width = 1400 and viewport height = 623 _

When a user goes to a Topic -> clicks Manage Participants -> clicks the menu next to it-> the Remove button appears misaligned i.e not close to the participant name (screenshot1). The remove button does not appear at all for the last participants of each page. 

<img width="539" alt="Screenshot 2024-10-21 at 12 07 37" src="https://github.com/user-attachments/assets/18cd8154-bed3-44c8-9557-d5286d80cde8">

**Why is this a problem?**
High priority. User cannot remove participants and reported the same to customer support.

**Possible solution.**
Remove button needs to be aligned properly with different viewports

**Comment by BeccaMelhuish** [comment]
Small side note: if this is a topic not a group, it should be 'Remove participant' not 'Remove member' :) 
Could be fixed at the same time, or we can make a separate issue

**Comment by BeccaMelhuish** [comment]
Estimated dev time: 15 mins.

**Comment by ssin1901** [comment]
@ilmartyrk I think this is still broken in the test environment (see screen recording)

https://github.com/user-attachments/assets/e6ad2eee-4568-4638-aa23-5484baecdef2

**Comment by BeccaMelhuish** [comment]
@ssin1901 Have put it back to in progress :)

**Comment by ssin1901** [comment]
Fix implemented for Invited Participants (see screenshot). Adding ready for Live label.

<img width="1435" alt="Screenshot 2024-11-25 at 00 26 52" src="https://github.com/user-attachments/assets/281413a4-470b-47b7-86ea-ff7ec4dcd1a3">

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 moving this one back to 'pre-live' so it can be deployed to live, as it got automatically sent to done :)
