### ISSUE TITLE
Hashtag throwing up error 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#165]
**What is the problem?**
When the user goes to Create Topic->Actions->Hashtag = "Democracy" the correct hashtag appears but when the user clicks on the Hashtag link (Social mentions: 0#democracy) they get an error message (screenshot attached).

<img width="1324" alt="Screenshot 2023-07-11 at 11 52 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/647f83f1-7009-4a9a-a066-e4f38acfb28d">

**Why is this a problem?**
User cannot add hashtags, also when the error comes up the user may navigate away from the topic in frustration.

**Possible solution.**
Either hashtags should work or feature should be temporarily removed.

**Comment by ilmartyrk** [comment]
@ssin1901 I noticed it too today. Seems that twitter has closed our app because it was using older API version and now they have made this search feature available for only paid users. We will discuss it with @anettlinno and see what we will do next

https://developer.twitter.com/en/products/twitter-api

**Comment by anettlinno** [comment]
Triage 87. Talked to Ilmar and decided to remove hashtag entirely, as we don´t have certainty that it would help to improve discussions any good way. Feedback from some previous users have been that they would rather prefer to merge FB feed with our platform. Don´t see any reason to pay for that service. 
To do: 

- [x] Remove # tab from topic view (next to arguments)
- [x] Remove # field from topic settings
- [x] Remove # from read topic view

Sending it to do. Est.dev.time 15 minutes.
