### ISSUE TITLE
MISC: Prioritised 'quick wins' 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1664]
@ilmartyrk As agreed, this is a trial 'group issues' to prioritise a few 'quick wins' - small but relatively impactful tasks that could be run through as a batch in a short space of time. 

I'll link to the issues here, and move the issues themselves to 'next'. Once the issues themselves are fixed they should be moved to QA as usual, and ticked off here:  

- [ ] https://github.com/citizenos/citizenos-fe/issues/938 
- [x] https://github.com/citizenos/citizenos-fe/issues/1464 
- [x] https://github.com/citizenos/citizenos-fe/issues/1488
- [x] https://github.com/citizenos/citizenos-fe/issues/1582
- [x] https://github.com/citizenos/citizenos-fe/issues/1452
- [ ] https://github.com/citizenos/citizenos-fe/issues/287
- [ ] https://github.com/citizenos/citizenos-fe/issues/1648
- [x] https://github.com/citizenos/citizenos-fe/issues/1654

Once all of these are ticked off and the issues moved to done, will close this issue. 

@ilmartyrk please give an estimated time and feedback if any of these are actually not-so-quick wins :)

**Comment by ilmartyrk** [comment]
est dev time 3h.  as some fixes might take a little longer than few minutes to fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk if it works better, you could let me know which ones aren't so quick, and I can remove them and prioritise them separately?

I notice I had lumped some other UX issues in with the search scroll one, so have separated those out into a separate issue in 'soon' for now (though if more efficient to tackle them all at once, that's fine too) :)

**Comment by BeccaMelhuish** [comment]
I will close this issue now to keep the process consistent for the new dev, and will prioritise these small issues all separately :)
