### ISSUE TITLE
IDEAS: Bug relating to adding multiple photos?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1666]
**What is the problem?**
In [this issue](https://github.com/citizenos/citizenos-fe/issues/1508), we had some bugs relating to adding multiple photos, but it's not clear if they've been resolved, or if we need to notify users of a maximum number of images they can add (10?).  

**Why is this a problem?**
Will cause user issues if they try to add many images. 

**Possible solution.**
Might @ssin1901 be able to test a bit and report back on the current situation? :)

**Comment by ssin1901** [comment]
@BeccaMelhuish a warning that only 10 images can be added has been implemented in the test app (screenshot1)

<img width="1380" alt="Screenshot 2024-12-09 at 16 05 23" src="https://github.com/user-attachments/assets/0d6e8337-bfd2-4296-8b24-a33ecec2b134">

Will put it in QA - Pre Live
