### ISSUE TITLE
VOTING: Change text 'Voting system' to 'Voting phase' 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1671]
**What is the problem?**
I remember we discussed with @oksks that calling the vote phase 'voting system' and all the others phases isn't ideal, and we should switch it to phase. E.g. here: 

![image](https://github.com/user-attachments/assets/a178f688-b389-4fe1-b5c4-344b341e3628)

**Why is this a problem?**
Inconsistent and potentially unclear for users.

**Possible solution.**
I will out this to 'soon' and assign myself to switch it in the strings wherever I find it.

**Comment by BeccaMelhuish** [comment]
In the translation strings, I've edited out 'voting system' in all places except where it does make sense, such as in the vote settings. Just needs merging by @ilmartyrk now so will put to 'in progress' :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish merged

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish this implemented in Live. I am putting it in Done.

<img width="1355" alt="Screenshot 2024-12-13 at 15 16 08" src="https://github.com/user-attachments/assets/72c510b2-c654-4a25-8bd9-de929f37c981" />
