### ISSUE TITLE
LOGIN: Internal Server Error received

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1674]
**What is the problem?**
During a live demo, someone from the team reported that a user tried to login multiple times and received a white screen and internal server message. The user tried on different devices but it took a while for it to work.

The issue occurred between 11:15-11:45 Tallinn Time on Friday (15.11.2024).

Could not replicate the issue with a test account but might be missing something @ilmartyrk 

**Why is this a problem?**
User could not log in, hence high-priority

**Possible solution.**
User should not receive an internal server error message.

**Comment by ilmartyrk** [comment]
@ssin1901 This user had google account connected to another account, though for some reason she had 2 different e-mail addresses referring to the same Google user. This seems like an edge case and I don't see any good possible fix at this point
