### ISSUE TITLE
REGISTER: Verification skipped

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1686]
**What is the problem?**
In the test environment, the user was able to register an account and login without receiving an email verification. 

Verification did not come to the email either.

Will send the account details to Slack.

**Why is this a problem?**
@ilmartyrk is the disabling only for the test environment? 

**Possible solution.**
@BeccaMelhuish is there a UX update that I missed wherein we do away with verification?

**Comment by BeccaMelhuish** [comment]
@ssin1901 no change to the UX update, so have put it to the top of ready for dev for @ilmartyrk to look into :)

**Comment by ilmartyrk** [comment]
@ssin1901 Database shows that the e-mail has been verified, we don't have any other logic to verify the e-mail addresses. We only do it automatically when user logs in with either Google or Facebook accounts

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish I can see from the mailgun logs that there was an invite sent to that e-mail and the user accepted the invite so this action already verified the users e-mail. Closing this issue
