### ISSUE TITLE
NOTIFICATIONS: Discussion notifications not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1690]
**What is the problem?**
@ssin1901 @ilmartyrk In [this topic](https://app.citizenos.com/en/topics/24faaf16-f75f-4d4c-8e94-a7d47c2f9755?argumentId=b61549a1-c96d-4693-8224-bcd260413b8a_v0), I've got notifications all switched fully on (and have had them on for several days), but I'm not getting any notifications come through e.g. when someone replies or adds an argument: 

![image](https://github.com/user-attachments/assets/7bb3a0fe-d0a0-4911-ab87-5e0909243f37) 

Is the notifications system currently working?

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk I didn't receive Discussion related notifications in Test or Live. However, idea gathering and voting worked in both.

**Comment by BeccaMelhuish** [comment]
OK thank you @ssin1901, will put this to ready for dev high priority as well :)

**Comment by BeccaMelhuish** [comment]
I am getting notifications for 'up' reactions (and their removal) though: 

![Image](https://github.com/user-attachments/assets/2d07d4ac-ba49-4d05-8b39-1a60888a43f2)

And also change to topic text:

![Image](https://github.com/user-attachments/assets/7e36bf16-44f2-4cf2-97da-64deb2a56f91)

So it seems maybe only arguments and replies are not working?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is related to deeper notification system fix. Cannot give a proper estimate for now.
Related to https://github.com/citizenos/citizenos-fe/issues/1212

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK makes sense thank you! Have bumped them up the priority together then :)

**Comment by ilmartyrk** [comment]
Fixed together with #1212

**Comment by BeccaMelhuish** [comment]
@ilmartyrk same as with ideas notifications, I tested in development with adding an argument, liking one and replying and I didn't get any notifications come through

**Comment by ilmartyrk** [comment]
@BeccaMelhuish not sure how you tested it, but you will not get notifications about your own actions, also just checked that users must be a member of the topic. 

Regarding users being members of the topic, should we continue with this requirement and hide the notification settings button for not members or we implement the logic to send notifications to all users who have turned them on for public topics?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk oh sorry my bad, I always thought I did get notifications on my own actions (which indeed makes no sense!), but must have been between my two accounts. Re-tested and all good!

Re the notifications for public topics yes let's send them to any users who turn them on in public topics, and make it so that if they turn on notifications they automatically 'join' the topic. I'll add a note to that effect in #307 

Will move this one to pre-live in this case, as once that fix is made in #307 it will presumably be fixed in this sense too :)
