### ISSUE TITLE
DISCUSSION: After editing my argument, the edits appeared underneath

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1691]
**What is the problem?**
@ssin1901 @ilmartyrk I edited an argument in [this topic](https://app.citizenos.com/en/topics/24faaf16-f75f-4d4c-8e94-a7d47c2f9755?argumentId=df74107a-f374-4534-8e00-1e8c7b1668cb_v0), and once I had finished, this edit history appeared: 

![image](https://github.com/user-attachments/assets/f3cf05b5-456e-442c-a8eb-5dd7efae31e2)

After having closed it, every time I come into the topic or refresh it shows me the edits again: 

![image](https://github.com/user-attachments/assets/5e82314b-b5dc-402b-875a-aa9cb26f1dd5)

Same thing happened in a 'first level' reply that I edited:

![image](https://github.com/user-attachments/assets/6c145c40-91f9-442b-8cd0-965e3c3c9b35)

But for a 'second level' reply it was fine (just closed with the edits showing in the reply as expected). 

**Why is this a problem?**
Very unexpected, I think it's a bug? 

**Possible solution.**
After editing, the edits should just appear in the argument. Only if you then click to view the edits should appear.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I'm assuming this might be quite a quick fix? On that assumption I'm going to put it near the top of the priority pile as we have a discussion use case starting tomorrow for which it would be great to have it fixed (but if it's actually a big job, let me know) :)

**Comment by ssin1901** [comment]
@BeccaMelhuish for me, the topic edits are not showing up once I navigate and come back to the topic (screen recording)

https://github.com/user-attachments/assets/24ae3fa4-34f4-4d32-9a3f-4f6419cce0f1

I think this issue is fixed. Should we move to Done? Seems fixed in live if I'm not mistaken @ilmartyrk

**Comment by BeccaMelhuish** [comment]
@ssin1901 Not fixed in live as it just happened to me again in the same topic, though I had the same impression last night as it didn't for me - so maybe it's only occasional? 

Seems to be all good in development app though so I think it can be moved to 'QA pre-live' ready for live :)

**Comment by BeccaMelhuish** [comment]
Moving to Done as it got merged to live
