### ISSUE TITLE
FILTER: pro and con arguments does not work well

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe#1692]
**Add a category to ticket heading for easier sorting**

**What is the problem?**
I wanted to filter pro and con arguments to read pro arguments first and not to have pro, con, neutral arguments mixed. I went and chose "pro" in the filter to go through these first. At first it worked but after I left a comment, it refreshed the page and I saw them all mixed again. 

I went to double check the filter (assumed it reset after refresh after the comment posting) and it showed the right filter was indeed selected, but all arguments were mixed. I had to go and uncheck the previously chosen filter option, then check again the one I wanted (repeat the procedure) and only then it showed pro arguments only. I had to do this after posting any comment as a reply. As I left several comments, I had to do this several times.

**Why is this a problem?**
It is confusing and uncomfortable for the user to have to un-check and check again their preferred filters any time they leave a reply, post something, etc. It's also confusing for them to see the filter they've set appears as active, but the preview of arguments does not display accordingly.

**Possible solution.**
Fix the issue so that once the person chooses a filter, even after engaging (leaving comments/replies or posts their own arguments), the filter stays on unless changed by the user.

**Comment by BeccaMelhuish** [comment]
Thank you @MeelikaH! 

@ssin1901 does this need more testing before @ilmartyrk works on it, or we prioritise it based on the above? :)

**Comment by BeccaMelhuish** [comment]
@ssin1901 adding high priority for the QA testing - if tomorrow's discussion topic happens to take off, would be great to have it live :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish currently replying to an argument does not cause the filter to be lost, so I guess the fix is good enough?

See screen recording from app.citizenos.com but it's the same in development.app.citizenos.com

https://github.com/user-attachments/assets/e2f25e8a-c11c-47dc-ac43-13ec7c27ab68

If it's already deployed to Live, can it be moved to Done?

**Comment by BeccaMelhuish** [comment]
Looks good from the recording! I think the merge was just to 'development' app so think it's not live yet? Will put to 'pre-live' ready for live anyway :)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think we can send to live, as it was working more consistently in development.app.citizenos.com.

**Comment by BeccaMelhuish** [comment]
Moving to Done as it got merged to live
