### ISSUE TITLE
Why does Send to Voting appear after the topic is in follow up?

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#170]
**What is the problem?**
When a topic is sent to Follow Up, the user sees a Send to Voting on the top right hand corner of the menu. When they click Send to Voting they are asked to confirm, however, nothing happens after that (screenshot attached)
<img width="1247" alt="Screenshot 2023-07-16 at 21 46 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6ca77225-6ffd-4a45-a4d5-280a542df9f0">

**Why is this a problem?**
Very confusing for the user 

**Possible solution.**
There should only the Close Topic option if the user cannot create a new voting sequence.

**Comment by anettlinno** [comment]
Triage 87. As we do not allow to open the voting after changing the status to follow-up, then let´s remove the "Send to voting" under the Options. 
Est.Dev.time 2 min. Sending it To Do.

**Comment by ssin1901** [comment]
@ilmartyrk testing and it is fixed, however there is a new issue with follow up #208
