### ISSUE TITLE
DEV ENV: Create topic not working

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1713]
**What is the problem?**
_Tested in Chrome incognito and Safari incognito_

In our Dev Env, there's is a 500 error (screenshot attached) when you create Click Topic

<img width="1381" alt="Screenshot 2024-12-10 at 11 45 45" src="https://github.com/user-attachments/assets/dff5b52e-f87a-4c3f-ab82-3393a780cc70">

**Why is this a problem?**
@ilmartyrk @BeccaMelhuish it's only in Dev not in Test or Live but it makes testing features in Dev impossible.

**Possible solution.**
@ilmartyrk @BeccaMelhuish I'm working through the issues in QA Dev, but if this issue will take a while to fix, then I can just just do one last round of testing in "Test" and leave Dev alone for the time being.

**Comment by BeccaMelhuish** [comment]
@ssin1901 @ilmartyrk I've put it to the top of ready for dev assuming it's just a quick fix 🤞

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish fixed

**Comment by ssin1901** [comment]
@ilmartyrk works properly, thanks. Moving to Done.
