### ISSUE TITLE
UX request: Copy Google Docs "Share" UX for selecting user to invite

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#175]
@kevincrepin @ilmartyrk @anettlinno 

Maybe this is the plan already, but for the redesign, would it be possible to fix the UX issue with selecting people to invite, when you type in their name and they pop up as suggestions? After 3 years of using the platform, it still gets me every time! :D 

So currently, when the user or group you want to invite shows up and you do the natural thing of clicking on the name (where I've highlighted yellow) to select it, nothing happens. The box just disappears completely, no-one gets added, and you keep trying a few times to make it work (or at least I do). Then you notice this "Press enter to add" and in my case click on that, which while not logical (as the words say "press enter to add", not "click here to add") works, but is odd and confusing. 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d00a6205-e5b3-443b-a57c-146511f64b1c)

I think we could do it the exact same way as Google docs when you share with other people, as this will be what most people are used to and expect:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f5891005-1e97-4a32-9908-3e87054c49de)

So when the names pop up underneath, you can either: 
-  With mouse: Click on the relevant name. 
-  With keyboard: press the down arrow until the relevant name is selected, then press enter. (No need for "press enter to add" instructions, as it's intuitive/common UX).  

Would make it nice and smooth :)

**Comment by BeccaMelhuish** [comment]
Ah OK I see here in the design that it is now "Select to add" for adding topics to a group, so presumably the same across the board. 

But am hoping it will be the case that selecting anywhere in that row will add it (not having to actually click on the "Select to add" bit like you currently have to with the "press enter to add" text), and that like with Google docs you will still also be able to press enter to add? 

(I feel like maybe the "Select to add" text is a bit redundant in that case? As people know that if they click on something in a dropdown box it selects it). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9e421d41-e654-45ae-a3a5-c6fd19fb1738)

**Comment by kevincrepin** [comment]
The logic should be same as google yes, click on any of the results to add. It was always meant to be like this. The "press enter to add" was always supposed to be just another means to add.

**Comment by BeccaMelhuish** [comment]
OK wonderful, @kevincrepin good to hear! 
A minor thing - but do you think the "select to add" text is necessary? I feel we could just do without it :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Maybe it's work in progress, but in case not: I notice in the redesign there's still "Press enter to add" hanging on here from last time, and also as per this conversation above you should be able to click anywhere in there row (highlighted yellow) to add (hence no need really for the "select to add" text I feel, but that's less important) :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5f8d6079-a1bf-4685-a064-ab721aad61ab)

**Comment by anettlinno** [comment]
Very much support for the proposed (Google) solution! :) IMO "Select to add" is not necessary, as what @BeccaMelhuish said, it is well known user behavior.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno Sorry I see I have somewhat duplicated this issue [here](https://citizen-os.slack.com/archives/C91AYDJ91/p1700580190885039)! (Though there's a bug in there too)

**Comment by kevincrepin** [comment]
Ok for me!

**Comment by anettlinno** [comment]
Triage 95. It is almost implemented, only thing to add is to extend clickable option in the drop-down. 
Sending it To Do.
