### ISSUE TITLE
Code in Delegation not allowed

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#177]
**What is the problem?**
When a user toggles vote signing and vote delegation it initially appears as if both can be done (screenshot attached). 
<img width="758" alt="Screenshot 2023-07-31 at 14 25 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f47b253a-88ea-4c3a-bfb6-c6f15173bbed">

<img width="1395" alt="Screenshot 2023-07-31 at 14 25 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8a9191d0-1c39-4948-92b6-d5205e280aa4">

However, when the user clicks start voting they receive this error which has code in it (screenshot attached)

**Why is this a problem?**
Confusing for the user 

**Possible solution.**
There should be no code in vote delegation not allowed

**Comment by anettlinno** [comment]
Triage 89. When User toggles in eID voting rights, then vote delegation should be on the "off" mode and disabled (User is unable to switch the toggle). In that case, error message is not needed. 
Time estimation 10 min. Sending it To Do.
