### ISSUE TITLE
No consistency in how the co-authors are ordered

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#179]
**What is the problem?**
When there is more than one author with Editor and Admin rights, the system is inconsistent in terms of which authors name appears first. Usually it is alphabetical, however today the topic owner appeared first (see screenshot)
<img width="841" alt="Screenshot 2023-08-03 at 08 57 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e5d85615-1e98-4d98-87a4-6ac768206c22">

**Why is this a problem?**
Problem especially for official proposals as the question might arise, what order will the names come in?

**Possible solution.**
@ilmartyrk @anettlinno @BeccaMelhuish  to my mind, this should be fixed in Redesign to be consistent but I am not sure how co-authors should be ordered. Maybe it is something we need to ask our partners.

**Comment by anettlinno** [comment]
@ssin1901 good catch! :) I think initially co-authors were ordered by the timeline -- person who created the topic was first, second editor second third editor third etc... That seemed to be logical and worked well and in my mind we should keep that if there isn´t any strong argument why to change that :)

**Comment by anettlinno** [comment]
Triage 89. Currently Etherpad sends co-editors back randomly and it would probably take quite a lot of time to change it there. So, we decided not to do anything with this issue in our current version, but we´ll add it in the redesign (currently co-editors are missing from topic view).
Closing this issue with no further action.
