### ISSUE TITLE
HC QUERY: Creating an account

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#180]
@ilmartyrk @anettlinno For the redesign HC texts, could you let me know if there are any changes to the way that creating an account works, other then the UI (i.e. other than the stuff that I can see myself in the prototype). I.e. does all of the current guidance below still stand? 

Current guidance: https://citizenos.com/help/login/creating-an-account/
**_Relevant text copied below_**

*****

There are various ways to create a Citizen OS account, depending on your preference. 

**Email and password**
You can create an account using your email address and a password of your choice. 

**Social login**
You can create an account by logging in using any of the following social login options. The first time you do so, your Citizen OS account will automatically be created. 

**Log in with Facebook** 
Log in with Google 
The email address connected to this Citizen OS account will be the email address you use for your Google or Facebook account. This is the email address you will receive topic/group invitations and notifications to. 

**E-ID login (Estonia only)** 
Log in with ID Card / Mobiil-ID 
Log in with Smart-ID 
When creating a Citizen OS account by [logging in with e-ID](https://citizenos.com/help/login/logging-in-using-e-id-estonia-only) you will be asked to provide an email address. This is the email address you will receive topic/group invitations and notifications to.

**Comment by anettlinno** [comment]
Triage 90. Creating an account remains the same in redesign.
