### ISSUE TITLE
HC QUERY: Troubleshooting “no permission to access”

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#181]
@ilmartyrk @anettlinno For the HC texts, I'm assuming all of this stays the same for the redesign?

Current guidance: https://citizenos.com/help/login/troubleshooting-no-permission-to-access/
_**Relevant text copied below**_

*********
Topics and groups can only be accessed using a Citizen OS account which is registered with the same email address to which the original invitation was sent.

**Follow these two key steps for topic/group access:**

- Click on the link in the invitation email you received for joining the group or topic.
- Login or register using the same email address the invitation was sent to, according to either of the two scenarios below:

- If you already have a Citizen OS account registered with the email address your invitation was sent to, log in using that account.
- OR
- If you do not yet have a Citizen OS account registered with the email address your invitation was sent to, register a new one with the correct address.

**A few additional tips:**

- If you are logging in with a social login such as Google or Facebook, this will only work if your social media account is registered with the same email address as the one with which you were invited to the group or topic.
- The option to log in with your ID-card/Mobile ID (applicable to Estonian ID-cards) will only appear if you have previously created a Citizen OS account with the email address to which the invitation was sent, and have previously digitally signed at least one document through that account. If this is not the case, you will need to log in using your email address instead.
- If you are unsure what email address your Citizen OS account is registered with, or to which account you are currently logged in, you can check this under "Profile".

**Comment by anettlinno** [comment]
Triage 90. This will remain the same also in redesign.
