### ISSUE TITLE
HC QUERY: Logging in using e-ID

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#182]
@ilmartyrk @anettlinno For the HC texts, I'm assuming all of this stays the same for the redesign?

Current guidance: https://citizenos.com/help/login/logging-in-using-e-id-estonia-only/
**_Relevant text copied below_**

***************************

It is possible to log in to Citizen OS using Estonian e-ID, Mobile-ID and Smart-ID.  (Note: you do not need to log in with e-ID in order to [vote with e-ID](https://citizenos.com/help/voting/how-to-vote-using-a-digital-signature-for-topic-participants-estonia-only), they are two separate actions).

In order to log in using Estonian e-ID, your account must have previously been linked to your e-ID. 

Accounts can be linked to e-ID in two ways: 

- If you logged in with e-ID when first registering your Citizen OS account. Only one Citizen OS account can be linked to your e-ID through this method. (Note: when registering using e-ID you will be prompted to provide an email address to which the account will be connected). 
- If you previously voted using e-ID, the Citizen OS account through which you voted will now be linked to your e-ID. Multiple accounts (i.e. various Citizen OS accounts connected to various different email addresses) can be linked to your e-ID through this method.

**Logging in to multiple accounts:**
It is possible to log in to various different Citizen OS accounts using the same e-ID, as long as they have previously been connected to your e-ID, as outlined above.

**Please note:**
- If logging in directly from the Citizen OS Home screen (i.e. navigating straight to the platform when logging in), e-ID login will take you to whichever account you first connected to your e-ID. 
- If following a topic invitation email link (from a notification email), e-ID login will take you to the account linked to the email address to which the invitation was sent.  
- If you try to log in to an account which has not previously been linked to your e-ID, e-ID login will display an error message, and you will need to log in using your password or social login.   
- If, after following the above instructions, you are still having problems logging in with e-ID, please refer to the Estonian ID-card “[Failed log in and sign in](https://www.id.ee/en/article/failed-to-log-in-or-sign-in-e-services-with-an-id-card/)” helpline page.

**Comment by anettlinno** [comment]
Triage 90. e-ID logging remains the same also in redesign.

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk Thank you! 
One thing I would like to add to the HC which we missed off previously, and which is related to data privacy, is info about whether and to whom your email address gets displayed. I know on the current platform there is a way to opt in/out of having it displayed. Will it be the same on the redesign, and how will it work? (May be a question for Kevin, but will let you tag him if needs be) :)

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk Thank you!

One query though, as re-reading the existing HC texts there is something that doesn't make sense to me. 

In a couple of places we are contradicting ourselves about whether or not you can log in with e-ID without having previously linked it. For example, we say that one way to [create an account](https://citizenos.com/help/login/creating-an-account/) is to log in with your e-ID (and then you will be asked to provide an email address to link to it). But then [somewhere else](https://citizenos.com/help/login/logging-in-using-e-id-estonia-only) we say that "In order to log in using Estonian e-ID, your account must have previously been linked to your e-ID." Which would suggest you can't create an account by logging in with e-ID, as you couldn't have previously linked an account which didn't previously exist. 

Which one is true? :)

**Comment by BeccaMelhuish** [comment]
Also, in one place we say:

"The option to log in with your ID-card/Mobile ID (applicable to Estonian ID-cards) will only appear if you have previously created a Citizen OS account with the email address to which the invitation was sent, and have previously digitally signed at least one document through that account. If this is not the case, you will need to log in using your email address instead."

But this doesn't seem to be true either, as I have never done so, and it appears for me..

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/97f0a32d-c38e-4869-9c7a-c2d98a4f3877)

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: Becca to check with Ilmar.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish
"In order to log in using Estonian e-ID, your account must have previously been linked to your e-ID." -> I guess that it was meant to say that if you want to login to your account where the invite to topic/group came, then this has to be connected to e-ID. But otherwise it is true that you can just create a new account by directly logging in using e-ID for the first time and after that adding an email.

Second one might be a bug, it should list only options that this account has connections with

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah OK thank you! So basically this: "In order to log in using Estonian e-ID, your account must have previously been linked to your e-ID" is about when you are following an invite link that was sent to a particular email address, rather than just logging in in general.  

For the second one I think I need to clarify in the text that we're referring to when you follow an email invite to a particular email address, but yes it does seem to be a bug as I just followed an invite link sent to my gmail (no e-ID linked) and it did come up like this below. Will make a new bug issue for this now :)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/21911787-6ac1-478e-87d6-92bc43a4bf2f)
