### ISSUE TITLE
HC QUERY: Inviting group members

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#184]
@kevincrepin @ilmartyrk @anettlinno For the HC texts, is it safe to assume that the "Invite members" function for groups will be exactly the same as the "Share and Invite" for topics (screenshot below), or will there be any differences? (It's not designed in the Figma file as far as I can see). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1a7f0bec-2cbf-4ef3-92db-956f311985f1)

**Comment by kevincrepin** [comment]
I would say the same yes, unless I missed some different needs between group inviting and topic inviting.

**Comment by anettlinno** [comment]
Triage 90. Yes, both invites are the same in group and topic view.
