### ISSUE TITLE
HC QUERY: How to see pending group members and edit members rights

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#185]
@kevincrepin @ilmartyrk @anettlinno For the HC texts, how will you see which group members' invites are "pending" when you're the admin? (I don't see it in the Figma, only this below): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d57d7e4c-d822-4d14-869e-410d878910db)

Also, when you are the admin, will this become a drop-down so you can edit the rights, or how will it work? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/88122197-d28c-4ad2-a3d4-bbc4fb6d5f3f)

**Comment by kevincrepin** [comment]
Absolutely right @BeccaMelhuish ! I added an example now: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=596-67961&viewport=-6841%2C-8363%2C0.5&t=itFogWayDOFOjc4d-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

One other thing which was missing is to show in the topic participant list when someone has made a request to change their rights. This is also added now: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=248-42420&viewport=-6841%2C-8363%2C0.5&t=itFogWayDOFOjc4d-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

**Comment by anettlinno** [comment]
@kevincrepin regarding pending members @ilmartyrk suggested to add one more filter next to search where people can choose members or pending invites (copy needs agreement).

@BeccaMelhuish Admin user can change roles from "Actions" menu on the right column (next to rights)

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/ff54449b-3a6b-484c-a292-ae16eaf9d72c)

**Comment by kevincrepin** [comment]
@anettlinno @ilmartyrk I added this extra filter in all designs: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=596%3A67961&mode=design&t=Z2CANJtlX4cwOcf2-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin would you be able to screenshot the bit you are talking about in the last link you shared (the extra filter)? The link seems to not take me to the right place

**Comment by kevincrepin** [comment]
Sure, here it is
![Screenshot 2023-10-10 at 16 48 52](https://github.com/citizenos/citizenos-fe/assets/26792281/7473359e-960b-46ed-8653-f44320b5d62d)

**Comment by BeccaMelhuish** [comment]
Got it, thank you!
