### ISSUE TITLE
Adding topics to a group (request access)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#186]
@kevincrepin @ilmartyrk @anettlinno For the HC texts, there's a couple of things that aren't totally clear on the design so I'd like to check my assumptions are correct: 

- When adding topics to a group, the Figma pop-up is different when you are adding it via the group or via the topic - is this just different views of the same pop-up? I.e. these will presumably both work the same, and both include the rights settings, or is there a reason for the topic one not including rights? 

The pop-up when adding via the group: 
 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c7aa6803-0f34-4417-a6f7-413dedd9d829)

The pop-up when adding via the topic: 
 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3decdb27-6a18-450d-9114-0e3d619c0048)

- As the prototype only shows the pop-up from the point of view of a non-admin, I'm assuming it will be like this for both different views (the bit in blue is my assumption) - is that correct, or if not how will it be for admins? (And presumably admins won't be shown the "Add a reason" box at all, as it's not relevant to them?).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e9beb866-28f5-4ed7-b39f-e6059b9afd0b)

**Comment by kevincrepin** [comment]
It's the same popup, yep. Just one has already topics added so that's how it would look.

It's actually a bit complicated because there should always be permissions given by the creator of the topic for their topic to be included in a group, I think? Otherwise my topic can be added into a group I totally not relate to for example. So I would say the reason always has to be there.

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ah OK yes makes sense! Does that mean this bit should also mention the owner of the topic then, as well as the owner of the group, if both have to approve it? (Though in some cases the person requesting will be one or other of these people, presumably). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b6237728-6a21-4a98-9515-7c43fad57def)

I guess there would be a case where the requesting wouldn't be necessary though, which would be if the person wanting to add it to the group is both the owner of the group and the owner of the topic - which I can imagine happening quite often potentially (if someone makes a topic, without adding it to a group when making it, and then later wants to add it to a group they manage). 

So in that case it would just be "Add to group", and they wouldn't have to go off and approve any requests from/to themselves hopefully - it would just happen automatically?

**Comment by kevincrepin** [comment]
Yes, this makes sense :) Would be quite interesting to have to justify to yourself why you do what you do, quite philosophical!

**Comment by anettlinno** [comment]
I´ll try to explain these situations through user cases. 

1. User is owner of a group 123 and wants to add a new topic that one has created in the group. After finalizing the topic, she goes to group, clicks on "Add topic", searches the topic she created, enters the topic in the group and sets topic rights. No permissions from other people or explanations are needed in this case. 

PS! As discussed with @ilmartyrk then **in redesign Phase 1 we only allow people to invite to the group those topics which they have created.** IF they want to add other people´s topics, they need to get a) admin rights to the topic OR b) contact topic owner directly. In the topic search field will be displayed only those topics that Users have created (they don´t see other people´s topics).

2. User Ben21 wants to add add topic that User Mia19 created to the group 123. Ben21 goes to group, clicks on "Add topic", searches the topic that User Mia19 has created, enters the topic in the group and writes reason WHY he wants to add this topic to the group. User Mia21 receives e-mail (?) notification and Activity Feed notification no the platform, where she can read the explanation and with one-button click can decide if she accepts the topic to the group or rejects. 
IF she won´t allow then she also has to write an explanation, WHY. User Ben21 receives an e-mail and Activity Feed notification and reads the reason why it was rejected.
IF she accepts the topic then who is setting topic rights? Either person who is owner of the topic or (Mia19) or person who wants to add it to the group (Ben21)?

This flow will be developed in redesign Phase 2.

**Comment by anettlinno** [comment]
Triage 90. Detailing the Phase I developments. 
Group admin can only add those topics, where one has admin rights. 

Use case where Mari (group admin) wants to add Mart´s topic, she has to either ask admin rights in the topic or give admin rights in the group to Mart. AND Mart should add the topic himself to the group.

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: For phase 1 will just go with what we have now on the platform, then for phase 2 will decide what to do about requesting to add. Might not even need it, may not be many cases where needed?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 just two things on this: 

Wondering if we still need it here, I guess not?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b42bf7cb-9fc0-4652-ac14-6763ceb2e434)

This bit that's yellow is currently active with the link but shouldn't be (only the text itself should be):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/13ccac07-eccd-47ee-b52f-adf18f4b6d75)

**Comment by BeccaMelhuish** [comment]
And I see from the screenshot in this comment above there was this 'We'll inform you" line - should be added in? :) 

https://github.com/citizenos/citizenos-fe/issues/186#issuecomment-1673347106

**Comment by BeccaMelhuish** [comment]
Copying in @ilmartyrk's update from earlier on Slack here too, just so all in one place :) 

_I've added the feature for users to request adding topics to a group in our https://redesign.app.citizenos.com/
How it works:_

_For public group members (not admins) there is a new option in the settings menu for a group to request adding topics to the group._

_After selecting topics an email is sent to admins where they can directly reject and accept requests. (Also added some code for cases where request is already rejected or accepted)_

_For admins added an extra options under add topics to group menu that says  Topic requests where they can quickly see all pending requests and accept or reject them_

_It was a quick MVP version so that we could possibly release as Viimsi parish started their participatory budget idea collection on our platform_

_This extra option for admins was my personal "design" solution as it would allow admins to quickly see the pending requests without going through their mailbox_

**Comment by ilmartyrk** [comment]
![Kuvatõmmis 2024-04-04 122043](https://github.com/citizenos/citizenos-fe/assets/19904307/9a06d02b-ad43-4dd6-8b43-9e5938a3a56f)
![Kuvatõmmis 2024-04-04 122028](https://github.com/citizenos/citizenos-fe/assets/19904307/96d7df43-4977-4e9c-bfe9-7b7ca3385b8b)

![Kuvatõmmis 2024-04-04 122929](https://github.com/citizenos/citizenos-fe/assets/19904307/a6b0d841-9062-40a0-b818-3841a75d615d)

Here are the custom views for group admins to accept or reject requests from group view

**Comment by ilmartyrk** [comment]
> And I see from the screenshot in this comment above there was this 'We'll inform you" line - should be added in? :)
> 
> [#186 (comment)](https://github.com/citizenos/citizenos-fe/issues/186#issuecomment-1673347106)

@BeccaMelhuish @kevincrepin @ssin1901 I guess we can use the generic topic notification e-mail template for this. I'll create a quick test implementation in my local machine and see how it looks

**Comment by BeccaMelhuish** [comment]
@ilmartyrk For the admin topic requests, can we also add a little number in a circle here, if there is one (or several) pending? (But this could also be for the future if complicated, for now this will do, and we can revisit with more time). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/63d1f8f1-d387-406a-bec2-da3de7091e51)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Copy-wise, to make it clearer that they can only add their own existing topics (and to make it work better whether one or several topics), can we change it to:

**Request to add topics to group**

**Search for existing topics you want added to the group**
You can request to add any topic for which you are admin

**Add a reason for your request**

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/240453b8-418c-4b52-8233-516503a820a9)

**Comment by BeccaMelhuish** [comment]
Please see this related issue too :) 

https://github.com/citizenos/citizenos-fe/issues/1074

**Comment by kevincrepin** [comment]
Was thinking about this missed functionality of removing topics from groups and maybe this could be a solution.
https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=12468-106573&viewport=-15119%2C-16136%2C0.5&t=4Ly7iTmY3x9xE8m8-1&scaling=scale-down&starting-point-node-id=12468%3A106573&show-proto-sidebar=1&mode=design

We have a button "manage topics" next to the add/create topic which allows the admin to remove all topics in one go or go into a sort of "edit mode" which will reveal a remove button per topic. I mainly didn't want to have a repeating remove button on each topic, but if this idea is too vague or does not make sense then I think that would probably be the next suggestion.
My concern is that it might be very clear how to get out of this "edit mode" again...

However this idea does come with an opportunity to do it similarly for members: you can click on the Members tab to see the update. So instead of the bulk actions in the bottom left as we have it now, there would also be a "manage members" option here which would open the same menu as we have now for the bulk actions. But it would be consistent with the management of the topics then.

**Comment by ilmartyrk** [comment]
@kevincrepin I like the solution, though my concern is that with 2 buttons side by side we need another design at around 600px screen width. As currently there isn't enough space there for 2 buttons

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish we haven't implemented the Manage topics in Groups feature yet.

If we are planning to do it in a later phase, can I move the topic from in testing to in Progress or one of the other labels?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Actually just for ease of getting a quick overview (this one became quite long), I've made a new issue for the 'Manage topics' and will close this one (as the original issue is solved) :)
