### ISSUE TITLE
HC Query: Terminology - "Document" or "Topic text"? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#188]
@kevincrepin @ilmartyrk @anettlinno 

For the HC texts, would like to clear up whether we're referring to the text that topic initiators include at the beginning of a topic as the "document" or the "topic text" (or something else). 

Previously I've always referred to is as the "topic text" (though there may be something better), and as I put in my comment on Figma, the word "document" doesn't really work for me - as a document is usually a standalone thing (like a PDF you might attach to the topic, for example) not a section of something that lives online like our topics: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cb6bac55-03eb-4532-9f82-a7d62ea01cb6)

@anettlinno if you agree that "topic text" is also fine, then we would need to make some adjustments to the design as well as just how we talk about it, for example here instead of "Intro" and "Document", could be one of these: 
- "Blurb" and "Intro text"
- "Summary" and "Main body"
(I'm a bit reluctant to use the word "Intro" for the short 500 blurb at the beginning, as I feel like the topic text overall is an "intro text" for the topic - introducing the topic and its context and how to engage in the discussion etc. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b1ead1f0-8602-4cb1-a6ce-df085ea6f719)

 (And anywhere else that uses the word "document", if there are others)

**Comment by anettlinno** [comment]
Triage 90. @BeccaMelhuish good point! Documents does sound in this context as an attachment document or something else... 

"Intro text" and "Topic text" sounds good there. Intro is an introduction text (like the first paragraph in newspapers) and it is well known and intuitively understandable, then I would vote for "Intro text". Topic text is the one where is explained the problem, brought examples etc -- it´s something that describes the topic in more detailed way.

**Comment by anettlinno** [comment]
@MeelikaH what is the structure of an article? Our new topic creation is kind of following this logic... Do you know how different parts are called?

**Comment by MeelikaH** [comment]
@anettlinno not sure what do you mean by "how different parts are called" but the articles structure is available in our website admin centre under "My News" #TEMPLATE - DUPLICATE IT" and it has several functions and blocks which won't be all needed for HQ, I'm sure and are not always all used in each article. However, articles look like this: https://citizenos.com/news/chatgpt-cannot-do-democracy/ or this: https://citizenos.com/news/what-to-believe-when-they-dont-want-us-to-believe-in-anything/ (video, social media feed, quotes, calls to action, etc are optional and possible blocks that can be used or not used). Hope this answers the question :)

**Comment by anettlinno** [comment]
@MeelikaH we were thinking the structure of news articles. Quick Googeling gives [this](https://www.google.com/search?q=structure+of+news+article&oq=structure+of+news+article&aqs=chrome.0.0i19i512j0i19i22i30l9.5902j0j7&sourceid=chrome&ie=UTF-8): 
Headline – tells what the story is about.
Byline – shows who wrote the story.
Lead – tells the most important facts (5 W's)
Body – contains more information and details.
Ending – gives something to think about.

We were just thinking that our redesigned topic creation follows certain structure and we wanted to brainstorm if the topic creation could follow the news creation structure and we could name the fields as different parts of news are named (headline, byline, body text etc). Wanted to check with you what is the structure and vocabulary that is most used and understandable for people :)

In redesign topic creation looks like this: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/d3520957-0c86-473e-9201-cbbb96d0d39c)

**Comment by MeelikaH** [comment]
@anettlinno now I see! Is the document meant to be a document or text? Will any images be used? Might be useful to illustrate the message. I might consider using Text or Description instead of document and consider if we will be enabling uploading any kinds of documents. 

In various journalistic / website publications, you can also:

- Emphasise quotes (similarly to our news section and as often seen in magazines, emphasising some statement, quote or short part of text to catch attention and add visual importance)
- Add fact boxes (highlighting key stats, some sort of links, etc)
- Images (e.g graphs, polls, illustrative photos)
- Videos (tutorials, trailers, short interviews, animations)
- Audio content (e.g interviews, audio advertisements with a call to action, etc)

News article structure is very simple and follows the inverted pyramid principle. Not sure if this is relevant, but sharing a link: https://en.wikipedia.org/wiki/Inverted_pyramid_(journalism)

I think it's summarised rather well here: https://www.vskills.in/certification/blog/structure-of-a-news-report/

**Comment by BeccaMelhuish** [comment]
@anettlinno my thoughts would be let's avoid using the technical language you suggested like "Byline", "Lead" etc, as no-one really knows them. (Even myself as a writer and comms/media student!). 

I think we could keep it simple, and scrap "Document" as I think everyone's agreed now that's not right, and go for:

"Intro" and "Topic text" 

Wdyt? :)

**Comment by kevincrepin** [comment]
Sounds good to me!

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: @kevincrepin could you update the designs to reflect that, on the page discussed above and anywhere else where the word 'document' is used?

**Comment by kevincrepin** [comment]
Should be fixed everywhere.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I noticed it's now "Description" but was agreed here it should be "Topic text" :) 

Tbh "Description" isn't bad though.. we didn't consider that.. Though intro and description are rather close/interchangeable words. 
@kevincrepin @anettlinno tagging you in case you have other thoughts, but I think Topic text is probably still best. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/935457cd-7cfb-4488-8d01-f205fe48c8a0)

**Comment by anettlinno** [comment]
@BeccaMelhuish @ilmartyrk if I think about it in Estonian, then Description is actually more precise in what we want people to do. 

I also checked some [dictionary ](https://www.google.com/search?q=description+meaning&oq=description+meaning&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDIHCAEQABiABDIICAIQABgWGB4yCAgDEAAYFhgeMggIBBAAGBYYHjIICAUQABgWGB4yCAgGEAAYFhgeMggIBxAAGBYYHjIICAgQABgWGB4yCAgJEAAYFhge0gEIMzA2M2owajeoAgCwAgA&sourceid=chrome&ie=UTF-8)explanations: 
- a spoken or written account of a person, object, or event
- a statement that tells you how something or someone looks, sounds, etc. : words that describe something or someone
- The meaning of DESCRIPTION is an act of describing; specifically : discourse intended to give a mental image of something experienced.

Description leads people to describe an object, or person, or situation, or problem. Topic text is and sounds more technical. So, I would even vote for description :)

**Comment by BeccaMelhuish** [comment]
@anettlinno OK yes let's leave it as it is then! We'll hopefully see in the user tests if people are getting confused anyway. Plus it'll work better for if we have [this](https://github.com/citizenos/citizenos-fe/issues/251) (not being a text for the topic overall, but just for a certain phase).

**Comment by BeccaMelhuish** [comment]
Have changed this everywhere in the translation strings now so closing :)
