### ISSUE TITLE
BUG: Topic "Not found" even after logging in when accessing from notifications email

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#191]
A couple of times now when I've clicked through to a topic from a notification email (both times for the COS Strategy topic, though I assume that's not relevant), this is what has happened: 

- It gives me the "Not found, recover from this unfortunate event by logging in" message.
- I log in.
- It then gives me just "Not found" (screenshot below).
- I then have to go to "My topics" to find the topic I'm looking for and access it that way.  

I just tried following the same link (in notifications email) after having just logged in recently and it did work smoothly. But I assume that's because I was already logged in (which most people wouldn't be). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/82d4ce92-4a97-42e0-9ab6-0c5c4285ff93)

**Comment by ssin1901** [comment]
@ilmartyrk I also got this "Not found" message when switching between two accounts

<img width="1439" alt="Screenshot 2023-08-16 at 11 18 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b4535058-5205-4226-8a69-04bf69449815">

**Comment by ssin1901** [comment]
@ilmartyrk we can talk about this separately. I did not get any Not Found errors but the Create Topics and Login sometimes didn't work when I was running automated tests.
