### ISSUE TITLE
BUG: Number of replies not displaying correctly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#192]
Here's some screenshots of what's happening in the COS strategy document - it initially only shows 1 reply, when actually there are 2. It's only once I'd clicked on the first reply, that it showed that there was in fact 1 more reply hiding underneath: 

Initial view: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f9eea2ba-52ee-4380-aac5-00de34f379c6)

Next view:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fd3b0f3c-a9e9-4af3-a0a2-9b7a7e910ea5)

Next view:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c9eba7c4-50e1-4eb2-8190-8dcb1e07caa1)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk I was able to replicate this issue in Mac OS Safari but not Mac OS Google Chrome or Windows Edge. See screenshots below

<img width="729" alt="Screenshot 2023-08-16 at 11 21 33" src="https://github.com/citizenos/citizenos-fe/assets/72747107/145f5c60-2ce2-4134-9e9c-ca56562870ed">
<img width="800" alt="Screenshot 2023-08-16 at 11 17 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/65b6725d-3f34-4ba8-8a55-8ec5746195e7">

**Comment by anettlinno** [comment]
Triage 88. Issue comes from when User replies to a reply. This is confusing yes, as if there are many replies under one comment then there is ongoing discussion and therefore it would be important to show users replies of the replies of the replies... 
Let´s show all replies count under the main argument.

Time estimation 20 min. Sending it to do.
