### ISSUE TITLE
Suggestion: Allow "Point of information" the same number of characters as other arguments

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#193]
@anettlinno @ilmartyrk A suggestion for the redesign - could we allow a "Point of information" to have the same number of characters as other arguments? I feel like there are a lot of situations where people might want to use this more "neutral" choice for their input, without being cut short as a result. 

For example, for me here it was quite surprising to have it cut short, and not ideal to have to continue in replies: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1c1881f2-fdfb-46cb-bdbd-72f366c7d253)

**Comment by anettlinno** [comment]
I very much agree and I have noticed that this is confusing for Users as well. From the UX side it won´t come out clearly that POI differs much from pro and con argument. AND sometimes there is no opposition in the topic, but rather a dialogue and for that POI or neutral argument/comment fits the best. So, I support changing POIs characters to the same amount as arguments has.

**Comment by anettlinno** [comment]
Triage 89. Let´s change POI´s characters to 2048. 
Time estimation 5 min. Sending it To Do.

**Comment by ilmartyrk** [comment]
Fixed in redesign
