### ISSUE TITLE
Incorrect error message when Argument description has no text

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#194]
**What is the problem?**
When the user adds an Argument title but not a description, they receive the following notification/

<img width="1438" alt="Screenshot 2023-08-16 at 11 11 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3aa09f6d-7972-4dab-8a4f-3eeec95051bf">

**Why is this a problem?**
The actual issue is that the user must add a title as well as a description. However, the error message above completely misleads the user.

**Possible solution.**
The error message should say something like "Argument description cannot be empty"

**Comment by anettlinno** [comment]
Triage 89. Needs to create new error message for this issue, like "Argument field is missing text"
@BeccaMelhuish we kindly ask your copy-magic help here :)

**Comment by BeccaMelhuish** [comment]
@anettlinno what about this: 
"Argument field empty. Please explain your argument."

**Comment by anettlinno** [comment]
Thanks @BeccaMelhuish! :) Let´s go with that!
Sending it To Do.
