### ISSUE TITLE
HC Query: What comes under the "Edit group" tabs?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#197]
@kevincrepin One thing that's missing (unless I've missed it) from the Figma is what comes under the Settings and Tags tabs, in the "Edit group" pop-up. 

For the HC texts, am wondering which items from the "Settings" in group creation will be on the "Tags" tab - will it be just Tags, or also Categories, as they are quite similar? (Country and language I assume not, though that's grouped with Categories in the other Settings section, so maybe)? 

Or maybe it doesn't need a 'Tags' tab at all - just "Information" and "Settings" (with Tags, Categories etc. all under that)?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f6387610-3da0-45de-a18d-de2b8d583217)

Tagging @anettlinno and @ilmartyrk too for info.

**Comment by kevincrepin** [comment]
The Settings and Tags tabs can be seen from here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=475%3A60483&mode=design&t=YG0SmSCvTqN779T5-1

**Comment by BeccaMelhuish** [comment]
Ah perfect, thank you @kevincrepin! :)
