### ISSUE TITLE
Email updates need defining

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#198]
@anettlinno @ilmartyrk For the HC (but also for the product generally of course :)), as per @kevincrepin's comment below these email updates (engagement updates and analytics) need defining - re what exactly they'll include. 

Tagging @MeelikaH too in case it's relevant (as it's a communication of sorts), and am also wondering if there might be an opportunity for including opting into the Citizen OS newsletter in the same place (or if we somehow combine them)..  

Feel like @ssin1901 may want to input too :) 

(Wondering if it's something worth discussing in a Monthly meeting even, to get everyone's ideas/input/feelings on it, as it's something quite different to what we've done before? With Kevin in attendance though preferably, if so!) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/96454f99-93e2-4d56-bfaf-5c9b985c565d)

**Comment by MeelikaH** [comment]
I would like to discuss briefly but overall I have the feeling that HC, we should keep focus on help and relevant information. I'd love to see a button to advertise our future newsletter & social media channels on the platform, but currently not sure if this should also be somewhere visible in the HC part.

**Comment by BeccaMelhuish** [comment]
Ah sorry @MeelikaH, I didn't make that clear at all! These "HC QUERY" issues I'm making on Github are queries about the platform, so that I can write the texts for the HC. So the screenshot above is of the "notifications management" bit of the platform redesign, where there is a bit that defines the regularity of the "email updates" (a new things we've not done before).

**Comment by MeelikaH** [comment]
@BeccaMelhuish oh, thanks for explaining. To me, looking it without having previously thought about it, so - in a way as a potential user, I'm not sure what e-mail updates are exactly about and why should I be interested in them. Like, what statistics? What updates? All the updates? Certain updates? Can I choose which ones? I see I can choose how often, but not what topics? Currently, hard to comment as the purpose and content is unclear and as a user, I would not want to subscribe.

In regard of newsletter, could it be a little button with a call to action under the "manage e-mail options" part? We should mention it's a monthly newsletter with inspirational case studies, news about e-democracy and ways to engage in our projects (open calls, events, etc).

**Comment by anettlinno** [comment]
Triage 90. We have thought about providing topic admins statistics and analytics after the discussion / voting / ideation has ended (and it was also requested by the people in focus group interviews). But it should be available on the platform right after the engagement action. We discussed it in Triage meeting and we would not provide an opportunity to "order" weekly or monthly updates via email. 

Marketing content is separate topic. If User could subscribe to a newsletter under the **Notifications**, then that could work.

**Comment by ssin1901** [comment]
@anettlinno @BeccaMelhuish @MeelikaH I would also recommend to not use "analytics" anywhere for Marketing, and instead specify exactly what is included (i.e activity count). I think Kevin raised the same issue. 

Analytics is way too broad, and can be misleading. 

I would actually like to raise the issue of analytics on the platform sometime in November/December Monthly Meetings after getting input from the whole team.

**Comment by MeelikaH** [comment]
@anettlinno and @BeccaMelhuish my former comments stands that if we offer any statistical summary, the information should be easy to understand for the user (which to get, when, what type of summaries, etc). I think the idea is great. I would keep the newsletter away from this part. I feel it becomes too much. Proposal is to find a permanent little tab throughout the platform experience where people can always subscribe for newsletters.

**Comment by anettlinno** [comment]
In redesign Phase I this feature does not fit in (as it would need proper discussion among our team and also proper use case AND it´s time-heavy development). But for further discussion and later developments we can keep the issue open. 

I´m moving it to In Preparation.

**Comment by BeccaMelhuish** [comment]
@anettlinno OK great, so just to confirm, for the HC texts I will ignore this bit as we won't be keeping it, and the newsletter sign-ups will be something for a later phase? Will proceed like this unless anyone corrects me :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d4dd7f06-5304-4189-bc20-bba58e381f6d)

**Comment by anettlinno** [comment]
Yes, @BeccaMelhuish, correct. For the HC texts, please do not add it.

**Comment by kevincrepin** [comment]
Also removed from the design (kept it somewhere in case we bring it back)

**Comment by BeccaMelhuish** [comment]
No longer a HC query as I have the answer I needed, so have removed HC tag and edited title, but leaving open as per @anettlinno's comment above :)

**Comment by MeelikaH** [comment]
@anettlinno and @BeccaMelhuish is anything still needed from me at this point? Or can I close this thread for myself?

**Comment by BeccaMelhuish** [comment]
@MeelikaH all resolved, thank you! (But being kept open for further consideration in phase 2 I believe)

**Comment by anettlinno** [comment]
Moving this discussion into Redesign Phase II

**Comment by BeccaMelhuish** [comment]
I will close this seeing as we don't have a newsletter to link to :) 
We can always make a new issue when we have one
