### ISSUE TITLE
HC QUERY: Vote delegation needs clarification

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#199]
@anettlinno @ilmartyrk some input needed from you. Tagging @ssin1901 too in case :) 

For the HC and for the design, would be good to have some clarification of how the vote delegation works.

As per these Figma comments between @kevincrepin and I, is it correct that the person who delegated gets to find out how the person they delegated to actually voted (as the design currently states)?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/981e2bec-ed0a-4dfc-b937-d89278980afb)

What is this bit about accumulating/owning votes? Is that something new? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7f7103ea-a3bb-4173-863d-8a2b697e4de1)

Also, in the HC currently we say: "The delegated person won’t be aware that you have delegated your vote to them, unless you tell them yourself." Is this still the case? 
EDIT 8 Sept: I see now that the person does know before voting that they have been delegated to. (I think I remember Margo saying that they wouldn't/shouldn't know, in his vision of liquid democracy, but presumably this has been discussed and decided against now): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0cb2750b-1d70-4074-85d4-16893331dd7e)

**Comment by BeccaMelhuish** [comment]
P.S. Wondering now also whether people have/should have a choice to not use the delegated votes, and "send them back" to their original owners? For example, if they are really torn what way to vote themselves, they might not want the extra 'weight' of other people's votes on their decision..

**Comment by kevincrepin** [comment]
This vaguely rings a bell and I think we spoke about this, but not sure if any decision was made around this... I get your point but also on the other hand why would you feel the weight if what you're voting for is anyways your choice? 

Potentially big topic :D

**Comment by anettlinno** [comment]
In our current version we do not show people if they have delegated votes. They can possibly realize that after they have voted and vote count increases more than one vote. BUT this is a discussion point. If to think about offline vote delegation then people who have been delegated votes also knows how many votes they have. I don´t quite remember, what were the arguments that in offline vote delegation we do not show that... 
@ilmartyrk @oksks do you remember?

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: In phase 1, all will happen as it currently does. Won't show if you have delegated votes, or how a person you delegated to voted. And then we'll discuss further for phase 2.  
@ilmartyrk FYI.

**Comment by BeccaMelhuish** [comment]
Just bringing this one to attention again, as I notice in a user test it still says this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9621ae1f-5b9b-4d6f-8be5-218f38f949f0)

I guess we need a new text for here, which off the top of my head could be: 

"They won't know they are voting for you. Your vote will be the same as theirs, but you won't see evidence of how they've voted."
