### ISSUE TITLE
Error message while accessing Public Topics

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#203]
**What is the problem?**
User received an error message while accessing public topics (see screenshot)

<img width="1326" alt="Screenshot 2023-08-18 at 16 54 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/862747a2-65e6-4f3e-9af0-99d7911d33e4">

**Why is this a problem?**
User should be able to access public topics while logged in and logged out without error messages

**Possible solution.**
@ilmartyrk not sure if this is still a bug

**Comment by ilmartyrk** [comment]
@ssin1901 can you describe a little more, how did you get this error?

**Comment by ssin1901** [comment]
@ilmartyrk first Becca was not able to access Public Topics, until she logged in. Somehow it worked for me but then a few minutes later, I tried again (while logged out) and got this message. 

Issue is difficult to replicate, I could not replicate it again after that. Luckily had taken a screenshot when it happened.

**Comment by anettlinno** [comment]
Triage 88. Could not replicate the issue. Closing the issue.
