### ISSUE TITLE
Admin cannot close topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#204]
**What is the problem?**
When a user is a topic admin and tries to close the topic, they receive this message (see screenshot) on Google Chrome). 

<img width="1440" alt="Screenshot 2023-08-21 at 12 46 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ceddff4a-ad2d-4f04-8859-1f125b89a3b6">

**Why is this a problem?**

User cannot close topic, a very critical feature for our platform. Also creates confusion about roles.

**Possible solution.**
User should be able to close the topic when logged in as admin

**Comment by ilmartyrk** [comment]
@ssin1901 checked the issue, seems that topic is not reloaded after clicking the close topic button and if you click it the second time, it will give you that error.

**Comment by ssin1901** [comment]
@ilmartyrk tested and working
