### ISSUE TITLE
Multiple voting interface is confusing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#205]
**What is the problem?**
When a user adds 51 votes, the options they select move to the top not for the results but also while displaying options (see screenshot). 
<img width="1147" alt="Screenshot 2023-08-21 at 15 01 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/15dd97a6-7447-4b87-99f4-af8bbb1b41f4">

**Why is this a problem?**
It is very difficult for the user to orient themselves.
This is helpful for prioritizing the bugfix.

**Possible solution.**
There is no need to show the user all the possible options, just organise them by graph (see screenshot)
<img width="1332" alt="Screenshot 2023-08-21 at 15 01 04" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a9810741-5281-41b4-a8b6-e551d8997304">

**Comment by ilmartyrk** [comment]
Ok I got that this was an issue previously too. I don't understand what should be the proper fix in here. Remove the labeling, or ignore the options without votes? I guess it is anyway an extreme case to use that many options in a voting and it is confusing for users to go through all of them.

**Comment by ssin1901** [comment]
@ilmartyrk bug fix is an improvement on https://github.com/citizenos/citizenos-fe/issues/161 where the alphabetical ordering was also incorrect. 

I still find it confusing how it is displayed but maybe the issue is not so urgent.

**Comment by ssin1901** [comment]
@ilmartyrk the graph in the test environment looks really good to me! I will ask Agustina for her opinion as well, as she has a use case coming up.

<img width="676" alt="Screenshot 2023-08-22 at 10 06 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/93b522cd-962d-405e-8be2-e4ecfe476bfe">

**Comment by anettlinno** [comment]
Triage 89. Issue fixed. Closing the issue.
