### ISSUE TITLE
Send to follow up button in voting does not work as intended 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#208]
**What is the problem?**
When all votes are in, and the topic owner clicks Send to follow up via the button indicated in the screenshot (see screenshot) 
<img width="1005" alt="Screenshot 2023-08-27 at 18 02 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/99f72887-4708-4cb0-b859-dafb436e6644">

the user is directed to this interface (see screenshot) 
<img width="1017" alt="Screenshot 2023-08-27 at 18 02 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5f9028dc-9150-49db-9d14-8c0c18c78dfc">

and there is no follow up (see screenshot)
<img width="1019" alt="Screenshot 2023-08-27 at 18 02 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/16d75402-df2c-4b6f-b34a-7692e80c4ee4">

**Why is this a problem?**
Quite critical. User can longer send their topic to follow up.

**Possible solution.**
User should be able to send their topic to follow up regardless of whether they click the button or the item in the right sidebar menu.

**Comment by anettlinno** [comment]
Triage 88. Important fix but should be quite quick one, time estimation 15 min. Sending it to do.

**Comment by ilmartyrk** [comment]
Was fixed inside another fix
