### ISSUE TITLE
When a topic is closed follow up tab is still there despite being blank

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#209]
**What is the problem?**
When a user closes a topic and a vote has not taken place, the follow up tab is still there (screenshot attached)
<img width="1016" alt="Screenshot 2023-08-29 at 15 00 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/61495653-0100-4d9c-a519-a76bc63198fc">

This is despite the user not having initiated any activity, which means that follow up is just showing blank space (screenshot attached)
<img width="1014" alt="Screenshot 2023-08-29 at 15 01 05" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d331a8cc-b1eb-41e2-9b60-4175536e8913">

**Why is this a problem?**
Decision making process becomes confusing for the user

**Possible solution.**
When a topic that has been closed has not gone into voting and therefore into follow up, only view tab should be displayed.

**Comment by anettlinno** [comment]
Triage 88. Decided not to fix it in current version, but we will check if the same UX is in redesign version as well. 

Sending it to UX/UI redesign.
