### ISSUE TITLE
Some code in set topic notifications 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#210]
**What is the problem?**
When a user clicks on topic notifications, instead of title they receive a coding error (see screenshot)

<img width="1012" alt="Screenshot 2023-08-29 at 15 35 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1f5f9f49-a5e7-4a03-b717-41d37ce301c3">

**Why is this a problem?**
Coding error 

**Possible solution.**
When the default title is not edited, activity feed reflects "Your topic title here". It should be the same in Notifications.

**Comment by anettlinno** [comment]
Triage 88. Quick fix. Estimation, 15 min. Sending it to do.

**Comment by ssin1901** [comment]
@ilmartyrk this issue came up again (see screenshot)

<img width="1203" alt="Screenshot 2023-09-25 at 14 42 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3431e691-aadc-48f8-ab1d-879f5742f0f8">
