### ISSUE TITLE
When you expand search bar then the close button disappears and the search menu gets pushed down 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#211]
**What is the problem?**
When you search for an item and expand the search results, the close button disappears and then the search menu gets pushed down, so that the background is partly visible (see screenshot)

<img width="1104" alt="Screenshot 2023-08-30 at 15 09 32" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b82818c0-a6a3-47c8-9503-fff4db805d87">

**Why is this a problem?**
Very confusing for the users, as they can neither focus on search results and then cannot close the search menu without refreshing the page (assuming they know that this will make it disappear).

**Possible solution.**
Search bar should be moved to the top and the x close button should be visible

**Comment by anettlinno** [comment]
Triage 88. Bug replicated. Quick fix. Estimation 15 min. Sending it to do.
