### ISSUE TITLE
Problem with pagination

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#212]
**What is the problem?**
Pagination is triggered by more than 5 replies (see screenshot 1) but when the user clicks on the second page, it is blank (see screenshot 2)
<img width="1013" alt="Screenshot 2023-09-03 at 17 59 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/40e5374f-22eb-4616-a583-439fae09290d">

<img width="1011" alt="Screenshot 2023-09-03 at 17 59 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5f2e1208-2abe-4258-a50c-e7d525327067">

**Why is this a problem?**
Wastes the users time as they would click on the button expecting to see more results on the second page

**Possible solution.**
Pagination logic should be more clear and there should always be results on the second page

**Comment by anettlinno** [comment]
Triage 88. Currently replies are also counted inside arguments and this triggers the pagination page numbers. Quick fix, aprox.dev time 15 minutes. Sending it to do.
