### ISSUE TITLE
HC QUERY: Anonymity

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#214]
@ilmartyrk @anettlinno @kevincrepin For the Help Centre texts, two things to ask regarding anonymity:

1. I wanted to double check that it's deliberate that we've changed our stance on allowing admins to see who has voted before a vote has ended. Previously we had [this Help text](https://citizenos.com/help/voting/why-admins-cant-see-who-has-voted-while-a-vote-is-in-progress/) explain our philosophy on why not allowing it is more democratic. But now on the Redesign it's possible. (No objections to the change from me, just wanted to check the change is correct and I should delete the Help text). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2268239a-5179-481a-a785-b0ae7d7c9a32)

2. How will voting anonymity work on the new platform? I know previously it was the case that what a participant votes for is anonymous to everyone except the admins, who can see exactly who voted for what. Will this remain the same, or it will be possible to have fully anonymous voting now, so that even admins can't see an individual's vote? (We didn't actually have a Help text explaining this, but I think it's an important thing to clarify).

**Comment by anettlinno** [comment]
Triage 90. So far it has been our philosophy to not allow to see who has voted, as topic initiators /admins could somehow impact people who haven´t voted yet. But we can open this discussion here again. What are the pros and cons for that? 

100% anonymous voting is in the pipeline and it´s coming, but this is totally separate from our current voting system. This we should also discuss deeper once we´re there.

**Comment by BeccaMelhuish** [comment]
@anettlinno 

For 1. I don't have a strong opinion either way, but my feeling is that it's a bit of an invasion of privacy for the admin to see whether or not you've voted, and that having the "send a vote reminder" feature means they are able to chase up people who haven't yet voted, without knowing who they are :) (And I don't really see a need for them to know, other than for that purpose?).  

And for 2. OK good to know, I will keep it [like this](https://citizenos.com/help/voting/why-voting-is-not-fully-anonymous/) (or similar) for now, and then we can update when it's fully anonymous.

**Comment by kevincrepin** [comment]
Personally I think it's ok to see who voted and who hasn't as long as you can't see **how** they voted. For the admin it's a nice tool to understand who they need to encourage to vote, who they should remind, etc.

I think there might be some kind of preconceived notion that people who haven't voted are therefor not engaged, but when looking at it neutrally there will probably often be a lot of people who don't actually take their participation to that level. And it's also nice to see as a topic owner what kind of traction does your topic get.

Alternatively we could also think about showing how many ppl haven't voted in straight numbers or percentages. And keep everything at a higher level.

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: Decided that we shouldn't show who has voted. 
@kevincrepin would you be able to edit the design to reflect this?
@ilmartyrk FYI.

**Comment by kevincrepin** [comment]
Let's replace the "view who voted" with "Send reminder to vote" action which opens up this preview mail
![Screenshot 2023-10-13 at 17 07 36](https://github.com/citizenos/citizenos-fe/assets/26792281/757ededa-5407-4f4f-949c-d3cb31c92c70)
![Who voted - Desktop](https://github.com/citizenos/citizenos-fe/assets/26792281/93dc88ad-34ac-4dbc-ace0-8fa472e3a5ad)

**Comment by anettlinno** [comment]
Triage 95. 

- In vote delegation topics we are currently missing "View who voted" but in Phase I we´ll add it also there. 
- "Send reminder to vote" will be published only when reminders are yet not sent as currently we allow to send reminders only once during the voting.

Sending it To Do.

**Comment by ilmartyrk** [comment]
@anettlinno if I remember correctly, in vote delegation we are missing vote count, not view who voted.

**Comment by anettlinno** [comment]
Yes, you are right @ilmartyrk and now it´s there and works nicely :)
