### ISSUE TITLE
HC QUERY: DDOC mid-voting

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#215]
@ilmartyrk @anettlinno @kevincrepin 

For the HC texts, two things relating to the "Download DDOC" button here, which is mid-vote (while the vote is still ongoing), and in the "topic owner" view: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ae72bd04-b357-48f4-9068-abb303c0ab54)

1. Wondering what it's for, at this point in the vote (still 30 days to go)? Is it the individual file for the person to download their own individual vote? And if so, what's the scenario for someone wanting to download this? 

2. Thinking we should call it something else? As DDOC is such an unfamiliar abbreviation, and I think even those who are somewhat familiar with it (like I am) would be confused by what's in it (like I am) :)

**Comment by anettlinno** [comment]
Triage 90. It should be "Download your signed vote (BDOC file)" as on our current platform. This will be used in redesign as well.

**Comment by BeccaMelhuish** [comment]
@anettlinno OK thank you! 

For simplicity, could the text just be "Download your vote"? So then it will be "Edit your vote" and "Download your vote" next to each other - nice and consistent and easy to digest/understand. 

(And presumably this will only show up for people who signed their vote with e-ID?) 

Could you give me the reasons why someone would want to download their own vote BDOC file? May help me write a text that makes sense if I understand the need :)

And is there anything about the BDOC file that we need to explain? I feel like most people won't know what one is, or is it something people with e-ID are already very familiar with?

**Comment by kevincrepin** [comment]
I would say let's have "Download your vote (.BDOC)". I's good to keep the file extension there for understanding what will be downloaded.

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: Why download it?: Follow the e-voting system. If suspicious, can download vote everywhere. Then later when results published, can prove vote. Everyone knows what .bdoc file is in Estonia.

**Comment by BeccaMelhuish** [comment]
@anettlinno I'm wondering if we should only allow people to download their own vote after the vote has actually ended? As they can change their vote at any point up until the vote deadline/closure. So their downloaded vote wouldn't 100% prove what they had voted for, if they did want to use it as evidence in any dispute? 

Or some sort of note perhaps, pointing out that they can download it now, but it will be more valid as a record if they download it after the vote has ended?
