### ISSUE TITLE
HC QUERY: Closing/editing vote settings once vote is underway

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#216]
@kevincrepin, for the HC texts, a couple of questions about changes to the vote once it's already underway: 

1. Is it still possible to close a vote manually (rather than relying on a deadline)? 
2. Is it still possible to edit a vote's settings once it's underway?  
3. Is it still possible to add a deadline once it's underway (after starting it without one)?
3. If so, would these things be in the menu circled below (there is nothing there on the prototype currently, and I can't find these actions anywhere else)?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3bb23753-c209-47a2-94de-a9fb708a6ab3)

**Comment by anettlinno** [comment]
Triage 90. We are missing drop-down menu, but we can reuse the existing menus.
Menu should contain: 
- Close a vote manually
- Change the deadline
- Automatic reminder for users who haven´t voted yet

**Comment by kevincrepin** [comment]
Yes, this component exists even if this specific spot in the prototype doesn't have it implemented ;)

**Comment by BeccaMelhuish** [comment]
Ah OK thanks Kevin I will try to find it :)

**Comment by kevincrepin** [comment]
Ah no, I mean the general menu component exists :) But Anett listed the actions this menu would hold above.

**Comment by BeccaMelhuish** [comment]
Ah gotcha! In that case I'd suggest some tweaks to the wording :) 

- Close vote manually
- Change vote deadline
- Send vote reminders

**Comment by BeccaMelhuish** [comment]
Also, @kevincrepin what if someone sets up the vote, then realises they've made a mistake - i.e. they meant to make it mandatory to vote with e-ID, or they missed off an option from the list of vote entries. What are their next steps in such a case?

**Comment by anettlinno** [comment]
@BeccaMelhuish If voting has already started (published), then it is not possible to change vote entries or voting rights, because all people should vote the same version. For double-checking voting actions, we have draft and preview in redesign version, where Admin User should do the final check.

**Comment by BeccaMelhuish** [comment]
Makes sense, thanks!

**Comment by BeccaMelhuish** [comment]
Closing this now as got what I needed for the HC texts, though @anettlinno I'm not sure what should happen to my suggested wording above (for the menu) at this point..

**Comment by BeccaMelhuish** [comment]
Actually for the menu wording, presumably it should be this (changes in bold) to cover when there wasn't already a deadline set: 

- Close vote manually
- **Add or edit** vote deadline
- Send vote reminders

**Comment by anettlinno** [comment]
Menu is still missing in UX/UI test environment and needs to be implemented with the wording that @BeccaMelhuish proposed. Thanks!

**Comment by anettlinno** [comment]
Triage 95. Sending topic reminder needs some research, but we have the designs. 
Sending it To DO.
