### ISSUE TITLE
Code in the view argument anyway window

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#221]
**What is the problem?**
When a user goes to an argument that has been deleted and clicks on Why, the window that pops up has some unnecessary code (see screenshot)
<img width="988" alt="Screenshot 2023-09-14 at 16 45 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fe901e1a-d259-4aba-b6b4-ffa4ab9e2864">

**Why is this a problem?**
Does not look professional to have code visible to our users on the front-end.

**Possible solution.**
Code should be removed and replaced with a user-friendly link

**Comment by anettlinno** [comment]
Triage 89. Fixing this issue together with #176. 
Fixed during Triage meeting :)
