### ISSUE TITLE
Etherpad version history doesn't seem to be working 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#222]
**What is the problem?**
Not sure if this is a bug or an enhancement but currently when the user goes to Etherpad version history (see screenshot 1) they have to scroll down quite a bit to access the button (see screenshot 2)
<img width="1012" alt="Screenshot 2023-09-14 at 16 52 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6611eae2-00ba-4c0f-9894-5ab3e6c1b94d">
<img width="1014" alt="Screenshot 2023-09-14 at 16 53 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/79adb675-08a4-40d1-b664-1b33841a5ddf">
When they see finally see the button, it does not restore the previous version (which would be the expected flow) but takes them back to the most recent version (see screenshot)
<img width="1014" alt="Screenshot 2023-09-14 at 16 53 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cd593023-4c0b-4e69-8b11-f5103a0b8be5">

**Why is this a problem?**
Confusing for the user, as they would initially assume that they can restore old versions

**Possible solution.**
Less scrolling as well as the option to restore older versions of the document. Users who have set up Notifications under topics, should be notified that the document was modified to an older version.

**Comment by anettlinno** [comment]
Triage 89. Is is well-known issue and we have had problems with this since the beginning of times :) As it´s Etherpad´s internal issue, we should not do anything with that at least in this moment, as it would take a lot of time fixing it and could break other things.
Closing this issue with no further actions.
