### ISSUE TITLE
Cannot change profile picture in Safari

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#223]
**What is the problem?**
In Safari when a user tries to change their profile picture with a photo that is above 500 kb they get a success message instead of a warning (see screenshot)

<img width="1298" alt="Screenshot 2023-09-14 at 19 24 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f18b56bf-3598-4e20-ac67-59c4ef602c8d">

Even after resizing the screenshot, the profile picture is not updated, even after a hard refresh. In Chrome, the profile picture refreshed.

Describe, how this bug stops a user from performing a desired activity.
User cannot update profile picture, for example to use a more professional or appropriate one. 

**Possible solution.**
User should be able to update profile picture.

**Comment by anettlinno** [comment]
Triage 89. Needs investigation. 30 min. Sending to investigation.
