### ISSUE TITLE
Unclear logic in Topic Notifications display

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#224]
**What is the problem?**
When a user goes to My Account->Notifications a list of topics is displayed in seemingly a descending order (see screenshot). When the user toggles the notification the topic remains in the same order. 
<img width="1052" alt="Screenshot 2023-09-14 at 19 41 44" src="https://github.com/citizenos/citizenos-fe/assets/72747107/327b60fa-b023-4366-9831-429df274eb34">

However, when the user confirms that they would like to switch off the topic, the topic disappears and appears again at some seemingly random place (see screenshot).
<img width="1062" alt="Screenshot 2023-09-14 at 19 43 53" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a94b278f-13e6-4d52-a495-34ce25a167d0">

+ add screenshot / screencast whenever possible

**Why is this a problem?**
NB! Issue is difficult to replicate as it does not always occur.

**Possible solution.**
Topic order should not be affected by the status of Notifications

**Comment by anettlinno** [comment]
Triage 89. Topics could be listed by latest activity. Est. dev. time 1 hour. Sending it To Do.
