### ISSUE TITLE
HC Query: How will digital signature voting work? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#229]
@ilmartyrk @anettlinno @kevincrepin 

For the HC texts, a few queries about how digital signature voting will work, and whether there are any major changes to the way it will work compared to what we currently have. 

**Do we need the flow designed for how a user votes electronically?** 
So far there isn't one, but Ilmar said on Slack that it is similar to login. Still I wonder how a user will select that they want to vote digitally, as currently there is only one option "Submit vote". Or perhaps it will be the case that however the admin has set up the vote will dictate whether e-signing opens when they click it, or the vote just gets submitted directly? (Is there ever a case where the user can choose)? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7d45483d-3650-4012-b6dd-1dfeb3172d8c)

**Do we need the flow designed for how to download voting results if the vote included digital signatures?** 
As currently, there is just one button "Download voting results", but in the past we have given admins a choice of what the folder contains ('human-readable' etc... Which we agreed we'll change now!). So I'm wondering how this flow of them choosing which file to download will work in the redesign, if it will still be the case: 
- https://citizenos.com/help/voting/downloading-digital-signature-vote-files-estonia-only  
- https://citizenos.com/help/voting/submitting-signatures-to-the-ariregister-riigikogu-local-government-estonia-only

Also wondering if the contents of the folder they download will be the exact same, e.g.:
- https://citizenos.com/help/voting/digital-signature-voting-results-folder-contents-estonia-only

(Please check these 3 current help texts to see if there is anything that will be different, other than basic UI - where buttons are, etc.)

**Comment by anettlinno** [comment]
The illustration above is when Admin User has selected soft authentication. If Admin chooses hard authentication, then we should also notify Users that this is e-ID voting and requires e-ID signing. Like we currently have: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/a3961b2a-a8b3-4dab-a4ce-d0937f2829ba)

@kevincrepin I think we are missing:

1. The flow of e-ID voting (what happens after User is clicking on "Submit your vote" button)
2. The flow what happens after Admin User clicks on "Download voting results" and for that we already have separate issue #230

**Comment by anettlinno** [comment]
Triage 90. In http://redesign.app.citizenos.com/ we have e-ID login and voting flow that is designed by @ilmartyrk :)) 
@kevincrepin, when checking the whole redesign project in the end of October, please check that as well :) 

Human-readable and machine readable are still missing. @BeccaMelhuish you mentioned: _'human-readable' etc... Which we agreed we'll change now!_ Please remind us, what we were supposed to change in here?

**Comment by BeccaMelhuish** [comment]
@anettlinno please see this old issue for what I meant, not sure if it is still like this for e-ID voting on the current version, but we'd definitely want it different for the new one.. 
https://github.com/citizenos/citizenos-fe-old/issues/1216

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: Will keep human and machine readable for now, like the current platform, until we find something better.
