### ISSUE TITLE
HC Query: Vote download folder stays the same?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#230]
@ilmartyrk @anettlinno For the HC texts, I assume everything will stay the same for the contents of the vote download folder, but please give it a look over just to be sure :) 

- https://citizenos.com/help/voting/downloading-voting-results/

**Comment by anettlinno** [comment]
Yes, but I think we are missing the container design, @kevincrepin? :) At least I couldn´t find it in Figma...

**Comment by anettlinno** [comment]
Triage 90. Content of the folder remains the same @BeccaMelhuish and @ilmartyrk said that we don´t need container design.

**Comment by BeccaMelhuish** [comment]
@kevincrepin is there a design for how this bit will look for admins, or it will just be a case of adding 'Download vote results' next to (presumably before) 'Download your vote', which would download the folder immediately? 
(Edit: I'm sure I have seen this somewhere, but struggling to track it down in the files). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/86885d96-cbc3-44e1-8e79-f3c9255a1992)

**Comment by BeccaMelhuish** [comment]
Also @ilmartyrk @anettlinno, we say in the HC that there is a PDF of the results in the folder, but there doesn't seem to be when I just tried? Should it be there, or should I remove it?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5c38b700-3ac1-40dc-a50a-91b749b69798)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d9f61a16-d262-4440-9157-8acf0d6dcc09)

**Comment by anettlinno** [comment]
I also remember that we already had it somewhere, but cannot find it :)
@kevincrepin I think we are missing "Download vote results" (admin view) from the designs. 

@BeccaMelhuish as for the PDF results graphic, let´s just remove this from the HC now and we´ll fix it in redesign Phase II together with the issue #261

**Comment by anettlinno** [comment]
Ahh, @kevincrepin I found the vote download duplicate issue here: citizenos/citizenos-fe/issues/142 

You refer to [this ](https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?mode=dev)Figma file, but it´s still "Download your vote" and not admin´s view (where should also be "Download vote results"

I will close this issue as vote results folder will be fixed with issue #261 

AND

Vote download issue discussion is already taking place in issue #142
