### ISSUE TITLE
HC QUERY: Impact on other phases after moving to "Follow up" phase

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#231]
@ilmartyrk @anettlinno @kevincrepin

For the HC texts (though also for the platform text shown below), I'd like to be sure exactly what will/won't be possible once a topic has been moved into follow-up phase.

- No more editing of the topic text: I understand from the below text (and current platform). 
- Voting: will it still be possible to vote when a topic has a follow-up phase? Does moving it to follow-up automatically close the vote as is the case with our current platform, or these are two separate actions now? 
- Discussions: can people still add arguments, comments, reactions, anything else to the discussion part once it's in follow up? 
- Anything else that is affected by this? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7c449923-6b16-4303-a46d-d1c4ca57f4bf)

And just a thought off the back of this: is it always logical/necessary to block certain actions in other phases when a follow-up phase has been added? I'm wondering if there are use cases where people would like to add things to follow-up while the process is still ongoing.. And wondering how much benefit it brings to close it off..

**Comment by anettlinno** [comment]
If topic is being sent to the follow-up phase, then:

- Users can no longer (co)edit the topic
- It automatically closes the voting and **it should also be announced here** @kevincrepin. IF admin has set the voting deadline, our system should also notify about the voting deadline and close the voting if User still decides to send the topic to follow-up. I think it should be the same way as on our current version that when voting ends our system will not send topic to the follow-up automatically, but Users should send the topic to follow-up themselves. 

@BeccaMelhuish  I haven´t met use cases where users would like to add anything to follow-up phase before discussion or voting is ended. Follow up phase is more about informing people what is happening next. Discussion, ideation and voting results might affect the activities of the project and also follow-up. 
IMHO it is totally OK to block certain activities for two reasons: 1) users should set the discussion, voting, ideation phase deadline which delimits the discussion/voting/ideation time wise; and 2) follow-up activity decisions are made in certain time on the basis of certain information and if we would let people editing topics or hold voting open forever, the project would never end as there is always new information coming. 
We are currently facing the problem, where people initiate discussion/voting/ideation, but nothing follows is. Hopefully our new follow-up phase is gently pushing people to actually end these activities and inform people what happens next.

**Comment by anettlinno** [comment]
I´m also thinking that maybe in each phase (discussion/voting/ideation/follow-up) we should only show people the discussion (in argumentary or ideation) that has happened only in each phase. Users can easily move between different phases when clicking on the windows:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/5b469ad4-b682-411a-aeaa-9f54a5594fc1)

A use case where Admin User need to summarize each phase and showing discussion only under each phase, looks logical to me. Let´s say that I as an Admin User initiated discussion about if and what should we do with the empty field close to our community. I open a discussion where people can share their opinion. Then **we decide** to send it to the voting to see how many people support doing something with that and I as an Admin User will update the topic text where I announce that this topic is going to the voting. 
In voting phase, people will let know if they want to keep it as it is or use this land someway. Now we decided that we do something with that and in argumentary people have already started suggesting what to do with the empty land. Majority of people voted that we should do something with that land. Voting results are nicely visualized, but @kevincrepin WDYT, whould there be an opportunity for Admin Users to also summarize voting results and say briefly what is going to happen next (like "Now we start collecting ideas for the topic").
The dicsussion that took place in voting phase is only seen when user clicks on Voting phase.
Next, Admin User opens ideation and after voting over the best idea, Admin User could also somehow summarize what the results were and what is happening next. Ideation and ideas stay in this phase.
Lastly, I as an Admin User, sent the topic to follow-up, where I or who ever is leading following actions, will start informing people about what is happening next. 

Now, the question is if people should have an opportunity to also discuss or ask things from Admins during the follow-up phase? @kevincrepin I think currently it was planned that there is no discussion in the last phase. But should there be? :)

**Comment by anettlinno** [comment]
Triage 90. This topic needs more discussion that should take place before follow-up phase is being developed in redesign.

**Comment by kevincrepin** [comment]
_I think currently it was planned that there is no discussion in the last phase. But should there be? :)_

I think this is a bit of a ... "philosophical" question? :D I think like in any "project" there is a time when additional input doesn't actually help move the project further anymore. So at this point when the votes have been collected and a decision has been made, what should still be discussed?

Of course we can think of many situation that a conversation can still be helpful, ie. helping organise etc, but for this we could think of other tools that are not "an open discussion". To keep the focus on the follow-up and not get side-tracked by people's opinions. 

Might not be the most democratic though, but I would rather think of more focused tools to help the users through the follow-up phase, ie. volunteering, raise funds, etc.

**Comment by BeccaMelhuish** [comment]
@anettlinno I got a bit confused here: _"The discussion that took place in voting phase is only seen when user clicks on Voting phase"_, as from the prototype it seems there is no discussion in the voting phase, only voting?

**Comment by BeccaMelhuish** [comment]
My two-pence on the questions of whether to have a discussion in the follow-up but, I'd say maybe a Q&A format would be suitable there? So not a pro and con discussion (as wouldn't make sense), but a chance for transparent dialogue with the admins on that section?

**Comment by BeccaMelhuish** [comment]
Notes from meeting with Anett: If in follow up, discussion is open (in phase 1, needs rethinking re phases of topics). 
Will make separate issues to discuss the rest. 
@ilmartyrk FYI

**Comment by BeccaMelhuish** [comment]
@anettlinno @kevincrepin @ilmartyrk - one more question on this, is this below still the case, or they'll now be able to download results regardless of whether they have moved it to follow up or not? (I'm assuming not from what I've seen on the prototype, but let me know if I've missed something). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e4f9cd5a-043b-407c-83f1-9b22c15b39c1)

**Comment by BeccaMelhuish** [comment]
@anettlinno @kevincrepin @ilmartyrk - And one more thing I am assuming for the HC texts, again please correct me if I'm wrong:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5698dc67-0dc7-4955-bb22-0db8bff3d305)

**Comment by kevincrepin** [comment]
- I think vote results can be downloaded before sending topic to follow-up because admin might never send to follow-up.
- @BeccaMelhuish correct in the above. It's a linear process (right now at least) so if you skip a phase you can't add it later.

Added the automatic vote closing + a notice that if you've set a voting deadline that we clearly bring this out. If you have not set a deadline this would not be shown.


![Property 1=Intro](https://github.com/citizenos/citizenos-fe/assets/26792281/7dda18dd-9fed-4c43-9cd9-7a3131e6f3b7)

**Comment by BeccaMelhuish** [comment]
Wonderful, thanks @kevincrepin!

**Comment by anettlinno** [comment]
> @anettlinno @kevincrepin @ilmartyrk - one more question on this, is this below still the case, or they'll now be able to download results regardless of whether they have moved it to follow up or not? (I'm assuming not from what I've seen on the prototype, but let me know if I've missed something).
> 
In redesign admins can download voting results without sending topic into follow-up phase, so yes, this should be removed from HC texts.

**Comment by anettlinno** [comment]
@kevincrepin but actually in redesign test app I can send follow-up topic to the voting ;)

<img width="829" alt="image" src="https://github.com/citizenos/citizenos-fe/assets/45175679/793aa716-743b-4967-9270-999ad6f018ea">

**Comment by kevincrepin** [comment]
I think that's for @ilmartyrk :) In design it is like this: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=887-120321&viewport=-2088%2C-23837%2C0.5&t=x8WJxYrNW8wfwSuN-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

**Comment by anettlinno** [comment]
OK, great! Thanks @kevincrepin! 
@ilmartyrk please let´s change current status menu :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno updated the items

**Comment by anettlinno** [comment]
Tested and works as in design. Closing this issue.
