### ISSUE TITLE
Login and Reset Password not working with the Alex account

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#232]
**What is the problem?**
@ilmartyrk currently the Alex login isn't working in the Redesign app. Password is showing as incorrect (it is the correct password)
<img width="1339" alt="Screenshot 2023-09-24 at 18 33 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7ccb77e9-295a-474b-952d-76cbbb9d9fe5">

When I try to reset the password, I can only reset the password in the Test environment 
<img width="1346" alt="Screenshot 2023-09-24 at 18 33 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e9764ffc-7f8e-411f-a79d-020c00bce6c4">

**Why is this a problem?**
Makes it more difficult to run all tests

**Possible solution.**
Let me know if it is a bug or under development

**Comment by ilmartyrk** [comment]
@ssin1901 is this still an issue?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Am also interested to know if there's a login issue that should be fixed before testing :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 tested login and password reset and all works fine
