### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#233]
**What is the problem?**

In the Redesign project, there is no registration button (screenshot attached)

<img width="677" alt="Screenshot 2023-09-24 at 18 36 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a8e4f139-66fb-4881-bac4-2860606f57dc">

@ilmartyrk @anettlinno also not clear about the flow. In the Figma design there is no Terms and Services and Privacy policy displayed when the user is signing up. There is only a Display name and invite. 

In the Redesign app, we have all 3 and I was wondering if we could remove the Display name and invite to help the content fit on the page better. At the moment, the scrolling does not feel very intuitive.

**Why is this a problem?**
Currently cannot test Registration

**Possible solution.**
Need a registration button

**Comment by ilmartyrk** [comment]
Scrolling issue, is fixed now
