### ISSUE TITLE
Public topics dates not in logical order

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#235]
**What is the problem?**
When the user selects Visibility->All and Category->Every Category, they would expect that the public topics appear in descending order/most recent first. However, at the moment the dates don't seem to be in any order. 

Also unclear whether the date is first or the month. In any case the topics are not in order (see screenshots) 

<img width="1237" alt="Screenshot 2023-09-24 at 19 14 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1a8c3255-e906-4916-92d0-78050ef49015">
<img width="1227" alt="Screenshot 2023-09-24 at 19 15 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fcdf80f2-cdd2-4ed5-a28f-88838d674d75">

**Why is this a problem?**
User does not see the most recent topic or know how to find it

**Possible solution.**
Dates must be in descending order and the same date and time format should be used consistently i.e d/m/y or m/d/y.

**Comment by BeccaMelhuish** [comment]
It might be that it's showing them based on most recent activity, which would make sense? Otherwise a really old but very recently active topic would be way back in the list, while dead but recent topics were right at the front.. 
I would suggest keeping it as is if so :) 
(But can be a decision for Kevin also)

**Comment by ssin1901** [comment]
@anettlinno @ilmartyrk this seems to be a UX issue. Let me know if I should close the issue or follow up.

**Comment by anettlinno** [comment]
I also agree that topics with most recent activity should be first and I wouldn´t change that. @ssin1901 if you´re OK with that then please close the issue.

**Comment by ssin1901** [comment]
@anettlinno @ilmartyrk @BeccaMelhuish by descending order, I mean from most recent to the oldest. 

In the current arrangement they are organised by Most recent edit not the date displayed under the topic. 
<img width="1192" alt="Screenshot 2024-01-24 at 12 33 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e8e819e6-23d7-48df-9837-49f7f3d7fd45">

Is this what was intended?

**Comment by anettlinno** [comment]
Yes, most recent edits or activity in topics is exactly what was meant and I would leave it like that :)

**Comment by ssin1901** [comment]
@anettlinno my bad, I understood what you meant. Closing it now.
