### ISSUE TITLE
Check out Mobile ID

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#236]
**What is the problem?**
@ilmartyrk @anettlinno previously when I tried the correct mobile and personal code combination (screenshot 1), I was getting a message that this ID has not been activated. Issue recurs across Safari and Chrome on Mac OS.

<img width="1324" alt="Screenshot 2023-09-25 at 13 48 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c4cf2ca0-2600-4260-a469-5631d599f99d">

However, now the control code shows but then nothing happens - no error message or anything (screenshot 2, screenshot 3)

<img width="1053" alt="Screenshot 2023-09-25 at 13 51 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8e49573c-03f7-4cea-bca8-37f50a41d864">

<img width="1321" alt="Screenshot 2023-09-25 at 13 57 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8f840f0c-bcac-4e67-bf9a-d0b8e3ef106a">

**Why is this a problem?**
Might not be a bug – but it is worth checking if Mobile ID is working properly as Mobile ID is an MVP feature. I also noted a couple of times that there is a brief flash of red, but it goes away so fast that I could not take a screenshot.

**Possible solution.**
This maybe needs discussion but I think security wise, the user who has entered correct mobile ID and personal combination should receive an error message stating invalid personal code and mobile number combination (since the Mobile ID itself does not exist/is not active). 

I understand that this might be something that the Mobile ID developers have to implement from their side though.

**Comment by anettlinno** [comment]
@ssin1901 I just tested and for me, Mobile ID log-in worked on desktop and in Mobile. 

I also checked Mobile-ID voting and the process itself works but the UX is really a mess. After voting I see this kind of picture and there is no way for the User to understand that one has voted. "Your vote has bee registered" in the top line is really hard to catch. @ilmartyrk if I remember correctly, there should be a message that confirms also in the "voting box" that the vote was registered. Please check :)
 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/db255364-5447-4280-9b59-2425172b8621)

**Comment by anettlinno** [comment]
Triage 91. This UX issue is solved in redesign. Closing with no further action in this point.
