### ISSUE TITLE
Send to voting: View and Vote don't seem to be working properly

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#237]
**What is the problem?**
In Google Chrome and Safari, when a User sends a topic to voting, they get this interface (see screenshot 1) where nothing happens if you click View and Vote. In fact, it seems a bit redundant as the topic details are below the vote (see screenshot 2).

<img width="1200" alt="Screenshot 2023-09-25 at 14 20 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4a89199a-db9a-467e-a51f-577c52ec9295">
<img width="1202" alt="Screenshot 2023-09-25 at 14 20 33" src="https://github.com/citizenos/citizenos-fe/assets/72747107/84368780-5303-4609-a6b7-551f6185140b">

**Why is this a problem?**
View Button is redundant, doesn't work, and confuses the user

**Possible solution.**
Either View should show the user the topic or it should be removed.

**Comment by ssin1901** [comment]
@ilmartyrk probably linked to #209 in which case, it can be fixed in Redesign as agreed.

**Comment by anettlinno** [comment]
Triage 90. This is solved in redesign. Closing this issue with no further action.
