### ISSUE TITLE
Options are a mess when the voting options are up to 200 characters

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#238]
**What is the problem?**
When I tested with longer options, I got the error message Sorry, one of the vote options provided is invalid. Vote option can have maximum of 200 characters. (screenshot attached). 
<img width="1199" alt="Screenshot 2023-09-25 at 17 36 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5774c33c-dd57-42ba-860d-164a684c5b30">

However, when I reduced the text to 200 characters, everything worked smoothly except that the vote options were displayed in an unreadable manner. 
<img width="1016" alt="Screenshot 2023-09-25 at 17 40 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8d9622c5-3d03-4647-a051-624b3cc50024">

**Why is this a problem?**
Very critical @anettlinno @ilmartyrk. Tasia informed me that the options they use for the IOF 2023 are always quite long. Our platform states that 200 characters are allowed, but it doesn't work properly.

**Possible solution.**
Can we optimise the spacing for longer vote options. The IOF is an important use case and they require this feature.

**Comment by ilmartyrk** [comment]
@ssin1901  @anettlinno  OK, this is the reason why we had option names separated with letters and numbering in the past 
https://github.com/citizenos/citizenos-fe/issues/161

**Comment by ilmartyrk** [comment]
@ssin1901 @anettlinno I added back the lettering and separation of option names and voting columns, but ordering is now as agreed that the most voted options are on the top

**Comment by ssin1901** [comment]
@ilmartyrk I will test it, thanks a lot. Maybe we can rethink this flow in Redesign?

**Comment by ssin1901** [comment]
@ilmartyrk the first part (selecting an option works, screenshot1) but the options are not being displayed correctly (screenshot2)

<img width="1132" alt="Screenshot 2023-09-27 at 14 34 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b6919a48-4076-4a55-a067-99fa370c50c4">
<img width="1148" alt="Screenshot 2023-09-27 at 14 34 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/baf7cb06-7b94-4fa2-a030-79700909d596">

**Comment by ssin1901** [comment]
@ilmartyrk @anettlinno everything looks good and logical in the test environment according to me. See screenshots

<img width="1170" alt="Screenshot 2023-09-27 at 14 49 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/88e8ac72-0f68-416a-a362-183e532e4cb0">
<img width="1357" alt="Screenshot 2023-09-27 at 14 48 31" src="https://github.com/citizenos/citizenos-fe/assets/72747107/da6712a1-b8ba-4ed0-93ae-05456e6c9228">

**Comment by ssin1901** [comment]
@ilmartyrk tested to see if the correct results come, and they do (see screenshot 1 and 2). However, it is not super intuitive for the user. Let's rethink this flow later.


<img width="1332" alt="Screenshot 2023-09-27 at 16 04 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e965a69d-77f2-41c5-ba54-38c8b07046a6">

<img width="1141" alt="Screenshot 2023-09-27 at 16 05 52" src="https://github.com/citizenos/citizenos-fe/assets/72747107/dd7feea6-f241-41b9-9cce-a92b61d18220">
