### ISSUE TITLE
Problem with Accept button button at one point

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#239]
**What is the problem?**
While I was testing the new account registration, I could not "Accept" the terms and conditions from Mac OS and iPad Safari the first few times. Later, it worked. 

For further information, I had also just deleted and registered the account again as part of the testing process. Maybe that was the reason?

Screenshot attached (screenshot 1) 

<img width="1327" alt="Screenshot 2023-09-26 at 00 27 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/59089d4a-63a0-4a65-91d2-1ac807138c92">

**Why is this a problem?**
Not sure why the button was not working. It might be a one-time issue but I cannot say for sure. 

**Possible solution.**
Accept button should work.

**Comment by anettlinno** [comment]
Triage 90. Could not replicate the issue. Accept button worked fine. 
Closing this issue with no further action.
