### ISSUE TITLE
Download voting options disappeared

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#240]
**What is the problem?**
When the voting has ended and the user has sent the topic to follow-up, the Download votes option disappears (see screenshot) **only in Safari**

<img width="794" alt="Screenshot 2023-09-27 at 15 49 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/09276a79-24ee-46c0-a7a0-de062b72611e">

**Why is this a problem?**
Users cannot download the voting results anymore 

**Possible solution.**
Download vote options should appear like in the Test environment (see screenshot). NB! It works as expected in Google Chrome.

<img width="930" alt="Screenshot 2023-09-27 at 15 49 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/81fa7e23-d1e6-4e37-9509-3cdda5acad13">

**Comment by ssin1901** [comment]
@ilmartyrk works when the user refreshes Safari.

**Comment by ilmartyrk** [comment]
Triage 91.  I have one idea of what might be going on so will do 15 min research to confirm if my hunch is correct

**Comment by anettlinno** [comment]
Triage 92. High priority issue. Sending it To Do.

**Comment by ilmartyrk** [comment]
@anettlinno @ssin1901 I could not replicate it, tested also on MacOS and Safari
