### ISSUE TITLE
Inconsistent and incorrect Main statement message

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#241]
**What is the problem?**
When a user exceeds 128 characters while making a main statement for arguments, it is not possible to add any more characters. If you copy paste, only up to 128 characters is pasted (screenshot1). 

<img width="1203" alt="Screenshot 2023-09-29 at 13 55 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d28feede-73b5-4107-90de-a314b6960150">

However, when the user has not exceeded the character limit but has forgotten to add body text, they inconsistently get this message (see screenshot 2)
<img width="1205" alt="Screenshot 2023-09-29 at 13 52 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b2e626eb-75f3-47e0-93c0-4ad94c8a3ea1">

Other times they don't, and the 125 character main statement is posted just fine (screenshot 3)

<img width="1016" alt="Screenshot 2023-09-29 at 14 04 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8c67052e-daa6-4b8d-bbd4-01d1661d0ff7">

@ilmartyrk in Redesign the user also incorrectly gets the main statement message is too long when the argument body is blank (see screenshots 4 and 5)

<img width="1338" alt="Screenshot 2023-09-29 at 14 09 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d79ca0f6-81ef-45d6-9b3c-22e5f77655aa">

<img width="1338" alt="Screenshot 2023-09-29 at 14 09 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/53718533-9a41-4e53-a07b-d226ca7da23a">

<img width="1321" alt="Screenshot 2023-09-29 at 14 09 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0205dc24-a078-4d8b-ad33-cb18217dbd9d">

**Why is this a problem?**
@ilmartyrk Tasia reported seeing a lot of "duplicate" arguments, which was negatively affecting the IOF. Could this be related to the inconsistency at the time of submitting the argument?

**Possible solution.**
1. Since it is not possible to add more than 128 characters in main statement, the user should not get any error message at all. In Redesign the character count shows the user that the reason they could not add anymore characters was because the count was exceeded
2. If the issue is that main body text is blank, the error message should be something like "Error. Body text cannot be blank". Main statement and body text messages should not get mixed up.
3. Further, the issue of why the message comes only sometimes should be investigated. This issue prevented me from running automated tests, as it lead to a failure the first time. As mentioned, duplicate topics were also reported as a potential issue.

**Comment by anettlinno** [comment]
Dublicate issue #194

**Comment by ilmartyrk** [comment]
Triage 91. Will fix this in redesign, probably better solution would be to add error to the fields rather than displaying on the top of the page as it is field related. 

Currently the error message has been updated to "Main statement can be 1 to 128 characters long." as we have to use it for generic API response that comes with either empty or too long subject.
