### ISSUE TITLE
Profile picture can be larger than 5MB

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#242]
**What is the problem?**
When the user uploads a profile picture that is larger than 500KB (see screenshots 1 and 2) the image is accepted by the system.
<img width="262" alt="Screenshot 2023-10-03 at 12 46 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9a003132-eb5d-417c-b64d-97da9b9850dc">

<img width="1322" alt="Screenshot 2023-10-03 at 12 50 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c542073f-4227-42b9-ada3-687f543ea22b">

**Why is this a problem?**
The text explicitly states that there is a size limit

**Possible solution.**
Actual size limit should be mentioned

**Comment by anettlinno** [comment]
Triage 91. Picture size should remain 500KB, but there are two options:
1. We ask User to resize the picture if it´s too large
2. We automatically resize the picture 
For the UX side the second option would be the best and we´ll investigate what it means to automatically resize the picture. 

Sending it to investigation. Est. time for that 1 hour.
