### ISSUE TITLE
Topics in Notifications be links

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#243]
**What is the problem?**
When the user goes to Profile->Notifications the list of topics is presented as links (blue underline) but when the user clicks on them the link does not work (see screenshot)

<img width="1230" alt="Screenshot 2023-10-03 at 13 14 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/42295637-4473-448f-879b-f9b4a85bf414">

**Why is this a problem?**
User cannot visit the topic from Notifications to check what it is. They have to instead perform other actions.

**Possible solution.**
The user should be able to click on the topics in Profile->Notifications and visit the links

**Comment by anettlinno** [comment]
Triage 91. Adding links to the topics.
Est. dev. time 2 minutes.
Sending it to do.
