### ISSUE TITLE
Topics ordered by group does not work

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#244]
**What is the problem?**
When the user goes to My topics->Show topics ordered by group the list of topics that appear have no connection to groups (see screenshot). NB! I also created a topic which has no connection to groups which is right at the top of the list.

<img width="1135" alt="Screenshot 2023-10-03 at 13 59 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b0f1c2c7-6333-425a-a62c-1fb7d350a039">

**Why is this a problem?**
User would not be able to find their topics in a group and may misunderstand which topics are in which groups (an MVP feature)

**Possible solution.**
Topics should be ordered by groups (only show topics that are added to groups)

**Comment by anettlinno** [comment]
Triage 91. We decided to remove option "Show topic ordered in groups" from the list, as currently it doesn´t do anything and the text is also unclear (what it should be doing).  

All sorting options should be checked in redesign. 

Est. dev time 2 minutes. Sending it to do.
