### ISSUE TITLE
Arguments cannot be reported

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#245]
**What is the problem?**
@ilmartyrk I received this error at one point while trying to report an argument from the test account on Safari (see screenshot attached). However, when I tested it with older arguments, it worked perfectly. Later, I was also notified that my argument had been reported.

<img width="1337" alt="Screenshot 2023-10-05 at 16 35 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b6b956eb-1770-47dd-8909-f47bbac393b4">

**Why is this a problem?**
Users might not be able to report arguments all the time or might not understand that an argument has been reported. 

**Possible solution.**
Users should be able to report arguments

**Comment by anettlinno** [comment]
Triage 91. @ssin1901 please describe this User case in more detailed way, as currently it is not clear where the issue arises.

**Comment by ssin1901** [comment]
Hi @ilmartyrk @anettlinno basically at one point when I clicked Yes, Report Argument I got that HTTP error. But it started working a bit later.

**Comment by anettlinno** [comment]
Triage 92. Need some investigation, est. time 30 min. 
Sending it To Do.
