### ISSUE TITLE
Mobile issue: Show profile not aligned properly

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#246]
**What is the problem?**
When a user registers an account, in Iphone 6S (375px × 667px viewport) the show profile is on top of another element (see screenshot)
<img width="397" alt="Screenshot 2023-10-05 at 19 27 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8515a7ec-edf3-4dc1-95db-2dfb880635bf">

**Why is this a problem?**
Makes it more difficult for the user to toggle the button 

**Possible solution.**
Show my profile in search can go below the description

**Comment by anettlinno** [comment]
Triage 91. This will be fixed in redesign.
Closing the issue with no further action.
