### ISSUE TITLE
Editor could not be used on iPhone 6S

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#247]
**What is the problem?**
 On Iphone 6S (375px × 667px viewport) the topic editor cannot be used properly as the editor menu appears over the text that the user is trying to compose (see screenshot)

**Why is this a problem?**
<img width="411" alt="Screenshot 2023-10-05 at 19 32 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/eec3350a-65fc-44bf-bac6-75c001d8d294">

The user cannot use the editor without spending a lot of additional time

**Possible solution.**
Need to brainstorm how to fix this, but the editor should be minimised or disappear in mobile devices. Otherwise it is very difficult for the user to edit.

**Comment by anettlinno** [comment]
Triage 90. Should check how much usage there is from these small screens, but according to the gut feeling, it is rather low (screens are getting bigger and bigger or at least screen resolution gets better). 
We´ll keep it in mind in redesign. 
Closing this issue with no further action.
