### ISSUE TITLE
On Mobile the Help Centre button affects the use of buttons in the Group interface

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#248]
**What is the problem?**
 On Iphone 6S (375px × 667px viewport) when the user goes to Groups and views a particular group, the Help Centre icon is blocking the toggle button for topic list (see screenshot)

<img width="408" alt="Screenshot 2023-10-05 at 19 37 04" src="https://github.com/citizenos/citizenos-fe/assets/72747107/083ee499-0dd2-4ad1-84bc-683fa70ca747">

**Why is this a problem?**
User cannot access the Toggle button 

**Possible solution.**
Needs rethinking. The Help Centre button should not be overlayed on top of other buttons

**Comment by anettlinno** [comment]
Triage 91. Replicated this issue, but this actually doesn´t block the action itself as the grey bar is active anywhere User clicks on.
We´ll keep it in mind in redesign -- maybe the bubble could be movable in the screen (at least in mobile)?

Closing this issue with no further action.
