### ISSUE TITLE
User is not notified about attachments 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#250]
**What is the problem?**
In https://citizenos.com/help/topics/attaching-files-to-a-topic/ it is mentioned that we notify the users about attachments being uploaded. However, I tested and this does not appear to be the case when you select Topic updates.

**Why is this a problem?**
I think the user should be notified about attachments in Topic updates

**Possible solution.**
@ilmartyrk @BeccaMelhuish do we update this feature or just the HC text? I am not sure whether this is a bug or confusion about the flow.

**Comment by BeccaMelhuish** [comment]
@ssin1901 I agree it would be good for them to be notified, will wait to see what @ilmartyrk says on this and then only update the HC text if we won't be making it happen :)

**Comment by anettlinno** [comment]
Triage 92. @ssin1901 we cannot find the place in the HC where it is said that we notify the user when file is attached. Please elaborate, where it is. Thank you!

**Comment by BeccaMelhuish** [comment]
@anettlinno Here it is :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ec96b0dc-4894-4370-95df-8dd130f82151)

**Comment by anettlinno** [comment]
Triage 93. Users should receive a notification email when new attachment is being added. Issue is probably on API side.
Sending it To Do. Est. dev. time 2 hours.

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk closing this because it isn't mentioned in the topic updates and there is no HC
