### ISSUE TITLE
BUG: e-ID login showing for non-connected accounts following email invite

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#252]
When I followed an email invite to my gmail (which is not connected to e-ID), the login options showed e-ID options (but it shouldn't).

@ilmartyrk @anettlinno @ssin1901 Am wondering if this bug should be a priority to fix/QA test with the Estonian general meeting that's coming up? (Not sure the date?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a023d4bb-5c3a-4c9e-ba8e-77cf5be1c5e8)

**Comment by anettlinno** [comment]
Thanks for noticing, @BeccaMelhuish, prioritizing this bug @ilmartyrk

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish this only happens for accepted invites where we redirect users to login and after they log in they get redirected to the topic or group they were invited to. I guess we could add available options here too, but it needs some thinking on how to implement this here. I'll probably check it after redesign launch so closing this issue and creating a new one. [#254](https://github.com/citizenos/citizenos-fe/issues/254)
