### ISSUE TITLE
BUG: Moderation not working? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#255]
@ilmartyrk @anettlinno @ssin1901 - seems this could use some testing, as for me just now the moderation feature didn't work. When I tested (for the HC texts) reporting and moderating an argument, using a dummy topic and two of my own accounts, this is what I got when I clicked on the link in the notification email to me as moderator (logging in with same email I used to set up the topic), and no option to hide, delete, etc. (i.e. no possibility to moderate).    

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/de7ce97d-e258-4a6e-8304-eab43f0b5250)

**Comment by anettlinno** [comment]
Triage 92. @BeccaMelhuish please let us know if you tested it on the test or live environment.
Sending it To Do. Est. dev. time 30 min.

**Comment by BeccaMelhuish** [comment]
@anettlinno Pretty sure it would have been the live one. I don't really use the test environment when just playing around to see how things work for the HC - I just use my own account in the live one :)
