### ISSUE TITLE
BUG: topic phase tabs not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#257]
@ilmartyrk @ssin1901 @anettlinno When I try clicking between the tabs of the different phases of a dummy topic I just made, it keeps getting stuck. Sometimes it shows the correct thing, but mostly it just shows the same content whether I'm on View or Vote or Follow-up (usually the Vote tab content, though maybe coincidence). I click between them several times, and it allows me to change tab visually (i.e. the tab displays as though it is selected) but the content doesn't budge. I have to refresh the page to get the right tab content to display. 

On Chrome: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1a8ef23e-a03d-4fa3-83c8-26361676846d)

Same thing happens when I try on Firefox: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3f5102d7-a062-4782-8827-607062977482)

**Comment by anettlinno** [comment]
Triage 92. This is fixed in redesign. Closing this issue with no further action.,
