### ISSUE TITLE
UX of the vote results folder

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#261]
@anettlinno @ilmartyrk At some point as part of the redesign could we work on the UX of the vote results folder? I just downloaded one myself, and can see that it could be a lot less confusing with a bit of work on the way the folder is structured, the way files are named etc. (The folder itself being named 'final' is also a bit odd). Happy to give more suggestions on how if wanted :) 

(Also hopefully any designs in there (like the results graph) will be updated to match the new look?)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/700d6792-0fad-4892-944f-d75ccfc4a386)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish results graph file has been updated, All other suggestions are welcome here. But I guess we won't do any major changes before phase II

**Comment by BeccaMelhuish** [comment]
OK thank you @ilmartyrk! I've added a Phase II label and will happily provide suggestions when the time comes, I think it should be relatively simple to clean it/clear it up a bit :)

**Comment by BeccaMelhuish** [comment]
Closing as there are new issues about this
