### ISSUE TITLE
Redesign: Could 'manage participants' include inviting? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#263]
Hey @kevincrepin, one thing that has bothered me on the current platform, and I just noticed it's the same on the redesign, is the separation of:

- viewing the participants (and pending invites) and their rights, and editing their rights (and deleting users? Not sure from the prototype)
- inviting participants

Especially when we call the first 'Manage', which you'd assume would be a heading for something that included inviting new participants, as that's a big part of managing who has access. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ed423e7b-769a-41c6-afad-4d6b27932720)

I remember one UX tester gave this feedback too, that it was confusing/frustrating having them separated, and should all be in one place like with Google docs:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e695c41d-4c52-4583-97e5-5eb79c15f826)

Maybe 5 tabs is too much, but could they perhaps be different tabs of the same window? Opening at the relevant tab depending on your route into it, but with the other tabs right there if you need them? Or is there another solution to make going between them a bit smoother? 

Tabs headings could be shorter maybe if all 5, e.g.:

Participants, Groups, Pending, Invite, Share

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/015073e2-81f6-4db9-b8a8-3f1225b33e9e)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ffb97669-c662-4383-84ff-cd7e4ac78696)

**Comment by kevincrepin** [comment]
Hmm, not sure if I (100%) agree with this. I mean I get it, but I think we have a slightly different context than Google Docs in the amount of people you might need to manage. Also to be clear only the admin would see this link, but regular participants would still see the "Invite & Share". How would that label look like? Because I would not necessarily expect to manage users, groups, etc under "Share" or "Invite".

Also considering different types of users they might not be as familiar with Google Docs as we are, so maybe let's not take it as the undeniable truth to guide us. In my opinion 5 tabs is too much and creates confusion by bundling all of this. One of the design principles was to not overload with too many options (admittedly not always so easy to do...). So to separate this at a higher level for me (still) makes sense.

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK yes fair enough! 

Though just to clarify I wasn't meaning these (screenshot below) links/buttons themselves change, but just what you get when you open the window. So for admins, when you've clicked 'Manage' you would also have the option to invite from the same pop-up window (which you might expect - I know I've looked for how I invite a few times myself within the 'Manage participants' window on our current platform, and I remember one or two users in the current platform's user tests did too). So for example when clicking 'Manage', it would open the window on the 'Participants' tab, and when you click 'Invite & Share' it would open on the 'Invite' tab (and you could quickly check to see who's been invited already in the 'Participants' tab, before inviting anyone else, if you wished/needed to). 

And thinking now that one way it could be 4 tabs rather than 5 could be by having the pending invites included in the participants list (with the grey 'pending invite' text), like we do with groups? So then just Participants, Groups, Invite, Share, all under the heading of 'Manage participants'.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f9187d7e-abe8-4946-b6b3-81ba8a2180fb)

**Comment by anettlinno** [comment]
I agree with @kevin that as "Manage" participants is only for the admin Users and other users cannot see it, then IMHO it makes sense to separate these from the "Invite & Share". 

I understand your concern @BeccaMelhuish and I think that this could be something that we test in our User tests.

**Comment by BeccaMelhuish** [comment]
Had some minor insights related to this, but will close it for now and re-open if there's anything solid that comes up :)
