### ISSUE TITLE
HC query: Manage participants bulk actions

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#265]
@ilmartyrk do you feel we need a design for the bulk actions on the 'Manage participants' window? For the HC texts I'm not quite sure what will happen there, so I can either wait until it's developed to finalise the text, or if you'll need a design anyway then @kevincrepin could make us one? (Unless there's one already, but I haven't see one). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d95ec3d1-570d-4d19-8b8f-dd42280435c7)

**Comment by kevincrepin** [comment]
We have this component in other place(s). It would work the same. Basically we have one type of action menu and it's the same for different places that trigger an action menu.

(nvm this missing icon in the button, it's a hover state bug :( )
![Screenshot 2023-10-16 at 16 57 24](https://github.com/citizenos/citizenos-fe/assets/26792281/e00bf61f-fb76-4f19-bedd-6aee79f220bd)

**Comment by kevincrepin** [comment]
And of course there might be more actions in this menu. Or less.

**Comment by BeccaMelhuish** [comment]
Ah OK perfect, thank you @kevincrepin!
