### ISSUE TITLE
Browser tab heading

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#266]
@ilmartyrk, I'm sure at some point it got changed so that the tab said what topic/part of the platform you were on, but seems to be back to just "Citizenos" now - is it a bug, or did I just imagine it? :D 

Either way I think it should be more specific, and in case that's not possible/desirable, then it should at least be Citizen OS not Citizenos :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e405b303-50e6-4c12-abce-17b9a1a4703b)

**Comment by anettlinno** [comment]
Triage 92. You are right, @BeccaMelhuish, will be fixed with metatags. 
Est. fix time 1 hour. Sending it To Do.

**Comment by BeccaMelhuish** [comment]
I see this is working as it should in the redesign so am closing :)
