### ISSUE TITLE
Logout issue 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#268]
**What is the problem?**
Tested logout with existing account on Safari (see screenshot 1) and a newly registered account on Google Chrome (see screenshot 2 and 3) and received errors.

<img width="1391" alt="Screenshot 2023-10-22 at 17 25 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/13916195-e9b6-4324-8d2b-86dcf3770fe1">

<img width="1422" alt="Screenshot 2023-10-22 at 17 24 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4d428b8f-e78f-407b-a87f-989fb8aba0ea">

<img width="1421" alt="Screenshot 2023-10-22 at 17 24 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e7ef8038-4f7b-47d8-b296-3701f914d273">

**Why is this a problem?**
User cannot logout 

**Possible solution.**
Critical bug fix

**Comment by ilmartyrk** [comment]
Triage 92! Needs some investigation est. 30 minutes. Might be related to Etherpad update and/or our database in testing getting filled to the limit
