### ISSUE TITLE
Clicking Reject Terms and Conditions -> No, don't delete account has some issues

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#269]
**What is the problem?**
When a user registers an account and clicks on Verify my email (see screenshot)
<img width="935" alt="Screenshot 2023-10-22 at 17 45 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a19ba2bb-1ccd-4e47-99be-41d9b985d133">

They are directed to a normal login page (see screenshot)
<img width="1429" alt="Screenshot 2023-10-22 at 17 43 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/52d8d385-469a-4e66-a41d-4efeb369a39f">

When they try to Login, they are presented with Terms and conditions (see screenshot) but if the user chooses the option "Reject" and under Are you sure you want to delete this account->No, keep this account. 

<img width="1432" alt="Screenshot 2023-10-22 at 17 43 14" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e6a4a3d1-0c7e-488a-96d6-b368b4fd52f2">

Here, it also seems like the previous popup is still visible (see screenshot)

<img width="1420" alt="Screenshot 2023-10-22 at 17 43 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d9619eb0-f4ed-4b9b-9e1c-46790a0a762f">

They are then redirected back to the Acceptance page (see screenshot) BUT accepting the Terms and Conditions sends them back to the Login page (see screenshot)

<img width="1434" alt="Screenshot 2023-10-22 at 17 43 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/924fb18c-8b19-4bc2-a63d-e3adbfb3d612">

<img width="1429" alt="Screenshot 2023-10-22 at 17 43 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cb9c6d3c-5d46-438e-a9fd-743d114722f1">

Finally, after they login for the second time they get this screen (see screenshot)
<img width="1414" alt="Screenshot 2023-10-22 at 17 44 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/01a4c26d-5e26-4858-94a0-490c354d2488">

**Why is this a problem?**
If a new user has already entered the correct email and password combination, why are they asked to login again after accepting the terms and conditions?

**Possible solution.**
New user who enters correct login credentials should not be asked to Login again after Accepting Terms and Conditions, regardless of whether they initially clicked Accept, or clicked Reject but did not confirm account deletion, and then went back to the Terms and Conditions page and clicked Accept. 

There should not be another popup form visible behind No, don't accept.

Also, the user should not get a black screen after logging in, following the loop above.

**Comment by anettlinno** [comment]
Triage 92. Needs some investigation as we could not replicate it. Est. investigation time 30 min, sending it To Do.
