### ISSUE TITLE
Members Invited Via Public Group > Invite & Share not Displayed in Members Although Email is Received

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#27]
**Specifications**
MacOS Google Chrome

**Problem**
When a user invites a participant (see screenshot) the participant receives the email invite.

<img width="1249" alt="Screenshot 2023-03-14 at 14 13 09" src="https://user-images.githubusercontent.com/72747107/225059239-1af9bf68-315a-4897-8270-6eb25ee6920d.png">

 However, the Member is not shown as a pending participant (see screenshot).

<img width="1250" alt="Screenshot 2023-03-14 at 14 12 53" src="https://user-images.githubusercontent.com/72747107/225059096-9427120b-bb3f-4550-98c0-8dfe96b01403.png">

**Expected Result**
Invited user should be shown as a pending participant under Members. Otherwise the user will continuously receive email invitations as there is no record of them having ever been invited.

**Comment by ssin1901** [comment]
@ilmartyrk just edited it and I am SO sorry.

**Comment by ilmartyrk** [comment]
I guess this is again a UX/UI issue, this was not implemented in the designs, probably makes sense to add another tab with invites
