### ISSUE TITLE
Text review: 'Did you know?' box in topic creation process 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#270]
@ilmartyrk @anettlinno @kevincrepin @oksks 

A text that needs a bit of reconsideration. Have edited it to "which you can use when moving the topic forward" just so it works grammatically, but the message/meaning isn't really clear. Was there a certain message that was important to communicate at this point? Or what would be best to say here instead?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/becf4f19-3f8e-43ec-a17f-a3deb819d743)

**Comment by kevincrepin** [comment]
Like you suggested "which you can use when moving the topic forward" better articulates what I wanted it to say :) The idea would be that you can use people's arguments to adapt the topic text or use it to create ideation or a vote. Basically including people's input.

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK gotcha! Had a little brainstorm of possible ways to get that idea across a bit more - do any of these work well for you? :)  

", which you can use as input for moving the topic forwards"  
", which can help you decide how to move the topic forwards"
", which can help you shape the next phases of the topic."
", which can help inform how you take the topic forwards". 
", which can feed into the next phases of the topic decision-making".

**Comment by kevincrepin** [comment]
I think they all work, but if I have to choose then any of these :)

- ", which you can use as input for moving the topic forwards"
- which can help you decide how to move the topic forwards"
- ", which can help you shape the next phases of the topic."

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK great thanks! I think let's go for this one then, as if they haven't yet understood that they can add further phases to the topic after discussion, it'll help them get there :) 

", which can help you shape the next phases of the topic."

**Comment by BeccaMelhuish** [comment]
Code updated
