### ISSUE TITLE
Text review: "Order by level" unclear

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#272]
@ilmartyrk @anettlinno @kevincrepin @oksks 

As per Slack conversation with @ilmartyrk, this text doesn't make much sense and needs reconsideration. 

Input from Ilmar: "Level is meant for permission level, admin, editor, participant, I guess A-Z is a bit confusing in that context, so I can probably replace it with arrow icons." 

Could also be edited to "Order by level of access", potentially? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/49f3a164-8cd3-457a-8295-c3f030331e9e)

**Comment by kevincrepin** [comment]
Can't we just do an "order by role"? Descending would be admin > editor > participant

I agree A-Z in this context is a bit weird and also doesn't give much indication of the level of permissions. Also we only have 3 levels so I think it could be easily understandable that admin is the highest, editor gives edit rights and participants is the baseline?

**Comment by BeccaMelhuish** [comment]
Ah yes that makes much more sense, thanks @kevincrepin! 

@ilmartyrk if you agree, shall I change it or will you?

**Comment by BeccaMelhuish** [comment]
Actually @ilmartyrk I will leave this one to you as I see it's not a case of a simple text switch (as now will only be descending, not ascending too). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a5f6841e-e9b7-44e8-b6ce-5dd7a88429eb)

**Comment by ilmartyrk** [comment]
@ilmartyrk I'll make the change

**Comment by anettlinno** [comment]
Triage 95. Changed to "order by role". Closing the issue.
