### ISSUE TITLE
Text review: "(n)etiquette"

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#274]
@ilmartyrk @anettlinno @kevincrepin @oksks

A text that might want some consideration: as one of the choices for why you are reporting something as inappropriate, one of the options is "infringes (n)etiquette". It's a bit of an odd one - partly because (n)etiquette isn't a well known term (nor is even etiquette on its own, if not a native speaker, so not even easy to guess). And partly because even if you've understood what the term might mean, I wonder what sort of thing people would be putting in that category? I.e. what actually counts as (n)etiquette infringement? 

OK I just Googled it, and got [this list](https://www.kaspersky.com/resource-center/preemptive-safety/what-is-netiquette), but it feels a bit of a vague one to me - is so broad, and much of this isn't really a report-worthy offence? 

Wondering if it's necessary, or could be renamed to something a bit clearer/simpler?    

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/33fefbb7-e731-4c8b-ba57-a208fb26d759)

**Comment by kevincrepin** [comment]
Maybe something like "Infringes common courtesy", friendliness, "not considerate". I think those have the same intent.

Not a fan of the term "infringes" tho :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Hmm yes how about "Is impolite or inconsiderate"? 

Though we do already have ""Is abusive or insulting", which isn't that dissimilar? I'm wondering if it's necessary?

**Comment by kevincrepin** [comment]
Good point. I think if the other options cover most (if not all) of the cases then we could drop this. There's always still the "Other" option as well I think that allows for free text?

**Comment by BeccaMelhuish** [comment]
Actually it seems we don't have an "Other", but there is a free text box. @ilmartyrk could we remove the "(n)etiquette" one and and an "Other" option at the end? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ddd77389-0294-49e4-b822-150b18a47f02)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2beef840-4d68-4a4f-aa95-a5c2d6bbf72d)

**Comment by kevincrepin** [comment]
Seems like a "two birds with one stone" solution to me!

**Comment by ilmartyrk** [comment]
Will add the option Other and remove netiquette

**Comment by anettlinno** [comment]
Will send this issue to UX/UI update

**Comment by anettlinno** [comment]
Triage 95. Issue is fixed. Closing the issue.
