### ISSUE TITLE
Text review: Topic sections or phases? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#275]
@kevincrepin was there a problem with using the word phases to refer to the different parts of a section? I made some edits which include the word "phases" when talking about them (see below), but seem to remember there may have been an issue with this when we discussed it before once? If there isn't though, I'd vote for using "phases" consistently throughout rather than "sections", as I think it's closer to what we mean, and gives more of an idea of how it works? 

@ilmartyrk @anettlinno @oksks FYI too   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4217beb4-5a5c-4fd9-a4a6-e31e7b16c97f)

**Comment by kevincrepin** [comment]
Phases is good for me!

I think during the design process we went back and forward on how to call these, but in the end I think phases probably still suits the best.

**Comment by BeccaMelhuish** [comment]
OK perfect, thanks @kevincrepin! Will update the codes :)
