### ISSUE TITLE
Text review and related UX: Pinning or favouriting

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#276]
@kevincrepin @ilmartyrk @anettlinno @oksks 

For the "starred" topics, groups, etc., what will we call them now? Throughout the code, currently in some places we call it "pinning" and in others "favouriting" - would be good to make it all consistent :) 

My vote is for "Favouriting" as it's a star icon, not a pin icon, so it seems to fit better. E.g. "Favourite this topic" or "Add to favourites". 

Though that said, if it will work the same was as it currently does - that by default the starred ones are pinned to the top when you open "My topics" or "My groups" (which would be helpful - I definitely find that feature useful on our current one), then maybe calling it "pinned" would be best to describe the functionality. 

@kevincrepin do you have a preference for one or the other, from a UX perspective? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7c433b00-c6c6-4cbc-809b-410416dcc1b7)

A note from Kevin about this feature on Figma: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e9cc89cd-a0b7-472f-919e-b71cf5305739)

**Comment by kevincrepin** [comment]
I would also prefer "Favourites" and I would not have them pinned at the top at all but keep them according to the filter parameter (for example, latest activity). If you want to see your favourites just filter out by favourites then :)

If we agree on this I will update the designs with the correct term.

**Comment by BeccaMelhuish** [comment]
OK yes makes sense to me! And easy enough to filter, very true :)

**Comment by kevincrepin** [comment]
Updated everywhere (actually it was used only in 3 places :))

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I can't find a string for "remove pin" or "un-pin", but if you find or create the equivalent it should be "unfavourite" please :) 

The rest I have edited now.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a3640b56-fb9c-455d-a3de-91a815e723b8)

**Comment by ilmartyrk** [comment]
This will need a little bit more work from me, I'll think I'll rename the current pinned topics on our API side and also add this favoriting system to groups, also will add Unfavourite string to translations

**Comment by anettlinno** [comment]
Sending this issue to UX redesign project @ilmartyrk

**Comment by anettlinno** [comment]
Triage 95. Issue is fixed. Closing the issue.
