### ISSUE TITLE
Text review: "Social media hashtag" should be "X hashtag"?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#278]
A few places on our platform we talk about the "social media hashtag", and "social media mentions", when it is actually only a Twitter (X) hashtag. This feels a bit misleading/confusing. Shall we update all mentions of this social media mentions feature to specify that it is only an X hashtag/only pulls through X mentions?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/880d8fde-1b6f-47cd-93df-2baa4a685bb1)

I see in the design it is for Facebook and Instagram too, which would be great, but @ilmartyrk are there any plans/possibility to make this work? (Would make the feature make a bit more sense than it currently does..). 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bc2ce77d-10b1-4620-9dae-0232a132a927)

**Comment by kevincrepin** [comment]
I guess at the very least I have to update that Twitter icon :)

I'm a bit in the middle of renaming it to "X mentions" or "X activity" because it sounds quite bad. And going down this "X (former Twitter) activity) is also not ideal :)

**Comment by kevincrepin** [comment]
@ilmartyrk FYI I updated the Twitter icon to the X icon in Figma

**Comment by BeccaMelhuish** [comment]
Ah sorry @kevincrepin, had a glitchy internet connection yesterday and seems I ended up with two of these issues - [the other of which](https://github.com/citizenos/citizenos-fe/issues/279) I closed yesterday for the reason's explained there :)  

Closing this one now too then!
