### ISSUE TITLE
Text review: "Multiple choice" not the right term

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#280]
We've always referred to our feature where you can select more than one option in the vote, as "Multiple-choice voting", but actually this isn't the correct use of the term. In common English usage, "multiple-choice" means you have several things to choose from, and can choose one thing from among those. It's often used for exams, so a "multiple-choice exam" is one where you don't have to find the answer yourself, but choose from 3-4 possible answers that are given to you for each question, only one of which is correct. 

Some alternative options (thanks to ChatGPT) would be:

- Multi-vote / Multi-voting
- Multi-select voting
- Multiple Selection voting 

Any preferences?
The first one, multi-vote / multi-voting, seems to be quite a common term, used for the activity in team meetings where you each get to vote for a few different things, to help gauge the group's feeling on what should be the priorities / to narrow down a selection of ideas etc. Which is pretty similar to what this feature does. So my vote would go for that :) 

Though in this context below, I guess we would have to say a "multiple selection" and "single selection" vote:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5b9fc97a-52e5-4a2f-96e8-d5e3a2f18867)

**Comment by kevincrepin** [comment]
Sounds good to me. Updated the designs.

**Comment by BeccaMelhuish** [comment]
OK great thanks @kevincrepin!

Will change it to "multiple selection" in the code here too :) 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c02085e8-385e-48fe-bf78-ff839e547231)

**Comment by BeccaMelhuish** [comment]
Code updated
