### ISSUE TITLE
Text review: "moderated" should be "hidden"? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#281]
@ilmartyrk @anettlinno @kevincrepin @oksks 

The "moderated" filter has always confused me, but from going through the full texts, I've now realised that we're using the word "moderate" to mean "hide". So a moderated argument is an argument hidden by a moderator, and a moderated topic is a topic hidden by moderator. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fdbdf659-ad27-4df0-848f-169288491895)

Could we therefore switch the word "moderated" to "hidden" throughout, to be more understandable to those without the context to guess? As the word "moderated" on its own doesn't really communicate what we're trying to say - I think a lot of others like me would be confused by it. For example, a moderator could hide, or delete, or edit, or block something. The act of moderating doesn't always mean hiding. And a "moderated" topic, could also simply mean that a topic has moderators, and is being moderated (i.e. has some moderators actively keeping an eye on it). 

Ideally we would say "hidden by moderator" where possible, to make it totally clear. But if we need to choose between just "moderated" or just "hidden" in some places, the latter is much more understandable :) 

In this context for example, instead of "moderate argument" it would be "hide argument". Unless the context is one in which the moderator is given all the options for moderating an argument, in which case the heading could be "Moderate argument", but the options would be either "Hide argument" or "Delete argument" (and any other options available to the moderator, if there are any).  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bb8a03d8-d494-45c2-aa88-45ae6e465a48)

Let me know if all OK and I will go through and make the edits :)

**Comment by kevincrepin** [comment]
I'm ok with this. Agree that "moderated" seems a bit too vague. On the other hand without context so is "hidden". I think generally more used term could also be "flagged", what do you think of that one @BeccaMelhuish ?

**Comment by BeccaMelhuish** [comment]
@kevincrepin Hmm yes "flagged" could work for the filter! Though it's still not ideal as to me flagged would suggest it includes things reported but not yet acted on, and I think the filter only includes things that have actually been hidden by a moderator, and wouldn't include things that have so far only been flagged? Maybe that's fine though? 

To be fully clear, the filter could be "Topics hidden by moderator", but is that too long? Or just cut out the "Topics" for that particular one (as the user knows we're filtering topics, all the others say it - pinned topics, closed topics, etc.) and cut it to just "Hidden by moderator"?   

Not sure which is best really! Probably flagged (but still using the word "hide" in places we ask the moderator what action they want to take). What's your preference? :)

**Comment by kevincrepin** [comment]
Actually "Hidden by moderator" is ok for me. Or would it be "Hidden by admin"? Bit confused as to admin / moderator usage :)

**Comment by BeccaMelhuish** [comment]
Ah true yes, "Hidden by admin" is better!

**Comment by BeccaMelhuish** [comment]
@ilmartyrk FYI I've changed the code to "hide"/"hidden by admin" for the most part, but in some places it was hard to tell whether the word moderated was actually correct without seeing the context. (As "moderate" is an umbrella term for the act of moderating, which includes hiding something among other things).

So if you can tell from these strings if the context is actually meaning hiding, or the broader sense of the word moderate, please let me know, but if not hopefully @kevincrepin or I can catch it once it's all developed and testable :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2cdd0157-edc8-4f30-bd7d-2ddbc76e08a5)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/47c7f6dd-16e8-45c0-8d24-bb7148f716e3)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2c364b7e-1640-4c0b-a023-0b60040c356c)

**Comment by ilmartyrk** [comment]
I have to say that for public topics the moderator can be our own user with moderator permissions, meaning that this user is stored in moderators table and will receive notifications to moderate arguments/topics that are public. BUT at the same time these users don't actually have any other permissions regarding the topic or argument. Though I guess in this context admin could refer to general system admin too.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Yeah I feel like admin still works for such cases, as in general system admin, as you say :)

**Comment by BeccaMelhuish** [comment]
@anettlinno I'm not sure if this one gets closed or not, as it's kind of 'as resolved as I could' as per comment Oct 26th :)

**Comment by ssin1901** [comment]
@BeccaMelhuish here is the view from Public Topics! To me it seems logical, can we close this for Phase 1? (see screenshot)

<img width="1160" alt="Screenshot 2024-02-01 at 14 18 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/52ce6ba1-32d5-48c1-adbb-50a839f26b6b">
