### ISSUE TITLE
LOGIN: Privacy policy pop-up

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#283]
@ilmartyrk @anettlinno @ssin1901 

According to a Slack conversation with Ilmar, this pop-up appears both when we have made a change to these documents and every user needs to accept them before continuing, or also when a user creates a new account using google/facebook or e-id login they get this popup on first login. 

I'd like to suggest two things:

1. We have two different pop-ups for the two different scenarios (as the message needs to be a bit different for each).
2. We edit the text a bit, to make it a bit less intimidating/over-bearing (the last sentence in particular feels a bit much to me). 

@ilmartyrk (or @anettlinno when back) let me know if the two different pop-ups suggestion is OK, and then I can suggest revised texts accordingly :)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b83012e1-5185-4e7b-a04c-256d44345b5a)

**Comment by ilmartyrk** [comment]
Coding wise I can use the same popup and replace the texts according to use-case.

**Comment by BeccaMelhuish** [comment]
OK perfect, thanks Ilmar! Proposed new texts coming soon then :)

**Comment by BeccaMelhuish** [comment]
OK here come the texts :) 

**For the situations where someone has created a new account via social/e-ID login:** 

**_Pop-up message 1:_** 
"Thanks for creating an account! Before you continue, please take a moment to read and accept our Terms of Use and Privacy Policy."
_**Pop-up message 2 if they click "Reject":**_ 
"Are you sure you want to delete your account? 
Please keep in mind you cannot undo this action.

- By rejecting the Terms of Use and Privacy Policy, you can no longer use this account
- You'll be logged out and your account will be deleted
- All your data will be anonymised and won't be recoverable 
- We'd be sorry to see you go! 

No, go back. (Green button) 
Yes, delete account. (White button)" 

**For the situations where we've changed our terms/policy, and need everyone to re-accept:** 

**_Pop-up message 1:_** "We've changed our Terms of Use and Privacy Policy! To continue using your account, please take a moment to read and accept them."
_**Pop-up message 2 -** exactly the same as the previous one above._

Side note: when trying to make the pop-up appear I discovered it's not quite working as described @ilmartyrk - made an [issue here](https://github.com/citizenos/citizenos-fe/issues/343).

**Comment by anettlinno** [comment]
Thanks @BeccaMelhuish for the text suggestions! Looks very good!

**Comment by BeccaMelhuish** [comment]
@anettlinno most welcome! 
@ilmartyrk I'll leave you to make the changes if that's OK as it's a bit complex (for me) :)

**Comment by BeccaMelhuish** [comment]
@anettlinno does this one need to be moved somewhere for Ilmar to action or OK like this? :)

**Comment by anettlinno** [comment]
Sent to UX/UI redesign project Phase I

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno changed the texts and behavior

**Comment by ssin1901** [comment]
@ilmartyrk Not sure how to test this though. This is for updated Terms and Conditions only right? Not default?

**Comment by ssin1901** [comment]
Created an account with a test Mobile ID. Received appropriate pop up message. Closing the issue! (see screenshot) 
<img width="1227" alt="Screenshot 2024-02-27 at 12 59 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3789027c-002f-48fb-ae72-d30c6c94130b">
