### ISSUE TITLE
Text review: Dashboard final texts? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#284]
@kevincrepin @ilmartyrk @anettlinno @oksks 

Ilmar raised the question of whether these are the final texts for the dashboard, or just dummy ones? They look OK to me, though wonder if we could optimise them..

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3a557b3e-efe4-404d-86d9-94179a2be48d)

I made some slight tweaks in the code though (not yet all showing on the redesign), so they are currently like this:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/715ea6d5-dc1b-4532-a5b6-c2ada4ced684)

**Comment by kevincrepin** [comment]
Multiple selection tho, not multiple choice ;D
