### ISSUE TITLE
Text review: Follow-up phase explanation texts

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#285]
@kevincrepin @ilmartyrk @anettlinno @oksks 

We don't currently have texts for the equivalent of here, but for follow-up:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9b389883-4fe8-4d56-b071-e642a61def84)

For now while we'll just have the MVP follow-up features, I suggest the below.
(I guess unlikely there are any objections, but will wait a bit before updating the code just in case :)) 

**How follow-up works**

Follow-up is the last phase of a topic. After a decision has been made, it's important to keep participants up-to-date with the next steps. 

Here you can post what will happen as a result of the decisions made, and details of any progress or outcomes.

**Comment by kevincrepin** [comment]
Seems good to me.

**Comment by BeccaMelhuish** [comment]
Great - thanks @kevincrepin, code updated :)
