### ISSUE TITLE
Text review: Duplicate topic text needs updating

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#288]
As per Slack conversation, this one needs updating to the new redesign text in the code :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8e2b6447-a90a-4836-b892-ef93e5919fad)

**Comment by BeccaMelhuish** [comment]
@anettlinno this one was beyond me (so needs Ilmar to action) :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I believe this is now fixed with syncing all the translations

**Comment by ssin1901** [comment]
Seems to be missing the line "in progress" (screenshot1)

<img width="1052" alt="Screenshot 2024-02-06 at 14 01 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/faba526c-7c1e-448a-b96f-44064475ad74">
