### ISSUE TITLE
Code in Topic Invitation to new User

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#290]
**What is the problem?**
When a user who does not have an account in the Citizen OS database is invited to a topic and clicks Join Topic, they come to app.citizenos.com and get a message with has code in it (see screenshot)

<img width="1421" alt="Screenshot 2023-10-28 at 17 15 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5facf8eb-9568-4771-b81b-f8646d5899e5">

**Why is this a problem?**
Confusing to the users, might make them think the app is not working properly.

**Possible solution.**
Code should not be there in topic invitation

**Comment by anettlinno** [comment]
Triage 92. Quick fix, 5 min. Sending it to do.
