### ISSUE TITLE
All votes are in missing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#291]
**What is the problem?**
When a user sends a topic to voting normally they can select a deadline OR select when all votes are in. At the moment, only the deadline option is there (see screenshot)
<img width="701" alt="Screenshot 2023-10-29 at 18 14 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9ecf012b-48d7-4d24-a114-b6618e4f90c0">

**Why is this a problem?**
Users have different needs regarding voting systems. For 100 percent consent based decisions, the "All votes are in" option is very useful. 

**Possible solution.**
Option is there in Redesign which is great. However, users in current platform may require this feature as well.

**Comment by anettlinno** [comment]
This feature was removed with the decision #94  because the UX was confusing. Closing this issue.
