### ISSUE TITLE
Facebook Login issue

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#293]
**What is the problem?**
When the user tries to login with Facebook, they receive a confirmation message with a logo that is distorted Citizen OS logo (see screenshot)
<img width="1394" alt="Screenshot 2023-10-30 at 15 26 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4c9f4230-f8d0-4e1f-b4c9-2eefaff6fd9f">

Also this is inconsistent with the Google login where the user is directed to an authentication page every time they log in. 

**Why is this a problem?**
Does not look very good that our logo is distorted. Might scare away users.

**Possible solution.**
Fix the logo

**Comment by anettlinno** [comment]
Triage 92. Low priority issue. Let´s test it after redesign is launched, as it needs some investigation and might be caused from FB side.
Est. investigation time 30 min. Sending to To Do.
