### ISSUE TITLE
Profile>Show my profile in search results>On not working correctly 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#294]
**What is the problem?**
When a user goes to Profile>Show my profile in search results and toggles the on button (see screenshot) others users still cannot find the user (see screenshot)
<img width="1389" alt="Screenshot 2023-10-30 at 17 13 01" src="https://github.com/citizenos/citizenos-fe/assets/72747107/78186897-7050-45b5-802f-c179f3347f61">
<img width="1380" alt="Screenshot 2023-10-30 at 17 13 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/740f9475-621f-49ba-8795-4a766b4a9172">

**Why is this a problem?**
Confusing for those who might be searching for members of their organisation by name

**Possible solution.**
If a users sets their profile to public, they should be able to be added via search

**Comment by anettlinno** [comment]
@ssin1901 users appear after entering 5 characters but it´s good point that if the name has only 3 or 4 characters, then they won´t appear :)

**Comment by anettlinno** [comment]
Triage 92. Closing this issue.
