### ISSUE TITLE
Hyperlink option disappeared in Editor

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#295]
**What is the problem?**
The option to add a hyperlink is not there in the Editor anymore (see screenshot). Problem occurs across Safari and Chrome on multiple devices.

<img width="1380" alt="Screenshot 2023-10-31 at 14 12 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cdb8446a-f188-4bdc-b687-3f054eab875d">

**Why is this a problem?**
Users cannot add hyperlinks to documents. 

**Possible solution.**
Hyperlink should be added

**Comment by ilmartyrk** [comment]
Fixed
