### ISSUE TITLE
Can't close pop-up window

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#297]
**What is the problem?**
1) After clicking the large black "+ Create" button in the top-left corner..
2) ..a pop-up opens, which you cannot escape unless clicking one of the options.

![Screenshot 2023-11-01 at 15 02 47](https://github.com/citizenos/citizenos-fe/assets/34126353/02fb405e-7433-4164-a911-d265ae855075)

**Why is this a problem?**
Can't close it - there's no "X" to close, nor you can click outside of it to close. The only way to escape it is to click the "Back" button, but then it also threw me out of the account once (out of 3 times of verifying this), though I couldn't reproduce the latter.

**Possible solution.**
Add an "X" to the pop-up + allow to click outside of it to close.

**Comment by BeccaMelhuish** [comment]
I think this one might be fixed, as you can now close it by clicking off it?

**Comment by ilmartyrk** [comment]
Thanks @BeccaMelhuish for noticing, will close the issue
