### ISSUE TITLE
Add existing topics to group users and a-z not working 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#299]
**What is the problem?**
A user can only add one public or private topic group at a time (see screenshot). In that context, I was wondering what purpose the users and a-z tab serves anyway?

<img width="1196" alt="Screenshot 2023-11-01 at 13 11 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c1a98142-9aae-4d7a-a59a-62eb900bb3e6">

**Why is this a problem?**
Might confuse users

**Possible solution.**
Can we just remove it?

**Comment by anettlinno** [comment]
Triage 93. Replicated the issue that "Title A-Z" and "Users" tabs are not working. But could add more than one topic in a group.
Est. dev. time 15 min. Sending to To Do.
