### ISSUE TITLE
Automatic reminder for users not working properly

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#300]
**What is the problem?**
When a user goes to Actions->Edit deadline for voting and changes the dates, the reminder option disappears at random. In screenshot 1 (see screenshot) _Automatic reminder for users_ displays options for 2023-11-02 08:45 +0200. However, nothing is displayed for 2023-11-01 10:45 +0200 (see screenshot).

Screenshot1
<img width="1382" alt="Screenshot 2023-10-31 at 14 47 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0bfe7e4d-adf7-4064-8560-48282118d97b">

Screenshot2
<img width="1391" alt="Screenshot 2023-10-31 at 14 46 52" src="https://github.com/citizenos/citizenos-fe/assets/72747107/15216d78-3164-470a-8d9c-fba974586529">

**Why is this a problem?**
User has difficulty adding new vote reminder

**Possible solution.**
User should always have the possibility to add a new deadline and vote reminder, regardless of the date change.

**Comment by anettlinno** [comment]
Triage 93. This issue is fixed. Closing the topic.
