### ISSUE TITLE
Public group image not updating 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#302]
**What is the problem?**
When the User goes to Public Groups and tries to update the image(see screenshot), the image will not update (see screenshot) even when the image is only 277 KB

<img width="1178" alt="Screenshot 2023-11-02 at 14 34 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0a0288f4-e45d-46d8-959f-bb1c8379ab09">

<img width="1203" alt="Screenshot 2023-11-02 at 14 36 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6993f399-f8d1-4a6a-af05-0b819a858dbc">

**Why is this a problem?**
User cannot update Public Group image 

**Possible solution.**
User should be able to update Public Group image

**Comment by anettlinno** [comment]
Triage 93. Needs t bug fix. Est. dev. time 30 min. Sending it to do.
