### ISSUE TITLE
Register button not working

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#303]
**What is the problem?**
Registration button missing (see screenshot) 

<img width="1389" alt="Screenshot 2023-11-03 at 16 04 14" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b0f57343-5c81-49a3-a617-6feb271f5e18">

**Why is this a problem?**
User cannot register

**Possible solution.**
Register button should be there

**Comment by BeccaMelhuish** [comment]
I was wondering if this was a problem found on tablet (@ssin1901 could confirm?), and so tried it at a smaller browser window and I noticed there are two scrollbars that appear at certain size - could be related to the problem? 

But if it is just a tablet issue then not so urgent to fix as for now testers will be using desktop :)  

https://www.loom.com/share/d9ee6b7d20db44c3895c422e23336b0d?sid=287de84d-37da-4b61-bb97-85ff2ed4c8e1

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @ssin1901 scrolling was missing when Sara initially tested it
