### ISSUE TITLE
Logout button missing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#304]
**What is the problem?**
Logout button missing (see screenshot)
<img width="1387" alt="Screenshot 2023-11-06 at 13 24 14" src="https://github.com/citizenos/citizenos-fe/assets/72747107/23e51c99-62e2-48e0-ad45-49d01575f6b8">

**Why is this a problem?**
User cannot log out

**Possible solution.**
Logout button should be added

**Comment by ilmartyrk** [comment]
@ssin1901 Logout button is under profile

**Comment by ssin1901** [comment]
@ilmartyrk checked the documentation and you are correct (see screenshot). I am closing this issue

<img width="1377" alt="Screenshot 2023-11-07 at 12 27 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/914982ed-abd9-4c88-8fa2-296e1cab9ab7">
