### ISSUE TITLE
MISC: Horizontal overflow in certain viewports in Safari

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#305]
**What is the problem?**
In Safari, at certain screen resolutions there is horizontal overflow (see screenshots)
<img width="913" alt="Screenshot 2023-11-06 at 13 29 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8f8a1c90-f6ec-4a1d-97cd-c2af9d5511b7">

**Why is this a problem?**
User loses the main menu when they scroll on certain Safari viewports

**Possible solution.**
Should be the same as Chrome (see screenshot)
<img width="1382" alt="Screenshot 2023-11-06 at 13 33 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1008d017-30a9-4f3d-8a67-690df0fea806">

**Comment by ilmartyrk** [comment]
@ssin1901 this seems to be tablet with nav menu on the top, maybe you could try refreshing and then the menu should appear

**Comment by ssin1901** [comment]
Horizontal overflow issue is fixed (see screenshot). Closing the issue now.

![Uploading Screenshot 2024-01-24 at 12.53.26.png…]()
