### ISSUE TITLE
Mini-voting needs removing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#306]
**What is the problem?**
When a user creates a mini vote via the editor they receive this error on Mac OS Safari and Google Chrome (see screenshot)
<img width="1388" alt="Screenshot 2023-11-06 at 21 53 20" src="https://github.com/citizenos/citizenos-fe/assets/72747107/442e0d27-64da-429d-b1f8-e4262faa2ce3">

**Why is this a problem?**
User cannot easily use the mini vote

**Possible solution.**
No error should occur during the minivote

**Comment by BeccaMelhuish** [comment]
Mini voting isn't included in the new designs, so just needs removing rather than fixing :)
