### ISSUE TITLE
Typo in Dashboard Tour>Main Menu

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#308]
**What is the problem?**
In Dashboard Tour>Main Menu, ie. is written but it should be i.e. 
<img width="1381" alt="Screenshot 2023-11-07 at 12 21 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d6377456-f2e8-4c27-b6d5-6c91b1f7516b">

**Why is this a problem?**
Typo

**Possible solution.**
@BeccaMelhuish tagging you for confirmation

**Comment by BeccaMelhuish** [comment]
Thank you @ssin1901, now fixed! :)
