### ISSUE TITLE
Typo in Topic successfully published message 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#309]
**What is the problem?**
Typo in Topic successfully published (see screenshot)

<img width="1386" alt="Screenshot 2023-11-07 at 12 38 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/09c34fbf-d70d-4eef-b9e0-df359bb3cd04">

**Why is this a problem?**
Typo 

**Possible solution.**
@BeccaMelhuish tagging you for final confirmation

**Comment by BeccaMelhuish** [comment]
Thanks Sara! 
@ilmartyrk I've tried searching for this [here](https://github.com/citizenos/citizenos-fe/blob/redesign/src/assets/i18n/en.json), but can't find it. Are there some strings somewhere else I may have missed in my review?

**Comment by BeccaMelhuish** [comment]
@anettlinno this is one I should be able to edit myself in the translation strings in theory, but couldn't find it
