### ISSUE TITLE
Facebook login not implemented yet 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#310]
**What is the problem?**
It seems that Facebook login has not been implemented yet for Redesign (see screenshot)

<img width="1381" alt="Screenshot 2023-11-07 at 13 45 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f3680208-e9f7-4b7d-bff0-935c9eab5868">

**Why is this a problem?**
User cannot login with Facebook

**Possible solution.**
@ilmartyrk at what stage of the process should we be able to test this?

**Comment by ilmartyrk** [comment]
@anettlinno @ssin1901 Facebook login in testing will work for users that have been added from Facebook app developer console.  I think it will not be fully implemented as it is for testing and there are a lot of different with Facebook popping up through different times that will make it more difficult to manage for our testing app.
