### ISSUE TITLE
Email strings to delete/edit/combine

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#312]
@ilmartyrk As per the Slack messages, there are some email text strings that need to be deleted following my edits (as they are now duplicates) or combined (so they are all on one line/paragraph, not multiple) or more complex edit is needed. 

**To delete unless highlighted in bold**

- [x] [reportTopicReportReviewModerator](https://github.com/citizenos/citizenos-api/edit/redesign/views/emails/reportTopicReportReviewModerator.html) Delete rows 26-31. Also delete row 84. Also **edit 'Topic X'** so it's the topic's actual name. 
- [x] [reportCommentCreator](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportCommentCreator.html) Delete row 24. 
- [x] [reportTopicModerateMember.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicModerateMember.html) **Edit out** speech marks from topic name row 22. Also delete row 116. 
- [x] [reportTopicModerateReporter.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicModerateReporter.html) Delete 81-83. Also delete 131-132. 
- [x] [reportTopicReportMember.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReportMember.html) **Combine** 21-25. Delete 28 and 100. 
- [x] [reportTopicReportReporter.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReportReporter.html) Delete 102-103. Also delete 114. Also **move** 'what happens next?' section downwards - should be under the report info? 
- [x] [reportCommentModerator.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportCommentModerator.html) **Combine** rows 20-32 into one paragraph if possible. If it is, please change "The argument's author" to "Its author". 
- [x] [reportTopicReportModerator.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReportModerator.html) **Combine** rows 22 and 25 into one paragraph. Then also delete row 65. 
- [x]  [reportTopicReportResolveMember.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReportResolveMember.html) Delete row 43. 
- [x] [reportTopicReportResolveReporter.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReportResolveReporter.html) Delete row 43. 
- [x] [reportTopicReviewModerator.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReviewModerator.html) Please check that this is a duplicate of [reportTopicReportReviewModerator](https://github.com/citizenos/citizenos-api/edit/redesign/views/emails/reportTopicReportReviewModerator.html)? I didn't edit it, as it seemed to be the same just with a different name. Please let me know :)

**Comment by BeccaMelhuish** [comment]
@anettlinno these are all ones I wasn't able to do, so need Ilmar's skills :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this list is really confusing, the lines seem quite random  I don't understand what and where should I edit or remove

**Comment by BeccaMelhuish** [comment]
@ilmartyrk sorry it was so confusing! I should have done a doc with screenshots :) 

Have gone through them all now, and mostly looking good, except these ones below. 

https://github.com/citizenos/citizenos-api/edit/redesign/views/emails/reportTopicReportReviewModerator.html
Please delete these lines and see [this topic](https://github.com/citizenos/citizenos-fe/issues/321) too:  
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5bf667e8-ce4e-4c4c-8d27-aa754996d8cb)

For this one the edit is fine, but the 'moderator name' bit doesn't seem to be working: 
https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportCommentModerator.html
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0b3e51d3-5c15-411e-82bf-85c45488c3a5)
