### ISSUE TITLE
Text review: "an argument" wording moderation emails? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#313]
In the notification emails for a reported argument, I believe we send the same email regardless of whether it's an argument, or a reply comment to someone else's argument? (In which case the wording is not quite right for all scenarios).  

Firstly, do people think this is a problem, or this is just me being pernickety? :D 

Secondly, if it does matter, should we solve it in one of the two following ways? 
- Change the wording to "a contribution" or "some discussion content" has been reported
- Send a different email for each scenario:
1. One saying "an argument has been reported"
2. One saying "a reply has been reported"  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a835408a-2420-4323-b6e1-88d58b34477a)

**Comment by anettlinno** [comment]
I just learned a new word -- pernickety :D 
I think "Discussion content was reported" sounds good. I´m not sure about "Some"... Maybe without that or "Your discussion content was reported"... 
@BeccaMelhuish

**Comment by BeccaMelhuish** [comment]
@anettlinno haha yes it's a good one :D  
Hmm just "discussion content" on its own doesn't really work, and "Your" is only relevant when it is theirs, but often it isn't.. (I.e. the emails that go to moderators).  
Shall we go with "A discussion contribution" maybe? Or the second option of sending two different emails depending what sort of content it is?

**Comment by oksks** [comment]
I find "discussion contribution" is pretty hard to translate well. Ideally, could we please simplify this somehow, maybe a'la:

- "Some content has been reported under topic X:", or
- "Topic X contains some reported content"

**Comment by BeccaMelhuish** [comment]
@oksks @anettlinno Shall we just go back to "Some discussion content" then? :) 
It could just be "some content" but it's a bit vague..

**Comment by anettlinno** [comment]
"Some discussion content has been reported..." sounds good to me :) @oksks @BeccaMelhuish

**Comment by BeccaMelhuish** [comment]
@anettlinno OK great I can change this in the code then :)

**Comment by BeccaMelhuish** [comment]
I have done this now, though I realised that for the email that goes to the person who posted the argument/reply, "your discussion content" / "your content" would be a bit odd, so I went for "your discussion contribution" / "your contribution" in that context :)
