### ISSUE TITLE
Edits to emails social media buttons

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#314]
Please remove the Medium one and change Twitter to X :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0c733ea9-7393-4919-89f9-747d133a875c)

**Comment by BeccaMelhuish** [comment]
@anettlinno does this one need to be moved, or OK here? :)

**Comment by anettlinno** [comment]
Yes, please let´s remove Medium (also from the left menu in platform)

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/3582cd54-d6ba-409d-8caf-96786ca4c9a5)

**Comment by ilmartyrk** [comment]
@kevincrepin can I get a new X icon for e-mails please :)

**Comment by kevincrepin** [comment]
@ilmartyrk Updated!

**Comment by BeccaMelhuish** [comment]
@ilmartyrk an odd thing happening here now, in the emails: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ad575219-aa19-4c1f-9c47-f8457fa98123)
