### ISSUE TITLE
Spammy looking moderation reference IDs

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#315]
As per my Slack post, I would like to delete all these reporting IDs from the email signatures as they look very spammy and don't add anything useful to the subject headings anyway (I believe?). Any objections? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/00c46fc6-936d-409b-b99d-0d6046ecd4f9)

They are also included in the body of the emails, and again look a bit like an error rather than a real ID. Is there a way that we can simplify them? Or is there actually a need for the user to see it, or its more an internal thing? (Please ignore darker yellow highlights). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5855f990-848d-43c4-af7e-f53d9e16af1d)

**Comment by kevincrepin** [comment]
Agree on removing from subject line. Not sure if for some reason someone needs to know the number for some kind of follow-up?

**Comment by BeccaMelhuish** [comment]
OK thanks @kevincrepin, I will remove from the headings then.
Then @ilmartyrk and @anettlinno what are your thoughts on the ones in the email body?

**Comment by anettlinno** [comment]
Reference number is probably helping to identify and find the reported arguments/topics, but I´m not entirely sure, why we display it there. @ilmartyrk do you know?

**Comment by BeccaMelhuish** [comment]
Or if there's a possibility of making it an bit less long perhaps? :)

**Comment by ilmartyrk** [comment]
I guess it's OK to leave it inside the report details box in e-mail, but agree with removing from the e-mail subject
