### ISSUE TITLE
Text review: Invite email language about "discussions" and "decisions"

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#316]
In the invite emails we have language about decision-making and discussions, which won't always be relevant to the topic in question. 

E.g. in the email subject: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9cac807e-e034-4e31-bdb0-7dd157d3f6a8)

And in the email itself: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a2e36788-7c1f-4473-9966-36589beb4fd9)

I can think of are a few contexts where "collaborative decision" doesn't make sense, e.g.: 
- It's a public discussion on a topic, but there isn't going to be any decision made, it's just a chance for people to discuss and share views, etc.  
- It's an idea gathering/consultation type of initiative, but again, no plan for a group decision. 
- It's a petition or signed letter (not a key use case we "market" though). 

And obviously "join the discussion" doesn't make sense if it's a vote topic, that just goes straight to vote with no discussion. 

Some suggestions for getting around this: 

- We just say "So-and-so is inviting you to join a topic" for the invites ones
- When the topic is a vote topic, we send out a differently worded email (relevant to voting, not discussion)

**Comment by kevincrepin** [comment]
I agree, more straightforward and clear to the user.

**Comment by anettlinno** [comment]
I also agree that it makes more sense in different use cases.

**Comment by BeccaMelhuish** [comment]
OK I will edit the texts to be more general, and make the button "Join topic" rather than "Join the discussion" :)
