### ISSUE TITLE
Email block headings for clarity

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#317]
@kevincrepin when doing the email texts review, I felt some of the boxes could use headings, to make it clear what they are. For example in this one it took me quite a while to work out what these two boxes were. What do you think? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/466c9c16-0139-400b-9d91-6c5dae0d3271)

**Comment by kevincrepin** [comment]
It was originally designed that the 2nd box label would actually hold the "ID" of what is above it:
![Screenshot 2023-11-10 at 15 38 44](https://github.com/citizenos/citizenos-fe/assets/26792281/335c059f-85c3-4e47-9817-19c7144381b0)

I agree in its current form it is a bit confusing. I made this alternative than can make it clearer: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=9211%3A2894&mode=design&t=BeGEzNnCVbUnptbP-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin yes this is much clearer, thanks! 

Though as per [this discussio](https://github.com/citizenos/citizenos-fe/issues/313)n, should we call it "Content", rather than argument? :)

**Comment by kevincrepin** [comment]
Updated here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=835%3A90147&mode=design&t=PhFtA9pToszSoRt5-1

**Comment by BeccaMelhuish** [comment]
Thank you @kevincrepin! Any chance you could share screenshots along with the Figma links though, not sure about others but they often don't work for me sadly.. (I paste the link to my browser, it then pretends to open it in the Figma app, but doesn't actually go to the right place..)

**Comment by kevincrepin** [comment]
Sure, no problem. Where do you end up tho? :)

![Report - Argument](https://github.com/citizenos/citizenos-fe/assets/26792281/9a6d1728-80f8-42b2-9853-7ff5df1eef5e)
![Report - User](https://github.com/citizenos/citizenos-fe/assets/26792281/b1a04fba-cdc6-4dea-b194-9148520659e2)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Perfect thank you! I think it just opens where I last was in the app, rather than moving to the correct place, though today it is working fine so hoping it stays that way :D 

So @anettlinno @ilmartyrk, this would again be something for Ilmar to action rather than me, but is the same thing as [this issue](https://github.com/citizenos/citizenos-fe/issues/320)

**Comment by BeccaMelhuish** [comment]
Closing this as seems to be done (correct me if wrong Ilmar)
