### ISSUE TITLE
Text review: No indication that a topic was previously reported 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#318]
Am wondering if this is in keeping with our philosophy on moderation? As usually there is a visible trail in the moderation process? (I think that's the case for arguments? Or is it not?) Personally I'm torn which is best, just raising it for discussion if relevant :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fd6811e0-652e-4a26-b1fa-5bd6c78b84fc)

**Comment by anettlinno** [comment]
@BeccaMelhuish this is strange sentence there, I agree. This email will be sent after topic has been reported and revised by Admin user, if I understand correctly? And this is confirming that now everything is OK? If so, then I would just remove this.

**Comment by BeccaMelhuish** [comment]
@anettlinno yes that's right :) Though actually I was wondering whether there _should_ be an indication that a topic has previously been reported, like a trail showing the history (as we do with edited arguments I believe?). Or if we do want it to be like this - no indication that anything was ever wrong.

**Comment by anettlinno** [comment]
@BeccaMelhuish From the UX perspective I would say that if a topic has not been reported previously, then it´s not necessary to mention that. If it was reported previously then showing the history would be valuable, but I´m not sure how hard it is to implement it from the technical side, @ilmartyrk

**Comment by BeccaMelhuish** [comment]
@anettlinno yes in this scenario a topic was reported, and this is an email saying the report was resolved :) 
Maybe something we can think about in Phase II, but leave it as it is for now?

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish we could probably create a report trail, but not sure if it makes any sense in the long term. Eg. user creates a public test topic, it gets reported. Then the user decides to follow the resolving process and creates a proper discussion topic and sends it for a review. From topic content perspective it makes no sense to show this trail. 

Also in other cases topic could initially have some real content and also a discussion starting related with that content . And after the review process the original content and arguments could get out of sync context wise.

But I guess it's up for discussion in the future.

**Comment by anettlinno** [comment]
Good points, @ilmartyrk !

I would say that let´s just remove the sentence "There will be now indications..." from emails for now and if we´ll see that it´s needed (any use cases?) then we´ll come back to it. 

@BeccaMelhuish please close the issue after editing the email texts.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @anettlinno I'll do it myself
