### ISSUE TITLE
EMAIL: topic titles always in bold? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#319]
@kevincrepin am I right in thinking that all topic titles such as these below should be non-italic and bold in the emails? And that if they're linked, they should be in dark blue bold? (Not underlined?) There's some inconsistency currently but wanted to check with you before suggesting @ilmartyrk adjusts them :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/688ab842-78ff-46d7-b316-50b1845cfce5)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/47f21e11-472d-4ad6-b9d3-25f0368c2b02)![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3413fa2f-5774-4166-a45d-b2be85e2c3ec)

**Comment by kevincrepin** [comment]
Actually it was designed to not have the topci title in the paragraph but always have it in some "summary" or "overview": https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=763%3A80740&mode=design&t=BeGEzNnCVbUnptbP-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ah yes true for some! But not for others like these for example :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d88aff42-cfb8-4cea-b66b-a1b860568e9b)

Looking through the emails there are a few that don't have any sort of summary box, like this one (below top), though the topic heading is at the top. And also others where there is a summary box, but it doesn't have the heading in it (below bottom).  

So for the ones that do have a summary box with the title in it, I can edit the texts to remove the heading from the intro copy. But for the ones that currently don't have it, should @ilmartyrk add summary boxes to all of them with the titles in (or add titles to the summary boxes that exist already without them), and then I will edit the intro texts once that's done?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4c69a9a5-8dbc-445a-9603-af3ed3a73287)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a7afe978-8c39-49b3-8d7c-b307d58bd859)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I believe you can choose what ever options looks better.  If you still think that topic title is necessary then I guess it should be in bold, but as we have it already in the header box there is not actual need for the title in the summary. From localization point of view it is probably best to not have too many script elements as they might get broken by the translators

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK thank you, I will go through and see how I think it best for each, and make a Github to-do list with anything I'm not able to edit myself!

I think it prob best to have the topic title in the summary and hyperlinked where possible, so the user can easily click through to view the topic in question in case they want to access it. 

@kevincrepin Will wait to see if you have any other thoughts/preferences on this before going through them all, probs early next week :)

**Comment by BeccaMelhuish** [comment]
OK I've gone through and removed the topic title from the body copy for all the emails as discussed (as the titles are in the emails headings, and links through to them either in the summaries or the "view topic" buttons). 

The only place where the initial issue still stands is here (below) where the group names need to be made bold, dark blue and hyperlinked please @ilmartyrk :) 
(As the email heading is about the topic not the group, and there isn't a summary box in the optional notification emails layout - just this text then "view topic"). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a78eefab-e48d-439e-938f-77b70edac027)

**Comment by BeccaMelhuish** [comment]
@anettlinno so in summary, most of this I could do, but just a bit left for Ilmar as per previous comment :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think these items are not sent as notifications I fixed the translations and added support for the links but it will need some update to send notifications about these actions too. Anyway changed all the italic items to bold in all notifications
