### ISSUE TITLE
How should personal messages look in emails? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#320]
@kevincrepin When there is a personal message from someone included in an email notification (like an invite for example), how should it be displayed? 

Should it be at the top of the summary box? (Like this one isn't?)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8e27cbc1-28d9-407d-839a-2dd64eab8066)

I.e. like this one already is? (Please ignore highlights):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3f86252a-bcd3-462f-a7e0-defd6dc8317f)

Or should it be something more like this, that you have in one of the Figma designs? (But adapted slightly for the context? With a heading or something?) 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c2e2c7b6-ed5e-4d99-b27b-f020a9134bf2)

**Comment by anettlinno** [comment]
I just notice that we are saying "Participant Ilmar..." or "User Ilmar..." but maybe we could just say "Ilmar Türk has requested..." instead. It´s like we´re categorizing people based on odd indicators... WDYT?

**Comment by BeccaMelhuish** [comment]
@anettlinno very much agree and really wanted to change these, but on discussion with @oksks sadly it seems it's not possible to remove them for translation reasons :( 
@oksks there's no way we could find a work-around for this is there?  
(This is a bit of a separate issue though)

**Comment by oksks** [comment]
We really only have 2 options:

1) English to read great, but translations (in any languages with genders) can only be tailored to one gender, while usernames have 3 genders so it will look Frankensteiny. 
If we say "user" or "participant", etc before the variable, then the preceding noun defines the gender used and what follows is no longer affected by the username or any other variable used.

2) English to sound a bit techy, but translations will look correct in any language.

Up to you:) I vote for techy and correct, but I'm biased.

**Comment by BeccaMelhuish** [comment]
@oksks there's no way to add some sort of note/instructions for translators in certain languages, i.e. always add "User" or "Topic" before the username or topic name, by any chance?  

Though I think for the moment the 3 main languages that the platform gets used in (and our 2 target countries) - English, Estonian and Indonesian (I believe?) - don't have gendered nouns? So maybe it's preferable to change them to work better in these languages for now anyway?

**Comment by anettlinno** [comment]
Thanks @oksks for the explanation! I think if it helps to avoid Frankensteiny situations in the future translations and helps (volunteer) translators to better understand the context, then we probably should go with adding "participant" or "user" in front of the User´s name @oksks 

Initial issue needs still @kevincrepin´s input :)

**Comment by kevincrepin** [comment]
Updated so that all emails now have this label and so do the messages: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=764%3A81647&mode=design&t=PhFtA9pToszSoRt5-1

**Comment by BeccaMelhuish** [comment]
Ah super thanks @kevincrepin! 

This is for @ilmartyrk to action now then, across all the emails :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Was just checking the status of this one and actually seems I'm not getting a personal message when I invite myself (from a different account). Will add bug label too :) 
(Not sure if it's the same for group invite email, or only topic invite). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/84dd18e5-9fd5-40f2-b195-6a2f0c082364)
