### ISSUE TITLE
Report resolved email needs more clarity - "Original report" heading? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#321]
This email is a bit confusing, as it shows the original report (type and reason) just under the message from the admin, and the rest of the content is about the fact that the report is no longer valid (as the issue has been rectified). 

Needs a bit of designing for more clarity? E.g. a title saying "Original report"? 
Also related to [this issue](https://github.com/citizenos/citizenos-fe/issues/320), maybe the message should be in a separate from the rest? And have some sort of heading to say who (or what sort of person - i.e. admin/editor of topic) it's from?  

@kevincrepin wdyt? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/41e10574-30ba-4dd6-9cfa-c4b30a9a9ebe)

**Comment by anettlinno** [comment]
Explanatory text also looks a little bit fragmented. @BeccaMelhuish let´s try to explain what happened in two simple sentences, currently it sounds like robot has written it :D

**Comment by BeccaMelhuish** [comment]
@anettlinno yes that one's re-written, and I believe it was indeed to two sentences :)

**Comment by anettlinno** [comment]
@BeccaMelhuish so this issue is solved? Can we close it or still needs Kevin´s input in separating the message from the rest?

**Comment by BeccaMelhuish** [comment]
Still needs @kevincrepin's input on how to make it clearer which bit is the original report and which bit is the more recent message from the person who has sent it for review (and also on how messages like this should be displayed though that's [this issue](https://github.com/citizenos/citizenos-fe/issues/320)) :)

**Comment by kevincrepin** [comment]
Updated this here with the new label logic: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=9722%3A94107&mode=design&t=PhFtA9pToszSoRt5-1

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk, as per my comment in [this issue](https://github.com/citizenos/citizenos-fe/issues/335), I've not been able to get this email to fire (into my inbox) as I can't see how the system works.  So Ilmar please either send me a copy of the email to check or just mark it as closed if it's done and I'm sure it's fine :) 

https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReportReviewModerator.html

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I've forwarded you the e-mail, you can also get it if you submit topic for review
