### ISSUE TITLE
'Save topic' button (in 'Actions' menu not working) - can't edit settings

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#322]
@ilmartyrk @ssin1901 
Trying to change a topic from private to public, via the actions menu, when clicking the "Save topic" button, it's just 'dead' - nothing happens. (Regardless of what trying to do, but in my case making public was my reason for being there). 

Happens both in test and in live. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/abd80394-7dcb-4e4e-86e5-9d19b390e362)

**Comment by anettlinno** [comment]
Triage 93. Probably the issue is on public/private topic. Needs some investigation. Sending it to do. Est. investigation & dev. time 30 min.

**Comment by BeccaMelhuish** [comment]
Seems to be the save button itself (not connected to public/private), as same thing happens when you try to edit categories (both in live and in test)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I could not replicate it, it is working for me, What browser were you using, or what permissions do you have on the topic, is it your own topic?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Hmm that's odd, I tried it on Chrome in both test and live and got the same thing. Just check on Firefox in both and same thing. Yes a blank topic I've created for the purpose of trying it. Also tested changing the categories in our Marketing meetings topic (which I am an admin of), same thing. Also whether I do it from within the topic or within the dashboard - same problem..

**Comment by anettlinno** [comment]
@ilmartyrk replicated the issue. My own topic (Monthly Meetings 2023) and used Chrome.
