### ISSUE TITLE
GROUP: Uploading image of 5.9 MB throws up this error only at the end of the Group process

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#323]
**What is the problem?**
A user who creates a group>Visibility>Public and uploads an image of 5.9 MB is able to complete all the steps without error messages and even gets "Group successfully created" message (see screenshot)
<img width="1379" alt="Screenshot 2023-11-11 at 22 57 44" src="https://github.com/citizenos/citizenos-fe/assets/72747107/218af9c7-696b-49b0-9a3a-f29b8b50d88f">
. 

However, they are not redirected to the Public Group list. Upon refreshing, this error is displayed (see screenshot)
<img width="1387" alt="Screenshot 2023-11-11 at 22 53 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/af223a31-c15e-4c9e-9268-1ad118242faf">

**Why is this a problem?**
User should not be able to complete all the steps without receiving an error than the image size is too large (with the correct image size present in the message).

**Possible solution.**
Add an error message to the first step of the process so that the user can correct their actions during the initial step, instead of going through all the effort and then seeing an error message

**Comment by ilmartyrk** [comment]
@ssin1901 this should be fixed with image resizing

**Comment by ssin1901** [comment]
Works now (see screenshot) and closing issue. 

<img width="1187" alt="Screenshot 2024-02-01 at 14 25 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bf7e6d40-b97b-458e-aad8-f07f6f827927">
