### ISSUE TITLE
GROUP: Commas in group names display with special characters in invitation email 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#325]
**What is the problem?**
When a Group Name has a comma, it is displayed with special characters in the invitation email (see screenshot)

<img width="1389" alt="Screenshot 2023-11-12 at 22 23 31" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6f1081fa-1818-409e-8e32-1519c4c15fed">

**Why is this a problem?**
Looks a little spammy 

**Possible solution.**
@ilmartyrk @BeccaMelhuish not sure if anything can be done from our side

**Comment by ilmartyrk** [comment]
@ssin1901 @anettlinno @BeccaMelhuish closing as duplicate of https://github.com/citizenos/citizenos-fe/issues/450
