### ISSUE TITLE
Vote description not being saved 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#327]
**What is the problem?**
A user who has entered a vote description between 1 - 255 characters (see screenshot1) receives errors when they try to publish their vote (see screenshot2)

However, the user has  (see screenshot) 
<img width="1376" alt="Screenshot 2023-11-13 at 00 04 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e147bd15-4954-4a2f-a0fa-e82645a1119e">

<img width="1386" alt="Screenshot 2023-11-13 at 00 03 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9f043ea6-95e7-46f5-8aaa-f5eca2cdb4e0">

**Why is this a problem?**
User cannot publish their vote

**Possible solution.**
User should be able to publish their vote if they have entered text between 1 to 255 characters long. Additionally, the character limit should also be indicated under vote description.

**Comment by ilmartyrk** [comment]
@ssin1901 this error is actually for the vote question, but as the field in database is from old times and has name description, this is the default error

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno I don't full understand this one but it seems like a high priority to fix before testing (and will add the label if so)? If it means publishing a vote topic isn't possible, or did I misunderstand?

**Comment by anettlinno** [comment]
I also received the same error message and discovered that vote question was missing. Correct error message should be added, prioritizing this issue and sending it To Do.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno please check if fix is working for you

**Comment by BeccaMelhuish** [comment]
Just checked and got the right error messages in the right place :)

**Comment by anettlinno** [comment]
Yes! Worked for me too! Closing this issue as this is fixed now.
