### ISSUE TITLE
Logged in user gets error while trying to access a Public Topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#328]
**What is the problem?**
A logged in user gets an error message (see screenshot1) while accessing a Public Topic while a user who is not logged in does not (see screenshot2)

<img width="1391" alt="Screenshot 2023-11-13 at 12 13 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ca883861-e25a-4ae7-8cec-9f62c25e6b88">

<img width="1385" alt="Screenshot 2023-11-13 at 12 15 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1a0bf072-ffca-4216-8721-0469f53e26c7">

**Why is this a problem?**
Logged in user prevented from accessing Public Topic

**Possible solution.**
@ilmartyrk @BeccaMelhuish shouldn't everyone be able to access a Public Topic regardless of whether they are logged in?

**Comment by ilmartyrk** [comment]
@ssin1901 it is actually not error preventing user access to topic, as you are already seeing the topic, it actually is related to loading groups list and it will be fixed from API side

**Comment by anettlinno** [comment]
Issue is solved, unable to replicate it. Closing the issue.
