### ISSUE TITLE
TOPIC: Add Attachments throws up an error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#330]
**What is the problem?**
When a Logged in User tries to Upload a file, they receive an error (see screenshot)

<img width="1389" alt="Screenshot 2023-11-13 at 12 26 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2d71d192-6530-4dce-a1ef-218b8b8c0b79">

**Why is this a problem?**
User cannot upload attachments

**Possible solution.**
No error message should be thrown up

**Comment by anettlinno** [comment]
Unable to scroll down the page for adding attachments: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/1b090242-28a5-4d44-b7bf-14810f0a03cb)

**Comment by ilmartyrk** [comment]
@anettlinno should be fixed now, @ssin1901 can you add more information

**Comment by ilmartyrk** [comment]
@ssin1901 I've checked and you probably didn't have permissions to add the attachments, I hadn't hidden the edit options for topics users didn't have permissions for

**Comment by anettlinno** [comment]
@ilmartyrk I tried to add attachment (upload files) as an admin on voting topic and failed. Got the same error message as @ssin1901 did: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/efde0525-acf0-478f-a91e-248c5034d74e)

Linked with this issue: https://github.com/citizenos/citizenos-fe/issues/392

**Comment by ilmartyrk** [comment]
@anettlinno @ssin1901 can you possibly share what kind of files did you try to upload (size, type)

**Comment by anettlinno** [comment]
@ilmartyrk I tried to upload our Annual Report PDF file, size 3.64 MB

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk for me this is a high priority one to get fixed before testing, added the label accordingly :)

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish this is a really weird issue, I've debugged it on the server and on my local machine. It works well on my local machine, showing all proper error messages. On the server side it seems to work too as it gets all the same errors in the same places also reaches the place where the error response is sent back to the user, but for some weird reason the error response isn't more over any response is not getting back. Will investigate it later,I don't believe it is TOO critical to stop user testing or postpone any other activities.

**Comment by BeccaMelhuish** [comment]
Ok yes noted thanks @ilmartyrk :) 
You said something today though about 'It only happens when X'? Remind me what X was? (Then can bear that in mind for test prep).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish only if file type is not allowed or file size is over the limit. I'll try to add checks on our FE side for fix

**Comment by ilmartyrk** [comment]
Triage 95. File types error needs some tweaking to make it more understandable, also API side needs research to understand why it is not working on heroku, but works properly on local deploys (in ng serve and also using final built code)

**Comment by ssin1901** [comment]
Could not replicate this specific error so closing
