### ISSUE TITLE
SEARCH: Information about Global Search needed for Testing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#331]
**What is the problem?**
@ilmartyrk @BeccaMelhuish I could not find in the documentation what happens when there are lots of results in Global search. Is it pagination or lazy loading i.e when the user scrolls down? Or is there a limit based on relevance?

See screenshot for more information (see screenshot)

<img width="1383" alt="Screenshot 2023-11-13 at 13 03 44" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3440c923-9e9c-436d-87ee-11bd560a5ca7">

**Why is this a problem?**
Need it for testing

**Possible solution.**
Not urgent at the moment but should be ready before January.

**Comment by ilmartyrk** [comment]
@ssin1901 it's a little different than in design, but under each section where are more results there is a view more results link, and it will load more topics/groups into that section. Eg. if you have more topics under my topics it will have view more results link as the last item and after clicking it will only load more topics to the my topics list

**Comment by ssin1901** [comment]
Works as expected based on @ilmartyrk input above (see screenshot1 and screenshot2)

<img width="1440" alt="Screenshot 2024-01-25 at 16 00 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/47ff9a09-09a1-4385-825a-1a704146c601">

<img width="1440" alt="Screenshot 2024-01-25 at 16 00 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9f8aa061-b377-41eb-ba38-93333df6ffc9">
