### ISSUE TITLE
Duplicate email text files for moderation

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#333]
@ilmartyrk I'm making an issue just in case you missed it on Slack. These two below seemed to be the same thing? So please note that I did the text review and edits on the top one, and ignored the second one :) 

- [views/emails/reportTopicReviewModerator.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReportReviewModerator.html) 
- [views/emails/reportTopicReviewModerator.html](https://github.com/citizenos/citizenos-api/blob/redesign/views/emails/reportTopicReviewModerator.html)

**Comment by ilmartyrk** [comment]
ignore reportTopicReviewModerator.html this is something old
