### ISSUE TITLE
DISCUSSION: Order by Argument Type not working

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#334]
**What is the problem?**
When a user clicks Order by Argument Type>Con they still only see Pro arguments (see screenshot). 

<img width="1382" alt="Screenshot 2023-11-14 at 22 31 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a6b38ee7-9efb-4026-bde0-b91f6e67c06a">

Other Argument types are not working either.

UI also seems to be incomplete 

**Why is this a problem?**
User cannot order Argument by Type

**Possible solution.**
If a User clicks Order by Argument type->Con arguments, they should get only con arguments.

**Comment by ilmartyrk** [comment]
@ssin1901 it currently works differently, you can actually filter by type, ordering still has two options at Phase I

**Comment by ssin1901** [comment]
Cannot execute the test because of #625

**Comment by ilmartyrk** [comment]
@ssin1901 this should be fixed now with https://github.com/citizenos/citizenos-fe/issues/625

**Comment by ssin1901** [comment]
Fixed (see screenshot)

<img width="1166" alt="Screenshot 2024-02-06 at 15 04 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2ad35fe1-939f-401a-b5ef-a2eab835a394">
