### ISSUE TITLE
EMAIL: Deleted topic notification email - check if send and consider button if so

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#337]
@ilmartyrk as just discussed, need to check if we do send a notification email when a user has deleted a topic, as if so the "View topic" button below this text presumably won't work :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bf180491-89ab-448f-9943-de5c52d48bb7)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish checked and we do send out notification e-mails for this action and the link will refer to topic, but will result in error, so I will try and fix this while working on the e-mails

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix for this issue, View topic button will be hidden for topic delete notification

**Comment by ssin1901** [comment]
@ilmartyrk are email notifications ready for testing yet?
