### ISSUE TITLE
Add references to ideation back into translation strings 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#340]
When we have the ideation feature added, we need to go through the Figma and search for all references to "ideation" that were edited out of the copy, and add them back in again.

**Comment by BeccaMelhuish** [comment]
E.g. here, removed for now: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a7b90943-3168-47b3-8d7d-b8b96264df4d)

**Comment by BeccaMelhuish** [comment]
And will be removed from here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/de4c8ca6-b109-4a36-8294-65f6c7cc2631)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish closing this issue as we are going through ideation and its setup deeply anyway
