### ISSUE TITLE
Click password reset opens a new notification without closing the old one

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#350]
**What is the problem?**
When a user goes to Forgot your password and clicks Send reset code multiple times, a new notification appears under the old notification (see screenshot 1, screenshot2)

<img width="1438" alt="Screenshot 2023-11-17 at 11 05 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a9bfc040-b3b9-400b-a9bc-04db0c8ff751">

<img width="1438" alt="Screenshot 2023-11-17 at 11 04 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/23a6317b-1c61-4e17-aa92-50537fb8c415">

**Why is this a problem?**
Does not look right to the user

**Possible solution.**
When the user clicks Send Reset the second time, the first notification should disappear

**Comment by anettlinno** [comment]
Tested and works as it should -- when clicking multiple times on "Send reset code" button, I only receive one "success" message. Closing the issue as this is fixed.
