### ISSUE TITLE
TOPIC: - Add attachment (upload pdf)

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#353]
Uploading attachment displays 2 error messages one with message:
0 - Http failure response for https://test.api.citizenos.com/api/users/self/topics/b64464f4-13b2-4d19-9eb3-f9e70e180080/attachments/upload: 0 Unknown Error *

second has no error body

**Comment by ilmartyrk** [comment]
Seems to be related to file validation on server size, should probably implement something on the client side

**Comment by anettlinno** [comment]
Triage 99. Replicated issue. Needs some investigation and fix, approx 1 hour. Sending it to do.

**Comment by anettlinno** [comment]
@BeccaMelhuish next to attachments there could also be information about file size and type limits (50 MB). Maybe this shall be solved with tooltip, WDYT?

**Comment by ilmartyrk** [comment]
I updated the code and also changed configuration in testing env. This issue is caused by Heroku as the big file upload is canceled, but data is still sent it triggers H18 error that overrides our API response with error code 503, Not sure how to override it for now, but FE validation will help

**Comment by ssin1901** [comment]
@ilmartyrk tested with our Annual Report 2.2 MB and a 5.9 MB file. Got this error message (see screenshot).
<img width="1292" alt="Screenshot 2024-03-06 at 15 57 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2d265ae9-0d87-4a0f-acd1-f64f1faf5d8e">

To me it seems that this particular issue is fixed, opening another one for the incorrect file size text.
