### ISSUE TITLE
TOUR: Onboarding experience for new users - reconsider copy & visual emphasising (UX)

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe#355]
**What is the problem?**

1. 1st step of the tour "Create actions" gives hints about creating new topics, gathering ideas, proposing a new vote or creating a new group. Some users have said that once they experience the platform for the first time or haven't yet, understanding what's meant under topic is not so clear. First time user might have a confusion between the difference of a topic and discussion.

2. 3d step of the tour "Activity feed": here in the copy it's not so clear what activity and this might not give a good understanding to the user. Why is the 

3. 4t step of the tour "Search": The text Global activity is confusing. Does this mean I see absolutely all notifications and activities automatically when I make an account? Is this needed for the users? 

4. 5th step "Topics": Here also (as previously) "topics" is not contextualised. Could be needed? The text "populated this space with popular" seems a bit repetitive in sound to me (populated-popular). 

5. UX issue regarding blurred background and tour step: It's hard to notice with blurred background and no animation or special visual attention added that in the tour, the pop up text actually shows you where the section is on the platform dashboard. I only realised this in the "search step". 

**Why is this a problem?**
1. First step might not be clear for users and they won't be able to evaluate at this stage what is a topic, what's it for. 
2. Third step might not give good enough understanding how activity feed is useful and what sort of activities are shown and why. 
3. If the "Global activity" shows activities across all topics (as the name "global" indicates) then this will probably be unnecessary for the user and cause noise. The description says "activity within a topic you're involved in" – so this indicates only selected notifications. Button suggest something else to me.
4. Not a problem probably, just something that caught my eye. Contextualising a bit might help the users better understand why they even need this feature.
5. It does't make it clear enough where this function is - which would be one of the goals of the onboarding. Visually you don't grasp quickly enough that you're taken to the right part of the platform. What's more visual throughout the tour is the blurred "News" view and some bigger buttons (like "+ Create"). Topics part and Groups is especially hard to connect visually.

**Possible solution.**
1. Rewrite and specify briefly what's meant under a topic.
2. Rewrite and give short examples or specify what's the activity feed useful for and what sort if activities will the person see. 
3. Consider renaming "Global activity" button if it doesn't automatically pull in all notifications from the entire platform.
4. Can be ignored or rephrased a bit. Consider giving some context to the functions of topics – what are they there for. How are they relevant for the user?
5. Make the right part more visible by design (wobble, glow, etc).

@ssin1901 @ilmartyrk @BeccaMelhuish – tagging as I'm not 100% sure who to notify about this testing experience :)

OTHERWISE, all functionalities worked. I used Google Chrome.

**Comment by BeccaMelhuish** [comment]
This is all very helpful thanks @MeelikaH! I am working on the tours texts in relation to the things raised here, so will take all this into account as I edit them (and then @kevincrepin will share proposals with you once ready). 

Have also made a [separate issue](https://github.com/citizenos/citizenos-fe/issues/488) to discuss the 'global activity' button separately to the tour (as it's a thing in itself). Though one thing that does relate to the tour specifically - did you see the 'global activity' as being something related to the 'search' when you took the tour (as they are two separate things (search and activity feed, they just are next to each other)), as you talk about them interchangeably?

**Comment by BeccaMelhuish** [comment]
Also @kevincrepin do you have any thoughts re @MeelikaH's point 5? 
I'm thinking maybe greying out rather than blurring would make it a lot clearer, but not sure how this will look?  
Wobble animation is a nice idea, but probably more time-consuming to develop @ilmartyrk?

**Comment by kevincrepin** [comment]
Here's the original prototype: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=29-13982&viewport=305%2C-45%2C0.02&t=ODt1nTXQy3gjM7vo-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

Couple differences:

- The background is blurred, but also faded (opacity 50%), I think currently that's not the case
- The element in focus has a (subtle) dropshadow which elevates it more from the base layer
- There's animation so it's easier to follow where the next tooltip in the walkthrough is focusing on. Probably not the easiest to develop but quite crucial I would say.
- One issue right now (I think I mentioned this in my feedback doc also) is that the screen focus aligns the tooltip to the top of the browser window. Ideally there is some upper margin so the tooltip is not "tucked away" so much and to get better context.

I would say if all of the above is done, greying out is not necessary.

**Comment by BeccaMelhuish** [comment]
Ah yes this looks much better to me! Have made a [new issue](https://github.com/citizenos/citizenos-fe/issues/491) for the visual side of things (and will keep this one for copy discussion) so @MeelikaH please check it too and continue any discussion in that one :)

**Comment by BeccaMelhuish** [comment]
OK @MeelikaH @kevincrepin here is a re-draft of the dashboard tour which I think covers all your points @MeelikaH, and makes it relevant to new and old-new users (as agreed [here](https://github.com/citizenos/citizenos-fe/issues/400)).  

https://docs.google.com/document/d/1SftGkd5BwKwzxuZi8tG1DbJH5vXnPD9IxevlhCjL5eU/edit?usp=sharing
(Kevin you should have access with DUX email) 

Please take a look and let me know what you think. Will do the same for the topic tour hopefully tomorrow :) 
(Meelika your 'fresh eyes' comments on the topic tour very welcome too! So far plan is just to make sure it's relevant to both admin/editor and participant view again as agreed [here]((https://github.com/citizenos/citizenos-fe/issues/400)). 

@anettlinno @ilmartyrk again am adding 'high priority' tag as keen to test the tour in user test / pre-testing calls very soon!

**Comment by BeccaMelhuish** [comment]
@MeelikaH @kevincrepin I have also re-drafted the tour one, if you wanted to see what you think of that too :)

https://docs.google.com/document/d/1qWmbpG3GX8u8jPxfVyOb8xY3mk4kGVxVgNhX2VsXvoE/edit?usp=sharing

**Comment by ilmartyrk** [comment]
@BeccaMelhuish Fixed the tour behavior, copy changes will be made later, focusing on coding for now

**Comment by BeccaMelhuish** [comment]
@kevincrepin, Meelika has gone through and given feedback now and have made some more tweaks - am wondering what you think of these texts now, if they are OK to go? (Am hoping to get them edited tomorrow before some possible calls with users this week). Some changes are just minor, but some are quite big, and have made sections of the tour much bigger than they were previously - like the 'Create actions' for example. It all feels necessary to explain, as per Meelika's initial feedback above, but also makes it quite heavy. 

**Dashboard tour**
https://docs.google.com/document/d/1SftGkd5BwKwzxuZi8tG1DbJH5vXnPD9IxevlhCjL5eU/edit?usp=sharing

**Topic tour**
https://docs.google.com/document/d/1qWmbpG3GX8u8jPxfVyOb8xY3mk4kGVxVgNhX2VsXvoE/edit?usp=sharing

And as per [this issue](https://github.com/citizenos/citizenos-fe/issues/514), am wondering if we don't add the visualisations of the topic phases here?

**Comment by anettlinno** [comment]
As tour´s visual is in accordance to the design (issue #491) then I´d remove the "high-priority" label, as I don ´t see that changing the copy is high-priority in the list of all the thigs we need to implement before user tests :)

**Comment by BeccaMelhuish** [comment]
@anettlinno I'll be testing the tour on Thursday midday (Estonian time) with the first user, so the copy would need to be correct by then (currently it isn't saying the right things), or there wouldn't be much point in testing it.. It's not the functionality of the tour I'll be testing, but its content and what this leads users to understand/misunderstand :)

**Comment by BeccaMelhuish** [comment]
And just to clarify, what's changed in the re-draft tour texts compared to the Figma designs and why: 

- Making the tours speak to both new and returning users at the same time (as we agreed they won't get different tours)
- Making the tours speak to participants and admins at the same time (as we agreed they won't get different tours)
- Making sure they only talk about Phase I features, currently the tours talk about some Phase II features that don't yet exist
- Taking into account some of the feedback Meelika gave looking at it with 'fresh eyes' - especially re clarifying the different topic types, phases etc.

**Comment by BeccaMelhuish** [comment]
Just an update on this, what I've done is edited the texts based on what I can see is 100% necessary (either already agreed or not really in need of any debate). e.g.:  

- Making the tours speak to both new and returning users at the same time (as we agreed they won't get different tours)
- Making the tours speak to participants and admins at the same time (as we agreed they won't get different tours)
- Making sure they only talk about Phase I features, currently the tours talk about some Phase II features that don't yet exist
(Though @ilmartyrk as per my Slack message I need your help in making the edits I made actually show up in the strings before Wednesday - somehow they've been reversed). 

But these changes I have left for now (though personally I do agree with Meelika that they're likely necessary), and we can discuss it further depending on how the user research goes:

- Taking into account some of the feedback Meelika gave looking at it with 'fresh eyes' - especially re clarifying the different topic types, phases etc.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish is it fixed now?

**Comment by ssin1901** [comment]
Hey @BeccaMelhuish tour looks okay to me for this phase. Can I close the issue?

**Comment by BeccaMelhuish** [comment]
Yes will close it now :)
