### ISSUE TITLE
Test C888: Blank screen after logging in on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#359]
On mobile, android, chrome, after logging in I got a blank screen, see below. 

It went like this: 

- Typed in URL, it loaded fine
- Clicked log in
- Logged in with Google
- Accepted "we've changed T&Cs" box
- Got a blank screen: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fa28a09e-0eba-4152-a1ba-1958543b07b4)

Was able to continue with the test (ID C888) as clicking the + (create) button still worked, just on top of a blank background: 
 
![Screenshot_20231117-093818_Chrome](https://github.com/citizenos/citizenos-fe/assets/61320526/1b887d90-7bc2-4b90-a959-cdc7d4762df7)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk It just happened to me on laptop, windows, Chrome, too:
(After logging in with Gmail for the first time with a new email then accepting the T&Cs pop-up window) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/48e90210-2ec1-4580-8d2c-b480f09b2e48)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I am already fixing this issue and some other related issues where users might end up on blank page

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should be fixed now

**Comment by BeccaMelhuish** [comment]
Great yes much better! 

Though in [this](https://github.com/citizenos/citizenos-fe/issues/175) crossover topic it was decided to remove the "select to add" as well, plus I'm now wondering what the little 'document' icon is doing next to the name - was that in the design? Seems out of place to me. 

And just noticed we have the word "group" where it should say "topic" :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/00265ab6-62b5-47d3-a74a-54da744a3efb)
