### ISSUE TITLE
Error message the first time the user access redesign.app.citizenos.com

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#360]
**What is the problem?**
The first time a user accesses redesign.app.citizenos.com they receive an error message (see screenshot). This issue occurred on Mac OS Safari 17.1.

<img width="1439" alt="Screenshot 2023-11-17 at 11 31 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/696cad6b-5de5-4291-ab17-d24a6f174c54">

**Why is this a problem?**
Confuses the error message

**Possible solution.**
Error message should be removed

**Comment by ilmartyrk** [comment]
@ssin1901 I couldn't get that error, and it probably was related to deleting data from our test database. I think you might have had a logged in user at the time and as database was wiped clean it couldn't get any data with your logged in credentials
