### ISSUE TITLE
Test C888: Pre-publishing page seems published, and lands already scrolled part-way down

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#366]
On mobile, android, chrome, when clicking continue and the topic was published (actually not yet published, but seemed so to me, see below), the screen landed already scrolled down on the "What's next" box, rather than at the top of the screen as it presumably should? It felt very disorientating to have it land part-way down. 

Also, I realise now that the topic _wasn't_ published, I just assumed it was. But actually from my knowledge of the design I remember I still have to click one more step to actually publish it. On mobile this is just a blue arrow to the right, so not clear at all. I think a lot of people will think their topic is published at that stage. So this is a UX design issue too. 

This is how it landed (already scrolled): 

![Screenshot_20231117-100245_Chrome](https://github.com/citizenos/citizenos-fe/assets/61320526/5793bf02-2123-41d9-8974-81d2a4462f7a)

**Comment by kevincrepin** [comment]
The scrolling should be fixed, but very good point about the last step and the CTA to publish being only an arrow. That is indeed not very clear.

Of course we are – as always – limited in space so in English the label just fits, but doubts about other languages. So there's also the option that we bring out the publish button more prominently in the last step:
https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=9715%3A89809&mode=design&t=PhFtA9pToszSoRt5-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ooh yes this looks good :) 

Especially the bigger version across the full width of the screen, makes it really clear as soon as you land on the page that you're viewing a preview not the final thing. 

Would be great to have the tab headings too in English at least, but will carry on that conversation in the other issue :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Actually it just caught me out on desktop too, for a few seconds I felt like I was seeing the published version rather than a preview, until I remembered this issue. 

Wondering if the button should say "Publish" rather than "Save changes" (as Save seems like saving a draft), and be a bit bigger or somehow clearer with a message at the top pointing out it's a preview (editing the existing one a bit? Making it more eye-catching with colour maybe?), or having it all slightly greyed out or something?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fbfc8923-8a6f-4bc8-a43b-d5e7e2284ac4)

**Comment by BeccaMelhuish** [comment]
And actually, am thinking now that we have drafts this would be a good place for a "Save changes" button, but as well as a "Publish" one? Otherwise you'd get a bit stuck at this point if you did want to save a draft and wait for co-creators to collaborate before publishing (which I guess would be quite common), and not know how to do so. (I know we discussed this being something to test, but I feel like it has potential for causing enough confusion it'd be worth adding in already?)

**Comment by kevincrepin** [comment]
Regular flow should have publish, like in design: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=232-34602&viewport=-4156%2C-9328%2C0.5&t=gFoc9DWn68bC4dVT-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

Editing should have "Save changes": https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=482-62559&viewport=-4156%2C-9328%2C0.5&t=gFoc9DWn68bC4dVT-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design


But we can add "save as draft" quite easily I think:

Desktop: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=9877-64123&viewport=-3088%2C-6361%2C0.25&t=e8ehus9TkSVnhhTI-1&scaling=scale-down&starting-point-node-id=2804%3A112414&show-proto-sidebar=1&mode=design

Mobile: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=9877-64906&viewport=-3088%2C-6361%2C0.25&t=e8ehus9TkSVnhhTI-1&scaling=scale-down&starting-point-node-id=2804%3A112414&show-proto-sidebar=1&mode=design

**Comment by BeccaMelhuish** [comment]
OK great thanks Kevin!

So that's something for @ilmartyrk to fix regardless (it currently says save where should say publish, as above), but also something to add in if @anettlinno agrees? (The 'Save as draft' button - makes a lot of sense to me!)

**Comment by BeccaMelhuish** [comment]
Also, there's currently quite a difference in what the preview page looks like to me currently versus the design: 

Currently for me, big empty space under topic text: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5d2fe064-5f7e-4b30-88f7-4fbbc50f5f58)

Design: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5db084a1-fbe1-47b7-b194-870cbc6e4e54)

But maybe this is just a bug @ilmartyrk and I should make a separate issue?

**Comment by BeccaMelhuish** [comment]
I will also have a think if I can make any of the texts on this page help with making it clearer it's a preview, it's on the to-do list and will come back with suggestions soon!

**Comment by kevincrepin** [comment]
@BeccaMelhuish Maybe here we can start the sentence "**You're watching a preview of your topic.** You can still edit..." etc?

![Screenshot 2023-11-24 at 14 00 11](https://github.com/citizenos/citizenos-fe/assets/26792281/fe4a0779-ff00-4a27-8605-236c4a7db562)

**Comment by BeccaMelhuish** [comment]
Great yes something like that will help! :)

**Comment by anettlinno** [comment]
Adding "Save as draft" next to "Publish my topic" (I would remove "now" as unnecessary) makes sense and easy to understand that draft document can be saved for later as well. So, please let´s implement this in Phase I, @ilmartyrk (Y)

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/62c5257d-cb1f-49c4-87c8-f45a31035cfa)

Regarding the notification text "**You are watching a preview topic** and can still edit your topic text now or later (but not after voting has started) -- would it be possible to add the text in the brackets: _(but not after voting has started)_ only to voting topics? Otherwise it is confusing, if I have started discussion or ideation and do not plan to send it to voting...

**Comment by BeccaMelhuish** [comment]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dd895d40-6437-4229-bb29-b3516c1a3398)

I have changed this bit in the code to the wording below. Some related Qs:
- It's a bit long now, but I think OK? 
- @anettlinno I think this text solves the problem you raised (as it's more an 'if you start a vote' rather than 'when you start a vote' - which is possible in all topics)? 
- @kevincrepin I'm wondering if we could make this blue bar more visible, with orange perhaps - wdyt?
- @ilmartyrk could you make the first bit bold as below - don't think I can do that from the translation strings?   

"**This is a preview of your topic!** You can still edit your topic now or later (though if you start a vote, the topic description gets locked)."

@kevincrepin on this bit screenshot below, a few Qs too: 
- Currently (in test) we only have it when the page is published but not in the preview, but we should add it into preview as well right? But with the 'Add argument' greyed out as it's not possible to add before publishing? 
- I'm wondering if there should be a message if someone clicks on the greyed out button that says 'Publish the topic to add the first argument!'. 
- Also wondering what happens to this bit when it is published, but someone is just going back in to edit the topic, once the discussion has already started. Should it show the actual active discussion there, or what should fill that space? (If anything, I guess it can just be empty) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ab1267aa-9829-40e6-801a-091f1b7b7831)

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk added high priority tab as feels an important one to fix before testing

**Comment by kevincrepin** [comment]
We can make it more visible by using the warning style, sure:
https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=232-34602&viewport=-1336%2C-47828%2C1&t=0gYdGEycKdxGoI6s-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

And yes, in preview the discussion section would already be visible with a disabled button – visible in link above as well When editing the topic I would not include the discussion at all here? Just to keep it focused on the topic text.

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK great, looks/sounds good! 

Is this new text too long though, or will be OK? 
"**This is a preview of your topic!** You can still edit your topic now or later (though if you start a vote, the topic description gets locked)."

**Comment by kevincrepin** [comment]
Could it be simpler to say "This is a preview of your topic! You can still edit your topic at any point during the discussion phase."? Because I guess if you start follow-up, then it's also locked, right?

**Comment by BeccaMelhuish** [comment]
Ah yes, this is good - thank you! 
Have changed it in the strings.

**Comment by BeccaMelhuish** [comment]
So to summarise, tasks for @ilmartyrk from this would be:

- [x] Switch to the warning style for the 'This is a preview' text: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=232-34602&viewport=-1336%2C-47828%2C1&t=0gYdGEycKdxGoI6s-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

- [x] Add this box to the pre-publishing preview with the add argument button greyed out: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6c4e9d6f-5f69-4417-b849-47df6dd30202)

- [ ] For the preview for 'Edit topic' (rather than 'Create topic'), don't include the discussion in the preview: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/20763840-a0ba-4f89-a981-a0b61f5cb329)

**Comment by anettlinno** [comment]
Triage 95. Sending To Do.
