### ISSUE TITLE
Moderation: Can't invite a user to a topic

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#367]
**What is the problem?**
I'm trying to invite an existing user to a topic I've just created, in some occasions I can't even click on her name to add here (nothing happens), in some others it seems I can select and invite her (or at least the window disappears once I click on Send Invites), but there's no confirmation, that she was invited, nor can I find her in the "Invited users" view after inviting.

https://github.com/citizenos/citizenos-fe/assets/34126353/c814e7d3-43c6-4200-8bc8-feaf1ae09ac0

And she doesn't show up under invited:
<img width="587" alt="Screenshot 2023-11-17 at 12 07 27" src="https://github.com/citizenos/citizenos-fe/assets/34126353/e7b509a3-66ea-4fa7-a55f-efa97aa92faf">

**Comment by oksks** [comment]
Note to self: retest [this flow](https://costest1234.testrail.io/index.php?/cases/view/918&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=51) after bug has been fixed. 
@ilmartyrk pls assign to me when resolved 🙏

**Comment by ilmartyrk** [comment]
@oksks fixed
