### ISSUE TITLE
TOPIC: Double pop-ups on mobile when publishing topics - confusing/messy

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#368]
On mobile, android, chrome, when publishing the topic, there are two pop-ups overlaid over each other which makes it hard to read and confusing and rather messy looking too: 

![Screenshot_20231117-101028_Chrome](https://github.com/citizenos/citizenos-fe/assets/61320526/a64f8a75-d6b3-4276-a5b6-daf905be8bd5)

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish only solution for that is if we remove the invite dialog or add the notification after closing the invite

**Comment by kevincrepin** [comment]
@ilmartyrk it's not possible to have the invite popup be under the success notification, like in design? https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=42%3A11279&type=design&node-id=415-55918&viewport=-2733%2C-23228%2C1&t=R3qA3ZqttpN3Ys7j-1&scaling=scale-down&starting-point-node-id=47%3A8891&mode=design

**Comment by ilmartyrk** [comment]
@kevincrepin good point , I'll have a lot changes to make as I'll probably have to swap out the popup library, but I guess in a long term it will make things easier and better looking

**Comment by anettlinno** [comment]
Popups needs some rethinking. Pushing it to Phase II.

**Comment by ilmartyrk** [comment]
Fixed

**Comment by ssin1901** [comment]
Looks alright and moving to done

![IMG_0138](https://github.com/user-attachments/assets/6e3fd5e4-0061-4c43-9737-c3d850a497b3)
