### ISSUE TITLE
LOGIN: Password reset did not work for Ozzie account 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#370]
**What is the problem?**
When trying to reset password with the Ozzie account (see screenshot), the password reset email never came. However, it worked with Sara account.

<img width="1438" alt="Screenshot 2023-11-17 at 11 05 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/896c9151-4147-4d8f-bc7c-c4593a220947">

**Why is this a problem?**
New users will encounter issues with password reset

**Possible solution.**
Password reset notifications should work for all users

**Comment by ilmartyrk** [comment]
@ssin1901 do we have an actual account with ozzie e-mail?

**Comment by anettlinno** [comment]
Password reset works now. Closing this issue.
