### ISSUE TITLE
Public topics page, public groups page, my topics, my groups missing pagination

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#378]
@kevincrepin by default we currently load 10 items per page, how should loading more be solved, I couldn't find any pagination or load more button in designs. I would rather use one of these two rather than load on scroll

**Comment by kevincrepin** [comment]
@ilmartyrk Added pagination to the relevant screens. Since we also use pagination  in the arguments and some lists let's reuse that logic.

**Comment by ilmartyrk** [comment]
@kevincrepin thanks.
