### ISSUE TITLE
Onboarding: broken design (3)

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe#381]
**What is the problem?**
In the "Take the tour" and "Topics" page I see a weird "Format" drop-bar menu that interrupts the design. I see it on other pages as well.
![Screenshot 2023-11-17 at 12 57 26](https://github.com/citizenos/citizenos-fe/assets/126671955/920c6b55-1a8b-4605-a266-a5598f8505a7)
![Screenshot 2023-11-17 at 12 58 14](https://github.com/citizenos/citizenos-fe/assets/126671955/2fef4a12-8c03-482b-960d-b062d45400b8)

**Why is this a problem?**
The pages look broken. It is confusing for users. What is it? Why do they see it?

**Possible solution.**
Needs a fix and to be tested on other browsers if the case appears there as well. I used Google Chrome.

@ssin1901 @ilmartyrk

**Comment by ilmartyrk** [comment]
@MeelikaH I could not reproduce this, also this dropdown is not related to our app, it might be your browser plugin
