### ISSUE TITLE
Profile: Profile photo positioning (UX) & former notifications 

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe#382]
**What is the problem?**
1. When uploading a profile photo, it's not possible to change positioning.
![Screenshot 2023-11-17 at 13 21 46](https://github.com/citizenos/citizenos-fe/assets/126671955/8993ad47-299e-4bd6-94e7-178ef1df98c9)
2. Former profile notifications don't disappear when you take next actions. 
![Screenshot 2023-11-17 at 13 21 46](https://github.com/citizenos/citizenos-fe/assets/126671955/35b4add7-62b0-49c3-9aec-8d75d154d4b5)
3. Format view is also visible on profile page.

**Why is this a problem?**
1. The user will have to find a perfectly scaled photo which would not cut off part of the face or change the size. This is not user-friendly.
2. It feels messy with 2 x Success and text "Info! Your email address has been updated..."
3. Displaying format view gives a broken page feel.

**Possible solution.**
1. Add the function to re-position the photo or crop within the tool (e.g Wordpress).
2. Ensure that once the user takes next steps, the former pop-up notifications disappear.
3. Ensure that the format view is not breaking the design (or have it removed from the user view).

Tested on Google Chrome.
@ilmartyrk @ssin1901

**Comment by ilmartyrk** [comment]
@MeelikaH @ssin1901 this will need a little bit more work, but can be achieved, I'll alter the image resizing/cropping code that I added, probably will be done tomorrow

**Comment by ilmartyrk** [comment]
@MeelikaH @ssin1901 added image positioning and scaling (this will work with mouse scroll). Moving is not very smooth, probably needs more time to get it working properly, but hopefully it is good enough for now. Also added same functionalities to group images
