### ISSUE TITLE
Profile: Profile photo change (bigger files) doesn't work, not all photo files supported

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe#383]
**What is the problem?**
1. Trying to upload a bigger resolution photo doesn't work.
2. Not all photo file types (even tho common) don't work.
![Screenshot 2023-11-17 at 13 32 35](https://github.com/citizenos/citizenos-fe/assets/126671955/3ef0be04-28ee-471b-85e4-85076f36da42)

**Why is this a problem?**
1. It would be good to allow bigger resolution photos to be uploaded or communicate the maximum size allowed. If the size is bigger and the person doesn't know how to reduce the size of their photo, it would be useful that the platform automatically reduces the size (similar to Wordpress).
2. HEIC as a very common file might be also supported. Consider other photo files.

**Possible solution.**
1. Allow bigger photo files, resize automatically and communicate clearly the file types and max size allowed.

Tested with Google Chrome.
@ilmartyrk @ssin1901

**Comment by ilmartyrk** [comment]
@MeelikaH  @ssin1901 I've added image resizing to profile image, so on uploading an image it will be cropped and resized to 320*320
