### ISSUE TITLE
EMAIL: Dodgy looking email header

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#385]
Dodgy looking email header here (via @MeelikaH), header with logo needs fixing of course, but also headings on all emails should be aligned with the rest of the text :)   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7395faac-0a3c-49c7-bb1b-89f0d67f4bc7)
 
The designs had these icons, but now they've been dropped all headings should be aligned as per the red line above :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/43e6659c-2091-4838-ab0d-8d6823f39928)

**Comment by anettlinno** [comment]
I think this is fixed now: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/470f5031-54a4-4c1c-8f3c-02dca05d78e2)

@ilmartyrk how is it with adding the icons?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno I understood from @kevincrepin to not have any of these icons anymore

**Comment by kevincrepin** [comment]
IIIRC @anettlinno didn't like those icons :) and since then I didn't manage to make new ones anymore so seemed more efficient to remove them.

If I remember this incorrectly, please tell me @anettlinno !

**Comment by anettlinno** [comment]
Yes, @kevincrepin ! That might have had the thing :D Sorry for my short memory -- I just checked the designs and saw them there (and I still prefer emails without icons) 😁

OK, closing the issue as email header is aligned correctly  now.
