### ISSUE TITLE
Platform not fitting browser window

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#386]
On laptop, Windows, Firefox, the platform stretches beyond the edge of the browser window, so you have to scroll right to see the rest of it: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3647c056-8499-47d8-ad1f-ca485d6ab46f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I encountered same issue, it should be now fixed on Firefox
