### ISSUE TITLE
Authenticate with Smart ID not working

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#387]
**What is the problem?**
When a user enters correct personal code and clicks Authenticate with Smart ID (see screenshot) nothing happens.

<img width="1338" alt="Screenshot 2023-11-17 at 14 24 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ad592dca-89b5-4b03-be53-20ec46a0c7ae">

**Why is this a problem?**
User cannot login with Smart ID

**Possible solution.**
User should be able to login with Smart ID

**Comment by ilmartyrk** [comment]
Test Smart-ID-s are working
