### ISSUE TITLE
Mobile ID with no active certificates should show an error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#388]
**What is the problem?**
When a user enters a mobile number and ID combination with no active certificates(see screenshot), the control code appears and then the user is directed back to login (see screenshot) without an error message

<img width="695" alt="Screenshot 2023-11-17 at 14 34 01" src="https://github.com/citizenos/citizenos-fe/assets/72747107/89d5aad2-eb0b-41a3-9e37-b86173d626d3">

<img width="1413" alt="Screenshot 2023-11-17 at 14 31 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/469a3363-0fa8-4128-9e98-992e3f736fb0">

**Why is this a problem?**
Without an error message, user cannot understand or fix the problem

**Possible solution.**
User should at least an error message that the mobile ID and number combination could not be recognised but he system.

**Comment by ilmartyrk** [comment]
@ssin1901 fixed
