### ISSUE TITLE
Pictures are not seen in voting creation preview

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#390]
**What is the problem?**
I added a picture in voting topic and it is not visible in preview:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/7a108a9e-f42c-44d8-a139-c47f3cf41c4a)

**Why is this a problem?**
User canned see added picture under the preview, before creating a voting.

**Possible solution.**
Please add picture preview.

**Comment by anettlinno** [comment]
Same happens after publishing voting:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/a383aed9-3a58-4ecf-8d6b-783358d2f00b)

**Comment by ilmartyrk** [comment]
@anettlinno I had forgotten to add image property to topics on our API side, it has now been updated and should work as intended

**Comment by anettlinno** [comment]
Tested @ilmartyrk And now it works.
Closing this issue.
