### ISSUE TITLE
TOPIC: Adding attachement text (or box) should be responsive

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#391]
**What is the user story?**
User can currently add attachments only by clicking on the three dots on the right side of the Attachments tab. From the UX perspective the whole box should be responsive as the three dots are not clearly seen and easily findable:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/610e036a-de18-4c51-af1c-31dbc4d1232a)

**Which feature needs to be updated and how?**
Make the Attachments box responsive for better UX.

**Additional information.**
N/A

**Comment by anettlinno** [comment]
After clicking on the Attachment box, User should see the pop-up window (or any other solution) with opportunities to attach documents:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/c226ba52-f857-4d58-abd4-8846999a1124)

**Comment by ilmartyrk** [comment]
@anettlinno probably needs @kevincrepin input

**Comment by anettlinno** [comment]
@kevincrepin any good thoughts how to solve this? :)

**Comment by kevincrepin** [comment]
Actually wasn't supposed to be like this ;) 
![Screenshot 2024-01-21 at 15 16 32](https://github.com/citizenos/citizenos-fe/assets/26792281/838d5de8-f8b1-447e-ad4d-ab0a1edb14f2)

But I think with the time constraints and other, more important, issues to solve, my suggestion would be:

- Let's have "Add" button next to attachments label
- Same menu as now
![Screenshot 2024-01-21 at 15 30 49](https://github.com/citizenos/citizenos-fe/assets/26792281/5f063a08-fdf4-4c80-8f92-8882e333dee1)

PS @ilmartyrk : I added these icons to the components also.
File can be found: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11457%3A77740&mode=design&t=cdGvUcp5EzmNWfSd-1

**Comment by ilmartyrk** [comment]
updated the views

**Comment by anettlinno** [comment]
Tested and works nicely now. Closing the issue.
