### ISSUE TITLE
SSL certificate not showing on iPad/site not secure icon 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#393]
**What is the problem?**
On Safari 17.1 in Ipad OS 17.1 the secure lock is missing (see screenshot). Test was run in incognito mode so not cookies issues.

![Screenshot 2023-11-17 at 15 19 41](https://github.com/citizenos/citizenos-fe/assets/72747107/18addc09-2147-4464-9c9f-41481eb86147)

**Why is this a problem?**
Site not secure

**Possible solution.**
SSL should be be properly installed and configured.

**Comment by ilmartyrk** [comment]
please add https:// manually before url in testing environment, at least for now

**Comment by ssin1901** [comment]
@ilmartyrk thanks. It worked now in iPad after adding s manually.
