### ISSUE TITLE
Error message when adding attachment from Google Drive

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#395]
**What is the problem?**
Adding files from Google Drive (after added files from DropBox) gives me error message and I´m unable to add attachments from Google Drive

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/f557a8e7-c6b3-4594-b556-8db6d860cf0c)

**Why is this a problem?**
Unable to add attachments from Google Drive

**Possible solution.**
Please fix it.

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish @ssin1901 fixed

**Comment by anettlinno** [comment]
Tested. Closing the issue as this works nicely.
