### ISSUE TITLE
Unable to continue creating voting topic after saving it for later

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#396]
**What is the user story?**
As a User
- I wanted to create a voting topic and chose Add voting topic
- I filled Title and Intro parts and left it for continuing later
- I clicked on the Dashboard
- Later I opened topic under "My topics" to continue editing the voting topic
- I clicked on three dots to Edit topic

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/9f924839-dec7-4f59-a55a-ff01c9c3c5ea)

- AND the voting topic has turned into discussion topic, as there are no voting creation options any longer

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/a2cf5cdd-e3ab-413c-a37d-583f0b846d05)

**Which feature needs to be updated and how?**

If User creates voting topic, it should remain voting topic throughout its lifetime. 
- User should be able to continue creating voting topic after one has interrupted topic creation and saved it for later
- Voting topics that are started (only topic part is created or under the creation) and saved for later (voting is not set up yet) should be visible in "In voting" under "My topics" menu
- In "My topics" they should be waring green color-code since the beginning. Currently these voting topics which are saved for later are in blue:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/775df540-d2fc-4d2b-b026-65d39499a201)

**Additional information.**
Let´s make it user friendly, @kevincrepin  :)

**Comment by ilmartyrk** [comment]
@anettlinno it is because of our current system, we don't have drafts yet so every topic initially is discussion topic. If you choose to create a voting topic our current platform generates a discussion topic, you fill out all the fields for the topic, then setup the voting options etc. and after publishing it creates the vote and sends topic status to voting. If you cancel during the creating process we will only have discussion topic info in our database, that is why currently you can only access edit discussion topic. 

I have some ideas that might work, but not sure how long the implementations will take time, also I guess we will have to add drafting system before launch then.

**Comment by anettlinno** [comment]
Thanks for the answer @ilmartyrk 

From User perspective, current flow does not make sense, so I very much recommend us to add the drafting system before the launch. We probably need some revisions in the foldering system where user can also see the drafts. I don´t see it in our current Figma files, but maybe I just don´t find the place. @kevincrepin your help is very much appreciated here. 

@ilmartyrk could you please try to estimate how much time it would take (I know you said "_not sure how long the implementations will take time_", but please try to guess? :))

**Comment by kevincrepin** [comment]
We had in the filter "My engagement" an item called "My topics in draft", but now thinking maybe it make mores sense under  "Current status"?

And we could also indicate the topic accordingly.

![Screenshot 2023-11-22 at 11 03 26](https://github.com/citizenos/citizenos-fe/assets/26792281/9ab303f6-d057-4f22-86c8-9119d1efab94)

**Comment by anettlinno** [comment]
Ahh, OK, @kevincrepin ! Thanks, let´s leave it then in the filter for now :)

**Comment by anettlinno** [comment]
Triage 95. In progress.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk for testing prep, am I right in thinking drafts are done now?

**Comment by anettlinno** [comment]
@BeccaMelhuish this issue is in progress: https://github.com/orgs/citizenos/projects/5/views/1
