### ISSUE TITLE
Tooltip on registration about our non-profit status

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#397]
As per the [Slack conversation](https://citizen-os.slack.com/archives/C02M6JLEGP3/p1700225720334729), I'm switching this text to: 
"Free for everybody and for always! No ads, no sale of data, no hidden costs"

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/757bb2ee-6d6c-4bdb-a668-6717d1127681)

And next to it (at the end of the sentence) would like one of the tooltips that Kevin designed (see [issue here](https://github.com/citizenos/citizenos-fe/issues/207) for more info) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fca0b76b-3584-45c8-a906-752a3e6e31c6)

The tooltip text should say:

**Forever free**
Wondering what the catch is? There isn't one! We're a non-profit with a mission to empower as many people as possible to participate in respectful, meaningful discussions on the issues that matter to them. We run off donations and grants from long-term funders – which means no fees, no sale of your data, no strings attached! We're just here to help, for everybody and for always.

--> Read more in the Help Centre 
(I'll provide the link when it's ready) 

@anettlinno @ilmartyrk I feel like this is a good one for the first tooltip, and then from then on (once this one is developed and looking good) it should be easy (I assume) to add in additional ones as and when we find they're necessary (according to UX tests)?

**Comment by anettlinno** [comment]
@BeccaMelhuish good idea, thanks!

I have few suggestions here: 

- Let´s not emphasize the "Free forever" that much. Few times is OK, but now it´s all over. Main features of the platform will be free forever, but one day we might start providing subscriptions for fee...
- I suggest to leave out the last sentence: "_We're just here to help, for everybody and for always_" (we cannot help everybody and for always, it sounds like a cliché :) ) and replace it with something like: "We want to make collective decision-making accessible to everyone with no barriers" (what you suggested in Slack). Let´s promise what we are able to deliver :)
- I would rather guide people to our product page and not to HC. OR if we have FAQ, then maybe there, but if it´s also on the product page, then this would be enough. HC is for people who look for help when using the platform. Product page is explaining what the platform is about and these Users who need more information will get it rather from web, than from HC

**Comment by BeccaMelhuish** [comment]
@anettlinno super, thank you for the feedback! 

So for the first text I could switch it to this then? 
_"Create your free account today! No ads, no sale of data, no hidden costs"_

For the longer text, I think we could just leave it like this, with the last sentence removed? As the bit about making collective decision-making accessible with no barriers is somewhat covered in the third sentence? :)  
_"Wondering what the catch is? There isn't one! We're a non-profit with a mission to empower as many people as possible to participate in respectful, meaningful discussions on the issues that matter to them. We run off donations and grants from long-term funders – which means no fees, no sale of your data, no strings attached!"_ 

For the HC link, I was thinking it could go to a [text like this](https://citizenos.com/help/general/your-data-security/), as I think the main concern at this point is "are they selling my data"? I feel like sending them to the product page is a bit too general (as it's not more information about this particular issue, just more information about the features, at the moment). Sending them to the [About page](https://citizenos.com/about-us/) could work nicely though, if not keen on the HC :)

**Comment by anettlinno** [comment]
Thanks @BeccaMelhuish ! Now the text looks good! :)
Re guiding people to our product page -- I was thinking our revamped page :)

**Comment by BeccaMelhuish** [comment]
@anettlinno ah, yes maybe if we had an FAQ on our new Platform page that related to this, then we can link directly to it :) 
Shall we link to the About page for now, and then switch it once we have Platform page ready?

**Comment by anettlinno** [comment]
@BeccaMelhuish yes, let´s do that :)

**Comment by BeccaMelhuish** [comment]
@anettlinno OK great! 

I have changed the "forever free" text in the translation strings as agreed, so the task for @ilmartyrk from this then would be: 

- Add the tooltip icon at the end of the sentence "Create your free account today! No ads, no sale of data, no hidden costs"

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/996ebba2-5a82-4fbf-a8c2-27fbfde22820)


- Make the tooltip pop-up as per [Kevin's design](https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=7017%3A65745&mode=design&t=qWRYXOj6fiKZwaEM-1) (screenshot below)
- With the text:
"Wondering what the catch is? There isn't one! We're a non-profit with a mission to empower as many people as possible to participate in respectful, meaningful discussions on the issues that matter to them. We run off donations and grants from long-term funders – which means no fees, no sale of your data, no strings attached!
--> Read more on our About page (_link to: https://citizenos.com/about-us/_)"
  
(This will bring me a disproportionate amount of joy @anettlinno, our first of such buttons 😍😂)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/32f19757-50df-4a4a-8025-7086d9afba3b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the tooltip

**Comment by anettlinno** [comment]
Cannot see it, @ilmartyrk :) 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/6e9aaf62-2e54-4f76-aaf1-c4e7d144fad5)

**Comment by ilmartyrk** [comment]
@anettlinno this image from voting was an example from designs, check the register form for the tooltip ;)

**Comment by anettlinno** [comment]
Ahh, yes! Now it´s there! Thanks @ilmartyrk !
Closing the issue.

**Comment by BeccaMelhuish** [comment]
Hooray! 

Couple of things from me though:

- Sorry I realise now I forgot to give you the heading! Could it be "Free, really?"
- Could we have a little more gap between the blurb and the "Read more" like in the design? 
- Could we nudge the tooltip icon a little closer to the end of the sentence? 
- @kevincrepin any tips to make it look as good as your design? (I notice the font is a bit smaller and the Read more in bold, but not sure if needs adjusting or it's OK like this?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c284e07b-5089-420c-afec-337a7b9c576b)

Design:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/551c8038-a295-4b2a-9320-c20e8a89f462)
