### ISSUE TITLE
TOUR: Topic tour should be only first time, and for own topics only? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#399]
First part - I assume this might just be for now (so that we can easily see and test the tour), but just flagging in case it's an oversight. Currently the tour pops up every time you go into any topic, but obviously once you've taken the tour once or decided to skip it, it shouldn't appear again.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/77b423aa-495c-4369-98fb-2b1b7e6d5e56)

Second part - the topic tour is also written as if the topic is your own topic "Welcome to your topic". It currently pops up in whatever topic you go into (not necessarily your own). Wondering if @kevincrepin intended it to only be a tour of the first topic you create, popping up once you have published it, rather than for any topic you go into first? I believe so as the copy suggests that - it talks about inviting people, editing the topic etc, which you can only do when you're an admin/editor. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c498573d-9be7-4cbd-b73e-52775d9072a7)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I haven't currently set up the saving part for skipping tours because as we are in the testing process it is better for everyone to see the tours without deleting cookies or making changes in the database. I'll leave this issue open and close it after our testing period after I've added the storing system for users who have seen the tour(s) or decide to skip them

**Comment by BeccaMelhuish** [comment]
Makes sense! 
Good to leave it open too for @kevincrepin's thoughts on whether the tours were intended for the first time you go into any kind of topic or only for the first time you create one yourself :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think this is fixed now with our minimizing solution

**Comment by ssin1901** [comment]
@BeccaMelhuish can we close this issue? Topic minimises automatically after a few seconds, and is minimised after completing the tour, and once the user has clicked skip.
