### ISSUE TITLE
Empty grey screen every time after hitting "refresh"

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#403]
**What is the problem?**
I'm getting an empty grey screen every time I hit refresh. Mac, Chrome.

https://github.com/citizenos/citizenos-fe/assets/34126353/f3aebba0-6dd9-4964-ae5e-22dcd6541ddb

**Comment by ilmartyrk** [comment]
@oksks I made some changes that possibly fixed this issue, can you confirm that it is now working for you?

**Comment by oksks** [comment]
Awesome! Tested, seems to be fixed, thank you 🙏
