### ISSUE TITLE
Error message when creating voting topic

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#404]
**What is the problem?**
Getting error message while creating a voting topic, but still can create it. 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/85744f9d-fbea-4292-a5de-e5b7fb1f1c14)

**Why is this a problem?**
Confusing for user -- why do I get this error message if I can do everything.

**Possible solution.**
Please fix.

**Comment by ilmartyrk** [comment]
@anettlinno at what point did you get this message, were you running a test from our test suite, need more context

**Comment by anettlinno** [comment]
I run test in our test environment, yes, @ilmartyrk 
Error appeared after adding Header picture. I tried adding different sizes of pictures and the error message appears with big size pictures -- 6.29 MB and not with smaller ones (109 KB and 165 KB). @ilmartyrk max size is 5 MB? Anyway if the size limit is exceeded then the platform should send message about that. OR there should be text somewhere about which formats and sizes are allowed. 

How to solve it @kevincrepin ? :)

**Comment by ilmartyrk** [comment]
@anettlinno @kevincrepin added some checks to file upload, also changed some error handling code so if server sends back something useful it is not overwritten with generic message. Now if file is too large or not suitable type an inline error is displayed for 5 seconds.

**Comment by anettlinno** [comment]
Tested and received the error message with explanation. Closing the issue.
