### ISSUE TITLE
"Report participant" pop-up items don't make sense together

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#405]
**What is the problem?**
The pop-up is about reporting the participant, but drop-down options seem to be from another menu, they don't fit this action.

![Screenshot 2023-11-20 at 11 15 59](https://github.com/citizenos/citizenos-fe/assets/34126353/46b56412-dd65-4d65-955a-03b715a69ed6)

Bonus bug: "Cancel" should have some padding above.

**Comment by ilmartyrk** [comment]
@oksks changed the heading to "Report argument to admin" as  it is argument reporting dialog. Also Cancel link is the dual visible from under the dropdown so I think it doesn't need any more padding in this context
