### ISSUE TITLE
Error when trying to access public groups when not logged in

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#407]
When clicking "View all public groups" on the logged out dashboard (on laptop, Windows, Firefox), getting this error: 

Though when I went back and tried it again, it then worked fine. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1e110811-312a-4aa5-b781-f1464c5ab170)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I couldn't replicate it, but it might have something to do with updates to the API code at the time you were testing

**Comment by BeccaMelhuish** [comment]
Tried again now and it does work fine :)
