### ISSUE TITLE
Log in after clicking "Create a group" 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#408]
**What is the problem?**
+ add screenshot / screencast whenever possible

**Why is this a problem?**
Describe, how this bug stops a user from performing a desired activity.
This is helpful for prioritizing the bugfix.

**Possible solution.**
A clear and concise description of what you expected to happen (when applicable).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish was this meant to be the same issue https://github.com/citizenos/citizenos-fe/issues/409

**Comment by BeccaMelhuish** [comment]
Ah yes sorry, must have been!
