### ISSUE TITLE
Log in pop-up empty after clicking "Create" buttons

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#409]
When clicking the "Create a group" button on the logged-out dashboard (on laptop, Windows, Firefox), the log-in pop-up doesn't load: 
 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1b888eb7-d05a-4449-94f6-4ba668e25d4f)

**Comment by BeccaMelhuish** [comment]
These buttons aren't working for me either (again, when logged out) - the left hand one does the same as above (opens log-in pop-up but only with heading), and the right-hand one is just a 'dead' button for me - nothing happens when click it: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0581d30f-0ac0-4a53-9ad5-821dab42ff87)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I've fixed the button not working, but I could not replicate the empty login box, can you provide some more info

**Comment by BeccaMelhuish** [comment]
@ilmartyrk are you able to view [this screen recording](https://www.loom.com/share/a90e0b7d05d44155b73ca48ae6066fad?sid=ac347c30-8ce3-4d70-8519-775eda00b5b6)? Should give an idea - it's temperamental :) 
(Let me know if need more explanation of what I was doing in the video though, maybe isn't clear)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I managed to somehow get it too, but it should be fixed now

**Comment by BeccaMelhuish** [comment]
@ilmartyrk, Tried it a few times going back and forth like in the video, and seems to be better now yes :)
