### ISSUE TITLE
Mix up between logged in and logged out welcome message 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#410]
A few seconds earlier, I saw the personal "Welcome back Becca" message when logged in, but now it's showing the logged out message in its place (despite still being logged in): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/15477e7a-e3b7-4567-ae9e-a431d6968466)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is on the home page, personalized message was on the dashboard, will change it on the home view too, to have the same message

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I see that on the dashboard the message is welcome back to your dashboard, would it make more sense to make it just welcome to your dashboard, and also how would the message be for the home page?

**Comment by BeccaMelhuish** [comment]
Ah, though @kevincrepin is there meant to be a home page _and_ a dashboard when you are logged in? I thought the home page was the logged out view, and the dashboard was the logged in view. As they're so similar, rather confusing to have both accessible at once?

**Comment by kevincrepin** [comment]
No, only a dashboard when logged in. Since we can't show a dashboard when not logged in that's why we have that "homepage". That was the idea at least :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK great, so clicking the Citizen OS logo when logged in should take you to your dashboard right? (As well as clicking on Dashboard)

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish, understood will remove access to home page when logged in

**Comment by kevincrepin** [comment]
Yep, exactly right @BeccaMelhuish !
