### ISSUE TITLE
Problems with inviting users - UX and bug

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#411]
Hey @ilmartyrk, [this video](https://www.loom.com/share/2a6fab69e5c54481a481037cac49d12a?sid=7effa869-223a-4c80-b577-256c5ea775b8) shows a couple of problems with inviting users - one UX issue, one bug.
(On laptop, Windows, Chrome)

- You should be able to click anywhere on the line (on the email address or in the space next to it) to add the person, but currently you can only add them by clicking on the "Select to add" bit (bad UX, Kevin has confirmed it should be anywhere on the line). 
- After adding, as you see in the video, the "select to add" dropdown stays stuck there.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Great yes much better! 

Though in [this](https://github.com/citizenos/citizenos-fe/issues/175) crossover topic it was decided to remove the "select to add" as well, plus I'm now wondering what the little 'document' icon is doing next to the name - was that in the design? Seems out of place to me. 

And just noticed we have the words "Invite members to the group" where it should say "Invite people to the topic" :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/00265ab6-62b5-47d3-a74a-54da744a3efb)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed theses new issues too
