### ISSUE TITLE
Unable to choose and submit vote in multiple-selection voting

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#414]
**What is the problem?**
1. Unable to check voting options. When I click on the tick-box, nothing happens
2. "Submit your vote" button is missing

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/ba3e1c8c-18ee-4225-b644-261007b79edb)

**Why is this a problem?**
Unable to vote and submit my vote

**Possible solution.**
Please fix it

**Comment by ilmartyrk** [comment]
@anettlinno I think you might have been in the preview and you cannot submit votes in there as the voting hasn't started, its just a visual preview how it will look like to users

**Comment by anettlinno** [comment]
Tested and could vote in published topic.
