### ISSUE TITLE
Unable to remove picture

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#415]
**What is the problem?**
Unable to remove Header Picture when creating voting topic. 
After clicking on the "Remove" button nothing happened. Then I refreshed the page and Remove button was replaced with "Cancel X" button

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/6d44974b-0f2a-4248-ae83-4411701c145a)

**Why is this a problem?**
Unable to remove Header picture

**Possible solution.**
Please fix it

**Comment by ilmartyrk** [comment]
@anettlinno fixed now

**Comment by anettlinno** [comment]
Tested. Works nicely.
