### ISSUE TITLE
LOGIN: Learn more link in login invite pop-up has black box around it

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#421]
This black box around the learn more link in the pop-up after following the email invite link shouldn't be there: 
(Laptop, Windows, Chrome)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/18951479-7a72-42e7-a1a6-b2b24658e22f)

**Comment by ilmartyrk** [comment]
this was caused by the browser default styles applying the pseudo class called [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) that set black border to buttons and link elements in different views on initial load. Managed to override in main styles file

**Comment by ssin1901** [comment]
Did not find this issue in Google Chrome (see screenshot). 

<img width="1292" alt="Screenshot 2024-02-06 at 14 15 31" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cbfc392b-eebb-4f1c-8962-4af25ffe9fca">
