### ISSUE TITLE
IS: Participants view currently has "Invite & share" button

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#422]
@ilmartyrk @anettlinno @kevincrepin  At the moment the participants view of a topic has this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5231f6bd-af7d-401a-a83d-eabb84b43d29)

When you click on it, it opens this (just sharing, no inviting): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/22195ec2-30d1-46f6-9ba8-f22b394161d2)

Which I believe it shouldn't unless permissions have changed, as according to HC only admins can invite/share:
https://citizenos.com/help/topics/understanding-topic-user-rights/ 

In which case, this box would look a bit empty for participants view, and I wonder if it needs a design re-think, wdyt? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/531a336d-2eb9-4590-981f-2f4f2e7ae117)

**Comment by kevincrepin** [comment]
Why can't participants invite people? 

If they can share a link that guides people to the topic anyway...

**Comment by BeccaMelhuish** [comment]
They're not actually meant to be able to share a link either, according to the current platform permissions - so I think it's a mistake that it's currently possible in the redesign (@ilmartyrk is that right?) :) 

@anettlinno can confirm, but I think it makes sense - so that the admin has control over who is allowed into the private topic space - e.g. if it's an annual meeting or board election, it should only be members of that organisation who can be invited - people can't just invite whoever they like, or it wouldn't be a safe space to say what you want to say knowing only people internal to the group/organisation will see it..

Different for public topics of course though! Presumably participants can invite whoever they like to public topics (@ilmartyrk is this the case currently?), and actually that's something that should be clearer in the HC..

**Comment by kevincrepin** [comment]
Ah yes, for private topics makes sense, I had public topics in mind... :)

In design we show a couple avatars, which would fill up the space a bit more.
![Screenshot 2023-11-24 at 13 56 24](https://github.com/citizenos/citizenos-fe/assets/26792281/96f7967c-e3f0-4e97-9c5b-c27844823224)

**Comment by BeccaMelhuish** [comment]
Yes that does look better! But I think @ilmartyrk said adding these profiles will be a Phase II thing? 
So am wondering how we could make it look better in the meantime.. (Once @ilmartyrk has removed the Invite & share button, if we all agree it shouldn't be there @anettlinno?)

**Comment by BeccaMelhuish** [comment]
I'm pretty confident it shouldn't be there (and wanting to sort it before testing ideally), so @kevincrepin what do you think about an improved design for the empty box for Phase I (until profile pics are added) - or OK for it to just have this bit?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/64676cc3-66b9-49fc-ae7d-5ee9d0ea4dc1)

**Comment by kevincrepin** [comment]
I would still keep the same component for regular users and admins or for public topics. Otherwise we have 2 different ones for the same content – seems unnecessary. And in a way it's good to have the participant count emphasised, it's an important number.

**Comment by BeccaMelhuish** [comment]
OK grand. So to summarise the task here is just:

- [x] Remove the 'Invite & Share' button from participants view
- [x] Resize the box accordingly 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/317e2cb2-6106-4592-b2d1-968e9a3b9a77)

(It may be necessary to remove it from editors view too, depending on the outcome of [this discussion](https://github.com/citizenos/citizenos-fe/issues/363) re whether or not editors are now allowed to invite people).

**Comment by anettlinno** [comment]
> OK grand. So to summarise the task here is just:
> 
> * [ ]  Remove the 'Invite & Share' button from participants view

Remove also "Manage" button from participants view :)

**Comment by BeccaMelhuish** [comment]
Ah sorry @anettlinno my screenshot above was misleading, there is no "manage" in participants view currently, it looks like this:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f555c85a-9dde-4729-8197-c563cb8a38e4)

**Comment by ilmartyrk** [comment]
@anettlinno @kevincrepin @BeccaMelhuish I've added the avatars as in the designs and removed the button

**Comment by anettlinno** [comment]
Ahh, love it! Looks beautiful and works as it should :) @BeccaMelhuish please check and close the issue if you´re happy :)

**Comment by BeccaMelhuish** [comment]
Looks great indeed! Closing :)
