### ISSUE TITLE
Group image won't show when uploaded

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#430]
**What is the problem?**
When creating a new group, I've uploaded an image for the group, which loaded like this (it actually had Christmas Tallinn on the pic):

<img width="892" alt="Screenshot 2023-11-26 at 17 33 40" src="https://github.com/citizenos/citizenos-fe/assets/34126353/e79bfb2f-056d-4d9b-80ce-531786707928">

And it won't show up after I've created the group, either.
And when I click on "Edit group" and add it once again, result is the same - it doesn't upload.

**Why is this a problem?**
It should show a preview of the group's image after uploading it.

**Comment by ilmartyrk** [comment]
@oksks actually the image is draggable and you can also zoom in and out using mouse scroll. It is a feature that we hadn't planned previously and it is quite confusing as there is no indication you can do these things. 

@kevincrepin can you propose a solution for that? I have in my mind a popup where user can do the dragging and zooming the image to fit a circular are. I think Facebook has something similar.

**Comment by oksks** [comment]
Sorry if I've been unclear @ilmartyrk - I've meant to indicate, that the image doesn't show up at all. It just shows this blue circle in place of an image.

Here's a video: https://drive.google.com/file/d/1xtruRpGHUijofTwnbWxdSdPO5MhdNrki/view?usp=drive_link

**Comment by ilmartyrk** [comment]
@oksks it does show up, it's one corner of the image, part of the sky :)

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk for me this is a high priority one to get fixed before testing, as seems it could cause quite some confusion, added the label accordingly :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @oksks I don't see this as a critical issue that must be fixed before testing as we don't have a proper solution to fix this issue anyway. Will remove the high-priority tag for now. And hopefully we can get some solution from @kevincrepin for image editing dialog before launch.

Reason: 
1) Image is uploaded UX is terrible as we don't have any guidance other than cursor, that user can actually drag or zoom the image
2) Not a critical feature

**Comment by oksks** [comment]
I would kindly disagree here - if we don't have a solution it doesn't mean it's not a high priority issue.
Maybe we could revert to the same functionality that we currently have on the (old) app? I think it worked just fine - yes, basic, but did the job. 
I don't think we need to apply all the fancy bells and whistles, if they're unusable and create so much confusion - I would've never guessed my image loaded at all, from what I saw upon uploading.

**Comment by ilmartyrk** [comment]
@oksks good point, reverted back to original solution till we get a better UX solution

**Comment by BeccaMelhuish** [comment]
Though @oksks @ilmartyrk do we leave this issue open as it will still need design for it from @kevincrepin? Or there is another issue open for that? :) 
(And is this a Phase II thing, or ideally sooner?)

**Comment by oksks** [comment]
@BeccaMelhuish I think - coming to the original bug report - this issue is solved and ticket is fine being closed.

Adding new functionality will need @ilmartyrk and @anettlinno to think through reqs, create a new user story, ask DUX for design and go through the whole dev flow from scratch.
