### ISSUE TITLE
ACTIVITY FEED: String variable isn't functioning properly in group AF

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#431]
**What is the problem?**
Ilmar changed my access level in the group to admin. For some reason, the activity feed notification arrived broken, didn't show "Oksana" instead of the variable:

<img width="305" alt="Screenshot 2023-11-26 at 17 48 19" src="https://github.com/citizenos/citizenos-fe/assets/34126353/c211db35-ecd6-44b4-b629-6beb556b4845">

**Comment by ilmartyrk** [comment]
@oksks posted a fix for that

**Comment by ssin1901** [comment]
@ilmartyrk went through Activity Feed and found a variation of this issue but with field update (see screenshot)

<img width="1440" alt="Screenshot 2024-02-03 at 17 12 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4a86a61d-ee6d-4ca1-834e-ca6de197b7e5">

**Comment by ilmartyrk** [comment]
@ssin1901 these field issues should be fixed

**Comment by ssin1901** [comment]
Current issue should be fixed, if issue recurs we can make a new issue
