### ISSUE TITLE
Alter argument loading

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#44]
Original in [fe-old](https://github.com/citizenos/citizenos-fe-old/issues/796)

Current pagination solution only displays x amount of arguments, but to make arguments more visible we should add load more button and load arguments into same view.

**Comment by ilmartyrk** [comment]
I agree with @ilmartyrk that if User chooses to press on "Load more" button after she has reached to the end of 10 arguments, she also sees the "Add argument" form. If she chooses to load more arguments (there could be said "Load 10 more arguments") then I think it´s OK, because there is also "Add argument" button on the right top of the Argumentary section.

If I remember correctly @kevincrepin, then this issue was solved in better way in our redesign project (add argument is always seen and clickable on the screen, even when scrolling up and down).

**Comment by BeccaMelhuish** [comment]
Will close this as seems no longer relevant post-redesign :)
