### ISSUE TITLE
Public topics start off as private (despite correct settings)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#440]
When creating a topic, I selected "public" in the settings. Once published, I checked in public topics and it wasn't there. I went back to edit the settings, saw it was set to "private", switched it to public, Saved changes. Now it was public. 

Repeated this with another topic creation to check wasn't my own error, but same thing happened.

**Comment by BeccaMelhuish** [comment]
@kevincrepin just mentioned having had a similar issue, but with editing the status rather than setting it when creating: "Somehow when I changed to public before it didn’t register. When I went in to edit it did actually show the correct status (public or private). But I had to save it again for it to show when published".

**Comment by kevincrepin** [comment]
Adding here screen recording of the behaviour: https://www.dropbox.com/scl/fo/mdf6cmlpja1m08gmwbht6/h?rlkey=x3gie9ddnir6dc484cpisy61l&dl=0

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk for me this is a high priority one to get fixed before testing, as it quite interrupts/confuses the flow of usage, added the label accordingly :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin this should be fixed now

**Comment by kevincrepin** [comment]
Seems to work for me
