### ISSUE TITLE
New topic pop-ups after editing topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#441]
These two pop-ups should only be when you have just created and published the topic, but currently they pop-up when you have just saved changes to it (Edit topic): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b79b5b92-21f0-45ed-b275-f36c67fc0530)

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk for me this is a high priority one to get fixed before testing, as it quite confuses the flow of usage, added the label accordingly :)

**Comment by anettlinno** [comment]
Triage 95. Issue fixed. Closing the issue.
