### ISSUE TITLE
MODERATION: Text review and bug: "Moderate Mark as resolved" message

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#443]
(Time-saving tip: I'd start reading from [this comment](https://github.com/citizenos/citizenos-fe/issues/443#issuecomment-1828302870) once I had figured out what this was all about :D)

I just reported a topic and this message came up. I'm not sure what's it's meant to be saying - seems like a bug as wasn't at the right moment for such a message, but if it's a real message in other contexts then the text needs editing (for grammar and clarity): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/81ec0fdb-50e8-4e76-ab5e-fb4e8914df24)

**Comment by BeccaMelhuish** [comment]
Ah I discovered (when trying to close with the X) that these are actually two separate links "Moderate" and "Mark as resolved", and when you click them they each open a different moderation pop-up. I guess it was appearing at a confusing time as I reported my own topic (which wouldn't usually be the case IRL). 

But nonetheless I think it needs some work as it's very unclear it's two links not just a weirdly-worded (non-link) message, what the message means, and also it looks like a pop-up that you can close (hence the X) but actually the X doesn't do anything (there's no way to close it). Maybe needs some design/input from @kevincrepin? (Kevin if you want to check it you can make a public group, report it yourself, and then you'll see this view).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d5186b06-9330-4932-9377-36c43b671a83)

Also the text on this "Moderate" pop-up isn't saying the right things, but @ilmartyrk I'll need some help from you in tracking down where these texts are in the translation strings :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/671861a2-fceb-49c3-a825-f9de22722e91)

**Comment by BeccaMelhuish** [comment]
P.S. Am understanding now that both "Moderate" and "Mark as resolved" probably wouldn't normally show up at the same time (in a usual case where you are not both topic admin and moderator at the same time)? But am a bit confused about which message is to who/for what, so @ilmartyrk please help with understanding this and then hopefully between better copy and better design we can make it all clearer in the standard contexts :)

**Comment by BeccaMelhuish** [comment]
Ahh OK, after going over it a few times in the email review, I've now understood what this is meant to be about, and that actually this issue isn't to do with me being being both the admin and the moderator. 

So @kevincrepin, I can summarise now that this is meant to be two different possible actions that a moderator can take:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/047a2ca9-13e8-42c0-ad73-98bb470da170)
 
- "Moderate" which means "hide the topic because I agree that it is inappropriate"
- "Mark as resolved" which means "don't hide the topic because it's not inappropriate" (either because they disagree with the reporter, or because since the person reported it the admins have edited it - hence the use of the word "resolved", though that's not relevant to all contexts here). 

When you click either of these two links, they open two separate pop-ups. (The text's on which don't currently make full sense, but hopefully you get the idea):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/41ef4b86-7279-48ad-b6cb-caec75eef3a2)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/454f85f1-bf44-4bde-8f4a-fd529a9778d1)

There is also another issue, which is that there is no option to delete (which I understand from @anettlinno is necessary if it involves hate speech for example. And even when selecting the hate speech option, no delete option appears).

Definitely in need of designs from @kevincrepin here, or guiding Ilmar to where the designs for this bit are if they exist already :)

**Comment by kevincrepin** [comment]
@BeccaMelhuish @ilmartyrk I made an example of how this could be improved: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=10101-59113&viewport=-8618%2C-4821%2C0.5&t=nRYrz5LNGqgbbZQv-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design
(prototype so you click on those notification text links)

Instead of the red error notification we should use the orange warning one. And we should give a bit more context to the moderator and 3 options:
- review reason
- hide topic
- mark as resolved

The above cta's need better wording. @BeccaMelhuish, feel free :)

I also made those dialog windows so they fit with the existing ones bit better. @ilmartyrk I think you're using a lot the blue background for these sections in dialog windows but mostly it's the light grey ;)

**Comment by BeccaMelhuish** [comment]
@kevincrepin I think it's better but still has the problem of using the "mark as resolved" as the only way to reject the report. But I think this is a problem with the moderation system as it stands - there's nothing in the system as far as I understand for the scenario in which the moderation disagrees with the report and simply wants to reject it. 

But ideally, it would be more like this (not actual copy suggestions, just the idea of what they each are for):

- Review reason
- Accept or reject the report (i.e. either do or don't hide the topic)
- Mark as resolved (if the issue that was reported has now been resolved - i.e. the admins have edited out the problem)
 
Then ideally, if the moderator rejects the report (i.e. decides not to hide it) and email gets sent to the user saying that the moderator didn't agree with their report. However I see this is a problem with the way the moderation system works, as I think the moderator can't tell if the admins have edited it before they got to it or not? Hence probably why this one is missing. But maybe we can find a solution that covers both scenarios - both moderator disagrees with the report, and the issue has now been edited out..  

Also, I've realised that as reporting topics always goes to an internal moderator, it's not so important that this is super clear as long as we all internally know what it means. But the emails to users about the decision made should be clear (which currently they're not, with the "marked as resolved" message).

**Comment by BeccaMelhuish** [comment]
This text also needs some work (confusing), but will leave it til the flow has been finalised, realise this may be a Phase II thing. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/eef07c1b-3ab9-46cf-b371-c67c44b59d5f)
