### ISSUE TITLE
Emails wonkiness on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#444]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/82a177f7-bcfd-4d98-a3f2-033dca07e928)

**Comment by BeccaMelhuish** [comment]
Plus some more wonkiness here below. 
(Bit at top should be reaching right across the screen (here it looks like a tab), bit at bottom should be in line with the box above it, though maybe the latter's just my preference. Top one is more definite I think).
I guess this is due to different length texts creating different width boxes, but maybe there should just be a standard box width for all to ensure it's all always aligned? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d28f6603-009d-4fc2-a9dc-bd78fadfe4ef)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I cannot fix the header and info table, not sure why it is happening for some e-mails. But nothing seems to work. Html and style support inside e-mails and different clients works very differently and sometimes very badly. Button layout is fixed though they are actually not buttons, as buttons are not supported. this is a table cell with button looks and an <a href> link inside. The link by default is only the width of the text so only solution was to add hardcoded padding to make the button clickable in the full width. But this padding broke the text to two lines on mobile. So I went and reduced the padding so it would look good on mobile
