### ISSUE TITLE
PROFILE: Duplicate success message

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#446]
**What is the problem?**
I've changed my full name under the Profile and got an confirmation message, which said "Success!" twice.

<img width="1241" alt="Screenshot 2023-11-27 at 18 14 46" src="https://github.com/citizenos/citizenos-fe/assets/34126353/469e513e-923e-46d3-b3af-4d7dc0a1e4a2">

**Why is this a problem?**
Text shouldn't repeat itself.

**Possible solution.**
Add text "Your profile has been changed" to the second line, instead of a second "Success!"

**Comment by ilmartyrk** [comment]
@oksks Added proper message from translations with key "MSG_SUCCESS_PUT_API_USERS_SELF"

**Comment by ssin1901** [comment]
Duplicate message removed and text corrected (see screenshot1, screenshot2, screenshot3)


<img width="1407" alt="Screenshot 2024-02-04 at 17 34 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f421ab1f-26a5-44c1-8fd5-bbc07f7a4b80">

<img width="1396" alt="Screenshot 2024-02-04 at 17 34 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d5c28e62-02ec-497d-9925-dcc10668cebb">

<img width="1406" alt="Screenshot 2024-02-04 at 17 34 40" src="https://github.com/citizenos/citizenos-fe/assets/72747107/af885055-2ce8-4c5a-b311-c67609283537">

Closing this issue
