### ISSUE TITLE
PROFILE: image disappears after refresh

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#448]
**What is the problem?**
I've added a profile image, clicked Save and got a "Success!" message, so the profile image was definitely saved to my profile.
Then I clicked "refresh" and the profile image disappeared - in Profile view and the frontpage view, too.

https://github.com/citizenos/citizenos-fe/assets/34126353/a96aa94d-108f-405d-b021-4b80e9e89174

**Comment by ilmartyrk** [comment]
@oksks this should be fixed

**Comment by ssin1901** [comment]
@ilmartyrk @oksks closing this as the image was stored properly now (see screenshot1 and screenshot2). I might check if there this another issue about the blurriness though. 

<img width="1160" alt="Screenshot 2024-02-04 at 15 43 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/272e596e-1d8d-45f5-a7a9-c42781d6d9f1">

<img width="1354" alt="Screenshot 2024-02-04 at 15 44 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6cde8bc7-4567-49a9-939f-fbf1fd97f986">
