### ISSUE TITLE
SEARCH: "View more results" link gets lost in search results

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#449]
**What is the problem?**
1) When searching for something in the app, you only get served a few results, and are offered to click on "View more results". However, since it looks exactly as a link and also sits with other links, it's absolutely indistinguishable as a button.

<img width="305" alt="Screenshot 2023-11-27 at 18 39 55" src="https://github.com/citizenos/citizenos-fe/assets/34126353/2ee2aac3-99f7-4d20-88b0-abd0b9591ab5">

2) Why so few results are loaded in the first place? If screen allows, it should immediately load more results. 

**Possible solution.**
Add a "Load more results" button instead of just plain text.

**Comment by ilmartyrk** [comment]
@kevincrepin needs your input :)

**Comment by kevincrepin** [comment]
In design there's a divider line and this separates the View more better: 
![Screenshot 2024-01-21 at 18 40 39](https://github.com/citizenos/citizenos-fe/assets/26792281/293670fa-11d2-464e-89e8-3869b0d1c671)

**Comment by anettlinno** [comment]
Triage 99. @kevincrepin currently we have "view all" under each segment (My topics, Public topic etc) and it works quite good from UX point of view. If I only want to load more topics for example, then I´ll click on view more under My topics. 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/da03d816-ed32-45b0-998b-526f8d499cd0)

In proposed design we should load all, but what if it gets too long?

**Comment by kevincrepin** [comment]
That's a good point @anettlinno and in the search results we also allow filtering according to topics, groups, etc so it makes sense to from here be able to immediately go to the right place.

Updated the design:
![Screenshot 2024-01-31 at 10 21 51](https://github.com/citizenos/citizenos-fe/assets/26792281/13be83e8-a5bd-44e6-adad-91eca262cd5e)

@ilmartyrk all the way in the bottom of this page is the component: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=248%3A35545&mode=design&t=mGZWYhdhylxuJwCW-1

**Comment by ilmartyrk** [comment]
@oksks added the new layout

**Comment by ssin1901** [comment]
Fixed (see screenshot) and moving to Done
<img width="1440" alt="Screenshot 2024-03-27 at 16 52 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ff6157d2-99dd-4ce9-b22a-ba0b60ffccea">
