### ISSUE TITLE
EMAIL: Apostrophes not displaying right in email headings: 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#450]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/93ffe053-b0c6-48a3-808f-aef5a9dc081f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by anettlinno** [comment]
Tested. Works nicely. Closing this issue.
