### ISSUE TITLE
Login with X email address for all email buttons to a topic? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#452]
@anettlinno, should we have this "you must log in with X email" message and the corresponding login pop-up (with similar message) for all emails that send people to a topic? Currently we only have it for the "You've been invited to a topic/group" emails, but am wondering if it should be in all of them? (E.g. moderation ones for example). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/59fff532-dcf0-4fda-a19c-adf99002f2a1)

**Comment by anettlinno** [comment]
That´s a good point, @BeccaMelhuish because the invite flow is pretty much the same with reported topics/arguments as it is with topic/group invites. I would push it to Phase II though, as currently we also don´t have it in reported emails eiher.
