### ISSUE TITLE
Blue bold text in emails when it's not a link

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#453]
In a few of these emails there is this blue bold text, but it's not a link. Not sure if the blue was a mistake or the lack of the link, but either way should be fixed :) 

(@kevincrepin this is the case right - that blue and bold font in the designs for the emails was meant to be only when it was a link?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fb4254f6-d29b-4c5f-8b7c-80ca57280240)

**Comment by kevincrepin** [comment]
Yes, should be a link that quickly guides you to the right place.
