### ISSUE TITLE
Moderation email formatting 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#456]
@kevincrepin what do you think about all this bold, and should there be one of those "info" symbols or something for the bottom chunk? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d01e6b33-3c80-4e93-92b2-756f60882765)

**Comment by kevincrepin** [comment]
The bold doesn't bother me. I'm not sure how realistic it is that such long reasoning would be given, which is what creates this wall of text.

But I like the idea about the informative text. Added design example here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=10099%3A11230&mode=design&t=JD3MB48GGbZ5hnlN-1

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin Should we use the same info box in emails like topic and group invites,  where we have the message 
"Please note: You must log in using the same email address ({{toUser.email}}) to access this topic."

**Comment by BeccaMelhuish** [comment]
Seems like a good idea to me, to draw more attention to it! Thoughts @kevincrepin? :)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/434bf5b1-449e-4279-aad9-95869f69ae16)

**Comment by kevincrepin** [comment]
Actually made this for one other issue :) 

![Property 1=Join Topic Not Logged in](https://github.com/citizenos/citizenos-fe/assets/26792281/f5aa5fbc-6dec-4238-9a56-211e018ecadd)

@ilmartyrk you can find it in the bunch of modals here ;) https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=248%3A35545&mode=design&t=J5P0yP4skaklMew0-1

**Comment by BeccaMelhuish** [comment]
Ah nice yes, more eye-catching like that!

**Comment by anettlinno** [comment]
Triage 99. Sending it to do. Approximate dev. time 2 hours.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this done now

**Comment by ssin1901** [comment]
@ilmartyrk almost matches the design by @kevincrepin (screenshot1, screenshot2) except in one place (screenshot3).

<img width="955" alt="Screenshot 2024-02-27 at 13 25 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f3ef0853-5cae-4a15-b383-d6af40546d37">
<img width="955" alt="Screenshot 2024-02-27 at 13 26 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fcf72892-49ff-4954-8eff-f883185aea13">

<img width="1077" alt="Screenshot_2024-02-26_at_21 57 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cbf8e546-024d-4ad1-8444-a487b5188f96">
