### ISSUE TITLE
EMAIL: 'What happens next' box design

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#457]
@kevincrepin Flagging this box in the emails for your attention, needs a bit of design input I feel :) 
(Tiny heading, big font, ugly bullets) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/505ccb3d-8ea4-47c9-aa70-25d7b37829f8)

**Comment by anettlinno** [comment]
Triage 99. Tagging @kevincrepin here :)

**Comment by kevincrepin** [comment]
Don't think it's so bad :) but made couple changes: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11762%3A112602&mode=design&t=mGZWYhdhylxuJwCW-1

![Screenshot 2024-01-31 at 10 41 24](https://github.com/citizenos/citizenos-fe/assets/26792281/df68622d-5558-45fc-85e4-ad1951485571)

**Comment by ilmartyrk** [comment]
@kevincrepin  @BeccaMelhuish Updated the designs though the numbered items look a little misaligned  in the e-mails, but there is nothing I can do

**Comment by ssin1901** [comment]
Closing for the time being as this won't be fixed in this phase
