### ISSUE TITLE
MODERATION: Missing moderation emails for reported discussion content? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#459]
@anettlinno @ilmartyrk We seem to be missing a load of emails for reported arguments/comments, compared to what we have for reported topics. 

For contributions, it seems all we have is "your discussion contribution has been reported" or "some discussion content has been reported" but no confirmation of the report to the reporter, and no email telling anyone the decision made, if it's been resolved, etc. 

Wondering if this is a mistake or a deliberate decision (or I'm missing something), as to me it seems just as important to have the whole flow for contributions as for topics? (Actually more important, assuming they are more likely to get reported - I would guess that's the case?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c4ec85f0-41c7-4838-983b-c160c87779e3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno I think this was deliberate as topics and arguments are different in their essence. Topic might have multiple editors and if one of them for reasons tries to sabotage the topic the current process allows others to fix the topic content. Argument is a  persons intended action an there is probably no intent to fix the argument if they wish they can delete it (hide) it themselves and in this case we provide a overlay text that author has deleted it themself. Anyway if you wish to change the process I'd rather push it to phase II.

**Comment by BeccaMelhuish** [comment]
OK I see! Something to think through a bit when we have more time I think, phase II indeed, if Anett agrees :)
