### ISSUE TITLE
Moderation decision email - decision/action taken not shown

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#464]
Related to [this issue](https://github.com/citizenos/citizenos-fe/issues/336) and [this issue](https://github.com/citizenos/citizenos-fe/issues/443) about the problems with the moderation system, we don't currently tell the user clearly what the decision/action taken was e.g. Action taken: Hiding topic / Deleting topic. 

This one's a simpler issue to solve than the others though :) 
@kevincrepin @ilmartyrk @anettlinno 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b9233099-8970-42c4-afc9-51a1e9e360e7)

**Comment by BeccaMelhuish** [comment]
Same applies for this email, maybe one other too, would need to check: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8767b205-0cc1-4a88-8a78-f36c65a14ae3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish the sentence "A moderator has reviewed your report of the above topic as inappropriate."  Kind of says that the topic is not acceptable. We currently don't have an action to delete the topic by moderator. As we ourselves are the moderators and the topics are hidden from general feeds (unless you specifically search from filters) I don't see the need to add deleting to our current version. 

Do you think we should just alter the sentence to include the info about topic being hidden

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah, actually that isn't supposed to read like that, but good to know that it does! That sentence is more like - "you know how you reported a topic as inappropriate? Well it's now been reviewed by a moderator." As when editing this email I hadn't realised this only gets sent out when the decision is to hide it (which I now understood is the case?). 

I think we can change it to this: 

"A moderator has reviewed the reporting of your Citizen OS topic. They agreed that the content is inappropriate, and have hidden it behind a content warning. Please see further details below."

**Comment by BeccaMelhuish** [comment]
I can switch this myself though, will do so later today :)

**Comment by BeccaMelhuish** [comment]
Ah actually sorry, my above suggested text is for the same email but to topic admins (not reporter), but I'll edit all similar ones accordingly!
