### ISSUE TITLE
AF doesn't close if I click elsewhere

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#465]
**What is the problem?**
On the current platform, you can navigate away from/close the Activity Feed by clicking elsewhere (great UX). In 2.0, clicking elsewhere does nothing, you have to find the big "X" and click it.

Bonus bug: there should be some padding between the "X" and "Show all activity" field.

<img width="299" alt="Screenshot 2023-11-27 at 22 58 30" src="https://github.com/citizenos/citizenos-fe/assets/34126353/4b5fa4b6-495a-4cb5-beaf-5ff5de4abc39">

**Comment by anettlinno** [comment]
Clicking elsewhere works not, but "bonus bug" is still unsolved :)

**Comment by ilmartyrk** [comment]
@anettlinno fixed

**Comment by anettlinno** [comment]
Tested and works nicely. Closing the issue.
