### ISSUE TITLE
IS: Big issues with inviting users

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#468]
Here's a list of the things that came up when I tried to invite us all to a topic: 

- [x] When I added Meelika, her email address stayed in the box after she was added. Happened again when I just typed her name then selected her username coming up:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ba1fb80b-8286-43cc-819e-7a4aee583e7f)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/12c0a772-fa6b-435b-b29a-1e2e13aafa05)

- [x] When I added Sara, she went to the bottom of the list. All the rest so far had been going to the top of the list: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b4357e64-3ac3-4e40-86bf-6a8e96026b11)

- [x] Then I added Oks, and she went somewhere in the middle:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fc6cbc7c-fe25-4de9-8e25-f9c1f1df5c55)

- [x] When I clicked 'Send invites' there was no confirmation that the invites were sent, or which ones were sent, there was just this pop-up that was still there from when I published, telling me to invite people (therefore potentially confusing, if you hadn't noticed it was there before). One for @kevincrepin's input for a good flow for this, and an invites sent confirmation (with which invites actually were)? EDIT: Kevin has now added a design solution for both these things below. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f5602056-600a-4f66-990e-ab1711b64ba5)

- [x] When I told the team on Slack they'd all been invited, Oks said she hadn't received an email. I checked the 'Invited' tab and only Anett (who was the first one I had added) had actually been invited. Tested again, sending both Oks and Ilmar invites (Oks first added) and again only Oks invite appeared in the 'Invited' tab. So invited everyone one by one and that seems to have worked (not heard from everyone yet). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/736fe5cb-d149-47d3-bc37-18c6f38411c5)

- [x] The invite/share link did work for me when joining with a second account, (FYI for [this issue](https://github.com/citizenos/citizenos-fe/issues/467)), but when I followed it this pop-up appeared both before and after logging in. @kevincrepin should it be before or after? EDIT: Kevin has added guidance and design for this below. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2ce15d55-1dfa-467d-bc21-1b6903366456)

- [x] No personal messages in the email invite (as per my latest [comment](https://github.com/citizenos/citizenos-fe/issues/320#issuecomment-1832407305) in [this issue](https://github.com/citizenos/citizenos-fe/issues/320)) :)

**Comment by kevincrepin** [comment]
Flow should be:
- publish topic
- immediately get prompted with invite/share modal and in this view we show notification about successful publishing: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=248%3A35019&mode=design&t=XhYfZ8CqlYuuiM7a-1
- When sending the invites the modal closes and then we can show in the topic view a notificaiton that invites have successfully been sent out.

About the invitation modal: we need 2 different modals as I think in the current platform. One if you're logged in that immediately allows joining. The other if you're not logged in that has main cta to log in. This didn't exist yet in the new design. @ilmartyrk I've added it here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=248%3A35545&mode=design&t=XhYfZ8CqlYuuiM7a-1

 
![Property 1=Join Topic Not Logged in](https://github.com/citizenos/citizenos-fe/assets/26792281/229d467a-c39f-463a-a076-de6ff6d6246a)

**Comment by BeccaMelhuish** [comment]
@kevincrepin though currently how it works is that these are two quite separate (looking and acting) pop-ups, so when the one I marked red closes, the one with yellow is still open. Should they act in sync, so when you close the red one the yellow one closes too? Or are you thinking the yellow one will stay open, but the text in it will change?  

I'm thinking maybe the message in the yellow one below can be included in the red on when you publish (just one pop-up not two), and then once published the yellow one could be used for the 'invites sent' message? 

Though I do think there's a benefit in including a list of which invites were actually sent (to give even more solid peace of mind that they have sent / ease of rectifying the situation if some of them didn't register for some reason / allow people to check over what they've sent and make sure they did it all right) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/929fb6e3-58de-44ba-b3bc-eba6e5f39532)

**Comment by BeccaMelhuish** [comment]
Oh I see what you mean now I think: 

These two are synced (so when invites are sent, both close together): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7e617aef-a06e-46b8-bd44-8d9b8e3fb900)


And then this one (longer and in a different place) we use for the 'invites sent' message: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9a98a629-6a32-4025-a7d5-e8d85c840784)

Makes sense to me! (Except not having the confirmation of which invites sent, but I think it's OK)

**Comment by kevincrepin** [comment]
Yep exactly :)

**Comment by oksks** [comment]
I will also add, that after clicking the invite link, I was prompted with the "You want to join..?" window => "Join topic" => was fed the login window => logged in with my COS account => Dashboard

**But I don't seem to have joined the topic, it's not in My Topics :(**

**Comment by ilmartyrk** [comment]
Fixed issues with inviting multiple users and missing message, issue that @oksks refers to needs digging deeper

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Great! What about the 'now invite people' pop-ups flow? :) 
(Sorry many issues in one in here!)

**Comment by anettlinno** [comment]
Triage 95. Fixing the last issue is in progress.

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish updated the invitation dialog, but the topic join dialog Becca refers here is a different flow with different dialog. Closing the issue

**Comment by BeccaMelhuish** [comment]
Reopening as I think some things are missing:

- The new flow that Kevin designed and I summarised in [this comment](https://github.com/citizenos/citizenos-fe/issues/468#issuecomment-1833797359). When I test it out the two 'now invite people' pop-ups don't seem to be redesigned and synced (both should close together as per design), and there's no "Invites successfully sent!" message. 

- Sorry I didn't understand what you meant about the topic join dialog [here](https://github.com/citizenos/citizenos-fe/issues/468#issuecomment-1840902488), @ilmartyrk?

**Comment by anettlinno** [comment]
@ilmartyrk @BeccaMelhuish I think there is only one thing left to be done:

- [ ] "Topic successfully published" message is not following the designs (they should be aligned on the same level):
Currently on redesing:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/ff53a195-bb8e-419c-8d7a-773ac9652e0f)

Accoding to the designs it should be: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=248%3A35019&mode=design&t=XhYfZ8CqlYuuiM7a-1

@BeccaMelhuish I just tested it myself and when clicking on "Now invite people" both tabs close and "successfully invited" message will be displayed: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/de7a7267-1a06-4409-a430-a8629ade738d)

**Comment by BeccaMelhuish** [comment]
Yes should be aligned like this, and only one X to close both of them (if you want to close without inviting, to not have to close both pop-ups: is a bit annoying):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/837e4c90-d13e-4184-b03c-ca172d58d380)

Currently there are two Xs, so you have to close them separately: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d91ac5ae-bf7c-42c0-a814-3acfe7bc936f)

But these are more minor and therefore less urgent things now, the main problem (of having the "now invited people" message still visible after you have invited) has been fixed - will remove the high priority tag and mark it as green in the "wishlist" :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @anettlinno fixed the notification width. Closing the invite dialog will remove notification, but will not work other way around as it will be too much work for not much gain.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk looks good thank you! Re the double closing, can the X in the notification not just be removed though, like in the design, or that's a big job?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9c2639b1-16e7-47e4-86d0-72e44ce0abb3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is a little bigger job, needs thinking how to properly solve and also what are the cases where it should be displayed and when not.

**Comment by anettlinno** [comment]
I think it´s OK with one X in the "Invite & Share" window as well, if it closes both windows. @BeccaMelhuish is there anything else left in this issue or we can close it now? 
If there is anything left, then please create new issue as this one is already monstrous and hard to understand what is fixed and what is still needed to be done :)

**Comment by BeccaMelhuish** [comment]
@anettlinno just to clarify this below was the design, whereas in the test site we have two Xs (one in each box). It's not a big deal but as and when there's time (for it to be thought through as Ilmar said would be needed) it would be good to have it as per the (cleaner, smoother) design :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e321afe5-d1f3-4e16-9219-30f860183a3f)
