### ISSUE TITLE
MANAGE PARTICIPANTS: 'Order by' not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#470]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a65bd989-c4cd-49c5-8aee-b16ea5679a5a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish Order by A-Z and role (ascending and descending) works perfectly but the "Order" remains "Order" (see screenshot). 

Please let me know if I should close the issue though.

<img width="1213" alt="Screenshot 2024-02-01 at 14 38 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fa1ce461-6488-4939-b13e-229ef1125952">
