### ISSUE TITLE
INVITE & SHARE: Missing and dodgy bulk actions for 'Invite' tab

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#471]
Was wondering what the bulk actions should be here (maybe needs @kevincrepin's input, not sure if it should be included here?), but when I click I see there are group related (this is a topic) and repeating: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d9ef0119-94c5-4d33-b565-d80e843fc017)

Also, the menu goes off the screen and makes the pop-up section scrollable (which feels rather odd) - see very faint greyed out scroll bars:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7e4618a8-b27e-4dd1-a0c3-58f799184632)

**Comment by kevincrepin** [comment]
Bulk actions should be:
- set all roles to x,y,x
- remove all participants

**Comment by BeccaMelhuish** [comment]
Grand, thanks! Though should it be just 'Delete all' as it's at the invites stage so they're not yet participating (and actually might not all have participant rights either)?

**Comment by kevincrepin** [comment]
Right! BTW wdyt of using "remove" rather than "delete", especially when it comes to people?

**Comment by BeccaMelhuish** [comment]
Remove also works I think!

**Comment by BeccaMelhuish** [comment]
So to summarise for Ilmar, bulk actions here should be: 

- Set all roles to member
- Set all roles to editor
- Set all roles to admin
- Remove all

**Comment by anettlinno** [comment]
Triage 96. 
We agreed to use "participant" in topics and "member" groups, so in topics bulk actions should be: 

- Set all roles to participants
- Set all roles to editor
- Set all roles to admin
- Remove all

Currently we are missing some bulk actions in group view and these should be added as well:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/7deeec10-1b9d-41a4-9b7b-484ebc237a72)

- Set all roles to member
- Set all roles to admin
- Remove all

**Comment by BeccaMelhuish** [comment]
@anettlinno though the first one should be singular as well - participant* :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno the issue was that levels were not translated properly

**Comment by BeccaMelhuish** [comment]
Checked and all seems correct now :)
