### ISSUE TITLE
DISCUSSION: 'Edit argument' button should be 'Save changes'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#474]
When you've gone in to edit your argument, should be 'Save changes' here, right @kevincrepin? :)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/21939379-d3c5-4ca7-8fc4-ecda11c4c24e)

**Comment by kevincrepin** [comment]
Yes!

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Tested and fix has been implemented (see screenshot)

<img width="1209" alt="Screenshot 2024-02-05 at 11 29 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/21f94865-b6dc-4b08-97f8-3a3fb470f147">
