### ISSUE TITLE
No way to close the reply box

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#475]
@kevincrepin @ilmartyrk there's currently no way to close the reply box once you've opened it (if you change your minds and decide not to reply - quite common): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/eb497d1f-0019-403a-9300-4fe29627eb02)

**Comment by kevincrepin** [comment]
It's missing the close button:
![Screenshot 2023-11-30 at 12 54 07](https://github.com/citizenos/citizenos-fe/assets/26792281/40e50f90-ea74-4903-b608-36fddf36a7e9)

**Comment by BeccaMelhuish** [comment]
Ah yes. Also missing the add images but @ilmartyrk I assume that's a phase II thing? 
(@anettlinno @ilmartyrk is that noted somewhere to add to phase II, or we should make a phase II labelled issue for it?)

**Comment by anettlinno** [comment]
Close button is added and works nicely, closing this issue.

@BeccaMelhuish in one point we need to go through all designs in Figma and create issues what to be implemented in Phase II. Currently let´s focus on Phase I :)
