### ISSUE TITLE
Argument menus not always showing up 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#476]
In one topic I get the full menu for the argument: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/896878ac-4af1-4812-85f9-eee4461104a3)

But only a shorter menu for the reply:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/669fbe89-47ac-4ab4-9a3b-9556d235e6bc)

In another topic I get the shorter menu for both: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3158d517-ed47-4b53-a108-d717dfac0ed1)

**Comment by BeccaMelhuish** [comment]
A related issue here: 
https://github.com/citizenos/citizenos-fe/issues/521

**Comment by ilmartyrk** [comment]
@BeccaMelhuish you are using two different users there, you are only allowed some actions for your own arguments created by the user you are currently using
