### ISSUE TITLE
TOPIC: Look of topic text/description section not good 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#477]
Probably already covered in @kevincrepin's design review, but just in case - flagging this dodgy looking bit:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1df71421-63fe-4e55-b396-7cd1028ad208)

**Comment by anettlinno** [comment]
Triage 99. This design is fixed now, @BeccaMelhuish. Closing the issue with no further action.
