### ISSUE TITLE
DISCUSSION: Issues with replies - too hidden, and too spacious, and missing @

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#478]
I'm a bit disappointed that the replies are so hidden again in the redesign, after we decided to make them more visible in the current version. I can't find the old issue now but I know we discussed it and decided to make them bigger and bolder.  
@kevincrepin can we make them a bit more prominent somehow? :) 
(They are so easy to miss, but you could be missing a long string of really important back and forth if you don't see them). 

Redesign:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/675d98c1-ea3b-44ad-ac09-97252af91dea)

Current: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d95a0411-5d03-445f-9f7f-31c42262e450)

Also, I feel like there's too much space around the replies in the redesign, e.g. below. @kevincrepin Should it be a bit tighter? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3014d07f-c52c-45d1-816d-618e783f2e09)

Also, we are missing the @ whoever we are replying to from the current version, is that deliberate?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fca7fd55-1e84-43e4-921f-3a94fee742fc)

And @kevincrepin in case you want to check, some discussion-related issues/suggestions I raised a long time back [here](https://github.com/citizenos/citizenos-fe-old/issues/762) (but not with you at the time), about the UX of replies, that maybe we could consider now or in phase II. It was decided this would be tested but then testing couldn't continue as hoped, so wasn't, but I will bear it in mind for upcoming tests.

**Comment by kevincrepin** [comment]
If we want to make them more visible or testing shows people don't find them we could do it like this: 
![Desktop](https://github.com/citizenos/citizenos-fe/assets/26792281/de634e52-a8d3-4bb3-8303-dd23506a627f)

@BeccaMelhuish can you elaborate on this _I feel like there's too much space around the replies in the redesign_?

**Comment by BeccaMelhuish** [comment]
@kevincrepin Oh yes, for the replies this is so much better in my opinion!

@anettlinno, OK to go ahead and add this without needing to test the need for it first? I feel like it's not only a UX thing, but also somewhat philosophical - i.e. why do we place such tiny importance (visually) on the replies in a discussion, when the voices' weight should be balanced (even more so than this in my opinion, as per my previous suggestions [here](https://github.com/citizenos/citizenos-fe-old/issues/762), but this would be a step in the right direction)  :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin re the space in the reply, please ignore this for now as I see there's a bug and the reply heading isn't showing - will make a separate issue then see how it looks once bug-fixed :)

**Comment by BeccaMelhuish** [comment]
Ah OK @kevincrepin, actually @ilmartyrk has confirmed that replies don't have headings (there was a heading field for input by mistake), so my question here was just an aesthetic one - whether you agree there's a bit too much white space (e.g. above and below the reply content)? Obviously the 1 word input doesn't help, but still feels all very loose?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4564bcdf-4a94-4d86-9bd1-8a277c9973be)

**Comment by kevincrepin** [comment]
Actually supposed to look like this. I think in your version it's a lot wider? We shouldn't actually expand the width of the content too much because it will hinder readability (long paragraph lines etc).
![Screenshot 2023-11-30 at 14 34 07](https://github.com/citizenos/citizenos-fe/assets/26792281/e30400ba-9a76-4b1e-b04f-ef12dd262f87)

**Comment by BeccaMelhuish** [comment]
Ah yes that does look better! Yes for me everything does stretch quite far across the screen currently. 
Though the replies don't have headings in the current version (of current live or redesign test), which seems correct (the expected UX I think)? So the reply body would shift up to where the title is in design?

**Comment by BeccaMelhuish** [comment]
Also @kevincrepin @anettlinno @ilmartyrk what do you think about the @ replies situation? Currently it seems to technically be working the same as current platform that you do reply to specific people, but no longer with the indication of who you replied to. 

Are we dropping that functionality (I think that's the case in the designs?), or keeping it (but if so will need a design for it - ideally better than the current platform one which doesn't work well in my opinion - as raised [here](https://github.com/citizenos/citizenos-fe-old/issues/762))? 

I'd suggest we launch it without direct replies for phase I, but then in phase II really spend some time designing and testing to make the replies overall work really well? (Like they do on Facebook for example - I'm sure they've based that design on a lot of testing, and it's always been very smooth and clear as far as I've experienced)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/59775ec6-dcc1-4809-81d1-beb42d863eb4)

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish this last image is because of reply to a reply, on our current platform we "flatten them out" and you can see from @personname that who the reply is for. I added this nesting here as I thought that in this version the arrow is pointing to the argument that the reply is for. So what do you think, should I bring them all to same level as on our current platform or leave it as is

**Comment by BeccaMelhuish** [comment]
Ah I see! 

So @kevincrepin it is like this: 
https://www.loom.com/share/ea7faf9eb1d14a88b454495ff2eaaea2?sid=d04c75c9-9ff2-4eeb-a581-83d8d01f214e

What do you think?

**Comment by kevincrepin** [comment]
I would say one flat level for replies and use the Facebook "@"/bolden username to indicate to whom the reply was.

I think nesting will quickly become messy, just imagine being a couple levels in, the indenting will create very narrow reply boxes :/

**Comment by BeccaMelhuish** [comment]
So just like this right? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1716d9b1-7ea3-4127-9eff-8576d803a835)

**Comment by BeccaMelhuish** [comment]
On Facebook when you click on the name it shows their profile, but maybe with ours clicking on the name will take you up to the comment to which the reply is attached?

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish I've flattened the list, update the "show replies"  button, but I am not sure how to highlight the argument the reply was meant to

**Comment by kevincrepin** [comment]
Nice @ilmartyrk ! Let's keep the button the same style when it's been clicked though: 
![Screenshot 2023-12-04 at 12 19 36](https://github.com/citizenos/citizenos-fe/assets/26792281/263574eb-a4e0-470b-8dd5-7dacd740296f)

And I think it's more about highlighting the author, not so much the argument/reply itself. Can do it like FB, the author's name in bold at the start of the reply:
![Screenshot 2023-12-04 at 12 20 48](https://github.com/citizenos/citizenos-fe/assets/26792281/5444cb8c-c5c6-4b01-837f-96f5728c90a3)

**Comment by anettlinno** [comment]
Trying to sum it up for implementation now :) 

- [x] Highlight "Hide replies" and "Reply" buttons and color them green
- [x] Highlighting the author: add person to whom one is replying automatically in bold (in front of the reply text)
- [x] Fix the width of argumentary
- [x] I think we have wrong font currently @ilmartyrk? It looks different from the designs: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/879eb3b8-f2ee-4faf-b1ab-893fd8fa546f)

**Comment by ilmartyrk** [comment]
@anettlinno button color depends on what type of argument is the parent of the button element, I think adding the bordered button style to "Show/Hide" replies buttons is enough as it was initially only designed as a link (view image 1 in the issue), but I will fix other stuff

**Comment by ilmartyrk** [comment]
@kevincrepin  @anettlinno @BeccaMelhuish . Currently clicking on the arrow before the reply will scroll to the argument or previous reply that the current reply was meant for.  I think we should add some highlight to the the argument too as the scrolling is not visible when the argument is already in the view,

example https://app.citizenos.com/en/topics/00efa891-6335-4b67-91a7-25b7929771a8?argumentId=fa9c67bf-d166-41b4-b6b8-c39bd930cfea_v0

**Comment by anettlinno** [comment]
@kevincrepin I´m unable to find the replies designs in Figma -- there are only designs for different types of arguments (pro/con/poi), but not replies. This is very much needed and with high priority.

**Comment by anettlinno** [comment]
Sorry, @kevincrepin found it! https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=137-30501&mode=design&t=GtItyIIfn5NCzpvq-0

**Comment by ilmartyrk** [comment]
@anettlinno  @BeccaMelhuish @kevincrepin I've modified the scrolling to the parent a little so that it will now scroll smoothly into the center of the screen, this should always trigger some movement on the screen making it a little more understandable for who the reply was meant for

**Comment by anettlinno** [comment]
@ilmartyrk @kevincrepin replies are much better now -- thanks a lot! 
But the narrowed argumentary looks very strange in wide screen. I opened separate issue for that here: #554

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno Initially the width for arguments and replies was set as 85% of the parent element. I set the max-width to 680px as in desktop designs. It is also possibility to revert to that size for arguments but make replies narrower or just revert the width back.

**Comment by anettlinno** [comment]
@ilmartyrk  GitHub has solved it so that discussion part is narrowed in the middle and only top menu bar is screen-wide. Maybe we can do something similar where everything (incl. left and right menu) are narrowed down in the middle and sides are empty in big screen?

Sorry, but I don´t know what the numbers and % means in real life :))

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/68cfec21-baf0-4f48-917e-50ab71afc004)

**Comment by ilmartyrk** [comment]
I think it's rather question to @kevincrepin, but I am sure it will mess up a lot of already implemented designs

**Comment by kevincrepin** [comment]
I'll answer this in the new issue: https://github.com/citizenos/citizenos-fe/issues/554

**Comment by anettlinno** [comment]
@BeccaMelhuish please check the replies functionality now -- in my mind it´s quite good already :) Please close the issue if everything works.

Just one thing with third reply (replying to a reply). Currently it´s on the same level with second reply, but it would be much easier to follow if that would be also visually distinguishable (aligned on the right). BUT we have had this discussion before. AND we have agreed that we´ll follow current designs and test it with Users. So, let´s not do anything now, but I just wanted to mark it here :))
