### ISSUE TITLE
DISCUSSION: 'Read more' shows even when there is no more to read

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#479]
Should only show when the text is actually too big for the space, and there is more to read: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6534989e-0e4b-4dac-bf2a-fa05e6c7c9ff)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  this should be fixed

**Comment by anettlinno** [comment]
Tested. Works nicely. Closing the issue.
