### ISSUE TITLE
FILTER: Text edits to My topic filters

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#480]
It's a bit messy as it is - with such a mix. I think all should start with capital letters, except "in voting" (and the others the same) as this is like it's starting half-way through a sentence: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9797a8dc-c0ac-4d1d-b5ea-66374093a7d7)

**Comment by BeccaMelhuish** [comment]
Also, need to remove topics here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b567a853-51ac-42d1-80fb-f3c0982187c8)

**Comment by BeccaMelhuish** [comment]
This one instead of 'every category' should be 'All' (though as per [this issue](https://github.com/citizenos/citizenos-fe/issues/484), should it even be a filter? Is this missing from the design or left out intentionally @kevincrepin)  
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0cd4c24a-7371-4c40-859e-5f8101da3311)

And same with this one:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/eaf4bd99-fa34-4380-957e-020a5ad94c5b)

**Comment by kevincrepin** [comment]
Not missing from the design, just under the expanded version:
![Screenshot 2023-11-30 at 16 19 01](https://github.com/citizenos/citizenos-fe/assets/26792281/e9d9a615-5033-4bbf-b11c-d3c355af61c2)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ah I totally missed that (it is in test too but hadn't noticed it), wonder if we can make it more visible?

**Comment by kevincrepin** [comment]
Let's wait and see how (or if) it's used in the wild.

**Comment by BeccaMelhuish** [comment]
OK yes :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin @anettlinno made all filters start with capital letters also currently showing filters we can actually use.

**Comment by anettlinno** [comment]
Tested and all texts start with capital letter. Closing the issue.
