### ISSUE TITLE
Reply headings not showing up 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#481]
Making a separate issue linked to [this one](https://github.com/citizenos/citizenos-fe/issues/478), the headings of replies aren't showing up:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f1087f79-80cd-40db-8b11-fd63ffd6c150)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish replies don't have headings, so will remove the heading field from reply inputs
