### ISSUE TITLE
FILTER: My topics filters - design/dev mismatch

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#484]
Noticed there's quite a mismatch between the my topics filters in the design and the test version @ilmartyrk @kevincrepin 

Was going to say that 'Visibility' should be 'Topic type' (as per design) or 'Topic status' (seems a better fit for what's there), but then saw in the design there is Current status as well as Topic type and got confused :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/737aadb9-f9eb-481a-bb7a-e6659a614a12)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b4025f4e-d923-4ce3-8e50-de9f41b373c0)

**Comment by kevincrepin** [comment]
In design these are

Topic type:
![Dropdown-1](https://github.com/citizenos/citizenos-fe/assets/26792281/51ea023c-9df2-4d69-a9b7-3a159c712153)


Current status:
![Dropdown](https://github.com/citizenos/citizenos-fe/assets/26792281/9089aec2-1064-4157-993b-376c27be0f2b)

**Comment by BeccaMelhuish** [comment]
This makes more sense! 
Though 'Moderated' should be 'Hidden by admin' as per that other discussion :)  
And 'Favourites' -> 'Favourited' just for consistency

And as per [this issue](https://github.com/citizenos/citizenos-fe/issues/480), what about categories, which is currently in test but not in design?

**Comment by BeccaMelhuish** [comment]
And @ilmartyrk what about the missing ones marked in yellow here - are they not possible/work in progress, or just an error? 
(1 from 'my engagement', and all from 'order')
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/13a7220d-c28f-426b-8c29-ed7a98712eba)

**Comment by BeccaMelhuish** [comment]
Expanded view from Kevin, for how it is in the design (order, headings, etc.): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/119dc445-51cd-47fc-92a6-9750505c54ed)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin I've left some filters out as they take too much time to implement on the API side, will add them later in the phase II, also I've modified the country and language selections a little to make them searchable as they are way too long to normally search or display on mobile. I might have gone wrong with it so please check

**Comment by BeccaMelhuish** [comment]
@ilmartyrk what about [these ones](https://github.com/citizenos/citizenos-fe/issues/484#issuecomment-1833856859), are they all doable currently and could be split/titled as per the design? :)

**Comment by BeccaMelhuish** [comment]
Removed the Phase II label as realised that may leave it unnoticed for now, but still would be good to get the existing filters as per design (before testing ideally). 

I guess Phase II label can be added back when Phase I filters are fixed :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the filters

**Comment by ssin1901** [comment]
@BeccaMelhuish I retested the filters, please check if everything is good for Phase I, and let me know if we can close the issue.

1. Topic type (screenshot1)
<img width="1211" alt="Screenshot 2024-02-01 at 14 11 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/30d746de-3399-4748-beea-1960ed33ed0e">

2. My engagement (see screenshot2)
<img width="1216" alt="Screenshot 2024-02-01 at 14 11 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3764def5-e28d-40b6-8505-1021efb6efe3">

3. Status (see screenshot3)
<img width="1214" alt="Screenshot 2024-02-01 at 14 12 30" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bdea8b5b-273c-4a63-a9cc-fb2a127f9623">

Also please remind me about the decision regarding Groups (screenshot from the Figma prototype)

<img width="1056" alt="Screenshot 2024-02-01 at 14 14 14" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4e6674b3-59e7-4b9d-882b-7bc849172dbc">

**Comment by ilmartyrk** [comment]
@ssin1901 groups filter is not added at this point

**Comment by ssin1901** [comment]
@ilmartyrk can we move this to Phase 2?

**Comment by BeccaMelhuish** [comment]
Phase I looks good from the screenshots :)

**Comment by ssin1901** [comment]
Since @BeccaMelhuish has approved for phase1, I am moving this to Phase 2.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish please check if we can close this one and create a new issue if needed

**Comment by BeccaMelhuish** [comment]
Made two new issues: https://github.com/citizenos/citizenos-fe/issues/1655 and https://github.com/citizenos/citizenos-fe/issues/1652 and will close this now :)
