### ISSUE TITLE
TOPIC: 'Create a discussion topic'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#486]
Please add in 'discussion' (not sure where this one is in the strings to edit myself) 

Test version:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/04f62b78-b0d2-4536-b2f6-8c167d362d20)

Design: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e58fc390-464e-4f46-ab33-81b4088d9d33)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish closing as its fixed
