### ISSUE TITLE
'Global activity' button

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#488]
In [this issue](https://github.com/citizenos/citizenos-fe/issues/355), @MeelikaH raised questions about the wording of the 'global activity' button. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/16a44b1b-3542-44eb-843f-ecf517d77718)

So for info Meelika, the idea is that this 'global' one is an activity feed which does pull in all activity from the whole platform, but in terms of what is relevant to them across the platform - i.e. any topics or groups they are participating in/members of. So it is 'global' but only relevant to them. And the reason for calling it this is because there is also a 'topic activity' and a 'group activity' feed, within each topic or group, which shows the activity feed for the specific topic or group they are in at the time, so we need to distinguish between them. 

Personally I see your point and had similar feelings when I saw the 'Global search' (global feels a weird word to me, for the users - more a kind of technical internal term I felt), but then couldn't think of anything to suggest to improve it, that would cover the idea of platform-wide versus topic/group-specific, so left it.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3e7f959c-579b-4228-a5c9-7fcdf3cfd5c4)

Adding @kevincrepin to the conversation for input/discussion :)

**Comment by kevincrepin** [comment]
I'm ok with changing labels if they support the functionality behind them :) So if we can rename "global activity" to something that still clearly makes the difference that the activity behind this is different from the activity when you're in a topic, I have no objections. 

Maybe it's as simple as calling it on the dashboard "Recent Activity" Or still just "Activity feed" and then in topic/group "topic/group activity"...?

**Comment by BeccaMelhuish** [comment]
@kevincrepin I feel like 'Recent activity' and then 'topic activity' or 'group activity' for the others could work. As it being on the dashboard should make it clear that it's activity related to the sort of things that grace your dashboard? Wdyt @MeelikaH?  

Though it's also possible we solve it by explaining it more clearly in the tour, screenshot of my WIP tour edits for this bit below:
(It's a bit convoluted/wordy though, not very easy to digest, so not sure myself yet)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/63100d38-98a2-4222-a577-02600008afdc)

**Comment by BeccaMelhuish** [comment]
Actually @kevincrepin I'm wondering if it shouldn't be:
'This topic's activity'
'This group's activity'

The additional 'This' would make it really clear what the topic/group ones are for. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f992f5cd-2e12-4b66-aa12-a61130c95097)

(Re 'Activity feed' / 'Recent activity' I can't decide my preference though)

**Comment by kevincrepin** [comment]
It could be if it doesn't become too long :)

**Comment by MeelikaH** [comment]
@BeccaMelhuish I'd solve this with specifying the text on the button, for sure, instead of only relying on tour, which presents more information at once which new users might not remember at once :) So "Group activity" or "Topic activity" seem good to me. I think I would even understand this if it was without "this" in the text but if it fits, will surely make it extra clear :)

**Comment by BeccaMelhuish** [comment]
OK so based on this, @ilmartyrk please can we have: 

- (Stick with 'Topic activity' / 'Group activity' for the button, as it currently is:)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e2dfdcff-748e-4176-94c3-1ad0ffcc3f3a)

- [x] At the top of the feed for each, please change it to: 'This topic's activity' and 'This group's activity' 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b0fd3f3b-b596-4692-9a9f-3d2c273ca7e1)

- [x] Change the 'Global activity' button to 'Recent activity': 
(The heading within the feed can still be 'Activity feed' though, as it currently is):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3aed4a11-2738-4366-a8b0-2469d2c62a4b)

@ilmartyrk @anettlinno I will add a high priority tag to this one as it's a possible area for confusion that would be good to check in the UX tests.

**Comment by anettlinno** [comment]
**Recent activity** sounds good -- sounds better and clearer :) I would love to hear what @oksks thinks about how easy it is to translate 'This topic's activity' and 'This group's activity' in different languages. In Estonian it would be already too long IMO ("Selle teema tegevused" and "Selle grupi tegevused" OR "Selle teemaga seotud tegevused" would be precise translation).

Removing high-priority tag as copy editing is not high-priority issues in redesign context.

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish fixed

**Comment by anettlinno** [comment]
Tested. All good, closing the issue.

**Comment by BeccaMelhuish** [comment]
Reopening as topic and group activity feed say 'Recent activity' at the top: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cbaa9bf2-1981-44cb-b795-d85145233136)

Should say 'Topic activity' or 'Group activity' as applicable :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue with the title
