### ISSUE TITLE
DB: What topics on dashboard? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#490]
@kevincrepin @ilmartyrk, the tour says:  

"As you're not yet active in any topics, we’ve populated this space with popular public topics.
Once you've participated in or created topics, they will show up here."

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e0d2ed33-725b-401b-9588-10b615fc35ed)

But on my own dashboard it's the same despite having made/joined some. How should it be? Not just public topics I think? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f286104f-6e7c-4aed-8f37-fb37b088d939)

**Comment by kevincrepin** [comment]
Initial logic was: haven't joined any topics or groups, we populate with popular public topics and groups for the user to serve as a (potential) jumping board. But when you join groups or topics, these public ones shouldn't be in your dashboard anymore.

No personal engagement: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=29-13070&viewport=305%2C-45%2C0.02&t=ODt1nTXQy3gjM7vo-1&scaling=scale-down&starting-point-node-id=29%3A13982&mode=design

Personal engagement: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=47-14884&viewport=305%2C-45%2C0.02&t=ODt1nTXQy3gjM7vo-1&scaling=scale-down&starting-point-node-id=29%3A13982&mode=design

**Comment by BeccaMelhuish** [comment]
This makes a lot of sense, how hard would it be to implement the two versions depending on engagement @ilmartyrk?

And for this one @kevincrepin, how come no public groups along with with public topics at the bottom? I feel like both would be good myself, and also seems like it could make it easier to implement? (I.e. when someone has joined a topic or group, the 2 public rows just get shunted down a bit, but both are still there not just topics)  

Personal engagement: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=47-14884&viewport=305%2C-45%2C0.02&t=ODt1nTXQy3gjM7vo-1&scaling=scale-down&starting-point-node-id=29%3A13982&mode=design

Tagging @anettlinno for input too :)

**Comment by kevincrepin** [comment]
We do have a separate menu item for public topics and groups that you haven't joined, so I'm not sure why we would also show it in dashboard once you've started engaging with content. I would want my dashboard to be about stuff I'm involved with. It's just that as long as you're not involved with anything, we have an opportunity to show content to help you engage with it.

Just my thoughts :)

**Comment by kevincrepin** [comment]
Seems I misunderstood or forgot that we indeed still show popular public topics below the news :) Fair point then, we could still show popular public groups as well.

Added also in design: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=19-6528&viewport=809%2C84%2C0.02&t=rFafFJCzx5C32tk2-1&scaling=scale-down&starting-point-node-id=29%3A13982&mode=design

**Comment by BeccaMelhuish** [comment]
OK great :) 
@ilmartyrk @anettlinno personally I feel like this is a pretty high priority one to be fixed before testing, but also not the end of the world if it isn't. Will add the label and @ilmartyrk can see how big a job it is?

**Comment by anettlinno** [comment]
Looks good and should be implemented in Phase I. 
This is not a high-priority issue @BeccaMelhuish and I´ll remove this label now and push it to Phase I To Do list.

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish this should be fixed now

**Comment by anettlinno** [comment]
Works nicely for me :) Closing the issue.
