### ISSUE TITLE
TOUR: Adjustments to the tour - visual emphasising and animation

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#491]
From @kevincrepin in [this issue](https://github.com/citizenos/citizenos-fe/issues/355), following the feedback from @MeelikaH:  

Here's the original prototype: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=29-13982&viewport=305%2C-45%2C0.02&t=ODt1nTXQy3gjM7vo-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

Couple differences:

- The background is blurred, but also faded (opacity 50%), I think currently that's not the case
- The element in focus has a (subtle) dropshadow which elevates it more from the base layer
- There's animation so it's easier to follow where the next tooltip in the walkthrough is focusing on. Probably not the easiest to develop but quite crucial I would say.
- One issue right now (I think I mentioned this in my feedback doc also) is that the screen focus aligns the tooltip to the top of the browser window. Ideally there is some upper margin so the tooltip is not "tucked away" so much and to get better context.

I would say if all of the above is done, greying out is not necessary.

_Originally posted by @kevincrepin in https://github.com/citizenos/citizenos-fe/issues/355#issuecomment-1834252409_

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk Added high priority label as would love to test the tour in testing / pre-testing calls

**Comment by BeccaMelhuish** [comment]
@ilmartyrk  Also one more thing in addition to Kevin's points above, as you can see in this video, currently for the first few steps of the dashboard tour, the screen scrolls down with the tour, so that the top of the tour text box is right up against the top of the desktop window. Which feels quite odd and a bit disorienting (especially on the second one, 'Main menu'). Would be better if the tour moved but everything else stayed static (except in case where there really is a need to scroll, because something is off the page). 

https://www.loom.com/share/13af498981374e95bc436ead428f1ef7?sid=a3fa3080-1dde-4a83-95c5-3c4723874b93

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish I've fixed the animation and background blur

**Comment by kevincrepin** [comment]
For me looks a lot clearer. Could the Main menu not have a dropshadow though? Or it should be the entire sidebar then.

**Comment by ilmartyrk** [comment]
@kevincrepin difficult start adding exceptions like that, will try and highlight the whole sidebar

**Comment by BeccaMelhuish** [comment]
@ilmartyrk ooh nice, so much better now! 

Two things though:
- To match the prototype, the Activity feed should pull out - is it possible? 
- When it gets to 'Groups' on the dashboard tour, for me it goes off the bottom of the window so you can't see it any more :)

**Comment by BeccaMelhuish** [comment]
Also, these should be bold :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7a89ccd0-0192-4c39-9932-85ac5b2b0a62)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e121c354-4fcb-4eda-8596-f6044e51a099)

**Comment by BeccaMelhuish** [comment]
Re-opening so these tweaks don't get missed :) 
(But without the high priority label any more, as the important stuff is done)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added bold, activity feed opening is a little more complicated thing to do. But maybe I can solve it in the future

**Comment by BeccaMelhuish** [comment]
@ilmartyrk thank you! 

A couple of other things I just spotted not quite as per design though sorry: 

In the design, this bit highlights all this corner section (as it refers to all the buttons up there, not just the 3 dots). 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c6bbdefc-bb77-460c-9ff6-bc1a32ed70c2)

Whereas in the current version, the tour blurs out everything except the 3 dots (so this is misleading, as the activity feed and favouriting that the tour talks about aren't found there):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/baa6ea50-d7c8-43b5-ab8d-1a4d8f5be4b3)

Also, the 'topic phases' currently has the activity feed highlighted, but shouldn't have (should be only the actual phases):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e2bb3c02-5d9b-4bbb-8f49-1aaeb3c82f06)

Will make a quick Phase II issue about making the activity feed pop out so we don't forget :)

**Comment by BeccaMelhuish** [comment]
Will make a quick Phase II issue about making the activity feed pop out so we don't forget :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk what about the things in my comment above - especially the top right corner? :) 
(Seems that same when I check it.)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk blurring seems to be okay (screenshot1)
<img width="1356" alt="Screenshot 2024-02-04 at 15 30 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d30c30a9-42c2-4782-9d98-078883bf12a0">

However, there is one UX question that I had. Why is Activity Feed in the Topic Tour under Manage when you cannot manage Activity Feed from there, and the actual Activity Feed is blurred? (see screenshot2)

<img width="1359" alt="Screenshot 2024-02-04 at 15 31 33" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5ddc1d44-364e-4cda-bce7-53033d646665">

**Comment by kevincrepin** [comment]
Myes, it's the result of the latest changes. We need to separate this in the tour now.

**Comment by ssin1901** [comment]
I think everything is okay for Phase 1, closing this issue.
