### ISSUE TITLE
TOPIC description input layout a bit wonky

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#492]
Big gaps either side of the toolbar, and cursor/type starts quite far in from the edge (not aligned with the rest)
Laptop, windows, Chrome

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/18f09eee-45ce-4cec-9650-b936ecada54c)

**Comment by ilmartyrk** [comment]
Not much I could do as we are dealing with an iframe and content inside that, but should be a little better

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk the alignment seems better now (see screenshot1) but still not aligned as per Kevin's design (see screenshot2)

<img width="1406" alt="Screenshot 2024-02-05 at 10 45 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/aab2c45c-d8c8-4ee4-a01d-703f7e1516dd">

<img width="1107" alt="Screenshot 2024-02-05 at 10 49 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6c9f7397-6c86-4574-a9b9-485cedfb2a52">

However, if there is no fix then can we close the issue?

**Comment by ilmartyrk** [comment]
@ssin1901  I forgot to update the src link for the Ethepad styles from redesign.app to test.app. It should now be fixed and aligned as per design

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish after update here is the fix (see screenshot). Closing the issue then.

<img width="1407" alt="Screenshot 2024-02-05 at 12 33 31" src="https://github.com/citizenos/citizenos-fe/assets/72747107/956f8a3e-cf0f-435d-9448-ea5703d67fb2">
