### ISSUE TITLE
Did you know / what's next boxes incorrect (topic creation) 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#493]
@kevincrepin @ilmartyrk Just flagging up that this seems to be the wrong text for the context - Kevin, do you have ideas for what goes here instead? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c0a6fc87-b01b-493c-baf0-60d9fc147361)

**Comment by BeccaMelhuish** [comment]
And @ilmartyrk, for this bit should be as per the design below :) 
(Currently it talks about discussions, which isn't possible in voting topic) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8a1a17a3-b7ed-4b24-b6e3-faed17f9f8b1)

**Comment by BeccaMelhuish** [comment]
Also @ilmartyrk, ideation needs to be removed from here for phase I: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f5d56a15-d1d4-4b6f-b7e8-3e41e6f0922b)

**Comment by BeccaMelhuish** [comment]
Also, currently when you go into edit topic (which could be long after having published, invited, discussed etc.), there is this box (which doesn't seem right to me?): 


![image](https://github.com/citizenos/citizenos-fe/assets/61320526/11601541-e66d-4c17-8e95-0f1f670e568a)

@kevincrepin do you have thoughts on what should be there instead? 
(Bearing in mind that the topic may change from a discussion phase to ideation/voting phase at some point, but remain the same topic)

**Comment by kevincrepin** [comment]
Good point. I think it could be removed entirely when editing a topic.

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK great! What about the first one, right at the top of the issue? Any thoughts on what should go there?

**Comment by BeccaMelhuish** [comment]
@kevincrepin For [this](https://github.com/citizenos/citizenos-fe/issues/493#issue-2020850677) one that's in the wrong place, how about replacing it with this? 

"Creating a voting topic allows you to cut straight to the vote. If you'd like a discussion before voting, create a discussion topic then add a voting phase." 

Would like to be testing this all with the correct texts next week (in theory), if possible :)

**Comment by BeccaMelhuish** [comment]
So to summarise the tasks: 

- [x] Make the copy in the 'What's next' box in 'Create a voting topic' match the copy in the design.
- [x] Remove the line about ideation in the 'What's next' box in 'Create a discussion topic'. 
- [x] Remove the 'What's next' box from Edit topic view. 
- [x] Change the 'Did you know' box in voting topic to the proposed copy in the comment above if Kevin agrees it's a good replacement (something needs to go there, as it's currently talking about discussions).

**Comment by kevincrepin** [comment]
for me it sounds good @BeccaMelhuish !
