### ISSUE TITLE
Vote phase description lock - bug and suggestion

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#494]
@ilmartyrk I went to check how it was when the description was locked due to a vote having started.

Bug:  
(Feeding through from current platform but shouldn't be here). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4c631d55-e8ff-4d67-9ef1-14ee88ca2474)

Suggestion:
@kevincrepin Instead of this create voting pop-up which as above shouldn't be there, could we have a pop-up that works in a similar way (popping up wherever you are trying to edit the text) that explains that the description is locked as a vote has been started? Or do you have thoughts on how we communicate to the user why the text won't budge. (Try starting a vote then going to edit the description and you'll see what I mean - would be quite confusing if you didn't know it locks after voting starts).

**Comment by kevincrepin** [comment]
I thought we were not going to keep this text edit voting functionality since no one seemed to know it existed or how to use it? @ilmartyrk @anettlinno 

Can't we just keep inline editing to also cover this case? We have "social voting" there with the thumbs up/down: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=6911%3A67355&mode=design&t=hGxzw5vXJ4PuWTI7-1

**Comment by anettlinno** [comment]
Yes, we agreed that we won´t keep the inline voting, so please remove it from redesign version @ilmartyrk 

Inline editing would be implemented in Phase II, I will create separate issue for that.

**Comment by anettlinno** [comment]
Inline editing is in issue #509

**Comment by BeccaMelhuish** [comment]
@kevincrepin what do you think about the problem of the user going to edit their text after voting has started and finding it locked though? We need to communicate it at that point I think?

**Comment by kevincrepin** [comment]
Yes, good point. I would suggest we still have the "edit" in the menu, but when clicking it then open up this dialog window:

![no editing](https://github.com/citizenos/citizenos-fe/assets/26792281/7d0c20eb-9a44-425a-ac20-b2a948b3ecfe)

@BeccaMelhuish feel free to write it better though :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Ah though the 'Edit topic' button gives you access to edit everything to do with the topic, rather than just the description. 

Currently it seems you can still change the title and intro, add attachments and a photo, but only the description is locked. (Is that how it should be @anettlinno @ilmartyrk? Doesn't seem quite right to me). And then there is step 2 where you can change the topic settings too. 

So I feel like the message needs to be along with the locked description?

**Comment by anettlinno** [comment]
Good point! After voting has started we should lock all parts of the document (header image, title, intro, description, attachemnts) and not allow editing any of these. 

Admin Users must still have access to edit: 
- Deadline and send reminders
- Make the topic public/private
- Leave topic
- Delete topic
- Change categories and tags

After clicking on "Edit document", we should only "lock" the "Compose" window in that case. Is that correct, @kevincrepin ?
<img width="733" alt="image" src="https://github.com/citizenos/citizenos-fe/assets/45175679/15ac0352-b51c-4222-8321-472d03356dff">

**Comment by kevincrepin** [comment]
Yes, makes sense! I would still allow users to open the topic text though, but there then open the dialog explaining why it's locked (instead of disabling the compose tab, for example).

One question is that when I click to edit the topic, would it also take me by default to the compose tab (locked, with dialog window) or would it take me to the settings. Normal behaviour when the topic isn't locked yet is that editing takes you first to compose. But this can become a bit cumbersome when the topic is locked and I basically want to change the settings... 

On the other hand then we're creating an exception where depending on whether the topic text is locked or not we take you to different places, which might also be a bit disorienting. 

![Edit - Locked](https://github.com/citizenos/citizenos-fe/assets/26792281/66538a5d-54ae-4b04-9e9c-1c0b23c605ad)

**Comment by anettlinno** [comment]
Good idea! I´m wondering if people know that topic "Actions" or "Settings" are under "Edit" in the first place? Is it a common practice @kevincrepin? Or should we remove "Edit topic" from the drop-down menu after topic is in voting or follow-up phase and only leave "Settings" there? 

Then, if User lands on the "Settings" page and clicks on "Compose" page, dialogue window with explanation is displayed.

**Comment by BeccaMelhuish** [comment]
My thoughts on this :) 

- It seems a good point that users might not realise 'Edit topic' also means 'Edit settings' (though we can also wait for user research to confirm this). 
- If we did decide this was a problem or research showed it was, we could add 'Settings' to the menu, along with 'Edit topic'? Then both pre- and post-voting you get taken straight to either Compose or to Settings tab depending which you select. If a user selects 'Edit topic' when it's locked, they still get taken there, but with the pop-up above (so they know what's going on). 
- If we didn't think it was a problem or while we wait for the research, then I think going straight to Compose as per usual, but getting the pop-up that explains and guides you to settings is maybe not ideal but also fine :) 

For the text in the pop-up, should we change it to 'topic content'? (As it's not all text?) 

Would like to add this to the pre-testing wishlist (to be testing whatever we decide on as best) if possible, but obviously needs finalising before dev :)

**Comment by ilmartyrk** [comment]
@anettlinno @kevincrepin @BeccaMelhuish I don't fully understand what and how to solve so just to clarify. When user clicks edit topic and editing is no longer possible. We display the Info dialog and after that user can access the edit view. User can switch between all tabs, but all fields in the first tab are disabled?

**Comment by anettlinno** [comment]
@ilmartyrk I´ll try to describe the use case:

1. Admin user has sent topic to voting or follow-up phase and clicks on "Edit topic" in published topic view:

<img width="200" alt="image" src="https://github.com/citizenos/citizenos-fe/assets/45175679/7c7ff494-e744-405b-9def-d29a3f62b470">

2. Admin user lands on the "Compose" page:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/a42b4955-fc97-47cc-b0fd-14443f04af22)

4. Admin user can still change "Settings" after clicking on the "View settings" button.

When User moves between different windows (Settings, Preview) then one can still go to "Compose" page, but this is disabled and the info dialogue box is showed.

**Comment by anettlinno** [comment]
I agree with @BeccaMelhuish that text should be: "When a voting or follow-up gets started, the topic **content** serves as..."

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish @kevincrepin Implemented the popup and disabled the items in the first tab. 

I set the disabled class items to have opacity: 0.5; is it OK Kevin?

**Comment by anettlinno** [comment]
@ilmartyrk there is a tiny-little-typo. Current text says: "Editing topic content is **not** longer available" but should be: "Editing topic content is **no** longer available"

I was actually thinking that the pop-up info box will stay there if admin clicks between different windows (compose, settings etc), but currently the "Compose" text is disabled. But this is a question to @kevincrepin about whether it should be with pop-up or disabled text :) 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/3a328ff3-d6b3-4e57-b292-653c838e170a)

**Comment by BeccaMelhuish** [comment]
I think the dialogue text needs some more work but will make a note to come back to it another time! (The single source of truth bit, for example - doesn't sit well with me in terms of media literacy, conspiracy theories etc.). 

I was still able to delete an attachment once it was locked, should I still be able to? 

Also when I then checked to see if I could still add an attachment, I got this error, that didn't seem relevant as I tried with allowed filetypes - is this due to the locking, and is the wrong message? 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ca8cbe55-66f4-4502-b5a4-e88fb896dddb)

Also discovered this related problem in the process, but made a new issue: 
https://github.com/citizenos/citizenos-fe/issues/561

**Comment by kevincrepin** [comment]
@ilmartyrk ok for me to set 0.5 opacity to disabled states
@anettlinno Yes, my idea was also that the dialog would always be visible under the compose tab.

**Comment by anettlinno** [comment]
@ilmartyrk shall we move it back "In progress" as what Kevin just confirmed.

**Comment by ilmartyrk** [comment]
@anettlinno @kevincrepin @BeccaMelhuish updated the dialog behavior, also fixed the typo. If I remember correctly there shouldn't be any restrictions with adding and removing attachments at this point of time, thought there was issue with detecting file types that now is fixed so if possible please check @BeccaMelhuish if it now works for you. If not then I'll need more info about file type and size you tried to upload
