### ISSUE TITLE
TOUR: Topic tour box placement for topic phases

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#495]
Should be pointing to where the phase tabs are (more to the left): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cc24fefd-f01d-4e98-96e8-881695ef6f41)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the positioning and highlighting

**Comment by ssin1901** [comment]
Seems to be working on regular sized desktop screens in Chrome and Safari (screenshot1 and 2). Closing and let's make new issues for responsive or mobile issues.

<img width="1046" alt="Screenshot 2024-02-06 at 14 27 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/82e39b4a-9003-4af4-9bc5-16dc14566c98">

<img width="1083" alt="Screenshot 2024-02-06 at 14 27 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/830955d1-d37b-4c7a-aaef-cd84de78e6b4">
