### ISSUE TITLE
Add Help Centre at the end of the tours? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#496]
@kevincrepin I think this might be a phase II thing as HC is on the backburner a bit at the moment, but what do you think about having a final step of the tours that opens up the HC and tells people to go there to find/ask for help, give feedback, etc.?

**Comment by kevincrepin** [comment]
Hmm, we can consider pointing out how to get to the HC, but not sure if I'd open it up. Of course ideally we would want people to not need to go there :) But showing where they can access help if they need it could make sense, yes!

**Comment by BeccaMelhuish** [comment]
Hmm yes, true we don't want people to have to use it ideally. But I'm thinking that it would be great if our users communicated more with us when they need help/have ideas or feedback. As we know our existing platform isn't user-friendly by any means, but the number of help requests or feedback submissions we get is oh-so-minimal.. But I guess this can be considered separately, how we get them to talk to us :D
