### ISSUE TITLE
3 x Activity feed heads should be different

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#497]
Current all the activity feeds have the same heading:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fb79c878-4da5-4c7a-9ff6-e49cc6be0b44)

But should be:

'Global activity'
'Topic activity'
'Group activity'

Unless there's a change as a result of [this discussion](https://github.com/citizenos/citizenos-fe/issues/488) but I think let's make them as per the design for now?

**Comment by anettlinno** [comment]
Closing the issue as this is fixed now.

**Comment by BeccaMelhuish** [comment]
@anettlinno Reopening as it doesn't seem to be fixed to me? When I go to them they all have this same heading (which isn't as per the design - all 3 should be different):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bdc1f247-abd0-4148-8a22-27a987ae3ba8)
