### ISSUE TITLE
HC and text query: Which permissions can add a new phase? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#498]
@ilmartyrk Is it only admins, or editors too? I will assume only admins for now. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/06d972be-d6e2-45da-936a-12068b36bff5)

**Comment by anettlinno** [comment]
Text should be revised so that it would speak to participants and admins at the same time.
As agreed in #363, then only admins can change topic status.

Closing this issue as this is duplicating issue #355
