### ISSUE TITLE
EMAILS through the platform

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe#505]
**What is the user story?**
1) When user receives an invitation to join a topic (or any other), the way organisation is presented in the footer area could be clearer. Currently, in the footer area with the text “For more information” makes one expect to get more information about the topic, Citizen OS or the platform. Even though it's linked “privacy policy” which will indicate you won't read more about the topic, organisation nor platform, I think it's not the best presented like this here. 

2) Also, the list os social media thumbnails would be useful to sort and add our website, which is currently missing.

3) It would be better is the dates throughout the system would be presented in a more user-friendly way, considering our users (Europe, Asia, not so much US-based people).

![Date_example](https://github.com/citizenos/citizenos-fe/assets/126671955/c181439f-2974-4b99-8b09-92024f0648be)

![SM_and_privacy](https://github.com/citizenos/citizenos-fe/assets/126671955/7e0fcbf6-f099-4e32-8122-7ece9e40e54a)

4) Currently there's a link/button missing for allowing readers to manage their e-mail settings.

**Which feature needs to be updated and how?**
1. Suggestion to adapt the text (@BeccaMelhuish please help with proofreading/editing): We care about your privacy. Read our privacy policy here. 

2. Arrange the social media buttons based on their relevance for us: Facebook, Instagram, LinkedIn, X, YouTube.
@anettlinno and @kevincrepin as Github is not your usual social media channel, would we want to visually place it somewhere else. It can also include a short call to action, e.g "Code better democracy with us!" or something like this. If you think it's good idea, @BeccaMelhuish please see if the text is okay like this. I think it makes sense to place it somewhere else in the footer.

2.1 Our website is currently missing. That should be added, but a question here to @kevincrepin how visually show it? I think when it's just in a list of all social media channels, it gets very lost. Please think how to show our website on the footer area. Thanks :)

3. If possible, change the display of date throughout all system so that users would always see Date/Month/Year format.  If possible, ideal way would be 4 December 2023 (all written out to avoid confusion for users from different parts of the world).

4. Please add a link (can be an additional text line after privacy policy part). Text could be ( @BeccaMelhuish please review): You have full control of the information flow – manage email settings here.

**Additional information.**
Sorry I assigned so many people to this one. Hope it's okay :)

**Comment by ilmartyrk** [comment]
@MeelikaH some quick answers
3. Dates are ISO standard we have gone through this before, it is really complicated to start changing date formats to different standards, it will blow up really fast if we start assuming where user is from (VPN, language preferences etc.) we decided to use ISO standard everywhere 
4. There is no manage e-mail settings system currently in place and it won't also apply for the current emails we are sending out at least until we have some invite accepting system in place in the phase II

Other items I will leave for others to decide and will implement if solutions are ready

**Comment by anettlinno** [comment]
@MeelikaH good points!

1. First point is especially valid for new users who haven´t heard anything about COS and are invited in the topic. Do you think instead of Privacy Policy we could replace it with "Do you want to know more about Citizen OS? Check here" and the link could direct on the Product (or landing page) of our website? 
2. GitHub is actually quite important for us and icon is meant for those people who wants to interact/read/know more about our open source code. I think if we would add one more row ("code better democracy with us") it would 1) be unimportant for huge amount of Users 2) taking space and creating noise in email text. So, I would actually support leaving GitHub logo there as it is.
I support adding website somewhere there (OR if my first suggestion likes you, then this link will direct on our website)

**Comment by MeelikaH** [comment]
@anettlinno My proposal is to:

**1. Change the text:** We value your privacy. Read our privacy policy here. 
**2. Add a button:** Visit our website
**3. Change the order of SM thumbnails based by priority:**  1) Facebook, 2) Instagram, 3) LinkedIn, 4) X, 5) YouTube.
**4. Leave Github thumbnail as it** is then, but keep add it as the last one. I guess those who know, know :)

**Comment by anettlinno** [comment]
Triage 99. @kevincrepin could we please add in email bottom text and link on our website, as suggested by Meelika above.

**Comment by kevincrepin** [comment]
Updated the footer and it looks like this now:
![Screenshot 2024-01-31 at 10 47 54](https://github.com/citizenos/citizenos-fe/assets/26792281/7e5bec9f-3974-43c0-b17f-57d0d4c47a04)

@ilmartyrk, Figma: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=764%3A81655&mode=design&t=mGZWYhdhylxuJwCW-1

**Comment by ilmartyrk** [comment]
@MeelikaH updated the e-mail footer

**Comment by ssin1901** [comment]
Matches the design by Kevin (see screenshot). Closing the issue.

![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/13fbe0d5-07ad-4614-997a-de3bc7cad976)
