### ISSUE TITLE
FOLLOW-UP: Send to follow-up box

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#508]
This text needs some work as it won't always be correct. I.e. if it's a discussion topic with no vote then the second line won't be relevant. Also does the first line mean that the topic settings and content gets frozen, or also the discussion? 
@ilmartyrk @kevincrepin :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dda5b47e-9247-4655-8b02-c2cab8c2bba7)

**Comment by BeccaMelhuish** [comment]
As per conversation with Kevin on Slack just now, actually what happens is you get this first:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ffb867dc-ec09-4bea-8272-86c496803143)

And then you click start topic follow-up, and you get this one: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ebedfcd4-2700-4a88-8bf7-6a7eb88ed250)

Which @kevincrepin confirmed isn't necessary, though agreed that we'll need different texts depending on whether a topic was sent to follow-up from a discussion or from a vote :)

**Comment by BeccaMelhuish** [comment]
So to summarise, tasks on this would be:

- [x] Remove the second pop-up
- [x] Create the new texts for voting topics, that talk about the vote closing/no longer being able to vote, or whatever is relevant to voting topics now (@anettlinno, not sure if Kevin would be providing these texts or me?)  
- [x] Create a different pop-up sending voting topics to follow-up (different to discussion topics) with the above text

**Comment by anettlinno** [comment]
Totally agree that second pop-up isn´t necessary :) 

@BeccaMelhuish please provide texts for voting topics. I don´t quite follow, what do you mean by "create a different pop-up sending voting topics to follow-up"? It´s the same pop-up but with different text -- is this what you meant? :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish can we just add the item with text "voting will end and further voting will not be possible"? I think other items are can stay in both views. So I can use the same popup, if topic has Vote attached to it then we'll display the item with vote related info if not it will be hidden 

I've added it the way I suggested, please check if it is OK

**Comment by anettlinno** [comment]
IMHO it is simple and clear now. Thanks @ilmartyrk. I will close the issue as it´s completed.
