### ISSUE TITLE
Inline editing in creating a topic

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#509]
**What is the user story?**
In redesign Phase II please implement the inline editing when creating a topic: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=6911%3A67355&mode=design&t=hGxzw5vXJ4PuWTI7-1

**Which feature needs to be updated and how?**
Inline editing feature

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Closing as it is duplicate of https://github.com/citizenos/citizenos-fe/issues/148
