### ISSUE TITLE
TOPIC information card section styling

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#510]
The titles/labels _Attachments, Groups, Categories_ do not need to be in blue. Only the actual files or links when opened up should be blue.

Also when opened up, the arrow should point up.

Dev:
![Screenshot 2023-12-04 at 15 02 08](https://github.com/citizenos/citizenos-fe/assets/26792281/2a841843-d0a1-4081-8174-8dff74e390b2)

Design:
![Screenshot 2023-12-04 at 15 05 18](https://github.com/citizenos/citizenos-fe/assets/26792281/ee6c77ea-58c2-4fca-909e-92742b787e35)

**Comment by ilmartyrk** [comment]
@kevincrepin should be fixed now

**Comment by ssin1901** [comment]
Tested and it seems to be working as intended. See screenshot. 

<img width="1208" alt="Screenshot 2024-02-05 at 10 41 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/88d9aeb5-6beb-43da-a682-6bf38592966f">

**Comment by ssin1901** [comment]
Closed for reasons indicated above
