### ISSUE TITLE
API: Email font too small in mobile view

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#511]
**What is the problem?**

**(On an iPhone 📲)**: In the topic invite email I've just received, font size for some reason isn't the default one set in system settings, but much (MUCH) smaller and hard to read. For comparison, my correct system font size is the size of "To: oksana@citizenos.com" right at the top. 

**Seems to apply to all test emails.**

![IMG_1233](https://github.com/citizenos/citizenos-fe/assets/34126353/75ee00c0-032c-4bcd-9aae-6f29aac6446c)

**Comment by anettlinno** [comment]
Triage 99. Needs some investigation. Approximate investigation time 1 hour. Sending it back to backlog.

**Comment by ilmartyrk** [comment]
Email issues seem to be really client specific and these are really difficult to fix as there aren't any good workarounds.
