### ISSUE TITLE
DISCUSSION: Weird red highlighting while writing an argument

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#512]
**What is the problem?**
I was writing an argument in a topic, and words kept turning red while I was writing. Haven't had this happening in any other text fields on any other pages - just here, so don't think it's a browser or extensions' bug. 
Mac, Chrome.

https://github.com/citizenos/citizenos-fe/assets/34126353/6779490c-8e46-4656-b8ba-ae55aad3ea47

**Comment by oksks** [comment]
Tested, same happens in Safari:

<img width="876" alt="Screenshot 2023-12-04 at 15 44 12" src="https://github.com/citizenos/citizenos-fe/assets/34126353/aad5399c-8e8b-42e8-92c3-63ed39c5e32c">

**Comment by ilmartyrk** [comment]
@oksks caused by markdown editors default spellchecker, turned it of from the config so should be fixed
