### ISSUE TITLE
DISCUSSION: Argument's direct link doesn't lead you to it

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#513]
**What is the problem?**
I've tried copying the direct link of an argument (argument => three dots => direct link), and then pasting it in a new browser window - it doesn't open the page with the argument in focus, unfortunately. It jumps to the top of the page.

<img width="1006" alt="Screenshot 2023-12-04 at 15 46 30" src="https://github.com/citizenos/citizenos-fe/assets/34126353/ccfcd532-cd1a-4b39-966d-df86cc7bc1ff">

Bonus bug: Pasting the link in an incognito window (so = not logged in view) gives a "Not Found" error - it should propose you to log in to see the argument.

<img width="1218" alt="Screenshot 2023-12-04 at 15 48 12" src="https://github.com/citizenos/citizenos-fe/assets/34126353/10e42c13-8772-42ff-a465-6f62f509c287">

**Comment by ssin1901** [comment]
@ilmartyrk direct link leads a logged in user with correct permissions to the correct topic but not the argument.

1. Here is the actual view (screenshot1)
<img width="1211" alt="Screenshot 2024-02-05 at 11 19 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b8cd0be1-3676-45e4-b6da-873316fc42df">

2. What was expected was that the direct link to _Testing direct link_ should have lead the user directly to the argument (screenshot2)
<img width="1212" alt="Screenshot 2024-02-05 at 11 21 10" src="https://github.com/citizenos/citizenos-fe/assets/72747107/851b2e4d-97ef-4bd9-8f9e-4a3b7b0fcf8c">

**Comment by ssin1901** [comment]
Resolved (See screenshot)
<img width="1299" alt="Screenshot 2024-03-05 at 15 46 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/66911ac2-ce3c-4366-9184-79f721be4409">
