### ISSUE TITLE
Idea for visually explaining the allowed order of phases

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#514]
@kevincrepin @anettlinno @MeelikaH @ilmartyrk 

From a mix of guesswork, trying to write the tour texts, and talking to Meelika about her confusion about how topic phases work, I've got a strong hunch that the allowed order of topic phases (discussion topics can be followed by voting and follow-up, but voting topics can only be followed by follow-up) is going to be hard for users to grasp. 

@kevincrepin I've got a proposal (below) for how we could present this more visually, which I feel might help get this across more quickly to users? Wdyt? (Just a rough mockup to give the concept - am aware they look like buttons though which isn't ideal). 

And if you like the idea, would you agree this is something to try and put in place before the user tests (so we can test if it works)? I feel like as it's so likely this matter will cause confusion, we might as well test it with more of a solution in place already? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2e153b2f-98f6-403e-9b35-9229db69eab6)

Also, could someone remind me why it was decided to not allow a discussion after a vote? Would it be a problem to just allow it, even if it's very rarely used? Would be so much simpler to explain/grasp if you could do any phases in any order except follow-up was always last, but I know there was a rationale to the decision initially..

**Comment by BeccaMelhuish** [comment]
P.S. Am thinking a line could make it seem less like buttons and more like phases: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/51053378-c97a-46d4-a633-1f0c29fd3861)

**Comment by kevincrepin** [comment]
Love the idea @BeccaMelhuish. I went in and alrdy updated the design, and then looking at it I started to wonder if it's actually creating too much (visual) noise...

It's definitely cleaner without, but thinking that with reduced texts maybe it could be better? Screenshot below with old texts.
![Screenshot 2023-12-04 at 17 13 49](https://github.com/citizenos/citizenos-fe/assets/26792281/db8bfc9d-749b-40f7-96bf-a95d89999504)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Great glad you like it! 
Hmm yes I do agree it's a lot to take in like that.. Shorter texts is a good idea though. Just off the top of my head (might be some better wording out there), how does it look with just this? 

Start with discussion, then add an optional voting and/or follow-up phase. 

Start with ideation, then add an optional voting and/or follow-up phase. 

Start with voting, then add an optional follow-up phase.

**Comment by BeccaMelhuish** [comment]
P.S. I don't know if we can have a tooltip on a menu like this? But if so we could then have a tooltip next to each option heading where it explains in more detail (for anyone that needs it), to allow the wording on the menu to be minimal like above?

**Comment by kevincrepin** [comment]
Rather not have tooltips here. Shouldn't be necessary. I'm also thinking now – after initial emotions :) – that maybe we're a bit overthinking this and adding too much... When you create in google drive a document or a spreadsheet it also doesn't give you any explanation. Because people do learn and fain understanding.

And I think in this case it's more the difference between when to start a discussion topic and when to start a voting topic, not necessarily which one offers which phases afterwards. Most ppl wouldn't even know yet about these phases anyway. 

So maybe the copy should reflect the focus of the choice, rather than what phases you can have after?

**Discussion topic:**
Allow participants to have a discussion before moving to optional voting and/or follow-up.

**Voting topic:**
A no-nonsense format to gather votes without prior discussion.

**Comment by BeccaMelhuish** [comment]
I think this less wordy way of saying is definitely easier to digest! And more likely to be read.

I still think it's quite confusing though... As we call it a discussion topic, but you can add actually add voting to it. I think it's quite hard for people to get their heads around unless it's really spelled out.. 

And some feedback from @anettlinno's UX tests last time was this (on a different UX, granted), about needing to know what phases are possible later at the point they're making the topic:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/569797a2-f072-4eba-84b9-57feb5743ac7)

Also I feel like with the Google example it's quite different, as they're so much simpler, and once you are in one you're aware exactly what you're in (it looks very different), and it doesn't affect the options for later (no future phases to add etc)..  

Is there a less visually cluttering way we could do a similar thing? I feel like it would really help people orient themselves. I guess one option would be to include this visualisation in the tours, along with the (new) explanations of the phases and their order, instead of in the menu? 

If we do go with just the texts though, I'd suggest edits like this - wdyt?  

**Discussion topic:**
Start with a pro and con discussion. Add an optional voting and/or follow-up phase later.

**Voting topic:**
A simplified format to gather votes without any discussion. 

@anettlinno @MeelikaH did you have any strong feelings on this - Anett from the previous tests you did as screenshot above, and Meelika from your experience of trying to understand it today? :)

**Comment by anettlinno** [comment]
I think under the "Create" we should only talk about what is "Discussion topic", what is "Voting topic" and what is a "Group". I very much agree with what Kevin said that when people initiate discussion or voting, they want to know only about these things. Questions about what phases and other opportunities there are, comes later, so I do not support adding those colorful labels as it creates too much visual noise and makes it even more confusing. 

I see that our current texts are also referring to what you can do later, but here we would rather want to explain people, what it is that they can do now -- when creating the discussion (maybe something like "_Co-create a topic and invite people to the discussions_")

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/b81f5a85-3886-4c8c-a43f-2d87a4bd33b6)

I would like to know what @oksks thinks about current texts?

We have a plan to create a "How to use Citizen OS platform" chunk on the front page, but probably in Phase III :) There we should explain all users -- new and existing ones -- what they can do in the platform, about discussion, voting, ideation and follow-up phases and its logic. But for now let´s keep it simple and clear :)

**Comment by anettlinno** [comment]
AND in topic creation we explain what next steps User can take: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/b9ad5ada-e13a-4e23-82f0-6869117994ca)

**Comment by BeccaMelhuish** [comment]
I think as we have such different ideas/assumptions of what the user will need/want to know and at what stage in the process, let's leave it as per the designs for the tests and see what the user research comes back with, then continue the conversation after if it's needed :) 

Though personally I really liked Kevin's [new suggested shorter texts](https://github.com/citizenos/citizenos-fe/issues/514#issuecomment-1838912489), except for the "no-nonsense" bit which I'd replace with "simplified" (to not accidentally suggest that discussions are nonsense :D), and would rather test with those if we can come to an agreement on them before Weds. 

I'd definitely be aiming for something that is intuitive without relying on any help from a user manual (e.g. the "How to use Citizen OS platform" chunks) though, but hopefully through the tests we can find ways to avoid that :)

**Comment by anettlinno** [comment]
OK, everyone has spoken now :) @kevincrepin and @BeccaMelhuish I´ll close this issue with comment that we´ll User test the copy and change it accordingly in the future. Let´s not implement colorful phases explanation visuals in this point.
