### ISSUE TITLE
TOPIC: Insufficient permissions error when creating public topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#515]
Was just creating a public topic and when I went to publish it, got this error during preview: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/45cee8d0-2d88-4c13-a623-ee1e1046a9a3)

**Comment by BeccaMelhuish** [comment]
I think it may be related to not having added an intro, but not sure

**Comment by anettlinno** [comment]
@BeccaMelhuish could not replicate the issue. Please check one more time -- maybe it was one-time problem?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno I believe it was related to draft issues. Intro is not required for publishing

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno not exactly the same thing but very similar - I'm now getting it when I try to go into any public topic, via a public group:
(But I just tried creating a public group and it was fine - no error).  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fd33a18d-333f-474e-9f82-3befe6fe17a2)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think it was because the topic was private and you weren't member of the topic or the group. If that is the case I removed private topics from public groups topics list for users who are not members of the group

**Comment by anettlinno** [comment]
@ilmartyrk @BeccaMelhuish could not replicate either issue -- both works for me now. I´ll close this issue for now but if you still have problems @BeccaMelhuish, then please reopen.
