### ISSUE TITLE
Issues with uploading photos

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#517]
Two issues came up when trying to add a photo to a topic:

1. I uploaded one photo then realised it wasn't the right one, so removed it. I went back and selected the right one, but it uploaded the wrong one again. I repeated and the same thing happened. 

2. I went away to the settings tab and then came back to the Compose tab. I tried again uploading the photo but this time it displayed blank like this, so I couldn't see if it was the right photo or not (or nothing). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/48cf399b-3596-4c11-beb2-b0bf256f855a)

**Comment by anettlinno** [comment]
Triage 96. Could not replicate the issue @BeccaMelhuish. Pease try it out and if now working, please let know.

**Comment by BeccaMelhuish** [comment]
Seems to be working, will keep an eye (as it was just an occasional problem, not every time), but closing the issue :)
