### ISSUE TITLE
Share feature broken

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#519]
**What is the problem?**

- When clicking "Invite & Share" in topic view, the "Generate a link to share" option isn't clickable anymore, instead it's a text field where one can write whatever. 
- The "Copy link" button doesn't copy anything since there's nothing generated and nothing to copy. 
- The "Link copied" green notification appears for a too short period of time, should appear for probably 2x longer as one can't spot & read it this quickly
- The "Generate QR code" button just takes you back to the same initial broken view, just without the QR button and with less text, without QR code

<img width="580" alt="Screenshot 2023-12-05 at 00 04 21" src="https://github.com/citizenos/citizenos-fe/assets/34126353/7468979b-38ae-4bae-b369-7504d9224dcd">
<img width="576" alt="Screenshot 2023-12-05 at 00 08 55" src="https://github.com/citizenos/citizenos-fe/assets/34126353/e8872c1e-1135-4c3f-ae74-14f8b751a1df">

**Comment by anettlinno** [comment]
Triage 95. Tested. In my own topic everything works well -- link is being generated and can share the topic via email.
Tested also with Ilmar´s topic (with participant rights) and link is being generated and can share the link. 
Replicated issue when User was logged out and wanted to share public topic -- in that case the link was missing.
@oksks could you please elaborate step-by-step Use case? 

Design wise let´s add just direct link to topic without editable field.  

Bulk actions (translations?) are wonky: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/bc218ac8-bd28-486b-bc73-955f73af007e)

**Comment by oksks** [comment]
Tested again with being logged out - everything works OK now, thanks.
