### ISSUE TITLE
Please delete 3 x tour paragraphs about Phase II features

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#524]
@ilmartyrk In these places, the tour mentions things that aren't currently included in the platform. Would be great to have them removed before testing the tours if possible :)  
(Should be added back in in Phase II though) 

In Dashboard tour:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/15bae683-8592-40df-b572-aee1f48b3dc6)

In topic tour:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e55cbad4-1347-441f-af7d-6d30726243ce)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4f27a282-ac87-4299-a41b-226a38331fb2)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish removed the items you marked
