### ISSUE TITLE
TOPIC: Header image loads very zoomed in, no way to resize

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#525]
Should it automatically show as much of the image as possible? In this case it's not usable: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ae1cbcfe-c995-46c7-8c66-b863a80f1e7c)

**Comment by anettlinno** [comment]
Triage 96. 
We don´t have a good solution how to fix this issue now. @kevincrepin we were thinking that maybe we should provide people approximate sizes of the image that would fit in the image "box". Can you provide us, what the ideal image resolution would be?

If you agree with this idea, then we should add this (text) somewhere in the design as well :)

**Comment by anettlinno** [comment]
Pinging @kevincrepin  :)

**Comment by kevincrepin** [comment]
Until we add a widget that allows you to crop, resize and reposition I guess we'll do it with text :)

![Screenshot 2024-01-26 at 09 57 17](https://github.com/citizenos/citizenos-fe/assets/26792281/905b3827-0926-4767-87be-70fd1503dd56)

**Comment by ilmartyrk** [comment]
@kevincrepin your example image is for a group, but I added the text you suggested like this
![Kuvatõmmis 2024-01-26 235224](https://github.com/citizenos/citizenos-fe/assets/19904307/84aa17e9-885a-4cbe-b71c-32c203e72c8a)

**Comment by ssin1901** [comment]
@ilmartyrk do we have a solution for this yet? We can also close the issue as the solution proposed by Kevin has been implemented.

**Comment by ilmartyrk** [comment]
@ssin1901 We can close as it is a duplicate already
