### ISSUE TITLE
GROUP: Adding photo to group not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#526]
Tried a couple of times to add a photo to an existing group, it appeared in the edit pop-up, but when I clicked 'Save changes' it wasn't there:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/77452c0b-3036-49a5-9ead-425c9ecb3a96)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is now fixed, please confirm
