### ISSUE TITLE
GROUP: No engagement numbers showing for my group

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#527]
This group one I made, the others made by other people all show the engagement numbers (including when it's 0), but for my own it isn't showing: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6e1c7c67-4040-4252-af27-b3081230595b)

**Comment by BeccaMelhuish** [comment]
Ah, I see it is showing up correctly on the dashboard, but just not in My groups / Public groups: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/af636b09-6bf3-42ba-97d3-f0644c245c3e)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is because of two designs for the group boxes https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=22%3A6187&mode=dev

**Comment by ssin1901** [comment]
@ilmartyrk but as per the Figma, the Public group that was joined should still display a title and a date. At the moment it doesn't (see screenshot)

<img width="1407" alt="Screenshot 2024-02-06 at 14 22 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6e5de0be-c810-45fd-a775-a765312db38b">

**Comment by ssin1901** [comment]
@ilmartyrk currently there is no date as per Figma. Can I move this to Phase 2 though?
