### ISSUE TITLE
GROUP & TOPIC: Drop down lists should respond to letters on the keyboard

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#528]
For these lists on both topic creation and group creation, pressing a certain letter should take you to that place in the list. E.g. pressing E to help you quickly find Estonia :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8537bb81-8a71-43d2-b89b-e86784309da4)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno added a fix for this

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish tested and keyboard shortcut didn't work in Safari or Chrome.

**Comment by ssin1901** [comment]
Tested and working in Google Chrome. Closing the issue.
