### ISSUE TITLE
GROUP: Country list not alphabetical

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#529]
This one is in 'Create group' settings:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/68e66fde-dfae-4757-9046-ddd4c06f0b73)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed

**Comment by ssin1901** [comment]
Closed as it is working now (see screenshot)

<img width="1357" alt="Screenshot 2024-02-04 at 15 58 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/031a1520-3bb7-47d4-8a0c-121ff779aba4">

**Comment by ssin1901** [comment]
Closed as it is working now (see screenshot)

<img width="1357" alt="Screenshot 2024-02-04 at 15 58 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/031a1520-3bb7-47d4-8a0c-121ff779aba4">
