### ISSUE TITLE
DISCUSSION: Topic -> argument generating doesn't work properly (the text box doesn't extend to fit all written text)

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe#535]
**What is the problem?**
When a user joins a topic and wants to add an argument, the text box doesn't adapt to text length and one doesn't see some of the text they're writing. This is making the participation very uncomfortable. This happens after about 1000 characters (allowed amount of characters is displayed to be 2048.

![Screenshot 2023-12-08 at 16 52 27](https://github.com/citizenos/citizenos-fe/assets/126671955/7eaa700b-09c1-4516-b56a-bc40e5372815)

**Why is this a problem?**
It's not possible for the user to see what they're writing (fully).

**Possible solution.**
Make sure the window adapts to text length when there is more than 1000+ characters.
@ilmartyrk (FYI @anettlinno )

**Comment by ilmartyrk** [comment]
@MeelikaH fixed the issue

**Comment by anettlinno** [comment]
@ilmartyrk I copied very long text in argument box and our system only allowed me to insert 2048 characters (which is correct). But when pressing on "Add your argument" then nothing happens (argument is not being posted). Later I saw the error message which is on the blurry background and not recognizable and seeable: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/82f9fb0c-074c-4321-ad63-7c948546b009)

After I deleted some characters, I was able to post my argument. 

AND when inserting text manually (no copy-paste), then after clicking on the "Add your argument" button, I received two error messages: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/f5ceef8c-fc19-438a-a008-c5f1f9262863)

**Comment by ssin1901** [comment]
@anettlinno @ilmartyrk closing as works perfectly now. 

The extra text is simply truncated (see screenshot1) to fit the 128 character limit for the title and 2042 for the body copy. System correctly displays the truncated text (see screenshot2).


<img width="1356" alt="Screenshot 2024-02-04 at 15 24 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b8a71654-1cf5-4422-bee5-ee21fdae8235">

<img width="1359" alt="Screenshot 2024-02-04 at 15 26 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d35e722e-3a4b-4564-84dc-a1e048a68823">
