### ISSUE TITLE
INVITE & SHARE: Missing rights for invites 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#537]
And should social media sharing buttons be there too? (As on current platform?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d42c911e-aabf-4547-88c5-1a9c858b3f20)

**Comment by anettlinno** [comment]
Triage 99. @kevincrepin we would need you magic here please :)

**Comment by kevincrepin** [comment]
Added in the designs.

Desktop:
![Screenshot 2024-01-31 at 10 29 22](https://github.com/citizenos/citizenos-fe/assets/26792281/49a433aa-de45-4aa4-8f9e-e86115be6356)

Mobile: 
![Screenshot 2024-01-31 at 10 30 16](https://github.com/citizenos/citizenos-fe/assets/26792281/7a218aa7-b0c7-42db-b024-352455d49eb3)


@ilmartyrk Figma: Share & Invite modal https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=524%3A62243&mode=design&t=mGZWYhdhylxuJwCW-1

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the dropdown to topics and groups. Also updated the code behind join buttons for public topics and groups, now clicking join button will give users read permissions. Previously they used the join link, and got permissions that the link had, this would be really bad in case admin wanted to share the join link with admin permissions to a smaller circle of users.

**Comment by ssin1901** [comment]
@ilmartyrk I am a little bit confused about the issue here. It seems that the interface has been updated (screenshot1) and matches Kevins design. Can we close this issue? 
<img width="1297" alt="Screenshot 2024-03-05 at 16 21 55" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8a29b6fc-6b86-4c51-a4b4-d1069c8bc700">

**Comment by ssin1901** [comment]
@BeccaMelhuish I want to close this issue. Could you provide a bit more information about what is missing (based on my latest screenshot).

**Comment by BeccaMelhuish** [comment]
@ssin1901 based on the screenshot it looks correct to me :) 

I didn't follow what @ilmartyrk meant here though - I get a bit confused at this point too: _Also updated the code behind join buttons for public topics and groups, now clicking join button will give users read permissions. Previously they used the join link, and got permissions that the link had, this would be really bad in case admin wanted to share the join link with admin permissions to a smaller circle of users._

Also @ilmartyrk I'm wondering about the rights assigned via the QR code - are these also based on whatever the user has selected here in the section above? As if so I don't think it's clear in the design and we might need Kevin to revisit it? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0263da3a-2116-46d8-9747-3c6f8503f574)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish yes the QR code is made from this access link. 

And for explanation on what I meant for my previous changes is;
Only way to join topics without invite e-mails was to use this generated access link with access level chosen from the dropdown. So I originally used the same link behind the "Join topic" button for public topics, but then I understood that this is a bad solution as it would possibly grant any random user admin permissions over the topic, so I created a new join topic API endpoint that will allow users to join public topics using the "Join button" and only allowing read permissions in this case.

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish I am closing this for now, please re-open if needed.
