### ISSUE TITLE
MANAGE PARTICIPANTS: Remove "participant" role from co-editors

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#539]
**What is the problem?**
When clicking on "Invite co-editors" in published topic view (under the drop-down menu)

<img width="182" alt="image" src="https://github.com/citizenos/citizenos-fe/assets/45175679/160d38fe-25ce-4504-8fe4-a08c1024fb4a">

there are participant, editor and admin roles, but should only be admin and editor roles. 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/118e077a-632c-45cc-81f4-f66f8b51647e)

**Why is this a problem?**
Co-editors must have an access to topic editing feature.

**Possible solution.**
Please fix.

**Comment by ilmartyrk** [comment]
@anettlinno replaced with invite co-creators dialog as in topic creating flow instead, so it should be fixed
