### ISSUE TITLE
DB: misleading text in voting creation

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#549]
**Add a category to ticket heading for easier sorting**

**What is the problem?**
If a User choses to create voting topic then we say that "no pro/con discussion available" which is misleading, because it is available.

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/3fc6781c-7d25-4872-a964-55952551b567)

**Why is this a problem?**
Misleading to Users. 

**Possible solution.**
Please remove this from voting option texts.
@BeccaMelhuish

**Comment by ilmartyrk** [comment]
@anettlinno FIXED

**Comment by anettlinno** [comment]
Closing issue as it is fixed.
