### ISSUE TITLE
GROUP: topic added into the group is without header picture

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#550]
**What is the problem?**
I added excising topic in a group and it is displayed without header picture:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/7e19e308-d150-4ad7-b230-5a380be87863)

**Why is this a problem?**
Please display topic header picture in group.

**Possible solution.**
Please fix

**Comment by ilmartyrk** [comment]
@anettlinno this is fixed

**Comment by anettlinno** [comment]
Tested and works nicely. Closing the issue.
