### ISSUE TITLE
TOPIC: Unable to open  attachments in topic

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#552]
**What is the problem?**
I added pdf and image attachments to the private topic and after publishing the topic I´m unable to open attachments. I see them like that: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/b583ceb5-8396-464d-aa7a-91cc7e665a26)

**Why is this a problem?**
Unable to open attachments after uploading them.

**Possible solution.**
Please fix.

**Comment by ilmartyrk** [comment]
@anettlinno should be fixed now,. FYI also with attachments it would help to include what upload method was used as uploaded files worked fine, but this error happened with google drive files. Attaching files from other sources will not upload them to our server but will provide a direct link to that file location depending on the upload option used :).

**Comment by anettlinno** [comment]
Roger to that @ilmartyrk ! :)) 

Tested and works nicely. Closing this issue.
