### ISSUE TITLE
TOPIC: error message when uploading image from computer

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#553]
**What is the problem?**
As a User, I wanted to upload jpg image from  my computer, but got this error message: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/589dd8fd-dd99-4665-9b3a-c5a07edb3426)

Same error message comes when uploading pdf file.

**Why is this a problem?**
Unable to upload files.

**Possible solution.**
Please fix.

**Comment by ilmartyrk** [comment]
Checked the issue, it was related to the changes in file type validation. Should be fixed now

**Comment by anettlinno** [comment]
Tested. Works nicely, thank you! Closing this issue.
