### ISSUE TITLE
LOGIN: Login button does not respond (when wanting to join public group in logged out view)

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#555]
**What is the problem?**
I was logged out from the platform and wanted to join public group. After clicking "Join group" button, I inserted my email and password, but the "Login" button did not respond. 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/cc199594-0df7-486a-8fa2-a4653280bb76)

After clicking around, I was suddenly logged in, without knowing it. I could join one group without showing to be logged in: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/1f0572f2-fcfd-4888-ba1f-2fe4980963dc)

Very weird behavior and should be tested properly.

**Why is this a problem?**
Unable to log in or if logged in, User don´t know that one is logged in.

**Possible solution.**
Needs some testing and playing around, as every time gets different behaviour.

**Comment by ilmartyrk** [comment]
@anettlinno the issue was with redirecting after login I made big changes to the previous code we used to have for that so that it would always work, it should even work after registering. So fixed the redirect link and should now work properly

**Comment by anettlinno** [comment]
Tested and seems to work nicely. Closing this issue.
