### ISSUE TITLE
Topic: Joining public topic doesn't do anything 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#556]
It doesn't do anything in two ways (as shown in the video): 

- I can add an argument with or without joining the topic (so I wonder what the point of joining is? I guess to get notifications maybe?). 
- After I have joined, it still says "Join topic". 

https://www.loom.com/share/968ef973fac54ec3aaad26af374fc89c?sid=cf51684e-be46-4e45-a051-ab18a976d0be

**Comment by ssin1901** [comment]
@ilmartyrk tested and "Join" becomes "Joined" and the user sees a menu to "Favourite" (see screenshot) which I guess justifies need to join the topic. I am closing this topic but I have another issue with the voting for which I will create a separate topic.

<img width="1432" alt="Screenshot 2024-02-09 at 17 12 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a9a3f2d8-2889-43e1-8ad3-3f54fd1c3a5a">
