### ISSUE TITLE
INVITE & SHARE: email invite is not working

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#557]
**What is the problem?**
Email invite in topic is not working. After entering email address, anything happens:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/b40729d6-3cf7-4713-8a4f-b126445c4d33)

From the pop-up window:

- [ ] Character limit number is missing
- [ ] "Search" icon and text is missing
- [ ] Too much empty space below the "Search" box

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/287871bd-b517-4881-9e45-4ecbbb586442)

In designs the same window is: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/8af92282-9945-4050-947f-9fe842cae922)

**Why is this a problem?**
Unable to invite people via email or user name to a topic.

**Possible solution.**
Please fix.

**Comment by ilmartyrk** [comment]
@anettlinno my bad copy-pasted the code over with group invite content, it's fixed now
