### ISSUE TITLE
TOPIC: "Read more" in topic view is not working

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#558]
**What is the problem?**
In topic preview "Read more" button is not responding: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/0cce435e-e68c-4cc8-b54d-0929f97a3ed1)

Should be: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/a4f7ebb4-c8d4-4006-92d9-5dd0a43d9e17)

**Why is this a problem?**
Unable to see whole text in preview.

**Possible solution.**
Please fix.

**Comment by ilmartyrk** [comment]
@anettlinno posted a fix for this issue, still there might be times where after editing topic content the new content is not loaded before switching to preview tab

**Comment by anettlinno** [comment]
Tested and it worked nicely. Closing this issue.
