### ISSUE TITLE
Topic: Delete group buttons not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#559]
In 'Create topic' flow, when user accidentally added the group (to which she wanted to add the topic) 4 times, the 'delete' buttons to remove the 3 extra ones didn't work: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/24109c76-c41e-4d58-8c93-77cb9114fd2c)

**Comment by ilmartyrk** [comment]
Should be fixed though this needs a better solution in the future with some API update as we don't currently have API query param to filter out the groups where user has admin permissions. Currently did it on FE side and probably isn't an issue for most users.

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish the delete button at least seems to be working (see screenshot1 and screenshot2) and the removed user did not receive an invite. Closing for now.

<img width="1406" alt="Screenshot 2024-02-04 at 17 30 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b5aa1b30-2024-4a09-8cd4-c50f8afa8fdb">

<img width="1403" alt="Screenshot 2024-02-04 at 17 30 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ffcd9466-e7f1-48db-8860-ec21e380f04e">
