### ISSUE TITLE
Group: 'Add topics to group' - no message when click it before searching

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#560]
(Something from the UX testing that is more about general good practice than an individual's experience, so I will report already despite only having done 1 test): 

When a user clicks on this button (below) "Add topics to group" without having actually selected any topics to add there should be a message to that effect. I'd suggest: 

"Please choose a topic to add". 

Presumably in one of those little red boxes that appears around an empty field when submitting? 

And in any other places where there is a button that becomes 'dead' it the user hasn't done a certain action, there should always be a message explaining why the button isn't working - maybe we can keep an eye out for any other such places? Tagging @kevincrepin in case he has any input on this too or it needs any design guidance :) 

![image](https://github.com/citizenos/citizenos-web/assets/61320526/8617ea11-2faf-4a76-9393-6a7f06a389f7)

**Comment by kevincrepin** [comment]
Yes, we need to validate this, but it's not really a field validation so I don't think we need to highlight the search in red (normally it means smt has been entered wrongly). 

So I would just give this notification:
![Property 1=Validation](https://github.com/citizenos/citizenos-fe/assets/26792281/9b041b14-ea8a-41ca-afea-b8ad2c37c7a9)

**Comment by BeccaMelhuish** [comment]
Perfect thanks Kevin! 

And please anyone while using the test site, keep an eye out for any similar situations where a button is currently just "dead" if they don't fulfil the required prior action elsewhere, so we can add similar such notifications if so :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the notification to add topics to group and add topic to groups dialogs

**Comment by anettlinno** [comment]
Tested and works nicely. Closing this issue.
