### ISSUE TITLE
Voting: Able to edit vote settings and options after vote has started

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#561]
I started a vote, and checked to see if I was still able to go in and edit its settings. I was able to, but understand this shouldn't be allowed? 

I tried voting, then checked to see if I could change the vote options. I was able to change the vote options I had voted for to something I hadn't voted for. E.g. I voted for 'Yes'. I then changed the option 'Yes' to 'Hello'. It then showed that I had voted for 'Hello'.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I've fixed the issue from the API side also started adding disabled classes to parts that you cannot edit as we still allow changing of the deadline and reminder time while the voting is going on.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think this is fixed now

**Comment by BeccaMelhuish** [comment]
Though I see that "Edit topic" has been completely removed, is that correct - that it's not possible to edit anything at all once the vote has started? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a3246545-b3ee-4463-9ab0-f73924518821)

If so, how will we communicate this to users, as at the moment it's just confusing that it has vanished? (They won't necessarily realise why it's happened, and so just be a bit lost/annoyed). 

Having "Edit topic" greyed out rather than just gone would definitely help, but am wondering if it's enough. @kevincrepin :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin Edit topic button is there for the admins as they can update the deadline and topic settings. Members with edit permissions cannot do any actions in the edit view anyway as the topic content is locked, they don't have permissions to edit the settings and vote settings so I removed it from the menu. I could add it back in with the disabled style, but not sure if it is the best solution

**Comment by anettlinno** [comment]
@BeccaMelhuish this should be fixed now, please check and close the issue if yes :)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk flow seems to be fixed. 

1.In topic where voting has started, topic admin gets this message (screenshot1).
<img width="1404" alt="Screenshot 2024-02-05 at 10 52 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8c938f5c-36b9-4004-840f-372477ccf375">

2.They can only change topic settings and voting deadline, and not amend the options or the type of voting (screenshot2). 
<img width="1212" alt="Screenshot 2024-02-05 at 10 53 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e1f4aa4b-0127-4c03-9585-d6f90127b65e">

3.The topic admin can also edit their own vote, change the deadline and close the voting from the manage menu near the voting options (screenshot3).
<img width="1206" alt="Screenshot 2024-02-05 at 10 53 40" src="https://github.com/citizenos/citizenos-fe/assets/72747107/80c6d1ea-44c7-4462-ae1f-f542b664ebda">

4. Whether a topic started out as a Voting topic or a Discussion topic, nobody but the topic admin sees the option to Edit once the voting has started (see screenshot4).

<img width="1209" alt="Screenshot 2024-02-05 at 11 04 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bfc0c6c6-04c9-4e50-81a0-abfd8d8ad042">

It would be great if we could close this issue, and open up a new UX issue to discuss related issues.
