### ISSUE TITLE
Topic: when editing vote topic it says 'Publish' not 'Save'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#562]
Instead of 'Publish' here it should say 'Save changes' (or whatever is in the design, haven't checked, but shouldn't be publish). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a452f06d-8670-43fa-a231-8ae762707900)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added  a fix, when topic is still in draft there are two buttons, save as draft and publish, but when published there is only save changes
