### ISSUE TITLE
INVITE & SHARE: invalid email addresses do not give error message

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#566]
**What is the problem?**
When inviting people to the group and inserting invalid email address, our system just accepts that and do not give error message: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/5662da3c-5dad-4dba-ac28-f98536e1e61e)

**Why is this a problem?**
Admins are not notified about invalid email addresses and some people might not receive invitations to the topic because of that.

**Possible solution.**
Please show error message if invalid email address is being inserted.

**Comment by ilmartyrk** [comment]
@anettlinno if by invalid email address you mean the address in this image then by definition it is valid e-mail address format. There is no proper way to validate an e-mail address other than actually sending one out and receiving an error if it didn't reach the person it was addressed to. If the e-mail format is valid, but e-mail address is invalid meaning that there is no account connected to it on an external e-mail service the invite will stay in the invited members list and admin can check that to validate if a typo has happened.

**Comment by ssin1901** [comment]
@ilmartyrk @anettlinno it works with invalid email formats i.e ones with missing or multiple @ symbols or invalid characters. See screenshot 
<img width="1411" alt="Screenshot 2024-02-01 at 14 21 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/019f50cf-0d78-435e-8a62-d7d8bd035ff3">

Closing the issue.
