### ISSUE TITLE
IVITE & SHARE: enter removes email address

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#567]
**What is the problem?**
When typing email address on the text field in topic invite and pressing enter, then email disappears.

Step 1: writing an email address:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/fb151c3c-3d7b-4f01-b979-3fd4c1746262)

Step 2: after pressing enter:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/ea912d3a-e06b-47da-883e-c040c3d6c973)

**Why is this a problem?**
Pressing enter is intuitive way of inserting email address (in a case where User must write whole email address -- I think in other cases it worked)

**Possible solution.**
Enter should insert email address

**Comment by ilmartyrk** [comment]
@anettlinno I could not replicate this issue, pressing enter always added the user to the list for me, it didn't matter if it was a registered user or a new email address. Can you please add more information

**Comment by anettlinno** [comment]
Could not replicate it either. It is working now. Closing this issue.
