### ISSUE TITLE
Emails: Reminder to vote - should include vote deadline

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#569]
I don't remember seeing this one in my email copy review, but shouldn't it included the vote deadline, instead of the number of votes collected? (I don't think the latter is that relevant to participants, that's more for admins to monitor?)   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f1fa8284-816c-4f3a-a2eb-8aa990936153)

**Comment by ssin1901** [comment]
Latest vote reminder included the vote deadline (see screenshot)

<img width="1126" alt="Screenshot 2024-02-19 at 15 21 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1af490e7-faf4-4e74-8292-321f04c149c1">

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish if vote has deadline then we include it, if not it just calls users to cast their votes
