### ISSUE TITLE
TOPIC: "Add to group" button not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#571]
Currently nothing happens when you click it: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/266c5164-0ae6-47ba-b6df-e78ba4b250da)

(Is something that came up in the UX test today, would be good to have fixed before the next one if poss :))

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the missing view

**Comment by BeccaMelhuish** [comment]
Thank you! 

Can the texts be edited to this though:

"**Add topic to a group**

When you add a topic to a group, all members of that group will have access to the topic.

Button: Add topic to group"

(I realise there sometimes might be groups plural, but I think it's OK). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3b5959b2-4827-45b9-9e97-6728d2e4d004)

**Comment by BeccaMelhuish** [comment]
Will edit myself now I have the new strings :)
