### ISSUE TITLE
TOUR: Repetitive topic tour pop-up getting in the way in testing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#572]
In the UX test today, the user didn't close or skip the tour pop-up which meant that important parts of the topic were obscured, like in the screenshot shown at the end. It therefore was hard to test if she would have found the thing she was looking for, had the tour pop-up not been in the way. (She didn't find the invite/manage participants box, but it was completely hidden by the tour). 

We currently have the tours popping up every time you go into the topic (which won't be the case in the live version). This has been very useful for testing the tour ourselves, which we might still need to do, but makes the testing a bit unrealistic. So I'm thinking there are 2 options: 

- We don't have the tours appear repetitively every time you go into the dashboard/a topic, only the first time after logging in.  
- We have the tour pop-up on a timer, so that if a user hasn't closed the tour pop-up themselves, after say 5 seconds of entering the topic, it closes itself. (Is this good practice anyway? Hopefully @kevincrepin has some advice here)  

I also wonder if we shouldn't have a way to take the tour if you have accidentally closed it, or you want to take it again? This is quite common practice I think - I've definitely seen this in other tours? And would solve part of the problem here too. @kevincrepin what do you think? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/19c8e537-0605-47d3-9274-6c79f4785c08)

**Comment by kevincrepin** [comment]
I think this is anyway the idea that the tours are not always visible, but for testing's sake Ilmar made it like this now – correct me if I'm wrong, @ilmartyrk.

I like the idea of having a timer, but maybe instead of removing/hiding entirely, the tour could just minimise – either after the set time or after user interaction. Worked it out here: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=596-73565&viewport=99%2C-15981%2C0.5&t=ifHZ2E5EY44R3inf-1&scaling=scale-down&starting-point-node-id=596%3A73037&mode=design

This way it's still accessible as well. For the dashboard walkthrough need to think about something because, yes, I agree the tours should still be accessible, but need to think from where you can start it again. Don't want something always visible in dashboard or topics even after you've already seen it and know everything...

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin added the proposed solution from Kevin

**Comment by BeccaMelhuish** [comment]
Ah @ilmartyrk, I don't see it though? It's still the same for me - not minimising or on a timer? 

Should have this little 'X' to close now too :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/08a9d380-c360-42ee-b5a1-8d6583391171)

Also, @kevincrepin how many seconds should we have it close after, maybe 5 is enough, seeing as it'll stay there?

I wonder if it being there all the time is a bit annoying/space consuming, especially once someone really knows their way around, but I think it works well for the testing phase. We can see how it goes and maybe re-think if needed!

One problem that needs some thought too, we have the HC bubble here on the real version:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/368277bd-6892-43bd-a1bb-58b66dbc016c)
 
And yes, hard to think how it could work for the Dashboard tour always being accessible.. I guess maybe it can be incorporated into the Help Centre, an option to take the dashboard tour on the HC home?

**Comment by BeccaMelhuish** [comment]
Summary of conversation with Ilmar on Slack :) 

- I was checking redesign. not test. - oops
- He'll add a 5 second timer for it to minimise (we can see how 5 goes, and always make it longer if needed)
- It'll only open the first time a user goes into their first topic, after that will always be minimised (in that and any other topics) 
- We should have the whole tab clickable not just the + (in case HC bubble obscures it, and for general ease of opening).  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4d0b24b3-a7ef-4cef-b05e-bdc5dd5db2f8)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the items we discussed, also added the missing dialog for mobiles and tablets.
@kevincrepin for mobile and tablet views, how the tutorial should be minimized?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk reopening this one as the tours are still popping up multiple times on mobile it seems

**Comment by kevincrepin** [comment]
@ilmartyrk A while ago we created this for the tutorial: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0---Design?node-id=11064-30687&t=jOdHzsGOP0tTzVlT-1

Idea being that you can close the tutorial and in the top of the screen there is this question mark icon which is the help center. if You're on a page that holds a tutorial, the help centre would indicate this on its first page.

![Screenshot 2024-07-02 at 15 49 58](https://github.com/citizenos/citizenos-fe/assets/26792281/25498e6b-e085-4bb6-8dde-dc4f08aa7665)
