### ISSUE TITLE
TOPIC: Description is missing no. of characters

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#574]
In the "Create topic" flow: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a56bed2f-a1fd-4edf-ae82-92a19fdf3989)

**Comment by ssin1901** [comment]
@ilmartyrk the Figma mentions that 5000 characters is the limit. Is that still applicable?

<img width="738" alt="Screenshot 2024-02-19 at 15 24 40" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7b048ee9-09c3-4acb-9946-36bf1c372f57">

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish we don't have a limit for the content, closing this issue
