### ISSUE TITLE
Topic: Topic intro field only shows 2 lines at once 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#575]
Here the user has written 3 lines of text, and there are scrollbars showing just 2 lines at a time. This feels a bit awkward and cramped - should it be like this or it's a bug? 

Ideally it would expand so the user can see all the lines they have written, while they are writing it (and afterwards), and not have to scroll up and down the tiny box like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a1357067-0a39-4a0a-80b8-9a6bda7080e5)

**Comment by ssin1901** [comment]
@BeccaMelhuish the toolbars were not causing any problems for me (see screen recording). Closing the issue.


https://github.com/citizenos/citizenos-fe/assets/72747107/df5d21bd-15c7-41ae-b05b-21c2c20d8ec7
