### ISSUE TITLE
TOPIC: alignment of texts in 'Description' box

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#577]
When a user was writing in the description box as below, the alignment of the start of each line was messy. 

From what I could tell, she seemed to only be pressing enter (not enter and then tab, or adding any spaces), but it was automatically indenting the lines with spaces at the beginning of each line. 

Seems to be a bug? Let me know @ilmartyrk if you'd like to see a clip of the video to get a better sense of the problem, I can try to cut out the relevant bit. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/54954742-113c-436a-be15-374b771caadb)

**Comment by BeccaMelhuish** [comment]
@ssin1901 I'm thinking this has probably been fixed with the Etherpad update? Would you mind testing, and send it to 'soon' if not fixed? :)

**Comment by ssin1901** [comment]
@BeccaMelhuish screenshot 1 is Preview view and screenshot 2 is Published view 

This particular bug seems to be fixed, but I see another one with the gap between heading and the paragraph text. Can we move this to Done?

<img width="1215" alt="Screenshot 2024-11-05 at 15 49 28" src="https://github.com/user-attachments/assets/6a4d18a0-daf2-4bfc-bfda-2c36b444af9f">

<img width="1219" alt="Screenshot 2024-11-05 at 15 49 40" src="https://github.com/user-attachments/assets/1360e30c-4342-46b8-9007-887cdc1c5e5c">

**Comment by BeccaMelhuish** [comment]
@ssin1901 OK great, I think we can close then! Have mentioned the gap in this [related issue](https://github.com/citizenos/citizenos-fe/issues/1181) here which groups the formatting inconsistencies :)
