### ISSUE TITLE
Topic: Bug - topics landing already scrolled down a bit

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#580]
When user (in UX test) was going into her topics, it was landing already scrolled down a bit: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3c485209-17c4-41e5-8dcc-a093e99c9080)

So this important part wasn't visible, unless she noticed and scrolled up to see it:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dd5f0a04-62dd-43d1-9227-607fc5661ca0)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should be fixed now
