### ISSUE TITLE
Group: Bug - wrong view after creating group

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#584]
After clicking "Create group and send invites" I saw the group flash up briefly, with a "Your group has been created" message at the top, but then a second later I was taken to this view instead: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dca3fa17-8921-4dea-b0c8-e329bfbf2c9e)

**Comment by anettlinno** [comment]
After clicking on "Create group and send invites", User should land on the group´s view as is in the designs: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/9599681f-0144-4206-8a75-bdc11f23d0a9)

**Comment by anettlinno** [comment]
Triage 98. Est. dev time 15 min. Sending it to do.

**Comment by ssin1901** [comment]
Closing because the view seems to be corrected (see screenshot)

<img width="1405" alt="Screenshot 2024-02-05 at 10 35 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/aa3ec01f-f979-49e2-aa2b-02c1c174c192">
