### ISSUE TITLE
AF: number of notifications still showing after viewing them

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#585]
This number should disappear once you've opened the Activity Feed and seen the (in this case 2) notifications for you? (Like with Facebook, Slack, etc.) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/24f7a3e5-b66e-4b06-b782-b95da7f98521)

**Comment by anettlinno** [comment]
Tested and notifications count starts all over after seeing them, @BeccaMelhuish.  Closing this issue now and if it´s not working for you as expected, please reopen.

I discovered another issue while testing that #685

**Comment by BeccaMelhuish** [comment]
Reopening as it's not quite working for me :) 

When I look at my activity feed and then close the feed again the notification I just saw are still showing in the number. 

E.g. There are 3 notifications, I look at them and then close it, there are still 3. 

If I reload the browser, there are 0, but it doesn't update there and then (which it should to be working as expected and as would be effective).

**Comment by ssin1901** [comment]
@BeccaMelhuish tested and after reloading it does work (see screen recording). However, there are a number of places where updates don't happen without refreshing, and that is important to resolve. 

https://github.com/citizenos/citizenos-fe/assets/72747107/f43875d2-2fd4-4c63-a5e1-499ba971a6ab

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 automatic reload is expected without manually refreshing , fixed the issue
