### ISSUE TITLE
Groups: Issues with group card summaries

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#586]
A few issues with the way these cards are displaying (this is from public groups):

- Left-hand one is missing the info
- All of them have ideation showing, but we don't have that in phase 1
- All of them are showing the same number for all 3 icons, e.g. 1 1 1, 2 2 2, etc. (which is incorrect).
- Viimsi group seems to be displaying twice (I believe there was only 1 created)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/49384cec-9726-4714-873b-d29def5458c9)

**Comment by anettlinno** [comment]
Triage 100. @kevincrepin we would need your input here, please. Shall we remove discussion/voting/ideation icons or remove only ideation for now (until we´ll implement that)?

Groups that are displayed twice is fixed.

**Comment by ilmartyrk** [comment]
related https://github.com/citizenos/citizenos-fe/issues/644

**Comment by kevincrepin** [comment]
I would just remove the ideation stats for now, but keep the discussion/voting.

**Comment by ilmartyrk** [comment]
@kevincrepin for me it looked weird with only 2 items that is way I added the follow-up icon and count

**Comment by ssin1901** [comment]
I think it is okay for now, closing for the time (see screenshot)
<img width="1440" alt="Screenshot 2024-03-27 at 13 16 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/aca8ab31-f93f-480c-9df6-c5673abb7c41">
