### ISSUE TITLE
Tour: Discussions part of topic tour is off the screen

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#587]
When I get to this bit, the bit it's talking about is off the screen. It should scroll down a bit so you can see it? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/78b1d9a5-700e-4c7d-ac47-2fec1e64b560)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
@ilmartyrk this one seems to still not be working optimally (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/0f3aa810-8b21-42f3-9652-fdecd2c54e7b
