### ISSUE TITLE
Topic: Odd alignment

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#588]
Topics have started showing like this for me - is it a bug or intentional? Feels quite odd to me (and not as per the design, but maybe something has changed?).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e533a158-30c3-4ff2-b11d-01a1c0aa6d7d)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is caused by the window width, the content area is fixed to maximum width and if screen gets wider the sides will be emptier
