### ISSUE TITLE
Topic: Topics in voting phase should open in Vote phase tab

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#589]
Currently topics in voting phase open in discussion phase (when you first go into them), but I think they should open directly in Voting phase. 

(Obviously this is related to the phases issue we'll discuss in the New Year - as in the design there wouldn't be an empty discussion phases for it to confusingly open into like it has in this case below. But I think for now opening any in vote phase directly in the vote tab would help). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/657323de-7f52-4e4c-8270-1dbabed93e70)

**Comment by BeccaMelhuish** [comment]
Have added "pre UX tests" label, though we may have a new solution for the phases issue before next tests anyway (this would just be in case we don't).

**Comment by ilmartyrk** [comment]
Added a fix when user clicks on the topic box it will take them to the voting phase though might have to add similar solution for it to work in other places too

**Comment by anettlinno** [comment]
Tested and works nicely. Closing this issue.
