### ISSUE TITLE
Topic: Match voting topic phases to design

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#591]
As per Zoom discussion today, remove discussion phase from 'voting topics' :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/893cb40b-dbf3-4ad1-87f1-153ccddb976c)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0b0bd016-ade3-42f7-befe-095f4b46ae51)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by BeccaMelhuish** [comment]
@ilmartyrk something came up in yesterday's test that I guess must be related to this, so will add it here. It went like this: 

He created a discussion topic. 

When it opened, it opened as a voting topic:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4660b5b0-e05f-4233-b0b6-b278230e1f37)

I explained what had happened (that it was a bug and it's opened as a voting topic). 

He then went to 'My topics', and it was showing in there as blue (for discussion topic): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5cadb641-1a41-42af-9a40-61d5ea725c38)

When he went into the topic it was now showing as a discussion topic, so we were able to carry on :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/208b53a8-3966-44ac-a487-492fdd46dc0d)

**Comment by anettlinno** [comment]
Triage 98. Needs some investigation. Est inv. time 15 min. Sending it to do.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish can you provide more info, what fields he filled etc. I didn't manage to replicate it

**Comment by ssin1901** [comment]
@ilmartyrk I also had a voting topic in draft get converted to a discussion topic #716

**Comment by ssin1901** [comment]
Discussions have been removed from Voting topics so closing this issue (see screenshot)

<img width="1162" alt="Screenshot 2024-02-06 at 14 30 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/10d3b6fd-d7a0-43c0-916a-d55a6cf3494f">

A separate high priority topic has been opened for the second issue #716
