### ISSUE TITLE
Topic: Create buttons that directly create a discussion topic - how to allow choice?  

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#592]
Hi @kevincrepin, there is this button below that currently opens straight to a discussion topic creation, and there is also a similar one in the activity feed that presumably does the same (wasn't able to test it). 

Discussed with @anettlinno and @ilmartyrk today and we'd like your guidance on how this should work, so that users are given the choice of whether they create a discussion topic or voting topic, as they would if creating via the main menu :) 
 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6b246a6f-e6da-46d7-94ef-b8a20aec77d5)

**Comment by kevincrepin** [comment]
Let's reuse the same component, without the group creation option: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=11017-102391&viewport=-20048%2C-27506%2C1&t=KwSiebLAtbnFq0KK-1&scaling=scale-down&starting-point-node-id=11017%3A102391&show-proto-sidebar=1&mode=design

![Screenshot 2024-01-08 at 12 04 29](https://github.com/citizenos/citizenos-fe/assets/26792281/0d2a6ecf-72b8-409c-8e53-828e96376e5b)

**Comment by BeccaMelhuish** [comment]
Nice, thank you @kevincrepin! Will this work for mobile too? 

@ilmartyrk this would be great to have for the Monday test if possible, to not cause to much confusion when they're trying to create a vote topic (as the test will be voting focused).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the menu

**Comment by anettlinno** [comment]
Tested and create menu is nicely added. Closing the issue.
