### ISSUE TITLE
Voting: Voting setting not displaying after initially setting them

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#593]
After setting the 'Vote settings' here and going forward to the preview step, when going back to the Vote settings tab it was blank. (And remained blank even after waiting and going back and forth to other tabs). 

I would need to check the recording, but I believe it happened in both voting topics he created.

Would be great to have fixed before next Tues, when the next test/pre-test call may take place :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/78572ce4-c049-443d-961d-01ac68c182e2)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should now be fixed

**Comment by BeccaMelhuish** [comment]
Thank you! It is for me so will close it :)
