### ISSUE TITLE
Voting: User wasn't able to download vote results

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#594]
There was no button for him to download: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/40a9b568-c775-4e5b-a274-47c11839b674)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should now be fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot)

<img width="1160" alt="Screenshot 2024-02-01 at 14 32 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/09638f6a-dd06-42bf-8075-c309d14fb02d">
