### ISSUE TITLE
Voting: Issues with vote closing and results download flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#595]
There needs to be different texts here depending on whether the vote has indeed closed because everyone has voted or not (or a text that works for both), as user was confused by it saying that 'everyone has voted', but only '1 / 2 votes counted'. 

(Happy to help with texts if needed).  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ffa70c1d-193f-4565-95df-8d0feff9d7b7)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish good you noticed that. Explaining what happened. We allow downloading vote results only when topic status is changed to follow-up or closed. This is because otherwise admins could possibly close the vote by changing the expiration date download results and then reopen the voting. This would mean that the vote results could possibly be manipulated in the long term or presented in the wrong way. Anyway I changed the behavior of the close voting button in the vote settings menu though we need new texts for when voting is closed because expiration date has arrived and results are not downloadable

**Comment by ilmartyrk** [comment]
I've added new texts for when voting is closed but results are not downloadable yet 
```
"HEADING_VOTE_ENDED_EXPIRED": "Vote deadline has been reached",
"VOTE_TXT_VOTE_ENDED_EXPIRED": "Vote deadline has been reached and voting is now closed. To download results start topic follow-up or close the topic.",
```

**Comment by BeccaMelhuish** [comment]
Ah this feels quite confusing to me, so I think will be even more so for users.. Does it need some thought from @kevincrepin about how the flow here should work?  

This text (screenshot below) says 'start topic follow-up' which I think most users won't understand, or 'close the topic', which is also confusing - close the whole topic just to get the results? And how? (I wouldn't know how to do this myself, and would worry it would be fully 'closing' it so it no longer was accessible).

I didn't think we still had this system of having to 'send to follow-up' before you can get results in the redesign? As I remember this is something that caused quite some confusion in users previously @anettlinno? It definitely doesn't feel very smooth/intuitive to me.. 

Is there a way around this, that we can make it much more straightforward for the user but prevent them from manipulating the results like Ilmar described above? E.g. once they have downloaded the results once, they are not able to extend the deadline? Would seem preferable to technically restrict them from the 'foul play' (in the probably very limited occasions that people try to) than make the process complicated/confusing for those just trying to get the results.. 

If this one could be a high priority to try and resolve before Monday 12.30 that would be perfect, as have got two UX tests where vote downloads will be an important part.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/64642ec4-567f-4aa2-8c3f-2a8d14707c74)

**Comment by BeccaMelhuish** [comment]
Linking this [this issue](https://github.com/citizenos/citizenos-fe/issues/594) in case it is related?

**Comment by BeccaMelhuish** [comment]
Also re this bit from @ilmartyrk: "_We allow downloading vote results only when topic status is changed to follow-up or closed. This is because otherwise admins could possibly close the vote by changing the expiration date download results and then reopen the voting. This would mean that the vote results could possibly be manipulated in the long term or presented in the wrong way._" I'm not sure I understand this as they can already see the results in the graph can't they(?), so not being able to download them wouldn't change anything? They could still see the result and choose to extend it to get the result they preferred, regardless of whether they have sent to follow-up or closed the topic (or downloaded the results)? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d0328540-e36b-49dc-9879-90ad755dd351)

I didn't fully understand this bit either: 
"_I changed the behavior of the close voting button in the vote settings menu though we need new texts for when voting is closed because expiration date has arrived and results are not downloadable_"
What vote settings behaviour is that regarding, and what texts are needed?

**Comment by BeccaMelhuish** [comment]
If I'm understanding the situation correctly (and I am a little confused here), then my proposal would be that: 

- As soon either all votes are in or the deadline has passed, the "Download voting results" button appears (with the relevant text depending on the way the vote closed).
- When you click it, you are asked to confirm: "Downloading the results means the vote will be permanently closed. Do you want to continue?" (Or similar). 
- If we want to prevent to possible foul-play Ilmar described above, we should also do this before results graph is displayed (i.e. you actively opt into viewing the results, and accept that viewing them means the vote is 100% over), if I understood that issue right? (Though how this would work for participants viewing the results I don't know.. Would mean they couldn't before an admin opts to display them - not ideal..) 
- We then make it technically impossible to extend the vote deadline once they've viewed/downloaded the results. That option is greyed out or whatever such UX Kevin prefers.

**Comment by kevincrepin** [comment]
I understand the confusion as I am also confused :)

When you download the vote results, does it also show who voted for what or is it pretty much also just the results as we anyway show? I don't remember this... If it's the same as we already show (no names) then I agree that by showing the results after voting "ended" we already allow the admin to do this foul play. 

I kinda feel all this could be avoided if the deadline is a hard deadline, with no possibilities to change it during or after. Gives less flexibility but on the other hand you can always set the deadline to 12.12.2124 if you want to...
The voting rules should be set and definitive before voting starts in my opinion, those rules should not be able to change anymore during voting... Gives too much flexibility to the admin to change according to how they want it.

If **definitely** we need to keep the option to change the vote settings then I agree with how @BeccaMelhuish outlines it above. I would then say that when the results are downloaded the entire vote settings are disabled (similar to how we currently disable topic text editing after going into vote).

**Comment by kevincrepin** [comment]
Will also put this here...

If – and that's a big if – we make deadlines not editable then we need to communicate this also:
![Screenshot 2024-01-12 at 10 02 09](https://github.com/citizenos/citizenos-fe/assets/26792281/de11dd2b-f2b7-4917-b0bf-dbf17fb472c8)

**Comment by BeccaMelhuish** [comment]
Thank you @kevincrepin!  

Yes it does indeed show who voted for what when you've downloaded, so I guess that's an extra level of possibility for foul-play, but even just them seeing which option had the most votes could be an issue if they are able to then extend the deadline after seeing them. 

What if we do allow changing the deadline (as it's quite feasible that they would want to for fair-play reasons, i.e. they simply didn't get many votes by the time they thought they would, so want to give participants an extra week to have their say, for example), but have it so that you can only edit the deadline _before_ the deadline has passed. Once the deadline has passed, the results will appear automatically, so they're not allowed to edit it beyond that point. But if it hasn't yet passed, and they haven't seen any results, then no problem to change it :) 

We could communicate this in this box as you suggested, but with different text e.g. "**You can only edit a deadline before it has passed.** Once it passes, you will see the results, and no longer be able to extend the deadline." (Maybe that's a bit long, we can tweak it if we go with it). 

Also, I've noticed what seems to be another connected problem, which is that we have these two options for closing a vote, but it's not mandatory to choose one or the other. I think it won't be clear to users, but I believe this means that if they haven't selected one or the other, then they will be able to close the vote manually (which I imagine is often the preference for people, as they can then be sure it is closing at the right time). So two things on this: 

- Do we need a 3rd option (or probably the 1st of 3 options, is my hunch) 'Close vote manually'? 
- And do we need some UX for how they will actually close the vote manually? As from what I understood from Ilmar above it's currently the case that they have to either 'send to follow-up' or 'close the topic' neither of which seems very smooth or intuitive, and I think is more current version UX than redesign version UX? Would be much clearer to just have a button: 'End vote', or something similar? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6d2485d1-b908-45a6-9db7-4bb5dd2379e3)

Have also separated out an issue to do with the 'All votes are in' option here, which is related but a bit of a tangent: https://github.com/citizenos/citizenos-fe/issues/641

@ilmartyrk is any of this related to the [issue here](https://github.com/citizenos/citizenos-fe/issues/594) where the user in a test couldn't download the results? 

Will change the title of the issue as it's broadened out to be about the vote closing and results downloading flow in general :) 

@anettlinno @ilmartyrk @kevincrepin if we could possibly make trying to sort this one out before the tests on Monday (12.30) that would be ideal, as I have vote-focused test (with two different users back to back) and am a bit nervous that the vote closing and downloading flow isn't really working at the moment.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @kevincrepin @anettlinno  admins can already close voting manually from the vote settings menu. As we don't have a "status" field in the database for the voting as we have for topic (inProgress, voting, followUp...) then initially closing the vote was done that I added the current time as the deadline time for the voting so it kind of solved 2 issues it closed the voting and also displayed the correct time as the end time. But as we didn't allow downloading results until the topic status was changed to follow-up I also updated this "Close vote" option to automatically  change the topic status to follow-up so that the download results option would work without any extra clicks. 

Currently I am thinking that the fastest and easiest way to implement a working solution without any major changes to our code logic is that when topic ends because of the deadline then we do as @BeccaMelhuish suggested that we display the download results link, but it will display an extra warning prompt that after results are downloaded they cannot change the voting deadline anymore, if they click Continue I will update the topic status and reload topic data that will include the download links and will trigger downloading automatically.

I will also hide the results graph if the topic is not in the follow-up or closed status

**Comment by BeccaMelhuish** [comment]
Thank you @ilmartyrk! 

OK I see the 'Close vote' option in the vote settings menu now :) 

A few things on this: 
- When I just tried clicking it, it closed the vote instantly, should there be an "Are you sure you want to close the vote?" dialogue first?
- As it's now decided [here](https://github.com/citizenos/citizenos-fe/issues/641) that there will no longer be a 'When all votes are in' option, @kevincrepin do you think the options in the menu below should now be "Deadline" and "Close manually" so that users understand that if they don't set a deadline then they close it themselves? (Once this is decided we need to re-write the text above the options too - I think we should specify you can always add a deadline later?). 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8177e11f-ee3e-4329-a7cc-4d0f6092e29f)
- When I just tried closing a vote, there is still this mismatch of text versus number of votes (yellow bits). Also I'm wondering what "download the full document" means - is it meant to be "download the voting results"?:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/442d2e3e-551f-4d21-bfbb-e5b44aacc8b6)
- And re the red bit, wondering if this should just this say "Closed" rather than showing the number of minutes ago it was closed as if it was a deadline? @kevincrepin what do you think on this?  

I'm a bit unsure about automatically changing the status to follow-up without an admin actually having opted to add that phase, as does that mean that whenever someone opens the topic they will land on the (probably empty) follow-up tab? Might be a bit disorienting/confusing? 

@ilmartyrk would you be able to share any texts such as [these ones](https://github.com/citizenos/citizenos-fe/issues/595#issuecomment-1877071237) you posted above, so we can make sure they are all saying the right things? Ideally with screenshots if possible as this is still all a bit confusing :)   

And @ilmartyrk what did you think about [this issue](https://github.com/citizenos/citizenos-fe/issues/594) - is it related to all this or something different?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish 595 and 594 are related, posted a fix

**Comment by anettlinno** [comment]
Thanks for the great discussion @kevincrepin @BeccaMelhuish @ilmartyrk. I´ll try to sum it up for Ilmar, please let know if you have understood something differently or left something out :)

**1. Extending voting deadline**

This feature is important for the reasons that Becca have brought out and there was a real use case where the General Meeting was postponed for a week and admins wanted to postpone the voting until then. It was an unforeseen situation. So, let´s allow extending voting deadline but then **allow to edit voting deadline only before the deadline has passed,** as you argued above. Once the deadline passes, User will see the results, and no longer be able to extend the deadline.

To do: 

- [ ] Add the notification text in setting voting deadline [box](https://github.com/citizenos/citizenos-fe/issues/595#issuecomment-1888611726). I think Becca´s suggested text works well: _You can only edit a deadline before it has passed. Once it passes, you will see the results, and no longer be able to extend the deadline._ 
I would actually bring this text in top of the deadline box, as I´m afraid, it´s too hidden in the bottom.

**2. Closing voting manually**

To do: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/766408d6-f4fd-436a-aac6-10ffc5060247)

- [ ] Add "by default" option (always opted in when User lands on settings page) "Close vote manually" field as @BeccaMelhuish suggested above. @kevincrepin could you please create new design and copy for that :)
- [ ] Remove "All votes are in" and we have an issue for that #641 
- [ ] If Admin has chosen the "Close vote manually" option then IMO this option should be visible for User on the "voting panel" (as under the menu it´s rather hidden). This need @kevincrepin ´s input :)
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/d2b44bba-8c0a-4f39-84dd-463d70527df1)

- [ ] When clicking on "Close vote manually", pop-up window appears with the question: "Are you sure you want to close the vote?"  
- [ ] Voting results will appear after Admin has closed the voting manually and all Admin users can download results

The question is, should we display "Close vote manually" in the case when Admin has set the voting deadline or should we then hide it in menu?

**3. Closing voting by setting a deadline**

- [ ] As soon as the deadline has passed, the "Download voting results" button appears 
- [ ] There will be warning: "After results are downloaded you are unable to change the voting deadline"

**Comment by kevincrepin** [comment]
Well I'm going through this after going through other vote-related issues :) We need a system where all these related issues are maybe a bit better bundled, but anyways...

I don't think we should have a "close manually" option in the sense that if you choose deadline you should also still be able to close manually, so it makes it a bit confusing. The point of doing things manual is that you can always do it (kinda).

Changes to the setup are posted in this issue: https://github.com/citizenos/citizenos-fe/issues/665  

And I would keep the closing action in the menu, but make the menu more clearly visible + have one line of text in the voting module that can communicate when you will see results and how to end the vote.

Changes to the voting module are posted in this issue: https://github.com/citizenos/citizenos-fe/issues/679

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno @BeccaMelhuish I guess this is fixed by fixing the issues Kevin referred

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish I am not closing this because there is still a mismatch between what is there currently (screenshot1) and the fix implemented by Kevin (screenshot2). 

<img width="1205" alt="Screenshot 2024-02-01 at 14 50 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7ecedabc-6331-43f0-b6c6-cccfcf18e31c">

<img width="1199" alt="Screenshot 2024-02-01 at 14 51 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f7bdda31-a2fd-4346-8110-3dd89e67cd0f">

Please let me know when the issue is ready to be retested.

**Comment by ilmartyrk** [comment]
@ssin1901 what do you mean by the fix? The copy text?

**Comment by ssin1901** [comment]
Looks okay to me for this phase (see screenshot). Closing.
<img width="1440" alt="Screenshot 2024-03-27 at 12 05 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e7ecfda8-e75d-4180-8397-19111dc3acd6">
