### ISSUE TITLE
🖥 Design review: General

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#597]
### **Hover states**
Currently hover states animation is instant. Can we do a dissolve/fade so it feels smoother?

### **Missing hover states**
Some interactive elements (buttons, links) right now don't have hover states.

1. Blue text links: let's give them an underline on hover 
2. Dialog windows "X": Can it rotate like 180degrees? :)
3. Topic card and Group card hover states: 
- only thing missing is that also the topic title here should transition from black to blue
- only thing missing is that also the group name should transition from black to blue
- it also seems like the blue transparent overlay currently falls under the photo, effectively making it not visible: 
https://github.com/citizenos/citizenos-fe/assets/26792281/70264858-757c-43b4-abab-727f69348b48

### **Main menu – Create button**
Nice to have: Can the "+" sign in the button on hover rotate 180degrees? make it more fun :) And then the same behaviour in all other buttons that have this "+" icon.

### **Main menu – My profile**
The icons for "Account details" and "Log out" are switched + text should be in black and let's do on hover in blue. 

### **Main menu**
The main menu should extent to the full height of the page, like you did on the redesign url
![Screenshot 2024-01-05 at 09 33 51](https://github.com/citizenos/citizenos-fe/assets/26792281/f36544a0-a2c0-46ff-91bb-58dc2f57977e)

### **Dialog windows**

1. When there's a larger dialog window currently there are no margins between the top and bottom and the browser screen. This makes it feel very confined. We should always have additional margins at the top and the bottom, let's say 40px:
![Screenshot 2024-01-04 at 13 36 50](https://github.com/citizenos/citizenos-fe/assets/26792281/1ee2e8fc-9449-490f-b027-ba32c9d19d69)

2. Also in this case when scrolling the dialog window, the background "darkener" scrolls with it, creating in the bottom an "opening" to the content on the background: 
![Screenshot 2024-01-04 at 13 36 17](https://github.com/citizenos/citizenos-fe/assets/26792281/cf6dcf58-4872-484b-95cb-37b3a3bcb309)

3. Finally it seems I can scroll the background content also while the dialog window is open, but this should never be the case:
https://github.com/citizenos/citizenos-fe/assets/26792281/5f43b0ad-3315-4d2c-a874-df72247f0cf4

### **Action menus**
Currently the action menus (opened mostly, but not exclusively, from 3-dot icon button) don't look correct:
![Screenshot 2024-01-04 at 13 42 10](https://github.com/citizenos/citizenos-fe/assets/26792281/d4879327-c474-43c6-86c8-84b314c19e4b) (opened from 3-dot group action)
![Screenshot 2024-01-04 at 13 42 17](https://github.com/citizenos/citizenos-fe/assets/26792281/6cd81bb7-f778-4272-9ae7-baea74bb3b8e) (opened from 3-dot table action)

Both should look the same, so both: 
- left aligned icon+text
- No border around the menu box, but a soft drop shadow
- dividing line between menu items
Example from design: 
![Screenshot 2024-01-04 at 13 46 34](https://github.com/citizenos/citizenos-fe/assets/26792281/d9b2cfa7-5097-4b21-bfdd-a59ae73799b0)

And let's do on hover that the icon+text goes from black(or red) to blue.

We should also look at some places where opening the action menu in the bottom of the screens creates this situation that it falls off screen. In these scenarios the action menu should rather open above the button instead of under it:
![Screenshot 2024-01-04 at 13 54 03](https://github.com/citizenos/citizenos-fe/assets/26792281/196d0dc4-7aac-468c-bf74-ca3479573ec1)

### **Inviting people**
I think this also happens throughout all inviting dialog windows even if the recorded situation is when inviting co-creators. 
Tou can see in the video that after I added a person who is in the system, their name still remains in the search field. But when I double click in there to select and clear the name, it assumes I want to add this person, and because it's not an e-mail address it shows me the error: 
https://github.com/citizenos/citizenos-fe/assets/26792281/6ee58a2c-ff04-4f31-8395-01e6baee9ffb

Potential solution: When an autocompleted person has been added, clear the search field.

PS: you can also see that there's no margin between the inline warning notification and the field, but there should be 24px.

**Comment by ilmartyrk** [comment]
@kevincrepin these should now all be fixed
