### ISSUE TITLE
🖥 Design Review: Logged in Dashboard

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#598]
### **Activity feed**
Let's avoid italics in the notifications here. The links can be blue and the username can be bold (because anyway no public profile to link to).

### **Search icon**
This icon should be in our "black" (#2C3B47)
![Screenshot 2024-01-05 at 10 00 02](https://github.com/citizenos/citizenos-fe/assets/26792281/c04412e1-aa65-480b-84e6-a7b80b8849df)

**Comment by ilmartyrk** [comment]
@kevincrepin there is a little issue with links as each activity currently is a link and will redirect to a group or topic if possible. So currently changed the italic items to bold and will re-visit it when we properly implement the updated activity feed in Phase II after initial launch

**Comment by kevincrepin** [comment]
It's ok (and good) to have the links, but I just want to  avoid them being in italic. So bold + blue links are fine, but since users don't have a public profile I guess the usernames are anyways also not links, right? In that case they can just be bold, not italic, for example.

**Comment by ilmartyrk** [comment]
@kevincrepin these should be fixed
