### ISSUE TITLE
🖥 Design Review: My Topics

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#599]
### **Filters**
1. The alignment of the texts within the dropdown boxes should be more in the middle. This applies for all dropdown fields everywhere, not just in this view (but anyway the same class I suppose :) )
![Screenshot 2024-01-04 at 13 01 12](https://github.com/citizenos/citizenos-fe/assets/26792281/3b99352f-28b0-40b8-8ee9-af1039972401)

2. The expand button and the Reset filters button icon colours are not consistent with each other. Let's do it so that both have blue icons (like the reset button) – I also updated this in the design accordingly:
![Screenshot 2024-01-05 at 09 58 12](https://github.com/citizenos/citizenos-fe/assets/26792281/dd933bd4-116e-464b-9f83-19d39fceee53)

3. And then let's do it so that on hover the light blue background goes to blue and the icon turns white.

**Comment by ilmartyrk** [comment]
@kevincrepin these should be fixed
