### ISSUE TITLE
🖥 Design Review: Topic creation

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#600]
### **Compose**

1. When clicking on "Title", "Intro" or "Description", I should be immediately able to type. Right now I click and I need to click again to focus on the text field in order to write.

### **Settings**

1. Can we do it that whenever there's a "radiobutton button" that the entire button is clickable? Not just the label or the actual radiobutton circle, but the entire bordered box: 
![Screenshot 2024-01-04 at 14 12 26](https://github.com/citizenos/citizenos-fe/assets/26792281/b7a6f1e9-5c21-4c2a-ad07-f9f50076b351)

### **Preview**

1. The image here should not have rounded corners, because of the notification on top. It will have rounded corners once published though: 
![Screenshot 2024-01-04 at 14 17 32](https://github.com/citizenos/citizenos-fe/assets/26792281/457794c5-12e1-45d7-a650-a918956c28a4)

2. The margins (especially top and to a lesser extent the sides) are too small. In design it's 40px top and 32px sides. 
![Screenshot 2024-01-04 at 14 20 28](https://github.com/citizenos/citizenos-fe/assets/26792281/3b58aae8-cd85-46c0-b590-3567cd9716a9)

3. The arrow in the "Read less" button should also be blue: 
![Screenshot 2024-01-04 at 14 23 15](https://github.com/citizenos/citizenos-fe/assets/26792281/32a91691-46ad-4387-a689-2e38d0d121c5)

4. Let's center align "Learn more about topics": 
![Screenshot 2024-01-04 at 14 24 36](https://github.com/citizenos/citizenos-fe/assets/26792281/30a496da-c074-4ba8-8897-9df7eae329a2)

### **Attachments**
The rounded corners of the attached file here should be only 4px:
![Screenshot 2024-01-05 at 09 28 05](https://github.com/citizenos/citizenos-fe/assets/26792281/82369c52-1314-4985-988e-954db693e41a)

**Comment by ilmartyrk** [comment]
@kevincrepin these should be fixed, though I will check topic text later as there might be some issues with lists, images etc.
