### ISSUE TITLE
🖥 Design Review: Topic view

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#601]
### **Tabs menu **

1. The "topic activity" is misaligned and it seems also the other icons have 1px shift (but this is minor :) ): ![Screenshot 2024-01-04 at 14 28 14](https://github.com/citizenos/citizenos-fe/assets/26792281/9504869a-ed44-4308-aaec-57c1bbb8792f)
2. The tabs labels should not be in blue, but black. Design reference: ![Screenshot 2024-01-04 at 14 31 53](https://github.com/citizenos/citizenos-fe/assets/26792281/0d5cacad-f160-48fd-99c5-afb053037a13)
3. The activity button hover should be uniform. Now when I go over the label, only the label background colour changes. The correct hover for the entire button is when I hover over the icon. So hovering over the text should trigger that look: https://github.com/citizenos/citizenos-fe/assets/26792281/e222e855-48af-4423-b45e-3dffee173ae5
4. When clicking on one of the topic phases in the tab menu, can we do it so that when landing on that page, there is an automatic scroll to the respective section under the topic text? So if I go from Discussion-tab to Voting-tab, I come on the page and it scrolls me to the voting section. Reason is otherwise I might not even understand what changed because the topic text is always visible.

### **Sticky action button**

The action button that sticks to the bottom of the screen (join discussion) should have a drop shadow like in the design. Currently it is not enough detached from what lays under it.
Design: 
![Screenshot 2024-01-04 at 14 34 52](https://github.com/citizenos/citizenos-fe/assets/26792281/6e4ee905-2d13-45ed-ac72-5d7799cec36a)
Dev: 
![Screenshot 2024-01-04 at 14 35 02](https://github.com/citizenos/citizenos-fe/assets/26792281/d17c853c-b23c-4eaf-bd8f-d52c844c0de8)

### **Phase indicators**

1. Let's remove the "i" tooltip icon. I think it's legacy...
2. I have one, seemingly, bug that when I click on the discussion phase indicator – which shouldn't be possible while I'm already in the discussion tab – I come to some view where the right side boxes are gone: https://github.com/citizenos/citizenos-fe/assets/26792281/0bac19ad-85a0-4cc1-aeaa-27a984533aa2

### **Information card**

1. Seems like the author icon (pen) is not black but grey. It should be black, like the rest of the icons under it.
2. When there is nothing in Attachments, Group or Categories, let's have this empty state text. Since they can be opened anyway we should show something rather than nothing: 
![Screenshot 2024-01-04 at 14 49 44](https://github.com/citizenos/citizenos-fe/assets/26792281/343bca5a-6fb4-47f1-8f8b-3978479da48f)
3. Let's truncate long filenames so they can fit and we avoid these situations: 
![Screenshot 2024-01-05 at 09 31 52](https://github.com/citizenos/citizenos-fe/assets/26792281/46eaf317-73d9-400a-9672-5176eb642244)

### **Topic walkthrough**
The walkthrough card notification from the bottom is offset to the left. it should align with the other cards on the right side of the topic text: 
![Screenshot 2024-01-05 at 09 35 47](https://github.com/citizenos/citizenos-fe/assets/26792281/d0fd8866-9a19-480f-acdb-ae8577de3cbf)

### **Discussion**

1. when I click "add argument" could it animate open? This would improve the understanding of how this sticky CTA card works.

2. When the "add argument" is open, the background should also be darkened a bit (#2C3B47 at 60%) to separate it better from the content. See design example: 
![Screenshot 2024-01-05 at 11 43 04](https://github.com/citizenos/citizenos-fe/assets/26792281/87481316-7b14-4aa9-9539-c106bc62d155)

3. The informational comment width should align to the left with the pro argument and on the left with the con argument:
![Screenshot 2024-01-05 at 11 46 27](https://github.com/citizenos/citizenos-fe/assets/26792281/5255b728-b9a7-4c31-9e51-ca0098ef5de2)

4. When replying to a comment, the width of the reply component is too big/sticks out. + currently margin missing between the text field and the buttons under it:
![Screenshot 2024-01-05 at 11 48 01](https://github.com/citizenos/citizenos-fe/assets/26792281/59463602-b2c7-4432-8ba6-0582bcb12f4e)
The same applies for con argument and informative comment.

5. The View replies button border should be 2px and the colour should be the same as the green of the button next to it:
Dev: ![Screenshot 2024-01-05 at 11 51 57](https://github.com/citizenos/citizenos-fe/assets/26792281/8ff789f8-e64d-4e21-90e9-44103498dbb6)
Design: 
![Screenshot 2024-01-05 at 11 52 40](https://github.com/citizenos/citizenos-fe/assets/26792281/327c2a6f-7ec7-48f9-b59f-8877ebfb258f)
The same applies for con argument and informative comment replies buttons, in their respective defined colours.

### **Start voting topic**

1. The background behind the tabs should be the same colour as is used above (green for this voting dialog modal, yellow, for ideation, pink for follow-up): 
![Screenshot 2024-01-05 at 11 55 26](https://github.com/citizenos/citizenos-fe/assets/26792281/6d51e424-d17c-4679-81e2-58b1c85ac166)

2. Dealing with the same screenshot above: the typography needs a bit of work when comparing it to the design. "Are you sure you want to start the topic voting? Things to keep in mind:" should be 16px and the list items should have 8px margin between them. Design reference: 
![Screenshot 2024-01-05 at 12 00 46](https://github.com/citizenos/citizenos-fe/assets/26792281/2c4b4786-a684-4b66-a924-f1ea8cb7c72f)

3. For the radio button selections let's on hover give these also a green background, not the blue as it is now. And pls apply this everywhere where we have similar radio button component.
Dev: 
![Screenshot 2024-01-05 at 12 02 30](https://github.com/citizenos/citizenos-fe/assets/26792281/1f0561e2-1b06-42fd-88c9-9a8b11f0c817)
Design: 
![Screenshot 2024-01-05 at 12 02 07](https://github.com/citizenos/citizenos-fe/assets/26792281/e48cf09e-d709-49c0-a793-a6bf032744b1)

4. A couple issues here:
- The voting question box rounded corners should be only 8px
- the button to add another answer is missing its background and I think we should immediately have at least 2 input fields to start writing these custom answers. Since user chose this now they again need to press a button for the input field to show up.
- Some issue currently with the min/max labels being code lingo :) and also are able to push the +/- and field out of the box.
![Screenshot 2024-01-05 at 12 09 21](https://github.com/citizenos/citizenos-fe/assets/26792281/60f08050-994b-4d75-8836-d095297e475d)

5. In the preview I can currently actually make a selection from the voting options, but this should not be interactive at all, just a representation of how it will look:
![Screenshot 2024-01-05 at 12 15 26](https://github.com/citizenos/citizenos-fe/assets/26792281/54238bf1-0222-4f39-9a20-99e52dffb5d5)

### **Voting topic**

1. When I created a voting to the topic then there is no success message, but there should be.
2. Ideally also the screen scrolls down to the voting section so the focus is in the right place.

3. Voting options selection:
- Let's on hover over these options change the white background to #E0F5E3
- currently the checkbox border colour changes to blue, but let's not do this
- and when the choice is selected the checkbox now this has a grey border, but that border colour should be #346933
- I can't deselect any option although there's shown as checkboxes so I should be able to deselect as well.
![Screenshot 2024-01-05 at 12 19 24](https://github.com/citizenos/citizenos-fe/assets/26792281/37ebb5e7-aaf6-4112-9416-497997ad05bf)

4. Delegate vote
- The text should have bit more lineheight (pls also apply this across the board for every similar dialog window text like this): 14px size and 20px line height. Basically we have 2 different line height styles for the 14px text size. If the text is on one line (label etc) then it's 16px, but if it's a multiline text then it's 20px.
- the background for the person should be a bit lighter: #F1FAF3 
![Screenshot 2024-01-05 at 12 32 35](https://github.com/citizenos/citizenos-fe/assets/26792281/a8b8f443-af8d-4a81-b507-8ed10e8f4b31)
- There should be more margin between these elements, a bit too cramped now. The button to revoke should also align to the right with 24px margin to the edge.
Dev: 
![Screenshot 2024-01-05 at 12 36 38](https://github.com/citizenos/citizenos-fe/assets/26792281/5d3e0127-81d2-4e9f-88fc-cb43f57811bd)
Design:
![Screenshot 2024-01-05 at 12 38 53](https://github.com/citizenos/citizenos-fe/assets/26792281/1cef9d36-496e-4c56-bf85-d52873617b51)

5. Send reminder mail
- The top of the dialog window falls off screen
- Space missing in the text between "close!" and "You"
- I think let's place the deadline under the "votes collected" text since in this width they bleed into each other.
- let's also reduce the margins above and below the button to 32px to reduce the overall height of the dialog window
![Screenshot 2024-01-05 at 12 40 19](https://github.com/citizenos/citizenos-fe/assets/26792281/65f6c472-9ae6-4cfa-bc80-e27b4f34fc71)

6. Vote submitted
- Let's give more margin above this edit your vote
- Also seems like this 14px text should apply the 20px lineheight
![Screenshot 2024-01-05 at 12 47 07](https://github.com/citizenos/citizenos-fe/assets/26792281/45ded2e0-505c-4576-80d6-77a888bc6607)
- For this voting system menu I created a reference and some new icons so we can use those. And let's change the background from the 3-dots button to #F1FAF3 on hover
![Screenshot 2024-01-05 at 12 53 48](https://github.com/citizenos/citizenos-fe/assets/26792281/9772ee79-9178-45bd-ac01-56530261840b)
![Screenshot 2024-01-05 at 12 53 35](https://github.com/citizenos/citizenos-fe/assets/26792281/8be66754-5893-4a8e-9d6e-2a5318b3d89f)

6. Inconsistency between voting info
- In this example I cast my vote and deadline is 2 months away. But in the right side phase indicator it shows voting has ended and no votes are counted:
![Screenshot 2024-01-05 at 12 57 04](https://github.com/citizenos/citizenos-fe/assets/26792281/81c19555-76a8-4a90-b2ee-ce19760d7c9c)

### **Follow-up**

1. There should be more margin on the sides here: 24px left, bottom and right & 16 px top:
![Screenshot 2024-01-05 at 13 53 40](https://github.com/citizenos/citizenos-fe/assets/26792281/cb0c7c9a-2532-4d8b-801c-6336860e8780)
2. the same goes for the posted milestone: 
![Screenshot 2024-01-05 at 13 56 28](https://github.com/citizenos/citizenos-fe/assets/26792281/eec1fb49-db18-4b07-b5a1-ce6b4e019cfa)

3. This follow-up phase indicator currently does not really make sense. Normally it would show the progress based on the checklist. But since we don't have that yet, I would just show how many milestones there are, so instead of 0/0 just a number. And the progress bar I think just needs to be removed for the moment.
![Screenshot 2024-01-05 at 13 58 03](https://github.com/citizenos/citizenos-fe/assets/26792281/de593d52-f6ab-4520-8702-7df55e012099)

**Comment by ilmartyrk** [comment]
@kevincrepin these all should be fixed, but wanted to add two comments, the topic tour box misalignment was caused, because I set it a little more left from the help bubble as @BeccaMelhuish commented that it got in the way, anyway moved it back.
Second thing is  that I fully didn't understand how the informational comments should be aligned, did you mean they should be full width of the arguments area or they should be narrower than pro and con arguments?

**Comment by kevincrepin** [comment]
@ilmartyrk yes, informational should be full width ( minus 24px margin on left and right side). Not narrower than pro or con, but align with their outer edge – respectively left or right:
![Screenshot 2024-01-21 at 18 37 57](https://github.com/citizenos/citizenos-fe/assets/26792281/56c936fb-425b-4a54-927a-32e5b1e91b5a)
