### ISSUE TITLE
🖥 Design Review: My Groups

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#603]
### **Search button**
On this page the button is a bit elongated, whereas on Dashboard and My Topics it is – correctly – a circle.
![Screenshot 2024-01-05 at 09 51 36](https://github.com/citizenos/citizenos-fe/assets/26792281/d0cdb408-462f-4fca-8644-3378bfb64b87)

### **Filters**
1. The same comment applies to these expand and reset buttons as in the "My Topics" page: colours and hover
2. The search field here has shifted down a bit. Should align with the reset button: 
![Screenshot 2024-01-05 at 09 53 42](https://github.com/citizenos/citizenos-fe/assets/26792281/6b620cc7-042d-47a1-80d1-18eed3fc8352)

**Comment by ilmartyrk** [comment]
@kevincrepin these should be fixed
