### ISSUE TITLE
Topic: Expanded toolbar menu in topic creation doesn´t look right

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#604]
**What is the problem?**
When expanding the toolbar menu, then two rows are too close to each other:

<img width="518" alt="image" src="https://github.com/citizenos/citizenos-fe/assets/45175679/df616e4f-6e42-42f9-aea6-5e4ebef6f043">

**Why is this a problem?**
Looks broken

**Possible solution.**
Leave more space between two rows when expanding toolbar.

**Comment by anettlinno** [comment]
Triage 99. Sending to do. Est dev time 5 min.

**Comment by ilmartyrk** [comment]
@anettlinno posted a fix

**Comment by ssin1901** [comment]
Seems to be fixed (see screenshot)
<img width="1284" alt="Screenshot 2024-03-05 at 16 25 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9c86274f-8162-4793-a15b-0c493b180f7c">
