### ISSUE TITLE
IS: two email/user name entry fields

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#606]
**What is the problem?**
I invited multiple users in one topic and two email/user name fields appeared: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/73e0fe26-c7de-44c7-9d0c-ffad9af7fbef)

**Why is this a problem?**
Very confusing and incorrect behavior.

**Possible solution.**
Please fix so that we would only have one entry field :)

**Comment by ilmartyrk** [comment]
@anettlinno fixed

**Comment by ssin1901** [comment]
@ilmartyrk there is still a problem with the flow. When an invalid email format is entered, the user gets a field to "correct" the invalid email (screenshot1) but the original search remains. When the user uses the original search, the field for correcting the invalid email is still present, effectively displaying 2 search fields (screenshot2)

<img width="1440" alt="Screenshot 2024-02-18 at 17 49 20" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c01ace8e-a768-4539-9e5e-8973c0a8130e">

<img width="1440" alt="Screenshot 2024-02-18 at 17 51 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/30427a8e-d8f4-4f5c-918d-cf78a301df0f">

**Comment by ilmartyrk** [comment]
@ssin1901 I could not replicate the issue, can you describe the flow or add a video

**Comment by ssin1901** [comment]
@ilmartyrk not necessarily a bug but the flow is a bit odd (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/c6dbb72f-d349-4302-b559-dfed4ae95786

Basically, the user can "edit" the invalid email format but also add other users via another input field.

**Comment by ilmartyrk** [comment]
@ssin1901 I think it is OK, yes it may look weird. But for example, you are from a big organization and have to add a long list of e-mails. You are already in the copy paste flow and some invalid e-mails have popped in. You see them on the screen, but decide to finish your initial flow and after that check what has gone wrong with some e-mails. Also I guess most user will rather correct the bad e-mails on the go or delete them if they get in their way so my suggestion is to close this issue for now and let's see if it comes back later

**Comment by ssin1901** [comment]
@ilmartyrk agreed, as both the search fields work so the functionality is not affected. Closing the issue.
