### ISSUE TITLE
📱 Design review: Logged in Dashboard + Walkthrough

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#608]
### **Walkthrough**

![Screenshot 2024-01-05 at 14 59 00](https://github.com/citizenos/citizenos-fe/assets/26792281/6d6b4547-4844-4a67-824d-b22050ffe053)
Is it possible on mobile that dialog windows are full screen also in height? Then we also don't need the rounded corners so nothing from the background is bleeding over.

![Screenshot 2024-01-05 at 15 01 59](https://github.com/citizenos/citizenos-fe/assets/26792281/2ea1f196-6bf1-479a-82d8-08011cc66620)
The orange bubble on top of the icon:
- should not have a dark 1px stroke
- if there's no notifications, the bubble shouldn't be there at all. Only if there are any new notifications should it show with a number in it.

![Screenshot 2024-01-05 at 15 00 57](https://github.com/citizenos/citizenos-fe/assets/26792281/8335851a-e438-42ee-a272-00cc598f5e46)
- In this step the Citizen os logo, search icon and profile photo have disappeared.
- Also from previous step to this one, the screen didn't scroll to the top to focus on this, so I was a bit confused where was I etc.

### **Top Menu**
![Screenshot 2024-01-05 at 15 59 14](https://github.com/citizenos/citizenos-fe/assets/26792281/277ab94b-716d-4411-ba7b-6c089ab5d55c)
The top menu in this view + in My Topics and My Groups should have a white bg with rounded corners in the bottom: 
Dashboard: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=472%3A59136&mode=design&t=qO6vqSn5rMBB0ODx-1
My Topics: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=64%3A35022&mode=design&t=qO6vqSn5rMBB0ODx-1

### **Notification**
![Screenshot 2024-01-05 at 15 08 05](https://github.com/citizenos/citizenos-fe/assets/26792281/af7d26be-dbe2-4ba9-b0b7-1dcfa462e089)
- Notifications etc should be same width as the screen

### **My Topics**
![Screenshot 2024-01-05 at 15 45 02](https://github.com/citizenos/citizenos-fe/assets/26792281/3f711284-83ce-4fd2-b51e-4d200c0f0da0)
Ideally the slider goes fully to the edge and doesn't cut the card before the edge, like in https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=472%3A59136&mode=design&t=qO6vqSn5rMBB0ODx-1

### **Citizen OS news**
![Screenshot 2024-01-05 at 15 51 09](https://github.com/citizenos/citizenos-fe/assets/26792281/41d6fbe5-a8e5-4b83-8600-b63c87469f10)
Can the images fill the entire rectangle provided for the image? Now there is this space left on the right.

### **Newsletter**
![Screenshot 2024-01-05 at 15 53 24](https://github.com/citizenos/citizenos-fe/assets/26792281/546abc19-db90-4b49-bb89-f03deb28a078)
This body text should be 16px size

**Comment by ilmartyrk** [comment]
@kevincrepin fixed these issues
