### ISSUE TITLE
Voting: Voting settings 'Public' button dodgy

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#617]
In a test, it looked like the user was trying to select 'public' when setting up a voting topic, but the button didn't register his click. It flashed blue briefly (see screenshot), but didn't change the selection from private (and he then carried on making the topic with it still set to private). 

Later on in the test when he made a new one, it did work OK. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d96c1fcc-20c0-4c51-a208-3758eb0809da)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish couldn't replicate
