### ISSUE TITLE
Topic: 'Choose a group' drop-down UX for when you have no groups yet? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#618]
@kevincrepin a minor UX bug I noticed in a test - what should the UX be for at this 'Add to group' stage when you are making a topic but have no groups yet? 

He was clicking the dropdown (presumably to work out what it was all about), but as he had no groups it just sort of 'jumped' a bit with his clicks, but didn't open. 

He then understood that he had no groups so this wasn't relevant and moved on, but should there be something a bit smoother here? E.g. the drop-down opens, but says 'You don't have any groups yet' or something like that? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d7de5980-17d9-40fb-860f-8007be6116ac)

**Comment by kevincrepin** [comment]
Yes, good point @BeccaMelhuish ! I've added this empty state: 
![Screenshot 2024-01-21 at 18 44 28](https://github.com/citizenos/citizenos-fe/assets/26792281/9b6b0196-72f3-4376-93d8-9c0bcaba5a21)

https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11460%3A107596&mode=design&t=cdGvUcp5EzmNWfSd-1

**Comment by BeccaMelhuish** [comment]
Looks good thanks @kevincrepin!

**Comment by anettlinno** [comment]
Triage 100. Sending to do. Est dev time 15 min.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the update
