### ISSUE TITLE
Voting: 'Select a voting system' buttons active in the wrong place

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#619]
User found that when clicking these buttons, it activated the selection when he clicked in the part he least expected it to - in the yellow rather than the red shown below. 

The red part (both circle and text) should definitely be active (i.e. clicking on it leads to selection), but @kevincrepin am I right in thinking good practice would to be to have clicking anywhere on the whole button as activating it - to make it as easy as possible to select?  

Seems to be the same for all the others on this page when I try it, may be worth checking any other similar buttons elsewhere? 

It should also be so that clicking a second time removes the selection (for all the buttons like this), so that if you accidentally click on it you can undo it (it's quite tricky at the moment, for some it does work like that and some it doesn't). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/737114ac-57e2-48dd-9a78-83c06c28dd55)

**Comment by kevincrepin** [comment]
Yep, I have also mentioned this in my latest feedback round ;)

**Comment by BeccaMelhuish** [comment]
Ah OK great! I will also add here this related bug in case you didn't catch this as well: 

Currently you can have both these selected at once (which I think shouldn't be possible?) and also selecting the "Set automatic reminder" seems to deselect and close the whole 'Deadline' box. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e1aeef7f-4cab-4dc4-86bd-a38f9ba726f5)
