### ISSUE TITLE
Voting: User wasn't able to vote in his own topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#620]
After trying out setting up a voting topic, user wanted to try out voting in it, but he wasn't able to cast a vote. He was clicking in the different vote options, but nothing was registering. It was in the same test as [this issue](https://github.com/citizenos/citizenos-fe/issues/593) (now closed), if that helps? 

(He clicked in all sorts of places on the button, in and out of the circle/text)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3b09ca9c-b4ef-4999-997d-cc57f342f4fb)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish was this in the topic preview?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk no I double checked the video and it was just after he had published: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b1601456-2b12-4dec-b8d9-6ebd6353dd9e)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish what browser was used

**Comment by BeccaMelhuish** [comment]
I don't know I'm afraid! As was UX testing rather than QA testing :) 

Maybe @ssin1901 can help with testing on different browsers?

**Comment by ilmartyrk** [comment]
Posted an updated that should fix this issue

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate on the latest versions of Safari or Chrome. I think the issue is fixed
