### ISSUE TITLE
IS: Invite link didn't work 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#621]
User invited me to his voting topic so that I could vote in it during a test, but when he sent me the invite link it didn't work - I wasn't able to access it. I believe I got 'Insufficient permissions' though it could have been 'Not found'. 

He invited me via email instead though and that worked fine. 
(But would be good to have the invite link working for future tests if possible, in case it's important to the scenario).

**Comment by anettlinno** [comment]
@BeccaMelhuish please detail if this link was "invite link" or URL link and public or private topic link?

**Comment by BeccaMelhuish** [comment]
It was a proper invite link (taken from the 'invite & share' pop-up), and it was a private e-ID voting topic :) 
(I was most likely logged in already at the time, though can't be sure now).

**Comment by anettlinno** [comment]
Triage 98. Est. dev time 1 hour. Sending it to do.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno posted a fix

**Comment by ssin1901** [comment]
Seems to be working but for 1 second (too fast for me to screenshot) the insufficient permissions error was flashed.

Should I close the issue anyway @ilmartyrk ?

**Comment by ssin1901** [comment]
Could not replicate. Closing this issue.
