### ISSUE TITLE
Voting: Participant seeing text meant for admin

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#624]
In this topic I am a participant, but I am seeing text that is speaking to the admin: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/98f05de8-4146-4638-8bc7-499da29e70ce)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is fixed

**Comment by ssin1901** [comment]
Could not replicate the issue after fix, closing
