### ISSUE TITLE
Filter: Argument filters can make discussion disappear

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#625]
When you choose arguments that don't exist in a topic here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0e73cc3c-607b-4e6d-b907-0e8adf1c0ca0)

Then it does this (and you have to reload the topic to get the filters back): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e3ba0057-104e-459d-92b6-ddcadf663279)

**Comment by ssin1901** [comment]
@BeccaMelhuish I found the same bug. Was just wondering if it would affect the next round of UX tests.

**Comment by anettlinno** [comment]
Adding pre UX test label to fix it together with other bugs.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by BeccaMelhuish** [comment]
Works thank you! 

Though I think we need a little block 'There are no con arguments' or 'There are no informational arguments' etc, would you agree @kevincrepin and if so how looking? (This I think is a 'nice-to-have' though, main problem is now fixed so am removing pre-UX texts label :)) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/29de2850-4693-4849-9350-53266b003a34)

**Comment by ssin1901** [comment]
Issue is fixed (see screenshot) so I am closing the issue. @BeccaMelhuish can we close the issue and make a separate issue for the UX fix?

<img width="1400" alt="Screenshot 2024-02-04 at 17 49 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/14a7e701-9c54-4158-aec8-9cc92e194367">
