### ISSUE TITLE
Topic: 'Read less' on a long topic description jumps

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#626]
When clicking 'Read less' on a long topic description (like [this one](https://test.app.citizenos.com/en/topics/7f0535f5-1ba7-4194-a095-13670a630db1#discussion)), it drops the user right in the middle on the discussion - far down the page. It should leave the user where they started (at 'Read more'). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9c66a805-1dec-459e-b654-619e03239092)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the behavior

**Comment by ssin1901** [comment]
Seems to function alright, closing.
