### ISSUE TITLE
Topic: some odd layout from changing browser window width

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#627]
User didn't mention this, but from what I see from his screen-sharing, there was some strange layout issues going on in the topic. (A guess: he may have had his browser window narrower than usual - so this is between desktop and tablet layout?)

It starts like this, with the odd layout at the bottom: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/09c995f2-0d85-4871-8087-fc7a3be843ea)

Then the topic 'jumps' out to the left like this, and there seems to be this little 'loading' circle top left (see previous one too): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f4b3e373-78c5-41ec-b8a7-3105df123027)

**Comment by BeccaMelhuish** [comment]
Just tried it myself and it does the same thing for me, when making the window narrower: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6fa80d24-68ed-4380-ac08-8eadbbbe053b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is fixed
