### ISSUE TITLE
Topic: Attachments upload menu stays open after adding 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#629]
After user has added his attachment, the menu stays open, until he clicks elsewhere. Felt a bit odd/unexpected to me - I assume it should close once the attachment is added? (And if they want to add another, they re-open it?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d003d681-334d-47e6-b149-34602245e4bf)

**Comment by anettlinno** [comment]
Could not replicate the issue and will close it as it´s fixed.
