### ISSUE TITLE
Topic: Category not displaying in full 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#630]
User added category 'Democracy and civil society' but it just displays as 'society,' with a comma. Show display in full, and with no comma when there is only one category listed. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8d6412f4-4526-4a53-825a-66c3efdb552f)

**Comment by anettlinno** [comment]
@BeccaMelhuish just tested and works nicely for me. Closing the issue, if anything doesn´t work as supposed, please reopen.

**Comment by BeccaMelhuish** [comment]
@anettlinno seems to still be a problem for me so reopening: 

E.g. in this case, should be 'Politics and public administration' but just says 'politics' and there is still the comma despite only 1 category. Also all categories seem to show up in lower case, not sure that's meant to happen? 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/39ee06a7-37d7-430d-99eb-c8a15c25a1a1)

Just tried with a new topic, it looks like this, same issue with case and politics: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5073f5fa-ca97-4822-9d76-71110ab5e402)

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish this is now fixed though already added categories int the test topics  that were broken are not fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot)
<img width="1439" alt="Screenshot 2024-03-27 at 13 18 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ece00b07-39f4-4f11-bf3d-13b6d7850185">
