### ISSUE TITLE
Topic: Pop-ups appearing off-screen. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#631]
Several times in a test the user found he had to scroll up to see a pop-up, as it appeared 'off screen' at the top, when he was scrolled further down. 

Here is one example below, when he clicked 'Add follow-up'. The other two times were 'Add voting', and I believe also when he was voting (the pop-up window asking for e-ID login) - I will check. 

But in general all pop-ups should display where the user is on the screen, rather than them having to scroll up? (I'm not sure what the best practice is - that the pop-up appears where the user is on the screen, or the screen automatically scrolls up to where the user is - I assume the first option, feels smoother, but maybe @kevincrepin can advise if he hasn't already). 

So would be good to check this for all pop-ups, not just these ones the user found.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9ddf2cae-6d3e-4873-a156-9f07074bc26c)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is fixed now together with some other UI design fixes

**Comment by BeccaMelhuish** [comment]
Hey @ilmartyrk maybe I'm checking too early (how many minutes does it take usually - you mentioned there can be a lag?), but I just tried one ('Add follow-up') and it still does this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/11714421-55dc-43a7-bfcb-3707996a6249)

**Comment by BeccaMelhuish** [comment]
Same with 'Edit deadline' one in voting: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/60110e17-930e-41e8-96d5-831c4ed7da64)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think it was because of the lag

**Comment by anettlinno** [comment]
Tested and for me it works nicely, @BeccaMelhuish I´ll close the issue as it´s fixed now and if something doesn´t work as supposed to, please reopen :)
