### ISSUE TITLE
Voting: Deadline box closes too early

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#632]
When trying to add a date to the deadline box, user found that that box closed and deselected 'Deadline' as soon as he clicked anywhere. (He was trying to click on a date, to set the deadline). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7e65fac6-fa8e-4940-82c9-40f1042a5d13)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/675badeb-1ee5-4c16-99d4-2dbbfe2fb461)

Interestingly though, the deadline had actually registered as the date he had clicked on, even though he 'Continued' without the deadline box being ticked in the end (due to the bug): 
 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0cb90f4b-d462-4af3-a408-6411d030ce47)

I notice that in the designs there is no 'Save' button for this box, so am wondering what the intended UX is - should the deadline setting clock stay open as soon as and for as long as the deadline tickbox is ticked, or should there be a 'Save' button that closes it? Hopefully @kevincrepin can advise if he hasn't already :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7de290d3-8c63-4e6c-9f59-ac1f3a9c8324)

**Comment by BeccaMelhuish** [comment]
Same thing happens with this edit deadline pop-up, just tried it out: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d87ab744-2f9a-4cdc-a9f2-d12bf729d258)

**Comment by BeccaMelhuish** [comment]
Hey @ilmartyrk maybe I'm checking too early (how many minutes does it take usually - you mentioned there can be a lag?), but I just tried one ('Add follow-up') and it still does this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/11714421-55dc-43a7-bfcb-3707996a6249)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I just tested it here and the same thing still happens - when you click on a date the whole thing closes and deselects..  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/07b4c956-370c-414f-aa9f-4904ec4ed81e)

**Comment by BeccaMelhuish** [comment]
Same in this bit for me still too: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b27cd230-8055-4986-a145-ebf1b1442ce9)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish weird, can you make a video of this? And also what browser are you using? I initially solved it only for edit deadline dialog, but now I added the same fix to vote creating flow too

**Comment by kevincrepin** [comment]
@ilmartyrk 
https://www.dropbox.com/scl/fi/xl942b54ub0uxorxrcuq3/votingSelect.mov?rlkey=ma7b5sz2lzklxj5r79fvpslit&dl=0

Seems like the checkbox + label has a separate click event then the "entire box". When I click on the text under the checkbox+label it opens up the voting deadline module. But if I just click on the checkbox+label then it checks the option, but doesn't open the module.

Similar with the all votes in, but here nothing can open anyway. But I had a hard time understanding how do I deselect this option. I selected it by clicking on the checkbox+label, but then I couldn't do the same to deselect it. I have to click on the text under the checkbox+ĺabel to deselect.

Chrome browser btw

**Comment by kevincrepin** [comment]
@BeccaMelhuish 
_I notice that in the designs there is no 'Save' button for this box, so am wondering what the intended UX is - should the deadline setting clock stay open as soon as and for as long as the deadline tickbox is ticked, or should there be a 'Save' button that closes it?_

That was the idea indeed. But might be needed to have a save button, since the mechanics of selecting and deselecting are turning out to be a bit more complex than I hoped.

**Comment by BeccaMelhuish** [comment]
The issue with the box closing whenever I click in it seems to have gone today so all good there :) 

But I have the same issues with selecting and deselecting it as Kevin shows (and have noticed users having trouble in similar tickboxes elsewhere during the tests). 

I feel like this blue highlight for the hover state adds to the confusion a bit - as you select it and it is blue ticked, then you deselect it and if you are still hovering then it's still 'blue-filled' which doesn't feel like it it deselected, so you click again to be sure and it re-selects it, etc. Maybe would be smoother without it? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/60ba7982-2cc5-4dd4-9958-0175c4a67acb)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this issue is a duplicate and is fixed
