### ISSUE TITLE
Voting: Preview vote allows selecting more than the specified maximum options

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#633]
In preview, user found it was possible to select more than the maximum number of options (should only be allowed 2 maximum in this case). Maximum worked fine in the published one, but not in preview. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6aa2e4ea-fc7d-49ab-9106-15677db705a5)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish disabled checking options as it is just a preview

**Comment by BeccaMelhuish** [comment]
Though I would suggest they should be able to, as they need to check at this point how the vote works with their min and max voting options set. This might be an important moment for them to notice that they have either the min or max set to the wrong number. 

And from user tests, they do try clicking it in preview, and do notice the min and max possible, hence this issue coming up. 

@kevincrepin @anettlinno tagging for input if you have thoughts on this :)

**Comment by BeccaMelhuish** [comment]
Made a [new issue](https://github.com/citizenos/citizenos-fe/issues/1524) for the last point, and closing this one :)
