### ISSUE TITLE
Voting: Vote reminders formatting

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#634]
Not sure how it is in the designs, but something's not right here :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/26d61704-ff58-40a7-92d9-f7a3a534c913)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted an update to this view, also updated all the e-mails with ne notification in the footer
![Kuvatõmmis 2024-02-08 234850](https://github.com/citizenos/citizenos-fe/assets/19904307/0d9fc6a6-fc41-4698-b610-ae8a1f107665)

**Comment by ssin1901** [comment]
Looks okay to me now. I will close the issue for the time being (see screenshot)

<img width="1115" alt="Screenshot 2024-02-18 at 17 44 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f85fe4bd-3562-456c-b431-d084a1336f8d">
