### ISSUE TITLE
Voting: Vote reminder talks about a deadline when there isn't one

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#635]
This is a vote that doesn't have a deadline, so shouldn't mention deadline: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/08fefdb8-383f-4671-b0bc-c6cd7c9c27f5)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the e-mail if there is no deadline then it just say Please cast your vote!

**Comment by ssin1901** [comment]
Currently one cannot send a vote reminder (see screenshot) if there is no deadline which seems reasonable to me. Closing this issue for the time being.
<img width="1439" alt="Screenshot 2024-03-27 at 13 08 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2ac30729-b38b-43cd-8111-434e13ee649c">
