### ISSUE TITLE
Voting: 'Invites sent' - wrong message for vote reminders

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#636]
After sending vote reminders, I got this message - should be 'Vote reminders sent! (or similar):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8a9d1aa7-e6c1-4345-829e-7400d646f788)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the correct message

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1289" alt="Screenshot 2024-03-15 at 15 22 53" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2e4c2b0c-1602-4cf9-8119-41de6907b64c">
