### ISSUE TITLE
Groups: Users look to create topics within group under "Add topics"

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#637]
@kevincrepin @anettlinno @ilmartyrk - This is only preliminary feedback as tests are still in progress, but something that I feel is potentially clear enough already to start thinking about if you wanted to. 

2 out of the 2 users who have been working with groups (the third did not), have expected and wanted to be able to create topics in their group by clicking here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/baa480c5-178f-4edc-8670-06f09f30a21a)

Both of them were quite confused by the fact that this was only for adding existing topics, and took some time to figure out that this was even the case. One of them was then totally stumped as to how she would create topics in her group if she couldn't do it there, and it took a really long time - much later in the test - for her to discover how to add to a group during the process of creating a new topic. The other figured out pretty quickly how to do it once he had worked out that 'Add topics' was only for adding existing topics, but suggested a preference for it being where he had expected it. 

Proposal: Can the 'Add topics' button also provide the option to create a topic that is automatically part of the group, from the same place as you can add existing topics? E.g. when you click 'Add topics' you have two options: 'Create a new topic' or 'Add an existing topic'. 

I can provide more details if needed later, but some food for thought for now :)

**Comment by kevincrepin** [comment]
Fair point. I think we had this conversation at one point and I think this can be easily fixed. We'd just need two buttons because the create button already requires the topic type menu:

![Screenshot 2024-01-12 at 10 10 08](https://github.com/citizenos/citizenos-fe/assets/26792281/f239f937-eea4-4ad3-847e-391cb4ec79e9)

**Comment by BeccaMelhuish** [comment]
OK yes that looks good! 

And presumably when you create a new topic via this button, this bit of the settings would be automatically filled in (but still editable if they wanted to change their minds for some reason, or add a second group) with the group that they wanted to create it in. So that it does get created in their group once they've made it? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/580240e0-935a-47cb-9ddb-139bf959ef59)

I'm wondering if it needs any copy to make it clear that 'Create new topic' there means creating one _within this group_, and that add topic means add an _existing_ group? (Seeing as the users were very much thinking 'Add topics' meant 'Create a new topic in this group', I feel they might be thinking "What's the difference?")

**Comment by kevincrepin** [comment]
Yes, the "add to group" would be prefilled then.

I think if we have the two buttons it might be clearer? Otherwise this copy gets so long and it becomes messy...

**Comment by BeccaMelhuish** [comment]
Hopefully yes, we can see how it goes! 

But I was thinking we could add the word "existing" somewhere in here, e.g. "Search for an existing topic" maybe?:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c79130ef-ae7f-4b09-b1d0-638955eab1d3)

And was wondering if we add a little heading/copy at the top of this menu, though I realise would detract from the cleanliness of it rather: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3380b9c9-634a-4780-b3f5-aca063ed8373)

**Comment by anettlinno** [comment]
Thanks for the discussion above. I´ll conclude it.

1. Let´s add "Add topics" option to the group, as it is logical to create new topics inside the group and it´s also there on our current platform version. I think we could use the same copy as we have today: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/f0533307-55b1-4121-9165-745adc1e8aa0)
"Create new topic"
"Add existing topic"

2. If topic is created inside the group, then the "Add to group" should be pre-filled

3. Add "An existing" to topic search in group ("Search for an existing topic" as @BeccaMelhuish recommended)

4. Let´s not add any headline in "Create new topic" menu to keep the consistency with "Create" design

**Comment by BeccaMelhuish** [comment]
To be implemented before the 31st Jan, when Round 2 tests start, please :)

**Comment by anettlinno** [comment]
Triage 98. Est. dev time 1 hour. Sending it to do.

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish @kevincrepin  added the functionality with the create topic button

**Comment by kevincrepin** [comment]
Sorry to do this @ilmartyrk but when reviewing tablet and realising I never made a reference for mobile either I think we need to rethink this a bit for better scalability. 

I'm thinking whether we can combine the two buttons in on "Add / Create a topic" which could then work better on smaller screens.

Desktop:
![Screenshot 2024-01-29 at 18 27 19](https://github.com/citizenos/citizenos-fe/assets/26792281/120834ec-57ba-4924-be8b-d4c77b183f86)

Tablet:
![Screenshot 2024-01-29 at 18 27 52](https://github.com/citizenos/citizenos-fe/assets/26792281/1e1367ce-7213-4bd7-8b42-bd22ec7e0430)

Mobile: 
![Screenshot 2024-01-29 at 18 23 25](https://github.com/citizenos/citizenos-fe/assets/26792281/711fc308-1f86-4022-b2cc-690bdcfda4e0)

@anettlinno @BeccaMelhuish your thoughts?

**Comment by anettlinno** [comment]
@kevincrepin I think we can go with this but then I´d recommend to change the copy: 
- Create new topic
- Add existing topic

**Comment by BeccaMelhuish** [comment]
I think it's good :) 

I agree with Anett's suggestion above though, and think maybe for the menu heading as there's space we can write it in full 'Add or create a topic' (the / is a bit jarring). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d5c5e993-23ac-4b48-bcc1-22310b226210)

Am also wondering if just 'Add topics' would be enough for the button and heading, and then the menu section headings as Anett suggested, but not sure.. More sure to be clear with 'Add / Create topic' :)

**Comment by kevincrepin** [comment]
Updated the copy!

**Figma links** @ilmartyrk 
Desktop: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=745%3A79774&mode=design&t=2V1PbRKKFTzVJ5dC-1

Tablet: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=1064%3A107778&mode=design&t=2V1PbRKKFTzVJ5dC-1

Mobile: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=801%3A94447&mode=design&t=2V1PbRKKFTzVJ5dC-1

**Comment by BeccaMelhuish** [comment]
@ilmartyrk - just checked with Kevin and the 'Add existing topic' opens this existing pop-up :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1ebd4b1a-0143-4d30-8187-8ee1bd86ae8a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the menu

**Comment by BeccaMelhuish** [comment]
Thank you - this is good for testing now!  

I won't close it yet though as have some thoughts and bugs to report, but they're coming soon :)

**Comment by ssin1901** [comment]
@BeccaMelhuish I tested the functionality and the Create Discussion, Create Voting and Add Discussion all work (see screenshot). Let's report the UI bugs in a separate issue.

<img width="1404" alt="Screenshot 2024-02-06 at 12 45 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a1ba5d27-b16c-47ad-a9a9-007da309a1f6">
