### ISSUE TITLE
Voting: User wanted more than one vote question per topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#638]
@kevincrepin @anettlinno @ilmartyrk In one UX research call (where the user tried out the test platform to see if it would be suitable for his needs), a big drawback for the user was that it was only possible to add one vote question per vote topic. 

The use case was that it was a youth organisation wanting to use try the platform for getting feedback from board members on what should go into their upcoming strategy. 

He was very surprised and unimpressed that it was only possible to add one vote question to the topic, and the fact he would have to make a separate topic for each question was a key thing that put him off using it. He would prefer to use Google Forms in this case. 

It's not sure that he would use the platform for such a use case if we did enable more than one vote question (maybe he would still prefer to use Google Forms for such a use case - this is something that is starting to come out of the research), but is it something we want to consider doing? 

Probably needs quite some discussion/consideration I assume, and maybe some more research, but am adding the insight here for now, so we can decide what to do with it and when. I can give more input later once his call is more fully analysed, but this is some food for thought for now if you want to consider it already :)

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish @anettlinno I think I already mentioned it at one of our meetings, but anyway going to write it here too. There are not technical limits to how many votes a topic can have. Our current structure is that Vote "Object" doesn't rely on Topic but is connected to a topic, so this way we could have any number of Votes related to a topic. Vote "Object" in our database has the field "description" that we currently use to store the voting question. 

Only technical issue I see is related to UX where we possibly display 10 Vote questions that need users to sign their votes. In our current system it would meant that user would have to choose options for each question and after that also sign multiple times.

**Comment by anettlinno** [comment]
I would suggest to design and develop it as a separate template as I think it is for quite specific use cases. Here is one use case that I know from previous users: 
User wanted to co-create the development plan for their organization and after it was co-created they wanted to collect feedback on it and vote over different parts of this document. So, their need was
- description + argumentary + voting
- description + argumentary + voting
- etc

@BeccaMelhuish please also share the use cases for this specific use case and we can think and discuss how to solve this best -- either with template solution or adding as an extra feature to the voting system.

**Comment by BeccaMelhuish** [comment]
@anettlinno It was a similar sort of use case actually! Happy to share more details and I have insights from another voting test where this issue came up (in the end he was happy with creating different topics for each, but he initially had wanted to add additional votes to the same one for ease for the users). But just for time management, do we think this will be a phase II thing rather than Phase I? As if Phase II then I will focus on sharing other insights for now, and come back here to share more at a later stage :)

**Comment by BeccaMelhuish** [comment]
Adding Phase II tag as I assume it will be, please remove if not :)

**Comment by BeccaMelhuish** [comment]
Will close this one now, as linked to it from another similar one: https://github.com/citizenos/citizenos-fe/issues/1514
