### ISSUE TITLE
Inline-commenting feature is not working properly

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#64]
Original in [fe-old](https://github.com/citizenos/citizenos-fe-old/issues/1151)

**What is the problem?**
I answered on the comment that was left in the document and my text looks messy.

<img width="519" alt="Comments" src="https://user-images.githubusercontent.com/45175679/209099619-0c612769-1dda-44fb-aab2-fc002ab62df9.png">

**Why is this a problem?**
Text is not readable.

**Possible solution.**
Please fix the problem.

**Comment by anettlinno** [comment]
Triage 85. Could not replicate the issue, probably it is fixed with new updates. As we are changing inline commenting in redesign project then closing this issue with no further action. Please see issue #148.
