### ISSUE TITLE
Voting: Differentiate between add or edit deadline

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#640]
In this topic there is no deadline, but it says 'Edit deadline'. Should be 'Edit deadline' when there is a deadline, and 'Add deadline' when there isn't one? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0e112146-ad51-4331-b3de-4d499632faf6)

Also, I can't find a design for this, but this doesn't seem right to me - there is a tickbox when it isn't relevant to have one, and the dates etc don't need to be hidden behind another click in this case (and the text doesn't make full sense either 'You can choose or edit the deadline"):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/22dcb276-7462-48d5-86d9-752b28152808)

Maybe needs some designs from @kevincrepin (if there aren't already) for what the pop-up should be for both 'Edit deadline' and for 'Add deadline'?

**Comment by kevincrepin** [comment]
I will raise here also my though on maybe deadlines should not be editable. Kinda defeats the purpose and causes this issue of the "download vote results" closing the topic...

Adding deadline should be possible though.

If – and that's a big if – we make deadlines not editable then we need to communicate this also:
![Screenshot 2024-01-12 at 10 02 09](https://github.com/citizenos/citizenos-fe/assets/26792281/de11dd2b-f2b7-4917-b0bf-dbf17fb472c8)

**Comment by BeccaMelhuish** [comment]
I put my idea for this [here](https://github.com/citizenos/citizenos-fe/issues/595) in more detail, but I'm thinking we could allow the deadline to be editable only before it has passed (and therefore only before vote results are visible).

**Comment by anettlinno** [comment]
Let´s keep this issue for the initial problem -- edit and add deadline as in issue #595 is ongoing discussion about should we allow editing deadline or not :)

I also think it would make sense that if there is no deadline added, the Voting actions list display "Add deadline" and if there is a deadline then "Edit deadline". 

I´m unable to find the "Edit voting deadline" pop-up in designs, need you help please, @kevincrepin  :)

**Comment by kevincrepin** [comment]
Add or edit deadline pop-up (they're the same except the wording):
![Screenshot 2024-01-26 at 09 48 01](https://github.com/citizenos/citizenos-fe/assets/26792281/b1198a6e-29ba-4232-97b6-8deab4d9c17c)

It can be found in the components: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=452%3A63048&mode=design&t=yoDKb7xLADti0hlu-1

**Comment by BeccaMelhuish** [comment]
Except this bit of course, if it is editable :) 

And maybe we should change the heading to 'Edit voting deadline' when they have arrived by clicking 'Edit deadline'?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a4089598-dfc7-46c6-a145-8f9ac2c6f2a4)

**Comment by kevincrepin** [comment]
Yeah that copy is a bit outdated :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin updated the view, if deadline is not set the text is add, if set it is edit

**Comment by ssin1901** [comment]
@ilmartyrk the add deadline button is added
<img width="1440" alt="Screenshot 2024-02-17 at 15 02 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bf03dd97-8787-4fdd-a537-5758515e0436">

<img width="1440" alt="Screenshot 2024-02-17 at 15 04 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/83ce1d61-b726-420d-8e6c-8b97af0a61c7"> is added 

However, the whole flow is still not clear to me, as here is the copy in the Figma (see screenshot). 
<img width="524" alt="Screenshot 2024-02-17 at 15 11 10" src="https://github.com/citizenos/citizenos-fe/assets/72747107/72792e17-dbba-4cf8-b738-f73e5e0895d6">

**Comment by ssin1901** [comment]
Flow seems reasonable for now, closing the issue
