### ISSUE TITLE
Groups: Adding topic to group doesn't show as registered

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#642]
When user was creating a group, he selected a topic to add, but it didn't show anything as having happened. There was no sign that it had been added (it had actually, when we carried on - it was there in the group). 

Screenshot shows him selecting topic, and then what it looked like after he had selected it - same as it looked before he opened the drop-down: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8e8f2921-5086-417e-8a6b-f0a041c1b237)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should be fixed now

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish tested and it seems to be working okay (see screenshot1, screenshot2, screenshot3). Though I'm soon going to open a separate issue based on screenshot3. But closing this current issue for the moment.

<img width="1403" alt="Screenshot 2024-02-05 at 12 52 30" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9d86c11a-7303-4ef7-8b7d-73c84cbeaf89">

<img width="1402" alt="Screenshot 2024-02-05 at 12 52 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/572ab996-e7e5-4696-92d4-903c6eec7957">

<img width="1404" alt="Screenshot 2024-02-05 at 12 52 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/70aabb5e-9193-4b76-bc26-bbeec3d9c20a">
