### ISSUE TITLE
Group: Error message only displays briefly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#643]
When user got this error message, it seems the error message only appeared for a couple of seconds, then vanished. Should stay open unless he clicks the X? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5c8f2df6-f0e1-47bf-a7be-615de799992a)

**Comment by anettlinno** [comment]
It stays for 5 seconds and then disappears, which in my mind is quite convenient. When I start typing topic´s name then it´s disappeared. @BeccaMelhuish please check again and let know WDYT?

**Comment by BeccaMelhuish** [comment]
I checked the video and may be around 5 seconds, but definitely too quick! 

Verbatim from the test: 
"OK, now I'm _really_ confused. An error message, and then it goes on to something else before I can read it..". 

Also I wonder what is the use of it being timed at all? Shouldn't it just stay there until the user does something else (closes the window, searches again, etc.)? :)

**Comment by anettlinno** [comment]
I think we can also just leave it there and not time at all.

**Comment by BeccaMelhuish** [comment]
OK perfect yes :)

**Comment by anettlinno** [comment]
Triage 100. Sending to do. Est dev time 30 min.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
To me, it seems quite acceptable for this phase that the error message occurs when a user hasn't added a topic (screenshot1) and stays until the user adds a topic (screenshot2). Closing this issue.
<img width="1440" alt="Screenshot 2024-03-27 at 12 13 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d548fb77-d095-47b5-81dd-64cb2c492021">
<img width="1440" alt="Screenshot 2024-03-27 at 12 13 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/56998c83-b57e-466e-83e6-c6cd00e32223">
