### ISSUE TITLE
Groups: User's group displays different to the rest

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#644]
The group a user made displays differently, with some a smaller box and some elements missing: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/56fd73ff-7b6c-4731-b3cf-06c49f4bbbc2)

**Comment by anettlinno** [comment]
Triage 100. @kevincrepin we are a little bit confused, which is correct one, either the view under the components (joined / not joined) that is implemented today: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/aeccab7a-50cc-44c0-98e3-0512a9742319)

OR in Figma under My groups & Public groups:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/9847854d-0255-4a29-b10c-d2081d50ecf5)

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish  updated the not joined boxes to have follow-up icon and correct numbers

**Comment by kevincrepin** [comment]
Idea was that those groups you haven't joined would be the cards that have the join buttons and the quick stats. 

The groups you have joined (ie. under My groups) would show the latest active topic.

![Screenshot 2024-02-07 at 09 02 56](https://github.com/citizenos/citizenos-fe/assets/26792281/a498480e-0cb3-4eeb-9457-59f611a635c8)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I'll close the issue
