### ISSUE TITLE
Profile: Profile is now twice in menu

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#645]
The new profile UX has been going swimmingly in the tests so far, but we have it twice now - @ilmartyrk presumably it should be removed from the lower section now we have it at the top :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d95ba575-f020-47dd-9886-635c9def99ab)

**Comment by anettlinno** [comment]
Closing this issue as this is solved.
