### ISSUE TITLE
Group: Odd view after following group join link (to own group) 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#647]
User tested what he thought would happen for a participant he was inviting to his group, by copying the group's invite link, opening a new tab and pasting it in there. 

He got the 'Join group' dialogue box, then when he joined it took him here - which seems wrong for two reasons: 

1. I would think it should take them into the group, rather into "My groups". (Though maybe this is to do with it actually being his own group he was 'joining' - so not a very usual behaviour?). 
2. I checked the video a couple of times and it looks like it opened with the Country filter drop-down already open like this (it doesn't look like he clicked it). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/454fa5a7-e072-4b55-bb02-ff1fdcce7d8d)

**Comment by anettlinno** [comment]
Triage 100. Sending it to do. Est dev time 10 min.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Fixed and closing
