### ISSUE TITLE
Voting: Can't untick an option

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#649]
**What is the problem?**
I was setting up a vote and after ticking and unticking both options, I discovered the latter one (All votes are in) cannot be unticked, even if I've decided to choose the "Deadline" option.

<img width="905" alt="Screenshot 2024-01-15 at 11 40 54" src="https://github.com/citizenos/citizenos-fe/assets/34126353/a5b608c9-8d79-4fba-96e4-e4b0fb706cba">

Mac, latest Chrome.

**Comment by ilmartyrk** [comment]
@oksks closing the issue as the option is removed
