### ISSUE TITLE
Voting: Votes calculated incorrectly

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#650]
**What is the problem?**
I closed a voting, which had 0 votes, but the counter says "0/1 votes counted" - maybe should say "No votes".
And offers to download a ZIP, which probably should be hidden in case there are 0 votes.

<img width="897" alt="Screenshot 2024-01-15 at 11 46 22" src="https://github.com/citizenos/citizenos-fe/assets/34126353/a094e1c0-9834-454a-a978-dc6e6f9b5aaa">

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish @kevincrepin @oksks I was thinking that maybe it would make sense to remove all these n number votes out of x counters and change it to simple x votes counted. We still have issue to solve regarding topic members counter and invited users who haven't accepted invites yet and we also don't have the required votes input on the UI and API side too.

**Comment by kevincrepin** [comment]
I would be ok with it

**Comment by BeccaMelhuish** [comment]
I don't see it would cause any major issues either, if an admin wants to see how many topic participants they have (to check if everyone who's joined has voted) they can easily see it in the participants box :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin though we would need to think about what goes here in that case:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2f02665e-bc40-4285-bbb3-e130f8c29ebe)

**Comment by kevincrepin** [comment]
We would need to lose the "2 votes needed" in any case since we don't have this "all votes are in" option anymore. So that is removed and "Votes collected        2" :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin and presumably the bar would go too, as at the moment it's like a progress bar?

**Comment by anettlinno** [comment]
Very much agree with loosing the "n number of votes counted" and "n votes needed"

**Comment by BeccaMelhuish** [comment]
Example of the bar 'in progress' as well, that will need some thought/just removal:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/136628cf-d554-4e98-8e38-68f55a732748)

**Comment by kevincrepin** [comment]
I think just removal.

**Comment by ilmartyrk** [comment]
@oksks @BeccaMelhuish @anettlinno  Updated the view

**Comment by ssin1901** [comment]
Looks okay to me (see screenshot) and closing.


![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/cb1bdc43-9577-4370-acda-ca7b755bcb0a)
