### ISSUE TITLE
FILTER: error message when filtering

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#654]
**What is the problem?**
As a User I will receive an error message when trying to filter topics. 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/b6285dab-4568-4f3c-84dd-bf051690a89f)

**Why is this a problem?**
Unable to filter topics.

**Possible solution.**
Please fix.

**Comment by anettlinno** [comment]
Triage 99. Some more issues came up when tested. Needs some investigation. Adding pre UX test tag to fix it asap. Sending it to do.

**Comment by ilmartyrk** [comment]
@anettlinno issues is now fixed

**Comment by ssin1901** [comment]
Tested and now working (see screenshot1 and screenshot2)

<img width="1358" alt="Screenshot 2024-02-03 at 15 59 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1f9989cc-459e-4274-a59f-e5cf35324557">
<img width="1360" alt="Screenshot 2024-02-03 at 16 00 10" src="https://github.com/citizenos/citizenos-fe/assets/72747107/85df32aa-bd7a-41eb-9760-55a3a9e46bd3">
