### ISSUE TITLE
FILTER: code in the filter tab

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#655]
**What is the problem?**
The filter combination of Topic Type>Hidden by Admin leads to code being displayed in the _Status_ filter tab (see screenshot)

<img width="1317" alt="Screenshot 2024-01-16 at 16 56 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/da85178b-c667-4a74-bd4c-5ce3fa84a3dc">

+ add screenshot / screencast whenever possible

**Why is this a problem?**
Does not prevent the user from using the filter tab but can still confuse the user and make the application look less professional.

**Possible solution.**
Code should not be displayed in the filter tab regardless of result from the database.

**Comment by anettlinno** [comment]
@sara I´m unable to replicate this issue. Could you please let know which device and browser you used.

**Comment by ssin1901** [comment]
@anettlinno on Mac OS Safari and Chrome. Sorry I forgot to mention. But I am still getting the issue myself even after clearing the browser cache. 

<img width="1440" alt="Screenshot 2024-01-23 at 14 20 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/622c0933-fd46-44e8-a18c-63af4d399aaf">

**Comment by ilmartyrk** [comment]
@anettlinno @ssin1901 issue is now fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot)

![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/1e7fc817-2a36-4655-add0-75541bf77e39)
