### ISSUE TITLE
Emails: Text issues in invite email

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#657]
- "Topic title" in subject heading
- Blue bold should be for hyperlinked headings? This one isn't linked - should it be linked to the topic?
- Same as above, but shouldn't be linked, and also should be "In progress".  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/edf43dc5-d963-496d-8d99-f87e1e824c5b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is fixed

**Comment by ssin1901** [comment]
Should be fixed but please keep an eye for recurrence.
