### ISSUE TITLE
Topic: Update Categories for Phase I

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#659]
@anettlinno @ilmartyrk There's been some consistent user confusion and a bit of frustration relating to the adding of categories to topics, which I will share in more detail soon, but am I right in understanding that's in Phase I its not actually possible to filter by Categories, and this will be added in a later phase? 

As if so, I am wondering if we shouldn't remove the request to add Categories for now, if there's actually no way to make use of the fact that an admin has added one? Then we can add it back in once the UX research insights has been considered, and the technical side of whatever solution we come up with sorted too? It feels like not too an important/useful a feature to me, at the moment, but could be at a later stage once more fully thought-through? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b159e411-bb41-437b-907f-3992bb919b0b)

**Comment by anettlinno** [comment]
@BeccaMelhuish you can actually filter topics under "Public topics" by categories. So, it´s there :)

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/d63c6d28-7aa0-415d-95e1-9c35d07126b7)

**Comment by BeccaMelhuish** [comment]
Ah OK! I was looking at 'My topics' (which doesn't have it, as below) but makes more sense for public topics. Though if someone is making a private topic, we currently still ask them to define the category when setting it up - am wondering if there is a point to that, or if it's only relevant to public ones (and therefore should only be asked for public ones)? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ffc0d8ea-ff8a-44bc-95a0-a3e28a775214)

But OK thank you, seeing as we do have a category filter already, I will share more soon re the confusion/frustrations in the tests :)

**Comment by BeccaMelhuish** [comment]
Should be fixed by 31st Jan ideally, more info coming soon

**Comment by anettlinno** [comment]
Triage 98. Let´s add categories filter in private topic filters as well, then it´s all there and users can add categories also on their private topics. 
Est. dev time 15 min. Sending it to do.

**Comment by BeccaMelhuish** [comment]
OK yes but that wasn't the problem actually sorry - didn't get chance to share the insights yet! 

Here they are :) 

- Users are getting confused and frustrated by the Categories. 
- They seem to all feel they have to add one, rather than it being optional (they don't notice it doesn't have an asterisk), but are struggling to understand them/find one or some that fits.
- They have pointed out that the list is very random/confusing/not working for them for a few reasons (not in priority order): 
1.  They are in a funny (non-alphabetical) order: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b2457e30-8daa-41ee-8e8d-bafab402d472)
3. There are random categories that don't seem to have much relevance to them. As one user said "I know the Jazz festival and the Opinion Festival, but I don't see how it's relevant to me". (Are these actually group names rather than Categories?): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0303ada1-846e-4c8a-8ef0-9f0f4aa3aa17)
4. The categories often don't fit how they word or group things, e.g. for a local government, he was making a topic for one of his strategy themes and saw ‘Health care and social care’ - "But we have Community in there so that would be misleading" i.e. meaning that 'Health and Community' are linked under one strand in their organisation. We have a lot of categories that are 'X and X', but I wonder how this was decided - would seem better to separate them out. 
5. Several suggested they would want to be able to make their own categories that are actually suitable to them. One said "It seems like others have been able to make categories, I feel left out". For the two that were trying to do big public consultations, this was linked to some extent to their [request for filters](https://github.com/citizenos/citizenos-fe/issues/670) or folders and other such things to structure the discussions and topics with. 
6. Sometimes they are confusing categories and adding one that isn't "correct". E.g. a very Europe-focused organisation added the category "EuroChangemakers" but I understand this was the category for a specific group that was once using the platform, not for Europe-focused changemakers in general. 
7. One asked if 'Varia' meant 'Other'. (And then suggested the option of 'Other' then you specify yourself, as per point 5). 

So my feeling from this personally is that this needs a bit more thought and we could even remove it for now, until we've worked out what it's real purpose and usefulness of this feature is (I don't see it that much myself at the moment - I get it to an extent but I think it won't be missed if we remove it while we think it through more), and then make the category names and UX of choosing/adding them make more sense for that?

**Comment by anettlinno** [comment]
Thanks for specifying, @BeccaMelhuish! It´s helpful :) 

I think let´s not remove the categories as I´ve seen them actually working well on our current platform and I also use them myself :) If you want see all the topics in certain category, then it´s very convenient. Categories also give us an opportunity to  gather information about what topics are being discussed the most, to learn more about our user profile. We can of course continue testing the usability with users and gather feedback, how to improve this feature. 

BUT I do agree that we should clean and update categories list and remove all the "projects" we have there. So, I would suggest to list them alphabetically in following way (with little help from my good friend Chat GPT): 

Agriculture
Animal Protection
Arts
Business & Industry
Civil Society
Communities
Culture
Defense & Security
Democracy & Open Society
Diversity
Education
Entertainment
Environment
Equality
Healthcare
Human Rights
Legal & Justice
Media
Migration
Politics & Public Administration
Public transportation
Religion
Science
Social Welfare
Sports & Recreation
Taxes
Technology & Innovation
Urban Development
Work & Employment
Youth

With copy (or someway else) we could try to make it better understandable that this is an optional. We do have the asterisks but maybe should also mention that in a copy.

**Comment by BeccaMelhuish** [comment]
OK nice, yes that's better! 

I would split out Migration and Cultural Diversity into two though personally - or maybe just Migration and Diversity as two separate ones. (We have Culture, and we have Equality, feels like Diversity on it's own is a good addition).  

Did our friend also say if we are missing any important categories? :) 

And yes maybe @kevincrepin can help with a way to make it clearer what is optional and what isn't (other than adding the words "(optional)" after each which gets a bit cluttered). For this one but also for others in the Create flow. 

Though actually maybe we don't want to nudge people too much towards skipping sections (if they are useful as you explained), but just make the UX of those parts as easy as we can? 

E.g. for this one (and other similar dropdowns - e.g. Language and Country, see #668), the categories that you have mostly commonly previously selected are 'remembered' at the top of the list, above a little line before it starts alphabetically?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2948bb4f-6720-4ea1-90aa-39c0620deaa0)

**Comment by BeccaMelhuish** [comment]
What about the question of whether users can add their own categories though (as several of them suggested)? 

Though I feel they may have been suggesting this for two reasons - one being that they couldn't find a relevant category for them (which hopefully we solve with our improvements above), and the other being they want more ways to structure big discussions with folders or filters (#670), which we can try to think through more thoroughly/holistically?

**Comment by anettlinno** [comment]
I think this list can improve in time, but I wouldn´t allow Users to add categories. In future developments we have tagging system which I believe is what you refer to, @BeccaMelhuish. Users can add their own tags and sort topics tags-based. Category is more like an "umbrella" to tags as tags might go too specific. 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/5999c817-0569-47b4-a17f-31d89e259393)

**Comment by anettlinno** [comment]
I made changes in the list according to your suggestions, @BeccaMelhuish. I´m quite sure we´re missing something here, but again, this list can improve and when ever we hear some category that our users are missing, we can just add it later :)

**Comment by BeccaMelhuish** [comment]
Ah right yes, had forgotten about the tags! Makes sense :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno updated the categories, also added the filter to my topics

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Great! Only problem is this below though, in a topic where I previously had some of the now removed categories.

@anettlinno We'll also need to think about how this affects transfer of topics from the current system, where they had categories that were written differently there - do we just delete those categories? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b66c4288-4c64-4403-b99d-d37a15c02a91)

**Comment by anettlinno** [comment]
Deleting those categories which doesn´t exist any longer makes sense IMO. If there isn´t any technical issues with that @ilmartyrk ?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno I added a fallback for these categories so that if a translation is not found it will use the actual category name in our system in English. So these labels in the image Becca added will look like citizenos and eurochangemakers

**Comment by ssin1901** [comment]
@ilmartyrk @anettlinno @oksks if I understood correctly, where a translation is not found the system will resort to the English name by default. 

However, it is a little bit confusing because then the order is not alphabetical anymore (see screenshot when the language is Estonian)

<img width="1405" alt="Screenshot 2024-02-04 at 17 46 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/729de23d-16cd-4eb8-9a60-677c91e04f1f">

**Comment by oksks** [comment]
@ssin1901, the aim is for the whole UI to be translated into all languages by the launch date, so that shouldn't be a problem:)

**Comment by ilmartyrk** [comment]
@ssin1901 @oksks there probably is the ordering issue even after translations are added as the current sorting is done by the category names that we use for our database. I'll try and add a fix, but I think it's not high priority

**Comment by ssin1901** [comment]
Tested Private and Public topics and it is working fine. I'm closing this issue for now (see screenshot). 

![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/d5d58d18-20fc-429d-9d63-407e3511b812)
