### ISSUE TITLE
DISCUSSION: "View edits" is missing an icon

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#661]
**What is the problem?**
"View edits" does not have icon in front of the text (as other options have)
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/dfe9b7cc-8d41-40f3-81f2-10db5714f79e)

**Why is this a problem?**
Design looks broken. @kevincrepin I think we need an icon design as I cannot see this option in our current design files:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/c1dedd96-9e05-42dc-982c-150604d8922d)

**Possible solution.**
Please add an icon.

**Comment by kevincrepin** [comment]
@ilmartyrk the icon is also in Figma, but to make your life easier, here's the svg: 
![View edits](https://github.com/citizenos/citizenos-fe/assets/26792281/7667215e-6cee-4084-b179-726557ecff29)

**Comment by anettlinno** [comment]
Triage 99. Est dev time 5 min. Sending it to do.

**Comment by ilmartyrk** [comment]
@anettlinno fixed the issue

**Comment by ssin1901** [comment]
Matches the SVG shared by Kevin (screenshot)
<img width="933" alt="Screenshot 2024-02-17 at 14 56 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ba368993-fccb-4fe0-8151-7be7711845e6">
