### ISSUE TITLE
Groups: More guidance needed on groups usage to easily share a set of related topics

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#662]
@kevincrepin @anettlinno @ilmartyrk 

From the round 1 tests, seems that we need to give more guidance/clues to users that they can use groups like 'folders' to structure their topics, or to share them all from one link, as this can be crucial to them seeing the platform as usable, but some are missing it. 

Users are generally understanding that a group is a group of users, who they can invite to their topics, like how we describe it in the tour as below. They're not so much understanding that a group is a place that you can collect related topics together like a folder. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/552a85bb-d20f-469c-a0f5-3c77dc27bfc7)

When they go straight to creating a topic, they then assume that for every new topic they create they will have to share each one individually, and give feedback that that wouldn't be practical, or that they would like a way to structure their topics. In one case, even with some hints and nudging to look around the platform more, he didn't find it. 

A couple of users did work it out, but one had prior experience of the current platform, and the other was quite uncertain to begin with, but tried creating a group anyway and figured it out along the way. 

There is also a problem with the idea of a group as 'a group of people', when it comes to public groups. As one user (who would have very much needed a group for what he was trying to do) read what a group is and said 'OK that's not relevant to me, as I don't have a group of people to invite'. Actually though, he did need a group to keep all his topics in a folder, and then be able to share that one link with the local public via social media etc. But because of understanding groups as a specific group of people to invite, he disregarded it (and therefore disregarded the platform as useful for what he wanted to do).  

Some thoughts from me on this: 
- This is a problem we've had with explaining groups in the HC as well - do we describe them as a group of people, or a group of topics, or both?
- From seeing the users miss the important 'folder' functionality of groups (and how important it can be to them deciding whether to use the platform or not), I'm thinking perhaps we need to describe groups more in this sense - i.e. focusing on it as a group of topics, rather than a group of people.
- We could also try communicating it as both, e.g. 'Collect related topics together, and share them with a group of people in one go'.
- However, this still has the problem of what if people are using a share link to share their group on social media, rather than inviting a specific group of people. In this case, like the user described above, they may not consider it relevant to them. 
- I wonder if we need to reconsider the naming of groups? Does something like 'Topic collections' or even just 'Shared folder' work better? A shared folder on Google is a similar thing - a collection of files that are shared with a group of people? 
- Also wondering whether we could separate out 'groups of people' and 'collections of topics' (not necessarily that wording, but could be) in the UX, so that they're not so interchangeable in the way we can talk about them. I.e. you can have a 'group' which is a group of people in a list that you can quickly invite to your topics/collections, and then you can have a 'collection' (or whatever name), where you collect related topics together. 
- When trying to communicate groups to users, it seems we can't rely much on the tour (users seem to either skip it or whizz through it). Some places where I feel from the tests it would be helpful to communicate it: 
*The 'Create' menu most importantly. 
*The 'Add to group' field of topic creation. 
*The empty 'My topics' and 'My groups' pages when a user arrives and has no topics or groups. (I have made a separate issue about this [here](https://github.com/citizenos/citizenos-fe/issues/664)). 
*Maybe the 'You don't have any topics yet' box can also help somehow.

**Comment by BeccaMelhuish** [comment]
If we do want to communicate groups more as groups of topics than as groups of users, then we might reconsider this icon too: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/193af066-128e-48bd-8efd-3e5ba000a691)

**Comment by BeccaMelhuish** [comment]
Added 'Pre UX tests' as it seems an important one (as missing this feature prevents users from working out how to make the platform work for them) so would ideally be before Round 2 tests, which start 31st Jan.

**Comment by kevincrepin** [comment]
Challenging concept...

I think separating 'groups of people' and 'collections of topics' might not be the way to go, because a "collection of topics" is at the highest level "your topics" and we can discuss the need to folder topics separately. But the whole point of groups is that these topics and these people are connected. So disconnecting them seems counterintuitive to me.

I do agree that the wording might be too vague or confusing. What randomly came into my mind is that these groups are basically "Communities". This word is inherently associated with people. From a communication and marketing point of view it's also a bit more human-centered.

Not sure if this would magically solve everything of course :)

**Comment by BeccaMelhuish** [comment]
I'm thinking for now we could just try the lighter fix of using copy to explain the usefulness of groups (not just as a list of people to invite) in these places, then see if/how much that helps? Maybe even visualising the topics within a group (rather than just the people) on the dashboard/My groups bit, rather than only relying on words? 

- Logged out dashboard (it is here a bit, but I think we can make it simpler/clearer/come through more prominently):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3fab0c25-f3b1-40ad-a54f-7059520c3360)

- 'Create' menu
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f8f657e9-0de3-4203-a31d-e8f30da7ae36)

- 'Add to group' in topic creation (they read this bit quite carefully, and it seems to be a key place they are getting their heads around groups and shaping what they think they are/do): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/eed9e70c-9f2d-487e-ae60-a1a8aecc0b73)

- Empty 'My groups':
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/748b86f2-c3b3-4f50-8ab3-cf8d467c1ce9)

- Tour (putting this one last as people aren't taking it/paying attention to it!) 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b060a02b-c371-4455-9ef9-e424d9d0fba4)
 
This still wouldn't really overcome the issue of public groups shared via a link not involving a set group of people much though (unless we try to do so with the copy but then that could start getting messy/confusing), but we can think more about that. 

I'm mulling over 'Communities' as a better option! First instinct was not so sure, but I can see how it could work better for a place that has both topics and people all as one, and not necessarily in a set 'list'. It does also have more the right vibe for us, than groups, which is indeed a bit cold. 

@anettlinno @kevincrepin maybe we could do an ideation on Slack with others in the team, for possible words that might work better than 'groups' to explain a space in which topics meet certain (but not always pre-defined, sometimes just public) people?

**Comment by anettlinno** [comment]
I´m pulling the breaks here to take some time for a pause @BeccaMelhuish 

Engaging a "Group of people" into decision-making process is why we exist! Therefore, a group of people contains all kinds of people -- not only a community (as this word has very certain and recognizable connotation), but all people who want to discuss on the topics that matter for them -- public and private. 

I very much agree with what @kevincrepin said -- this is not a collection of topics that we want to emphasize (like Google does) but it is a group of people we want to provide an opportunity to come together to discuss and make better decisions. **Groups on our platform are groups of people** and as @kevincrepin said -- these people and topics are connected. I also agree that **topic foldering system is a separate issue and is not the same as is the group**. 

If it is unclear for Users, then copy is one way how to explain it better, but we should not change our main principle of engaging people (and not topics) into the discussions. 

BUT @BeccaMelhuish  I read out that Users actually do understand correctly (in the way we want them to understand) what groups are: 
_Users are generally understanding that a group is a group of users, who they can invite to their topics, like how we describe it in the tour as below. They're not so much understanding that a group is a place that you can collect related topics together like a folder._
Because once again -- group is not a folder of topics, this is not how it should be used! If Users understand that group is "a group of users", then they understand it correctly!

So, according to what I read out from the user test, we need to communicate better:

- Every new topic they create/add into the group, will be shared with all group members
- Difference between public and private groups (first is open for everyone, latter is for invited people only)

We should make this communication very clear and stop describing "group of people" as a "group of topics".

**Comment by BeccaMelhuish** [comment]
Hey @anettlinno! 

The thing is, I don't think our groups are actually just a group of users, it's a bit messier than that and that's where the usability problems are coming in :) 

I felt the same when I was writing the HC texts about groups, and noticed that in some ways we talk about groups (and also in the way they function and are visualised) is in some ways as a group of users and in some ways as a group of topics. I was vouching for choosing one or the other (rather erring towards describing them as groups of users), and we discussed it and in the end we left it as a somewhat confusing mix of the two. 

If you think about it, we say all over the platform 'Add to group'. If a group is just a group of users, then users wouldn't be 'adding a topic to a group', they would be 'inviting a group to a topic'. (This is what I was suggesting changing in the HC texts, that if a group is a group of users, we should use wording that shows this - i.e. 'invite group to topic'). 

So actually, what we have with private groups is that they are _both_ a group of users _and_ a group of topics - they are a space in which the two combine. This is clear from the two tabs in the group - 'Members' and 'Topics'. 

In private groups I think the two combine quite evenly - they are as much a group of users as a group of topics, as in private groups there is a set group of people that the admin wants to access the topics which are in the group. 

But what makes it more complicated with public groups, is that groups are actually _more_ a group of topics than they are a group of users. At least in the heads of the admins who are creating them (which is what matters most). Sure, once people have joined a group, it is kind of a 'group of users', but not in the same more solidly defined way that a private group is.  

So to give more clearly the example of what happened in one of the user tests (which was similar to what happened in another):

- A user is running a public consultation, with 5 different themes. 
- To structure the discussion and make it more manageable, he wants to have 5 separate topics - one for each theme. 
- He will be sharing his consultation with the public via a social media join link. 
- When he goes to create his first topic, he sees the 'Add to group'. He has understood groups as a group of people he can invite to his topics. So he says "OK, I don't have a group of people to invite, so that's not relevant to me", and moves on, discounting groups as something he doesn't need to be concerned with.  
- He then starts to understand that (as far as he is aware) he will have to share each topic with a separate share link on social media. 
- He sees that this really doesn't work for what he wants to do: sharing all the different links in the social media post would be a real pain for participants, and they would struggle to find their way from one to the next - how frustrated they would be with the consultation leaders. 
- His verdict: The platform doesn't work for his needs. If only there was a way that all these topics could be collected together and all shared with one link!   
- Even with several (test-biasing) nudges to "Have a look around the platform and see if there's something that might help you make it work", he didn't work out that he could use a group to do exactly what he wanted to do, and therefore that the platform _was_ a viable tool.

So what I'm suggesting is: 
- Short term: we make copy edits in the places I indicated [here](https://github.com/citizenos/citizenos-fe/issues/662#issuecomment-1904390831), to try to make it clearer that you can use a group to share a collection of topics either to a pre-defined group of users or to the general public via a share link.
- Longer term: we keep ideating on this problem, and consider whether the word 'group' is actually the best word to describe 'the space in which a group of people and a group of topics come together'. And also whether there needs to be any difference between the way we talk about or name private groups (which are more like a group of users) and public groups (which are more like a group of topics). 

Hope that clears it up a bit :)

**Comment by BeccaMelhuish** [comment]
Hey @anettlinno just to check - are you still standing by removing the "pre-user tests" label? I think changing the copy in some of the places indicated above (which I think you agreed yourself would be a good solution) would be an important thing to test in the second round of user tests, to see if it makes a difference to users understanding of groups as way they can share several topics at once via one link, as described above :) 

I can suggest some copy changes tomorrow hopefully

**Comment by BeccaMelhuish** [comment]
@kevincrepin, @anettlinno My suggestions for copy tweaks here: 

- **Create menu**

'Create a group to quickly share related topics with a set group of people or via a public link.' 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/761246e5-e024-4099-9b38-742bcec4c273)

- **'Add to group' in 'create' process**

'You can add this topic to a group for which you have admin rights, either now or later. All topics in a group are shared with its members, and can be shared via the group's public link too.' 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/490c090b-9ca8-46c1-bb5a-1e5f4eef7a5e)

- **Empty 'My groups':**

'Join groups to engage in related topics. You can also create one yourself - to quickly share related topics with a set group of people, or share them via a public link.'

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7833b78e-4b23-4614-b75f-3ca2bbb9280b)

- **Logged out dashboard:** 

'**Groups – harnessing the power of the people**
- Invite people with a common interest to a group, to give them easy access to relevant topics
- Quickly share your group space of related topics via a public link 
- Join a public or private group that deals with topics that interest you'

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/02b0c7aa-7e85-4954-b34e-0d334e74cb51)

- **Tour:**

'Groups are a space in which people with something in common can access relevant topics. For example, members could be part of the same organisation or community. Or have similar interests or goals.

Groups allow a set of topics to be shared quickly and easily - either to invited members, or via a public URL or QR code. New topics can be added at any time, to which members get instant access.'

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1de9d30d-2286-45a0-8750-c9fd46b3d889)

@anettlinno I will add the 'pre-UX tests' label again as I feel pretty sure you won't object, seeing as you agreed this should be fixed with better copy, and there's nothing controversial here I don't think :) Would be great to have the texts finalised and switched before the 31st if we can :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the texts

**Comment by kevincrepin** [comment]
Just my opinion of course but for me "Groups", but potentially with a less vague term, should always be about the members. Yes you can "Add topics" but only because you want your members to engage with those. A group with a bunch of topics but only one member should not be seen or understood still as a "group". Yes it would be possible for users to interact with the function like this and I don't think we should prohibit this, but we also shouldn't encourage it or even talk about it at all. Because it completely defeats the purpose.

Again I'm feeling a term like "communities" would work better here and puts full emphasis on the "humans who have something in common" aspect of this function.

I'm not following this idea that we should acknowledge that this is a "hybrid of members + topics" because for me it makes things actually more confusing. We don't say topics are a "place where content and participants come together" although without the participants it would also not be using the function at its full strength. So why not approach Groups/communities the same way? Yes you can "assign" topics to a community if you want those members to engage with it. But the foremost thing is that it's a gathering of members.


PS: @BeccaMelhuish not sure do we need to repeat everywhere this inviting via mail, url or qr?

**Comment by BeccaMelhuish** [comment]
@kevincrepin yes I think you're right that the focus of a group should be about the members (as Anett said, we are all about the people), but just that we need to be clear in the communication what a group is for (i.e. what's the usefulness of them, one very key thing being all members having easy access to a set of related topics) and how people can access them (i.e. that there doesn't have to be a 'set group of people' you already know and want to invite, you can just have an open invitation shared via public link), which hopefully these texts I suggested would help with, but we can see how it goes in the rest of the tests? :)  

Re the texts I suggested, is there anything other than the URL and QR code that you'd change the wording of, or all OK other than that? (I think they're not that different to how we've described groups previously, just a bit clearer on the two points above). 

Re the URL and QR bit, I think we could just change it to 'a public link'? (A QR is a kind of link anyway). I will edit them in my suggestions above now, and see what you think :)

**Comment by BeccaMelhuish** [comment]
And a suggested for tweaks to two of my suggestions above, which I see were too focused now on the usefulness of a group than on its members - what do you think? :) 

**Create menu:** 
'Create a group to invite people with common interests to access a set of relevant topics.'

**Empty 'My groups':**
'Join groups to engage in related topics. You can also create one yourself, to allow people with shared interests to access related topics, either via email invite or a public link.'

This shows more that groups are a group of people, but that they are useful for sharing a set of topics, and can be accessed either via email invites (when you already have a group of people to invite) or via share link (when you don't yet have a group of people to invite).

**Comment by BeccaMelhuish** [comment]
Update from discussion with @anettlinno in roadmap meeting this morning:
- We should go ahead and test the new texts 
- We should keep the discussion open for future as it's an important one, and maybe we will need to differentiate between private groups and public groups (e.g. groups and communities)

But @anettlinno @kevincrepin, let's make sure the texts are as we want them for the tests? (As the ones on the platform now were just my initial ideas).  

Will summarise now the full set of proposed texts with edits based on Kevin's comments above - please let me know if OK and Ilmar can update them, or if there's something you would like changed :)

**Create menu:**
'Create a private or public group to invite people with common interests to access relevant topics.'

**'Add to group' in 'create' process**
'You can add this topic to a group for which you have admin rights, either now or later. All topics in a group are shared with its members, and can be shared via the group's public link too.'

**Empty 'My groups':**
'Join groups to engage in related topics with like-minded people. You can also create one yourself, to allow people with shared interests to access related topics, either via email invite or a public link.'

**'Groups – harnessing the power of the people**
'Invite people with a common interest to a group, to give them easy access to relevant topics
Quickly share your group space of related topics via a public link
Join a public or private group that deals with topics that interest you'

**Tour:**
'Groups are a space in which people with something in common can access relevant topics. For example, members could be part of the same organisation or community. Or have similar interests or goals.

Groups allow a set of topics to be shared quickly and easily - either to invited members, or via a public URL or QR code. New topics can be added at any time, to which members get instant access.'

**Comment by anettlinno** [comment]
> **Empty 'My groups':** 'Join groups to engage in related topics. You can also create one yourself, to allow people with shared interests to access related topics, either via email invite or a public link.'
> 

First part of the sentence could also hint on like minded people or that in this group there are topics, but also people with similar interests (perhaps _Join group to engage in related topics with like-minded people_). 

Here _You can also create one yourself_ it´s not clear what one can create -- either topic or group? :)

I think Public link is also good!

So, from my side, let´s change the copy :)

**Comment by BeccaMelhuish** [comment]
Perfect, thanks @anettlinno! 

Re the first point, sounds great and have edited it in to the summary above now :) 

Re the second point, it'll be under this heading on the 'My groups' page when you have none, so should be clear in that context I think? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f21cdca4-e999-4ea5-8b23-eb661437e038)

**Comment by kevincrepin** [comment]
From my end I think this latest copy works quite well, @BeccaMelhuish !

**Comment by BeccaMelhuish** [comment]
Super, thank you both! 

@ilmartyrk here are the final texts to be switched then :) 

**Create menu:**
'Create a private or public group to invite people with common interests to access relevant topics.'

**'Add to group' in 'create' process**
'You can add this topic to a group for which you have admin rights, either now or later. All topics in a group are shared with its members, and can be shared via the group's public link too.'

**Empty 'My groups':**
'Join groups to engage in related topics with like-minded people. You can also create one yourself, to allow people with shared interests to access related topics, either via email invite or a public link.'

**Logged out dashboard:**
**'Groups – harnessing the power of the people**
- Invite people with a common interest to a group, to give them easy access to relevant topics
- Quickly share your group space of related topics via a public link
- Join a public or private group that deals with topics that interest you'

**Tour:**
'Groups are a space in which people with something in common can access relevant topics. For example, members could be part of the same organisation or community. Or have similar interests or goals.

Groups allow a set of topics to be shared quickly and easily - either to invited members, or via a public URL or QR code. New topics can be added at any time, to which members get instant access.'

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the texts

**Comment by BeccaMelhuish** [comment]
Checked and closing! :)
