### ISSUE TITLE
EMAIL: Unnecessary attachment in voting reminder 

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#663]
**What is the problem?**
Voting reminder has an unnecessary icon-vote attachment, 
![image (15)](https://github.com/citizenos/citizenos-fe/assets/45175679/1d3e6a10-953f-42aa-b605-b054483e9dbf)

**Why is this a problem?**
This icon-vote attachment does not have any reason to be sent with vote reminder.

**Possible solution.**
Please remove attachment.

**Comment by anettlinno** [comment]
Triage 99. Est dev time 5 min. Sending it to do.

**Comment by ilmartyrk** [comment]
@anettlinno fixed the issue
