### ISSUE TITLE
Topics/Groups: Empty 'My topics' and 'My groups' when user first arrives

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#664]
@kevincrepin @ilmartyrk @anettlinno 

In the tests I've noticed that new users often quite quickly land on this empty 'My topics' page. ('My groups' the same, though they land their less quickly). 

They've not mentioned anything at this point, but I've sensed some confusion - they often start clicking on the filters, maybe to see if they can get anything to appear. It feels a bit disorientating/buggy anyway, to land on an empty page like this near the beginning of exploring the platform.

I think we should put something here so it's less confusingly blank, like the 'You don't have any topics yet' (and a similar one adapted for groups), but I also wonder if we could use this space to try and communicate certain things that a user might need to know at the beginning, if they haven't taken the tour (which the tests show most won't have). Something that springs to mind is the 'folder' functionality of groups as discussed [here](https://github.com/citizenos/citizenos-fe/issues/662), but there may also be other things in the tour which would be helpful to communicate here as well:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ef0804bb-6205-4769-8ffb-5d68f2b4e7a7)

**Comment by BeccaMelhuish** [comment]
Would be a good one to fix before Round 2 tests, which start 31st Jan.

**Comment by kevincrepin** [comment]
Very fair and good point @BeccaMelhuish , these pages need empty states. We can reuse the one we have in the dashboard and that should make it easier for @ilmartyrk to get this in place sooner rather than later.

My topics empty state: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11458%3A78261&mode=design&t=cdGvUcp5EzmNWfSd-1

My groups empty state: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11458%3A78896&mode=design&t=cdGvUcp5EzmNWfSd-1
(copy is needed for this one)

This would be short-term solution, but it's a good idea for long-term to think about some more substantial info or helping hand here.

**Comment by anettlinno** [comment]
Triage 98. Good solution, let´s implement it. 
Est. dev time 30 min. Sending it to do.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish It will probably need your hand for the copy text. 
![Kuvatõmmis 2024-01-26 152728](https://github.com/citizenos/citizenos-fe/assets/19904307/debe5da6-a899-4129-a732-524188484cb0)
`      "HAVENT_ENGAGED_GROUPS_DESCRIPTION": "Join groups to discuss relevant topics. Or create your own groups and invite members so they can participate in the related topics",
`

**Comment by BeccaMelhuish** [comment]
Just for the record am linking to [this issue](https://github.com/citizenos/citizenos-fe/issues/662) where the groups text was agreed, but @ilmartyrk my you be able to provide full-screen screenshots of these two views now, just so I can check and close it? Not able to check myself as I have topics and groups in both accounts :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this texts were already changed as in the issue you referred.
![Kuvatõmmis 2024-01-30 150714](https://github.com/citizenos/citizenos-fe/assets/19904307/2c143f0c-ccc5-4665-8163-947688d60640)

![Kuvatõmmis 2024-01-30 150801](https://github.com/citizenos/citizenos-fe/assets/19904307/8439b4f1-cb37-4e37-bf0e-a91126153f18)

**Comment by BeccaMelhuish** [comment]
OK thank you yes! I was wanting to see how it was looking on the whole page (rather than just that block itself) :)

**Comment by anettlinno** [comment]
So this issue is solved, @BeccaMelhuish ? :)

**Comment by BeccaMelhuish** [comment]
I wanted to check that it was looking good in how it was placed in the screen overall, though that is more for Kevin to give input really - in terms of the UX insights it is solved :) 

I guess I will get to see it in the tests, and can feed back if I see it's not looking good somehow, so yes will close :)
