### ISSUE TITLE
Topic: In vote settings, users think they have to choose at least one thing per section

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#665]
@kevincrepin @anettlinno @ilmartyrk 

This has come up in other topics too, but want to make a specific topic for it just so it's clear. 

In the vote settings, users in tests are assuming that they have to choose one or other of these two options, and not understanding what not choosing either of them will mean. 

This means they are sometimes selecting things they otherwise might not have done (e.g. enabling eID voting, or setting a deadline), and aren't understanding that selecting neither would me what we call internally 'social voting' in the first case, or closing the vote manually in the second case. (Note: there won't be 'All votes are in' any more, as that's agreed to be removed).   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/acaa307f-a344-4cc5-ba05-4c4decd282c1)

Related topics:
- [on eID](https://github.com/citizenos/citizenos-fe/issues/622)
- [on the deadline](https://github.com/citizenos/citizenos-fe/issues/595)

**Comment by BeccaMelhuish** [comment]
Would be good to fix before Round 2 tests, which start 31st Jan.

**Comment by kevincrepin** [comment]
These changes have a bit more impact than just removing an option. But I agree it's not very clear right now. 

I think we need to change the "Set up voting rights" a bit more specifically and, hopefully, more clearly:
![Screenshot 2024-01-21 at 17 56 19](https://github.com/citizenos/citizenos-fe/assets/26792281/65585ee0-b228-4e8d-93dd-ee08b32d336e)


A choice between "soft" and "hard" voting. Wording needs to be better, but basically we're separating this from the vote delegation. This voting right should be one or the other and then delegation is something to include and maybe we need to keep this separate entirely then.

And that same logic would apply also to the deadline, especially if "All votes are in" is removed as an option. It's also then rather something you "include". I think then it's also more clearly implied that you can also "exclude" it again if you want.
![Screenshot 2024-01-21 at 18 00 37](https://github.com/citizenos/citizenos-fe/assets/26792281/af2f4ef8-1da4-4d71-8032-c88a0b7702aa)

Figma: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11460%3A105968&mode=design&t=cdGvUcp5EzmNWfSd-1

**Comment by BeccaMelhuish** [comment]
I think this is good! Should solve the problems :) 

A few copy suggestions: 
- For the hard voting, it's actually not dependent on login, more that they must use eID when casting their vote, so copy should be rather this (and I've added an indication of accessing the signatures too): 
"Voters will have to use e-ID to cast their vote. Vote signatures can be downloaded at the end."

- For vote delegation, what about 'enable' rather than include, it seems clearer/smoother to me, and there is still an enable-disable binary? So:
Explanatory sentence: "You can opt to enable participants to pass on their voting right to another person."
Tickbox wording: "Enable delegation"

- Again I feel like 'include' isn't perfect here, but I see the logic of include/exclude so let's go with it! Suggesting mentioning editing and close manually though too, like this: 
"You can opt to include a deadline, which will close the vote automatically when reached. You can always edit the deadline, or manually close the vote at any time." 

(And I think you changed your mind on the 'voluntary' as I don't see it in the designs? But if not, then 'optional' would be better wording - though maybe then we would need to write optional on all of the optional ones..)

**Comment by kevincrepin** [comment]
Enabling is better, totally! 

Updated all copy in Figma.

And yes, I first had voluntary – indeed optional is way better – but then decided to remove it.

**Comment by anettlinno** [comment]
Triage 98. Good solution, let´s implement it. If a User has to choose either soft or hard voting rights and if User forgets to opt in either one of them, then before publishing, we should display an error message. 
We can reuse design, but @BeccaMelhuish please help with copy for the warning-message :)

Est. dev time 15 min.

**Comment by ilmartyrk** [comment]
Updated the view

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I checked this, and a few issues: 

- Some quite serious bugginess with these buttons and deadline setting bits - watch me struggle in this [screen recording](https://www.loom.com/share/537e63b07a4f4023babf0b02c0f35eea?sid=bdc57d17-37fb-4614-a7fd-e3057fd3727d) :D 
(The two issues being it's super difficult to deselect, and sometimes also just select, the tickboxes, and the deadline box closes as soon as you click on anything).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ba84dafc-5b1a-4767-b086-7345df300c55)

Laptop, Windows, Chrome if it helps. 

- I've added in the translation strings 'For soft voting only.' here, so that they know why it is greyed out when it is. Please make it live :) 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/df2ba8e7-9916-4eb0-aaea-64f1fe4e84cd)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix, also translation appears automatically if you add it as you did for this issue here

**Comment by BeccaMelhuish** [comment]
@ilmartyrk unless it's the lag (which I think not as the deadline box was working now, so if posted at the same time should both be? Or I should wait longer?) the buttons are still very temperamental - sometimes it works (to select or deselect) and sometimes it doesn't. 

Please see video below where I moved the cursor up and down very obviously to show when I was clicking - very many times the click doesn't do what it should (select or deselect the box):

https://www.loom.com/share/8d9b51ab6f6049d7b504640bf843943d?sid=444efc61-6942-4187-8aa4-7d64a76cb205

**Comment by BeccaMelhuish** [comment]
Also @ilmartyrk, just noticed this is the wrong text, I don't see a relevant line for this in the designs, so am suggesting:

'Choose how participants must cast their votes.' 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5ea2436a-63af-496f-a830-c2914c66ba59)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the checkbox and updated the description text for the voting rights

**Comment by BeccaMelhuish** [comment]
Tried it and checkbox works well now thank you! 
Just missing a full stop here :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/04f4f671-2021-4ca8-9b7b-9f1b0847c417)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the stop
