### ISSUE TITLE
Topic: Users are mistaking ‘Leave topic’ as a back button 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#667]
@kevincrepin @ilmartyrk @anettlinno 

A couple of users have mistaken this 'Leave topic' button as being more like a 'back button', as in not that they give up their rights as participants but just 'go out of the topic'. I guess more like 'Exit topic'. 

One clicked it then was very surprised to see what it meant (from the pop-up) and clicked 'no'. 
The other clicked it, glanced at the pop-up, clicked 'no', then changed his mind and went back and clicked 'yes'. Then explained he hadn't expected to be actually 'kicked out' of the topic.   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/98d2246a-8879-46c6-b1e0-72bcbd15d21e)

**Comment by BeccaMelhuish** [comment]
I think this is an important one to fix before Round 2 tests, which starts 31st Jan.

**Comment by kevincrepin** [comment]
I think we have once discussed this or at least I vaguely remember recommending not having this action at all there. You can check the prototype and it's not there. Instead there's an indication of your user-rights (admin/"group owner" or "Joined topic/group").

My suggestion is to not have that button there and let the "leave topic" be under the topic actions, which as per this [issue](https://github.com/citizenos/citizenos-fe/issues/680) would be – hopefully – more easily found.

**Comment by BeccaMelhuish** [comment]
I think that makes sense! 

Though to be consistent with wording elsewhere, wording re the rights should be:

- **Admin** 
- **Editor**
- Member (lowest level rights for groups)
- Participant (lowest level rights for topics)

I think the first two work well, but yes maybe for the lowest level ones:
- **Joined group**
- **Joined topic** 

Have put the ones in bold that I suggest we use :)

**Comment by kevincrepin** [comment]
All good for me :)

**Comment by anettlinno** [comment]
Triage 98. Let´s bring "Leave topic" under Topic Actions. 
Est. dev time 5 min. Sending it to do.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk, here it should be the following for topic participants / group members:

- Joined topic
- Joined group

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/159d2e70-cb60-405e-b222-41b7971652ce)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the label texts
