### ISSUE TITLE
Add link behind keyword(s)

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#67]
Original in [fe-old](https://github.com/citizenos/citizenos-fe-old/issues/937)

What is the user story?
As a User I would like to keep my topic clean and neat because pasting long external links inside the topic makes it look messy and long. I would like to add external documents, websites, other COS topic etc. link behind keywords that are marked with different color (usually dark blue).

What is the requested feature?
I see two options how to solve this:

I would like to add the link by double-clicking on the keyword(s) and click on the "Add link" icon on menu bar. That will open the pop-up window where I could insert the link and change the keyword(s).
OR I would like to add the link by double-clicking on the keyword(s), after what will open the window where currently I can insert comment or to create voting. By choosing "Add link", pop-up window will open and I can insert the link and change the keyword(s).
I want that linked keywords would be recognizable inside the text (different color is probably the best and most intuitive solution).
I also want to be able to remove links same way as I entered them.
Additional information.
N/A

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 I will close this one as it seems very out of date (hyperlinks were added, now missing but we have an issue to bring them back)
