### ISSUE TITLE
Discussion: Users would like to set their own argument filters

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#670]
@kevincrepin @anettlinno @ilmartyrk

When working out how to try to structure a big public consultation on a strategic plan with potentially a very large number of participants/arguments (the whole municipality and their views) and a number of different themes (e.g. Economy, Environment, Transport, Education etc) and sub-themes (e.g. within education: kindergarten, high school, university, adult learning, etc.) they would like to be able to provide their own filters to be able to manage the possible influx of arguments, so it's not just one long string of arguments. 

Both of the users who tested this scenario separately suggested they would need the same thing (these filters). One user worked out (with some help from me in the end as it wasn't intuitive to him) that he could use 5 different topics within a group to structure based on the 5 broad themes of the strategy (e.g. Economy, Environment, etc), so was more happy without the filters in this case. But the other said that even if she had separate topics for each theme, she would want filters/categories for the arguments (e.g. within education: kindergarten, high school, university, adult learning, etc.).

The way it would work in their ideas would be: 
- As an admin they could enter their own categories for the different possible arguments
- For one, they wanted this to replace the 'pro, con, informational' options, as he wasn't keen on them (will make a separate issue about that) 
- For the other, before they posted their argument they would have to select a category. She also liked that this would nudge the participants to think along the lines of the structure of the strategy - it would make it more manageable for them. 
- One of them explained that once people have entered the category for their arguments, it would mean there could be a filter for the arguments, so you can filter from all the many arguments (in the ideal situation, hundreds) and go straight to the issue you are interested in, or check what someone has already said on what you wanted to say).   

Having this way of structuring and managing a big discussion would make it more likely they would use it for public consultations. As it currently is, they wouldn't want to, as they would just have a huge long string of arguments which would make it very difficult for the participants to have a constructive discussion, as well as for them to sort and take insights from the discussion - a bit of a headache to try and deal with. 

Again, like with [this issue](https://github.com/citizenos/citizenos-fe/issues/669), it may be that this feedback is more something to consider for the ideation feature, as what they were trying to do was much more idea-gathering than a pro/con discussion. So perhaps the addition of the ideation feature would remove the need for this from discussions. But we do already know we have the issue of having long and unwieldy discussions when there are lots of arguments. Maybe this gives some thoughts on how to allow admins to better manage it?

**Comment by BeccaMelhuish** [comment]
Am assuming this would be more of a Phase II thing to have more time to consider, so have added the tag, please remove if not the case :)

**Comment by anettlinno** [comment]
Removing Phase II tag as this topic needs more discussion and will not be the case in Phase II. 
This is the massive input problem where we are trying to find some good solution (our AI-developer is looking for machine-learning opportunities, where we could group and cluster arguments semantically). We have discussed tags system as well, but it would probably get quickly messy. We have tried out arguments foldering system, but again, same case that there would be too many folders and admins should still do it all manually... 

Currently people can sort pro/con/info arguments and in the future there will be added more filtering options:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/4f9a5b93-50fd-4855-9607-f5f0dc2698b5)

There is no easy solution there for now. But let´s keep the discussion on.

**Comment by BeccaMelhuish** [comment]
I will close this one for now, as I feel it may be solved or at least changed now that we have the ideation feature (with folders that can be used for categories, potentially by participants if we implement that). Will keep an eye on this in future research though.
