### ISSUE TITLE
Profile: "Show my profile in search results" options incorrect

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#671]
**What is the problem?**
There's some mixup with the options under Profile:

![Screenshot 2024-01-17 at 15 20 11](https://github.com/citizenos/citizenos-fe/assets/34126353/d7ad1223-33b1-4d56-8498-93944397a850)

"Show my profile in search results" is displayed twice, and "Delete account" button is glued together with the second option, while it should be a separate, standalone function.

Btw, is the displaying of the profile turned off by default? I think it was turned off in my case. Can we have it turned on by default, to allow users to find each other?

**Comment by anettlinno** [comment]
@oksks by default User profile in search must be turned off as it requires User´s consent to show it publicly. When a User turns it ON oneself, then we´re all good.

**Comment by ilmartyrk** [comment]
@oksks @anettlinno the setting is off by default, tested it and works fine. Also fixed the texts

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1294" alt="Screenshot 2024-03-06 at 13 08 05" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7398b9b0-62f3-441e-a514-76c63312af5b">
