### ISSUE TITLE
Topic: Topic updated notification (after editing) a bit wonky

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#674]
As shown here: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d214e5e6-adc8-4817-bcf6-3a3da3acc499)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is fixed now

**Comment by ssin1901** [comment]
Fixed (see screenshot)
<img width="1287" alt="Screenshot 2024-03-05 at 16 27 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0fc33219-c1dc-48f4-a53e-e26bfd309a42">
