### ISSUE TITLE
TOPIC: Add "Save" topic in editing mode

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#676]
**What is the user story?**
When editing an excising topic, then currently User has to click "Continue" in text composing view, settings view and only in Preview mode can click on "Save changes". But after I finish editing, I would like to save the changes right away and not click through the entire flow. 
<img width="524" alt="image" src="https://github.com/citizenos/citizenos-fe/assets/45175679/70c8692b-1bfe-4fbd-8b77-d0d689d01092">

**Which feature needs to be updated and how?**
Please add "Save changes" or just "Save" button in topic editing mode. After clicking "Save" button, I should have directed back to the published topic view. 

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Triage 99. @kevincrepin  we would need your design for the "Save edits" or "Save changes" button (also in mobile view please).

**Comment by kevincrepin** [comment]
Maybe I'm mistaken, but don't we have this already?

Desktop:
https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=482%3A62559&mode=design&t=mGZWYhdhylxuJwCW-1 

Mobile didn't exist yet but should apply latest changes: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11762%3A106012&mode=design&t=mGZWYhdhylxuJwCW-1

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno added the button, made some changes to the styles to also include publish button when topic is being edited in the draft status

**Comment by ssin1901** [comment]
@ilmartyrk this button doesn't redirect to the published topic view (screenshot1) but it does save the changes. Tested on Safari and Chrome, also in incognito mode.

<img width="1197" alt="Screenshot 2024-02-16 at 12 18 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/719507a7-aeee-4745-b42e-67cd7c2f3dc7">

**Comment by ssin1901** [comment]
Closing, this looks okay to me (see screenshot)
<img width="1440" alt="Screenshot 2024-03-27 at 12 02 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f6d95a8f-d280-46c5-8d18-6a2b5c46748e">
