### ISSUE TITLE
Invite: Invite link didn't allow access

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#677]
Re what happened in the Strategy/Values meeting earlier, with me and @oksks having trouble with the topic access, this was how it went for me: 

- I tried accessing using the link @anettlinno shared in the calendar invite (presumably was a share link, so should have given access without an invite?) while logged into my gmail-connected account 
- I got some sort of error message (not sure what sorry!) and a fairly blank screen
- I thought it might be because I was in the wrong account - logged in with citizenos-connected account and tried again, same thing. 
- Saw that I had an invite email so followed the link that way, and accessed the topic fine.

**Comment by oksks** [comment]
Same, but I don't remember seeing an error message.. might be wrong - and the screen was also blank, light blue. I was logged in while it happened.

**Comment by BeccaMelhuish** [comment]
True, it's possible I didn't get an error message either - wasn't fully paying attention as was during the meeting :)

**Comment by anettlinno** [comment]
Triage 99. Duplicate issue of #621. Closing this issue.
