### ISSUE TITLE
Voting: Users are not (at all) finding how to see results before deadline has closed

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#679]
@kevincrepin @anettlinno @ilmartyrk 

An important one to focus on before the Round 2 tests (starting 31st Jan):

In 3 out of 3 cases where the user was trying to see the results of their vote before the deadline ended, they were all three completely stumped when it came to working out how to do it. They spent many long minutes looking basically everywhere but the 3 dots menu where 'Close voting' lives: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/313c3950-fe0b-46cc-8464-55c6feab2c52) 

There were 2 problems that were apparent: 

1.  They really didn't find that menu or expect it to be where they could get the results. (All 3 of them totally gave up without having tried clicking it, and I had to tell them in the end). 
2. The wording 'Close voting' was either confusing to them (one thought it meant more 'Delete vote' and she would lose the vote she'd set up), or wasn't what they were looking for - they were looking more for something like 'See results'. One user explained he hadn't thought he would have to close the vote before seeing the results. So even once I'd guided them to the right menu, they weren't fully confident that 'Close voting' was what they were looking for. 

They were all very similar in the places they were looking for it, but the clear 'winner' in terms of what they all were expecting and kept going back to (and also verbally said this is where they would expect it), was here:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7c099160-e523-4ea1-80ad-9d313991bc4e)

This is where it shows how many people have voted so is where they were looking to see how they had voted too. One user suggested he'd expect a 'See results' button to be there. 

A few other places they commonly also looked were these:

- In the upper part of the topic (scrolling up to see if it's up there)
- Around the vote box itself (but not noticing/clicking the menu) 
- In 'My topics' on the card for the topic (trying clicking various bits of it)
- In the Follow-up tab
- In 'Manage' (in the 'Participants' box)
- In the 'Information' box

So to fix this, my suggestion would be that we put 'Get results' or 'See results' in a more obvious place (ideally in their shared first instinct place shown above), and then explain in a pop-up that by seeing the results they close the vote (rather than the other way around as we currently have it).

**Comment by kevincrepin** [comment]
My first question is "Should they be able to see the results before the end of the voting?" Just wondering what was the scenario during the testing that prompted them to look for this.

Also important to now what we communicate to the user. Do we communicate to end the voting phase (and as a result you'll also see the results) or do we communicate to see the results (which would cause the voting to be closed). One implies what follows better than the other in my opinion. Seeing the results would not necessarily make me expect that that also closes the vote.

I'm just a bit hesitant to have a button somewhere saying "Get the results", clickable at any time whereas the voting might still be in full swing. It insinuates that you can see the results without having to close the vote so it's then disappointing to be told that you actually can't see the results "just like that". 

I get that "closing the vote" under the 3 dots might be too hidden now and the wording might be confusing.

What if we have an action "finish voting phase & get results"? Long label but basically says exactly what it does. And we would still have the "are you sure" dialog box as well. And the vote actions would have a label to make it clearer and more prominent.

**Comment by kevincrepin** [comment]
I also vaguely remember that at one point we have this dialog window where you could see which people had voted – not what they voted for, just that they voted. And this was something we removed.

**Comment by kevincrepin** [comment]
What if we add this additional line to the voting module? Note also the **vote actions** updated button and the deadline is now placed with the votes collected – also makes sense with the reminder action there.
![Screenshot 2024-01-21 at 18 17 46](https://github.com/citizenos/citizenos-fe/assets/26792281/30e2975b-a5d1-4561-887c-1967be35256c)

**Comment by BeccaMelhuish** [comment]
@kevincrepin I think this all makes sense! And the label for the menu should make it more visible :) 

Copy wise, some suggestions:

- Could we call it 'Manage vote' instead of 'Vote actions'? One user explained that why he hadn't been looking where we put it, was that he is also able to vote in the topic (as well as be admin of it) and he had thought of that section as more about his own vote than about managing the vote overall. And they were often clicking on the 'Manage' button in the participants, which makes me think manage is the right wording. 
- And for the sentence, to shorten it a bit, how about: 
"The results will be shown once the vote ends. You can end the vote at any time in the manage vote menu."

**Comment by kevincrepin** [comment]
Would it be clear that "manage vote" would be "manage the vote settings" rather than "manage **your** vote"? I guess we can see from the users.

Copy updated in Figma!

**Comment by BeccaMelhuish** [comment]
This is a good point! But OK yes, let's see in the tests :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin Actually, wondering now if we don't just go with 'Manage' for this one too, as we now have 'Manage' buttons in participants and topic info, so would be nicely consistent? And maybe that takes away a little(?) from the problem with 'Manage vote' (yours or the whole thing) you raised above?

**Comment by anettlinno** [comment]
Triage 98. Let´s implement provided solution. 
Est. dev time 30 minutes. Sending it to do.

**Comment by ilmartyrk** [comment]
Added this update, though it took quite a bit more time than I initially thought as I had done a mess with the code

**Comment by BeccaMelhuish** [comment]
Thanks Ilmar! 

Just noticed something though, can we change the text to 'You can close the vote etc......' so it matches the menu :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cedb1d12-d8c7-4024-8fbd-87615ffc5000)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I couldn't find this in the translation strings to do myself, so just a reminder to make the minor copy change and then this one can be closed :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this was already fixed with previous translation updates
