### ISSUE TITLE
Topic: Users aren't (at all) finding the top-right topic menu - edit, add to group, etc. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#680]
@kevincrepin @anettlinno @ilmartyrk 

Another important one to fix in Phase I and before the Round 2 users tests (starting 31st Jan), is that users aren't finding this all-important menu:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/db0e54ea-f35c-4d10-9612-d7fe8e6de6b6)

They are rather looking to do this in the area of the thing they are trying to edit, add, change the setting for, etc. 

Some examples of places they are looking for these sorts of actions (edit, add, change settings):

- Either expecting an edit/settings button for this box overall (e.g. where the public/private icon is top right, they often clicked that), or clicking on the individual thing they're trying to change, e.g. clicking on the attachments to edit attachments, or just clicking on all of the icons hoping one will do something: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ad3573c1-b773-4c93-ba5f-bf398fb2f87b)

- They are also often looking here and confusing this button for an 'edit button' rather than a 'created' icon. Same with the same icon in the participants box, users sometimes clicked it as if it's an edit button: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b7e5930e-077f-47d6-9159-0a6db617a3a3)

- For editing the topic text, one user explained that he would expect an edit button here, by the text: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bc554415-f889-45aa-ba97-5beefe967037)

- They also often seem to be confusing the 'Manage' in the 'Participants' box, as a possible place to manage the topic overall from, e.g. change settings, edit, etc.  

- One also tried the activity feed quite early on in looking for how to edit.  

In 4 out of the 4 tests where such things came up or I asked them how they would edit, add attachments, change visibility, etc., none of them found this menu (even after looking in many places for it). In one case, the user later on in the test found the menu, then realised that was where she could have edited from. In another case, he decided it would be easier to make a new topic than to edit the existing one. In the other two cases they gave up, and I told them at the end - one of those then said he was expecting that menu top-right to be more about his profile and settings for his account.

**Comment by kevincrepin** [comment]
Thinking/Hoping this could be easily solved by having a label for that button "Topic actions":
![Screenshot 2024-01-21 at 15 41 10](https://github.com/citizenos/citizenos-fe/assets/26792281/4f3f511a-3f5f-4bb6-868b-1eb90c263b1a)

https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11458%3A72382&mode=design&t=cdGvUcp5EzmNWfSd-1

Don't want to be adding button and actions everywhere because it will clutter the UI up very quickly.

**Comment by BeccaMelhuish** [comment]
I'm a little bit hesitant about this working, having see just how much they didn't look in that top right corner, and really were expecting it to be somewhere in the content (it was a bit painful to watch how much they struggled!). 

But a couple of suggestions that I think could help without cluttering up or moving things around too much:

- Could we call it 'Manage topic' instead of 'Topic actions'? As mentioned in the vote results issue, this feels like more the wording they're expecting/likely to understand. I wonder if we could also make it a more eye-catching colour than white? Or ideally, as they weren't looking up there at all, bring it further down towards where the action happens - next to the topic activity maybe? 

- I still need to make another issue about the information icons (tentative findings so far), but it seems the public/private icon isn't really being understood, and is also taking up quite a prime spot (they often clicked it when looking to edit/manage). And they often clicked 'Manage' in the participants box too. So, I am thinking, could we have a small 'Edit' button in its place (and work out what to do with public/private in a separate issue, but it's much less important to usage), same as the 'Manage' button in the participants box. This would take you straight to the topic Edit/settings tabs (I guess to Step 1). That way, you can either go straight with one click to edit/add/change settings, or you can go with two clicks to manage the less frequent things like duplicating, deleting, etc., that are currently up in the top right menu. (But we would still have the 'Edit topic' in the menu, this would just be a handy and much more findable shortcut). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/75eaa3cd-3709-41d7-b779-c61bda68339f)

**Comment by kevincrepin** [comment]
I like this idea to have the manage in the topic info card. I wouldn't want to highlight the existing button more than it is, but this "Manage" could work nicely. Maybe we should also rename "Information" to "Topic info" or smt @BeccaMelhuish ?

Then I would remove the more actions from the top and the "Favourite" action also becomes a bit lonely and weird there, so maybe that can be moved next to the topic activity?

![Screenshot 2024-01-22 at 17 17 12](https://github.com/citizenos/citizenos-fe/assets/26792281/35888622-8fe4-4f7a-a46c-031efa620af1)

**Comment by BeccaMelhuish** [comment]
@kevincrepin nice yes, I think this is a good solution!

**Comment by anettlinno** [comment]
Triage 98. Beautiful solution, let´s implement what @kevincrepin proposed. 
Est. dev time 15 min. Sending it to do.

**Comment by ilmartyrk** [comment]
@kevincrepin I also moved the join leave button to the actions menu or should it stay on the top next to the permissions? If not then we'll need an icon for the menu

**Comment by ilmartyrk** [comment]
@kevincrepin nevermind the previous comment, checked the designs found the icon for leaving topic and also left the join topic button at the top as it was in the designs

**Comment by kevincrepin** [comment]
Thanks @ilmartyrk !

@BeccaMelhuish it would be nice to find out if regular users (not admins) find how they leave a topic now actually. Because I'm just thinking that now that these topic actions are under "manage" make a lot of sense for the admin, for the regular user I'm not sure if they have the reflex to go there to find the actions they have access to...

**Comment by BeccaMelhuish** [comment]
@kevincrepin Oh yes very true! I

**Comment by BeccaMelhuish** [comment]
@kevincrepin Oh yes very true, 'Manage' is more suited to admins, and having it in that box makes more sense for admins too. But I think it still works OK, let's see. Unless we can think of a better word, but I think manage works to an extent also for 'manage my participation'. And at least having it in that box means they are much more likely to find it than when it was top-right. Will try to test :)  

I see the menu is currently missing for participants though, so @ilmartyrk please add it for participants too (but with only whatever actions they are meant to have there): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a3c89f40-be86-453c-ac2f-2e5c9f76aafd)

**Comment by kevincrepin** [comment]
Can also report topic and favourite.

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish added the link back for participants

**Comment by BeccaMelhuish** [comment]
@ilmartyrk menus are great but something's gone a bit wrong here, in the design they should be top right :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e7d8b22c-6c92-4240-9add-c91715fb6141)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2fa5516e-ab2b-456b-8c40-fc94209dc59c)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is fixed we also noticed it during our triage

**Comment by BeccaMelhuish** [comment]
@ilmartyrk just reopening as I noticed in one of my topics I have this menu twice now, should be just once in the topic info box: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/828d36ab-37af-463a-be57-2b602eaa4493)
