### ISSUE TITLE
IS: User confusion around topic invite by email

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#683]
@kevincrepin @ilmartyrk @anettlinno Another quite important one: 

In a couple of tests, users thought they had invited people but they hadn't (and weren't aware that they hadn't). There was also a common question 'Can I invite more than one email at once, or I have to add each one separately?'. They seem to be somewhat related so have added both together in this issue. 

The main one (I think the other may have been bug-related, will come back to add more to this issue after more analysis if relevant) went like this: 

User copied emails from a spreadsheet and pasted them like this, then added another one to the end by typing it. She was unsure if this was right (and voiced a question about it), but then clicked 'Send invites' and the dialogue closed. "OK I think it's good now" - so 'job done' as far as she was concerned, she would go away and wait for the votes to come in:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8325c59a-796a-4d47-81df-9b2b10075381)

Would be good to solve before 31st :)

**Comment by kevincrepin** [comment]
I would assume can add multiple, but separate it by a comma?

**Comment by BeccaMelhuish** [comment]
Yes I assume it's this too (hopefully @ilmartyrk can confirm), but how to let them know that (some copy presumably?), and also how to manage the flow of the emails appearing underneath so they can adjust the rights, for example, and so they see that they are added :) 

I.e. if I start adding some like this: 'becca@citizenos.com, anett@citizenos.com, ilmar@citizenos.com' do these 3 already appear below and therefore disappear from the box (even though I may have wanted to add a fourth one, I might not yet have finished the full list), as currently you have to select a name in order for it to appear below, like this (would they have to select each name?): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e75a33b8-57aa-4ba8-93b4-20d40506bd8e)

And should we have an error message that appears when you click 'Send invites' but nothing is being sent? I.e. the box stays open, with a message telling you you didn't actually add anyone to invite, like we do here:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a7690756-4ba7-4773-99b4-9202035dc3e4)

Also, if someone does add a list like this with no space, should the box turn red or something?
'becca@citizenos.com anett@citizenos.com ilmar@citizenos.com' 
Or, even better, @ilmartyrk can we accept lists with just spaces not commas, as this would be much smoother for users (they are probably usually copying from a spreadsheet, and would then have to go though and add 100 commas if there were 100 people in the list...

**Comment by anettlinno** [comment]
In our current version (which works really nicely IMO), when inserting emails from excel and pressing enter, they are inserted and list of added users is being displayed. 
When names are in a row (like @BeccaMelhuish suggested [here](https://github.com/citizenos/citizenos-fe/issues/683#issuecomment-1906110786)) are being inserted to the email field, then system automatically adds commas in between and when clicking enter, emails are displayed again. 
When inserting emails manually then both works -- with comma and without comma.
And when clicking on "Send" button without system sending anything out, error message appears. 

I think our current flow is well-tested and works nicely and we could reuse that.

**Comment by anettlinno** [comment]
I also agree that copy should mention somewhere that Admin User can add up to 50 emails in a row and paste them from other document (User don´t need to insert them manually).

**Comment by BeccaMelhuish** [comment]
The trouble with this would be, they don't necessarily think to press enter.. 

In fact I just checked and it's already the same on the redesign, if she had pressed enter in the test they would have appeared, but she didn't think to (and it didn't occur to me either 'til reading the above that she could have done). 

So I think it's not a good solution and we should make it more intuitive :) 

There is an option that 'Press enter to add' appears (like we have currently) when you have a list (but not when you have just one), but I'm not sure if this is the best UX, @kevincrepin what do you think?

**Comment by anettlinno** [comment]
Coming back to reusing what we already have now and not inventing a wheel again :)

When inserting email addresses, then "Press enter to add" appears and "Save invites" button is grayed out. I think this is good UX, @BeccaMelhuish, because you have to enter emails before sending them. WDYT?

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/b0bdc288-2d5f-4363-baad-04e9bf11539c)

**Comment by BeccaMelhuish** [comment]
OK yes let's do that (unless Kevin has objections/a better solution) :) 

And for the copy we could add the text: 

"Add up to 50 emails at once, with a space or comma between each." 

I guess it would go here, in regular rather than bold copy (however it is done elsewhere): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fa2c2732-11ea-421d-8bb0-5e1f077c5fc0)

(Side-note: should it not be 'username' rather than 'name' here?)

**Comment by anettlinno** [comment]
@BeccaMelhuish yes, it should be "username" as people can have different usernames than their names :)

**Comment by kevincrepin** [comment]
I'm ok with this ;)

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno @BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I checked this one and a few tweaks are needed :) 

- Seeing as the 'Press enter to add' looks like a link, let's make it possible to also click on it to add (like we have with the current platform)? 

- After the emails have been added the 'Press enter to add' currently stays put, it should disappear:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b648aa33-d5f0-4e40-8ee4-91331135d1a6)

- When there have been no emails actually added, the 'Send invites' but should be greyed out and not clickable (like on current platform):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c036c0a2-cb56-4e03-b9c4-a620cca371ee)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
Checked and works like a dream thank you, closing :)
