### ISSUE TITLE
TOPIC: Incorrect topic creation flow when title field is empty

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#684]
**What is the problem?**
Replicated in Mac OS Safari, Chrome and iPad Safari.

When a user goes to Create->Discussion and leaves the title field empty (see screenshot1) 

<img width="1440" alt="Screenshot 2024-01-23 at 15 28 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5811d4b0-c620-4f8b-b5e3-67e0adbabdba">

They are able to click "Continue" and complete the flow all the way up till _Publish your topic now_ (see screenshot2) and clicking _Publish your topic_ now shows them the message that the topic has been successfully published (see screenshot3). 

<img width="1440" alt="Screenshot 2024-01-23 at 15 33 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b812e180-2206-4fc3-bc77-e54b9aac2594">

<img width="1439" alt="Screenshot 2024-01-23 at 15 33 15" src="https://github.com/citizenos/citizenos-fe/assets/72747107/92cc6980-bb32-4c5f-8f48-c26a09be3a2e">

However, the topic is not added via My Topics (see screenshot4)
<img width="1440" alt="Screenshot 2024-01-23 at 15 38 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/09920f75-8cb5-43fd-ad67-26ea49c07a19">

**Why is this a problem?**
The red * indicates that it is compulsory for the user to add a title in order for the topic to be successfully saved and therefore published in the database. However, the user is able to complete the entire flow without inputting a valid title. 

The user also receives a message confirming that the topic has been successfully published, when it hasn't been.

**Possible solution.**
User should not be able to complete the flow without adding all the compulsory fields (title, intro, description) OR the fields should not be marked as compulsory and with a default title, intro or description (Eg. Your topic title here... )

**Comment by ilmartyrk** [comment]
@ssin1901 fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot)
<img width="1439" alt="Screenshot 2024-02-22 at 20 33 51" src="https://github.com/citizenos/citizenos-fe/assets/72747107/99d85fb4-c2e2-48ac-b70b-abfc86ff996b">
