### ISSUE TITLE
ACTIVITY FEED: Is missing closing X and is not closing when clicking elsewhere

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#685]
**What is the problem?**
When opening Activity Feed, I´m unable to close it as it´s missing X and is not closing when I click elsewhere.

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/252dfa26-2cc9-4072-89dc-b3647b736d67)

**Why is this a problem?**
Disturbing the view and freezes the page (unable to scroll up and down). I only get rid of it when clicking somewhere in the main menu.

**Possible solution.**
Please add Activity Feed closing options.

**Comment by ilmartyrk** [comment]
fixed
