### ISSUE TITLE
Account: User confusion between accessing topics in two accounts 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#688]
@kevincrepin @anettlinno @ilmartyrk This one is a problem we know has caused issues in the past, and in the only Round 1 test in which it was possible for it to cause an issue, it did! 

In one of the round 1 tests, a user had set up a topic with one account then was invited to a topic by his colleague (in another test) via a different email address. After voting in his colleague's topic he couldn't work out where his own topic had disappeared to. I gave him a lot of time to try and work this out himself, but he didn't get there. He tried at some point checking the Help Centre briefly, but didn't successfully find any help. When I directed him to the right HC topic with him, he did quite quickly realise the problem (his topic was in his other account). But if I hadn't been there he would have been totally lost. He said he would have sent a Help Request if I wasn't there, but if him accessing the topic was time-critical, which in several use cases it could be, this could be quite serious. 

And just for a bit more info, the same problem happened twice (as the test was split into chunks): 

- Once at the end of one call, when he had just voted in his colleague's topic and was then looking for his own. 
- Once at the beginning of the next call, when he had signed in to the other account, and was again confused where it was.
- (I myself was also confused and it was only later on I realised what had happened!)  

I think we can't rely on the HC (not everyone will think to go there), and I'm wondering if we can ideate any solutions to help this issue, as it's really quite a major one. 

A couple of ideas from me: 

- Is there somewhere we can have a help button or guidance text within the platform, that gets people thinking about this? 
- Can we use this part to allow users to switch between two different accounts? (I realise this means they will have to link them manually though, which they wouldn't always do). 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7372a04e-6f7c-43e2-83af-41a27a8edb42)
-  Can we have the created by bit saying 'You' when it is by the account you are in? I have often got confused myself in topics re why I can't do certain actions, only to realise that I'm logged in to the other account - one is Becca, one Becca Melhuish, so not easy to differentiate. 
- Any other ideas of how we can bring this issue more into people's minds, so that when they are faced with such a situation they are more likely to be able to realise the solution themselves?

**Comment by kevincrepin** [comment]
Immediate solution could be to show with what type of account they're logged in and hope this helps with the realisation:
![Screenshot 2024-01-26 at 09 30 53](https://github.com/citizenos/citizenos-fe/assets/26792281/55f2b893-f277-4c80-bc83-482b99dfdc61)

I agree linking and switching between accounts should be a thing, but I also think this is probably Phase II stuff.

**Comment by BeccaMelhuish** [comment]
I think this is a good idea to try! Maybe it will nudge their thoughts in the right direction :) 

@anettlinno re the account switching, should we have a list of things we're saying should be Phase II (or later), so we don't forget anything when assessing what to prioritise next? (I know the Phase II tag helps with that, but in this case wouldn't work as the solution is for Phase I?)

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk I didn't add pre-testing label to this one, but if it's just a quick-fix then would be great to have it for them, and test if there's time to orchestrate it or it just comes up naturally somehow :)

**Comment by BeccaMelhuish** [comment]
On reflection, am adding the pre UX tests label but no rush for tomorrow, just by next week (i.e. 5th Feb) would be good if possible :)

**Comment by anettlinno** [comment]
@ilmartyrk could you please estimate how much work would it take to implement the designs that Kevin proposed [here](https://github.com/citizenos/citizenos-fe/issues/688#issuecomment-1911606922)?
If this is rather easy solution, I´d say that let´s go for it now as we ourselves are often having troubles which are caused by using "wrong" account. 

@BeccaMelhuish we have Phase II list under the UX/UI redesign project in [GitHub](https://github.com/orgs/citizenos/projects/5/views/1). This should help to prioritize Phase II developments and sort out those which will be done later. In In-Prep column are all issues that are currently under the discussion or are waiting input from someone.

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno @BeccaMelhuish added the item to the profile dropdown. Only used the letter icon as we actually don't store the method used for login for the current session. Also if users have connected their account with gmail they can actually still change their e-mail addres so that the google account used for login e-mail doesn't have to match the profile e-mail

**Comment by BeccaMelhuish** [comment]
Looking a bit dodgy for me here, but not important for the test I think, she'll see it's just a bug and get the idea :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e2909d95-a3ac-4012-81e8-80e2748934ef)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the hidden overflow
