### ISSUE TITLE
Follow-up: 'Updates' rather than 'Events'? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#689]
Should we call them 'Updates' rather than 'Events'? Seems more logical to me, 'events' seems more like actual events - outreach events, meetings, conferences etc? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c9a011ed-92f4-4a02-a27e-ce2bf300167f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the texts
