### ISSUE TITLE
Groups: Browser back button doesn't work when in a group

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#693]
Tried in several groups (private and public) all the same. Seems fine for topics. Laptop, Windows, Chrome. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8f84c8ac-c9d5-411b-841b-412e0f8dce1d)

**Comment by ssin1901** [comment]
I had the same issue in Safari. The back button just freezes until you exit the group interface.

**Comment by anettlinno** [comment]
Triage 100. Sending to do. Est dev time 30 min.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 @anettlinno fixed the issue

**Comment by ssin1901** [comment]
Working now and closing (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/09b55ca3-a856-422c-8aaf-e2be41aba3fb
