### ISSUE TITLE
Topics: Users are confused at what to put in the 'Intro' 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#694]
@kevincrepin @anettlinno @ilmartyrk 

In some of the round 1 tests, the users were sometimes confused at the point of entering the 'Intro'. Some questions that came up: 

- "Intro? Intro to what?" 
- "What's the difference between Intro and Description?" 
- Generally expressions of uncertainty

I'm also unsure myself what the distinction between them is, if we were to try to explain it to them, other than "the intro will be automatically in bold at the top and is shorter, the description you can format as you wish and it's longer"? 

Here are some examples of their topics, so you can see what they are doing with them (basically it's often working OK, but causing some confusion when they are first entering them, and sometimes they are just repeating a similar thing to the title or the description): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6123664e-6c8c-4562-bfb9-a3de5e286a2c)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a18e0af9-227f-4ccd-af10-47a65192cb19)

Sorry in French, but this one the intro is very similar to the title: "Debate on the candidate speeches" and then intro: "It's a space for discussion during the candidate speeches": 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7b305c67-2ac4-4bb4-a5d8-6525e447fc3e)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/dfba9c95-7dd8-4be0-aa87-a916ad972f04)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/426660d7-9079-4fe9-abf2-cd5b9dd33c96)

This one there was a bug preventing the description, but explained she would put further info about the organisation, their website, etc. 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b3bef7d9-6da1-4f80-a29d-a8a8cd5e9e62)

Suggestion: we just try to fix this with copy for now (in the Create flow, when they are entering the intro and description), but also would be good to be clear ourselves what the difference is any why we specify/enforce the structure to be like this (rather than letting them just format it themselves). Not saying we shouldn't (I see that it makes for a good structure in some cases), just raising questions :)

**Comment by anettlinno** [comment]
I agree that let´s try to solve it with better copy and leave it for gathering more feedback from users. Maybe later in one point this section could be added only in some templates where it makes sense (like petitions for example) or this could be recommendable to fill it and not mandatory (as it is now). Just some thoughts...

But I think before we throw it out, let´s get more feedback to it.

**Comment by kevincrepin** [comment]
I thought what is now called "description" was called "topic text"? Wouldn't this already make it a bit clearer?

And maybe "Intro" could be "Small introduction to the topic". Which is a bit long but also sets that it's supposed to be shorter (as there's also the character limit).

**Comment by BeccaMelhuish** [comment]
@kevincrepin Hmm yes true, we had a long discussion [here](https://github.com/citizenos/citizenos-fe/issues/188) about what to call these, and it's true we did decide on 'Topic text', but then right at the end of the discussion changed it to 'Description'.

@anettlinno shall we try it with 'Topic text' instead? Reflecting again now and having seen the users get confused, I do think it would be clearer :) 

Then if they are still confused here, we could perhaps add a little line under each, explaining what they are, e.g.:

**Intro**
Add a brief introduction or call to action, summarising what the topic is for.

**Topic text**
The main topic content goes here - any instructions, information or context for participants.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin posted a fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Thank you! I wasn't able to check what you've done (internal server error as discussed) but was it just changing the headings or also adding the texts? 

I think the headings alone might be enough, but up to @kevincrepin if he thinks the texts are a good addition (given the user confusion previously) or add clutter and best only added later if the tests show they are still needed :)

**Comment by BeccaMelhuish** [comment]
Am seeing now that it's like this below, it looks a bit much and the UX of these is a bit confusing (when you click in them they disappear), so let's remove the texts for now please @ilmartyrk and keep the headings only for the next round of tests :) 

Then if people are still getting confused we can reassess - maybe adding these texts as help buttons if needed - could be a great place for these. Unless @kevincrepin you think we should already go ahead and add help buttons here? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9eb4189e-9b13-4d4e-926e-9a6bd5cc988f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I had to hide them specially for the topic text block when opened, because they got in the way for the Etherpad and it broke the design. So removed the texts for now,

**Comment by kevincrepin** [comment]
Also wondering if this additional text would be necessary with the change to "Topic text" now. 

It's also kinda... an intro is an intro. Not really many ways to interpret this? :) 

But previously "Description" was maybe asking too much to "describe something" which is maybe too specific and that's why it was confusing...

So basically I agree that let's first try without the additional text or help icons, tooltips, etc.

**Comment by anettlinno** [comment]
"Intro" and "Topic text" without explanatory texts looks good and let´s get users for feedback on it :)

**Comment by BeccaMelhuish** [comment]
OK wonderful. I've now gone through and edited in the translation strings the places where we talked about the 'topic description', so @ilmartyrk please do whatever needs to be done for those just now committed strings to appear on the test environment, then this one can be closed :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish your edits in the en.json were enough so after you commit your changes in the master branch it will take a few minutes and they appear on the test platform :). Closing the issue
