### ISSUE TITLE
Groups: In group create flow, users misunderstand/are unsure if can invite using an URL or QR 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#695]
@kevincrepin @anettlinno @ilmartyrk 

When you get to this part of the group flow, there's no mention of being able to share using an URL or QR code. This is how it went in the two tests where it came up: 

- She pointed out that it wasn't there, but said 'I assume I'm able to later though' (she had previous experience of trying out a group on our current platform though). 
- He pointed it out that it wasn't there. He had then assumed it wasn't possible (he confirmed at the end he had thought it wasn't) and so didn't see groups as meeting his need to share several topics at once via a public link (related to #662) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3195b752-5028-4d58-8c52-d7e45bd37896)

I see that it's a bit risky to have the invite URL or QR code here, as they haven't published it at this stage. But still maybe we can make it clearer that they can do it later?

**Comment by kevincrepin** [comment]
I would just add a small intro to this section where we can explain this. Initially I tried with an inline information notification, but this drew way too much attention for what it is. 

![Screenshot 2024-01-26 at 08 35 14](https://github.com/citizenos/citizenos-fe/assets/26792281/a05b3fcc-896e-4dee-b48a-442f5ae82c89)

PS @ilmartyrk I also flipped the placement of the search/input and the free comment. Feels more logical like this actually.
Figma: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=221%3A30940&mode=design&t=yoDKb7xLADti0hlu-1

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK yes this should help! Suggested wording though to be a bit more concise: 

'Invites will be sent when you create the group. You can also invite people later - either via email, URL or a QR-code.' 

(Saying 'create' the group rather than publish, as with the buttons we have 'publish' for topics but 'create' for groups).

**Comment by kevincrepin** [comment]
Great, updated the copy accordingly!

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin updated the view

**Comment by BeccaMelhuish** [comment]
Checked and closing :)
