### ISSUE TITLE
Group: Gap before error msg in 'Add topics to group' pop-up 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#698]
Isn't usually like this, but just now had this gap for me: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/71934f95-aa69-46f4-86b0-d6126134eeae)

**Comment by anettlinno** [comment]
Triage 100. Sending to do. Est dev time 5 min.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)

<img width="1247" alt="Screenshot 2024-02-18 at 17 57 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1922545f-7f3f-43ea-ba43-2b8336e473ea">
