### ISSUE TITLE
TOPIC: Create Discussion and Create Voting leads to Internal Server Error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#701]
**What is the problem?**
In the latest versions of Mac OS Safari and Google Chrome, the user receives an Internal Service Error when they click on Create Discussion or Create Voting (see screenshot). Issue is replicated in incognito mode. 

NB! User was signed in with Gmail login while the sequence of actions occurred. 

<img width="1440" alt="Screenshot 2024-01-28 at 23 23 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/53979dee-bcbb-4145-8086-a4e5ced18041">

**Why is this a problem?**
Users can neither access Create Discussion nor Create Voting

**Possible solution.**
Internal Server error should not be displayed and users should be able to access the Discussion and Voting sections without any issues. 

@BeccaMelhuish this might affect the user tests in the coming weeks, which is why I added the pre ux tests label.

**Comment by ssin1901** [comment]
@ilmartyrk it seems to be working now but I don't want to close the issue without asking first

**Comment by ilmartyrk** [comment]
@ssin1901 Etherpad database was full
