### ISSUE TITLE
FOLLOW-UP: text is broken

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#702]
**What is the problem?**
Text is broken in follow-up:
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/8c725278-9977-4832-ba37-2763de83e9f7)

**Why is this a problem?**
N/A

**Possible solution.**
Please fix

**Comment by ilmartyrk** [comment]
We decided to remove that item from the dialog, I had removed it from translations, but forgot to remove it from the popup
