### ISSUE TITLE
Follow-Up: Empty state for when voting is still on

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#703]
Currently when the voting has not ended yet, the follow-up phase doesn't show the empty state we otherwise have. We probably need a specific one to communicate within the context of "while voting is on..."

![Screenshot 2024-01-29 at 17 25 49](https://github.com/citizenos/citizenos-fe/assets/26792281/a052ae80-5197-4a54-ac87-9ce897e04180)

Or might also just be a bug @ilmartyrk :)

**Comment by ilmartyrk** [comment]
@kevincrepin was a BUG, posted a fix
