### ISSUE TITLE
TABLET -  Design Review: General

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#704]
### **Menu opening**
When the menu is open, the background content should be under a dark overlay, like in prototype:
![Screenshot 2024-01-29 at 16 34 43](https://github.com/citizenos/citizenos-fe/assets/26792281/51ce93d4-4d4c-4a02-bbf4-28fc4735a427)

Currently in dev it doesn't which makes it harder to differentiate between content and menu:
![Screenshot 2024-01-29 at 16 33 45](https://github.com/citizenos/citizenos-fe/assets/26792281/62156655-f681-41d0-985c-b897717121a7)

### **Menu is missing search**
With the latest update to including the search in the mobile menu it should also show up similarly in the tablet menu. Currently it's only the create button that's visible there.

### **Top menu background**
The top menu should have white background in overview pages, but in detail pages (topic, group) it should not have a white background. Currently it always has no white background.
Topic (detail page): https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=1064%3A104439&mode=design&t=2fKK7sjLhIHmesVZ-1
Topic list (overview page): https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=1054%3A101590&mode=design&t=2fKK7sjLhIHmesVZ-1

Also on dashboard and logged out page the top menu should have this white background.

### **Opening action menus is widening the layout**
![Screenshot 2024-01-29 at 17 21 50](https://github.com/citizenos/citizenos-fe/assets/26792281/1158f42b-2369-4404-a411-e1454e82b796)
This seems to be happening quite a lot where an action menu opens partly off screen which then triggers the layout to become a bit wider with some elements falling off screen.

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno I fixed the issues, though not !00% sure if I have found all the dialogs that overflow the view, but I suggest we create separate issues if some pop up
