### ISSUE TITLE
TABLET -  Design Review: DASHBOARD

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#705]
### **Tour**
![Screenshot 2024-01-29 at 16 42 10](https://github.com/citizenos/citizenos-fe/assets/26792281/537bfc3d-ea09-49f1-a9c9-b9273ef0fd26)

1. Tiny detail: the triangle pointer seems to have another colour.
2. We're reusing the tour copy from the mobile but on tablet our bottom menu holds 2 extra items. Can we include these as well to the explanation? 

![Screenshot 2024-01-29 at 16 44 38](https://github.com/citizenos/citizenos-fe/assets/26792281/1c52e248-9bc4-41c9-a5f0-2f2ba1181fd4)
In this step the arrow decided to separate from the content part :)

### **Footer**
![Screenshot 2024-01-29 at 16 48 17](https://github.com/citizenos/citizenos-fe/assets/26792281/762aaf86-ca97-4159-b56f-5ab0c48e5264)
Missing some padding under the button so it doesn't stick to the bottom menu so much.

**Comment by ilmartyrk** [comment]
Fixed the issues

**Comment by ssin1901** [comment]
@ilmartyrk @kevincrepin here is the view from tablet tested in iPad 9th generation (Dimensions: 9.87 x 6.85 x 0.3" / 25.07 x 17.4 x 0.76 cm, OS: 17.2). I don't see any mismatch between Desktop and Tablet view. Can we close the issue?

Added screenshots just in case I missed something

![IMG_0602](https://github.com/citizenos/citizenos-fe/assets/72747107/4f5a963b-6490-4ad0-a6fa-aef18cab12e6)

![IMG_0604](https://github.com/citizenos/citizenos-fe/assets/72747107/b9ded3aa-95e6-4b5e-a205-f021b634daf0)

![IMG_0605](https://github.com/citizenos/citizenos-fe/assets/72747107/3dd5ee2f-b5be-4272-bab2-e80b55ac9e67)

![IMG_0606](https://github.com/citizenos/citizenos-fe/assets/72747107/adb04dea-bbf6-412a-9d7c-92dd89a2c53e)

![IMG_0607](https://github.com/citizenos/citizenos-fe/assets/72747107/18e96c1c-3e5e-4bcd-a681-73d6810d6a9a)

**Comment by ilmartyrk** [comment]
@ssin1901 closing
