### ISSUE TITLE
TABLET -  Design Review: My Topics / My Groups

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#708]
### **My Topics**
![Screenshot 2024-01-29 at 17 13 30](https://github.com/citizenos/citizenos-fe/assets/26792281/82d1073d-0cbe-4773-b150-e4cd7f266913)

1. In design I managed to fit 3 cards in a row for this screen width. Would it be possible? Because now we have this weird blank space on the right :) The side margins in design are 16px if that helps have bit more space.
Figma: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=1054%3A101590&mode=design&t=2fKK7sjLhIHmesVZ-1

2. I also noticed that when you go "Back to my topics" from a topic detail view, the bottom menu doesn't highlight the page you're on. It does work when you click on it.

### **My Groups**
![Screenshot 2024-01-29 at 17 17 26](https://github.com/citizenos/citizenos-fe/assets/26792281/a1af534c-9ee3-4c16-9c51-aae00640521a)
Same comment for My Groups: we should be able to fit 3 cards in a row.

### **Public Topics & Public Groups**
Since they follow the same layout, we would also need to implement these updates for the public topics and groups.

**Comment by ilmartyrk** [comment]
fixed the issues
