### ISSUE TITLE
TABLET - Design Review: Group

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#709]
![Screenshot 2024-01-29 at 17 43 59](https://github.com/citizenos/citizenos-fe/assets/26792281/f600809f-b028-44c3-ba54-e5c23cc5a7fb)

1. The top menu falls off screen, probably caused by nr 2
2. Even if we make these buttons less wide in English then probably quickly in other languages they wouldn't fit anymore... This needs some thinking and references from me @ilmartyrk, I will assign also to myself.
3. Maybe same reason why the bottom menu falls off screen, not sure...

**Comment by kevincrepin** [comment]
@ilmartyrk for this two button situation I put a solution in the original issue: https://github.com/citizenos/citizenos-fe/issues/637

**Comment by ilmartyrk** [comment]
This is fixed with 637
