### ISSUE TITLE
TOPIC: Error message for more than 3 categories came after the topic was already saved 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#714]
**What is the problem?**
A user is able to add more than 3 categories while editing the topic (screenshot1) without receiving an error message.

<img width="1349" alt="Screenshot 2024-01-30 at 13 01 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d5b9a349-d571-47ad-bd20-67298b58baa1">

However, the error message did not appear after the topic had been saved - with only the first 3 topics displayed (screenshot2) 

<img width="1347" alt="Screenshot 2024-01-30 at 13 04 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/31e023fd-137a-4d56-81df-5962cb7d7109">

The error message was displayed when the user _published the topic for the second time with edits_ (screenshot3).

<img width="1352" alt="Screenshot 2024-01-30 at 13 04 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6700b92d-ca78-4ce3-bc3d-603b18a28ebe">

**Why is this a problem?**
Confuses the users

**Possible solution.**
Error message should be displayed at the time of adding the fourth category, not after the topic has already been saved.

**Comment by ssin1901** [comment]
Also in reference to #659 it seems that the Categories are still not in order

**Comment by ilmartyrk** [comment]
@ssin1901 fixed, only 3 allowed now to add

**Comment by ssin1901** [comment]
Fixed and closing
