### ISSUE TITLE
REGISTRATION: Unnecessary login popup after registering from group invitation link

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#717]
**What is the problem?**
A user is able to successfully register from a group invitation link. 

After successfully entering valid login credentials, they receive the group invitation with Log in replacing Create Account (screenshot1) but clicking _Log in to join the topic_ directs them to the Terms of Use and Privacy policy.

<img width="1349" alt="Screenshot 2024-01-30 at 15 38 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/05be7aaf-ecc2-4fd4-a2c8-ee2fd3fbc799">

**Why is this a problem?**
User may not complete the login flow due to the confusion about being asked to login for the second time 

**Possible solution.**
@ilmartyrk @BeccaMelhuish has there been some discussion about this flow? Why does the group invitation need to appear twice? Or if it does, shouldn't it say _join topic_, given that the user has already logged in?

**Comment by ilmartyrk** [comment]
Fixed with https://github.com/citizenos/citizenos-fe/issues/739

**Comment by ssin1901** [comment]
Closing this issue
