### ISSUE TITLE
VOTING: Received insufficient permission error after adding custom votes

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#718]
**What is the problem?**
After a user has created a Voting Topic with valid title, intro, description, voting question and 5 options they receive the following error message in Preview (see screenshot1). 
<img width="1413" alt="Screenshot 2024-01-30 at 16 02 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/487926ce-6eb7-42a4-827b-d9a9e4534936">

However, they are allowed to go ahead with publishing the voting topic anyway (see screenshot2)
<img width="1413" alt="Screenshot 2024-01-30 at 16 02 42" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ed70d094-0538-43e5-8503-2ffc2f48f8d5">

**Why is this a problem?**
Error message is not clear. If the user has insufficient permissions, how can they go ahead with publishing the topic?

**Possible solution.**
No error message should be displayed when valid input has been entered. If invalid input has been entered, user should not be able to publish the topic.

**Comment by ilmartyrk** [comment]
@ssin1901 I need a little more information, did you also invite users or add topic to group?

**Comment by ssin1901** [comment]
@ilmartyrk I had not invited users or added the topic to the group at the time. The error came up after I had added the custom vote options and clicked Continue to Preview.

I invited users later and everything worked fine.

**Comment by ilmartyrk** [comment]
I could not replicate it, maybe there was another cause for this error

**Comment by ssin1901** [comment]
@ilmartyrk can we close it if could not be replicated? If it comes up again, I will create a new issue.

**Comment by ilmartyrk** [comment]
@ssin1901 closing the issue
