### ISSUE TITLE
VOTING: voting type vs voting system

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#720]
**What is the user story?**
When translating the platform, I noticed that on our current platform we define "voting type" as the regular or custom voting option: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/7666e2f4-7e60-4516-8359-0a50dcc7b1d6)

And "voting system" in setting voting deadline: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/3181086e-4a24-44db-bef7-3fc0f42a21f2)

But in redesign we use "voting system" when choosing regular or custom voting option:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/44d66706-1aa1-455c-bbc4-2a76a46b8c95)

In redesign the voting system is wider, as it also includes voting question, but IMO "voting type" for regular vs custom voting is more precise. But was there a reason why it was changed @kevincrepin ? :) 

**Which feature needs to be updated and how?**
Voting type vs voting system

**Additional information.**
N/A

**Comment by kevincrepin** [comment]
Eeeehmm :) In the design I named it 
- Select a voting system
- Set up voting rights
- End of voting system

But I'm ok with renaming it, I think you know better the terminology that users relate to :)

**Comment by ilmartyrk** [comment]
@oksoks @BeccaMelhuish  do you have any ideas or should we close this issue for now?

**Comment by ilmartyrk** [comment]
Closing the issue
