### ISSUE TITLE
VOTING: Setting automatic reminder input not saved

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#722]
**What is the problem?**
Under Voting -> deadline, the Setting automatic reminders input (checkbox) is not being saved (see screenshot) 
<img width="1414" alt="Screenshot 2024-01-30 at 16 28 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/5d39d0e5-a5b7-446c-bd7f-3b89d0c2dcae">

**Why is this a problem?**
User does not know if they have checked the box to send automatic reminders or not

**Possible solution.**
Checkbox input - ticked or not ticked should be saved

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the issue

**Comment by ssin1901** [comment]
@ilmartyrk this issue is still open right? I tested it and it wasn't working (screenshot1) and the users also didn't receive the automatic email notification.

<img width="1354" alt="Screenshot 2024-02-01 at 13 42 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/33d53a12-e233-433b-bb48-d8002074c13d">

**Comment by ilmartyrk** [comment]
@ssin1901 is now fixed

**Comment by ssin1901** [comment]
Fixed and closing this issue (see screenshot)
<img width="1440" alt="Screenshot 2024-03-27 at 16 46 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a38386db-23d9-4004-9f50-f2027b392336">
