### ISSUE TITLE
VOTING: Download voting results doesn't work

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#723]
**What is the problem?**
User cannot download voting results as the link does not work (see screenshot).

<img width="1351" alt="Screenshot 2024-01-30 at 19 19 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/17420e02-56aa-4c3a-b44d-18d5442ee869">

Replicated in Google Chrome and Safari latest versions in incognito mode.

**Why is this a problem?**
User cannot see the voting results 

**Possible solution.**
Link should lead to a download with a file with correct voting results

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
@ilmartyrk this worked for me in Safari but in the latest version of Chrome I got an error message that I could not expand it as it as an unsupported file format. Replicated in Chrome incognito mode on Mac OS.

**Comment by ilmartyrk** [comment]
@ssin1901 I don't understand what error you had

**Comment by ssin1901** [comment]
@ilmartyrk can you check it in Chrome? I somehow got the same error in incognito, so perhaps it is more related to the OS.

**Comment by ilmartyrk** [comment]
@ssin1901 can you share a screenshot or video, I don't understand what error you are getting

**Comment by ssin1901** [comment]
@ilmartyrk my sincerest apologies

<img width="1348" alt="Screenshot 2024-02-05 at 13 06 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a7ea0487-187d-4cda-9eb8-df356b421bff">

**Comment by ilmartyrk** [comment]
@ssin1901 this is not an issue with our platform, it is an issue with Mac OS Archive Utility
