### ISSUE TITLE
Voting: Duplicate Mobil-ID icon in Create flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#724]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/719b057b-8825-42f2-92fb-465d4f07b7dd)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot)

<img width="1227" alt="Screenshot 2024-02-19 at 01 22 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cc0d4836-15ee-406a-9543-e20d19ec6aaa">
