### ISSUE TITLE
Group: Some remnants of added invitee after deleting them in Create flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#725]
User adds an invitee to group during 'Create group' flow: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/87a00482-ea2e-4d94-b4ed-ef0ebbdaa2cf)

Then she deletes them, but there are some parts still showing: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5474c81b-fff2-4e7a-ac0d-156c47bf56c0)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is a duplicate and is fixed
