### ISSUE TITLE
IS: Bug with inviting multiple emails to group after having deleted one

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#726]
As per [this issue](https://github.com/citizenos/citizenos-fe/issues/725), user had just added and then deleted one email address. 

She then copy pastes a string of emails: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1c5e389c-2ed1-421e-9da6-241dadcdc9a8)

When she presses enter, what appears is the single email she had just added then deleted, not any of the list she was trying to add. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a49ebf98-1628-4992-9282-e9ef604698d8)

She tries again and this time it's like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a503a4e4-0426-452d-a1d2-47efb2c4ee68)

She tried one more time copying and pasting them again from the spreadsheet, and it worked. This time it looks like she clicked on 'Press enter to add' where as the last times it seemed more like she was pressing enter, in case this helps :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think this is fixed

**Comment by ssin1901** [comment]
Could not replicate, closing this issue
