### ISSUE TITLE
IS: Text re inviting multiple emails at once should be above all invite fields 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#728]
The text "Add up to 50 emails at once, with a space or comma between each." that we agreed in [this issue](https://github.com/citizenos/citizenos-fe/issues/683) should be added everywhere that there is an 'Invite people' field. 

E.g. it needs to be added here in the 'Create group' flow, but maybe there are other places too :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f7db5d6e-be9e-4193-b8e7-8d2bf8a35c85)

**Comment by BeccaMelhuish** [comment]
Here is one other example of a place it should be too, anywhere there is a field to invite people: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2378deac-70c0-48f4-9647-439f7f15804e)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot1, screenshot2)
<img width="1440" alt="Screenshot 2024-03-27 at 16 44 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/41d7d0d6-3de6-4822-8795-793a17270cf3">
<img width="1439" alt="Screenshot 2024-03-27 at 16 44 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6a2915a1-4f3b-40e0-bf0e-7f62f18408ed">
