### ISSUE TITLE
Groups: Can't see pending (invited) group members

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#729]
User wasn't able to see any invited members, only herself (she was the only one joined at that point). 

I checked back to [this issue](https://github.com/citizenos/citizenos-fe/issues/185) about it and see I may have closed it prematurely! 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f26f6473-105a-4695-a2b7-c105bef23fa7)

**Comment by ssin1901** [comment]
@BeccaMelhuish I am adding the pre ux label as this frustrated me during testing, and would definitely frustrate the users during the tests if they need to track who was invited and who was not.

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish posted a solution

**Comment by ssin1901** [comment]
Seems to be fixed (see screenshot) and closing.
<img width="1440" alt="Screenshot 2024-03-27 at 16 51 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0a63365d-c5e2-4d1d-afb9-eb0f10839793">
