### ISSUE TITLE
Group: Empty 'Topics' tab needs some content

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#730]
Similar to [this issue](https://github.com/citizenos/citizenos-fe/issues/664), I think we should put something here for when a group is created but doesn't yet have any topics added. Would you agree @kevincrepin? 

It looks a bit buggy to have it empty for admins - user in yesterday's test was clicking the filters at some point presumably to see if anything appeared, and for members I remember @anettlinno advising previously that we advise admins in the HC along the lines of: 'add at least one topic to your group before inviting members or they get confused'.   

If so we'd need something for the admin view, and something for the members view :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2b61a061-1b4c-4d9b-86db-b244dcc90e4f)

**Comment by kevincrepin** [comment]
Yes, we can have the same empty state here, I agree. Copy needs to be edited for this context though, @BeccaMelhuish.

![Screenshot 2024-02-07 at 09 09 17](https://github.com/citizenos/citizenos-fe/assets/26792281/593f6968-e914-4d39-b151-7015037e8998)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the item, can you help with copy.

**Comment by ssin1901** [comment]
Fixed (see screenshot). Closing the issue.
<img width="1440" alt="Screenshot 2024-03-27 at 16 42 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/868e2571-4ad1-4658-b92d-7ba58b08fe9d">
