### ISSUE TITLE
Group/Invite: Bugs in the 'Add members' pop-up

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#731]
User had just tried inviting a list of email addresses (that she had already invited once, but we thought it hadn't worked). 

First point: she successfully invited them all again (maybe not technically, but as far as it looked) - should there not be a message saying that these emails have already been invited, or similar? 

Second point: when she then clicked on the 'Add members' button again, the pop-up opened up with all the email addresses still there like this (maybe related to the above point?). So in the screenshot, she is opening the pop-up to do what she wanted to do, add just my email, but all the other emails from last time she opened the pop-up are still showing there. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2f8233f2-acf1-40a7-a868-c827175829f1)

Third point: there should be a gap between these I think? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/edeef759-3da0-477f-b7c4-296c1f7a6884)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issues, not sure what happened with inviting process where you weren't sure, but it seems to be working

**Comment by ssin1901** [comment]
Could not replicate, closing for now

**Comment by ssin1901** [comment]
Could not replicate the issue, closing for now
