### ISSUE TITLE
Discussion: 'Arguments' should be 'Contributions'? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#732]
@kevincrepin @anettlinno @ilmartyrk, Should it be 'Contributions' rather than 'Arguments' like we changed it to on our current platform? 

This one is 1 argument with 3 replies, but says 4 arguments (so this is a bug, but needs deciding which way to fix it): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5b56b95d-a59a-4066-a6f9-537e1a7e8bed)

This is how we changed it on the current platform below - remembering the discussion it was because if you come to a topic that has say 3 arguments, but 10 replies on each, it seems like it is quite a 'dead' topic, but actually there's a lot of activity in the comments - 30 important different ideas or points of view, not just 3. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a4e5d700-6d8a-49e1-a9ef-7118d79bc4b2)

**Comment by kevincrepin** [comment]
OK for me :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @kevincrepin  updated the view

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1440" alt="Screenshot 2024-03-27 at 16 40 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ddfa2a65-76ef-410a-b200-5357646e86a0">

**Comment by ssin1901** [comment]
Sorry, closing (see comment above)
