### ISSUE TITLE
Topic: Duplicating topics not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#734]
User tried to duplicate her topic. She tried twice and both times it didn't work but in two different ways.

First time: 
She agreed to the pop-up asking her if she did want to duplicate, but then it just took back to the topic she was in. Nothing happened. 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7bddd7e1-7163-471b-b0cb-952a29ae1693)

Second time: 
It did duplicate, but hardly any of the content copied over. Only the topic text. It was a voting topic and she wanted to duplicate the vote she had just set up, but instead of the vote there was a 'There is no discussion' block (despite it being a voting topic, with no discussion phase): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a16bea99-5dca-41a0-b746-44dab5f123e4)

This bit was also dodgy looking:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9d6782b1-3ff2-47df-b414-a6a90913c9c8)

I notice that in the 'Duplicate topic' pop-up, we say that vote systems won't be duplicated, is it true? @anettlinno whether now or in a later phase is up to you of course, but I think when a user duplicates a voting topic (or a topic which has a voting system), the voting system should be duplicated too :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4ce2aed1-9a40-4090-9ca3-b188fe8c3c85)

**Comment by BeccaMelhuish** [comment]
Will also add what happened for me today. I tried duplicating one, and it seemed to do something - a topic appeared with some of the elements copied, but when I went to my group and to my topics it was nowhere to be found. 

Also I assume it should be a draft initially, rather than a published topic? (As I think in most cases users won't want to be publishing it instantly, but editing it a bit from the original and then publishing).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish voting system is not duplicated, I guess we will implement it in later phase, as it needs more tweaks to the duplication process. Partially this issue was caused as on our old platform title was inside topic content in Etherpad that is why you couldn't find it. And second issues were caused because topic in draft status opened in regular view instead of edit view as it should when in draft. Fixed these issues

**Comment by BeccaMelhuish** [comment]
Will leave for @ssin1901 to test if that's OK :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish duplicates everything but the header image. However, the text does not indicate that the header image WON'T be duplicated (see screenshot). Either the text should be updated or the header image should be duplicated.

<img width="1440" alt="Screenshot 2024-02-19 at 01 29 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2bdd0183-0c46-43b6-8e7a-3ebc8698ec0f">

**Comment by ssin1901** [comment]
@ilmartyrk we have incorrect content but it is low priority now. Issue is now resolved but removing the high priority label.

**Comment by BeccaMelhuish** [comment]
I think header image needs to be duplicated as well :) 
(But if not then yes, text needs changing) 

Also, text refers to footnotes and comments which we don't currently have - so should just be "(including images)" 

@ssin1901, just to check - did you test if attachments get duplicated OK, as it says they should be?

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish added image to the duplicate

**Comment by ssin1901** [comment]
@BeccaMelhuish yep attachments added (see screen recording) and now closing this issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/e4cbda2f-c45b-4405-bd4c-f2246ee710ef
