### ISSUE TITLE
Group: Adding existing topic to group creates a new voting topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#735]
When user was adding existing topic to group via the new 'Create or add topic' menu in groups, it made a new topic in the background.

When the pop-up is open, you can see it in the background:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/35b4a16b-45e2-4468-88cb-8a057b19b0fb)

Once she finished adding it, this was her view (when a second ago she was in her group): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d3e4e13b-1276-4272-bf40-b18874d3b005)

She then went to her group, and it was there as a draft:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a975a19f-990a-4f5e-a71c-49f9918ee4bc)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should be fixed now

**Comment by ssin1901** [comment]
Haven't been able to replicate this important issue and closing for now, but please create a new issue if it recurs.
