### ISSUE TITLE
Group: After adding existing pop-up to group, menu stays open

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#736]
User was adding existing topic to group via the 'Add or create a topic' button in the group. 

Does so and when the 'Add existing topic to group' pop-up closes, this one stays open. It should minimise as well, and the screen no longer be greyed out. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d7ed6f03-97ed-414f-bce4-bc2088578343)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by ssin1901** [comment]
Currently looks alright to me (see screen recording). Closing the issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/b7f6a4e5-c54d-4104-b610-1f103e3a2b8f
