### ISSUE TITLE
Login: Duplicate password error message

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#737]
Should only be below the Password fields, not at the top as well:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/291ef964-9f3a-4d87-ab17-11cdd8c7c956)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix for this issue

**Comment by ssin1901** [comment]
@ilmartyrk I think this is fixed already (see screenshot). It isn't in the testing column so let me know if I should close it.

<img width="1292" alt="Screenshot 2024-02-05 at 22 40 45" src="https://github.com/citizenos/citizenos-fe/assets/72747107/422998de-5650-4c22-946c-e64a4ac7b77f">
