### ISSUE TITLE
Login: Verify account pop-up very fast

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#738]
User is creating a new account so that she can join a topic she was invited to by a new email address. 

I noticed this pop-up message shows up for a split-second when she clicks 'Sign up'.
(So fast it was very hard to get this screenshot!) 

Also, it didn't seem like she needed to verify her account to access it (so this message isn't correct?), though it didn't go smoothly (which may be related?), I will make another issue about what happened next (she didn't land on the topic and had to go back to the email and try again): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ab6390d3-33f9-4aab-90ab-7e6dd3e6494f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I changed the flow so that if account is registered from invite there is no need to verify the e-mail as user got the invite from e-mail already. So there is no message displayed too to check the mailbox, they get redirected to the invite and can login from there afterwards

**Comment by ssin1901** [comment]
Fixed and closing
