### ISSUE TITLE
Group: Inconsistent rules bullet sizing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#742]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d41c632f-831f-4562-b974-b3265547e1a4)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
@ilmartyrk closing as the design (screenshot1) matches the Figma design (screenshot2)

<img width="524" alt="Screenshot 2024-02-19 at 01 26 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e4ba6c79-6812-4566-9322-1aae7bf0a732">

<img width="1108" alt="Screenshot 2024-02-19 at 01 26 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b7695820-f42d-43de-8696-221e5d29fc0d">
