### ISSUE TITLE
Group: Is 250 characters enough for group description

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#743]
@kevincrepin @anettlinno @ilmartyrk Just wondering if 250 characters is enough for the group description? 

I asked ChatGPT to write one for a dummy group. I got to this which felt quite a good length (not overly long), but the last two sentences wouldn't fit: 

_Welcome to Yourtown 2030 Visionaries! This online group is where Yourtown residents gather to discuss ideas for our community's future in 2030. Shape the local government's strategy by sharing your thoughts, dreams, and aspirations. Join us in crafting a collective vision for a brighter, more inclusive Yourtown. Your input matters – be a part of the change!_ 

Is there are reason to keep it so short? :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @BeccaMelhuish @kevincrepin I don't see any reason not to increase the length as only place it can be seen is in the group view. I guess 500 characters should be enough and it is then the same length as topic intro.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Working (see screenshot) and closing the issue.
<img width="1440" alt="Screenshot 2024-03-27 at 13 36 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3e87be70-a8b1-4483-9e4f-f7b3595b353b">
