### ISSUE TITLE
Groups: Default admin rights when topic created in group

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#744]
When I created a new topic in a group, it has admin selected by default, should it? 

Also, is 'participant' the right wording for groups rights?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f8646f59-96f3-4d66-9cd0-de6f571e7612)

**Comment by BeccaMelhuish** [comment]
Adding this here as it's related: this is what I get in the same place when I make a voting topic in the group, but in discussion topics it was only admin and participant:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/eb96382e-9cac-43bb-ae94-6784c567c7ca)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1250" alt="Screenshot 2024-03-27 at 13 34 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/84cc15f8-4b70-47ff-a7c4-ca8ed8d113c2">
