### ISSUE TITLE
Group: Added topic 'Name' heading looks like a link

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#745]
It's blue and when you hover it is underlined, but it isn't a link, should just be a heading :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c6cb01ba-4e51-43f2-a4d9-36a0290352e6)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot) and moving to Done.
<img width="1090" alt="Screenshot 2024-03-27 at 13 32 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cfc3bd2b-cabc-43d5-81a8-f3f2c9124869">
