### ISSUE TITLE
Group: Manage menu shouldn't appear in the preview

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#746]
It's a dead link anyway, should just be removed or it's confusing: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0f7bff76-fc94-4a8a-bd80-b502f0c1bed1)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is actually Topic issue not Group, but it is fixed

**Comment by ssin1901** [comment]
Manage no longer appears in topic (see screenshot)

<img width="1240" alt="Screenshot 2024-02-18 at 18 01 52" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e5466197-fc09-4028-94bd-25d629f4befa">
