### ISSUE TITLE
Group: Making a new discussion topic in a group created a voting topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#747]
I made a discussion topic via the 'Create new topic' menu in a group. 

Throughout the create process and preview it was a discussion topic, but when I published it it was a vote topic: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d441fbaa-a31f-4ba8-bbf7-fec46038c993)

**Comment by BeccaMelhuish** [comment]
Went back to 'My topics' and it looked like a discussion one there (blue), went into it again and it was now a discussion topic as it should be..  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/864a612e-4098-4b2b-a309-b1b6ffb53f6f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this issue should be fixed now

**Comment by ssin1901** [comment]
I am closing this for the time being but let's keep an eye out for recurrence!
