### ISSUE TITLE
Topic: How header image looks in compose isn't how it will be in the topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#748]
In Compose it looks like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2c6d5f0f-8b60-4bd1-8381-43218ec869b8)

In preview and published topic it looks like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f73fba0e-3b00-4736-a686-197e80140177)

It should look in Compose as it does in Preview/Published, or it's misleading

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Fixed now (screenshot1 and screenshot2)

<img width="1290" alt="Screenshot 2024-02-19 at 01 34 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2ac0c88a-79e6-4ed2-9399-3cc0b024b5c2">

<img width="1300" alt="Screenshot 2024-02-19 at 01 35 04" src="https://github.com/citizenos/citizenos-fe/assets/72747107/39dffea5-4ff5-42b2-905f-6c9e74f51786">
