### ISSUE TITLE
Topic: Group doesn't show in Preview

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#749]
It says there are no groups, but I added a group in Step 2 Settings, so this should show up here already in Preview:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/516d039b-ab55-4aae-9d33-95c801244639)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by ssin1901** [comment]
Fixed and closing (screenshot)

<img width="1240" alt="Screenshot 2024-02-18 at 17 59 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/436e6807-dbf9-4681-9017-a04023e07779">
