### ISSUE TITLE
Group: Topic showing on Group card

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#750]
One of my topics is showing up on the front of the group card which is confusing: 

(Also are the cards meant to look like this? They look a bit like they're not displaying as they should?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0b526732-f0ca-4b26-ab8a-952857e63172)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish related to https://github.com/citizenos/citizenos-fe/issues/586 and https://github.com/citizenos/citizenos-fe/issues/644 it is designed to look that way
