### ISSUE TITLE
Group: Private or public in info box? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#751]
@kevincrepin Currently it's hard to tell if a group is public or private, should we add it to the top of the info box like in topics? 

(This is just a personal suggestion based on my own experience, but backed up by the insight from UX tests in topic - padlock icon isn't really working on its own). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/14f74a1c-9b61-45c9-b85d-003d72873e7a)

**Comment by kevincrepin** [comment]
Yep, let's add it here same as with the topics.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the visibility item

**Comment by ssin1901** [comment]
Seems to be fixed (screenshot). Closing.
<img width="1240" alt="Screenshot 2024-03-27 at 13 31 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d65da7f1-d3e0-4db8-9051-2f62261ea4f2">
