### ISSUE TITLE
Voting: Should be able to select vote options in Preview? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#755]
Should you be able to? I couldn't select anything while in the Preview (topic Create flow), same in latest user test: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/87172933-df7b-4d83-b8ac-9ebfbc4b4aa3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish not a bug. this is just a visual preview

**Comment by BeccaMelhuish** [comment]
As per comment here, I think it should be possible to click them: https://github.com/citizenos/citizenos-fe/issues/633
