### ISSUE TITLE
Bug: Multiple selection voting when there is only 1 option 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#756]
This says it is 'multiple selection', but you can only select 1 option:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3ab49230-0208-453e-9861-ba39a98e052f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by ssin1901** [comment]
Seems to be working, closing now (see screenshot)
<img width="1159" alt="Screenshot 2024-03-27 at 13 28 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/75f0bb1b-0555-4648-bf5f-4139af329d2d">
