### ISSUE TITLE
GROUP: Redundant text in group box

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#757]
**What is the problem?**
Related to #749. The correct group shows up under a topic but there is still incorrect text about there being no groups (see screenshot)

<img width="1405" alt="Screenshot 2024-02-05 at 17 51 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/40262388-f67d-4a9c-b924-329380016b43">

**Why is this a problem?**
Highlighted text is incorrect 

**Possible solution.**
Highlighted text should be removed

**Comment by anettlinno** [comment]
Triage 100. Sending to do. Est dev time 5 min.

**Comment by ilmartyrk** [comment]
@ssin1901 fixed

**Comment by ssin1901** [comment]
Fixed in Preview (screenshot1) and Published (screenshot2)

<img width="1244" alt="Screenshot 2024-02-18 at 17 59 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/de41882d-5576-4414-9d33-e5ee5c5fa92e">

<img width="1240" alt="Screenshot 2024-02-18 at 17 59 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2dbd1790-6b5a-45d6-8a59-c8278fcbd900">
