### ISSUE TITLE
GROUP: Incorrect group creation date

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#758]
**What is the problem?**
In the group interface, the date of the group being created is incorrect (see screenshot1). It also doesn't match with the date in "My topics" which correct (see screenshot2)

<img width="1289" alt="Screenshot 2024-02-05 at 22 30 15" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8e20fe73-6d1e-4ede-9891-029145b6b2de">

<img width="1298" alt="Screenshot 2024-02-05 at 22 31 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0341efb6-a5ba-4630-913e-2976897154fd">

**Why is this a problem?**
Incorrect dates confuse the users

**Possible solution.**
Date should be correct everywhere

**Comment by anettlinno** [comment]
Triage 100. Should be fixed now. @ssin1901 please test :)

**Comment by ssin1901** [comment]
Seems to be fixed, closing the issue
