### ISSUE TITLE
AF: No number showing unread notification 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#760]
In a test, global recent activity toggle didn't have notifications number to indicate there were notifications. 

She had arrived at the dashboard when she followed a topic join link that didn't take her to the correct topic as it should have (I made a separate issue for this). When she landed on the dashboard there was no indication there was an unread notification here (that I had invited her to the topic) - it just looked like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1485832d-db51-4e21-9bed-2d3fb5557adc)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk I am closing this one, but keep an eye out for this one! It worked this time (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/f42ffd5b-d9e5-4912-bfa8-d7c43f8efb3b

**Comment by ssin1901** [comment]
It is still the case that the user is not notified (via activity feed number) when somebody invites them to a topic (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/e3ac0f93-94cb-4419-b872-0e1e801aa4ce

**Comment by BeccaMelhuish** [comment]
@ssin1901 just to check the right issue was tested here - this issue was rather that this global activity button didn't have any number next to it to show that she had a new unread notification. (Which it should have had, as she did - she'd been invited to something). And it looks like in your video there isn't one either? 

Moving it back to testing just to be sure :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/665d72a5-0629-4a5b-a69b-cb587b10eb5c)

**Comment by ssin1901** [comment]
@BeccaMelhuish thanks for letting me know, can you check the video? I understood the same, that the global activity button should have showed a number (1 in this case) so the user would click on it and know that they had been invited to a topic. Seems a rather important thing actually.

**Comment by BeccaMelhuish** [comment]
@ssin1901 the screenshot above is from the video of the UX test where the number didn't show, and in your one it definitely seems to be not working either (no '1' indeed, there should have been), so maybe we can hand it back to Ilmar to look into now? :)

**Comment by ssin1901** [comment]
Yep, sorry if I was the one to accidentally put in the Done column.

**Comment by BeccaMelhuish** [comment]
Have moved it back to In progress @ilmartyrk :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 fixed the issue, it was on the API side

**Comment by ssin1901** [comment]
Seems to be fixed (screen recording attached)

https://github.com/citizenos/citizenos-fe/assets/72747107/76d7a772-cb08-41a2-9166-2ff7b86b2d83
