### ISSUE TITLE
Topic: Link in topic text opens in same tab

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#761]
Should open in a new tab: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5aa3d003-2d36-4ea9-94b8-97458fe8e7bf)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this needs changes in Etherpad so will push it to Phase II

**Comment by ilmartyrk** [comment]
@ilmartyrk please check if already fixed

**Comment by BeccaMelhuish** [comment]
Checked and now fixed, closing :)
