### ISSUE TITLE
IS: Bulk actions button dead in topic invite pop-up

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#762]
In user test 'Bulk actions' button did nothing when clicked. He was inviting users in the pop-up just after having published. There were 20 emails added if that helps. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fb2c3866-26aa-47a4-ac19-e64a60cd77a4)

**Comment by ssin1901** [comment]
Works and closing the issue (screenshot1, screenshot2)
<img width="1293" alt="Screenshot 2024-03-13 at 16 50 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/52ded63c-7aed-4c4d-b3c1-4c8e7dd0b381">
<img width="1289" alt="Screenshot 2024-03-13 at 16 50 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/14c1d9ea-bd9c-4d62-9735-d632ec194514">
