### ISSUE TITLE
IS: No 'invites sent' notification

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#763]
After sending invites in the pop-up just after publishing, there was no 'Invites sent!' notification, but the invites did send. 

(In case it's relevant, this was one of the occasions where he was making a discussion topic but it displayed after publishing as a voting topic, until he went back to topics and came in again - separate issue made about that). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ec87716e-dfb8-44c6-af22-6871c2f7752f)

**Comment by ssin1901** [comment]
Closed, could not replicate (see screenshot)
<img width="1244" alt="Screenshot 2024-03-19 at 12 42 15" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fdd10feb-7f7a-46b6-bd99-60dd367d1020">
