### ISSUE TITLE
Discussion: 'Characters left' bugs

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#765]
Same thing twice here, doesn't seem right:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4ad3c212-45a4-409e-9998-58ba32572d95)

And once he added some text here, this one at the bottom didn't change: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f5f5799c-0175-4b0c-af22-0e448431d9ad)

**Comment by ssin1901** [comment]
This seems to be fixed (See screen recording) and closing the issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/1ba17050-5214-4da9-b184-ce33121263a3
