### ISSUE TITLE
Voting: Vote reminder frequency not showing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#767]
User was adding a voting phase to a discussion topic. He selected set automatic reminder, but no option to set frequency appeared. 

I guess this is because the deadline was in two hours (so less time than the minimum), but in this case I wonder when it gets sent? 

Maybe option shouldn't be there if less than 1 day 'til deadline? But not in all cases (just in the set up of a vote), as sometimes people might want to send a reminder there and then when there is e.g. 1 hour to go.. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/93998032-242c-4e22-a093-cfe44474feff)

**Comment by ssin1901** [comment]
Seems to be fixed (see screenshot) and closing
<img width="1370" alt="Screenshot 2024-03-27 at 17 17 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/93469d37-f494-4331-8cc2-a458719f161a">
