### ISSUE TITLE
Voting: e-ID voting error/notification message bugs

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#769]
Two bugs: 

1. On clicking 'submit my vote', a mispelled and wrongly timed message appears in the background "Voting had successf been started" behind this pop-up: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/45252693-250e-4e87-a8a1-a2011805e3c1)

2. His e-ID didn't work (not registered to demo system) but the error message "Not found" appeared in the background: 
(Two issues here, it can't be seen at the right moment, and it doesn't explain much - not found is quite vague)  
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/892150f5-eaa0-4e60-b6c2-f198baade581)

Also re 2. the error message (a wider version) was like this after the pop-up had been closed, so that needs removing too: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b7cbf63e-5b1c-4e15-b282-5c523249f32d)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the error displaying behind overlay issue, also changed the error text, but it still has to be closed manually

**Comment by ssin1901** [comment]
Could not replicate the issue, closing.
