### ISSUE TITLE
IS: 'Invite people' pop-up didn't appear after publishing 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#771]
In a test, the pop-up prompting the user to invite people that usually appears after publishing didn't appear. It just landed like this, part-way down the topic. He was making a voting topic - a standalone one, not added to any group. 

(Quite an important one as caused quite some problems later). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c33dcdae-67db-4ceb-b4aa-b62a4e05865c)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1292" alt="Screenshot 2024-03-13 at 16 52 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/90c2219b-9e99-40ab-a7ce-c0faf293c97a">
