### ISSUE TITLE
Voting: Deadline seems to be wrong 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#772]
I would need to go back through the video to be 100% sure, but I am 98% sure he didn't set the deadline to 6am (more like 6pm, but not sure). And it was the 6 Feb on the day of the test so 6am would have been before the test even started: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d0521ecb-2059-4625-a8d3-b4ee166fe72a)

**Comment by BeccaMelhuish** [comment]
OK yes can confirm now, it is showing as AM but should be PM: 

This is what he set: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/82e6fe58-919c-48cd-ab29-7ef3e20d2776)

This is how it displays: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1a5fda89-15a1-4ab1-b2da-7c67deed4b1a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I tried to replicate that, only way I could do it was to change the selection for date format from 24/h clock to AM  format, added an extra setting that will disable AM option if clock is past 12
