### ISSUE TITLE
Voting: Sending vote reminder shouldn't be possible when there are no participants

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#773]
In a test, due to an earlier bug (reported separately), user hadn't realised he hadn't invited anyone. He thought they just hadn't voted yet, so he sent a reminder. 

There was no error message to tell him that there was no-one to remind (as he was the only person in the topic) - it seemed as though the reminders were sent (though there was no 'Reminders sent' notification, it just closed). 

There should be something that flags the problem in such a situation.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d1e85d73-51bc-4d9d-98c6-c251fe4434c0)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish removed the send reminder buttons if topic has only 1 member

**Comment by ssin1901** [comment]
Fixed and closing (screenshot, screenshot2)
<img width="1440" alt="Screenshot 2024-03-27 at 16 49 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f95d42dd-6efa-4744-8769-75d0b16d8d3f">
<img width="1440" alt="Screenshot 2024-03-27 at 16 49 15" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fbcfa9f0-e6b2-42c4-b76d-025c7362106a">
