### ISSUE TITLE
Group: Bugs when inviting members to the group

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#775]
In group create flow, user was trying to add a list of emails:

He pastes them and clicks on Press enter to add:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/88a271bf-fe9b-4e09-b162-81eacea4ff64)

The press enter to add disappears and nothing happens: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/13ff9c29-b754-4925-860f-de30b6966c55)

Deletes them and paste them in again, and clicks on press enter to add. This time they disappear from the field but this happens: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/350c1c10-826e-464d-9195-9e15aa7cda25)

Tries just adding me not the full list, that does get added: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b7620576-cf2b-4175-8d75-d47eca7c8a9f)

But my email address stays in the box up here as well: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f87f4e9c-d956-43d2-b119-b32c42abbc8d)

**Comment by BeccaMelhuish** [comment]
Similar in this invite to group pop-up, invitees email stays in the box once added: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ca38cc7f-fd2d-4cd9-ac09-e6a59eb0ffd5)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I have some more along similar lines from a test done on Tuesday but only analysing today, so I will had the info here and you can see if you think the fix you've done is enough or there's anything new here :) 

She tries adding 3: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b9949058-9d79-4499-a6e9-abb672e0b449)

Only 2 are added, but there is an empty one at the end: 
(though Sara may have been added on the 2nd page, she didn't click it)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ebdfdbf9-1fd3-4403-9b0e-60173ebf0589)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish Yes that fixed these issues too

**Comment by ssin1901** [comment]
Works perfectly for me (see screen recording). Closing issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/80a96925-ff3c-42cb-b2aa-657d92a48c8b
