### ISSUE TITLE
Group: Message flashes up too fast after creating group 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#776]
After clicking this button, a green notification flashes at the top of the screen for a millisecond (so fast I couldn't screenshot it). It seems to say something about 'keep in mind'.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ef972388-d5a4-4a76-9214-6613c749038f)

**Comment by BeccaMelhuish** [comment]
I see this in another test, so it must have been this one: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4b931089-2979-4e22-876f-854883f8edca)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
@BeccaMelhuish seems fixed as the message did not flash on Chrome
