### ISSUE TITLE
Group: Empty rules of conduct

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#777]
@kevincrepin should we have something here for when they don't add rules? Looks odd/buggy at the moment :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/331c8840-9ad0-4959-9352-e94f520739d6)

**Comment by kevincrepin** [comment]
Maybe just a simple line of text stating that there are no group rules of conduct. Now it's just a lot of empty space, but it should behave as if there's nothing to show there :)
