### ISSUE TITLE
Dashboard: Page jumps up to top after closing pop-ups

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#778]
For these pop-ups that come up from these buttons, after closing them (i.e. not logging in), the page jumps to the top so user has to scroll back to where she was. Should stay in the same place. Same for all similar buttons on this page (e.g. groups, etc). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3da9ca9b-5137-4adc-a976-6ec5848243d5)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish moved to https://github.com/citizenos/citizenos-fe/issues/844 as duplicate
