### ISSUE TITLE
Login: Two users with ldiw.org emails didn't receive verification emails

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#779]
Tested with two users from LDIW and in both cases when they tried registering with their ldiw.org email addresses (through email and password registration) they didn't receive emails to verify their accounts and therefore weren't able to use that email address to log in. They created accounts with other emails (e.g. gmail) which did work.

**Comment by BeccaMelhuish** [comment]
Some more info on this - I didn't see this on screen, but feedback from the user the next day when we had a second call: 

"I can't log in, and the forgot password function and password reset doesn't appear to be sending me a reset to my work email", by which I assume he meant his LDIW email, and had forgotten that he hadn't been able to register using it the day before. So whatever is meant to happen (i.e. messages/guidance to them) when a user tried to log in with an account that haven't yet verified presumably didn't happen. 

I assume this is all related, sorry a bit vague - that's all I have :)  
(He later logged in with a different email address so we didn't go further into this problem).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I checked the e-mail logs and also our database, I can see from the logs that they got the e-mails at least they were delivered to the recipient and also some clicking action happened though I am not sure how mailgun collects that info. Maybe their spam filter just sent these e-mails to spam or trash etc.  I can see that we have 2 users in the testing database with ldiw.org e-mails and addresses are not verified so not sure what clicking action is in the mailgun logs.

**Comment by BeccaMelhuish** [comment]
Ah OK yes I guess must have been going to Spam. I will ask them to check and let's see :) 
(The clicking action is odd though, as I saw in the test what they clicked and it was to other email addresses) 
If it is going to Spam, is there anything we can do about that - I guess not?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish we cannot do anything for spam filters etc.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish as from mailgun logs e-mails have been sent out and it might have something to do with their spam filters I'll close this issue
