### ISSUE TITLE
Dashboard: X on you haven't engaged box - shouldn't be there? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#780]
Wondering why there is an X here, @kevincrepin should there be? Seems like should just stay until they have topics? (User in test almost clicked it instinctively without reading, presumably as used to closing popups when arriving on a page).

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/55ecd06f-6172-446e-920f-4799ae1034ad)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin removed the X as the box will disappear when user has topics there

**Comment by ssin1901** [comment]
x is removed (screenshot) and closing the issue.


![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/45844466-594d-4d52-b902-7c60fb744c1a)
