### ISSUE TITLE
Group: Rights are participant but should be member

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#781]
In create group flow, at invite people stage: 

(In bulk actions says member, but above says participant) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1c058228-ea8f-43ec-a1f0-15e219e36a00)

**Comment by BeccaMelhuish** [comment]
Same in this pop-up version of the same thing:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/caadb786-077d-4e7f-8371-dee1c31cdff6)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think the issue is fixed (see screenshot)
<img width="1417" alt="Screenshot 2024-03-19 at 15 52 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a4cceb81-67d4-4013-9f83-cec230059127">
