### ISSUE TITLE
Topic: No comments feature in topic text 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#782]
Not sure if this is a bug or just a Phase II/later thing, but can admins still add comments to co-create a topic text? A user was looking for this in a test and it didn't look possible: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e7e58ccc-efee-4abe-b89e-38b070bc8afd)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish will add back in the later phase
