### ISSUE TITLE
Topic: Participant can see and access draft topic. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#784]
In a user test, one user (admin) invited another user (group member) to join her group. He could see and get into the topic, but it showed without the discussion/voting bit.

He shouldn't have been able to see it at all, as drafts should be only visible to admins:   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e5763b3c-2090-492c-97e9-31f42c6f438b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish could not replicate the issue, please open a new issue with a screen recording if it occurs again
