### ISSUE TITLE
Topics: Should topics from a group show up in My topics? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#785]
Should topics that you have access to via a group show up in your 'My topics' as well, or only within the group that you access them via? Seems they currently don't show in 'My topics', only in the group. 

Not sure if this is a bug for @ilmartyrk to fix or a UX issue to consider (if the latter I can share more test insights soon).

**Comment by BeccaMelhuish** [comment]
Adding user insight tag here as users showed and verbalised that they were expecting them to.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish they do appear in my topics, always have

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah then it is a bug, as they often aren't :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think I need some examples here

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish could not replicate this as I tested with Chrome and every time I joint a group, the groups topics showed up under My Topics. Closing and let's reopen if the issue occurs again.
