### ISSUE TITLE
Voting: Participant was able to open 'Add voting system' process 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#786]
A topic participant was able to get some way through this process of starting a vote, despite not having admin rights. 

(I guess this may be related to a mix up between group rights and individual rights - the group had admin rights to the topic, but I think he had participant rights, maybe the system gave him something in between?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d501d202-da15-40d3-8529-ede65bac26c8)

He could get this far, then the Continue button didn't work: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/041b7621-7839-4b04-8901-cef0c727cdc3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Could not replicate, closing
