### ISSUE TITLE
Discussion: Page jumps to the top when click on reactions

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#788]
Screen should stay where it is when pop-up opens and closes, not jump up so they have to scroll down again: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2905580f-0fca-4644-9f04-df522c48848f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish moved to https://github.com/citizenos/citizenos-fe/issues/844 as duplicate
