### ISSUE TITLE
Voting: Neutral and Veto buttons stuck 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#789]
In start voting pop-up, user couldn't deselect neutral and veto: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4ec3996c-3e80-4178-bb50-84a153a67588)

**Comment by ssin1901** [comment]
This issue occurred on iOS and Android as well

![IMG_0040](https://github.com/citizenos/citizenos-fe/assets/72747107/f979412b-2900-4580-bff0-7f6e56d71463)

**Comment by ssin1901** [comment]
@BeccaMelhuish deselect issue at least is fixed (see screen recording). Closing the issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/ad9c59bb-3a73-4f9b-bb13-e04c565919d6

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk sorry, I uploaded the wrong recording. Here is the correct one
https://drive.google.com/file/d/1R1lVNHX_N59axIT8DRPcGw-oHNrsCByF/view?usp=share_link

**Comment by ssin1901** [comment]
Deselect works though, so closing the issue
