### ISSUE TITLE
Tour: Screen doesn't scroll correctly 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#790]
On the later and lower parts of the tour, the screen doesn't fully scroll down to the tour text boxes, so the users have to scroll down themselves. Should do it automatically so no chasing needing from the user.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish difficult to resolve there are many issues to make it work that way, currently it works without issues by scrolling to the element that the tour is referring to.
