### ISSUE TITLE
Emails: Dodgy invite to topic email heading

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#791]
For a topic within a group if this makes any difference: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9027e0c0-32a9-4cd5-9dfa-475123b42b4e)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3deb8974-c4c5-408c-aa4d-b9ee1c88ee22)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is related to the missing topicTitle in the subject field, I will soon test it, but I have a theory that it all might be related to users internet connection speed

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should now be fixed

**Comment by ssin1901** [comment]
@BeccaMelhuish closing because I could not replicate
