### ISSUE TITLE
Voting: When a voting is open should it take user to Vote tab?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#792]
Not sure if this is a bug or UX consideration, but currently when there is a vote going on in a topic that has both discussion and vote phases, is the system meant to take the user straight to the Vote tab? 

I thought this was this case, and if so there is a bug as in a test it took the user to the discussion tab when they entered a topic with a vote going on:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1d5bfd46-ebb6-4e03-be54-98535cb76a1f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it should and it does, but if url contains parameter that points to discussion it gets redirected to the discussion

**Comment by ssin1901** [comment]
Issue seems to have been fixed, could not replicate. Closing for the time being.
