### ISSUE TITLE
MISC: Testing error message recurrent and not closing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#795]
Just a test environment bug, but getting in the way a bit in testing so would be good to fix if possible - this one keeps reappearing at random times throughout (should only be when you first log in?) and seemed a user wasn't able to close it at some point (looked like she clicked a couple of times on the X and then gave up and left it there):  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3b01f607-52e4-4be1-9d36-ecc19dfb02b4)

**Comment by ssin1901** [comment]
Redundant now, closing
