### ISSUE TITLE
Group: Http failure response in My groups

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#796]
At some point in a test when user went to My groups, she got this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/567e7219-0c45-492b-a65e-30afcc4d4524)

(There was top left tiny loading symbol for a while, then it popped up). 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d2b58809-3332-4dcb-b4e6-e956f3aa1e62)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 I am 99% sure it is related to the API update during the test that I warned about
