### ISSUE TITLE
Group: Bugs in 'Show per page' for invites

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#798]
In create group flow, at the invite members stage, when trying to change this to 15 first time the number in the drop-down stayed on 5 (what it was originally on), and then the second time she tried the whole drop-down bit disappeared: 

After first time:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0704501f-b6bf-4020-9cea-227a3c14f2b1)

After second time: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b85c03e5-1054-4979-9a24-a88d31f5df81)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Seems to be fixed (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/ae56ae64-a0f3-46fe-8f16-7d02a139aa9a
