### ISSUE TITLE
Group: Public selection may be dodgy

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#799]
In a test video, it looks very much like the user tries to select public in group setup, thinks she has and moves one, but it didn't actually change from Private to Public. 

(Not 100% sure of this as she didn't verbally say what she was doing, but it really looks that way - her cursor goes to it, the Public dot and square flashes as if she clicked it, and then she carries on the the next bit).  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/56a0be03-743a-4aaa-ba3e-db086c6b6092)

**Comment by ilmartyrk** [comment]
It should be fixed now with changes to how these selections work.

**Comment by ssin1901** [comment]
Could not replicate (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/7ea8ab5d-6aae-4c95-b25a-4904e36988d9
