### ISSUE TITLE
GROUP: Incorrectly displayed selection box and placeholder in "Invite"

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#800]
**What is the problem?**
in Mac OS Safari 17.3, when a user is creating a topic and reaches the "Invite" stage, after inputting an email address, they get a selection menu that doesn't hide the text field positioned below (see screenshot1). 

Further, they don't see the _Press enter to add_ placeholder text

<img width="1440" alt="Screenshot 2024-02-08 at 16 49 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fc208288-257d-4660-a8b5-8f865da49b1f">

If the user happens to **add a space** after inputting the email, they then receive the _"Press enter to add"_ placeholder text (see screenshot2)

<img width="1440" alt="Screenshot 2024-02-08 at 16 49 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/21d25ae2-ad8d-4df8-8600-88d2de3a3c85">

**Why is this a problem?**
1. The selection menu is not displayed correctly 

2.Users should not be required to add a space after a single email address to receive text guidance. Most users will not understand how to add their valid selection. 

**Possible solution.**
1. The selection menu should "hide" the elements positioned below 
2. User should see the _"Press enter to add"_ placeholder appear after they have entered an email in a valid format i.e yourname@yourcomain.com

**Comment by ilmartyrk** [comment]
@ssin1901 will push to later stage as safari issue, but updated the input a little to display the message when multiple e-mails are entered as it is intended to be

**Comment by ssin1901** [comment]
Fixed and closing (screenshot1)
<img width="1187" alt="Screenshot 2024-09-23 at 14 31 00" src="https://github.com/user-attachments/assets/cd98c594-1e49-445c-98b8-0a626f37c3c4">
