### ISSUE TITLE
MOBILE: Text editor alignment makes it very hard to add a Description 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#801]
**What is the problem?**
_Tested with iPhone 6s Plus (5.5-inch screen, 414px × 736px viewport) on iOS 15.8.1_ 

_Tested with Simulator for iPhone 14 Plus - iOS (6.7-inch screen, 428px × 926px viewport) on iOS 16.2_ 

When a user goes to topic and then proceeds to description and expand the options in the text editor, the alignment of options prevents the user from being able to edit the text, and it is also very difficult to collapse the menu (screenshot1 from iPhone 6S Plus)

<img width="405" alt="Screenshot 2024-02-09 at 14 12 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e813d521-8725-4104-930e-eaf77c03b424">

Replicated in iPhone 14 Plus (see screenshot2)

<img width="459" alt="Screenshot 2024-02-09 at 14 06 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/533c400c-24ae-48e2-86be-75176a755f3b">

**Why is this a problem?**
User basically cannot edit the text on this device

**Possible solution.**
Text editor should not open vertically but horizontally. @ilmartyrk @BeccaMelhuish is there another design for this somewhere? Could not find it in the mobile Figma.

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the issue as much as I could

**Comment by ssin1901** [comment]
@ilmartyrk it is better but not optimal (see screenshot). But functionality wise it works as at least the user can make edits. Closing the issue till it comes up in a user test.

<img width="480" alt="Screenshot 2024-02-11 at 13 46 57" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a0719bb2-8f76-497d-8485-030b84c50d1e">
