### ISSUE TITLE
TOPIC: Pin Topic does not work

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#803]
**What is the problem?**
_Tested with iPhone 6s Plus (5.5-inch screen, 414px × 736px viewport) on iOS 15.8.1

Tested with Simulator for iPhone 14 Plus - iOS (6.7-inch screen, 428px × 926px viewport) on iOS 16.2_

On both devices, the "Pin Topic" button does not work (screenshot 1 from iPhone 6S Plus, screenshot2 from iPhone 14S Plus). 

<img width="405" alt="Screenshot 2024-02-09 at 14 43 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3372f7bf-b403-42d4-b819-434b365a421f">

<img width="446" alt="Screenshot 2024-02-09 at 15 34 52" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a66d2100-bb2f-4f45-8123-90323485f59c">

Further, the topic then doesn't show up as a Favourite topic (see screenshot3)

<img width="481" alt="Screenshot 2024-02-09 at 15 39 45" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1677e0ef-b102-4912-8b3f-7ef53ba638e3">

**Edit - Was replicated in Safari and Chrome as well. Removed the Mobile tag**

**Why is this a problem?**
User cannot pin a topic

**Possible solution.**
User should be able to pin a topic and it should appear under My Topics>Favourited topics

**Comment by ssin1901** [comment]
Now works

**Comment by oksks** [comment]
Doesn't work for me, Chrome on Mac :/ Reopening.

**Comment by oksks** [comment]
Doesn't work on iPhone 14 pro, either.

**Comment by ilmartyrk** [comment]
@oksks @ssin1901 yes, it was intended to be just an indicator and the actual action is in under topic actions menu, but made the icon clickable as it seems quite intuitive thing to do

**Comment by oksks** [comment]
Tested, works, thank you!!
