### ISSUE TITLE
Groups: Can't get into My groups or Public groups

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#805]
Right now when I click on these in the menu, they are 'dead' links: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f001ca14-1dfc-40a4-b22b-28d048d08693)

**Comment by BeccaMelhuish** [comment]
Also when I click on any group here, it doesn't open: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/45982ef4-9d10-4af1-89da-076546be7d2b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish might have been caused by some update going on, did you refresh? I cannot replicate it
