### ISSUE TITLE
Group: Missing manage participants 'Save' button 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#806]
In create group flow, co-creators box 'Manage' pop-up: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9a99da95-b6db-47fd-9a43-ac1f652eceaf)

**Comment by BeccaMelhuish** [comment]
Just to clarify though it does still work by clicking X, so maybe not the highest priority?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish there is no button in the designs there, I am closing this issue for now
