### ISSUE TITLE
Topic: Co-creation bug - users not seeing the same topic text

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#807]
User 1 had written this in the draft: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/04e74fad-b8db-4f31-bd20-95b7f6ab0aa5)

When User 2 went to edit it, he saw this (no intro or text): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f79ae20b-09c8-4878-bde9-4cfbbc0687b0)

**Comment by BeccaMelhuish** [comment]
When he opens this field it isn't there either: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2e0ee736-445f-491d-b292-e59eb3e6e4d9)

**Comment by BeccaMelhuish** [comment]
Then there is "loading" for a bit, and it does appear, but a good few seconds after he has opened it: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4f9ff54a-8a7b-4917-bc27-55076fbd2858)

**Comment by ilmartyrk** [comment]
Etherpad sync takes time, nothing to do there, intro part is also a little more difficult to solve

**Comment by ilmartyrk** [comment]
It doesn't seem to be worth fixing this issue as it provides little value to big effort in the changes relating both in the API and FE side.
