### ISSUE TITLE
Topic: When editing topic intro text field disappears

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#808]
User 2 comes to topic (as co-creator) to edit what User 1 has written.

Starts like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f49ff46e-e450-470e-9f4c-5388c30007f1)

Deletes it 'Jim': 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ecb5b5df-2079-4e91-a0ac-9dc4be90dfd8)

Once fully deleted, it collapses: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/44408274-b189-4c2e-b732-6b2604a93ce0)

Clicks on "Intro" again and it reappears: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1f3be8db-672e-4edc-8582-219a81710803)

Shouldn't collapse when cursor is in it :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  should be fixed

**Comment by ssin1901** [comment]
@BeccaMelhuish closing because I could not replicate.
