### ISSUE TITLE
Topic: Group rights reverted back to admin 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#809]
User 1 set group rights to (member) for this topic. When user 2 comes to the same place (as co-creator), it had reverted back to admin (should be default member anyway as raised in another issue). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4e93ac95-8359-4c5e-b3a6-a84632c922ad)

**Comment by BeccaMelhuish** [comment]
Seems an important and 'broken' thing, adding high priority(?)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Could not replicate, closing this issue
