### ISSUE TITLE
TOPIC: Manage Participants->Order by role symbol is incorrect

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#811]
**What is the problem?**
Under Manage Participants->Order by role has two downward arrows instead of one downward and one upward (see screenshot)

<img width="1440" alt="Screenshot 2024-02-09 at 16 52 01" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3a9dacd8-a11c-49b7-b4c3-f5a9645d4ab4">

**Why is this a problem?**
Confusing to the users

**Possible solution.**
One arrow should be pointing upwards

**Comment by ilmartyrk** [comment]
@ssin1901 seem ok for me, what browser are you using?

**Comment by ilmartyrk** [comment]
@ssin1901 I could not replicate it with different browsers so closing this issue
