### ISSUE TITLE
TOPIC FILTER: Topics that need my vote does not present accurate data 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#812]
**What is the problem?**
When the user goes to My Topics and selects the filter "Topics that need my vote" (screenshot1) they get a topic where the voting has already ended (screenshot2)

<img width="1436" alt="Screenshot 2024-02-09 at 17 02 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/dd8da6cd-75f8-4f0f-88fc-2ddee81f3e23">

<img width="1437" alt="Screenshot 2024-02-09 at 17 02 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0790eccf-dd99-48d0-ae73-447b8f47a4e2">

**Why is this a problem?**
Topic filter is not functioning as intended

**Possible solution.**
My Topics->Topics that need my vote should not show topics where the voting has ended.

**Comment by ilmartyrk** [comment]
@ssin1901 is fixed now

**Comment by ssin1901** [comment]
Seems to be fixed now
