### ISSUE TITLE
Voting: Long vote question goes out of view

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#813]
Field should expand to show it all if longer than 1 line? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b28c1e4a-d942-42b8-981c-5fbee06c2e29)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is generic behavior of input fields I don't see any reason to fix this as it still readable and useable
