### ISSUE TITLE
Voting: Max options field keeps jumping down to 1

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#814]
In test, user kept changing this to 2, every time she clicked in the "Create your own custom choices" box it jumped back down to 1 again: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e74974e8-2b8a-4f1e-8c15-54b583253433)

**Comment by BeccaMelhuish** [comment]
Is a broken thing so adding high priority(?)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish could not repeat this issue, guessing it is fixed with other updates

**Comment by BeccaMelhuish** [comment]
Ok can be closed then unless @ssin1901 needs to test :)

**Comment by ssin1901** [comment]
No jump found, closing the issue (see screenshot)
<img width="1295" alt="Screenshot 2024-03-13 at 16 59 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6efefe61-0515-40e9-b291-5c73a68976d1">
