### ISSUE TITLE
Voting: Remnants of selected then unselected boxes in vote

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#815]
When a vote option has been selected then unselected it sometimes has a thin blue box around the selection dot. (Looks buggy and causes confusion). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/65c0d67b-b990-4ed5-af5a-8c3348d7976d)

**Comment by ssin1901** [comment]
Interface has been improved and issues resolved (see screenshot). Closing this issue.
<img width="1374" alt="Screenshot 2024-03-27 at 17 22 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d2664760-fa69-4434-8680-b5da9407bae4">
