### ISSUE TITLE
Voting: User voted then delegated vote, still said vote was registered

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#816]
In a test, two users were experimenting with delegating vote from one to another. 

User 1 voted herself. 
User 1 then delegated her vote to User 2 (not a real-life situation, they were trying it out). 
After doing so, the part of User 1's screen that I could see still looked like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/277a01c4-1504-482d-86d6-228eab11a6a7)

If delegating after having voted, should switch to delegated vote view, not vote registered view.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish the delegation info should be below this box under "Your chosen options". I guess only thing here is to change the copy text a little if you think it is not OK at the current moment, but for me delegating your vote is basically the same as choosing an option from the list so the copy text isn't invalid in this case. Also we display it as "Your chosen option"

**Comment by BeccaMelhuish** [comment]
OK yes, let's leave it as is then :)
