### ISSUE TITLE
Groups: Not found when clicking on topic on card

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#817]
When user clicks this topic showing on her card, she gets not found error: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1d788057-554a-4077-a017-d59adc7a96a1)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/87630552-1b3f-436f-b3c4-2fd2e6da1897)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue, also looked for other places that still had old structured links to groups and topics
