### ISSUE TITLE
GROUPS: Reset filter button does not work 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#819]
**What is the problem?**
In My Groups-> the reset filter button does not do anything (see screenshot)

<img width="1290" alt="Screenshot 2024-02-11 at 13 55 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9916d809-62c0-405f-b237-10f0a9933855">

**Why is this a problem?**
User cannot reset the filters

**Possible solution.**
The button should reset the filters

**Comment by ilmartyrk** [comment]
@ssin1901 just clearing that it is actually group view not my groups view, but fix is on the way
