### ISSUE TITLE
ACTIVITY FEED: After admin user deleted a group, the original author was not notified 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#820]
**What is the problem?**
1. User Ozzie made User Sara, a Group admin while remaining admin themselves.

2.User Sara then deleted the group.

3. User Sara could see the deletion in the activity feed (see screenshot), user Ozzie could not

<img width="1297" alt="Screenshot 2024-02-11 at 14 08 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d9319e80-056c-4326-969b-4c6ae94be09b">

**Why is this a problem?**
User Ozzie cannot retrace what happened to their group from the Activity Feed. Basically was not notified on the web application itself.

**Possible solution.**
All group admins should be updated about group deletion in the Activity Feed

**Comment by ilmartyrk** [comment]
@ssin1901 posted an update
