### ISSUE TITLE
ACTIVITY FEED: Username not being retrieved 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#822]
**What is the problem?**
In the Activity Feed, in one case the username his not being retrieved (see screenshot) 

NB! In this case, the user had deleted themselves from the system

<img width="1296" alt="Screenshot 2024-02-11 at 18 19 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/195f1b43-b4a6-4844-b494-c2b520d96b6a">

**Why is this a problem?**
User does not know which user performed the activity. 

**Possible solution.**
Correct username should be retrieved or at least say "Deleted User" or something to that effect.

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the issue
