### ISSUE TITLE
MOBILE: Add attachment not working properly

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#825]
**What is the problem?**
_Tested with iPhone SE (4 inch screen, 320px × 568px viewport)_

On iPhone SE, the add attachment button is not being displayed properly and the user cannot add an attachment (see screenshot)

![IMG_0038](https://github.com/citizenos/citizenos-fe/assets/72747107/cb9f3cd8-6df4-48f4-ad4e-1763d5bb34ee)

**Why is this a problem?**
User cannot add attachment

**Possible solution.**
User should be able to add an attachment and the button should be displayed correctly

**Comment by ilmartyrk** [comment]
@ssin1901 not sure if I can fix that. seems to be really specific issue

**Comment by ssin1901** [comment]
@ilmartyrk can we move some of the iPhone SE specific issues to phase 2? Then we don't need to fix and test them in this phase. Maybe even Phase 3 if needed.

**Comment by ssin1901** [comment]
Closing as duplicate of #898
