### ISSUE TITLE
MOBILE: voting deadline datepicker not being displayed correctly 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#826]
**What is the problem?**
_Tested with iPhone SE (4 inch screen, 320px × 568px viewport)_

On iPhone SE, the voting deadline date picker is being displayed correctly (see screenshot)

![IMG_0042](https://github.com/citizenos/citizenos-fe/assets/72747107/6d29aaac-bdfe-4248-8bb8-7729716022a5)

**Why is this a problem?**
User cannot understand which date is being selected 

**Possible solution.**
Datepicker needs to be responsive

**Comment by ilmartyrk** [comment]
@ssin1901 this is fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot) 
![IMG_0063 2](https://github.com/citizenos/citizenos-fe/assets/72747107/a52a6b5f-31c3-486c-9a0e-ed6080251209)
