### ISSUE TITLE
MOBILE: Submit your vote button did not work 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#829]
**What is the problem?**
Tested with iPhone SE (4 inch screen, 320px × 568px viewport)

On iPhone SE, the Submit your vote button did not work (see screenshot)

![IMG_0050](https://github.com/citizenos/citizenos-fe/assets/72747107/207f7824-995f-4279-844d-e029279b465f)

**Why is this a problem?**
User could not submit their vote

**Possible solution.**
The submit your vote button should work

**Comment by ilmartyrk** [comment]
@ssin1901 I cannot replicate it in my browser, it seems to be  a multiple choice voting, but no options are selected, can you add more info please

**Comment by ssin1901** [comment]
@ilmartyrk I will try to replicate it and provide more details but if the issue was the choices not being selected, then shouldn't the submit button be greyed out? It seemed here that the user can Submit and the button is just not working.

**Comment by ssin1901** [comment]
Fixed and moving to Done
