### ISSUE TITLE
IS: Unable to vote from invite link

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#831]
**What is the problem?**
I received an email invitation to the voting topic: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/aa2a1681-b617-4c57-849b-63bd88a52320)

These is also copy issue: "There is only -4 left..." I think it should say 4 days left @ilmartyrk @BeccaMelhuish  :)

After clicking on it, I receive this error message: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/be164548-b045-424d-8639-dd2bc873a769)

**Why is this a problem?**
Unable to vote when clicking on voting topic and error message does not help me to understand what went wrong or what should I do.
After logging in from the same page where the error message was previewed, I am able to log in, but I don´t have any information about the topic I was invited to.

**Possible solution.**
Email link should direct me in the topic and if the voting is closed or I don´t have permission etc, the error message could say so :)

**Comment by ilmartyrk** [comment]
@anettlinno fixed the issue though e-mail update will take  a little more time to go through Crowdin sync

**Comment by ssin1901** [comment]
Tested and could not replicate. Closing the issue.
