### ISSUE TITLE
IS: In invite co-creators pop-up, add bulk action 'remove'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#833]
There should be remove all option here I think? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f90cad0c-4524-409d-9713-2bdc907d6ad3)

**Comment by ssin1901** [comment]
@BeccaMelhuish @ilmartyrk this is for Bulk permissions for invites? Didn't we remove this option? (screenshot)
<img width="1440" alt="Screenshot 2024-03-19 at 13 03 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bf5ebc76-9f42-4630-904f-756b65d0ff51">

**Comment by BeccaMelhuish** [comment]
@ssin1901 that's the 'Manage participants' which is a different place to where you invite (you have to click the invite button). But if you were confused there (thinking that's where inviting happens) then I'll make a note of it in potential UX issues to keep an eye on - I sometimes get confused there myself too, expecting inviting to be part of managing :) 

'Remove all' has been added to the invites pop-up though it seems! 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9e396f18-85e9-495d-9f40-d0345d74a337)

**Comment by ssin1901** [comment]
Seems to be fixed (and closing)
<img width="1377" alt="Screenshot 2024-03-27 at 18 23 45" src="https://github.com/citizenos/citizenos-fe/assets/72747107/58d16554-60ff-489e-b936-3bb600c59003">
