### ISSUE TITLE
Misc: Help button dodgy

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#837]
In one of the tests, Help button in menu didn't work at one point, but did at others. There was a notification 'hanging' unclosed, from earlier (see the top), if that could be related? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d4b15d58-9a8d-4284-9e29-4d238bd215f3)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I think these were related and there was an invisible overlay that prevented clicking on items, closing this issue
