### ISSUE TITLE
Misc: Notification wouldn't close

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#838]
When user clicked X, nothing happened: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a93dca8b-0aa9-4f1e-98ea-f9143ecabdf1)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should now be fixed together with other updates to displaying notifications

**Comment by ssin1901** [comment]
Seems to be fixed as I haven't been able to replicate. Closing the issue now.
