### ISSUE TITLE
Voting: vote reminder once already closed

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#839]
Still shows even though vote is closed, but shouldn't:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cf783d61-3a5c-4b83-8320-1c91809aad04)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the issue

**Comment by ssin1901** [comment]
Fixed and closing this issue
