### ISSUE TITLE
Misc: Help Centre back button took user back in the main page

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#840]
When she clicked HC back button, it took her back from Preview to Settings in the topic creation flow. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4166ba22-e4f8-4251-a881-5ec2711d0ee2)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this need some code changes from our webpage

**Comment by BeccaMelhuish** [comment]
Ok yes I guess doesn't matter for the time being now anyway, assuming we won't have a back button on the temporary form one :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish closing this issue as we have the form for now and will create a new issue if needed for HC in the future. I want to clear all the small hanging issues so we get a better overview of things that need fixing on our current scope. Also we already have quite a lot duplicates popping up so we will get a new issue if it happens in the future
