### ISSUE TITLE
Topic: Discussion contributions copied into new topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#841]
@ilmartyrk Quite a funny thing happened in Friday's user test. I assume it may have been something you were doing behind the scenes during the test as you mentioned it may be glitchy, but here it is: 

- User set up a discussion topic, and we had a mock discussion
- User got very confused at voting stage and so created a vote that didn't make sense
- She then closed the vote, as it was wrong
- She then found that she couldn't edit and re-start the vote in the same topic (I will make a separate UX issue about that, this one is just about the bug)
- She then made a new topic, so we could try out the voting process
- She starts a discussion topic (not in the same group or anything, just a totally separate and new topic) 
- Once published she tries adding a test argument: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8b6f8dfc-5707-40fa-b0e4-d271fa9cb82f)

- As if my magic, when she added her argument, all of the discussion contributions from her first topic appeared! 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cd07ff48-a5b9-4cba-8036-c87d9795797c)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk just bringing to attention in case it got missed :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I tried to replicate it, but couldn't do you have any extra information about what browser and OS was used

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I'm sorry I don't have that info :( I can easily email her to ask (she is a COS partner) but I've cross-checked the time-stamps and it happened 25 minutes after you posted this, as you had to clean the etherpad database in the middle of a test. Do you think it was likely this? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/60780675-b0e6-4d8e-b186-4d3e5ae9b8cc)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I am not sure what happened, I have tried to replicate it, it is not that contributions are copied into new topic, it is that previous topic contributions were loaded instead of new ones. I remember that we had similar issue and I posted a fix for that. I could not replicate this issue. so sending it to testing, maybe it will happen on Mac

**Comment by ssin1901** [comment]
Have not been able to replicate the issue in Mac with Google Chrome. Closing the issue.
