### ISSUE TITLE
Login: No way to see if password typed correctly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#846]
**Round 2 insight:** 

User (dyslexic) struggled to know if her password was typed correctly.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/72fcc37b-235f-419a-bf99-0a6b11b26c47)

**Suggestion:** 

Should be a way to show/hide it, e.g. little eye icon.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin posted a fix, hope it is ok

**Comment by BeccaMelhuish** [comment]
Thank you! It's an improvement but usually there is a line through the eye when it's not visible, so it's clear it's a show-hide button: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5764c6b8-aa58-4771-9a58-f646927a91b2)

And should be added here in registration too :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4c9fa069-9bf1-4a4b-9bfa-569cf30354f4)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk It needs to be on the registration page too, on both password lines :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8506d6c3-8e86-4fee-930d-e8c463bc18cb)

**Comment by ssin1901** [comment]
Closing (see screenshot)
<img width="1233" alt="Screenshot 2024-03-03 at 21 56 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/765f5d39-5162-4974-9403-782e06f25980">
