### ISSUE TITLE
Group: Users think padlock icon means 'locked' 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#848]
**Round 2 insight:**

Another user voiced that this padlock at the top means 'It's locked, I can't edit' (as was also voiced in Round 1): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a00ac8f9-fb8c-4c6a-a7ce-7585ff1baf6e)

**Suggestion:** 

I think after Round 1 we already agreed in another issue that the one at the top should be removed now we have it in the info further down (with explanation next to it), so I suggest we do that. Tagging @kevincrepin in case of objections though :)

**Comment by kevincrepin** [comment]
Yeah let's only have it in the info box.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish removed the icon
