### ISSUE TITLE
Vote: Users need to be able to move the order of vote custom choices

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#849]
**Round 2 insight:** 

Users need to be able to easily change the order of these custom choices once entered, so that if for example they need to add a new candidate in alphabetical order, they can do so without having to delete and re-type all the ones that come after it. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c0fbf5a3-bb68-4e28-bf95-7a187eb97a4d)

**Suggestion:** 

@kevincrepin @ilmartyrk Can we make them draggable?

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish added the functionality as it was really easy do to, but it is not that clear that users can do this function

**Comment by kevincrepin** [comment]
@ilmartyrk Can we add this icon?
![Screenshot 2024-02-22 at 11 45 52](https://github.com/citizenos/citizenos-fe/assets/26792281/56892df2-64db-4b62-bc95-5ccae2648210)

Here's the svg: 
![Change Order](https://github.com/citizenos/citizenos-fe/assets/26792281/94710555-81a7-485c-ab31-5cdc5ff7c9db)

**Comment by BeccaMelhuish** [comment]
And it should also be the case that you can only drag it when you have clicked and dragged on this icon (and hover state over the icon should be a little hand rather than cursor I believe, to make it clear what will happen when you drag?).

As currently as it is, if you click and drag to try to select a word within that field that you want to edit, it drags the whole thing, which isn't what you want in that case.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin updated the solution

**Comment by ssin1901** [comment]
Fixed and closing this issue (see screenshot1)
![Screenshot 2024-03-03 at 22 05 56](https://github.com/citizenos/citizenos-fe/assets/72747107/cecc9f25-4a32-41bc-8829-35b4658b9577)
