### ISSUE TITLE
Login: User gets lost in Registration when field titles disappear 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#850]
**Round 2 insight:** 

User (dyslexic) got lost in registration form, as had put surname into email box, then couldn't see where to put email. (She worked it out, but still - caused confusion). 

**Suggestion:**

@kevincrepin @ilmartyrk Can we do it like Airbnb does it, it gets smaller and goes above what you're typing? And I guess same for login and anywhere else that we have titles of a field in the box that currently disappear when you type in them? 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3a771774-9887-4ffa-8eaa-6ff21a1b60a3)

**Comment by kevincrepin** [comment]
Yeees, the design was like that ;)

![Screenshot 2024-02-13 at 18 04 22](https://github.com/citizenos/citizenos-fe/assets/26792281/d07b2fc1-dcfa-47fd-a4e6-a7cd6a111698)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I thought I already added the design solution everywhere, but noticed it wasn't here so posted a fix. Let me know if you find any other inputs like that.

**Comment by BeccaMelhuish** [comment]
Looks good! The only other one I've seen is this, but it's a bug already [here](https://github.com/citizenos/citizenos-fe/issues/765) :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e0fdef8d-6307-48ae-ab62-0412135839c4)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the argument subject placholder for new and edit argument forms

**Comment by ssin1901** [comment]
Seems to be fixed and closing
