### ISSUE TITLE
Vote: Users suggest vote reminders to only be sent to those who haven’t voted

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#851]
**Round 2 insight:** 

Users were unsure if vote reminders are only sent to those who have not voted, and suggested if it's not the case then it should be. 

**Suggestion:** 

@ilmartyrk Is this is the case already? If so, @kevincrepin shall we make this clearer somehow, and if not shall we make it the case?

**Comment by kevincrepin** [comment]
It's written here. I think we can assume that in a non-testing scenario they would read this?

![Screenshot 2024-02-13 at 18 18 35](https://github.com/citizenos/citizenos-fe/assets/26792281/f318a331-c717-432a-adb9-2036b8fbe8f0)

**Comment by BeccaMelhuish** [comment]
Hmm yes I think so. Will keep an eye, but closing it :)

**Comment by oksks** [comment]
@BeccaMelhuish @ilmartyrk - I just got a vote reminder email, for a topic I have already voted on 1-2 days earlier.
