### ISSUE TITLE
Voting: Users had a little difficulty finding how to get voting results

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#852]
**Round 2 insights:** 

It was nothing at all like as difficult as it was in Round 1, so the changes we made in #679 definitely helped, but there was still a couple of users who had trouble finding how to get the results. 

**Suggestion:** 

I wonder if just making this text bold might help draw attention to it? Or @kevincrepin maybe you have another idea for drawing more attention to it -  a bit of colour or something visual? Sometimes when they have voted themselves it gets a bit lost in all the other text about their own vote choice etc. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4f2c1782-1d04-4c47-816a-fc895459bf78)

**Comment by kevincrepin** [comment]
Let's make it bold but I wouldn't do any more visual things to draw attention – ideally...It's jsut getting noisier and noisier like that. Kinda hoping that with bold and actual usage people would read that :)

**Comment by BeccaMelhuish** [comment]
OK good yes, fingers crossed! :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk if possible by Thursday at noon for next admin tests, would be perfect :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the texts
