### ISSUE TITLE
Users get confused about 2-letter country code for eID voting

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#853]
**Round 1 and 2 insights:** 

Some users get quite confused about the 2 letter country code here for eID voting, usually thinking it means the phone code for the country. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c3ff3e21-8a45-4b22-a7b9-bc5044f3c1e1)

**Suggestion:** 

@kevincrepin @ilmartyrk 
- Seeing as we only have eID in Estonia, do we need this, as it will always be the same? Or could it be pre-filled? 
- Or should we have a help button here? 
- I guess there is the same issue for login or connecting account to eID so whatever solution we find here we could do across them all?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincreping let's prefill it now and disable changing as we currently only support Estonian and I suggest we add dropdown with pre-defined options in the future, this is the way that many other sites have gone with

**Comment by kevincrepin** [comment]
Yep, I agree with @ilmartyrk

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin made some changes to the form behavior that should make it clear that this field is mandatory

**Comment by ssin1901** [comment]
Fixed and closing (see screenshot)
<img width="1222" alt="Screenshot 2024-03-03 at 22 15 33" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0f5cc783-b55c-43c4-8afd-590ceddacf5b">
