### ISSUE TITLE
Topic: Some issues with finding the 'Manage' menu for topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#854]
**Round 2 insights:** 

Significantly less of a problem than in Round 1, so what we did in issue #680 has helped, but there were still some issues with finding the 'Manage' menu for topics. 

**Suggestions:** 

@kevincrepin Might we try making it just a little bit more attention-grabbing, as it's such an important one? E.g. the style of the Manage vote menu and with a bit of colour like the activity button or similar? Or do you have any other ideas for this? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5caa25f1-82f3-4adb-a1c8-0de47f6b9947)

**Comment by kevincrepin** [comment]
Sure, it can look more like a small button:
![Screenshot 2024-02-22 at 11 32 52](https://github.com/citizenos/citizenos-fe/assets/26792281/28312694-240e-48d8-b5f0-b5091b593ab8)

I updated this in the components @ilmartyrk

**Comment by BeccaMelhuish** [comment]
OK great thank you @kevincrepin! Would that be just for the info box, or for the participants box 'Manage' too?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the design, also for participants

**Comment by kevincrepin** [comment]
Yup was meant to be for both 👍
