### ISSUE TITLE
Login: Too many steps to access a topic or group 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#856]
**Round 1 and 2 insights:** 

As raised in this bugs-focused issue #739 and raised by @ssin1901 too, there are really very many steps to access a topic or group, when you've been invited to it. Users didn't express frustration verbally, but my guess is they were being polite or more patient that usual as it was a user test not a real situation.  

Users did however express (one in Round 1 and one in Round 2) that 'super-fast login' was going to be really important to use of the platform being desirable/successful for their projects, so they were definitely clear that streamlining this would be important.  

**Suggestion:** 

@kevincrepin @ilmartyrk I don't know if streamlining the login process so that it is really optimal (i.e. the fastest and simplest we can possibly get it) is something that would be doable for Phase I (that's up to Ilmar and PO), but if it's the case that working this out fully gets postponed to post-launch, is there something we can do in the interim to at least shave off some of it? 

For, example, as mentioned in the bugs issue above (739) - some of the pop-ups are duplicate actions - e.g. they have already ticked OK to the T&Cs, and already clicked the join topic. But maybe there is more we can do as a quick fix to streamline a little more?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish as the issues mentioned are fixed I currently don't see any good way to streamline this process as mostly it is related to registering account if one is not created yet. I think after that it is quite clear flow. I suggest we close it for now and come back if we get some live usage feedback about it

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ok yes, can we add it to phase II? Quick and easy login is a super important one for users, so deserves some good thinking through when we have time :)
