### ISSUE TITLE
Login: User confusion in the account verification flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#857]
**Round 2 insights:** 

Somewhat connected to issue #856 as is about making login quicker/easier, but a distinct issue in itself: the flow for verifying an account is causing some confusion. 

It caused two issues: 
-  One user spent 10 long minutes trying to get into the platform as she hadn't noticed or correctly understood (dyslexia didn't help) the notifications telling her she needed to verify her email account. After trying to make two different accounts, looking and failing to find a way to contact support, looking through the Help Centre (have noted this for HC in future), I in the end had to tell her. 
1. She missed this notification both times she tried to make an account: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7bc74957-0297-4311-aee8-e399e95b2323)
2. She misunderstood this one, thinking it was telling her the password was wrong: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/796d3e16-2076-455c-8929-e9671af0f055)

- Another user registered her account and didn't notice the notification telling her she needed to authenticate it:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5ddc1086-1930-4b84-9e2f-57aa4f3d5093)
So after registering, she gets back to the dashboard and thinks she is now logged in. She starts looking around and is quite confused about why she can't see anything about making private topics, only public ones. 
She later explains (once I have helped her), that she didn't notice the notification because it’s so similarly coloured (pale and blue), and that she is used to getting “Thank you, you can now log in”, to guide her that she still needs to log in after registering.

- Another user also missed the blue notification, and I think some in Round 1 did too. (But it didn't cause such big issues in this cases - the red error message was enough).  

**Suggestions:** 

- I'd suggest we redesign the registration flow so that it guides users in a much more step-by-step way (both through email authentication and also through logging in once that's done), within the same bit of the window, i.e. right here, and not using notifications at the top. Wdyt @kevincrepin? I think it's more standard UX to do it like that? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/54ad5200-5eae-49fa-a741-ef09a14c2938)

- Would also suggest we make our notifications here more dyslexia-friendly (actually something this test showed we could do across the board), by having one or two keywords big and bold so for people who don't actually read messages but just guess what they might be saying, they will guess more closely - e.g. **Verify your email!** or **Check your inbox!** as a heading for the message, for example.   

**Side note:** 

- Is there a reason we don't have social logins available when people are registering their account, only for logging in? As then they could just register with one click, so much easier! And tends to be standard registration UX to have them.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish registering using social logins actually works, but I agree that we should add these buttons to the registration form

**Comment by kevincrepin** [comment]
Yep,  I also agree. Added everywhere in the designs.

**Comment by BeccaMelhuish** [comment]
Ok that's good, thank you! 

Though @kevincrepin for email and password registration, what about a flow for guiding people more clearly through the steps of validating their email and logging in? As above, many people were missing/misunderstanding the 'validate your email' notification (in one case causing a 10-minute registration process only resolved with help from me), and one didn't realise she still needed to log in after registering - she assumed she was already :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin  I have to say that this register account flow is quite generic and universally used for who knows how long time so I would not generalize this as a big UX issue,  maybe we can tweak the message a little, but not sure if it will actually help.

**Comment by kevincrepin** [comment]
I agree this is pretty standard and maybe reason why this perosn didn't manage is because they use mostly social media logins? Not sure of course. WOuld also say that maybe with copy it can be fixed because this is as basic as it gets ;)

**Comment by BeccaMelhuish** [comment]
They're very often not seeing this notification at all though, it just blends in - is there something we can do to make it less easy to miss? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6cad815a-817b-4d47-b2a9-5cc1853c1380)

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk And if at all possible before Thurs for the next user tests, would be perfect :)

**Comment by kevincrepin** [comment]
It's a fair point @BeccaMelhuish that it is too subtle. I propose we make it into a dialog then it will be much more "in your face":

![Screenshot 2024-02-28 at 10 22 44](https://github.com/citizenos/citizenos-fe/assets/26792281/ed86e028-1a85-45a1-954b-4511eaa8f934)

@ilmartyrk you can find it (also for mobile) here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=248%3A35545&mode=design&t=pcxQxFzxhEfBUgW3-1

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the dialog

**Comment by BeccaMelhuish** [comment]
This is great, thank you both! Will leave open in case @ssin1901 needs to QA test but otherwise can be closed :)

**Comment by BeccaMelhuish** [comment]
I assume no need to test any more, will close it :)
