### ISSUE TITLE
Voting: Results spreadsheet is not set out in a clear and useful way

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#858]
**Round 2 insight:** 

Two tests showed that the voting results spreadsheet isn't organised in a way that is easily understandable and useful (for further analysis) to users. (More info coming depending on the below). 

**Suggestion:** 

@ilmartyrk before I add more context and suggestions here, how much flexibility is there in the way that results can be set out in the spreadsheet? Can we have it generated any way we want it to or are there some restrictions?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk What do you think about changing the spreadsheet - is it technically possible to do or a big job? More of a Phase II thing?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is technically possible to change it, but will need better overview what to change

**Comment by BeccaMelhuish** [comment]
OK yes, I can give more input in Phase II then :)

**Comment by BeccaMelhuish** [comment]
Closing this as I have now created this issue with proposed solution: https://github.com/citizenos/citizenos-fe/issues/1518
