### ISSUE TITLE
Discussion: Contributions don’t load live, could they/should they? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#859]
**Round 2 insight:** 

In a test, user wasn't seeing the discussion contributions that people had been adding behind the scene, as she had the tab open and they weren't loading live, only when she navigated away and back to it. 

**Suggestion:** 

@ilmartyrk Maybe it's a later phase thing, but would be really good if the contributions could pop-up when someone has posted rather than only when you leave and return, if that's technically possible? Unless @kevincrepin sees a UX issue with this? I guess it could cause things to jump around?

**Comment by kevincrepin** [comment]
This is more a technical thing with its own implications – realtime refreshing etc. Sure it opens a can of worms, but maybe doesn't! :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk what do you think about this from a technical perspective - is it possible? Though probably more of a Phase II thing if so?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish technically it is a whole different solution than our current as it needs to use Websocket to be basically be constantly connected to our API server. It is a really big change in terms of our whole setup, but I guess it might be up for discussion

**Comment by BeccaMelhuish** [comment]
Very similar to [this issue](https://github.com/citizenos/citizenos-fe/issues/1256), so I will close this one :)
