### ISSUE TITLE
Voting: Users misunderstand what vote delegation is 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#861]
**Round 2 insight:** 

Users misunderstand what vote delegation is and how it works. 

What they think it is this, which is something they say they would find useful: 
- User 1 can't vote, so gives their right to User 2 to vote for them
- User 2 receives a notification saying that they've been delegated to vote for User 1
- User 2 votes for themselves, and also votes separately for User 1
- The two (or how ever many, if several people have delegated to them) votes can be different, as per whatever Users 1 and 2 have agreed between themselves.

Side note for future: delegating e-ID votes is very desirable according to a user who tested General Assemblies in Estonia, and not having this possibility he said would be a barrier to him using it for a GA, as he thinks it not being possible would prevent him getting quorum. If we had this feature, there would (I think, needs checking) need to be a way for User 1 to e-sign the right to vote for them across to User 2 (as well as for user 2 to e-sign it). 

However, I wonder in both cases if their expected need for this is because they are used to running their votes offline/synchronously in a short period of time (as if a user is able to log in to the platform to delegate their vote, surely they could just vote themselves just as easily). But not sure, needs more thoughts and research into their processes, timelines, etc. It might be what they need is a way to delegate a vote in advance of the vote actually being open, if the person is not able to vote on the day of the event (if it is a GA for example, and they have chosen to run it with only a short voting window).  

**Suggestion:** 

- Short-term: @kevincrepin Can we have a help button next to it in the vote settings? I can help refine texts when back :) 
- Longer-term: Vote delegation might need a re-think to be more what users really need, but needs some more research.

**Comment by kevincrepin** [comment]
I would say here also let's just have better copy to explain it, then we don't need a help button.

![Screenshot 2024-02-13 at 18 26 31](https://github.com/citizenos/citizenos-fe/assets/26792281/8955c748-5395-49e6-82ca-98dfe2474491)

**Comment by kevincrepin** [comment]
I'm curious to understand what did they think it means? Just wondering how to better communicate it... Might be that this term is not commonly used in the context? @BeccaMelhuish is there a term in English that's used when you allow someone else to vote in your name?

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK yes, have added explanation above now :) 

I think some guidance will be needed for the participants side too, so they know what happens when they delegate their vote, I added some suggested text in [this issue](https://github.com/citizenos/citizenos-fe/issues/199#issuecomment-1936177481) the other day :)

**Comment by BeccaMelhuish** [comment]
@kevincrepin I've been trying to work out some copy for here, but feel like it might need a tooltip as it's quite complex. (Not sure the UX of a tooltip in such a place though, as it's already a tick box button?) 

This is as short as I could get it: 

_Allow users to pass on their voting right. The delegee to won't be informed, but their vote will be counted twice. The delegator won't see how the delegee voted._

**Comment by kevincrepin** [comment]
For me it's not necessary to have a tooltip for this. We have the option to add copy so let's just change it with your latest version :) 

![Screenshot 2024-02-27 at 15 06 41](https://github.com/citizenos/citizenos-fe/assets/26792281/466a3ee8-6463-4cbd-88c8-b3dfbe6cb881)

**Comment by BeccaMelhuish** [comment]
Ah right, yes that looks totally fine like that! Thank you :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the text
