### ISSUE TITLE
Group: Users very confused by group rights

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#862]
**Round 2 insights:** 

Users very confused by group rights in topic create flow (when adding a  group to topic) and in relation to topic rights (how the two interrelate). 

I can add more insights at a later date on how this played out in the test.

**Suggestions:** 

- Short-term: @kevincrepin Can we have a help button next to it in the topic create flow, to explain what giving a group rights for the topic means? I can help refine texts when back :)
- Longer-term: I think group rights needs a re-think to be more understandable - users are quite baffled by it, it causes access issues, and I myself was confused by what was happening in the test and reading the HC text about it (which I wrote!). Hopefully we can simplify it somehow, but I will add more insights as above when there's time.

**Comment by kevincrepin** [comment]
I think yes we can add the "tooltip" here – and in other places where it seems important. That's a pattern we can apply where we see fit.

![Screenshot 2024-02-13 at 18 11 42](https://github.com/citizenos/citizenos-fe/assets/26792281/53d4913c-7ef4-4ccd-a351-b0a433a8c588)

**Comment by BeccaMelhuish** [comment]
OK that looks good! 

Trying to work out what to write here is a bit tricky as it's quite complex, and we won't initially have a HC to link to for more detail. (So @ilmartyrk when implementing please leave off the link to the HC). 

If I'm not mistaken, it's the 'group topic access rights' part of [this HC text](https://citizenos.com/help/groups/understanding-group-user-rights) that is relevant to here.

To keep it simple, we could just say: 

"This will give all members of the group the selected level of permissions to the topic, unless you individually assign them a different permissions level from the topic's 'manage participants' section."

**Comment by BeccaMelhuish** [comment]
@ilmartyrk would be great to have it by Thurs noon for the next admin (mobile) UX test if poss :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the tooltip

**Comment by BeccaMelhuish** [comment]
@ilmartyrk needs to be added to group creation flow as well as topic creation flow :) 
(And anywhere else where there is an option to change this permission - not sure if there are others?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d867b63f-2607-41df-8900-d1a3deb16594)

**Comment by ssin1901** [comment]
@ilmartyrk tooltip implemented in Add Group to Topic (screenshot1) but not the other way around (screenshot2). 
<img width="1223" alt="Screenshot 2024-03-04 at 12 48 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/da52f3ad-c524-49e7-969d-bbe8841194c1">
<img width="1224" alt="Screenshot 2024-03-04 at 12 49 25" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0d2ce714-9b64-4f4f-8b9b-a69736d84773">

**Comment by BeccaMelhuish** [comment]
@ilmartyrk, moving it back to in progress :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 added the missing tooltip

**Comment by BeccaMelhuish** [comment]
@ilmartyrk this one still missing though :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2f60b61f-2700-4b4c-ac2a-935970dd1b2b)
