### ISSUE TITLE
Voting: Vote results folder is confusing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#863]
**Round 2 insights:** 

Users are overwhelmed by all the different files and confusing headings in the voting results folder. One clearly said that all they need is the CSV, and all have shown that this is all they are looking for when it is soft voting (and eID signatures when it is hard). Others said the names are confusing and there are too many options of files to open.

**Suggestions:** 

- Short-term: as a quick fix for now, can we just have the CSV file and the graph in the main folder, then a sub-folder that says 'Tracking data' with all the rest tidied away into? As I understand from @ilmartyrk that' what it's for, but people rarely actually need/want it.   
- Longer-term: Hopefully we can review this a bit more thoroughly, and probably also make the graph as PDF as I understand that's what it was meant to be (not html) to be more usable.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk what do you think about the folder idea for the short-term solution - is that a quick-fix from your side?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish, needs some investigation, shouldn't be too difficult, but I cannot promise it in Phase I

**Comment by ilmartyrk** [comment]
We need to setup clear structure for the container so it is legally clear how and on what people have voted on / signed on

**Comment by BeccaMelhuish** [comment]
I have made 2 separate issues, and will close this one now :)
