### ISSUE TITLE
Groups: Users confuse topics with categories in the group setup

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#864]
**Round 1 and 2 insights:** 

A couple of times users have seemed to confuse this with the 'Categories' in topics. 

E.g. here one user typed 'waste' then clicked continue (and carried on):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2f29e4e4-c4c6-4bce-9a37-eb8eb2935b0f)
 
**Suggestions:** 

Probably just a wording change? 
Or an error message if you type something in the field and click continue without having added anything?

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk I'm thinking here we could change the heading to:

"Add existing topics for members to access" 

This would also help with one other insight, which is that some users try typing the name of topics that don't actually exist yet, I guess assuming they could create them here somehow.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk if @kevincrepin is OK with the suggested text, would be great to have it by Thurs noon for the next admin (mobile) UX test if poss :)

**Comment by kevincrepin** [comment]
OK for me!

**Comment by ilmartyrk** [comment]
@BeccaMelhuish Changed the heading
