### ISSUE TITLE
REGISTRATION: Error message is greyed out

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#869]
**What is the problem?**
On Google Chrome latest version when a user tries to register with an email address that is already in use, they get this error message that is greyed out (screenshot)

<img width="1438" alt="Screenshot 2024-02-20 at 00 32 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b99f2172-63f7-4c10-a61b-5b6c8e6c3b38">

**Why is this a problem?**
Not easy for the user to understand the error

**Possible solution.**
Error message should not be greyed out

**Comment by ilmartyrk** [comment]
@ssin1901 this is already fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot)
<img width="1226" alt="Screenshot 2024-03-04 at 11 18 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f4dc842f-d026-4c3b-b3ae-62cb97352059">
