### ISSUE TITLE
LOGIN: Logged out user can add input to Argument but then gets a 404 error

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#872]
**What is the problem?**
A user who is not logged in can access the Add Argument feature and add also input. However, upon clicking the button they get a 404 error (see screenshot).

<img width="1298" alt="Screenshot 2024-02-20 at 18 55 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/431ab3a2-f4f3-4bf8-a298-93e2f766ba55">

**Why is this a problem?**
Logged out users are likely unaware that they need to login to add arguments. This really confuses them.

**Possible solution.**
A logged out user should be prompted to login when they click Add Argument and should never see the option to add input unless they are logged in.

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
Closing the issue (see screenshot)

<img width="1293" alt="Screenshot 2024-02-22 at 20 39 38" src="https://github.com/citizenos/citizenos-fe/assets/72747107/35b7b276-d7b4-4fd4-b053-435339aaa621">
