### ISSUE TITLE
TOPIC: Preview shows two Save Changes buttons

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#873]
**What is the problem?**
When a user edits a topic and comes to the Preview section, there are two Save Changes buttons. The button on the left doesn't do anything (see screenshot)

<img width="1241" alt="Screenshot 2024-02-21 at 00 19 52" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9db7a2e5-4c43-4b90-90e1-7b998c438478">

**Why is this a problem?**
Confusing to the user

**Possible solution.**
Redundant button on the left should not be displayed.

**Comment by ilmartyrk** [comment]
@ssin1901 fixed

**Comment by ssin1901** [comment]
Fixed (see screenshot)

<img width="1440" alt="Screenshot 2024-02-22 at 20 37 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/9a859429-d9fa-41e6-946d-8d313b67adc4">
