### ISSUE TITLE
AF: This group activity shows activity from unrelated topics 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#875]
**What is the problem?**
User is viewing Activity Feed for a particular group but when they click "Activity related to my topics", they are updated about topic activities that have nothing to do with the group.

NB! In this scenario, a fresh topic "Topic not part of a group" was created AND not added to this group or any other, and the user was still able to view it under "This groups activity" (see screenshot).

<img width="1287" alt="Screenshot 2024-02-21 at 14 54 06" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1188c324-fb34-4adb-810a-1811e1560461">

**Why is this a problem?**
Very confusing to the user

**Possible solution.**
If the title says "This group's activity" then the "Activity related to my topics" should only show activity related to topics added to that particular group.

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the issue that also decided to removed filters for topic and group activities as the API doesn't support them properly,

**Comment by ssin1901** [comment]
Could not replicate, closing this issue
