### ISSUE TITLE
REGISTRATION: Verify my account email option does not direct the user to Login 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#877]
**What is the problem?**
When a user clicks Verify my account from their email, they are not directed to the Login page but to the logged out view (see screenshot1 and screenshot2).

<img width="593" alt="Screenshot 2024-02-21 at 15 12 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7573a265-c39f-45eb-852c-ff7037476cb9">

<img width="1287" alt="Screenshot 2024-02-21 at 15 12 35" src="https://github.com/citizenos/citizenos-fe/assets/72747107/05dd61ab-e24d-4a9d-99c8-a045233297e4">

**Why is this a problem?**
User is unaware that verification has been successful and does not know what action to take.

**Possible solution.**
User should be directed to the Login page with a "account has been successfully verified" message.

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix, but it will only work with new registrations, so any old links already in the mailbox are as they are

**Comment by ssin1901** [comment]
Fixed (see screenshot)
<img width="1294" alt="Screenshot 2024-03-06 at 16 09 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/de6f3dfb-b289-4ac1-8c48-5c9a47cd6de5">
