### ISSUE TITLE
MOBILE: Internal Server Error after removing attachment

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#878]
**What is the problem?**
Tested on Moto e7 (screen size:6.5 inches) running Android 10

On an Android device, after a user has removed an attachment (jpeg) they get this error (see screenshot)

![IMG_0056](https://github.com/citizenos/citizenos-fe/assets/72747107/0706c26d-b039-46a6-8b65-b48d851c7e58)

**Why is this a problem?**
Confusing to the user

**Possible solution.**
User should not receive an internal server error after performing this action

**Comment by ilmartyrk** [comment]
@ssin1901 fixed

**Comment by ssin1901** [comment]
Tested and closing.
