### ISSUE TITLE
VOTING: Selecting options did not work

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#881]
**What is the problem?**
_On latest version of Google Chrome_, the user could not select options until the page was refreshed (see screen recording).

https://github.com/citizenos/citizenos-fe/assets/72747107/43b4bf82-c132-47f9-8460-921337fba2a7

**Why is this a problem?**
Initially appears as if the user cannot select an option. 

**Possible solution.**
Voting options should be selectable

**Comment by ilmartyrk** [comment]
@ssin1901 I don't see any refreshing and looks like it is working

**Comment by ssin1901** [comment]
@ilmartyrk my apologies, I think I somehow managed to start the recording after I had refreshed. I am closing this issue till I can get a hold of another recording of the same issue. Very sorry.
