### ISSUE TITLE
TOPIC: Vote description error would not close 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#883]
**What is the problem?**
At one point, when the user was in Topic Preview on _Mac OS Safari latest version_, two error messages appeared, and the user could not close them (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/02c3216a-99a4-4a57-ae26-5b20a69d8b8a
 
**Why is this a problem?**
User had to exit the page to resolve the error (hence high priority label)

**Possible solution.**
Error message should not be appearing at all, since it was agreed that user will not be able to navigate to the next section without correctly filling in all the fields.

**Comment by ilmartyrk** [comment]
@ssin1901 This needs more information, how were you creating the voting, directly from create menu or sent discussion topic to voting, also there seems to be some background loading going on see how the attachments item is twitching in the menu

**Comment by ilmartyrk** [comment]
@ssin1901 if you can replicate it then let me know if not it might be related to updating of code during the testing and I would rather close it

**Comment by ssin1901** [comment]
@ilmartyrk I will retest this. It might be caused by the internet but the new flow doesn't have the error messages at that stage. Therefore, I need to retest and see if those error messages are still appearing in the wrong place.

**Comment by ssin1901** [comment]
@ilmartyrk we won't fix this in this stage. Can we move it to Phase 2?

**Comment by ssin1901** [comment]
@ilmartyrk let's move this out of the testing column

**Comment by ssin1901** [comment]
Could not replicate and closing
