### ISSUE TITLE
MOBILE: In Edit Topic, Save Changes does not work 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#886]
**What is the problem?**
_Tested with iPhone 6s Plus (5.5-inch screen, 414px × 736px viewport) on iOS 15.8.1_

_Tested with Simulator for iPhone 14 Plus - iOS (6.7-inch screen, 428px × 926px viewport) on iOS 16.2_

When a user goes to Edit Topic and comes to Preview, clicking Save Changes doesn't do anything (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/148bc081-bf0d-4b7a-96f4-5ee8edee14c5

**Why is this a problem?**
User cannot save their edits

**Possible solution.**
Save changes should work in iOS

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
Fixed (screenshot1, screenshot2, screenshot3)

![Simulator Screen Shot - iPhone 14 Plus - 2024-02-29 at 11 46 09](https://github.com/citizenos/citizenos-fe/assets/72747107/e0374464-5577-4891-9c74-d535ecb54af5)
![Simulator Screen Shot - iPhone 14 Plus - 2024-02-29 at 11 47 35](https://github.com/citizenos/citizenos-fe/assets/72747107/3660518b-fb0b-46e9-b5cd-97826757f4ec)
![Simulator Screen Shot - iPhone 14 Plus - 2024-02-29 at 11 46 50](https://github.com/citizenos/citizenos-fe/assets/72747107/993d7fbd-d6d5-405c-b357-9452a48a46f6)
