### ISSUE TITLE
Discussion: wrong argument appeared

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#887]
I (under a dummy name) just posted a totally different argument to this, but what appeared when I clicked post argument was a dummy argument I had written in a totally separate (not in same group) topic a few minutes before: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ce8042ac-895c-401e-948a-75954055f71b)

Seems a high priority one to me, especially as can't delete an argument once posted..

**Comment by BeccaMelhuish** [comment]
Ah, though when I view it as admin of the topic the right argument is showing: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/217ea428-de31-4381-9850-57373fea296a)

Logged back into 'Megan' account and it is now showing there too, so the bug was only temporary, but confusing:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ed9c08b2-1b21-4049-9360-063171cb12f7)

Still a priority though I think as will be testing participants posting in discussions very soon - from this weekend hopefully. Adding 'pre UX test' tag :)

**Comment by BeccaMelhuish** [comment]
It just happened again here - I posted a dummy argument about housing, and what appeared was the one about sustainability I'd just posted in another topic: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c35aa32c-23ac-4ffe-a8b8-8d9f91b34e25)

This time I thought to click refresh, and the right one appeared: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cbeb1c32-1901-4f2e-bebc-d39a424dabc8)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now

**Comment by BeccaMelhuish** [comment]
I had something similar happen just now - I added this reply in one topic:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b916f373-63ae-428d-aea1-09253a99c1bb)

Clicked post reply and was instantly transported to the discussion section of a different topic! (Within the same group, which I had just add a reply to as well).

**Comment by ssin1901** [comment]
Could not replicate, closing now
