### ISSUE TITLE
Voting: edited vote option not appearing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#889]
In vote topic creation flow (before having published), first I had included 'Neutral' as an option. Seeing it in preview I went back to the vote settings tab and changed it to 'I don't mind': 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3a945cb4-24a0-4d42-a7bb-7daee1165101)

I click continue and it's not appearing in preview. Also not in the published vote. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7ce8772a-2652-43ce-a36b-70b5080d18c6)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish managed to replicate, but it was quite random. But posted a fix that should make it more stable

**Comment by ssin1901** [comment]
Fixed and closing (screenshot1, screenshot2)
<img width="1380" alt="Screenshot 2024-03-27 at 17 11 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/70aedc79-7359-4cd3-8426-1d2c3d06
<img width="1374" alt="Screenshot 2024-03-27 at 17 11 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3e6b9698-72de-4cc2-9633-8af3b44eb22b">
8557">
