### ISSUE TITLE
Voting: number of votes and arguments not showing

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#891]
Blank space where it should say 1 vote, and 0 where it should say 1 argument: 
(Participant rights if that changes anything). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/69498d41-7618-4f29-86d2-7b63a2c3652a)

**Comment by ssin1901** [comment]
@ilmartyrk this is making the user tests really difficult. Already came up twice and the users are very confused when they come to the group.

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish it took some time to understand what is going on as it looked OK in public and private groups logged in an logged out, finally found that it happens under group view. Will try to post a fix as soon as possible

**Comment by ssin1901** [comment]
Currently works (see screenshot). Please make a new issue in case it doesn't work.
<img width="1281" alt="Screenshot 2024-03-13 at 17 16 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c1e0f9d6-e4b9-4349-b7cb-a25920d8af60">

**Comment by BeccaMelhuish** [comment]
@ssin1901 I think the problem was in group view though? 

@ilmartyrk For me it looks like this currently, in a group for which I'm admin - votes missing on voting topic: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/55bb2cb1-97f7-4d34-847f-520df6a8af1c)

**Comment by BeccaMelhuish** [comment]
In my topics it is fine though:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5df5560b-7b70-4a5a-99e5-b43935d103f1)

**Comment by ssin1901** [comment]
@BeccaMelhuish I think it is working in Groups as well (see screenshots). Awaiting for your input before I close the issue again.
<img width="1236" alt="Screenshot 2024-03-13 at 23 08 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/60628b5a-53b0-4bb3-b00d-bc957159d6a6">

**Comment by BeccaMelhuish** [comment]
@ssin1901 this bit is missing the votes though :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c43f60a9-cc4c-480c-8ff9-403cd1531df3)

**Comment by ssin1901** [comment]
@BeccaMelhuish my apologies. This one goes back to high priority.

**Comment by ssin1901** [comment]
Votes are now present and closing the issue (screenshot). Moving this to done.
<img width="1375" alt="Screenshot 2024-03-27 at 17 46 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b36234d6-46fd-41d7-b12d-110579e07c18">
