### ISSUE TITLE
Groups: URL rights wording mismatch

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#892]
Both should say member: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b5f8c780-d535-4a31-b090-91bcf861c8e9)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed

**Comment by ssin1901** [comment]
Closing as it is fixed (see screenshot)
<img width="1438" alt="Screenshot 2024-02-26 at 12 02 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/546e2318-4d8c-427d-93c5-f83e84d5cc3d">
