### ISSUE TITLE
Groups: If follow the join link after joining, it asks you to join again

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#893]
Even if you have already joined, you get this pop-up. It should just take you straight to the group. (Let me know if more explanation needed why, can explain the use cases, but to save time only will if needed :)). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/11d84cdc-a4b3-414f-bc28-33b6352f74ba)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Just tested and I got the same pop-up I'm afraid! (For my own group). I was logged out when I followed the link. Logged in and got this pop-up. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ecfd2e81-2799-4bd3-ac41-a8a31090f003)

**Comment by ssin1901** [comment]
@BeccaMelhuish I didn't get this when I tested the topic (see screen recording). After logging in, went straight to the group (see screen recording)


https://github.com/citizenos/citizenos-fe/assets/72747107/dd4de857-6b2a-4cd4-87fa-497e430e2d79

**Comment by ssin1901** [comment]
Fixed and closing
