### ISSUE TITLE
Topic: Interrupt process pop-up after saving changes

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#895]
When I edit a topic, save changes then click the X on the bar at the bottom, I get this saying any progress won't be saved. Shouldn't appear. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ab8f44ba-0fc6-4445-92fa-03a9df6cbb32)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I removed this dialog from topic views as we use autosave for all the fields. And it would be quite difficult to implement this solution you proposed

**Comment by BeccaMelhuish** [comment]
Ah OK yes if we autosave to a draft then no need for it :)

**Comment by BeccaMelhuish** [comment]
Ah, actually no - we do need it. As when you go into edit topic, you need to have the option to close without saving, but also need to be warned that's what's happening. 

Now, when you are here, you have a save changes button that saves it, but also an X button that also saves it. There is now no way to change your mind about your edits and not save them (which is needed). 

But this is all very connected to [this issue](https://github.com/citizenos/citizenos-fe/issues/931), so hopefully can be considered by @kevincrepin as part of that :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/59f4cfd2-7be2-4f9e-92ec-7386d50844f3)

**Comment by BeccaMelhuish** [comment]
The flow has been confirmed by Kevin in [this issue](https://github.com/citizenos/citizenos-fe/issues/931) now, so once fixed there this can also be closed :)

**Comment by ssin1901** [comment]
Seems to be working and closing
