### ISSUE TITLE
IS: User added as a co-creator wasn't given Editor permission 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#896]
**What is the problem?**
On Google Chrome, a user who was added as a co-creator received an email that indicated that they may "request co-creator rights" (screenshot1)
<img width="1278" alt="Screenshot 2024-02-23 at 15 30 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e459261f-ebc5-4da9-8652-0838d1933d17">

Further, they did not receive the editing rights (screenshot2)
<img width="1291" alt="Screenshot 2024-02-23 at 15 30 30" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8ea8d51c-fabb-469e-85e0-3b054606593b">

**Why is this a problem?**
User cannot be edited as co-editor

**Possible solution.**
Co-editor should clearly be informed via email that they have editing rights and when they go to the topic, they should be able to edit it.

**Comment by ilmartyrk** [comment]
@ssin1901 removed this item from the dialog

**Comment by ssin1901** [comment]
Fixed (screenshot1, screenshot2) and now closing
<img width="1288" alt="Screenshot 2024-03-11 at 11 33 40" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1566004a-5fb8-42fd-8434-643317adad2e">
<img width="1296" alt="Screenshot 2024-03-11 at 11 34 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/99291c4c-51d8-40ab-ab15-1e3a8169d9ed">
