### ISSUE TITLE
VOTING: Voting deadline has a different time in email reminder

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#899]
**What is the problem?**
The voting deadline in the reminder email is different (screenshot1) from the one in the displayed in the voting interface (screenshot2)

<img width="1439" alt="Screenshot 2024-02-26 at 12 33 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f120aac1-497c-4154-8e82-67148789d4fe">

<img width="1439" alt="Screenshot 2024-02-26 at 12 33 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8c822621-5d2d-4013-9d5a-d381651af961">

**Why is this a problem?**
Confusing to the users

**Possible solution.**
Deadlines should match. Both deadlines in this case were created on the same computer.

**Comment by ilmartyrk** [comment]
@ssin1901 this is really difficult one to solve as the dates in the database are converted into our server local time and we don't know and cannot track the location of users who the reminder gets sent to. My only suggestion is to add that the time is GMT try to solve this issue in the later phase
