### ISSUE TITLE
BUG: Calendar should have a correct date/week format, based on browser settings

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#90]
Original in [fe-old](https://github.com/citizenos/citizenos-fe-old/issues/343)

**What is the problem?**
When setting a voting deadline, the calendar doesn't align with my locale - week starts with Sunday instead of Monday and the date format is incorrect (mm/dd/yyyy instead of dd/mm/yyyy). 
Date/week settings should align with user browser's locale settings.

<img width="569" alt="Screenshot 2019-11-20 at 10 38 16" src="https://user-images.githubusercontent.com/34126353/69222593-75e7c900-0b82-11ea-84c5-6b6e8e1220f3.png">

**Why is this a problem?**
It causes confusion and may cause choosing an incorrect date for the topic, as well as cause communication problems (it looks like Thursday is chosen, but it's actually Wednesday).

**Possible solution.**
Please make sure the calendar is synced with browser locale settings.

**Comment by oksks** [comment]
Seems OK. Thanks!

<img width="790" alt="Screenshot 2023-11-24 at 19 12 32" src="https://github.com/citizenos/citizenos-fe/assets/34126353/2f70373a-0977-4519-8ca1-0e6ee34febff">
