### ISSUE TITLE
GOOGLE LOGIN: error message

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#901]
**What is the problem?**
A user clicked on Login -> Google and then selected their email from the list. They then received this error message (see screenshot).

<img width="1296" alt="Screenshot 2024-02-26 at 21 43 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/53019523-be2e-4c28-8dc8-ac9ce3ca1f62">

@ilmartyrk this only happened with one email account (details in Slack)

**Why is this a problem?**
User could not login with Google

**Possible solution.**
User should be able to login with Google

**Comment by ilmartyrk** [comment]
@ssin1901 difficult to solve and also probably quite rare to happen, pushing it to Phase II
