### ISSUE TITLE
MODERATION: Errors in the moderator view

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#902]
**What is the problem?**
1. When a moderate clicks on Review topic from the email (screenshot1)
<img width="642" alt="Screenshot 2024-02-26 at 22 26 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c4271a31-859c-40f5-9946-e036a628c775">

2. They are presented with options (screenshot2) 
<img width="1387" alt="Screenshot 2024-02-26 at 21 59 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/07f0f85f-3b09-495f-9bb9-ec6a1a1ec29c">

3. Several of the options do not work as expected
3.1 View details does not show details (see screenshot3)

<img width="1379" alt="Screenshot 2024-02-26 at 22 00 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ed95b156-9ae2-4386-8552-d63ced2f525f">

3.2 Clicking on Yes, Mark as Resolved  (screenshot4) leads to a redirect to a Not Found page (screenshot5)

<img width="1391" alt="Screenshot 2024-02-26 at 22 00 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e529c23d-49dc-4b6d-865f-51ffb5a82df2">

<img width="1384" alt="Screenshot 2024-02-26 at 22 01 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6052294a-b91e-4319-a0c3-505e4faadd4c">

NB! Moderator is still able to review argument and the concerned parties are notified via email.
 
**Why is this a problem?**
1. Moderator cannot view details
2. Moderator does not know if their actions have been successful because the application redirects them to a Not Found page 

**Possible solution.**
1. Moderator should be able to see details
2. Moderator should be notified that their review has been sent to the concern parties. @BeccaMelhuish need your help here

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the issues

**Comment by ssin1901** [comment]
@ilmartyrk it is removed for now (see screenshot) is a fix planned within the next 1-2 days or can I remove the high priority label.
<img width="1287" alt="Screenshot 2024-03-13 at 17 05 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7d7b6533-9098-4ae4-a4fd-59d29e8d6e84">

**Comment by ssin1901** [comment]
@ilmartyrk since the view details can be retrieved from emails and doesn't affect the users, I am removing the high priority label

**Comment by BeccaMelhuish** [comment]
At a (very) quick glance I think this may be related to some of the other moderation issues I made issues about previously, but as topic reporting only comes to us (internal) it was decided to be fixed in Phase II with the big moderation review :)

**Comment by ssin1901** [comment]
Issues fixed and closing this issue.
