### ISSUE TITLE
MODERATION: Incorrect text

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#904]
**What is the problem?**
In the topic author/admin view for Moderation, the topic under review has text that is applicable to the Moderator not the topic admin (see screenshot)

<img width="1424" alt="Screenshot 2024-02-28 at 20 36 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/84bf8bc7-58d4-4aac-a3b3-4963aeec5780">

**Why is this a problem?**
Topic author is not the Moderator and this text could cause confusion across the whole flow 

**Possible solution.**
Text should be changed to "Since you're an admin/author of this topic". @ilmartyrk marked as high priority as moderation is currently being tested.

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix
