### ISSUE TITLE
Tour: Wrong topic tour text on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#906]
It's like this on mobile: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4a474f40-0b2f-4d74-b22d-7cd27c7c6d92)

But should be same as it is on desktop:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d1db7cba-e970-4372-9e16-dc016d616f37)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish nope, the designs were changed. There is this dialog for mobile and also help-center includes the start tour for topics
