### ISSUE TITLE
Topic: Insufficient permissions error 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#908]
User got this at some point during the creation of a topic in a test. It was just before her internet cut out, so may be connection related? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/78ea4a93-d13b-4536-82d9-14f24eca74b0)

**Comment by ssin1901** [comment]
@ilmartyrk did you figure out what was causing this issue? I am unable to replicate it.

**Comment by ssin1901** [comment]
@BeccaMelhuish closing the issue because this issue occurs on both live and test. Similar issues have been created and the issue is being investigated.
