### ISSUE TITLE
Topic: No voting/follow-up texts talk to all users as if they are admin

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#909]
@kevincrepin @ilmartyrk a UX bug I just noticed: the 'there is no voting yet' text and the equivalent for follow-up talk to users regardless of whether the person looking at them is admin or participant - we need different texts depending on who is viewing them (or one text that works for both), these are misleading for participants currently :)  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/da398031-3d95-4f80-8ce3-dbae413b46ed)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3684c910-b9d5-4cc0-b3e3-813ee438ad75)

**Comment by BeccaMelhuish** [comment]
@kevincrepin @ilmartyrk Here are my proposals for new texts that should work for both admins and participants :) 

**How voting works**
When a voting phase is added to a topic, participants can share their views by casting a vote. The voting system can be set up in different ways, depending on the needs of the topic. 

After voting has finished, the results can be seen by everyone, and the decision taken forward.

**How follow-up works**
Follow-up is the last phase of a topic. After a decision has been made, topic admins can post updates for participants about the actions taken.

Updates should show what's happened as a result of the decision, with details of any progress or outcomes.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the texts
