### ISSUE TITLE
TOPIC: Sharing link doesn't work for a Private Topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#910]
**What is the problem?**
User Sara generated a link for user Dave (screenshot1) _who was using Google Chrome on Mac OS_ to a private topic and got this error (screenrecording1)
<img width="1229" alt="Screenshot 2024-03-01 at 13 42 52" src="https://github.com/citizenos/citizenos-fe/assets/72747107/75c5e825-7d8e-47b2-a130-f461d77de3c7">

https://github.com/citizenos/citizenos-fe/assets/72747107/605ee47d-c279-464c-92aa-57d6577ce7f2

**Why is this a problem?**
Share link is redundant for Private Topic

**Possible solution.**
Share link should work

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
@ilmartyrk now working. Closing issue.
