### ISSUE TITLE
Login: No account, sign up link dead

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#911]
User on Android phone, Firefox, couldn't click this link - nothing happened. Told her to refresh and it did take her to registration page: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/96b5e384-5554-42eb-9c1d-f1771c930173)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now

**Comment by ssin1901** [comment]
Working now and closing (see screenshot)
<img width="1288" alt="Screenshot 2024-03-13 at 17 06 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/46487a77-7b9b-456f-b8ec-2e0e7dca6f4a">
