### ISSUE TITLE
Topics: User has trouble getting 'youth' category to register

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#912]
User on mobile (android, firefox), taps 'youth' several times, drop-down closes but it doesn't add, in the end it does add the category. The others worked fine, maybe to do with it being at the end? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ab55d6a9-839a-4814-8322-0fb83ebd8814)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish looks really user specific issue, tested on mobile and selection works. closing the issue
