### ISSUE TITLE
Misc: Notifications blend in on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#916]
@kevincrepin I noticed in mobile user tests that the notifications really blend in on mobile if they are over the same coloured background like this, I wonder if we can adjust so they stand out a bit more? Hasn't caused any issues yet though, will keep an eye on it. But flagging in case you think already worth adjusting :)   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1b931d3e-5d2c-45c9-9171-3b4d51ee6967)

**Comment by kevincrepin** [comment]
Hmm yeah, I think we can make the shadow a bit more pronounced:
![Screenshot 2024-03-06 at 10 35 16](https://github.com/citizenos/citizenos-fe/assets/26792281/93ed890f-5642-4893-ab62-399e219136bc)

@ilmartyrk updated shadow style can be found here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=47%3A10352&mode=design&t=PPmgEbzXtlzgZoGb-1

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the shadow
