### ISSUE TITLE
Groups: Bug / UX bug when re-adding topic to a group

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#917]
@ilmartyrk @kevincrepin This is partly bug, partly UX issue. 

**Problems:** 

_BUG:_ 
In a user test, the user got this after adding her topic to a group: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a3a4bf11-ce88-4b97-8582-25f5763f2f15)

However I think the reason may be (correct me if wrong Ilmar?) that she was adding a topic to a group that was already in the group (this was the case in the test, she wasn't sure if it was added, so she tried again), and the system does have an error message for that, or gave her this one instead? 

_UX problem related to it:_ 
When she went to this 'Add topic to a group' pop-up, there was no indication that the topic had already been added to the group (but it had been): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/337fc743-d9b1-4466-a4d6-e9adf1558126)

**Suggestions:** 

Should the error message rather than 'Insufficient permissions' be 'This topic was already added to this group'. And rather than showing up after she has added it, should it show in the pop-up window? 

Could the fact that the group has already been added should be apparent somehow in the pop-up? 

E.g. under the dropdown:

Groups already added: 
Salto Pi

Or in the dropdown itself the 'Salto pi' would be greyed out with 'Already added'?

**Comment by kevincrepin** [comment]
It would be great if it would be visible in the dropdown/search results of course. I guess it's a question to @ilmartyrk if it's build like this that that info is already known or does it need to do a separate request (after trying to add)?

If we can show it in the dropdown/results:
![Property 1=Variant3](https://github.com/citizenos/citizenos-fe/assets/26792281/88344164-dee3-415a-aab0-b5302ba48e1b)

If this check happens only after adding then indeed a notification needs to be shown.

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish updated the view

**Comment by BeccaMelhuish** [comment]
Wonderful! Just checked and working well :)
