### ISSUE TITLE
Group: wrong kind of group rights in 'Add topics to group'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#918]
In a test, when user tried to add a topic to a group in the topic create/edit flow, she got the 'participant, editor, admin' options. But when she tried to add it in the 'Add topic to a group' window (from the 'Manage' menu), she gets these ones:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c3113214-5acd-4fa3-9d85-9c37258b0856)

I assume it should be 'participant, editor, admin', and should have the same tooltip as we have in topic create/edit flow now:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e8457fa5-3cf9-4d6f-b673-2a3d76c14257)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish could not replicate

**Comment by BeccaMelhuish** [comment]
@ilmartyrk just tried it myself and got the same thing, here is a clearer screenshot of the context below :) 

Should be 'participant, editor, admin' I believe? As in this case it's the topic access rights for the group, not the rights to administrate (or not) the group? 

And here it will also need the same tooltip as we have in the 'Add topic to group' part of the create/edit topic flow as well, marked in yellow where it should be :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0986b784-f6b4-46f2-9823-e4bfa626ecf6)
