### ISSUE TITLE
Topic: Topic text harsh cut-off line on mobile 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#921]
@kevincrepin @ilmartyrk Am wondering if we can do something here, so there isn't this nasty line on mobile: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4235d972-5fdc-4d6d-8dab-0d6cc0270f36)

**Comment by ilmartyrk** [comment]
#Triage 101 won't fix
