### ISSUE TITLE
Topic: groups didn't expand when tapped

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#922]
User on mobile tapped on groups and it flashes like it registered that she has clicked it, but didn't expand (topic is part of a group). Not sure if a bug or just the way she tapped, but flagging in case: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/6f1da775-8946-4fed-bc8c-429921376c31)

**Comment by loorm** [comment]
@BeccaMelhuish In the future, it's easier to replicate, if you specify mobile platform (Android vs Apple) and device. There have been some specific iPhone SE issues.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish might have been some API response error etc. Could not replicate, closing it
