### ISSUE TITLE
Discussion: Should deleted arguments still be counted in the discussion stats? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#923]
User added 1 argument to an empty topic, deleted it, saw that it was still counted in the stats. Should it be? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/75748726-cae1-4f0a-adfd-24531dbffa52)

**Comment by ilmartyrk** [comment]
Triage 101, will still count these arguments, otherwise it might also be confusing
