### ISSUE TITLE
Discussion: Re-hide a hidden argument you have viewed? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#924]
@ilmartyrk @kevincrepin currently once you have viewed a hidden argument, there is no way to hide it again - should there be? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c5d2d494-a559-44a9-a776-1c7c32877296)

**Comment by ilmartyrk** [comment]
Triage 101, User has made conscious action to view the argument so let it be as it is
