### ISSUE TITLE
Topic: Buggy etherpad icons for version history etc

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#925]
These icons at the bottom of the topic text proved to be quite buggy in a test, when clicked. 

@ssin1901 I wonder if they are part of QA tests, as they're not actually part of our designed functionality, they just come along with Etherpad? 

And @ilmartyrk @kevincrepin, I wonder if we don't just hide them for now? Then re-visit in a later phase when we have time to de-bug them and maybe consider the UX of them? We don't really have the co-creation features yet anyway, and these are for co-creation I believe..  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/682f1636-1789-4051-aa84-56e0025f45b4)

If you do decide to keep them in and fix the bugs though, I can share what happened in the test - let me know :)

**Comment by BeccaMelhuish** [comment]
Update: In the test today the user also clicked them (seems more common that they will notice them on mobile - they are more apparent), and it all worked pretty smoothly. Except that nothing seemed to happen when she clicked the 'eye' one, but the text box has so much extra space under the text she had entered it wasn't possible to see what was happening to the text:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8b6a61e1-8a0d-4beb-9bcb-2b5689da1958)

Test today was on Android and Chrome. Previous test I'm just double-checking will let know when I know.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I see this is in Phase II now, but what do you think about hiding them completely for phase I, and only making them visible when bug-free and UX reviewed? (As 2 out of 3 admin users on mobile clicked them, so they're quite noticeable/attention-catching it seems).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish issue is actually fixed, the history button is the only one left.

**Comment by BeccaMelhuish** [comment]
Ah OK nice :) 

It's still a little dodgy I find, when I look at it on Chrome, but hopefully @ssin1901 can do more thorough testing at some point when there's time!

**Comment by ssin1901** [comment]
Fixed (see screenshot)
<img width="1102" alt="Screenshot 2024-03-11 at 18 32 10" src="https://github.com/citizenos/citizenos-fe/assets/72747107/96f085d2-f847-492d-bd4e-b343ef75ee25">
