### ISSUE TITLE
Topic: Users can continue with mandatory fields not complete

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#926]
In topic creation flow, it is currently possible to create a topic with no topic text, but this is a mandatory field. Should it be possible? 

(Not sure if this is the case for all mandatory fields, didn't test.)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it is difficult to solve as topic text sits inside Etherpad, let's leave it as is and come back later
