### ISSUE TITLE
Votes: Should it still say how many votes are needed? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#928]
As we no longer have 'close when all votes are in' should it still say how many votes 'needed'? 

@kevincrepin I think should just be how many votes are counted now, is that correct? 
(It doesn't really make much sense anyway in topics where the number of participants keeps changing all the time - e.g. public ones or ones shared via link). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e15264b7-6b17-44bd-8a1b-9f6fcd49cd52)

(Though Ilmar if we're keeping it, I believe in this case the number was incorrect and should have been 0 needed, though would need to double check).

**Comment by ilmartyrk** [comment]
Triage 101 will hide this line for now

**Comment by ssin1901** [comment]
@ilmartyrk seems to be fixed. Closing now.

<img width="1292" alt="Screenshot 2024-03-06 at 16 00 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2b12c88d-a37a-4e10-ba18-ad2ee6cd7cef">
