### ISSUE TITLE
GROUP: Incorrect rights given to Member 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#929]
**What is the problem?**
Replicated on Google Chrome in Windows and Safari. When a user is invited to a Private Group via a share link with permissions set to "Member" (screenshot1, screenshot2) they are still able to "Invite members" (screenshot3) however, they get an error message after clicking the Send Invites button (screenshot4, screenshot5).

<img width="1024" alt="Screenshot 2024-03-03 at 17 58 04" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0c5a4d6b-9c7a-4265-b426-264a9d8101d8">

<img width="1236" alt="Screenshot 2024-03-03 at 17 45 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4518ee13-bdb6-4bf5-834e-6bb8053a272c">

<img width="1293" alt="Screenshot 2024-03-03 at 17 46 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6ddee210-c2a5-4d95-95e4-0b9b29da7410">

<img width="1291" alt="Screenshot 2024-03-03 at 17 46 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f9dd3e87-9a39-43aa-bbe2-36def4ddaac7">

<img width="1288" alt="Screenshot 2024-03-03 at 17 46 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d0641c73-bdf3-44a4-b2cb-5ba2e5c47b99">

**Why is this a problem?**
Group "Members" should not be able to invite others to a Private Group.

**Possible solution.**
The "Invite Users" feature should not be displayed for Members.

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the issue

**Comment by ssin1901** [comment]
@ilmartyrk fixed and closing (see screenshots)
<img width="1292" alt="Screenshot 2024-03-05 at 18 27 03" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a7772fb3-c40c-46bb-813c-0b8d2ccb5b8c">
