### ISSUE TITLE
VOTING: Hitting the previous step button causes the title to disappear

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#930]
**What is the problem?**

_Tested in Mac OS Safari_

When a User is in Preview Mode and clicks the button to go to the previous step and edit their voting choices (screenshot1) they are able to do so button the Continue button in voting preferences is now greyed out (screenshot2). 

Upon investigation, it finally came out that the previously inputted title (screenshot3) is now missing (screenshot4). 

<img width="1228" alt="Screenshot 2024-03-04 at 10 48 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7371a2c3-1142-4012-be63-1b1e8fd507a2">

<img width="1223" alt="Screenshot 2024-03-04 at 10 50 11" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b74602dd-fa8d-414a-ac28-6e2881bc0661">

<img width="1226" alt="Screenshot 2024-03-04 at 10 47 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/caf371a6-647f-454b-88ae-3933eec86e4a">

<img width="1240" alt="Screenshot 2024-03-04 at 10 48 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e78ae5ed-6098-4490-8555-4af3d49e60bd">

**Why is this a problem?**

Extremely inconvenient for the user because the previous step button takes them to voting preferences page where the Continue button is now greyed out. Essentially they are stuck and would likely abandon the process at this time.

**Possible solution.**
The previously inputted title should not disappear when a user clicks the previous step button.

**Comment by ilmartyrk** [comment]
@ssin1901 working on chrome, sent to Phase II

**Comment by ssin1901** [comment]
Issue is fixed in Safari as well and closing
