### ISSUE TITLE
Topics: UX issues with saving changes in edit topic flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#931]
**Insight from Round 1B (admin, mobile) testing**

Only from 1 user test so far (the only one who has tested this bit on mobile), but I also had this confusion myself, so think it's worth flagging for @kevincrepin to review :) 

User went into 'Edit topic' in order to edit her topic text. 

Once she had edited the topic, she was then getting confused by the UX of saving and continuing. Here's what she struggled with: 

- Confusing "double layer" (as she called it) of 'Save changes' but then also a next button (right arrow). So you have to (or feel like you have to) click: save then next, save then next. 
- When you get to the end of the 'next' buttons, you can only go back (left arrow). Doesn't feel intuitive - "I'm used to next, next, next, finish". (The final 'save changes' button closes the edit flow, so that is the 'finish' button she was looking for, but isn't clear that it is so.) 
- She had gone into edit her topic text, but then due to the 'Next' arrows was guided along into settings, which isn't where she wanted expected to be. She just was intending to edit her topic text, then leave that flow and go back to the topic.  
- The save button changes from dark blue to light blue when clicked. She guessed this might mean it was saved, but was unsure and left feeling uncertain that it had. 
- Later when she is in group create flow, she clicks next (same right arrow) but then fears maybe it didn't save, as there was no save button like she had got used to in the topic edit flow. She goes back to check if the group info (step 1) saved, as fears it was all lost, and sees that it did.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/224d8aef-1b09-44b1-b801-37aae4515c47)

Will just link a related bug issue [here](https://github.com/citizenos/citizenos-fe/issues/895) too, for info when considering - maybe all can be resolved at once. 

**Suggestion**

Was thinking maybe the save button being a 'Save and close' button would help - so then you only click it when you are done and want out. But I'm not sure if this would cause more confusion. 

Perhaps better is if the close button brings up a window with 2 options, 'Save changes' 'Don't save changes' (or whatever wording is standard)?  
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/26e3ea72-cfca-475c-866b-ad1b8e44f09f)

But I'm not sure either of these things quite fix it. Hopefully @kevincrepin has some brighter ideas!

**Comment by kevincrepin** [comment]
Understand it causes some confusion. I wasn't happy with that back arrow there on the right side like that either...

I'm thinking whether this could work. I would still keep the "double layer" because we can't fit everything and we'd need to hide things under an action menu. But I would separate the two from each other a bit more clearly with a divider line. And I would keep the right arrow also there, but disabled once you reach the end of the line. Then this back arrow doesn't feel so out of place like is the case now.

Lastly maybe we can rename to "save changes & publish" which is a more positive action than "close".

Below comparison of regular flow bottom actions and under it the "edit" bottom actions:

![Screenshot 2024-03-06 at 09 54 08](https://github.com/citizenos/citizenos-fe/assets/26792281/26675e20-279f-4519-ab5d-542a1136bb43)

**Comment by BeccaMelhuish** [comment]
Nice, this is good on mobile I think! Seems much clearer. And can keep an eye in future tests :) 

But @kevincrepin would you be able to review how it should be on desktop too - I find it a bit confusing there too for similar reasons (save then next, save then next, save), and there is also [this issue](https://github.com/citizenos/citizenos-fe/issues/895) connected to it (which is fixed in the mobile solution). 

Can we have a similar solution on mobile for desktop (but just on one level)?

**Comment by kevincrepin** [comment]
Can't log in right now, but I think this is how it could translate to desktop.


When creating a topic, we don't use the arrow fwd button (in design at least) we use "Continue" label. So we only have back arrow + save as draft + continue. In the last step you can't continue so the button label becomes "Publish".
![Screenshot 2024-03-14 at 14 01 07](https://github.com/citizenos/citizenos-fe/assets/26792281/88189b88-2125-4cd8-96d9-6b1ecef086b0)


Now when editing the topic it's a different flow (a bit) because it's less vital to go through this step by step. So I would say here we could rather use the arrows and have the "save changes & publish button" also always visible. In the last step then the arrow right can be disabled. And we don't have the "save draft" button here anyway so that's not relevant.
![Screenshot 2024-03-14 at 14 03 35](https://github.com/citizenos/citizenos-fe/assets/26792281/4584b987-11a6-40be-bc2a-e6a0c2f1d844)

**Comment by BeccaMelhuish** [comment]
Nice, thank you @kevincrepin! I think this is good, and might also solve another UX issue I was about to report - that when users go in to just 'Edit topic' they click continue but are not expecting it to take them to settings (as they only came there to edit the text). I will keep an eye in further tests, but I think this should be smoother :) 

Only question now is what to do about this connected issue [here](https://github.com/citizenos/citizenos-fe/issues/895)? 

Am I right in thinking that here, clicking 'Save as draft' will close the create or edit flow? (I think it should). As if so then in all cases the X on the left should close the create/edit flow _without_ saving whatever has been done, and there should still be the interrupt process pop-up (that's currently been removed) that says changes won't be saved?   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cc35fc7c-30e1-422f-a7ea-c11767db4781)

**Comment by kevincrepin** [comment]
I think save as draft is only there when creating, not when editing an already published topic. Yes to closing. And also yes to pressing the x to close should bring up the confirmation dialog :)

**Comment by BeccaMelhuish** [comment]
Ah yes, true! 

OK perfect, so just to clarify for Ilmar, though @kevincrepin please correct me if you disagree with where they should be taken after clicking: 

- The 'Save as draft' button (in 'create' flow) should close the flow and take the user to the dashboard. 
- The 'Save changes & publish' button (in 'edit' flow) should close the flow and take the user back to the topic. 
- The 'X' buttons in all cases should close the flow and _not_ save whatever they've done since they opened the create or edit flow, but only after they have confirmed via the 'Interrupt process' pop-up which includes the sentence about changes not being saved. In the create flow, after this they should be taken to the dashboard. In the edit flow, after this they should be taken back to the topic.

**Comment by BeccaMelhuish** [comment]
Reopening as not quite right - and some bits of this are high priority so will add the label as such :) 

1. On mobile, when creating a topic it's not as per the design (and rather messy/confusing now - I think users would have a real headache trying to figure this out): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a4fc1261-2a53-4c70-821c-37454fa86eec)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5be41d3f-d47a-41cc-bbc6-09215ba72dff)

@kevincrepin maybe we need designs for 'Steps' and 'End' of both create and edit flows on mobile too, should be clearer for @ilmartyrk then? :) 

2. When creating a draft topic on desktop it has the publish button from the edit flow (should just be 'Publish' in create flow): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/65cd38e1-6433-480d-98e2-3dd3fc4b8af0)

3. When you click the X, you get the 'interrupt process, changes won't be saved', but the changes are still saved. Anything they did since opening create or edit shouldn't be saved when they click this one (they need to have an option to not save changes): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/92382261-3c9b-467d-b579-d7657e231126)

4. When editing a draft topic on mobile, it looks like this rather than Kevin's design (below it (it's says create but as per his post above, is for edit flow)): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/02131a6e-1418-4463-b092-3c1b4283408b)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/29db6674-35a7-47a4-9d73-022f7312a39b)

5. This has made me realise we need another variation in the design from @kevincrepin - the flow for editing a draft and editing a published topic should be different - as when you are editing a draft you could either want to save it as a draft again or publish it, whereas when you are editing a published topic (presumably?) the only option is to publish it.

**Comment by BeccaMelhuish** [comment]
Found some more problems but will leave this one closed - have made separate issues for the remaining things now :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 Am moving this one to 'testing' as noticed it didn't go there, but Sara please note several new issues I made already for things that are either broken (the two high priority ones) or not quite matching design - the 7 issues from #1042, ##1043, #1044 (HP), #1045, #1046, #1047, #1048 (HP)

**Comment by ssin1901** [comment]
@BeccaMelhuish thanks for finding so many relevant issues! Currently #1045  #1046 and #1047 are still open but with no status, so I am not closing the issue but moving it out of testing (as the issues haven't been fixed and are currently not in the in progress column either).

**Comment by ilmartyrk** [comment]
@ssin1901 closing this issue as it only refers to others
