### ISSUE TITLE
Topics: In create flow, topic content vanished when invite co-creators

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#932]
This was quite a big bug that came up in mobile admin test, on Android on Chrome, so adding high priority tag: 

User was creating topic, at the settings stage decided to invite someone using this bit below (with email). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/27015c2d-64e1-4b16-af12-dd9075686bc5)

All looks good initially when she goes back to where she was (in settings step) after inviting them - what she had previously input was saved: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/de08f4d4-152f-4d3d-b381-b2bce6392eeb)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9b38f737-d4ec-460d-84db-95b2ae5f2221)

But then when going to Preview, everything is empty and there is no button to publish: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/018ebbe6-c3f0-40f5-888a-e2c574d52efc)

She tries going back to settings, and now everything is gone from there too: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0a04632a-1d94-44f6-8e9e-59ad7687454d)

We decided to delete and start again, after deleting (I think that's what she did) she gets this:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3f069efc-1c8f-428a-a0aa-c2ae0d38dcd5)

She then refreshes, and it all appears back and correct again (so no need to start again) :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c13f4d72-ea30-40f2-a317-de8152609b35)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a fix

**Comment by ssin1901** [comment]
Tested and working fine. Closing the issue.
