### ISSUE TITLE
Topic: Discussion and join bugs when joining a topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#934]
I had some bugs on my side (on desktop, Chrome) when playing the role of participant for an admin test. I don't have screenshots or strong recollection as I was in the middle of running the test, but I think from memory this is what happened: 

- User sent me a link to join her public topic
- I followed it, and I think there was the usual 'Join topic' pop-up which I think I accepted
- When I entered, I tried clicking the 'add an argument' button in the 'There is no discussion yet' box, but it didn't work. 
- Thought this might be as I somehow hadn't 'joined' and didn't have the rights (I think this wouldn't be the case though anyway, for a public topic?) 
- Noticed instead of 'Participant' at the top it said 'Join topic' so I joined via the join topic pop-up (again, I think I already had)  
- Still couldn't add an argument, so I refreshed. 
- Then I could add and all was well.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I could not replicate it, might have been some weird glitch
