### ISSUE TITLE
Follow-up: Edit follow-up not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#935]
In test on mobile, Android, Chrome, user click the 'Edit' in the menu of her follow-up update to try and edit what she had just posted, but it didn't work. She tried a few times.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/488ef508-004f-4e28-bd2f-d47b84620a45)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish we actually didn't support editing on the API side added the functionality

**Comment by ssin1901** [comment]
Fixed and closing
