### ISSUE TITLE
Discussion: Argument actions menu stays open while editing argument 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#936]
It should close once you have selected edit (or whatever else you have selected), otherwise it gets in the way of editing: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/fc96b408-8b39-44d4-9290-ebe6a945ea41)

On mobile (Android, Chrome)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Tested in Android on Google Chrome and Actions is no longer visible. Moving to Done.
