### ISSUE TITLE
Discussion: Code for bold and italic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#937]
At some point can we make it so that this just shows as whatever is selected (bold, italic, etc.) but doesn't show the code? 

(This is an argument, on mobile) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/9d5b1a4e-25de-4ff4-9cb6-e4787e9720ee)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by ssin1901** [comment]
Suitable fix implemented (See screen recording) and closing this issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/d46ae430-b9bb-47f2-bb9e-d1cd9e84d9ef
