### ISSUE TITLE
Voting: Can only find person to delegate with username not email

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#941]
Not sure if bug or UX, so putting both labels. 

I had this problem myself recently, and it came up in a test too. I tried to find the person I wanted to delegate to using their email address. The user in this test did the same. But it seems it only finds it if you type their username.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7b57f96e-accc-47a1-947e-1a01b8d8515c)

And even if you type the right email, the error message says 'you can only delegate to people who have access to this topic'. It doesn't recognise it at all. 

Can it be changed so you can use either, same as when you are inviting? Text would need to change if so.

**Comment by kevincrepin** [comment]
Both should be possible I think yeah. Should recognise the user according to username or mail.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin updated the member search to include email

**Comment by BeccaMelhuish** [comment]
@ilmartyrk tried it and it's great thanks! 

2 things though: 

Can we change the text to 'by their email or username' (top) and ' Search by email or username' (bottom):
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f9fb127d-5ca3-4592-9cb8-0c5782552aea)

And when I was typing in the email address it was really very jumpy - very hard to focus on it: 
https://www.loom.com/share/e3e7f070469d4b88b680ebf2e038edfc?sid=869dfbcc-87c2-4872-8d84-d3b7470a5dc1

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the texts and fixed the "jumpy" dropdown

**Comment by ssin1901** [comment]
Seems to be working and closing now (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/161bdfc1-3974-47e6-b89e-7f30eb73a5b4
