### ISSUE TITLE
Topics: UX for jumping to own country in dropdown on mobile 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#942]
Round 1B (mobile, admin) insights: 

On mobile, it's quite frustrating/time-consuming for users to have to scroll all the way down to their country in the country and language drop-boxes, especially if they are far down the list. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8fb9b6af-e20b-488a-b11b-9e569483d426)

Suggestions: 

On desktop there is the functionality that if you press 'I' for example, you get to the countries beginning with I. @kevincrepin what is good UX practice for the same situation on mobile?

**Comment by kevincrepin** [comment]
This is a tricky one. Only way I can think of is to have the option to search within the field – but this triggers the keyboard, obscuring part of the screen, and you'd have to type to start filtering out the countries. 

Not sure if this would be "better" experience than going through the dropdown... It would be more precise, but also demand more "complex" interaction...

We can consider having the search there and then both options still exist and it's up to the user to decide. @ilmartyrk we have a component like this that's suitable: 
![Screenshot 2024-03-06 at 10 25 42](https://github.com/citizenos/citizenos-fe/assets/26792281/adf3beeb-29d4-4dd7-9a42-ebf554d77999)

**Comment by BeccaMelhuish** [comment]
OK yes sounds good, we could try that and keep an eye on it :) 

But @kevincrepin one other idea that we could explore for Phase II: what do you think if the system recognised the users location or remembered what the user last entered, and that country displays at the top (above a little line before the alphabetical list begins)? This could also make it even smoother on desktop? 

If that would be technically possible of course, @ilmartyrk

**Comment by ssin1901** [comment]
Implemented the shortcut and I am now closing this issue
