### ISSUE TITLE
Discussion: make reference to info arguments the same colour everywhere? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#943]
**Round 1B (mobile, admin) insights:**

Was only one user, but for a while she was unsure 'what the blue argument' was for. She guessed maybe informational, but it took a while before she was sure of that. 

**Suggestions:**

@kevincrepin should we make it blue or grey in both places, as currently they are two different colours in these two different places - might be why she was unsure? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1ce1878e-61df-4d0c-9210-2bc47629788f)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3994c1a8-a624-4b36-ab6b-a800476e8a72)

**Comment by kevincrepin** [comment]
It should not have that blue :)
![Screenshot 2024-03-06 at 10 27 53](https://github.com/citizenos/citizenos-fe/assets/26792281/d7ca87d2-fcc1-46e9-80c3-5ea1c758f57a)

@ilmartyrk I see this is also in desktop the case, but not supposed to be like that. Not sure how it happened – hope we didn't discuss this at some earlier time and I forgot.
![Screenshot 2024-03-06 at 10 30 13](https://github.com/citizenos/citizenos-fe/assets/26792281/c6dd3f41-f22d-4377-9026-e89600c8ef60)

**Comment by ilmartyrk** [comment]
@kevincrepin yeah, my bad the design was probably meant for pinned argument
