### ISSUE TITLE
GROUP/TOPIC: User cannot "leave topic"

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#946]
**What is the problem?**

_Tested on Google Chrome, Mac OS_

A user has joined a group with Admin rights and accessed a topic within the group with Participant rights. When user clicks Leave Topic, user continues to receive notifications for said topic.

<img width="1282" alt="Screenshot 2024-03-05 at 15 53 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d3dac406-1b26-4678-a30f-3199d0959bee">

**Why is this a problem?**
User cannot "leave topic" 

**Possible solution.**
If the user has left the group, they should not receive group notifications for the topic even if they are a member of the group that the topic has been added to.

**Comment by ilmartyrk** [comment]
@ssin1901 this is as expected as user is member of the group that has permissions for this topic. We can discuss it in the latter stages so moved it into in-prep

**Comment by ssin1901** [comment]
Connected to #884

**Comment by ssin1901** [comment]
User no longer receiving notifications for topics that they have left
