### ISSUE TITLE
PROFILE: Old profile image not removed and new one not added

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#950]
**What is the problem?**
_Tested on Google Chrome_

Profile image (under 500kb) does not change despite success message (screenshot1) and does not get stored (screenshot2)

<img width="1288" alt="Screenshot 2024-03-07 at 22 59 50" src="https://github.com/citizenos/citizenos-fe/assets/72747107/67cd2cb9-a0de-4340-b49e-4743a1927381">

<img width="1288" alt="Screenshot 2024-03-07 at 23 01 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/53095b08-0ef1-43c5-b231-970a3ec74c5f">

**Why is this a problem?**

User cannot delete or update profile image

**Possible solution.**
User should be able to store, upload and delete profile image.

**Comment by ilmartyrk** [comment]
@ssin1901 I could not replicate the issue, did you upload an image and then also click save?

**Comment by ssin1901** [comment]
@ilmartyrk yes hit save and got the successful message as well (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/eff391c5-4528-45e6-9f9f-55306860ed95

Currently not working in Chrome.

**Comment by ilmartyrk** [comment]
@ssin1901 if you refresh it should have the new image, it is working for me on my pc and chrome, though it might be some cache related issue for you. I'll try and think about how to solve it

**Comment by ssin1901** [comment]
@ilmartyrk on Windows the picture updated after refreshing. The bigger issue was that the success message came when the profile was still the old one.

**Comment by ilmartyrk** [comment]
@ssin1901 the success message is correct, the picture not updating is related to the browser cache

**Comment by ilmartyrk** [comment]
@ssin1901 posted a  fix that should work

**Comment by ssin1901** [comment]
@ilmartyrk still not fixed, also tested it with a different account (see screenshot)
<img width="1299" alt="Screenshot 2024-03-12 at 12 04 12" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bd4e66cd-b846-463c-87e5-eca30181154f">

**Comment by ilmartyrk** [comment]
@ssin1901 looks really Mac specific issue it works for me on all browsers, sending to Phase II
