### ISSUE TITLE
TOPIC: Add attachment file size error not accurate

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#951]
**What is the problem?**
A user tries to attach a file size of 5.9 MB and gets an error message saying that only files under 50 MB are allowed (see screenshot)

<img width="1295" alt="Screenshot 2024-03-08 at 12 28 52" src="https://github.com/citizenos/citizenos-fe/assets/72747107/06aaa860-5b90-4c89-95bc-dbc7d2aa65af">

**Why is this a problem?**
User cannot take action based on incorrect information provided

**Possible solution.**
@ilmartyrk shouldn't it say 5MB?

**Comment by ilmartyrk** [comment]
@ssin1901 it was hardcoded as it is the limit on our live site, though made it changeable maybe we need to lower this limit

**Comment by ssin1901** [comment]
Now says 5MB which is reflected in the system performance (see screenshot)
<img width="1292" alt="Screenshot 2024-03-11 at 11 42 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fe09f788-c97a-4e9c-b757-adffadf86571">

**Comment by ssin1901** [comment]
See comment above
