### ISSUE TITLE
GROUP: Needed page refresh to display the Login

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#952]
**What is the problem?**

_Tested in Mac OS, Google Chrome_

When a user who was not logged used a link that was shared to them, instead of being prompted to login, they got this view (screenshot1). User needed to refresh the page to get the login popup.

<img width="1413" alt="Screenshot 2024-03-07 at 18 37 07" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1fd063e9-05c3-4ce2-8be5-2b7605e9de3e">

**Why is this a problem?**
Users might get stuck, as they won't assume a page refresh will fix the issue

**Possible solution.**
Login window should appear without page refresh

**Comment by ilmartyrk** [comment]
@ssin1901 I could not replicate it

**Comment by ssin1901** [comment]
@ilmartyrk did not come up in this round of tests. Closing this issue.
