### ISSUE TITLE
GROUP: Insufficient permissions error while accessing a public group

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#953]
**What is the problem?**
A logged in user got an error message saying insufficient permissions while trying to access a public group (screenshot1).

<img width="1431" alt="Screenshot 2024-03-07 at 19 23 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c2aa087c-f662-4f27-ab3d-f2f0a1d2b014">

**Why is this a problem?**
Confusing to the user

**Possible solution.**
Insufficient permissions error should not appear

**Comment by ilmartyrk** [comment]
@ssin1901 difficult to debug as I cannot replicate it, also it might have happened due to some other background thing

**Comment by ilmartyrk** [comment]
@ssin1901 I think I found the issue and it should now be fixed

**Comment by ssin1901** [comment]
@ilmartyrk when these Not Found/Insufficient permissions errors come, would it be helpful to send you the group or topic url that is responsible for the 404 error?

**Comment by ilmartyrk** [comment]
@ssin1901 yes, makes it easier for me to debug

**Comment by ssin1901** [comment]
@ilmartyrk I got an insufficient permissions error _in Chrome incognito mode_ after downloading machine-readable file in this topic https://app.citizenos.com/en/topics/2c8bb9e5-7486-421b-b268-4368e67cbba0#voting

When I used Network Recording the message disappeared and I got the Tour instead.

**Comment by ssin1901** [comment]
Got it with this one as well
https://app.citizenos.com/en/topics/da4ad617-4c0f-4200-858f-1be28ebc752c

**Comment by ssin1901** [comment]
@ilmartyrk similar issues have been created with the server error included. https://github.com/citizenos/citizenos-fe/issues/1064

I think this issue can be closed and we can focus on new instances of the same issue.
