### ISSUE TITLE
TOPIC: Mismatch between inline image in Editing and Preview/Published View

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#958]
**What is the problem?**
_Tested in Google Chrome_

The scaled down version in the Editing view (screenshot1) does not give the user any indication that the image will be resized and hidden in the Preview/Published view (screenshot2)

<img width="1098" alt="Screenshot 2024-03-09 at 14 47 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b54c9026-78ec-48e2-b0a9-00f86432057d">

<img width="1097" alt="Screenshot 2024-03-09 at 14 47 26" src="https://github.com/citizenos/citizenos-fe/assets/72747107/0bd4a182-d051-46f9-a68d-8567237ffc7f">

**Why is this a problem?**
Users not happy with how the image looks

**Possible solution.**
Low priority in this phase because Preview shows the user what it will look like before it is Published.

**Comment by ilmartyrk** [comment]
@ssin1901 was a quick fix
