### ISSUE TITLE
GROUP: Search for Members does not work

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#961]
**What is the problem?**
In Groups, searching for members does not work (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/bd33da15-538e-4bbb-a080-8cde8896621a

**Why is this a problem?**
Problem when there is a large number of members

**Possible solution.**
If a user types Sa ... then a list of users whose names begin with Sa should appear

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix

**Comment by ssin1901** [comment]
Fixed (see screenshot)
<img width="1297" alt="Screenshot 2024-03-11 at 18 06 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bdcd1426-65bc-4974-9871-b57ed4ea0562">

**Comment by ssin1901** [comment]
Closed due to comment above
