### ISSUE TITLE
TOPIC/VOTING: Disappearing title breaks functionality

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#962]
**What is the problem?**
_Tested in Google Chrome_

The user entered a title but it disappeared and then the user was unable to publish the voting topic without entering the title. New title also did not get saved (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/9ce0a918-0c5b-4ced-8079-89e5ca2eca67

Also screenshots (screenshot1, screenshot2, screenshot3)

<img width="1293" alt="Screenshot 2024-03-09 at 15 10 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/dce69977-cabd-40ee-9c09-983421f56a49">
<img width="1292" alt="Screenshot 2024-03-09 at 15 09 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/abaedf87-b247-4add-a22c-7a59067674af">
<img width="1291" alt="Screenshot 2024-03-09 at 15 09 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a436e752-eacf-4df7-9749-05781a3cbb26">

**Why is this a problem?**
High priority because the user cannot take any further topic action without inputting the title

**Possible solution.**
Title should be stored correctly. @ilmartyrk this might be related to users needing to click Continue on each section but that is not at all clear to the user.

**Comment by ilmartyrk** [comment]
@ssin1901 found the issue and fixed it

**Comment by ssin1901** [comment]
@ilmartyrk I think it fixed. Will open a new issue if it occurs again
