### ISSUE TITLE
Topic: Tooltip for attachments info

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#963]
@kevincrepin, in [this issue](https://github.com/citizenos/citizenos-fe/issues/353#issuecomment-1916481855) Anett suggested a tooltip with the info about attachment file size limits etc. Seems a good idea to me (I remember it was an FAQ previously) - do you agree?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the tooltip

**Comment by BeccaMelhuish** [comment]
@ilmartyrk thank you! 

Can we call it 'Attachment guidelines' instead?  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b09dfea7-f1ad-4db8-a29b-3dfb58d7b57e)

And this is the HC text we had for attachments below - was 50MB incorrect then? 

Do we still have a maximum of 10 files? Let's add if so:
"Up to 10 files can be added"  

And there are some funny looking (very unfamiliar to me) file types in the list above - I think the list below is the ones that users are more likely to be familiar with? 

- The maximum size of a single attachment in a topic is 50 MB.
- A maximum of 10 files can be attached to one topic.
- Acceptable file types are: txt, pdf, doc, docx, ddoc, bdoc, odf, odt, jpg, jpeg, img, png, rtf, xls, xlsx, ppt, pptx, pps, xlt.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish all the numbers and file types are not hardcoded to the translations, for testing environment the limit is 5MB, acceptable file type extensions are in the list I created as actually the check is based on the files mime-type eg. for .txt file it is "text/plain" etc.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk just reopening as it's still 'params' rather than 'guidelines'. (I think params is more tech-speak, I've not come across it before) :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish made the change in translations

**Comment by ssin1901** [comment]
Implemented and moving to Done
