### ISSUE TITLE
Discussion: Hover over reactions number should be a hand

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#966]
Currently it's just a cursor when you hover over these, but should be a hand to show that you can click: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/db106cd3-8b2f-4068-b61f-4f0418086c2b)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish made them into buttons

**Comment by BeccaMelhuish** [comment]
Perfect, checked and looks good :)
