### ISSUE TITLE
Groups: Private group public topics 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#970]
A bit of a vague and uncertain one sorry, but here's what happened/might have happened:  

I made what I thought was a public group, for @ssin1901 to use as part of a scenario in user tests. 

It's possible that I made it private to begin with, meaning to make it public later. But I think I did make it public from the start (maybe Ilmar can check? It's the 'Yourtown 2030 Visionaries' one. I can't see that far back in my AF). Unfortunately it is a couple of weeks ago now, so I can't remember exactly. 

Sara today showed me that the group is actually private. I was confused about this, as I thought I'd made it public, and the topics within it had been showing up as public topics in my own user tests. 

I now see that the topics are public, but the group is private. 

So there are either 1 or 2 problems, depending one whether I made a private or public group initially: 

1. It shouldn't be possible to have public topics in a private group. That one's for sure, but already discussed [here](https://github.com/citizenos/citizenos-fe/issues/752) for Phase II. 
2. If I did make the group public in the beginning, did it somehow get changed to a private group without me or Sara doing so? Or did the system make a private group, when I had selected public?  

Probably just be something to keep an eye on though. May well just be 'user error' on my part!

**Comment by ilmartyrk** [comment]
@BeccaMelhuish checked the activity feed from database and the group was created as private
