### ISSUE TITLE
LOGIN: Error message flashed while resetting password 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#972]
**What is the problem?**
_Tested in Google Chrome_

After a user has inputted a new password, some kind of message seems to flash (see screen recording)
https://github.com/citizenos/citizenos-fe/assets/72747107/6dea5295-1935-4b36-a859-e0efa3ffdfc4

**Why is this a problem?**
Very distracting for the user 

**Possible solution.**
No error message should flash

**Comment by ilmartyrk** [comment]
@ssin1901 it was actually the success message
