### ISSUE TITLE
TOPIC TOUR: Activity feed and Favourite incorrectly in tour section which points to Manage

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#974]
**What is the problem?**
In Topic Tour, the Topic actions include Activity Feed and Favourite under Manage (screenshot1), when Topic Activity and Pin Topic are located above Manage (screenshot2)

<img width="1293" alt="Screenshot 2024-03-11 at 22 18 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/32dcc1c3-ae93-4aec-860b-5864a7f635e0">

**Why is this a problem?**
<img width="1292" alt="Screenshot 2024-03-11 at 22 21 39" src="https://github.com/citizenos/citizenos-fe/assets/72747107/dbfa9d22-ac44-4f0a-bb48-f816a1217bfb">

Confuses the users

**Possible solution.**
Activity feed and Pin Topic should not be included in the Topic Actions section. Ideally, it should have its own section like in Onboarding.

**Comment by ilmartyrk** [comment]
@ssin1901  @BeccaMelhuish if we move these items to new tour item then what should its title be. The change I would make is that from the current item I would remove Activity feed and Favorite and I would also remove the three dot icon for More button and change the text "More" to "Manage". But for the other items would it makes sense to create new tour item with title Topic Interactions and move activity feed and favorite in there ´
![Kuvatõmmis 2024-03-12 111009](https://github.com/citizenos/citizenos-fe/assets/19904307/a9a2af01-b280-4dd0-8360-f0ced2fedafa)
![Kuvatõmmis 2024-03-12 111107](https://github.com/citizenos/citizenos-fe/assets/19904307/02337550-d8bd-4bd4-a663-a864dcbe941f)

**Comment by BeccaMelhuish** [comment]
Very good point @ssin1901, we moved the items but didn't update the tour! 

@ilmartyrk I agree with your suggestions! 

'Topic interactions' is a bit of a funny title for the AF and favourites, but I can't think of anything better that covers both.. Maybe @kevincrepin has ideas, but for now I think we could stick with this? 

Visually, just needs a little gap under that heading :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the gap

**Comment by ssin1901** [comment]
Uploaded video in Slack, closing the issue as it looks fine to me. Will reopen if there are any new insights.
