### ISSUE TITLE
Change our date format

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#98]
Original in [fe-old](https://github.com/citizenos/citizenos-fe-old/issues/507)

**What is the user story?**
As a user, I want to clearly and quickly understand dates. Right now, dates are in the strange US mm/dd/yyyy format across the system.
![us_dates](https://user-images.githubusercontent.com/22661743/82597163-380b4200-9bb1-11ea-9314-ad6c9a266101.jpg)

**What is the requested feature?**
Either make the date format follow the geo-IP (or UI language?) or change it to international date format (https://www.w3.org/QA/Tips/iso-date).

**Additional information.**
Maybe @oksks has input on this.

**Comment by ssin1901** [comment]
@ilmartyrk seems to be in ISO 8601 format now (see screenshot).

<img width="714" alt="Screenshot 2024-02-19 at 13 52 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/38055577-7e15-41ec-86b7-5af82b766567">
