### ISSUE TITLE
GROUPS: Incorrectly marked compulsory fields marked in Group 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#980]
**What is the problem?**
When a User is creating a Group, the asterix incorrectly indicates that Name, Description and Uploading an Image are compulsory (screenshot1) when it appears that only Name is compulsory (screenshot2)

<img width="1290" alt="Screenshot 2024-03-13 at 13 50 05" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ee6f3d0e-e7df-4a57-8c78-e4f65abcb662">
<img width="1302" alt="Screenshot 2024-03-13 at 13 52 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b37e410a-a697-4da0-9f48-e63bf6bc1823">

**Why is this a problem?**
It is a generally a good idea for topic creators to include Name, Description and Image because (as indicated by a user in the usability test) it makes it much easier to find and understand groups.

**Possible solution.**
1. If we decide to make the 3 fields compulsory a) each missing field should be highlighted b) user should not be able to go to the next section without completing all the fields

2. If only Name and Description are compulsory, a)each missing field should be highlighted b) user should not be able to go to the next section without completing all the fields c) asterix should be added to Name and Description and removed from Group

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish  changed the view a little, hopefully the section titles are OK

**Comment by ssin1901** [comment]
@ilmartyrk looks okay to me, closing the issue (see screenshot). We can open a new issue for UI/UX if Becca or Kevin have suggestions.
<img width="1290" alt="Screenshot 2024-03-13 at 17 08 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3fbb2b4b-a1a0-430f-8481-de395e3d6dc8">
