### ISSUE TITLE
Activity Feed: Same notification showed up multiple times 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#989]
**What is the problem?**
In the Activity Feed, the same notification showed up multiple times (see screenshot)

<img width="1440" alt="Screenshot 2024-03-14 at 11 37 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/a6d597a4-0bbc-4a5f-a6c1-b08c2b309692">

**Why is this a problem?**
Makes it harder to use the Activity Feed

**Possible solution.**
Same notification should show up only once

**Comment by ilmartyrk** [comment]
@ssin1901 closing this issue as this was actually caused by adding topics to group flow error, related with the issue where many invite e-mails were sent out.
