### ISSUE TITLE
Groups dashboard - topics and users display issues

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#99]
@ilmartyrk @anettlinno  Seems like something is up with the way that topic rights etc are displaying for groups? (i.e. some have drop-downs and "bin" icons, and some don't). Initially I was thinking this was due to whether or not I have admin rights, but seems not to be consistent: 

![image](https://user-images.githubusercontent.com/61320526/228001399-0bb8ea19-7e36-48fe-827d-556eb4ebdac6.png)

**Comment by BeccaMelhuish** [comment]
Actually, @ilmartyrk it seems all of my groups are currently displaying "Users: 0"...

**Comment by BeccaMelhuish** [comment]
Ah, now I clicked on "view" for one of them that was showing as "0", and it then displayed the correct number, and did the same for all the other groups.. Strange! 

![image](https://user-images.githubusercontent.com/61320526/228002979-a14f33ef-e9cf-41b0-a4f2-cba0b161d6a4.png)

**Comment by BeccaMelhuish** [comment]
Another example of the display inconsistency, this time with the COS public group:

![image](https://user-images.githubusercontent.com/61320526/228004095-0d79f48f-53e5-434c-8175-1eba226bdcf6.png)

**Comment by BeccaMelhuish** [comment]
On the users issue, I just refreshed the dashboard and now all my groups are showing 0 topics, 0 users... E.g. this, and it is the same for all of them: 

![image](https://user-images.githubusercontent.com/61320526/228010748-e128e5b0-73a9-47d0-a4c3-3575b6678547.png)

**Comment by BeccaMelhuish** [comment]
And now after searching for someone in the search, the very same list shows "20" not "37":

![image](https://user-images.githubusercontent.com/61320526/228011559-8352bea1-05e9-4a7e-b3de-61ec560627da.png)

**Comment by anettlinno** [comment]
I quickly tested and it works for me. Will send it to testing for @ssin1901

**Comment by ssin1901** [comment]
@BeccaMelhuish I could not replicate the issue on Safari or Chrome (MacOS). I noted that if you have admin rights then you (rightly) see the option to change other participants rights via dropdown, but when you don't then you just see plain text.

I think some alignment things were recently fixed, this issue was probably resolved after the cache was cleared.

@anettlinno @ilmartyrk

**Comment by anettlinno** [comment]
Thanks @ssin1901 for testing the issue. Closing the issue with no further action as we could not replicate this any more.
