### ISSUE TITLE
Topics: Drafts not showing up in my topics with 'All' filter

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#991]
When I go to my topics, my draft topics don't show: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3dc36a3f-d6fa-4f7b-849a-0b17cf2d1076)

They only show when I filter status to drafts: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3d089276-4fa4-4738-9189-9d523c35558d)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish they are on another page, topics are by default ordered by status long time ago we decided that voting topics are most important as they might have deadline
