### ISSUE TITLE
IS: Invite email missing participants and latest activity

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#992]
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/08d64417-24e6-489d-b73b-38938233a83e)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk have re-opened and moved this to testing as spotted it skipped that :)

**Comment by ssin1901** [comment]
Seems to be fixed (see screenshot) and closing.
<img width="1032" alt="Screenshot 2024-03-27 at 17 48 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bfeb2f22-6e39-4424-a159-0018c1c83060">
