### ISSUE TITLE
Discussion: Red error message too early in argument explanation field

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#994]
Same as [this issue](https://github.com/citizenos/citizenos-fe/issues/993), literally as soon as you click in the box to write your explanation, you get an error message. Should only appear if you try to click the greyed out button without adding something, or not at all. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5e491218-29de-497d-9090-ae237482b191)

**Comment by ssin1901** [comment]
Seems to be working (see screen recording). Closing the issue.

https://github.com/citizenos/citizenos-fe/assets/72747107/688c199f-afb9-4558-8cc9-0adaa4d55dbc
