### ISSUE TITLE
Help: Red error message too early in message field 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#995]
Same as [this issue](https://github.com/citizenos/citizenos-fe/issues/993) again, as soon as you click in the message box, you get an error saying your message is missing. Should only appear if you try to click the greyed out button without adding something, or not at all.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/72f9f08d-1fdf-4bd0-8a8c-0e399f96dff6)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish it was a general error for form validation that  I hadn't used properly, did some research and fixed it in all the places I used it so that error trigger only after interacting with the field
