### ISSUE TITLE
Discussion: Confusing eye icon that doesn't seem to do much

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#997]
Haven't noticed this eye before, when I click it it just turns the box a little greyer. Is it meant to be there and if so what is it meant to do? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b8aa5334-de86-4fac-a9d8-a64bc0ac5c9c)

**Comment by ilmartyrk** [comment]
Fixed with https://github.com/citizenos/citizenos-fe/issues/983

**Comment by BeccaMelhuish** [comment]
Rather than having the eye to preview the bullet points as they will look (that's the only this I can see that looks different in preview, but may be wrong?), could we just have the bullet points formatted as they will be straight away, and then not have the eye icon? Can be a Phase II thing though.. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a4521674-1959-429c-9190-2ffb52daabdd)

**Comment by ssin1901** [comment]
Minor UI fix. Closing this and we can create a new issue if needed.
