### ISSUE TITLE
Discussion: 'Not found' when trying to post a reply 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#998]
When trying to post a reply, I got this, and it wouldn't post. I think it was just after doing [this](https://github.com/citizenos/citizenos-fe/issues/996), so may be connected (and therefore may be low priority, as unlikely to happen often)? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bcc1fb8f-5554-410e-8311-0eedc6ba10c0)

**Comment by BeccaMelhuish** [comment]
I tried closing with this X, and closing the notification, and then pasting it in to try again, but got the same problem: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2fffeb82-3c81-42ff-a94e-c1e467793f9c)

**Comment by BeccaMelhuish** [comment]
Ohh I see why now, the argument had since been moderated: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f95eee58-5d9c-4120-9a6f-fc2fbe6437d4)

So will tag this Phase II and hopefully we can work out the UX for when that happens when we do the moderation review?

**Comment by BeccaMelhuish** [comment]
When viewing the moderated comment I see that it had actually posted my reply 7 times! Which is presumably the number of times I tried clicking the 'Post reply' in the various attempts. 

Should it be possible to reply to a moderated comment? Again something for the moderation review when we come to it. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4b7b8f1c-c29f-40f1-9d07-5c7be840e13f)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is a rare case and difficult to post a fix. I guess it won't become an issue if and when we decide to add live syncing of arguments, but wont fix for now.
