### ISSUE TITLE
TOPIC: Moderated argument error message shown 2x

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#999]
**What is the problem?**
After moderation, this is the message I see:

<img width="587" alt="Screenshot 2024-03-14 at 13 57 17" src="https://github.com/citizenos/citizenos-fe/assets/34126353/066e1b79-4d32-447a-abc1-aaa297c4fc7e">

**Comment by oksks** [comment]
@ilmartyrk doesn't seem to be fixed, just checked..

**Comment by ilmartyrk** [comment]
@oksks it takes some time to deploy to heroku usually ~5 mins. If I add the issue link to the commit message with prefix FIX github will autoclose the issue and after that I usually add a comment if it is a bigger issue, but even by the time I have added my comment the code might not yet be deployed to heroku
